### ISSUE TITLE
Clicks in plot pane arrows are processed very slowly

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#10024]
**Steps to reproduce:**
* Generate two separte plots so that the plot panel would have arrows.
* After generating the second plot, click the back arrow in the plot pane.
* After being switched to the earlier plot, double or triple click the forward arrow in the plot pane quickly.

**Expected results:** should switch to the last plot without issue.

**Actual behavior:** the clicks are not processed fast enough and I am presented with an error message "Invalid plot index" for each additional click past the number of available plots, and same in reverse when clicking the back arrow.

**Setup:** RStudio 2021.09.0 Build 351, R 4.1.1, running on debian sid.

**Comment by ronblum** [comment]
@david-cortes Do you know if this is new behavior in 2021.09.0+351, or was it a problem in earlier version of the IDE? Thanks!

**Comment by david-cortes** [comment]
Don't remember. I think it used to be slow to switch before, but it didn't throw errors about switching past the number of available plots.

**Comment by mikebessuille** [comment]
Duplicate of https://github.com/rstudio/rstudio/issues/7161 - but that one is closed (stale).  This is not a new problem. The problem here is that the 2nd click on the arrow happens before the arrow is greyed out, when it's at the end of the list of plots.  However, I don't think this is a critical enough bug to gain our attention given the number of more pressing issues, so I'm closing this.
