### ISSUE TITLE
Keyboard Shortcuts Not Functioning WITHIN R Projects

### ISSUE THREAD

**Issue by CDCStatistician** [rstudio/rstudio#10041]
I have been experiencing an issue where certain keyboard shortcuts are not functioning in R Studio Projects, but they work in code outside of a Project.  For example, the Ctrl+Shift+M keyboard shortcut assigned to the "insert pipe operator" shortcut will not work when used in the code editor in a Project (but it works fine in code that is newly created outside of a project). 
I have read other posts by users who have reported conflicting software installed such as AMD Radeon or Webex, but I do not have these installed or any other software that I can find that would override the shortcuts.  

I am running version R Studio 2021.09.0 Build 351, with R Version [64-bit], Version R-4.1.1.

**Comment by ronblum** [comment]
@CDCStatistician Thank you for raising this!
- Is this for RStudio Desktop or Server?
- What operating system are you running on
- If you're using RStudio Server, what operating system and browser are you connecting from?
- Did you use a previous versions of RStudio, and if so, did it work there?

Thanks!

**Comment by HeywoodCode** [comment]
I am having the exact same problem. I'm running RStudio desktop.

**Comment by galuardi** [comment]
Same here. 
RStudio
Version 1.3.1056
R version 4.0.2 (2020-06-22)

**Comment by HeywoodCode** [comment]
Same here. Desktop version (not server)
RStudio
I even installed R version 4.1.2 that just came out. 
Any ideas on how to fix it? I can't type out the pipe operator anymore! That's way too time-consuming.

**Comment by galuardi** [comment]
**another update:** after a reboot, everything works fine again.. like @mikebessuille alluded, it could be a keyboard shortcut conflict from another program.. anyway, all good again!

**Comment by CDCStatistician** [comment]
I've rebooted several times with no luck.  @ronblum.  I'm also running a recent version of R and R Studio Desktop.  I'm operating on Windows 10 Version 1809 OS Build 17763.1935.

**Comment by HeywoodCode** [comment]
I have the latest version of R/RStudio. My computer is Windows 10 on a X1 think pad , only a year old. I am still having the same issue.

**Comment by mikebessuille** [comment]
@CDCStatistician thanks for the extra info.  Do most of your shortcuts work?  Is it just Ctrl-Shift-M that doesn't?  Not asking you to do a full inventory of all shortcuts!!! :). just trying to determine how large a subset and if perhaps there is some commonality (all shortcuts that use ctrl-shift, for example...)

**Comment by CDCStatistician** [comment]
> Is this issue still out there?

This is no longer for an issue for me.  I determined that this issue only seemed to be present in a particular project.  Once I closed out of the project, this issue has disappeared.  I just ended up re-creating the project from scratch and this resolved it.  I could never find the appropriate project setting that would change this behavior, and I literally tried dozens and dozens of things.

**Comment by dbkoh1** [comment]
Since I don't see the answer posted already, this is what solved the problem for me:

AMD Adrenalin uses many of the same hotkeys as R-studio by default (ctrl+shift+m and ctrl+shift+c for example).  If you open have an AMD graphics card, you can open Adrenalin by right clicking its icon in the dock, click the gear icon for Settings in the top right of the Adrenalin window, navigate to the Hotkeys submenu, then either unbind/rebind the specific shortcuts, or disable "Use Hotkeys."

**Comment by stevencarlislewalker** [comment]
I got the same thing for a single project on macOS 11.6.1 and RStudio Version 2023.12.1+402 (2023.12.1+402).  Reboot has apparently solved it.

**Comment by razorofockham** [comment]
I have been having the same issue lately with one of my projects. Specifically, upon creating the project, the latter would inherit all shortcut customizations I had previously made in RStudio (while not working on a project). However, after closing and reopening the project in question, some (but not all) of the customizations would be gone.

The only solution I could find was deleting the ```.Rproj.user``` folder before restarting the project, which would indeed recover the customized shortcuts (at the expense of losing all my open tabs). However, after a few more times closing/re-opening the project, the issue comes back, always affecting the same customized shortcuts (CTRL + D and CTRL + SHIFT + D, which I swap to have CTRL + D duplicate selection and CTRL + SHIFT + D delete the current line) .

I also checked and this does not happen for other projects. I am currently using RStudio 2025.05.1+513 "Mariposa Orchid" on Windows 10.

Thanks for any help you can provide!
