### ISSUE TITLE
.rs.secureDownloadMethod() needs to stop using wininet for newer R

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#10163]
R 4.2.0 has deprecated the use of the "wininet" download method, as per:

https://github.com/wch/r-source/commit/f8f705fe994ee163919d6246af3ae8c48440c65f

We try to force the use of "wininet" here:

https://github.com/rstudio/rstudio/blob/06e7d7d1f2106c295e96126a2da979afbf7b1acf/src/cpp/session/modules/SessionPackages.R#L1324-L1335

For R 4.2.0 and newer, we'll probably want to prefer using "libcurl" (but we should verify that certificates are now properly checked, as per the associated code comment).

**Comment by mikebessuille** [comment]
@kevinushey do you know if the deprecated method will still work in the short term?  What's the urgency of this?

**Comment by kevinushey** [comment]
I believe it will continue to work through the R 4.2.x release; my guess is it will be removed in R 4.3.0 (but hard to know for certain).

**Comment by yutannihilation** [comment]
I see this warning every time I `install.packages()`, which feels a bit annoying. So, if possible, I think this should be switched before the actual release of R 4.2.

```
> install.packages("remotes")
Installing package into ‘C:/Users/Yutani/AppData/Local/R/win-library/4.2’
(as ‘lib’ is unspecified)
Warning in install.packages :
  the 'wininet' method is deprecated for http:// and https:// URLs
trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.2/remotes_2.4.2.zip'
Content type 'application/zip' length 398825 bytes (389 KB)
downloaded 389 KB

package ‘remotes’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\Yutani\AppData\Local\Temp\RtmpSkAPDe\downloaded_packages
```

**Comment by jgutman** [comment]
To test using R-devel (4.2) on Windows. Ran `install.packages("remotes")` and verify that package installed successfully, and warning message that was previously there is no longer there. Package installs should also be successful on Windows with non-development versions of base R

**Comment by kevinushey** [comment]
It's also worth confirming that one can change the download method back to "wininet" if required, e.g. via `options(download.file.method = "wininet")` either run in the console or (perhaps) in `~/.Rprofile`.

**Comment by ronblum** [comment]
Verified with RStudio 2022.02.0+367 in Windows 10 by installing `magrittr`.
1) Checked the error message goes away with R 4.2.0 (R-devel).
2) Checked that installation with other versions of R (4.1.2 64 bit and 3.6.3 32 bit) succeeds.
3) Checked that setting the option above reverts to `wininet`, judging by the return of the warning message.

**Comment by hsbadr** [comment]
JFYI. I get this warning on R-devel and RStudio `2022.06.0 Build 15`. It doesn't happen in the R console. See https://github.com/r-lib/remotes/issues/687.

**Comment by jgutman** [comment]
Please try one of the RStudio dailies 2022.02.0 from  https://dailies.rstudio.com/
This fix was added very recently, and may not have been added to the 2022.06.0 build

**Comment by hsbadr** [comment]
Thanks @jgutman! I've been running into this with RStudio dailies 2022.02.0; just installed from the 2022.06.0 branch today. Happy to re-test if you wish. I'm currently setting `options(download.file.method = "auto")` in `.Rprofile` as a workaround.

**Comment by yutannihilation** [comment]
I don't see the warning on RStudio 2022.02.0 Build 368 (which I installed a day after this got merged).

**Comment by hsbadr** [comment]
> I don't see the warning on RStudio 2022.02.0 Build 368 (which I installed a day after the fix got merged).

Confirmed. This issue is fixed on RStudio `2022.02.0 Build 374`, but not on RStudio `2022.06.0 Build 15`.

**Comment by ronblum** [comment]
@hsbadr Thank you for following up, and even checking in Spotted Wakerobin 2022.06!

**Comment by jgutman** [comment]
Thanks for confirming, that is expected. The 2022.06 builds do not yet contain all changes included in 2022.02, and this fix has not been merged into the 2022.06 branch yet. It will eventually, but for now we'd recommend using the 2022.02 daily builds to get the latest upcoming changes, until 2022.02 is released.

**Comment by atocharnaud** [comment]
Hi,

We are running R on Windows. Access to the internet is controlled by a security proxy doing deep packet inspection. I couldn't get our certificates to be accepted by commands like download.file or install.packages which are now relying on libcurl rather than wininet even after setting 
`CURL_CA_BUNDLE=c:\temp\OECDPKIG2PEM_All.txt`

```
download.file('https://cran.rstudio.com/bin/windows/contrib/4.2', destfile =$
trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.2'
Error in download.file("https://cran.rstudio.com/bin/windows/contrib/4.2",  :
  cannot open URL 'https://cran.rstudio.com/bin/windows/contrib/4.2'
In addition: Warning message:
In download.file("https://cran.rstudio.com/bin/windows/contrib/4.2",  :
  URL 'https://cran.rstudio.com/bin/windows/contrib/4.2': status was 'SSL peer certificate or SSH remote key was not OK'
```

Could you confirm R 4.2.0 implementation of libcurl on windows does properly honor the CURL_CA_BUNDLE environment variable ?

Merci

Arnaud Atoch

**Comment by yutannihilation** [comment]
@atocharnaud 
The error probably indicates you are trying to access to Internet *without* proxy, which I guess is not allowed in your network. Since it's libcurl, you need to set `HTTPS_PROXY` envvar properly.

**Comment by atocharnaud** [comment]
> @atocharnaud The error probably indicates you are trying to access to Internet _without_ proxy, which I guess is not allowed in your network. Since it's libcurl, you need to set `HTTPS_PROXY` envvar properly.

Thank you. HTTP_PROXY and HTTPS_PROXY are properly set as both commands below are working:
download.file('http://cran.rstudio.com/bin/windows/contrib/4.2', destfile = "test")
download.file('https://cran.rstudio.com/bin/windows/contrib/4.2', destfile = "test", method = "wininet")

**Comment by yutannihilation** [comment]
Hmm, then I have no idea. Sorry for the noise... This might not be the right place to ask since it sounds not a problem on RStudio's side but on R itself, btw.

**Comment by jgutman** [comment]
Can you confirm if you get the same issue when running R 4.2.0 in a terminal, not using RStudio? This may be a shortcoming with R itself, but I can see if there's a possible workaround for RStudio -- the best way forward would likely be an issue with R-core though

**Comment by jgutman** [comment]
We have no control over what changes the R-Core team chooses to make in the R language. You can still use wininet method  by setting `options(download.file.method = "wininet")`, but you will receive a deprecation warning when doing so.

**Comment by wurzerj** [comment]
I face the same issue. In our corporate setting a tool named Netskope (https://www.netskope.com/, https://en.wikipedia.org/wiki/Netskope) is analyzing web traffic. It also monitors https traffic and introduces its own SSL certificate, which is more or less "overwriting" the original SSL certificate (almost like man-in-the-middle). The certificate is accepted, since the respective CA is added to the client.

Within the current libcurl implementation in R 4.2.0 and 4.2.1 this causes troubles, despite libcurl on a Windows machine uses the Windows certificates via Schannel. In such a setting typically the SSL certificate revocation check will likely fail (at least in our case), since the current libcurl settings are pretty strict and do not allow to either disable SSL certificate revocation, or a "best effort revocation check" (see https://curl.se/libcurl/c/CURLOPT_SSL_OPTIONS.html, options CURLSSLOPT_NO_REVOKE and CURLSSLOPT_REVOKE_BEST_EFFORT),. Thus R can not communicate with anything via https.

The "issue" sits within src/modules/internet/libcurl.c. I'll open a bug report. The R team from my perspective should either consider enabling CURLSSLOPT_REVOKE_BEST_EFFORT as default (I believe most browsers handle it this way), or let the user configure CURLSSLOPT_NO_REVOKE and/or CURLSSLOPT_REVOKE_BEST_EFFORT via an environment variable, similar to CURL_CA_BUNDLE.

**Comment by yutannihilation** [comment]
Just noticed the fix is commit to R-devel. Thanks @wurzerj!

https://github.com/wch/r-source/commit/f1ec503e986593bced6720a5e9099df58a4162e7 (tl;dr: now we can set `R_LIBCURL_SSL_REVOKE_BEST_EFFORT` envvar to `TRUE`)

**Comment by kevinushey** [comment]
@mabuimo: unless I'm misunderstanding, it seems like these would be issues specific to the `devtools` and `remotes` packages, not RStudio?

In any event, I think our current recommendation is to use the default "libcurl" download method if possible (with `http_proxy` set if a proxy is required), and "wininet" if not (e.g. because you require the default Windows proxy settings).
