### ISSUE TITLE
Debounce builds to reduce AWS cost

### ISSUE THREAD

**Issue by mikebessuille** [rstudio/rstudio#10171]
From Jonathan:  We build on commit extremely aggressively, so a flurry of commits can trigger multiple builds. if we debounced the builds by even 30-60 minutes we'd probably do a lot fewer of them.

**Comment by zachhannum** [comment]
I think we can do this with Jenkins' Quiet Period option:

> When this option is non-zero, newly triggered builds of this project will be added to the queue, but Jenkins will wait for the specified period of time (in seconds) before actually starting the build.
For example, if your builds take a long time to execute, you may want to prevent multiple source control commits that are made at approximately the same time from triggering multiple builds. Enabling the quiet period would prevent a build from being started as soon as Jenkins discovers the first commit; this would give the developer the chance to push more commits which would be included in the build when it starts. This reduces the size of the queue, meaning that developers would get feedback faster for their series of commits, and the load on the Jenkins system would be reduced.
\
If a new build of this project is triggered while a build is already sitting in the queue, waiting for its quiet period to end, the quiet period will not be reset. The newly triggered build will not be added to the queue, unless this project is parameterized and the build has different parameters than the build already in the queue.

**Comment by cm421** [comment]
Quiet period doesn't quite do what we want, because it will wait for the specified period and _then_ start the build. We need it to 
1. Start the build
2. Don't let another build start until an hour after the earlier build started
3. (open question:) If any build(s) tried to run during that hour, start the build with the most recent commit

Maria shared some code recommended by Josh that should get us headed in the right direction:
`rateLimitBuilds([count: 1, durationName: 'hour', userBoost: true])`

And she has implemented it as part of the dailies build here: https://github.com/rstudio/latest-builds/pull/83
