### ISSUE TITLE
R 4.2: support automatic download + installation of rtools42

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#10205]
Needed to allow for compilation of packages from sources with R 4.2.0 on Windows.

https://developer.r-project.org/Blog/public/2021/12/07/upcoming-changes-in-r-4.2-on-windows/

https://www.r-project.org/nosvn/winutf8/ucrt3/web/rtools.html

**Comment by kevinushey** [comment]
See https://github.com/r-lib/pkgbuild/pull/125/commits/e23ab87e57b7f4d65885c61c7f10f342efd21fec for prior art.

**Comment by mikebessuille** [comment]
@kevinushey is this absolutely required for 4.2 support, or could we do it next release?

**Comment by kevinushey** [comment]
I think we could leave this for next release.

**Comment by kevinushey** [comment]
The rtools42 toolchain is now made available (and described) here:

https://cran.r-project.org/bin/windows/Rtools/rtools42/rtools.html

But unfortunately, it sounds like we won't have a stable URL to use for downloads. Throwing out some options...

1. Try to read and parse the HTML served at `https://cran.r-project.org/bin/windows/Rtools/rtools42/files/`, to guess what the appropriate installer URL is.
2. Serve our own copy of Rtools (from an RStudio AWS bucket), and use a redirect link to update to the "current" Rtools build as appropriate.

I feel like (1) is probably the best way forward, but it's probably worth some discussion. (There's no guarantee that the HTML served from https://cran.r-project.org/bin/windows/Rtools/rtools42/files/ will be stable, and indeed, could differ across different CRAN mirrors based on which web server is hosting.)

(If we take route 1, we could also try to read and parse links from https://cran.r-project.org/bin/windows/Rtools/rtools42/rtools.html as well, which should be a bit more stable than the server-generated file listing.)

**Comment by jgutman** [comment]
Yeah I think reading from the Rtools installer link on rtools.html makes
sense to me

**Comment by jgutman** [comment]
QA Notes from @ronblum 
> QA Note: In testing, include verification that

> A fresh installation of R 4.2 (no previous installation of R and Rtools) triggers installation of Rtools42.
> Installing R 4.2 on top of earlier versions of R and Rtools triggers installation of Rtools42.
> Installing an earlier version of R (such as R 3.6.3 and 4.1.2) triggers installation of earlier versions of Rtools (e.g. Rtools35 and Rtools40, repsectively).
> Also, an easy way to test this is by trying to open a new C++ file.

**Comment by kevinushey** [comment]
I tried testing this on Windows, but I see Rtools40 installed instead:

```
> .rs.installBuildTools("Testing")
trying URL 'https://cran.rstudio.com/bin/windows/Rtools/rtools40-x86_64.exe'
Content type 'application/x-msdownload' length 174215072 bytes (166.1 MB)
downloaded 166.1 MB
```

**Comment by jgutman** [comment]
Yeah, same! Now that I have Windows working again I can look into this better

**Comment by kevinushey** [comment]
It might just be that we need to add Rtools42 as a "known" installer in the list here:

https://github.com/rstudio/rstudio/blob/df59e55c9b5b4834255f3301335602e9ac1b209a/src/cpp/session/modules/build/SessionInstallRtools.cpp#L69-L84

**Comment by kevinushey** [comment]
Also, I think the compatibility test here is causing us to infer that Rtools40 is compatible with R 4.2.0:

https://github.com/rstudio/rstudio/blob/df59e55c9b5b4834255f3301335602e9ac1b209a/src/cpp/core/r_util/RToolsInfo.cpp#L194

See here for how we construct the version predicate (we check `<= maxVersion`; maybe that should just be `< maxVersion`? Or we can just tweak the max version entry for Rtools40):

https://github.com/rstudio/rstudio/blob/df59e55c9b5b4834255f3301335602e9ac1b209a/src/cpp/core/r_util/RToolsInfo.cpp#L293-L294

**Comment by jgutman** [comment]
Will do! Also realize that our current code for the Rtools 42 installer checks for the version being equal to 4.2, which we'll also want to change to >=

**Comment by ronblum** [comment]
When testing, just creating a C++ file didn't seem to be enough; I had to source the file. The default C++ file is sufficient.

These are helpful to determine if RTools is available and which version is being used:
- `pkgbuild::has_rtools()`
- `pkgbuild::rtools_path()`

Verified the following:

*With R 4.2.0*
1) If RTools is not installed, RStudio asks to install 4.2.
2) If only RTools 3.5 is installed, RStudio asks to install 4.2.
3) If only RTools 4.0 is installed, RStudio asks to install 4.2.
4) If both RTools 3.5 and 4.0 are installed, RStudio asks to install 4.2.
5) If RTools 4.2 is already installed, RStudio is content and complies C++ files properly.

*With R 4.1.3*

6) If RTools 4.2 is installed, RStudio asks to install 4.0.
7) If both RTools 4.0 and 4.2 are installed, RStudio uses RTools 4.0.

Note that if RTools is not installed but is still on the OS and in the path, RStudio will describe this in the console, but not try to install RTools. I think this is acceptable, since RTools is in a messy state.
