### ISSUE TITLE
consider user preference for "discard input on error" console behavior

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#10391]
Following up from https://github.com/rstudio/rstudio/issues/3014 and https://github.com/rstudio/rstudio/pull/10368.

**Comment by mikebessuille** [comment]
Presumably the default setting should be to discard the remaining input.  Not sure what the text should be but "discard input on error" sounds to me like it could be very confusing.  "Stop execution on error"?

**Comment by kevinushey** [comment]
Yes, I think so.

Aside from that, I'm conflicted though -- it kind of stinks to introduce a fairly fundamental feature that isn't supported on Windows, especially since it means RStudio behaves slightly differently depending on which platform you're running on.

**Comment by kevinushey** [comment]
One thing to consider is whether we can override R_ResetConsole altogether on Windows. I'm going to investigate that when I have time.

**Comment by gtritchie** [comment]
> One thing to consider is whether we can override R_ResetConsole altogether on Windows. I'm going to investigate that when I have time.

Note: that was implemented in https://github.com/rstudio/rstudio/pull/10835.

**Comment by gtritchie** [comment]
The preference can wait for next release (if we get complaints we can always reconsider). Moving to Elsbeth Geranium.

**Comment by mjsulik** [comment]
+1 for the option to choose between halting on error or continuing to execute subsequent code. If running parts of an Rmd file interactively, the new behavior to halt on error means that it's not possible to select and run more than one code chunk at once using keyboard commands because the code chunk delimiters throw an error.

**Comment by kevinushey** [comment]
@mjsulik, to clarify: are you trying to execute multiple chunks by selecting multiple chunks in the source editor, then using e.g. Ctrl + Enter to execute those chunks?

If so, maybe a better refinement would be to only execute chunk contents for a selection, so that we don't try to send things to the console that aren't R code.

**Comment by jmcphers** [comment]
Another community request to have an option for reverting to the previous behavior: https://community.rstudio.com/t/script-run-in-rstudio-now-halts-on-first-error/144982

**Comment by JimboMahoney** [comment]
Another vote to have an option to stop (current behavior) or carry on (previous behaviour) when encountering an error using CTRL+Enter to execute code chunks.

For context, I'm a novice coder running on Windows 11.

The main reason I encounter this is when debugging Shiny code.

I've worked around it by wrapping my output objects in try(, silent = TRUE)

`  try(
  output$Property_Plot <- renderPlot({
    
    Property_Plot
    
  }) # End of Property Plot
  , silent = TRUE)`

so that I can execute everything inside the server function within RStudio to investigate errors and any objects created.

**Comment by jmcphers** [comment]
Another customer request from StackOverflow here: https://stackoverflow.com/questions/73567974/how-to-make-r-by-default-not-stopping-when-an-error-is-encountered-while-running

**Comment by jmcphers** [comment]
also here: https://stackoverflow.com/questions/73506371/making-r-script-continue-running-despite-encountering-error/73641425#73641425

**Comment by sgoldbergR** [comment]
Yes, an option to disable this behavior would be amazing! All my old scripts are a bit broken now...

**Comment by matthew-c-keller** [comment]
Another request to return to the old behavior of continuing to evaluate after an error, or at least giving the user an option  to revert back to the old behavior. (It seems a bit crappy to change the default behavior in RStudio in a way that is this central and not allow users to revert to the previous default!). I teach R using RStudio and all my scripts have multiple intentional errors in them for didactic purposes. I then need to run large sections of codes (with errors) to arrive at the place where my students are. This behavior has made this way of teaching very difficult. For now, I'm going to try to install an older version of RStudio - or just use the R GUI from CRAN.

**Comment by matthew-c-keller** [comment]
I'll note that I've installed the old version of RStudio (from Feb 2022) in order to get back to the old behavior. Easy workaround for now in case you're interested...

**Comment by sgoldbergR** [comment]
Great solution, Matthew! Thanks for suggesting it. My error-full code and I are back in business!

**Comment by jmcphers** [comment]
I ran an incredibly scientific poll on @rstudiotips and found that most people prefer the new behavior, by about 3 to 1. 

<img width="602" alt="image" src="https://user-images.githubusercontent.com/470418/189413468-06d79c83-2e80-4751-bc49-f8ccb7bbbc29.png">

No reason we couldn't bring back the old behavior, but I think the new behavior should remain the default.

**Comment by rhijmans** [comment]
This breaks code in "terra" that sometimes emits error-messages from the garbage collector that otherwise have no effect  `Error in x$.self$finalize() : attempt to apply non-function`. But R-Studio now stops when this happens (See https://github.com/rspatial/terra/issues/30#issuecomment-1250128901)

This is an obscure problem and should be fixed, somehow, somewhere. But it would be really helpful to be able to tell R-Studio to keep going.

**Comment by kevinushey** [comment]
I think this should be fixed in `terra`; however, users will be able to control the "Discard pending input on error" console preference here if necessary.

https://github.com/rstudio/rstudio/pull/11927

IMHO there isn't any work required on the IDE side.

**Comment by jrelmore** [comment]
I'd greatly appreciate having the old option available. Otherwise I'll be using an outdated version of R for the foreseeable future.

Also, jmcphers, I really appreciate the poll. That said, you didn't actually ask the question at hand. You asked what people 'thought' would happen, rather than what they would prefer to happen when executing the code. Based on the question you asked, it turns out that unless they recently updated most people's expectations are wrong.

Along another line, I suspect the audience who follows any account related to Rstudio on twitter are not representative of the Rstudio user population as a whole. thus, theres a big polling bias :)

**Comment by kevinushey** [comment]
@jrelmore 
good news; we added control over this behavior in https://github.com/rstudio/rstudio/pull/11927. Do you think that will suffice?

**Comment by jonvanausdeln** [comment]
Verified on 2022.12.0-daily+248
Windows 11, Ubuntu 22.04

Option to stop/discard input is checked by default in `Tools->Global Options->Console`. Unchecking box allows input to continue regardless of error as expected.
