### ISSUE TITLE
add syntax support for Fortran files

### ISSUE THREAD

**Issue by waynelapierre** [rstudio/rstudio#10403]
Many R users and developers use Fortran to extend R. Currently, 222 R packages using Fortran are registered at CRAN. There are more that are not registered. It would be great if RStudio could add some basic syntax support for Fortran files.
https://github.com/cran?q=&type=&language=fortran&sort=

**Comment by kevinushey** [comment]
Ace does provide highlight rules for FORTRAN code:

https://github.com/ajaxorg/ace/blob/master/lib/ace/mode/fortran.js

so we could in theory update the version of Ace we use to include that.

**Comment by kevinushey** [comment]
Good first issue for someone who wants to get familiar with how we build + bundle Ace.

**Comment by waynelapierre** [comment]
Any progress?

**Comment by sgiannerini** [comment]
Good day, is there any hope to see this feature implemented? It had been added to the 2023 milestone (and then removed ) so that I assume it is feasible. 

As it has been already pointed out, many R packages (and R base itself) rely on Fortran code and having at least a basic syntax highlighting scheme would be a great help in package authoring. 

Many thanks

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.10.0-daily+132 on SLES 15 SP5. I haven't programmed in Fortran in a while (my first computer language!), so I used some examples from https://fortran-lang.org/learn/quickstart/ which has code with formatting. The only difference I found was in the way `=` is treated.
