### ISSUE TITLE
visual editor can sometimes show additional copy of toolbar commands

### ISSUE THREAD

**Issue by jjallaire** [rstudio/rstudio#10471]
For example:

![image (1)](https://user-images.githubusercontent.com/104391/151663781-50c652a1-7853-4c9b-9b02-15e39020c540.png)

We've seen this occur a couple of times however don't currently have a repro.

**Comment by ronblum** [comment]
I tried a number of things a bunch of times over a couple of days, but I've had no luck reproducing the problem:
- Switching back and forth between visual and source modes, including some very fast back-and-forths
- Closing and reopening the file in visual and editor modes
- Moving the splitter so that the toolbar both can only be partially and fully seen
- Exiting and restarting the application
- Checking out and editing in the context of [ModernDive_book](https://github.com/moderndive/ModernDive_book)
- Editing in both a four-pane layout and with a zoomed-in Source Pane
- Starting with the default Rmd file and 1) setting the styles for the headers, 2) adding some text and a chunk at the bottom, and 3) changing the YAML values, to exactly match the code when the issue appeared

Tested primarily in a mixture of RStudio Desktop 2022.02.0-preview-394 and 2022.02.0-preview-412 on MacOS 12.1, and a little bit in RStudio Server 2022.02.0-preview+398. (The original issue appeared on in RStudio Desktop on MacOS.)

**Comment by jgutman** [comment]
Can't be sure about this, but it's possible this may have been resolved by changes in #11042, as addressed in #10987.

That issue also showed some intermittent duplication of the edit toolbar commands as shown in the above screenshot, however without being able to consistently reproduce the issue here it's hard to be sure if that fix resolved it completely
