### ISSUE TITLE
Cleanup UI Zooming in Electron Desktop

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#10484]
Cleanup and finish implementing the zoom feature. It seems to be working in general, but review and resolve the following TODOs to ensure it is fully implemented.

Be sure to test via keyboard shortcuts, command-palette, and via invocation of the View / Actual Size / Zoom In / Zoom Out menu.

Also look at persistence of the zoom level. Currently it is being saved (somewhere...) but in a different place than Qt desktop. Decide if we care about zoom level staying the same if you are going between Qt-based and Electron-based RStudio.

Note, currently relies on Electron's menuItemRoles versus the explicit command-handling we do in the Qt desktop. That might be ok (don't quite recall the gory details 7 months later).

- https://github.com/rstudio/rstudio/blob/e869a097415c5e8ded835bdd70a6eae465d4f226/src/node/desktop/src/main/desktop-browser-window.ts#L194-L197
- https://github.com/rstudio/rstudio/blob/e869a097415c5e8ded835bdd70a6eae465d4f226/src/node/desktop/src/main/main-window.ts#L111-L114
- https://github.com/rstudio/rstudio/blob/e869a097415c5e8ded835bdd70a6eae465d4f226/src/node/desktop/src/main/menu-callback.ts#L302-L323

Also including these TODOs related to dpi as part of this:

- https://github.com/rstudio/rstudio/blob/e869a097415c5e8ded835bdd70a6eae465d4f226/src/node/desktop/src/main/utils.ts#L48-L51
- https://github.com/rstudio/rstudio/blob/e869a097415c5e8ded835bdd70a6eae465d4f226/src/node/desktop/src/main/utils.ts#L344-L349
- https://github.com/rstudio/rstudio/blob/b9cfb0cead45532141eb11bb772ff501a047bd51/src/node/desktop/src/main/gwt-callback.ts#L286-L289

**Comment by matheustavaresdev** [comment]
After many testing and code walkthrough, here's my outcomes on this:

## 1) Image comparison
- **Default ( 0 ) Zoom**
  - Electron 
![electron_0](https://user-images.githubusercontent.com/36674530/154419211-15a2e820-66fa-4c62-8511-ead9d7e00d78.png)
  - QT
  ![QT](https://user-images.githubusercontent.com/36674530/154419236-0e963b73-e6e6-4ccd-a96e-170dcc6eaf6c.png)
  
- **+4 Zoom ( Increase zoom 4 times when current zoom level is default)**
  - Electron
![electron_+4](https://user-images.githubusercontent.com/36674530/154419359-21597808-b82f-4f6e-bfc0-ce5815b47f87.png)
  - QT
![qt_+4](https://user-images.githubusercontent.com/36674530/154419375-55bc3f25-b6a6-4790-91fb-bb9bf7fde271.png)

- **-4 Zoom ( Decrease zoom 4 times when current zoom level is default)**
  - Electron
![electron_-4](https://user-images.githubusercontent.com/36674530/154419475-a0b989e2-a7d5-48fe-96b9-caa620e66f7b.png)  
  - QT
![qt_-4](https://user-images.githubusercontent.com/36674530/154419487-e29c65f0-8e87-40f4-8c58-06efa51bc7d6.png)

## 2) Conclusion

2.1) Besides when having them at -4 or +4 size and beyond, they are pretty much the same when using in between zoom levels. The main difference seems to be the font used or at least the font spacing or something alike, due to the minimal difference we can observe when using Default Zoom. This applies for both Windows and Mac.


2.2) We can also note that on Windows, we have a vertical and horizontal scroll bar on the bottom right box, which are always misplaced on Electron. Their position should be probably fixed. ( Not sure if we can interfere directly from Electron or not ) 
2.2.1) On Regular RStudio, we only have a horizontal scrolling bar present at all times, which does not seem to work at all, and a vertical scrolling bar that works properly when the content does not fit that box. The vertical scroll bar works properly at least.
2.2.2) Both scroll bars seems to be working on Electron.
2.2.3) On Mac we only have a vertical scroll bar for both the Regular and Electron RStudio app


2.3) Zoom levels are being saved as they should for both Electron and regular RStudio. Altough I don't think it would be worth the work for having them sharing the same zoom level, as most likely both apps will not be used together and even if they do, it's a simple change for the user ( I could be wrong on how much is this needed though )


2.4) DPi seems to be handled automatically by Electron. After testing for both somewhat "extreme" cases on -4 and +4 zoom levels, they seem to be equal related to DPi. I also don't think it's needed to do further work on this, but I could be missing something here

**Comment by timtmok** [comment]
I've tried the zoom on all platforms and things look good. Windows didn't seem to suffer from the misplaced scroll bars. I don't think Electron was updated in the 6 days since Matheus tried it so it might be a specific environment issue.

I think all that needs to be done is no-op the zoom events and continue using Electron's zoom handling.

**Comment by gtritchie** [comment]
I played with zooming on Mac, Windows, and Linux, and all seems to be behaving as expected. Closing.
