### ISSUE TITLE
Error Reading on MAC

### ISSUE THREAD

**Issue by allilahsa** [rstudio/rstudio#10590]
### System details

    RStudio Edition : 
    RStudio Version : Desktop
    OS Version      : MacOS Mojave Version 10.14.6
    R Version       : RStudio Desktop 2021.09.2+382

### Steps to reproduce the problem

Install new RStudio

### Describe the problem in detail 

Error reading R script (), system error 2 (No such file or directory); Unable to find libR.dylib in expected locationswithin R Home directory /Library/Frameworks/R.framework/Resources

### Describe the behavior you expected

Install Software smoothly and can work.

- [ x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ x ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

<img width="1440" alt="Screen Shot 2022-02-14 at 08 28 55" src="https://user-images.githubusercontent.com/64634447/153785658-6490e768-67a4-405c-adcd-a81b72bd97fd.png">

**Comment by ronblum** [comment]
@allilahsa Can you also verify that R is installed? You can check on the command line with
`R --version`
or search for the R GUI in the Applications folder.

**Comment by AlexMapley** [comment]
I actually just saw the exact same error on Big Sur `11.6.5`, after downloading the latest mac release from https://www.rstudio.com/products/rstudio/download/#download (`RStudio-2022.02.3-492.dmg`).
<img width="418" alt="Screen Shot 2022-06-17 at 9 43 28 AM" src="https://user-images.githubusercontent.com/18649003/174311972-07fa24fb-05ae-4bca-99ef-eb97a81764de.png">

As it turns out I had not yet installed R, running `brew install R` did the trick 😅. I wonder if that's what happened here as well.
