### ISSUE TITLE
implement clipboard handling

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#10737]
Re: https://github.com/rstudio/rstudio/blob/749ed1bf7f7eecb25be26dcab5c70ecf869fae31/src/node/desktop/src/main/gwt-callback.ts#L182-L220

Also note some Ace-specific workarounds here:

https://github.com/rstudio/rstudio/blob/749ed1bf7f7eecb25be26dcab5c70ecf869fae31/src/cpp/desktop/DesktopGwtCallback.cpp#L342-L385

**Comment by ronblum** [comment]
Works splendidly except for one issue, which I filed separately:
-  #11111 (Linux)

It also fixes an existing issue, which I'll file for reference but put it into "Fixed by Electron:"
- #11128

-----

Verified using the QA Notes in 10740 as a guide.

*OS and RStudio Versions*
- MacOS 12.4, Ubuntu 20.04, and Windows 10
- A combination of RStudio Desktop 2022.06.0-daily+322, 2022.06.0-daily+341, and  2022.06.0-daily+353

*Locations in RStudio Desktop*
- R Script
- R Markdown
- Quarto Document
- Console Pane

*External Editors*
- LibreWriter (Ubuntu)
- Notes and Word (MacOS)
- Notepad and Word (Windows)

*Methods and Content Types*
- Keyboard shortcuts
- Mouse (right-click and middle-click)
- Text and images (https://tinyurl.com/littlekittykat)

![](https://cdn.theatlantic.com/thumbor/d_NLi03xlxJllzEaXKQfcLenM_8=/1120x0:5600x4480/1080x1080/media/img/mt/2021/05/GettyImages_1218380632/original.jpg)
