### ISSUE TITLE
Electron: checking version with command line returns "unknown"

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#10794]
### System details

    RStudio Edition : Desktop (Electron)
    RStudio Version : 2022.06.0-daily_210 (Electron)
    OS Version      : MacOS 12.1/3, Red Hat 8.3, Ubuntu 20.04.3, etc.
    R Version       : N/A

### Steps to reproduce the problem

Run `rstudio --version`

### Describe the problem in detail

The version is returned as `unknown`.
```
$ rstudio --version
unknown
```

### Describe the behavior you expected

The current version of RStudio Desktop should be returned. Compare to Spotted Wakerobin, non-Electron:

```
$ ./rstudio --version
2022.06.0-daily+210
```

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by matheustavaresdev** [comment]
@ronblum what OS is this happening? I just tested and it's working just fine. Although, for example, with MacOS, you need to run `RStudio.app/Contents/MacOS/RStudio --version` for it to work..

**Comment by ronblum** [comment]
Red Hat 8.3, Ubuntu 20.04, and MacOS 12.1 and 12.3. And yes, with MacOS I use the full path:

```
Rons-Busy-Bee ~ % /Applications/RStudio.app/Contents/MacOS/RStudio --version
unknown
```

Are you using a development version or daily? That's made a difference with some issues.

**Comment by matheustavaresdev** [comment]
It seems that for it to work you need to run it with `-- --version`. Otherwise it will try to return a `npm` version instead of the `Electron` app version. Spent some time trying to work around this, but it seems that it should take quite some time to find a solution. 

Would this be worth it? 

- Commands and their outputs:
    - `npm run start --version` -> `npm` version 
    - `npm run start -- --version` -> `electron-forge` version
    - `npm run start -- -- --version` -> `RStudio App` version

It also seems that there's some code on `electron-forge` that's overriding the default `--version` command. There's a chance that building the app with electron only could get rid of those issues, although I am not sure of that as of now and this could potentially take a lot of time to be done.

cc @gtritchie

**Comment by ronblum** [comment]
Verified that this works on the command line in RStudio Desktop 2022.06.0-daily-296 on
- MacOS 12.3
- Red Hat 8.3

Checked that this works in Electron (fix) and Qt (existing behavior).

This is entirely on the command line, so not recommending for automated testing.
