### ISSUE TITLE
RStudio fails to launch on M1 Mac with SIP turned off

### ISSUE THREAD

**Issue by thomasp85** [rstudio/rstudio#10863]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2022.02.0+443, "Prairie Trillium" (9f796939, 2022-02-16)
    OS Version      : macOS 12.3
    R Version       : R version 4.1.3 (2022-03-10) -- "One Push-Up"

### Steps to reproduce the problem
Currently not reproducible

### Describe the problem in detail
After turning off SIP RStudio fails to launch as it misidentifies the required architecture, looking for x86_64 instead of arm64. Turning on SIP again resolves the issue

**Comment by kevinushey** [comment]
Some notes from debugging with @thomasp85:

- When SIP is disabled, nothing is logged at `~/.local/share/rstudio/log`.
- I couldn't find a way to get RStudio Desktop to emit its logs to stderr, either.
- Because RStudio was running through Rosetta, we couldn't use dtruss or other tools to introspect what RStudio was trying to do.

We should have some way of enabling stderr logging of messages in RStudio Desktop at least for debugging these sorts of things.

**Comment by kevinushey** [comment]
Also weird is that I have no issue running RStudio myself with SIP disabled.

**Comment by Slagt** [comment]
Hello,

I have been looking for a solution to this problem for some time already. The solution that was suggested to me was to make a symlink to make sure that `RStudio.app/Contents/MacOS/rsession` points to `RStudio.app/Contents/MacOS/rsession-arm64`. It does allow RStudio to run, but it's not possible to install any package, as it believes it's running on x86.

The SIP was disabled on my computer, somehow. There are three level of security policy now: permissive (former "disabled"), medium and strict (former "enabled"). Using "medium" solved my issue, and I can now run RStudio in arm64 mode.

Now idea if this is reproducible or not.
That was a fresh re-install of RStudio and a fresh re-install of R (although R was running fine on its own).
