### ISSUE TITLE
Add Cgroups V2 Support

### ISSUE THREAD

**Issue by JsizzleR** [rstudio/rstudio#10914]
On Cgroup v2 enabled systems, this error is logged:

![image](https://user-images.githubusercontent.com/27960665/161984391-3976b85a-1570-4ff0-8a50-46c6af069677.png)

In Cgroup v2, many of the cgroup psuedofiles have been renamed and their range of values have changed as well.  
For example, Cgroup v1's memory.limit_in_bytes correlates with v2's memory.max.
Ref: https://www.kernel.org/doc/html/latest/admin-guide/cgroup-v2.html 

Debian 11 has Cgroups v2 enabled by default, RHEL 8 has support for it but it's not enabled by default. Ubuntu 22.04 LTS will have cgroups v2 enabled.

**Comment by cm421** [comment]
I don't know how much effort this will take, and therefore lean towards pushing it to the next release. But it should be fixed sooner rather than later.

This seems related: https://rstudio.slack.com/archives/C7HT9GDB9/p1652905055371659
And here's another ticket bumping into this: #74677

**Comment by Cecilsingh** [comment]
customer ticket: https://rstudioide.zendesk.com/agent/tickets/75365

**Comment by mbaynton** [comment]
The hosted team is starting work on moving our underlying systems from cgroup v1 to cgroup v2. It looks from the existing code like if we take the cgroup v1 memory controller away, the system's overall memory data from `/proc/meminfo` will be used instead. 

rstudio.cloud uses the values reported by the IDE to populate the memory used gauge near the top right of the rstudio.cloud interface when you are inside a project, so it's going to become quite important to cloud that we have cgroup v2 support. @mikebessuille okay to add the rstudio.cloud label on this?

When working this issue, please compute the percent available value using a representation of memory used that does not include reclaimable memory like the kernel page cache. Otherwise, the gauge will quickly become saturated and make it look to users of cloud like they are almost out of memory, simply by performing disk i/o. (This is also a problem with the cgroup v1 collector today, see related https://github.com/rstudio/rstudio-pro/issues/3654)

**Comment by mikebessuille** [comment]
Thanks for the detail.  Unfortunately, we have no capacity to support this for our fall release, "Elsbeth Geranium".

**Comment by datakid** [comment]
Also seen in customer ticket: #77824

**Comment by JsizzleR** [comment]
Also seen in customer ticket id: 78693

**Comment by aronatkins** [comment]
Also seen in Connect customer ticket id: 79441

**Comment by datakid** [comment]
Also seen in customer ticket: 79648

**Comment by datakid** [comment]
Also seen in prospective customer ticket #80253

**Comment by mikebessuille** [comment]
This was merged accidentally into EG awhile ago.  If we have time to test it, we should keep it in EG considering how important it is to so many customers.

**Comment by ronblum** [comment]
Ref #11235 for cgroups v1 and v2.

**Comment by mikebessuille** [comment]
@timtmok to comment.  The original work for CGroups was mistakenly merged into Elsbeth (we didn't expect to have time to test it).  Since it's now merged into Main, we're going to try to test it for Elsbeth.  This seems to point out that not all of the work was merged.  So...  Need a risk assessment of leaving this out, or pulling it in.

**Comment by ronblum** [comment]
First, tested the cgroups v1 continues to work. With memory limit set to 1GB, the environment pane shows the following for RStudio Server 2022.07.2-576 on RHEL 7.9 (cgroups v1):

![Image](https://user-images.githubusercontent.com/31009952/203650434-53546755-f29f-4899-98e4-0bced0ca6a5f.png)

With RStudio Server 2022.12.0-preview-342 on RHEL 7.9 (cgroups v1):


![Image](https://user-images.githubusercontent.com/31009952/203650568-8ccba274-81c1-45a7-88fc-6fd5131655cc.png)


Compare this to RStudio Server 2022.12.0-preview-342 on Ubuntu 22 (cgroups v2):

![Image](https://user-images.githubusercontent.com/31009952/203650994-c4311aaf-6839-417b-a2a7-dc7e2ff2fa11.png)

This was a verification that this change doesn't affect cgroups v1, so it's safe to keep this change. I'm moving this out to the next release, for any more comprehensive testing of cgroups v2.

QA: Some useful commands for setting the memory limit of `rstudio-server`:

1. Cgroup v1: `systemctl set-property rstudio-server MemoryLimit=1G`
2. Cgroup v2: `systemctl set-property rstudio-server MemoryHigh=1G`

Then start the process with `systemctl restart rstudio-server`
The status/startup should include the following, in which the "Memory" line indicates the uppsr limit:
> Main PID: 29030 (rserver)
     Memory: 2.6M (high: 1.0G)
     CGroup: /system.slice/rstudio-server.service
             └─29030 /usr/lib/rstudio-server/bin/rserver

**Comment by Cecilsingh** [comment]
Another customer ticket: https://rstudioide.zendesk.com/agent/tickets/82195

**Comment by mikebessuille** [comment]
@marexin you should be able to run the latest release, 2022.12.0, with no issues using CGroups V2.  The feature is in that release, just as experimental, not fully tested.   In any case, this problem should not prevent you from installing or running Workbench on Ubuntu.

**Comment by marexin** [comment]
@mikebessuille I installed version 2022.12. When I check status with `sudo rstudio-server status` it's full of cgroup error messages. And Workbench webpage is not displayed properly. So yes, installation is possible, but rstudio-server doesn't work correctly.

**Comment by mikebessuille** [comment]
@marexin looks like you're running into https://github.com/rstudio/rstudio-pro/issues/2683 which we haven't completed yet...

**Comment by marexin** [comment]
@mikebessuille don't have access to see that issue

**Comment by marexin** [comment]
@timtmok ok but is it somehow possible to run Workbench on Ubuntu 22? Maybe with turned off rserver-monitor?

**Comment by datakid** [comment]
@marexin My understanding is that this isn't a blocker. You will get warnings, and cgroups v2 will not be recognised (ie, memory limits aren't respected) but you can still run Workbench on Ubuntu 22.

**Comment by marexin** [comment]
@datakid ok, I installed Workbench on Ubuntu 22, however I can't create new users. We use JumpCloud as IdP provider and we pass metadata file in rserver.conf: `auth-saml-metadata-path=/etc/rstudio/saml-idp-metadata.xml`. 

From docu: "Normally, when users sign in to Posit Workbench for the first time, they are automatically added to the Posit Workbench user database."
However when logging in I get this error: `ERROR system error 2 (No such file or directory) [description: User not found., user-value: my_user_name];` 

So I try to add user manually with command: `sudo rstudio-server add-user my_user_name 1` 
Error: `[rserver-db] ERROR system error 2 (No such file or directory) [description: User account does not exist, user-value: my_user_name]; OCCURRED AT rstudio::core::Error rstudio::core::system::User::Impl::populateUser(rstudio::core::system::User::Impl::GetPasswdFunc<T>&, T) [with T = const char*  rstudio::core::system::User::Impl::GetPasswdFunc<T> = std::function<int(const char*, passwd*, char*, long unsigned int, passwd**)>] src/cpp/shared_core/system/User.cpp:68; LOGGED FROM: int main(int, char* const*) src/cpp/server/db/DbMain.cpp:479`

It's not possible to add any user. I am not sure if this is related to cgroups problem, or it's a separate issue.

**Comment by datakid** [comment]
@marexin If you are using the open-source RStudio Server, you will not have access to Authentication. If installing the professional product Posit Workbench, please [open a support ticket](https://support.posit.co/hc/en-us/requests/new).  Please see this page [for the full product comparison](https://posit.co/products/open-source/rstudio-server/).

**Comment by ronblum** [comment]
As far as I can tell, this still isn't working with cgroups v2. Tested on Ubuntu 22.04, the following shows up every minute in `/var/log/syslog` (see #3466#issue-1242096940).

```
Feb 17 09:34:50 vmware rserver-monitor[5893]: ERROR system error 2 (No such file or directory) [path: /sys/fs/cgroup/memory/memory.limit_in_bytes]; OCCURRED AT rstudio::core::Error rstudio::core::FilePath::openForRead(std::shared_ptr<std::basic_istream<char> >&) const src/cpp/shared_core/FilePath.cpp:1483; LOGGED FROM: rstudio::core::Error rstudio::monitor::metrics::systemMemoryData(rstudio::monitor::metrics::SystemMemoryData*) src/cpp/monitor/metrics/Collector.cpp:198
```

**Comment by mikebessuille** [comment]
@atheriel any ideas?

**Comment by MariaSemple** [comment]
@ronblum This should be in rel-cherry-blossom and main now, could you retest?

**Comment by ronblum** [comment]
Useful info for cgroups:

```
Cgroups v1 and v2
Check current version:	
	stat -fc %T /sys/fs/cgroup/
		tmpfs = V1
		cgroup2fs = v2
Check available versions
	ls -ld /cgroup/*/lsf
	mount | grep '^cgroup' | awk '{print $1}' | uniq
	mount | grep '^tmp' | awk '{print $1}' | uniq
Set memory limit
	Cgroup v2
		systemctl set-property rstudio-server MemoryHigh=1G
	Cgroup v1
		systemctl set-property rstudio-server MemoryLimit=1G
	systemctl restart rstudio-server 
```

**Comment by ronblum** [comment]
@astayleraz and I have been reviewing this on RHEL and Ubuntu.
1. On RHEL 9, the error messages are now gone. We still need to confirm with Ubuntu 22.
2. In the open source RStudio Server, the memory usage report is correct. However, the it's incorrect in Posit Workbench. With the limit set to 1 GB, the report is showing over 7 GB memory:
![Image](https://user-images.githubusercontent.com/31009952/222283274-65f0ae87-9caa-412f-8e85-cc2e136b45c8.png)

But as it turns out, this didn't work in previous versions, either. Possibly related to #10928, which is really a generic issue, not just for Kubernetes? If this is the case, then we can open up a separate issue (or rely on #10928) and mark this issue as completed.

Tested on 
- RHEL 7.9 and 9.1
- Using
    - RStudio Server 2022.12.0-353 and 2023.03.0+380
    - Posit Workbench 2022.12.0-353.pro20 and 2023.03.0+380.pro3

Ubuntu details forthcoming.
