### ISSUE TITLE
Consider routinely updating version of Quarto bundled with RStudio

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#10920]
### System details

    RStudio Edition : Desktop and Server
    RStudio Version : 2022.06.0-daily+270
    OS Version      : MacOS 12.3, Red Hat 8.3, Ubuntu 20.04
    R Version       : 4.1.3

### Steps to reproduce the problem

Run `quarto --version` bundled with RStudio:
- RStudio Desktop on MacOS: `/Applications/RStudio.app/Contents/MacOS/quarto/bin/quarto --version`
- RStudio Desktop on Red Hat: `/usr/lib/rstudio/resources/app/bin/quarto/bin/quarto --version`
- RStudio Server on Ubuntu: `/Applications/RStudio-2022.06.0-daily-272-OG.app/Contents/MacOS/quarto/bin/quarto --version`

### Describe the problem in detail

The bundled version is 0.9.80.

### Describe the behavior you expected

The most recent version at https://quarto.org as of April 6, 2022 is 0.9.194. Version 0.9.80 is from March 10. We should consider routinely updating to the latest version. 

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Triage: Also consider as `backport` to Prairie Trillium.

**Comment by mikebessuille** [comment]
I don't think we need to backport this; PT users of quarto are using a prerelease thing; they should update it themselves.  

JJ is going to work with Tim so that our dailies include the latest build of quarto starting shortly.

**Comment by timtmok** [comment]
I got some direction from JJ. The dependency can be updated to `latest` (https://github.com/quarto-dev/quarto-cli/releases/latest) which will point to the tagged release. GitHub has REST API to query the releases (https://api.github.com/repos/quarto-dev/quarto-cli/releases).

This commit is an example of what a Quarto update would change: https://github.com/rstudio/rstudio/commit/acac28db27d2d172834036d9f47d85792b2e0b04

JJ noted that taking the latest will require some other updates to handle the change in how Pandoc is packaged. Should be fairly minor.

It's just getting the build to grab the latest tagged release, updating the dependency installer scripts, and `SessionQuarto.cpp` since it has a version warning if Quarto is less than the recommended version.

Something to think about is whether the build should trigger the update. Updating Quarto does require code changes for the version warning. Maybe this might be suited for a script that is manually run and committing the changes it generates.

**Comment by jgutman** [comment]
Can we update our admin guide builds to mention this and put something in our release checklist to pin the version? @mikebessuille

**Comment by ronblum** [comment]
Will this automatically happen with every build, or can we control it so that we stop at some point? For example, we should fix the version number before issuing release candidates.

**Comment by jgutman** [comment]
Yes it will automatically happen with every build, hence why we need to add a step to the release checklist to pin the quarto version, because release candidates should be pinned to a static version

**Comment by mikebessuille** [comment]
Added to release checklist at https://rstudiopbc.atlassian.net/wiki/spaces/ENG/pages/39223304/Release+Checklist+-+Spotted+Wakerobin

**Comment by timtmok** [comment]
Actually, none of the builds necessarily pulls the latest Quarto. This is due to the builds using Docker containers that are pre-built with the dependencies already installed. Any of the Docker image layers before the dependency install step (including the `rstudio-tools.sh` script) have to change before Docker decides to rebuild the subsequent layers.

So it's mostly building from the cached layer with whatever Quarto version at the time the layer was built. I may be able to invalidate the cached layer based on the current Quarto release version but this will need to change across all the Docker images.

**Comment by timtmok** [comment]
Note: Windows will use the latest Quarto because it always runs the install dependencies script instead of using a cached layer.

**Comment by timtmok** [comment]
I'm trying out a cache busting solution in the Dockerfile by grabbing the Quarto release list from the GH API. This way it can cache the layer if there haven't been any new Quarto releases and only install Quarto if there's a new version. This should help keep build times down by avoiding installing all the dependencies on every build.

**Comment by timtmok** [comment]
The Docker images are now updated with the latest Quarto version. This affected Linux builds only. Windows and Mac were always running the dependency installer script to fetch the latest version.

Verified in build 482 for RStudio Server and Desktop as well at the image build stage in Jenkins.
