### ISSUE TITLE
Allow system-wide Rprofile.site file on installDependencies

### ISSUE THREAD

**Issue by Enchufa2** [rstudio/rstudio#10945]
Currently, installation of package dependencies (e.g., when you open a file that uses an R package that is not installed, a prompt says "Package %s required but is not installed" and you have the option to click "Install", which launches a job) uses a vanilla session:

https://github.com/rstudio/rstudio/blob/ce2869b15b1c7d4d6221b5edd9efd6a049a7f139/src/cpp/session/modules/SessionDependencies.cpp#L618-L621

I find this too restrictive, because `--vanilla` implies `--no-save`, `--no-restore`, `--no-init-file` and `--no-environ`, but also `--no-site-file`. It would be nice to use all but the last one for this (could be e.g. `R_PROCESS_VANILLA_USER`), so that system-wide R options apply to these installations too.

**Comment by kevinushey** [comment]
Can you elaborate a bit more?

Because user + site profiles have already been executed, the requisite state (e.g. the library paths) should already be set in the parent R session (or, the user may have changed library paths separately), and so it's RStudio's responsibility to ferry that current state to the launched sub-process without having that state again modified by a user or site profile.

I'm guessing this might not be true for certain R options set in the child sessions that you're hoping would be reflected though; is that the case? If so, it might be sufficient for us to set `R_PROFILE_USER` to an empty (or non-existent) values so the site profile can be run without the user profile.

**Comment by Enchufa2** [comment]
Any other options, apart from the library paths, set in the `R.home("etc")`/`Rprofile.site` file are not carried out to the child session. I see good reasons to avoid the user's `.Rprofile`, but not to avoid the system-wide `Rprofile.site` file. Or maybe an option to enable this.

**Comment by Enchufa2** [comment]
Still relevant.
