### ISSUE TITLE
rgl crashes in RStudio

### ISSUE THREAD

**Issue by ms609** [rstudio/rstudio#11043]
Originally reported at https://github.com/dmurdoch/rgl/issues/208

### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.06.0 Build 322
    OS Version      : Windows 10 x64
    R Version       : 4.2.0 RC (2022-04-21 r82226 ucrt)

### Steps to reproduce the problem
`install.packages("rgl")` (or `install_github("dmurdoch/rgl")`)
`library("rgl")`

### Describe the problem in detail
RStudio crashes with "R Session Aborted".

### Describe the behavior you expected
The rgl library loads fine in RStudio with R4.1.3, and with the standalone R 4.2 GUI

Possibly relevant? I've noticed a change in RStudio's behaviour from R4.1.3 to R4.2: `throw` in c++ code in R packages was handled safely, but now causes RStudio to crash.  I wonder whether there's a change in how R handles exceptions in the new version?

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics-report.txt](https://github.com/rstudio/rstudio/files/8541599/diagnostics-report.txt).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by glin** [comment]
I noticed this too while testing rgl with the R 4.2.0 RC on Windows yesterday. And oddly enough, RStudio doesn't crash if you set `options(rgl.debug = TRUE)` before loading rgl:

```r
options(rgl.debug = TRUE)

library(rgl)
```

**Comment by dmurdoch** [comment]
Yes, @kevinushey is right:  the workaround prevents the crash, and the devel version has a check added so the workaround isn't necessary.  (The issue was that some Unix systems print spurious error messages on startup, so rgl directed those to the nul device unless you set `options(rgl.debug = TRUE)` to see them.  But what's new is that the nul device sometimes fails to open in Windows.  rgl wasn't checking for that, but now it does.  Thanks Kevin for tracking it down.)
