### ISSUE TITLE
Two spaces within text treated as tabs when navigating via keyboard

### ISSUE THREAD

**Issue by jassler** [rstudio/rstudio#11081]
### System details

    RStudio Edition : Desktop
    RStudio Version :  RStudio 2022.02.2+485
    OS Version      :  Windows 10, version 21H2 (19)
    R Version       :  4.2.0

### Steps to reproduce the problem

1. In any document, type something like
```
1 2  3   4    5     6
```
2. Use left / right arrow keys to move the text cursor character by character

### Describe the problem in detail

If the text cursor is placed on an uneven column, two spaces to the left and right are treated as a tab. This is fine when it's to the left of indented code, but when it's within text itself, navigating and fixing spaces gets irritating. Clicking "within" two spaces with my mouse works though.

As a side note, using Ctrl+Right / Ctrl+Left to navigate word by word also does not seem to align with default behavior found in other applications such as VS Code, any browsers, Word, etc. In other applications, pressing Ctrl+Right for instance skips whitespace AND the next word, whereas RStudio only skips whitespace. Is this intended? Should I open a separate issue for this?

### Describe the behavior you expected

Spaces within text or code should be treated as single spaces when navigating with the left and right arrow keys.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@jassler Thank you for raising this! I can also reproduce this in RStudio Desktop 1.4.1717 and 2022.06.0-daily+341 on MacOS 12.4. We'll review this as we continue development of RStudio.

Regarding Ctrl+Right / Ctrl+Left, can you open a new issue for it? It'd be good to review and track, to at least identify that the behavior is different. Thanks!

**Comment by jassler** [comment]
@ronblum Added the issue: https://github.com/rstudio/rstudio/issues/11105#issue-1223124496

**Comment by jassler** [comment]
This is still relevant in the latest update of RStudio. I hope this gets resolved.

**Comment by jassler** [comment]
Unfortunately, this issue has still not been resolved and I'd love to see it fixed.

**Comment by avila** [comment]
Hello, I would like to ask if there is any way of re-opening this issue or if I should open a new issue and refer to this one. (I read the [issue grooming](https://github.com/rstudio/rstudio/wiki/Issue-Grooming) document and didn't find any indication on how to deal with closed issues due to staleness) 

This issue is quite bothersome when writing with multiple cursor, that I often have a Positron window opened just for more complex multi-cursor edits. 

Please note that other people also raise this issue elsewhere:

- [SO Question/Answer](https://stackoverflow.com/a/48325528/8237186). 
- [Here is another community post ](https://forum.posit.co/t/navigating-double-spaces-with-arrow-keys/54132) about this issue. 
- [And another SO question](https://stackoverflow.com/questions/60366672/navigating-double-spaces-in-rstudio).
