### ISSUE TITLE
R Markdown excludes unicode characters in PDF output

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#11120]
### System details

    RStudio Edition : Desktop & Server
    RStudio Version : 1.4.1717 & 2022.06.0-daily+341
    OS Version      : MacOS 12.4 (Desktop) & Ubuntu 20.04.3 via Chrome on MacOS 12.4 (Server)
    R Version       : 3.6.3 & 4.1.2

### Steps to reproduce the problem

[Modeled after #11116]

1. Create an R Markdown file with the following contents:
```
---
title: "Use R Markdown"
output: 
  pdf_document: 
    latex_engine: xelatex
---

## Test

Chinese: 中文

曾经沧海难为水，除却巫山不是云。

Hello? Is any body in there?

Hebrew: איפה

Where oh where?
```

2. Knit the file (as PDF).
3. Open the file.
    - None of the unicode characters are printed.
4. Knit the file as HTML.
    - The unicode characters are displayed correctly.

### Describe the problem in detail

Unicode characters—in this case, Chinese and Hebrew—are not displayed in the PDF file.

<img width="232" alt="unicode_pdf" src="https://user-images.githubusercontent.com/31009952/166693386-cb7f0c15-a32f-4840-84b1-2806b258077d.png">

### Describe the behavior you expected

All characters should be displayed, as with HTML and Word.

<img width="245" alt="unicode_html" src="https://user-images.githubusercontent.com/31009952/166693570-d8554ed5-0ced-4699-a700-33bdd10f4f7b.png">

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Presumedly, this is a pure `rmarkdown` error, since the issue would be reproduced by calling `rmarkdown::render("path/to/doc.Rmd")`. Do you want to file this at https://github.com/rstudio/rmarkdown/issues?

**Comment by GlekoMa** [comment]
@ronblum  Thanks you for replying in #11116 

The source of this problem is LaTeX I think. 

Actually if write: 
```
---
title: "Use R Markdown"
documentclass: ctexart
output: 
  pdf_document: 
    latex_engine: xelatex
---

## Test

Chinese: 中文

曾经沧海难为水，除却巫山不是云。

Hello? Is any body in there?

Hebrew: איפה

Where oh where?

Japanese: にほんご

とにかく　人の世は住みにくい
```
The PDF created will be: 

![pic1](https://user-images.githubusercontent.com/97289978/167144506-32d17b32-b953-4a47-8023-caa1a0b8f793.png)

```
documentclass: ctexart
```

The ctexart is a documentclass wirten by Chinese to display Chinese in LaTeX. And it can display Japanese, too. But to Hebrew, it failed. 

Maybe it can be working by add another LaTeX package in the contents. Just like the [R Markdown Cookbook](https://bookdown.org/yihui/rmarkdown-cookbook/latex-extra.html) points. 

And I have found a template using Hebrew in LaTeX: [Hebrew document in Overleaf](https://www.overleaf.com/latex/examples/hebrew-document-in-overleaf-writelatex-msmk-bbryt/vpfygfqnfjxs). I runned the example from this website with texlive, and got error: 

```
The command name is D:\texlive\2021\bin\win32\mktexmf
Cannot find jerus10.mf.
```

Maybe I lack the font of Hebrew. After all I don't use Hebrew to write, so I have to take a pity to give up. I think there are some solutions in Stack Overflow if we seek for deeply.

So I think this issue could not be soluted because it is not a bug. This's just how R Markdown was designed. 

Maybe my expression is not clear enough. Forgive for my poor English.
