### ISSUE TITLE
install RStudio desktop failed in Ubuntu 22.04

### ISSUE THREAD

**Issue by Tsai002** [rstudio/rstudio#11256]
### System details

    RStudio Edition : rstudio-2022.02.2-485-amd64.deb
    OS Version      : Ubuntu 22.04

### Steps to reproduce the problem

```
> sudo dpkg -i rstudio-2022.02.2-485-amd64.deb
(Reading database ... 206698 files and directories currently installed.)
Preparing to unpack rstudio-2022.02.2-485-amd64.deb ...
Unpacking rstudio (2022.02.2+485) over (2022.02.2+485) ...
dpkg: dependency problems prevent configuration of rstudio:
 rstudio depends on libssl1.0.0 | libssl1.0.2 | libssl1.1; however:
  Package libssl1.0.0 is not installed.
  Package libssl1.0.2 is not installed.
  Package libssl1.1 is not installed.
 rstudio depends on libclang-dev; however:
  Package libclang-dev is not installed.

dpkg: error processing package rstudio (--install):
 dependency problems - leaving unconfigured
Processing triggers for mailcap (3.70+nmu1ubuntu1) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu3) ...
Processing triggers for desktop-file-utils (0.26-1ubuntu3) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for shared-mime-info (2.1-2) ...
Errors were encountered while processing:
 rstudio

```

```
> apt list libssl*

Listing... Done
libssl-dev/jammy-updates,now 3.0.2-0ubuntu1.2 amd64 [installed]
libssl-dev/jammy-updates 3.0.2-0ubuntu1.2 i386
libssl-doc/jammy-updates,jammy-updates 3.0.2-0ubuntu1.2 all
libssl-ocaml-dev/jammy 0.5.10-1build2 amd64
libssl-ocaml/jammy 0.5.10-1build2 amd64
libssl-utils-clojure/jammy,jammy 3.3.0-1 all
libssl3/jammy-updates,now 3.0.2-0ubuntu1.2 amd64 [installed,automatic]
libssl3/jammy-updates 3.0.2-0ubuntu1.2 i386
```

maybe libssl3 should be supported.

**Comment by Quba1** [comment]
The problem is indeed with a fact that Ubuntu 22.04 does not provide libssl1.1 anymore.

[This StackOverflow thread](https://stackoverflow.com/questions/71962411/installing-r-studio-on-ubuntu-22-04) provides some workarounds how to install libssl1.1 on Ubuntu 22.04 but I couldn't make any of those suggestions work.

[This Rstudio Community thread](https://community.rstudio.com/t/rstudio-ide-desktop-2022-02-0-443-not-working-on-ubuntu-22-04-lts-some-gui-issue/135876) says that RStudio daily builds support Ubuntu 22.04 already so they can be installed instead.So support for Ubuntu 22.04 should arrive at some point. 

Personally, I think that RStudio website should clearly state that current stable version supports Ubuntu only up to 21.10.

**Comment by ronblum** [comment]
@Quba1 Thank you for providing guidance! And I'll put in a request that we state on the download pages that Prairie Trillium 2022.02.X is only for Ubuntu 18 and 20—now that 22.04 is live, "18+" is incorrect.
