### ISSUE TITLE
there is no quarto settings rmarkdown section in Rstudio Daily Build 

### ISSUE THREAD

**Issue by danieltomasz** [rstudio/rstudio#11262]
in `RStudio 2022.06.0-daily+421 "Spotted Wakerobin" Daily` there is no  Quarto section in rmarkdown preferenceres
The bundled version is quite old (`0.9.230`), there is a issue to update it https://github.com/rstudio/rstudio/issues/10920
But I would like to have an option to  choose and enable system binary `/Applications/quarto/bin/quarto` which is currently `v0.9.433` in similar way to `RStudio 2022.02.2+485 "Prairie Trillium" Release`

**Comment by ronblum** [comment]
The standalone binary at `/Applications/quarto/bin/quarto` should be getting precedence and getting used. Is there a symlink to it at `/usr/local/bin/quarto`, and is `/usr/local/bin` in PATH?

Updating the version installed with RStudio is in progress. The setting was meant for when Quarto in RStudio was still in a more experimental phase, in order to add Quarto to the new file menus only if explicitly desired. The setting is no longer needed because now Quarto is available in RStudio from the get go.

**Comment by danieltomasz** [comment]
Ok, I was confused with the disappearance of the menu
```
>library(quarto)
> quarto_path()
"/usr/local/bin/quarto"
````
points to the brew-installed binary (latest one) so I am closing the issue
