### ISSUE TITLE
respect quarto project-dir setting when running chunks interactively

### ISSUE THREAD

**Issue by jjallaire** [rstudio/rstudio#11361]
Originally reported here: https://github.com/quarto-dev/quarto-cli/issues/1059

Rmd editing has a mechanism for setting the execution directory for running chunks interactively. These (per-document) prefs are disabled for Quarto, however Quarto does have a mechanism within its project system to request that execution occur in the project root directory (document here: https://quarto.org/docs/projects/code-execution.html#working-dir)

We don't need to support all of the behaviors of Rmd in Qmd, but we should figure out a way to respect the `execute-dir` when set in the project. We have functions on the client and the server to determine if a given source file is within the "current" Quarto project within the IDE. We also have a way to access the Quarto project config on both the client and the server. Here I've enhanced that mechanism to have access to the `execute-dir`: https://github.com/rstudio/rstudio/commit/e286d65d8eaa0d79dd860227e5e47d91975de508

The value will be either `null`, `document`, or `project` (where `null` implies document, so all you need to check for is whether its equal to `project`.

I looked through the source code surrounding setting the working dir and its sufficiently layered and complicated (and touches not just execution but completion) that I didn't think it was safe for me to try to change. @kevinushey and @jmcphers I think one of you should take a look at this and figure out the right (i.e. minimal and safe) implementation. This is definitely something we need to do for SW as not having it breaks a major use case for Quarto projects.

**Comment by ronblum** [comment]
I've verified that `execute-dir: project` and when `execute-dir` is not set work on 
- RStudio Desktop 2022.06.0-daily+506 on MacOS 12.5
- RStudio Workbench 2022.06.0-daily+505.pro1 on Red Hat 8.5

Both options succeed and fail as expected depending on whether or not the files are in the expected directories.

However, the expected values are `file` and `project`, so `document` and `null` don't work.
<img width="435" alt="document" src="https://user-images.githubusercontent.com/31009952/173065377-212a8543-7c85-4c2c-b2d2-a77bb3344bc4.png">

<img width="450" alt="null" src="https://user-images.githubusercontent.com/31009952/173065499-143bad9a-c716-430f-9c60-af52afadab12.png">

**Comment by ronblum** [comment]
Note: PR #11370 refers to `file` though. Is this the expected value, not `document`? And should `null` be respected as a value?

**Comment by jmcphers** [comment]
I think that was a typo in JJ's notes. The Quarto docs only mention `project` as an allowable value.

https://quarto.org/docs/projects/code-execution.html#working-dir

However, `file` is technically valid as well according to the `_quarto.yml` schema.

https://github.com/quarto-dev/quarto-cli/blob/e271b8071bd19be34ef06b024950a3d31717ff51/src/resources/schema/project.yml#L13-L21

The value `null` is not valid; I think JJ was referring to the state wherein no value is set.

**Comment by ronblum** [comment]
In that case, all set!

**Comment by DarwinAwardWinner** [comment]
@ronblum I've downloaded the test release from the link you provided, and I'm still seeing this issue. Specifically, I have `execute-dir: file` and `getwd()` inside any chunk still returns my home directory. Are you certain this fix has been merged into the test release?

The RStudio version is RStudio 2022.07.1 Build 554 "Spotted Wakerobin" Release (7872775e, 2022-07-22) for Ubuntu Jammy, which also appears to match the release version at time of writing.

**Comment by ronblum** [comment]
@DarwinAwardWinner Thank you for raising this! I'm either unable to reproduce this, or else I'm not trying out some test cases correctly. Here's what I get when switching between `project` and `file` and using `getwd()`. (I'm cribbing the project provided at https://github.com/quarto-dev/quarto-cli/issues/1059#issue-1260697205 for this.)

https://user-images.githubusercontent.com/31009952/184144996-5a1eaf5c-5608-4a6c-9f05-15cbed731fbd.mov

This is in RStudio Desktop 2022.07.1+554 both on Ubuntu 22.04 and MacOS 12.5.

If this is behaving differently for you, or if I'm trying to do something different, would you be able to upload a simple projects—e.g. sample code in here or zipped? This way I can try to reproduce what you're seeing in the same way. Thanks!

**Comment by DarwinAwardWinner** [comment]
Ok, I see the problem. I misunderstood the docs. I found [this page](https://quarto.org/docs/projects/code-execution.html#working-dir), which said I could add the `execute-dir` option to my "config". However, what I didn't notice was that in this context, "config" means the config file for the project, *not* the yaml section at the top of the document. So when I create the following quarto document in an arbitrary directory (not a project directory), the `getwd()` always returns my home directory interactively:

<pre>
---
title: "Untitled"
author: "Ryan C. Thompson"
format: html
editor: visual
project:
    execute-dir: file
---

```{r}
getwd()
```
</pre>

![image](https://user-images.githubusercontent.com/228145/184253470-3d392336-7e1e-40a7-8e37-4556da88b190.png)

The interesting thing, though, is that when I render the document, `getwd()` *does* return the directory where the file resides:

![image](https://user-images.githubusercontent.com/228145/184253541-5cc2ed03-0367-49e4-a9d6-cd9f9776516c.png)

It would be nice RStudio could use the same working directory interactively as it does when rendering, though I guess that would be a different issue from this one.

(As for my nickname, I've been using it since I was a kid playing video games, in which one tends to die in embarrassing ways frequently.)

**Comment by Dijkie85** [comment]
Hello, I'been experimenting this issue in RStudio 2022.07.1+554 "Spotted Wakerobin" Release (7872775ebddc40635780ca1ed238934c3345c5de, 2022-07-22) for Ubuntu Jammy
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36.

Steps to reproduce:
1) Create new blank (ie., not Quarto) project with the wizard
2) Create a subfolder within the project folder
3) Create a Quarto doc in said subfolder
4) Add this to the YAML block:
```
---
title: "Untitled"
author: "Me"
format: html
project:
    execute-dir: project
---

```{r}
getwd()
```
5) You'll get the subfolder where the Qmd file is located, not the parent's, ie., the location of the project root.

**Comment by jaredlander** [comment]
I'm running Workbench version 2023.03.0+386.pro1 with Quarto version 1.2.335 with the following folder structure. The directory is an RStudio project and within there is a directory that holds the Quarto project, with all of the qmds in that directory. It is illustrated in the file tree below.

Rendering with Quarto from the CLI works as expected (I can't use `quarto::quarto_render()` because that doesn't give the option to specify profiles as far as I can tell). However, when running code interactively, like `getwd()` or `read.csv()`, it behaves as if my working directory is the RStudio project directory, rather than the Quarto project directory or the file's directory, regardless of what I set for `project.execute-dir` in _quarto.yml.

I watched the video posted in https://github.com/rstudio/rstudio/issues/11361#issuecomment-1212006095 and that is not what is happening on my setup. Could this be because my _quarto.yml is in a subdirectory rather than the root of the RStudio project?

```
.
├── book
│   ├── BasicData.qmd
│   ├── Basics.qmd
│   ├── Plotting.qmd
│   ├── _quarto-html.yml
│   ├── _quarto-pdf.yml
│   ├── _quarto.yml
│   ├── app1.qmd
│   ├── cover.png
│   ├── data
│   │   └── TomatoFirst.csv
│   ├── index.qmd
│   ├── intro.qmd
│   ├── latex
│   │   ├── after_body.tex
│   │   ├── before_body.tex
│   │   └── preamble.tex
│   ├── references.qmd
│   ├── summary.qmd
├── renv
│   ├── activate.R
│   ├── library
│   │   └── R-4.2
│   │       └── x86_64-pc-linux-gnu
│   ├── local
│   ├── settings.dcf
│   └── staging
├── renv.lock
└── tester.Rproj
```
