### ISSUE TITLE
Deno processes stick around if Quarto files not closed before closing RStudio

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#11487]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.07.0-preview+540
    OS Version      : Windows 11
    R Version       : 4.2.0

### Steps to reproduce the problem

Using RStudio Desktop on Windows:
1. Open the Windows Task Manager in order to view the running processes.
2. Open a Quarto document. The default is sufficient.
3. Render the document.
    - This creates a deno.exe process.
4. Close the document.
    - The deno.exe process terminates.
5. Open a Quarto document, whether the same or another.
6. Render the document.
    - This creates a deno.exe process.
7. Close RStudio Desktop. Do not close the document before exiting RStudio—it must be left open, or else the bug won't occur.
   - The deno.exe process continues to run. It might be a subprocess under an RStudio process that lingers.

### Describe the problem in detail

The deno.exe process sticks around. One problem that this creates is that when trying to install a new version of RStudio Desktop, the installation fails, warning that the process is still running.

### Describe the behavior you expected

The deno.exe process should terminate. This will allow users to install RStudio Desktop updates.

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jjallaire** [comment]
@kevinushey we noticed that the normal process termination code for deno processes wasn't actually working on Windows (esp. when it had a web server running). This extra sauce was added to the **stop** action for quarto preview jobs:

https://github.com/rstudio/rstudio/blob/main/src/cpp/session/modules/quarto/SessionQuartoJob.hpp#L59-L84

I think that to resolve this problem we just need to arrange for the **stop** code to be called on session shutdown. I looked a bit and wasn't confident that I could do this safely. I noticed that there is a cleanup operation that is called for each job but it wasn't clear how to hook into it. I also noticed that the jobs list was cleared on session shutdown so that also creates some potential order dependency.  

Thought it better that someone with a more recent "working set" in rsession make this change.

**Comment by ronblum** [comment]
Note: I checked Prairie Trillium, and the deno processes are closing properly.

**Comment by jjallaire** [comment]
Okay good. To be honest I was surprised that these processes were lingering because we run all child processes under a Job that should automatically clean them up. Let's definitely not do anything here unless/until there is a clearly reproducible case.

**Comment by gtritchie** [comment]
Yes, FWIW Electron should be doing the same on Windows (child processes close when the parent closes), but that job management part is inside Electron / node.js versus being done explicitely by our code in the Qt C++.

**Comment by kevinushey** [comment]
I'm not able to reproduce the issue as described in a recent preview release either (2022.07.0 Build 540, on Windows 11).

**Comment by gtritchie** [comment]
> Electron might not be creating the Job Object when launching the R session. @gtritchie This is done when we call the `initHook()` in the Qt desktop:

@jjallaire My (perhaps misguided) expectation was that this wouldn't be needed in Electron because node's process-creation routines (including the one we use to launch rsession, `spawn`) are supposed to be doing that by default on Windows (ensure child processes don't keep running when parent exits). Unless you specify the detach option.

https://nodejs.org/dist/latest-v16.x/docs/api/child_process.html#optionsdetached

That said, the docs don't elaborate on the underlying technique used to implement this, so perhaps it doesn't work for children of the children. Will need to experiment and see.

The rsession launching code is here, for reference: https://github.com/rstudio/rstudio/blob/09f60f0f76cdf6eb0d57e3ea2f2717fb2d273702/src/node/desktop/src/main/session-launcher.ts#L116

**Comment by gtritchie** [comment]
I was looking at this recently in the context of the urlopener.exe utility, comments here: https://github.com/rstudio/rstudio/issues/11439

**Comment by kevinushey** [comment]
It looks like node uses libuv for launching processes:

https://github.com/nodejs/node/blob/2bd940c0cb597f1de7dd3c0300bc57cb728106e8/src/process_wrap.cc#L262-L263

And that should be similarly using a job object to handle child processes on close:

https://github.com/nodejs/node/blob/2bd940c0cb597f1de7dd3c0300bc57cb728106e8/deps/uv/src/win/process.c#L67-L105

So the job infrastructure should already be there; we'll need to figure out why it's not behaving as we expect.

**Comment by kevinushey** [comment]
Ah, it's because node uses `JOB_OBJECT_LIMIT_SILENT_BREAKAWAY_OK` (which we don't in Qt desktop). Copying from their comment:

>    We're setting the JOB_OBJECT_LIMIT_SILENT_BREAKAWAY_OK flag so only the
>    processes that we explicitly add are affected, and *their* subprocesses
>    are not. This ensures that our child processes are not limited in their
>    ability to use job control on Windows versions that don't deal with
>    nested jobs (prior to Windows 8 / Server 2012). It also lets our child
>    processes created detached processes without explicitly breaking away
>    from job control (which uv_spawn doesn't, either).

And indeed, from https://docs.microsoft.com/en-us/windows/win32/procthread/job-objects:

> If the job has the extended limit JOB_OBJECT_LIMIT_SILENT_BREAKAWAY_OK, then child processes of any parent process associated with the job are not associated with the job. It is not necessary for parent processes to be created with the CREATE_BREAKAWAY_FROM_JOB flag.

I think this implies that we need to explicitly force any child processes launched on Windows with Electron to be associated with the parent job object.

**Comment by kevinushey** [comment]
In other words, I think we need to explicitly use `AssignProcessToJobObject()` after processes are created here:

https://github.com/rstudio/rstudio/blob/d5a1bc209137589551f02a357ba88d0c74ef3e05/src/cpp/core/system/Win32ChildProcess.cpp#L530-L549

since effectively, node is forcing the default behavior to be "breakaway from job" for the processes we create.

**Comment by ronblum** [comment]
Verified using the above steps in RStudio Desktop 2022.11.0+91 on Windows 11 with R 4.2.0. Tried with both the bundled and standalone Quarto CLI, both version 1.0.38.
