### ISSUE TITLE
Code examples with scrollbar in R 4.2.0 Help Pane don't have a solid gray background

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#11520]
### System details

    RStudio Edition : Desktop and Server
    RStudio Version : 2022.07.0-preview+543
    OS Version      : MacOS 12.5, Windows 11, Ubuntu 20.04 via Chrome and Safari on MacOS 12.5
    R Version       : 4.2.0

### Steps to reproduce the problem

1. In Console Pane: `??dplyr`
2. In Help Pane: Click on the Vignette `dplyr::dplyr`
3. Scroll down till reaching a code example.
    - The code example should be on a solid background.
5. Shrink the width of the Help Pane enough that a scroll bar appears for the code.
6. Scroll right.
    - Only the rows that are too long for the window are on a solid (gray) background. The rest of the code block is on a white or black background, in accordance with the light or dark theme.

### Describe the problem in detail

The background is no longer a solid block.

<img width="311" alt="Screen Shot 2022-06-28 at 10 48 37 AM" src="https://user-images.githubusercontent.com/31009952/176211146-1bbd7ee0-c04c-4ce9-8bd3-4ec98234830c.png">

### Describe the behavior you expected

The block should remain a solid block.

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Compare this to using `?data.frame` which works correctly:
<img width="312" alt="dataframe" src="https://user-images.githubusercontent.com/31009952/176431706-58616f29-40fe-4da9-918c-6f281ea71fa2.png">

**Comment by kevinushey** [comment]
The issue here is that the CSS background is applied to the inner pre element, but not the div containing the code.

https://github.com/rstudio/rstudio/blob/14f8bf3517f17220d6727aa9fc9e9eeeff951b31/src/gwt/src/org/rstudio/studio/client/workbench/views/help/HelpPaneEditorStyles.css#L78-L83

We might be able to resolve this by including `div.sourceCode` in the CSS rule here.

<img width="322" alt="Screen Shot 2022-06-29 at 10 56 32 AM" src="https://user-images.githubusercontent.com/1976582/176504134-1d6c8df4-5c83-473b-b169-8dd5b3289ece.png">


<img width="618" alt="Screen Shot 2022-06-29 at 10 56 37 AM" src="https://user-images.githubusercontent.com/1976582/176504112-7ef451de-f16d-47bf-a8c6-97cb1459306e.png">

**Comment by sharon-wang** [comment]
Looking into this!

**Comment by ronblum** [comment]
Verified in RStudio 2023.03.0-daily+270 on MacOS 13.2. Here's the same example now:


![Image](https://user-images.githubusercontent.com/31009952/214418479-f6b74c07-cb75-4e21-b5a1-249e78648025.png)
