### ISSUE TITLE
[FR]: Introduce syntax highlighting for in-body syntax for chunk options in `.Rmd` docs

### ISSUE THREAD

**Issue by IndrajeetPatil** [rstudio/rstudio#11663]
Currently, the  in-body syntax for chunk options can't be easily visually distinguished from comments.  

<img width="478" alt="Screenshot 2022-07-23 at 11 07 58" src="https://user-images.githubusercontent.com/11330453/180598470-bca82081-3f9d-47d5-b9b2-affdcac07f33.png">

It'd be great if the options were highlighted, so that they can be distinguished from values, and the entire block of options can be distinguished from comments.

One option could do something similar to how Roxygen comments are highlighted:

<img width="553" alt="Screenshot 2022-07-23 at 11 09 36" src="https://user-images.githubusercontent.com/11330453/180598529-7839b04f-5407-4540-bec4-f22749a2a7f2.png">

cc @cderv

**Comment by kevinushey** [comment]
In theory we could highlight the code here either as R or YAML but unfortunately the fact that users can use _either_ format without explicitly declaring it makes it harder for us to know up-front whether we're parsing YAML or R code.

**Comment by romainfrancois** [comment]
The situation is a little better with the some themes: 

default: 

<img width="452" alt="image" src="https://user-images.githubusercontent.com/2625526/186875831-d9f7d34c-9128-40ef-b17c-34be079fb4bf.png">

ambiance: 

<img width="647" alt="image" src="https://user-images.githubusercontent.com/2625526/186877480-b15fa272-d6fe-4a47-8c15-1ad20bb53ae9.png">


These comments are given a different set of classes since #9626

![image](https://user-images.githubusercontent.com/2625526/186876006-1d9f41dd-4f7e-44d4-94b9-2e0a418f6fe4.png)

But only some themes define styles for this: 

![image](https://user-images.githubusercontent.com/2625526/186876864-84d598e9-e4c5-4679-ad36-95a1fca02e06.png)

**Comment by cderv** [comment]
Please unstale :) I still think this should be improved

**Comment by cderv** [comment]
Please unstale :) I still think this should be improved

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2023.12.0-daily+165 on MacOS 14 with dark themes (Chaos and Dracula) and light (Chrome).
