### ISSUE TITLE
RStudio freezes when computer goes to sleep/hibernation....

### ISSUE THREAD

**Issue by GabryS3** [rstudio/rstudio#11696]
### System details

    RStudio Edition : <Desktop version >
    RStudio Version : 2022.07.0 Build 548
    OS Version      : Windows 10 Enterprise - version 21H2 (OS build: 19044.1766)
    R Version       : 2022.07.0 Build 548

### Steps to reproduce the problem
Open RStudio - start working on a script - then leave RStudio open (without any process running though) - and leave the computer (still charging) for a while (computer goes into sleep/hibernation) -> return to computer - RStudio has frozen...

### Describe the problem in detail
see above...there is not much to add to that description..

This issue seems to have been reported previously (https://github.com/rstudio/rstudio/issues/5927) but the post was closed and no real solution provided...

### Describe the behavior you expected
I expect to be able to return toRStudio and be able to continue working on it straight away...not sure if this is a graphic card problem or a RStudio issue?
!-->

- [ YES] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports). --> YES
- [ YES] I have installed the latest version of RStudio, and confirmed that the issue still persists. --> YES
- [NO  - see comment as to why at the end of this line] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report). --> I can't run a diagnostic report...because RStudio is frozen and the issues is that it freezes so I am not sure how to run a diagnostic report if RStudio is frozen... 
- [YES ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue. --> i think so

**Comment by GabryS3** [comment]
Hi Rob,
Thank you for your reply.

1)
I am a bit confused about this Electron version.
In this post  RStudio Electron Preview Release Notes – RStudio Support<https://support.rstudio.com/hc/en-us/articles/5773239924375>, it says
“The Electron-based IDE will replace the QtWebEngine version entirely in a future release, but for now is considered experimental and should not be used for production work. Most users should continue using the QtWebEngine-based desktop release.”

As I am using R for work, I cannot afford to try things out and I need to ensure I work with a stable version of RStudio Desktop. Is there any Electron version which is established and ok to use for work at this stage?
Which is the upcoming RStudio Desktop release? A new version of RStudio Desktop which is established and approved for work purposes (not testing)? And when will it be available?


2)
Also, I am a lot concerned by the coding changes. In the same post above, it says:
“Note that this isn't a ground-up rewrite of the RStudio IDE; the vast majority of the underlying code is identical between the Electron and Qt versions.”
So, does this mean that the coding system/language will partially change once the Electron version has been established (or is already partially different in the currently available Electron version?


3)
What does it mean that the upcoming RStudio Desktop release (version for testing only (not for work) – at least for now correct?) can be run using an installer-less build? It means it is a portable version and thus can be run separately and independently of the normal established/installed RStudio Version? (they can be available/present on the same computer at the same time?)


4) Is an established electro version of RStudio already available?
Is this one an established version (ok for work – not for testing purposes) -->
RStudio 2022.07.1+554 - Windows 10/11 (64-bit)<https://s3.amazonaws.com/rstudio-ide-build/electron/windows/RStudio-2022.07.1-554.exe>  (at RStudio Preview - RStudio<https://www.rstudio.com/products/rstudio/download/preview/>)

Thank you for any clarifications you can provide.
Best,
Gabriella

**Comment by GabryS3** [comment]
Hi Rob,
Thank you for your reply.

1)
I am a bit confused about this Electron version.
In this post  [RStudio Electron Preview Release Notes – RStudio Support](https://support.rstudio.com/hc/en-us/articles/5773239924375), it says
“The Electron-based IDE will replace the QtWebEngine version entirely in a future release, but for now is considered experimental and should not be used for production work. Most users should continue using the QtWebEngine-based desktop release.”

As I am using R for work, I cannot afford to try things out and I need to ensure I work with a stable version of RStudio Desktop. Is there any Electron version which is established and ok to use for work at this stage?
Which is the upcoming RStudio Desktop release? A new version of RStudio Desktop which is established and approved for work purposes (not testing)? And when will it be available? 


2)
Also, I am a lot concerned by the coding changes. In the same post above, it says:
“Note that this isn't a ground-up rewrite of the RStudio IDE; the vast majority of the underlying code is identical between the Electron and Qt versions.”
So, does this mean that the coding system/language will partially change once the Electron version has been established (or is already partially different in the currently available Electron version?


3)
What does it mean that the upcoming RStudio Desktop release (version for testing only (not for work) – at least for now correct?) can be run using an installer-less build? It means it is a portable version and thus can be run separately and independently of the normal established/installed RStudio Version? (they can be available/present on the same computer at the same time?)


4) Is an established electro version of RStudio already available?
Is this one an established version (ok for work – not for testing purposes) 
[RStudio 2022.07.1+554 - Windows 10/11 (64-bit)](https://s3.amazonaws.com/rstudio-ide-build/electron/windows/RStudio-2022.07.1-554.exe)  (at [RStudio Preview - RStudio](https://www.rstudio.com/products/rstudio/download/preview/))

Thank you for any clarifications you can provide.
Best,
Gabriella

**Comment by GabryS3** [comment]
Also,,, if the available Electron version is only "for testing" (experimental) - I cannot use it for work...
So, would there be another option to solve this freezing issues in the RStudio version  I currently have?
Thanks
Gabriella

**Comment by ronblum** [comment]
@GabryS3 Unfortunately, there is no fix for the current stable version of RStudio. We've been struggling to fix this in the current framework (Qt WebEngine), especially since we haven't been able to reproduce the issue internally. The only solution seems to be the new framework (Electron). 

I can answer a few of the questions:

1) No, there isn't a stable version yet of RStudio Desktop using Electron. The open source version 2022.11.0 is working well, but It's still an active work in progress—both development and testing—so we can't guarantee its stability yet. So any concern you have about using it for production work is justified. The release is expected later this year, and barring any major problems, is expected to be completed and released in November. This isn't a guarantee, though truth be told, we would also be unhappy if the date slipped.

2) The coding change affects some of the underlying code, but most will remain the same. However, in terms of your work, it should be transparent—the Electron version should work the same way as the Qt version, plus the usual bug fixes and enhancements. Basically, the change should be transparent to you—you'll be able to write any code, work with projects, etc., the same as you currently do.

3) The installer-less version will let you run the new version almost independently, side-by-side by an installed version. The main overlap is that both are using the information in `%localappdata%\RStudio` and `%appdata%\RStudio` including some of the preferences you set. @timtmok can you confirm, and are there other things, esp. session information, that could intefere?

4) The 2022.07.1+554 Electron version is a preview version, as it was still in development. The current 2022.11.0 is the continued work from it. So most of the work (for the open source) is pretty settled, but still not stable. @timtmok would you be able to provide a little more information about the general state of the open source version?

So, we're still in a state of flux. Your concerns about using it  for work are justified. I'm sorry that I can't provide better answers for you.

**Comment by timtmok** [comment]
> 2. The coding change affects some of the underlying code, but most will remain the same. However, in terms of your work, it should be transparent—the Electron version should work the same way as the Qt version, plus the usual bug fixes and enhancements. Basically, the change should be transparent to you—you'll be able to write any code, work with projects, etc., the same as you currently do.

For further clarity, the UI is pretty much 99% the same since Electron is reusing the same code. There will be slight changes in the main menus as Electron handles displaying that now but the underlying code for the action is still the same. The hooks into the R session are still the same and untouched. The way I think of it, Electron is the new container that connects the R session to the UI and taking over non-UI things that are not related to the R session hooks (e.g. instance handling, native dialogs, preferences, window management, among other things).

> 3. The installer-less version will let you run the new version almost independently, side-by-side by an installed version. The main overlap is that both are using the information in `%localappdata%\RStudio` and `%appdata%\RStudio` including some of the preferences you set. @timtmok can you confirm, and are there other things, especially session information, that 
could interfere?

There would be no interference with the preferences. With the move to Electron, the preferences were moved to a more appropriate location that makes sense for the platform. It migrates the existing preferences and keeps the old data. So you can change a preference when using Electron but it may not be updated when using Qt.

This is the user state that was migrated, which is one part of the preferences that are saved: https://github.com/rstudio/rstudio/blob/bugfix/electron-instance-handling/src/node/desktop/src/types/user-state-schema.d.ts
Note: not all of the preferences are currently read in Electron from the migrated location as it may not be implemented yet

**Comment by ronblum** [comment]
@timtmok Thank you, especially for the correcting me in no. 3, that it's only that some preferences might not get updated, not that they might be changed.

**Comment by GabryS3** [comment]
Hi Ron & Tim,
Thank you both for all your detailed explanations and quick reply!
I really appreciated it and things are clearer to me now.

On this note though, I found in a post this info from one of the users regarding the RStudio freezing issue:
https://github.com/rstudio/rstudio/issues/5927

ericvaughn11<https://github.com/ericvaughn11> commented on 5 Mar<https://github.com/rstudio/rstudio/issues/5927#issuecomment-1059358587>
Also adding that this issue persists for me on an Asus ROG Strix with both Windows 10 and Windows 11. Does indeed seem to be related to hibernation as keeping my laptop plugged in (where it won't hibernate, but does sleep) prevents RStudio from hanging. It's a bit frustrating because using software rendering doesn't seem to allow me to use Plotly, which I need for 3D plots I produce.
I'll report back if the problem comes up again, but I may have a cure (which I don't fully understand) that seems to work. I figured the computer graphics and Rstudio aren't playing nice at some point when Windows switches to low power hibernate, so I went into the nvidia control panel and switched Rstudio's preferred graphics processor from the default (Integrated) GPU, to my RTX3070 GPU (High Performance Nvidia GPU). I forced Windows to hibernate on battery and on power and don't seem to be getting any freezing anymore. Fingers crossed! Figured I'd post this now before I forget and maybe it'll help some of the others dealing with this pesky issue!
I cannot test this on my computer because it’s a work computer and I don’t have administrator’s rights to change the graphic card settings. However, I did try to leave RStudio open (without any process running) but minimise the RStudio window instead of leaving it open on the screen…and I hibernated the computer. Next day…RStudio was still running ok and not frozen…so it might really be something related to the graphic settings in the computer & RStudio?

Just a hint that may help solve this issue.

Thanks a lot!
Best,
Gabriella
