### ISSUE TITLE
`devtools::check()` and `cleanup`

### ISSUE THREAD

**Issue by fweber144** [rstudio/rstudio#11706]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2022.07.1+554 "Spotted Wakerobin" Release (7872775ebddc40635780ca1ed238934c3345c5de, 2022-07-22) for Ubuntu Jammy; Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36
    OS Version      : Ubuntu 22.04.1 LTS
    R Version       : 4.2.1 (2022-06-23)

### Steps to reproduce the problem

See https://github.com/r-lib/devtools/issues/2448#issuecomment-1192858045 and https://github.com/r-lib/devtools/issues/2448#issuecomment-1206127954.

### Describe the problem in detail

See https://github.com/r-lib/devtools/issues/2448#issuecomment-1192858045 and https://github.com/r-lib/devtools/issues/2448#issuecomment-1206127954.

### Describe the behavior you expected

See https://github.com/r-lib/devtools/issues/2448#issuecomment-1192858045 and https://github.com/r-lib/devtools/issues/2448#issuecomment-1206127954.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Cross-posting from the other issue:

---

For reference, this is where the IDE was relying on cleanup = FALSE for devtools::check():

https://github.com/rstudio/rstudio/blob/175f031b4f193f6a971163f088227c68d5fc569e/src/cpp/session/modules/build/SessionBuild.cpp#L1080-L1081

I'm guessing most users left the default preferences here, hence why this is the first time we're seeing this now.

This is where Hadley made the change:

https://github.com/r-lib/devtools/commit/7cc2bdf74cbae90233fa6c84f221631d1876598d#diff-580bc730038e74accf0289eb2f9bfae59d84a9d79a9b096546f57bafaf85f9a7R79

Was that change really intentional? If so, it seems like it should be accompanied by a NEWS entry?

It seems like, as far as the IDE is concerned, we can just stop using cleanup = FALSE and rely on our own code which manually deletes the .Rcheck directory (if appropriate) after calling devtools::check().

Marking for EG as the fix should be straightforward (stop using `cleanup = FALSE` with newer `devtools`).

**Comment by jonvanausdeln** [comment]
Verified on 2022.11.0-daily+215
Windows 11, Ubuntu 22.04

Tested with devtools 2.4.3 and 2.4.4.  Behaved as expected.
