### ISSUE TITLE
RMarkdown chunk's "Show in New Window" button has an problem with the graphics engine

### ISSUE THREAD

**Issue by steveharoz** [rstudio/rstudio#11805]
### System details

    RStudio Edition : Dekstop
    RStudio Version : 2022.07.1
    OS Version      :  Windows 11
    R Version       :  4.2.1

### Steps to reproduce the problem

1. Get a custom font of your choice: "my_custom_font.ttf"
2. In RStudio -> Tools -> Global Options... -> General -> Graphics. Set the Backend to AGG.
3. Create an RMD with the following code:

`````
---
title: "asdfasdf"
output:
  html_document: 
    dev: ragg_png
---

```{r}
library(tidyverse)
library(systemfonts)
register_font("my_custom_font", "my_custom_font.ttf")


ggplot(mtcars) +
  aes(x=wt, y=hp) +
  geom_point() +
  theme(text = element_text(family="my_custom_font"))
```
`````

4. If you press play on the code chunk, it should work with the custom font and AGG as expected.
![image](https://user-images.githubusercontent.com/2257540/185757382-d5755877-1cff-4fd5-8d7e-39a40e824695.png)
5. But if you click "show in new window", it ignores the custom font.
![image](https://user-images.githubusercontent.com/2257540/185757547-2fee196f-1318-4bc3-af97-ce63d8c06b2a.png)

### Describe the problem in detail

The show in new window button doesn't render graphs correctly.

![image](https://user-images.githubusercontent.com/2257540/185757547-2fee196f-1318-4bc3-af97-ce63d8c06b2a.png)

### Describe the behavior you expected

Inline in the document, it looks fine:  
![image](https://user-images.githubusercontent.com/2257540/185757649-e9091689-d1a8-44f8-8b91-518139a8dd94.png)

But clicking the new window, custom fonts fail:  
![image](https://user-images.githubusercontent.com/2257540/185757712-f8571563-7ffb-4720-9981-438e2113dd4f.png)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by steveharoz** [comment]
Tagging @thomasp85 just in case this is an AGG bug.

**Comment by thomasp85** [comment]
Hmm... It may be more about how the graphics is replayed and if it is done so in another session. If it is in another session then the fonts aren't registered and the device will fall back to the default

**Comment by kevinushey** [comment]
The same thing can be seen if you resize the RStudio editor (so that the plot is redrawn to fill the new visible region).

It looks like we replay plots in a separate R process, mostly via the code here:

https://github.com/rstudio/rstudio/blob/main/src/cpp/session/modules/rmarkdown/NotebookPlotReplay.cpp

https://github.com/rstudio/rstudio/blob/82e0174552930e6dc7d9f1a66baa0922576a1720/src/cpp/session/modules/NotebookPlots.R#L104-L179

My guess is that the registered fonts aren't propagated to the sub-process that's trying to re-render plots here, hence why this issue occurs.

**Comment by thomasp85** [comment]
Is there anything I can do in systemfonts to make it easier to port over registered fonts?

**Comment by kevinushey** [comment]
It feels tricky. As I understand it, we're basically doing something like:

1. Use `recordPlot()` to save the current plot, and write that to disk;
2. In a separate process, setup a graphics device, load the saved plot, and then run `replayPlot()`.

Is it possible to register custom hooks to be run when the plot is restored, or anything like that? Or, could the recorded plot be tagged with the set of registered fonts, so that RStudio could try to restore those when rendering the plot?

It sort of feels like the onus is on RStudio to manage all this, though. For example, we could run these notebook-replaying plots with a custom `.Rprofile`, whose contents are generated based on other requirements for plot generation (e.g. registering already-registered system fonts). In addition, we likely need to do this already so that the correct graphics device is used when replaying plots as well.

Does `systemfonts` provide a way to list all fonts that have been registered?

**Comment by thomasp85** [comment]
There is `systemfonts::registry_fonts()` which provide the info in a data.frame, but it doesn't really translate directly to how you specify these in a new session:

```r
> systemfonts::register_variant(name = 'test font', family = 'Spectral', weight = c('medium', 'ultrabold'))
> systemfonts::registry_fonts()
# A tibble: 4 × 7
  path                                               index family    style       weight italic features 
  <chr>                                              <int> <chr>     <chr>       <ord>  <lgl>  <list>   
1 /Users/thomas/Library/Fonts/Spectral 500.ttf           0 test font Regular     normal FALSE  <int [0]>
2 /Users/thomas/Library/Fonts/Spectral 800.ttf           0 test font Bold        bold   FALSE  <int [0]>
3 /Users/thomas/Library/Fonts/Spectral 500italic.ttf     0 test font Italic      normal TRUE   <int [0]>
4 /Users/thomas/Library/Fonts/Spectral 800italic.ttf     0 test font Bold Italic bold   TRUE   <int [0]>
```

I'd be happy to add some functionality that made it easier to save and load the font registry
