### ISSUE TITLE
Change notarization tool for macos builds from altool to notarytool

### ISSUE THREAD

**Issue by GCRev** [rstudio/rstudio#11863]
Mac builds are now presenting warnings about the imminent deprecation of the `altool` we use in order to notarize the electron code.

```
ltool has been deprecated and, starting in fall 2023, will no longer be supported by the Apple notary service. You should start using notarytool to notarize your software.
```

We should consider replacing this tool in our pipeline to silence the warning and prepare for deprecation.

**Comment by timtmok** [comment]
Notarization command: `xcrun notarytool submit --wait --apple-id <apple id> --password <apple id password> --team-id <team id where apple id is a member> <path to file>`

The branch `feature/macos-notarytool` has changes in progress to use `notarytool`. It is blocked because a team id is required for the notarization command. This is new in the notarization process.

@jmcphers Is your Apple ID dev account connected to any team? This appears to be a required argument for notarization. In any case, it may make sense to wait until SRE has created a team account to update the notarization step.

**Comment by jmcphers** [comment]
Yes it is, I'm part of the RStudio developer team. The team ID is `FYF2F5GFX4`.

**Comment by timtmok** [comment]
I'm going to wait for the Apple ID to get sorted before making any changes to the notarization credentials. Changes are on `feature/macos-notarytool`. There will be some merge conflicts to resolve since the Jenkinsfile refactor will merge soon that changes the name of the environment variables holding the credentials.

To update the branch after the Apple ID has been created:
* Apple ID must be added to the RStudio team
* Team ID needs updating in `notarize-release.sh`
* Generate an app-specific password in the Apple dev account
* Update Jenkins credentials with the Apple ID loging and app-specific password

**Comment by MariaSemple** [comment]
@timtmok It seems like there might be a risk that we don't get the Apple ID before `altool` is completely deprecated. Can we merge the notarytool changes for now and update the Apple ID later?

**Comment by jmcphers** [comment]
Deadline is November 1 according to Apple:

> the Apple notary service will no longer accept uploads from altool as of November 1, 2023. Existing notarized software will continue to function properly.

**Comment by timtmok** [comment]
@jmcphers I think we'll have to go ahead and have an app-specific password with your account until an org account is ready to replace it.

**Comment by jmcphers** [comment]
That's fine. There's already an app-specific password for my account in Jenkins; LMK if you need another one (and/or need that one refreshed).

**Comment by timtmok** [comment]
Thank you for closing it! I forgot that the issue status doesn't change when changing the project status.
