### ISSUE TITLE
Quitting RStudio takes two steps with daily builds

### ISSUE THREAD

**Issue by psads-git** [rstudio/rstudio#11952]
I am using 

[RStudio Desktop Electron for Fedora 36 / RedHat 9 (Daily builds)](https://s3.amazonaws.com/rstudio-ide-build/electron/fedora36/x86_64/rstudio-2022.07.2-576-x86_64.rpm)

When using a Python script file, after having run some code, exiting RStudio gives the following message:

![image](https://user-images.githubusercontent.com/75945439/190356259-175e220a-6b8d-4a51-8286-e4d84afdfabe.png)

After having clicked `No`, exiting RStudio goes fine, without any popup message.

Should not RStudio exit immediately without any popup message?

**Comment by kevinushey** [comment]
For reference, I think this occurs whenever the Python REPL is active. This happens because RStudio calls `reticulate::repl_python()`, which reads input from the user and executes it.

In other words, strictly speaking the R session is "busy" running the Python REPL, hence why we get this message. We should probably detect and handle this specific case.

We might need the reticulate REPL to set a flag that RStudio can read to infer whether it's currently just waiting for input from the user.
