### ISSUE TITLE
Rebranding: Change email address in Open Source Components to use posit.co

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#12015]
In RStudio Server or RStudio Desktop:
- <kbd>Help -> About -> Open Source Components</kbd>

Most of the references refer to *RStudio* the product. However, we'll need to change the email address at some point from `info@rstudio.com` to `info@posit.co`, but only when all of the email domain changes are set.

**Comment by ronblum** [comment]
Triage: Consider for Elsbeth Geranium as part of rebranding, but functionally it's not urgent because the current `rstudio.com` address should continue to work.

**Comment by mikebessuille** [comment]
"In the alternate, you may request a copy of the source code for
any of these components by e-mail to info@rstudio.com."    We need to change this to info@posit.com.  In the future we could remove the whole sentence, and potentially put all that open source information into a web page and link to it, instead of showing it in the about box.

**Comment by ronblum** [comment]
Verified in
- RStudio Desktop 2022.12.0-daily+286 on SLES 15 SP4
- RStudio Desktop 2022.12.0-preview+299 on MacOS 13

I'll open an issue for switching to using a web page.
