### ISSUE TITLE
Support running of PyShiny applications

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#12054]
Copying from https://github.com/rstudio/rstudio/pull/12051:

To see this feature in action

1. Grab an example from https://shinylive.io/py/examples/, and save it as an app.py file.

2. Open that file in RStudio, and hit the "Run App" button to see it launch in a new window.

3. Arrange the app window and the RStudio window so that you can see them both, and make a trivial change to app.py. When you hit Save, you should see the app window reload itself.

**Comment by romainfrancois** [comment]
🎉 

![image](https://user-images.githubusercontent.com/2625526/193025158-683ed65f-76a9-47ff-9361-3c0d30e26ead.png)

**Comment by romainfrancois** [comment]
I had to `pip install shiny` first, otherwise the `Run App` still sends the command to the terminal and we get this: 

<img width="647" alt="image" src="https://user-images.githubusercontent.com/2625526/193029251-223b3ceb-e94b-4f54-af6e-00990152d91f.png">

maybe `runPyShinyApp` could first do a `which shiny` and then open a dialog if not installed ?

**Comment by jgutman** [comment]
Actually `pip install shiny` will currently not install the correct version of shiny for this functionality. But you bring up a really good point about if users have not previously installed `shiny`. I think we should leave as is for now and open a separate issue for that. 

Thanks for opening this issue, but we were already tracking this in rstudio-pro #3595, so this is a duplicate
