### ISSUE TITLE
False warning about Quarto CLI

### ISSUE THREAD

**Issue by lpechacek** [rstudio/rstudio#12169]
### System details

    RStudio Edition : Desktop and Server
    RStudio Version : 2022.07.2-576
    OS Version      : openSUSE Tumbleweed 20221016
    R Version       : 4.2.1

### Steps to reproduce the problem
1. Start RStudio

### Describe the problem in detail
At the bottom of the window there is a warning saying that Quarto CLI is installed, however, RStudion requires a different version. That is not true, there are no traces of Quarto on my system.

### Describe the behavior you expected
RStudion should avoid false claims about Quarto presence on the system.

### Workaround
Set `RSTUDIO_QUARTO` environment variable to `/bin/true`. E.g. start RStudio with `RSTUDIO_QUARTO=/bin/true rstudio`.

### Discussion
The warning is emitted at [SessionQuarto.cpp:269](https://github.com/rstudio/rstudio/blob/1ecc5249012170a256e7159e13b73dd6b7830f1c/src/cpp/session/modules/quarto/SessionQuarto.cpp#L269). That is because `readQuartoVersion(embeddedQuartoPath)` returns an empty version due to the absence of (the embedded) Quarto on the system. `embeddedVersion` then compares lower than the required version at line 248 and the warning is triggered at line 269. IMO, RStudio should keep silent when Quarto is not on the system.

### Proposed patch
```
From: Libor Pechacek <lpechacek@gmx.com>
Date: Mon, 17 Oct 2022 22:14:12 +0200
Subject: [PATCH] Avoid false warning in absence of Quarto

When Quarto is not found, RStudio should not issue the CLI
warning.

--- a/src/cpp/session/modules/quarto/SessionQuarto.cpp
+++ b/src/cpp/session/modules/quarto/SessionQuarto.cpp
@@ -268,7 +268,7 @@ void detectQuartoInstallation()
          LOG_ERROR(error);
       }
    }
-   else
+   else if (!embeddedVersion.empty())
    {
       showQuartoVersionWarning(embeddedVersion, kQuartoRequiredVersion);
    }
```

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by mikebessuille** [comment]
@lpechacek thanks for contributing!  We'll have a  look.

**Comment by jgutman** [comment]
1. If you run `install.packages("quarto"); quarto::quarto_path(); quarto::quarto_version()` what does it return?
2. Do you see the same warning message in one of the later daily builds installed from https://dailies.rstudio.com ?

the embedded quarto path should not be empty here, and it's not clear to me why it would be empty for you here

**Comment by jgutman** [comment]
Ah okay. Yes, we also bundle Quarto in our release builds of RStudio, which
is why we always assume there is an embedded version, but since this is
installed from the OpenSUSE shipping distro makes sense why Quarto is not
included in this case. Thanks for clarifying

**Comment by timtmok** [comment]
I'm not sure if SUSE intends to exclude Quarto from their builds but this is the patch that causes this issue: https://build.opensuse.org/package/view_file/devel:languages:R:released/rstudio/0002-Don-t-install-pandoc-and-mathjax.patch?expand=1

The subsequent patch to address the warning is likely fine. Although, I'm not sure why those patches decided to exclude those dependencies. The patch history seems to indicate that the pandoc and mathjax inclusion would introduce many other dependencies. Deciding to also exclude Quarto is fair since it bundles pandoc. I believe pandoc is required for Quarto and if they don't want to build pandoc then it will need to be excluded.

I think what's packaged will allow Quarto to be installed separately as is reported here. So any users that do want Quarto functionality can get it by installing Quarto. As long as SUSE keeps the `QUARTO_ENABLED` CMake global set, the code will support a user-installed Quarto.

**Comment by aaronpuchert** [comment]
> I'm not sure if SUSE intends to exclude Quarto from their builds

Might [have been me](https://build.opensuse.org/request/show/978774) who did that. (At least for Quarto.) Our builds have no network access for reproducibility, thus all dependencies need to be packaged. At the time I just wanted to update the RStudio version that we ship and since we don't have Quarto packaged yet I just cut it out. Once that changes we might include it.

For my use of RStudio it's not relevant, and if somebody wants it in the distro package, they'll have to package it themselves. (I know my way around C++, but Node is not my field.)
 
> The subsequent patch to address the warning is likely fine. Although, I'm not sure why those patches decided to exclude those dependencies. The patch history seems to indicate that the pandoc and mathjax inclusion would introduce many other dependencies. Deciding to also exclude Quarto is fair since it bundles pandoc. I believe pandoc is required for Quarto and if they don't want to build pandoc then it will need to be excluded.

MathJax and pandoc are available, but via separate distro-provided packages. We call this “unbundling”: remove the bundled dependencies from the build and installation, then set dependencies to the separate packages. We do the same for libclang, hunspell, Node.JS and maybe more. The distro-provided packages are often more recent and adjusted to the particular environment, possibly with patches of their own. Also they can be shared with other applications.

> I think what's packaged will allow Quarto to be installed separately as is reported here. So any users that do want Quarto functionality can get it by installing Quarto. As long as SUSE keeps the `QUARTO_ENABLED` CMake global set, the code will support a user-installed Quarto.

That's good to hear. If someone decides to try it and it doesn't work we'll hopefully get a report on our bug tracker and can look into it.

**Comment by aaronpuchert** [comment]
> > I'm not sure if SUSE intends to exclude Quarto from their builds
> 
> Might [have been me](https://build.opensuse.org/request/show/978774) who did that.

Yep, found an old [comment](https://bugzilla.opensuse.org/show_bug.cgi?id=1198936#c7).
