### ISSUE TITLE
Opening .qmd in RStudio visual editor changes line numbering (especially for display style equations)

### ISSUE THREAD

**Issue by halidaee** [rstudio/rstudio#12238]
Hello,

I mostly edit .qmd in VScode but occasionally switch to RStudio to use the visual editor for idiosyncratic reasons. I've noticed when subsequently switching back to VScode that my line numbering has been changed around inline math. For example, if I originally had

```
The equation is 
$$
Y = ax + b.
$$

That is a line.

``` 

This is then converted to something like 

```
The equation is $$
Y = ax + b.
$$ That is a line.

``` 
which creates problems down the line for code coloring and folding. 

Running RStudio 2022.07.0 Build 548 on macOS Ventura (but also experienced this issue before upgrading to Ventura).

**Comment by ronblum** [comment]
@halidaee Thank you for raising this! It might be something that Pandoc is doing intentionally, but I'll mark it for review to see what control we have over it.

Note: Reproducible going back to RStudio Desktop 1.4.1743 on MacOS 13.

**Comment by DavZim** [comment]
On a similar note, when I use escaped inline R code (eg I want to display verbatim code without executing the R code, eg `r 1+1`).
In Quarto I would use the following code

```markdown
`` `r
mycode(123)` ``
```
note the newline that prohibits Quarto from detecting the inline R code and leaving it as is.

When switching to the visual editor and back to the code view, the code is changed to this:

```markdown
`` `r mycode(123)` ``
```

Therefore the inline code is detected and is being executed (not wanted in this case).

Note that this happens when switching the code editor view, there is no rendering involved.

(On a separate note, I and my team love the visual editor, which lowers the learning curve especially for beginners!)
