### ISSUE TITLE
Below a certain level on screen y axis cannot click on right side panels or adjust panel size

### ISSUE THREAD

**Issue by rjvelasquezm** [rstudio/rstudio#12231]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.07.2 Build 576
    OS Version      : Windows 11
    R Version       : 4.2.1

### Steps to reproduce the problem
Hard to say, happens somewhat randomly although I've noticed if I lock my desktop and then come back to it with an open Rstudio session.

### Describe the problem in detail
Below a certain vertical level on my screen (let's call it half) I can not click or interact with right side panes (say panes to see plots or packages etc.) nor am I able to interact with the window edges to resize those window edges. If I create a plot the plot will still display but I can't interact with it.

### Describe the behavior you expected
Being able to normally interact with panes.

- [ X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@rjvelasquezm Thank you for raising this! Do you know if this occurred with previous version RStudio, by chance?

Also, we're currently working on a version of RStudio Desktop using a new framework, Electron. We're hoping that the switchover resolves a number of issues. Please note that since this project is still in development, these builds are meant for testing and development purposes, not production.

If you're interested in trying it out the Elsbeth Geranium project 2022.12.0 currently in development, [the RStudio Desktop installers are all Electron-based](https://dailies.rstudio.com/rstudio/elsbeth-geranium/electron/windows/). 
 
In addition, there is an option to run it on your machine without installing and replacing your current version.

First, to be on the safe side, I recommend backing up the current state. There are more details at https://support.rstudio.com/hc/en-us/articles/200534577-Resetting-RStudio-Desktop-s-State, but the two directories to back up are `%localappdata%\RStudio` and `%appdata%\RStudio`.

Next, get and run RStudio Desktop (Electron):
1) Download an installer-less build from https://dailies.rstudio.com/rstudio/elsbeth-geranium/electron/windows-xcopy/
2) Unzip the file.
3) In the unzipped directory, run `rstudio.exe`
4) Check that you're using the Electron version by going to <kbd>Help -> About RStudio</kbd>, which should include the word "Electron" in the description.

This way, your installed version will be unaffected, which means you can run both—although I recommend using them one at a time, not simultaneously.

And just a reminder, these are meant for testing and development purposes, not production.

**Comment by rjvelasquezm** [comment]
Hi @ronblum thanks for the quick response and suggestion to use the new version, I'll definitely test it out.

To your question, Yes I do believe it's happened on previous versions of RStudio as well.

**Comment by rjvelasquezm** [comment]
@ronblum not sure where to post this but just wanted to let you know I've been using Electron version you recommended and have not encountered this issue. 

One thing I have noticed is a difference in the behavior of the alt key when using shortcuts relative to standard RStudio. When using shortcuts it seems that the alt key behaves in a 'sticky' manner. And many times I'll end up with menus highlighted when that wasn't my intention (rather say navigating left ro right on my script using ALT+right)

**Comment by ronblum** [comment]
@rjvelasquezm Regarding Electron and the original issue—good to hear that it works!

Regarding the alt key: Are you using a US QWERTY layout, or is it another layout with AltGr?

**Comment by rjvelasquezm** [comment]
@ronblum regular US QWERTY layout (ASUS G14 2022 laptop if that helps).
