### ISSUE TITLE
Keybindings for zooming (e.g., `Ctrl`+`+`) do not work

### ISSUE THREAD

**Issue by GegznaV** [rstudio/rstudio#12242]
### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 2022.12.0.292
    OS Version      : Windows 10 x64 (build 19044)
    R Version       : R version 4.2.1 (2022-06-23 ucrt)

### Steps to reproduce the problem

 Press either <kbd>Ctrl</kbd>+<kbd>+</kbd>, <kbd>Ctrl</kbd>+<kbd>-</kbd>, or <kbd>Ctrl</kbd>+<kbd>0</kbd>

### Describe the problem in detail

In daily builds RStudio version, nothing happens. In 2022.07.2+576 (current stable version), these keybindings were active.

The issue might be that they are not present in the list of keybindings for zooming (neither in the stable version nor in daily builds):
<details><summary>Print-screen</summary>

![image](https://user-images.githubusercontent.com/12725868/198387372-92c66bcd-10c0-4f55-80de-26a9483ecc53.png)

</details>

### Describe the behavior you expected

These keybindings should be default:

- <kbd>Ctrl</kbd>+<kbd>+</kbd>to  zoom in;
- <kbd>Ctrl</kbd>+<kbd>-</kbd> to zoom out;
- <kbd>Ctrl</kbd>+<kbd>0</kbd> to reset zooming (most probably it is "Zoom actual size" option).

**Comment by ronblum** [comment]
@GegznaV Thank you for raising this! Did this just start with this build, and is it still an issue with more recent builds? I'm able to use these standard zooming keyboard with RStudio Desktop 2022.12.0-preview+308, although it's on Windows 11.

**Comment by timtmok** [comment]
The shortcuts work for me as well on Windows 11 with daily 306. I do see why they aren't listed in the keybindings and it seems to only have defaults for Mac. It doesn't appear to have changed recently so I'm not sure why it would have worked before with Qt builds. I'll try to reproduce on Windows 10.

With 2022.12.0, the change to Electron means this should work with `Ctrl`+`+` and `Ctrl`+`-` for zooming by default since it has been defined for all platforms.

This also reveals that some keybindings that are now handled by Electron need to handle keybinding changes. I don't see anything that handles keybinding updates so setting them won't workaround this issue either.

Rebinding probably doesn't work for these actions:
* Zoom in/out
* Zoom actual size
* Undo
* Redo

**Comment by timtmok** [comment]
This works for me on Windows 10 as well with daily 309. The keybindings can also be updated and it works for zooming. I can confirm that the code does indeed get the updated keybinding in Electron.

I will add a default keybinding for zoom in/out and zoom to actual size. I'm going to check the Linux keybindings to verify there will be no conflict.

**Comment by GegznaV** [comment]
Still does not work on RStudio-2022.12.0-preview-311. 
But works perfectly when I re-install RStudio-2022.07.2-576.

On RStudio-2022.12.0-preview-311,  <kbd>Ctrl</kbd>+<kbd>+</kbd> for zooming in and <kbd>Ctrl</kbd>+<kbd>0</kbd> for resetting zoom do not work even when I set them manually but the commands work if I set other keybindings, e.g.  <kbd>Ctrl</kbd>+<kbd>*</kbd>, <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>*</kbd>. On the other hand,  Zooming out works after manual setting to  <kbd>Ctrl</kbd>+<kbd>-</kbd>. I tried   <kbd>Ctrl</kbd>+<kbd>+</kbd> with other commands: does not work too.

I tried to delete (rename) `AppData\Roaming\RStudio\keybindings`: didn't help too.

**Comment by GegznaV** [comment]
I see the `repro needed ` label. How can I debug the issue further?

**Comment by timtmok** [comment]
@GegznaV Can you attach your desktop log file? Logging around key events isn't verbose but maybe an error will show up.

You can find the log in `%LOCALAPPDATA%\RStudio\log`. The `rdesktop.log` now has the date that the IDE launched.

**Comment by timtmok** [comment]
Also, enable debug logging either by launching with the `--log-level=debug` argument or setting `RS_LOG_LEVEL=debug` in your environment variables.

**Comment by GegznaV** [comment]
> Also, enable debug logging either by launching with the `--log-level=debug` argument or setting `RS_LOG_LEVEL=debug` in your environment variables.

Hope, this is the correct way to do that:
![image](https://github.com/rstudio/rstudio/assets/12725868/e2c2b292-6f6f-4204-b29d-e0a611ea7da4)
After that, I restarted my PC, removed old logs, and opened RStudio. Tried the shortcuts. Closed RStudio. Re result in `log` folder:

[log.zip](https://github.com/rstudio/rstudio/files/11486723/log.zip)

***

I tried using **Ctrl** + **+** after setting it explicitly or removing the explicit shortcut. This had no effect (no zooming-in occurs):
![image](https://github.com/rstudio/rstudio/assets/12725868/c360b1cd-aabd-4f70-95a2-df139ca862b1)  
![image](https://github.com/rstudio/rstudio/assets/12725868/1e12403b-e128-4bad-a09f-a2f882730449)



When I set to **Ctrl** + **\***, zooming-in works:
![image](https://github.com/rstudio/rstudio/assets/12725868/0f24c606-f011-4ec4-8c79-d405a6cc9c46)


***

In one of the previous logs, there was a record:
```
2023-05-16T06:54:50.456709Z [rsession-USER] INFO No keybindings/editor_bindings.json found at C:/ProgramData/RStudio/keybindings/editor_bindings.json
```

Folder `C:/ProgramData/RStudio` does not exist. **Why does RStudio search for something in there?** 
The folder with keybinding-related files is in `C:\Users\USER\AppData\Roaming\RStudio\keybindings`

**Comment by GegznaV** [comment]
I currently use:
 
    RStudio Edition : Desktop [Open Source]
    RStudio Version : 2023.5.0.333
    OS Version      : Windows 10 x64 (build 19045)
    R Version       : R version 4.3.0 (2023-04-21 ucrt)


Is this information enough to find out why **Ctrl** + **+** and some other keybindings do not work?

**Comment by GegznaV** [comment]
Is there any progress toward solving this issue?

Why <kbd>Ctrl</kbd>+<kbd>+</kbd> does not work for zooming in even after it is explicitly set?

Still, I am not able to use this shortcut combination on:

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 2023.6.2.561
    OS Version      : Windows 10 x64 (build 19045)
    R Version       : R version 4.3.1 (2023-06-16 ucrt)

**Comment by GegznaV** [comment]
At the beginning of this semester, I asked my students to try these shortcuts, and half reported that `Ctrl` + `+` works, and the remaining ones said that it doesn't. One student reported that it depends on whether `+` in the main keyboard (above `[` in my layout) or `+` in the keypad is used: with the `+` in the keypad the shortcut does not work.

One more detail: if I set keybinding to `Ctrl` + `+`
![image](https://github.com/rstudio/rstudio/assets/12725868/1563978e-3aad-4e56-b5e6-36b0fc7a863d)
After I close and reopen the same "Modify keyboard shortcuts" window, the shortcut is changed even if I use `+` in the keypad to set the shortcut:
![image](https://github.com/rstudio/rstudio/assets/12725868/fc50af97-ac70-4a34-ad79-8e965819b60e)

Is this behavior related to the issue I reported?

@timtmok, does the keybinding work for you with both `+` in the main keyboard and in the keypad?

**Comment by timtmok** [comment]
> 2023-05-16T06:54:50.456709Z [rsession-USER] INFO No keybindings/editor_bindings.json found at C:/ProgramData/RStudio/keybindings/editor_bindings.json

That's an info level message to let you know that no custom keybinds were found. You would have a file like that after customizing your keybindings. Otherwise, it uses the built-in defaults.

Thank you for following up with this mystery. The keypad seems to be the issue. Changing to Electron as the application container meant we tried to use some of the shortcuts available without having to recreate the bindings. Electron uses the +/- on the number row instead of the keypad. This is reflected in the key accelerator hint when viewing the action in the View menu.

With Qt, it also used Chromium but specifically uses +/- instead of =/- like Electron does. Likely, the change was due to the ease of using the number row instead of the keypad. A special case can be added to address this and allow the keypad.

I'll throw it into triage for milestone targeting.

![image](https://github.com/rstudio/rstudio/assets/9591545/7cceb45f-9ac2-493f-a92b-87b53b00d58d)

**Comment by ronblum** [comment]
Note: Number pad issue.

**Comment by gtritchie** [comment]
Sorry I didn't notice this the first time around, but <kbd>Ctrl + NumPad Zero</kbd> doesn't restore zoom to default. While we're touching this, might as well do that, too?

**Comment by gtritchie** [comment]
Verified with build 2024.11.0+353. Note that Ctrl+Numpad0 does not work on Windows, but does on Mac, but we've decided to live with that.
