### ISSUE TITLE
Completion narrowing after first completion with empty token

### ISSUE THREAD

**Issue by romainfrancois** [rstudio/rstudio#12300]
When we first trigger a completion with an empty token `""` we get some possibilities, and then if we start typing something, they get narrowed. But then we get a different set of possibilities than if we directly had typed that same something, because some forms of completions (search path completions, ...) bail on empty token. 

So I'm wondering if narrowing should perhaps be disabled when the initial completion is to an empty token. cc @kevinushey

 For example, completing `mtcars %>% select(st`

with narrowing: 

https://user-images.githubusercontent.com/2625526/200261748-7b4b23ba-3c21-4350-8aff-a5c2afaaae85.mov

directly: 

https://user-images.githubusercontent.com/2625526/200262048-2c6a6652-7ee7-4e94-bbb6-eca67ac02a76.mov

So it's difficult to get to e.g. `starts_with()` which could be useful in a `select()`.

**Comment by kevinushey** [comment]
FWIW the main reason for this behavior is because we would otherwise overwhelm the client with the number of completions (e.g. imagine giving every single symbol from `base` on an empty token). That said, we start showing completions after 3 consecutive characters (instead of 2) so in the simplest case changing that from 3 to 2 would "solve" this issue.

<img width="601" alt="Screen Shot 2022-11-07 at 10 06 05 AM" src="https://user-images.githubusercontent.com/1976582/200382928-130973ba-1c45-4c0f-a166-1772e695aaf3.png">

Usually, this case is handled cleanly because autocompletions are automatically triggered after the user types a few letters, and so in that case they get a smaller set of relevant completions.

> So I'm wondering if narrowing should perhaps be disabled when the initial completion is to an empty token. cc @kevinushey

It's worth investigating, trying, but it might feel janky if the completion list suddenly expands as the user starts typing. It might be better to just toggle the default number of characters before automatic completions kicks in to a lower number.
