### ISSUE TITLE
Return of "3/4 of the window is black on external display" bug?

### ISSUE THREAD

**Issue by cornejom** [rstudio/rstudio#12340]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.07.2  Build 576
    OS Version      : darwin17.0  (for Monterey 12.6.1)
    R Version       :  4.2.1

### Steps to reproduce the problem
After MacBook has been awoken from sleep, I launch RStudio.  It opens on the integrated display and I then move it to an external one. 
The problem does not occur before sleeping.  After a fresh reboot RStudio looks fine on external display.

### Describe the problem in detail
Seems like problem previously described 4 years ago in issue [3479](https://github.com/rstudio/rstudio/issues/3479) has returned: the screen contents shrink into 1/4 of the screen while the remainder is black.
![RStudio shrunk](https://user-images.githubusercontent.com/6126003/202022566-24290329-81e4-40c3-9cf6-4503cc6b910d.png)

The problem can be worked around by changing the _Rendering engine_ setting from the recommended value of "Auto-detect" to "Software".

### Describe the behavior you expected
Expected screen contents to appear over the entirety of the external screen with "Auto-detect" rendering.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@cornejom Thank you for raising this!

We're switching RStudio Desktop to a new framework, Electron. The switchover resolves a number of issues. Would you be willing to check if the Electron version resolves the problem? If you're interested in trying out the Elsbeth Geranium 2022.12.0 project currently in development, [the open source RStudio Desktop installers are all Electron-based](https://dailies.rstudio.com/rstudio/elsbeth-geranium/). 
 
Please note that since this project is still in development, and these builds are meant for testing and development purposes, not production.

**Comment by cornejom** [comment]
@ronblum Thanks for the update.  Unfortunately, I'll not be able to try out the Electron-based development version (for now).
