### ISSUE TITLE
git clone prompts with error: cannot run rpostback-askpass

### ISSUE THREAD

**Issue by samperman** [rstudio/rstudio#12390]
### System details

    RStudio Edition : Workbench (running in posit.cloud)
    RStudio Version : 2022.12.0-349.pro2
    OS Version      :  Ubuntu Focal
    R Version       :  4.2.2

### Steps to reproduce the problem
Create a new project, navigate to the terminal and run `git clone`

### Describe the problem in detail
The clone prompts with errors:
```
/cloud/project$ git clone --depth=1 https://github.com/rstudio/connect
Cloning into 'connect'...
error: cannot run rpostback-askpass: No such file or directory
Username for 'https://github.com': sam@permans.com
error: cannot run rpostback-askpass: No such file or directory
```

### Describe the behavior you expected
Spotted Wakerobin would open a modal to prompt for username and password.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment]
This will affect _any_ git operation that requires credentials. I don't think we can release with it.

**Comment by samperman** [comment]
A couple other pieces of info from the environment i was using:
```
$ echo $PATH
/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/opt/R/4.2.2/lib/R/bin:/opt/quarto/1.2.269/bin:/usr/lib/rstudio-server/bin/postback/postback:/usr/bin:/opt/R/4.2.2/lib/R/bin
```

```
> Sys.getenv("RS_RPOSTBACK_PATH")
[1] "/usr/lib/rstudio-server/bin/rpostback"
```

**Comment by jgutman** [comment]
> This will affect _any_ git operation that requires credentials. I don't think we can release with it.

Yes, but we tested several variations of this on several different OSes with several different combinations of ssh with and without password protected key, and https cloning. So I'm a little unsure as to the scope, clearly we missed something in testing but it did pass all the tests we did run. @jmcphers @jonvanausdeln

**Comment by jmcphers** [comment]
> sh with and without password protected key,

**Comment by jmcphers** [comment]
> ssh with and without password protected key

I can't see any way this could work in @samperman's environment. 

> SSH_ASKPASS=rpostback-askpass

This requires `rpostback-askpass` to be on the `$PATH`, and it's not, so SSH passphrase prompting is probably going to fail.

**Comment by jmcphers** [comment]
I found this same problem on https://colorado.posit.co/daily-workbench, so it is not an artifact of the cloud environment. Here is the `$PATH` I observed there:

```
/opt/python/3.9.5/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/rstudio-server/bin/quarto/bin:/usr/lib/rstudio-server/bin/postback/postback:/usr/bin
```

Notice `postback/postback` instead of just `postback`. 

It looks like Git and SSH credential prompting from the Terminal is going to be broken in all Server and Workbench environments unless we fix this.

**Comment by jonvanausdeln** [comment]
I just tried on https://colorado.posit.co/daily-workbench, and it seemed to work for me with a username/PAT

> jon.vanausdeln@session-a291ccfc78a314c770168-jonvanausdeln---rstudio-pro-ldrq6:~$ git clone https://github.com/jonvanausdeln/toolbox.git
Cloning into 'toolbox'...
Username for 'https://github.com': jonvanausdeln
Password for 'https://jonvanausdeln@github.com': 
remote: Enumerating objects: 33, done.
remote: Counting objects: 100% (33/33), done.
remote: Compressing objects: 100% (25/25), done.
remote: Total 33 (delta 4), reused 28 (delta 2), pack-reused 0
Unpacking objects: 100% (33/33), done.

**Comment by mikebessuille** [comment]
I don't understand how this is succeeding for Jon (and Jackie?) but not for Sam and Jonathan???  Need to understand under what circumstances this works, or doesn't.   OS dependent?  local / home directory config?  password-protected key?  Aliens?

**Comment by mikebessuille** [comment]
Jon, you tried to clone a repo that you own.  What if you try to clone an rstudio private (or public) repo?

**Comment by ronblum** [comment]
First HTTPS on current Colorado, Spotted Wakerobin 2022.07.2+576.pro12, using a password protected key (which will be ignored because it's not using the SSH key). GitHub should reject all HTTPS calls to private repos, but allow public repo cloning.

*Terminal*
```
$ echo $PATH
/opt/python/3.10.4/bin:~/.local/bin:/opt/python/3.10.4/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/rstudio-server/bin/quarto/bin:/usr/lib/rstudio-server/bin/postback:/usr/bin
$ echo $RS_RPOSTBACK_PATH
/usr/lib/rstudio-server/bin/rpostback
```

*Console*
```
> Sys.getenv("RS_RPOSTBACK_PATH")
[1] "/usr/lib/rstudio-server/bin/rpostback"
```

*HTTPS to the original private repo from Terminal*
```
$ git clone --depth=1 https://github.com/rstudio/connect
Cloning into 'connect'...
TTY detected. Printing informational message about logging configuration. Logging configuration loaded from '/mnt/dynamic/rstudio/logging.conf'. Logging to '/usr/home/ron/.local/share/rstudio/log/rpostback.log'.
TTY detected. Printing informational message about logging configuration. Logging configuration loaded from '/mnt/dynamic/rstudio/logging.conf'. Logging to '/usr/home/ron/.local/share/rstudio/log/rpostback.log'.
remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/rstudio/connect/'
```


*HTTPS to a public repo from Terminal*
```
$ git clone --depth=1 https://github.com/rstudio/rstudio
Cloning into 'rstudio'...
remote: Enumerating objects: 9199, done.
remote: Counting objects: 100% (9199/9199), done.
remote: Compressing objects: 100% (6314/6314), done.
Receiving objects:   2% (238/9199), 31.49 MiB | 31.49 MiB/s 
```

*HTTPS to another private repo from Terminal*
```
ron@session-8fe967aa2b96ddc8b0803-ron---rstudio-session-3-vsrpzrcm5:~$ git clone --depth=1 https://github.com/*REDACTED*
Cloning into '*REDACTED*...
TTY detected. Printing informational message about logging configuration. Logging configuration loaded from '/mnt/dynamic/rstudio/logging.conf'. Logging to '/usr/home/ron/.local/share/rstudio/log/rpostback.log'.
TTY detected. Printing informational message about logging configuration. Logging configuration loaded from '/mnt/dynamic/rstudio/logging.conf'. Logging to '/usr/home/ron/.local/share/rstudio/log/rpostback.log'.
remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/*REDACTED*'
```

*HTTPS to original private repo for a Git project in the IDE*
GitHub username/password dialogs appear. Output:
```
>>> /usr/bin/git clone --progress https://github.com/rstudio/connect connect
Cloning into 'connect'...
remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/rstudio/connect/'
```


*HTTPS to public repo for a Git project in the IDE*
```
>>> /usr/bin/git clone --progress https://github.com/rstudio/rstudio rstudio
```
etc., which can't be copied. The repo is successfully cloned.


*HTTPS to another private repo for a Git project in the IDE*
GitHub username/password dialogs appear. Output:

```
>>> /usr/bin/git clone --progress https://github.com/*REDACTED* *REDACTED*
Cloning into '*REDACTED*'...
remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/*REDACTED*'
```

**Comment by samperman** [comment]
> GitHub should reject all HTTPS calls to private repos

HTTPS is supported if using a personal access token.

**Comment by jgutman** [comment]
I also just attempted cloning the rstudio/connect private repo via HTTPS in the RStudio terminal via username and PAT, in Posit Workbench 2022.12.0+351.pro4. This worked for me. It requested username and password (supplied PAT) directly in the terminal, which was a change from the Spotted Wakerobin behavior, which requested username and password via a popup modal, but regardless the authentication appeared successful. However:
```
Sys.getenv("RS_RPOSTBACK_PATH")
[1] "/usr/lib/rstudio-server/bin/rpostback"
Sys.getenv("PATH")
[1] "/opt/python/3.9.5/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/rstudio-server/bin/quarto/bin:/usr/lib/rstudio-server/bin/postback/postback"
```
There appears to be an inconsistency between the value of RS_RPOSTBACK_PATH and PATH itself, not entirely sure why off the top of my head.
Still trying to understand why cloning would have succeeded for some of us (me, Ron?, Jon) and failed for others (Sam, Jonathan?) -- although not clear if Jonathan actually cloned or just noted the unusual PATH value

**Comment by samperman** [comment]
sorry if I have caused some confusion here. cloning worked, but it logged the errors about postback.

**Comment by jgutman** [comment]
It logged the errors but still worked? that's even more confusing. 

However, I didn't get any errors, and clone was still successful

```
jacqueline.gutman@session-8b632cfc78a3123c1482c-jacquelinegutman---rstudio-p9wzsg:~$ git clone https://github.com/rstudio/connect.git
Cloning into 'connect'...
Username for 'https://github.com': jgutman
Password for 'https://jgutman@github.com': 
remote: Enumerating objects: 430729, done.
remote: Counting objects: 100% (2455/2455), done.
remote: Compressing objects: 100% (1208/1208), done.
remote: Total 430729 (delta 1326), reused 2149 (delta 1165), pack-reused 428274
Receiving objects: 100% (430729/430729), 959.68 MiB | 4.04 MiB/s, done.
Resolving deltas: 100% (310102/310102), done.
Checking out files: 100% (11162/11162), done.
jacqueline.gutman@session-8b632cfc78a3123c1482c-jacquelinegutman---rstudio-p9wzsg:~$ 
```

**Comment by samperman** [comment]
Yup, that's right:
```
/cloud/project$ git clone --depth=1 https://github.com/rstudio/connect
Cloning into 'connect'...
error: cannot run rpostback-askpass: No such file or directory
Username for 'https://github.com': sam@permans.com
error: cannot run rpostback-askpass: No such file or directory
Password for 'https://sam@permans.com@github.com': 
remote: Enumerating objects: 11077, done.
remote: Counting objects: 100% (11077/11077), done.
remote: Compressing objects: 100% (9271/9271), done.
remote: Total 11077 (delta 1669), reused 6604 (delta 1293), pack-reused 0
Receiving objects: 100% (11077/11077), 269.87 MiB | 29.90 MiB/s, done.
Resolving deltas: 100% (1669/1669), done.
Updating files: 100% (11162/11162), done.
/cloud/project$ 
```

**Comment by ronblum** [comment]
Alright, since I've already done this without a personal access token, here's some more without the personal access token, but on Elsbeth Geranium 2022.12.0+351.pro4.

Now, all of this on Colorado using HTTPS in RStudio Server, Elsbeth Geranium 2022.12.0+351.pro4.

First HTTPS on current Colorado, Spotted Wakerobin 2022.07.2+576.pro12, using a password protected key (which will be ignored because it's not using the SSH key). GitHub should reject all HTTPS calls to private repos, but allow public repo cloning.

*Terminal*
```
$ echo $PATH
/opt/python/3.9.5/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/rstudio-server/bin/quarto/bin:/usr/lib/rstudio-server/bin/postback/postback:/usr/bin
$ echo $RS_RPOSTBACK_PATH
/usr/lib/rstudio-server/bin/rpostback
```

*Console*
```
> Sys.getenv("RS_RPOSTBACK_PATH")
[1] "/usr/lib/rstudio-server/bin/rpostback"
```

*HTTPS to the original private repo from Terminal*
```
$  git clone --depth=1 https://github.com/rstudio/connect
Cloning into 'connect'...
Username for 'https://github.com': ronblum
Password for 'https://ronblum@github.com': 
remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/rstudio/connect/'
```


*HTTPS to a public repo from Terminal*
```
$ git clone --depth=1 https://github.com/rstudio/rstudio
Cloning into 'rstudio'...
remote: Enumerating objects: 9199, done.
remote: Counting objects: 100% (9199/9199), done.
```
etc.


*HTTPS to another private repo from Terminal*
```
$ git clone --depth=1 https://github.com/*REDACTED*
Cloning into '*REDACTED*'...
Username for 'https://github.com': ronblum
Password for 'https://ronblum@github.com': 
remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/*REDACTED*'
```

*HTTPS to original private repo for a Git project in the IDE*
GitHub username/password dialogs appear. Output:
```
>>> /usr/bin/git clone --progress https://github.com/rstudio/connect connect
Cloning into 'connect'...
remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/rstudio/connect/'
```


*HTTPS to public repo for a Git project in the IDE*
```
>>> /usr/bin/git clone --progress https://github.com/rstudio/rstudio rstudio
```
etc., which can't be copied. The repo is successfully cloned.


*HTTPS to another private repo for a Git project in the IDE*
GitHub username/password dialogs appear. Output:

```
>>> /usr/bin/git clone --progress https://github.com/rstudio/*REDACTED* *REDACTED*
Cloning into '*REDACTED*'...
remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/*REDACTED*'
```

**Comment by ronblum** [comment]
Using SSH in Terminal on Spotted Wakerobin:
```
$ git clone git@github.com:rstudio/connect
Cloning into 'connect'...
Enter passphrase for key '/usr/home/ron/.ssh/id_rsa': 
remote: Enumerating objects: 430737, done.
remote: Counting objects: 100% (2463/2463), done.
remote: Compressing objects: 100% (1203/1203), done.
Receiving objects:   0% (1438/430737), 212.00 KiB | 404.00 KiB/s  
```
etc.


Using SSH in Terminal on Elsbeth Geranium:
```
$ git clone git@github.com:rstudio/connect
Cloning into 'connect'...
fatal: unable to fork
```

The latter happens when trying to create a Git project in the IDE.

**Comment by jgutman** [comment]
However, if the clone was successful, we will still look into fixing this ASAP, but at the moment we are trying to evaluate whether this is a stop-ship kind of bug (we are in the middle of certification for release) or "let's fix ASAP but for the next release" type of issue. If you aren't completely blocked from cloning, then I would lean towards the latter, but let us know

**Comment by ronblum** [comment]
Why is SSH failing with `fatal: unable to fork`? Is this related or another bug?

**Comment by jgutman** [comment]
`fatal: unable to fork` sounds unrelated and more like some kind of permissions issue on the github side. Do you actually have access to that repo? And if using a PAT, what permissions did you set up the PAT with? it shouldn't be attempting to fork the repo, at least if you have permission for it. You can test with another private repo if not

**Comment by ronblum** [comment]
I have access to it—it works in Spotted Wakerobin but fails in Elsbeth Geranium.

That was with a password-protected SSH key.

Here's the output using HTTPS with a classic personal access token:  Successful cloning, no errors.
```
$ git clone --depth=1 https://github.com/rstudio/connect
Cloning into 'connect'...
Username for 'https://github.com': ronblum
Password for 'https://ronblum@github.com': 
remote: Enumerating objects: 11077, done.
remote: Counting objects: 100% (11077/11077), done.
remote: Compressing objects: 100% (9264/9264), done.
remote: Total 11077 (delta 1672), reused 6608 (delta 1300), pack-reused 0
Receiving objects: 100% (11077/11077), 269.86 MiB | 12.11 MiB/s, done.
Resolving deltas: 100% (1672/1672), done.
Checking out files: 100% (11162/11162), done.
```

**Comment by ronblum** [comment]
BTW, I figured out why SSH cloning was failing: `ssh` is missing from wherever Elsbeth Geranium instance on Colorado. So that's just a Colorado setup issue.

*Spotted Wakerobin*
```$ which ssh
/usr/bin/ssh
```

*Elsbeth Geranium*
```
$ which ssh
$ ls -l /usr/bin/ssh
ls: cannot access '/usr/bin/ssh': No such file or directory
```

**Comment by kevinushey** [comment]
Just to try and summarize some of the different pieces floating around this thread...

The `RS_POSTBACK_PATH` environment variable should point to the `rpostback` executable. You can see how it's used in some helper scripts, e.g.

https://github.com/rstudio/rstudio/blob/main/src/cpp/session/postback/rpostback-browser
https://github.com/rstudio/rstudio/blob/main/src/cpp/session/postback/rpostback-askpass

Most of the code in RStudio seems to assume that the `rpostback` executable, and the `rpostback-*` helper scripts, all live in the same directory. For example:

https://github.com/rstudio/rstudio/blob/1ab0a77ee965680e4c437ff2ff95e79ff9bc0c2b/src/cpp/session/SessionPostback.cpp#L106-L108

https://github.com/rstudio/rstudio/blob/1ab0a77ee965680e4c437ff2ff95e79ff9bc0c2b/src/cpp/session/session-options.json#L637-L644

https://github.com/rstudio/rstudio/blob/1ab0a77ee965680e4c437ff2ff95e79ff9bc0c2b/src/cpp/conf/rsession-dev.conf#L33-L34

Compare to the layout I see on macOS (it seems similar on other operating systems)

```
kevin@MBP-P2MQ:/Applications/RStudio.app/Contents/Resources/app/bin
$ tree
.
├── diagnostics
├── postback
│   ├── askpass-passthrough
│   ├── rpostback-askpass
│   ├── rpostback-browser
│   ├── rpostback-editfile
│   ├── rpostback-gitssh
│   └── rpostback-pdfviewer
├── r-ldpath
├── rpostback
├── rsession
└── rsession-arm64
```

I think we use that assumption in a number of places when trying to place `rpostback` and its utilities on the PATH, e.g.

https://github.com/rstudio/rstudio/blob/1ab0a77ee965680e4c437ff2ff95e79ff9bc0c2b/src/cpp/session/modules/SessionGit.cpp#L126-L131

https://github.com/rstudio/rstudio/blob/1ab0a77ee965680e4c437ff2ff95e79ff9bc0c2b/src/cpp/session/modules/SessionGit.cpp#L3356-L3363

https://github.com/rstudio/rstudio/blob/1ab0a77ee965680e4c437ff2ff95e79ff9bc0c2b/src/cpp/session/modules/SessionSVN.cpp#L120-L126

To wit, I think the ultimate solution here is to make sure that package builds of RStudio also place `rpostback` in the `postback` directory, so it's a sibling of the related helper scripts:

https://github.com/rstudio/rstudio/blob/1ab0a77ee965680e4c437ff2ff95e79ff9bc0c2b/src/cpp/session/postback/CMakeLists.txt#L58-L61

Note the extra added wrinkle that the postback installation layout hence differs between package builds and development builds; e.g. in my development build of RStudio I have:

```
kevin@MBP-P2MQ:~/rstudio/src/build-cpp-Desktop_Qt_5_12_11_clang_64bit-RelWithDebInfo/session/postback/postback [main]
$ tree .
.
├── askpass-passthrough
├── rpostback
├── rpostback-askpass
├── rpostback-browser
├── rpostback-editfile
├── rpostback-gitssh
└── rpostback-pdfviewer
```

and (unless we have a very good reason) we should make sure directory layouts match between development and package builds, since otherwise we'll see that the issue is not reproducible in development builds, but is reproducible in package builds.

The thing that surprises me the most is that seemingly this has been the case for a long time -- so why is this only becoming a more visible issue now?

**Comment by kippandrew** [comment]
I have some concerns that shipping with this issue might be very confusing to users. If cloning from git results in spurious errors, I think that could result in a high volume of support cases.

**Comment by kippandrew** [comment]
I understand that we are in the final days before release. Just to be clear, my understanding of this issue (and please correct me if I'm wrong) is that any interactions with git using HTTPS will result in the user seeing spurious error messages. I think this would impact a substantial number of Workbench users and nearly all Cloud users as we configure the projects to use HTTPS when they are created from GitHub following the "new project from GitHub" workflow. That said, it seems like those operations will be successful despite the errors, so you may be right that that doesn't qualify as a stop-ship issue. However, I would anticipate a fair amount of confusion from users and at least a moderate number of support cases as a result.

**Comment by jgutman** [comment]
I'm not sure that it's the case that any interactions with Git using https
will result in the spurious error messages. We've had difficulty
reproducing the issue, and it does not seem to occur consistently. At this
point we're not sure of the scope of the issue, after spending considerable
man-hours doing QA to reproduce. We've also not yet had any user reports of
the issue from any of our users using the dailies, and the code related to
this has been unchanged for about 6 weeks. So I don't think the scope can
possibly be quite as broad as what you're concerned it might be, although
again at this point we don't necessarily know more than that several devs
and QAs have failed to reproduce the error in several different testing
environments and servers.

**Comment by jgutman** [comment]
For example, I successfully cloned the connect private repo on Colorado using HTTPS with no error messages. We are going to look into what Sam reported, but I don't think we can further divert our QA resources away from the certification process anymore than we already did last week, when we spent many hours trying and only extremely inconsistently reproducing the error. If there are a flood of support issues related to this, we will address them at this time, but based on the behavior we have actually observed so far and the lack of user reports on the preview product, I don't currently expect that to be the case

**Comment by ronblum** [comment]
The original post involved cloning using the git CLI from the command line. If the concern is that most users will run into a problem when creating version-controlled projects via the UI, has anyone sees a problem when using it?

**Comment by samperman** [comment]
So far in my testing in cloud, if i use the IDE to interact with `git`, then i don't see any error messages (even if i then fall back to the terminal).

If i start with the CLI in the terminal, then any `git` command that interacts with the server (`git clone` `git pull` etc) will print the errors mentioned above, but the call will work despite those errors.

This behavior is consistent each time i've tried.

**Comment by samperman** [comment]
Yup, i still see `/usr/lib/rstudio-server/bin/postback/postback` in the path. This is using staging.posit.cloud (production posit.cloud is using spotted wakerobin)

**Comment by jgutman** [comment]
@kevinushey says:
> My understanding is that any git operation initiated within RStudio could fail if git tried to prompt you for credentials. This could happen if:

> You're using a password-locked SSH key, but you haven't unlocked it yet;
> You're trying to access a repository requiring authentication, but your credentials haven't yet been added to the git credential manager.

Yes, in theory this would appear to be true, however I've used a git clone with HTTPS username and PAT where git has prompted me for username and password (PAT) credentials, entered them successfully in the prompt, and cloned with no error message. Also Sam has reported that he's received the error message, but then it has still cloned successfully. So there's something happening beyond just "the rpostback-askpass path is completely wrong and all operations that require credentials will fail", since that isn't what we observe. We just haven't quite grasped what exactly is causing the error in specific circumstances/environments

**Comment by jgutman** [comment]
> It would definitely be good if we could understand what's going on with this error though:
```
kevin@session-3978bcfc78a3143e6569f-kevin---rstudio-pro-session-mfwg7:~/scratch$ git clone git@github.com:kevinushey/rstudio-tour.git
Cloning into 'rstudio-tour'...
fatal: unable to fork
```
but it seems more likely to be something esoteric with how Coloardo is set up?

For some reason, the daily Colorado appears to be missing the ssh executable. You can see this if you run `which ssh` in the terminal. I don't know why this is. We've reached out and asked Monanshi about this, but it's probably some issue with the docker container for the instance. Regardless of this SSH issue, we should be able to test using HTTPS with username/PAT

**Comment by ronblum** [comment]
One more data point: I created a couple of fresh installations so that I had no keys of any kind or cached information, and I was able to 1) reproduce the problem, and 2) confirm that it's a regression in Elsbeth Geranium 2022.07.2+576.pro12 as it works in Spotted Wakerobin 2022.07.2+576.pro12.

Using a private repository:
```
rstudio@ip-172-98-15-193:~$ git clone https://github.com/REDACTED
Cloning into 'REDACTED'...
error: cannot run rpostback-askpass: No such file or directory
Username for 'https://github.com': ronblum
error: cannot run rpostback-askpass: No such file or directory
Password for 'https://ronblum@github.com': 
remote: Enumerating objects: 210, done.
remote: Counting objects: 100% (72/72), done.
remote: Compressing objects: 100% (46/46), done.
remote: Total 210 (delta 31), reused 65 (delta 26), pack-reused 138
Receiving objects: 100% (210/210), 120.41 MiB | 28.88 MiB/s, done.
Resolving deltas: 100% (88/88), done.
```

**Comment by kevinushey** [comment]
I'm going to take a look -- there's enough going on here that I think it's worth a second set of eyes.

**Comment by jgutman** [comment]
For testing purposes, it will be useful to know how to clear any cached credentials to test what happens when credentials are needed: 

If using HTTPS with username/PAT (or with browser-based login), you can clear any cached credentials as follows:
**Mac:**
In Terminal, Enter:
~~~~
$ git credential-osxkeychain erase ⏎
 host=github.com  ⏎
 protocol=https   ⏎
 ⏎
 ~~~~
NOTE: after you enter “protocol=https” above you need to press RETURN TWICE (Each '⏎' is equivalent to a 'press enter/return' ).

**Linux:**
It is uncommon to use a credential manager on Linux. If you are entering your password every time, then you do not need to worry about resetting any cached credentials. However, there are two possible ways you may have configured Linux to cache credentials. 
1) You have installed and configured the Github CLI. You can confirm this by running:
```
gh auth status
```
and receiving a response like this: 
<img width="630" alt="image" src="https://user-images.githubusercontent.com/7817881/207687735-9ef6904c-a721-48b5-92b1-ef4ba1f2c336.png">
To clear these credentials, enter in Terminal:
```
gh auth logout
```
2) You have set up a long-running cache. You can confirm this by running:
```
git config --get credential.helper
```
and receiving a response like:
```
cache --timeout=10000000
```
If this is the case, you can simply exit the cache early by running:
```
git credential-cache exit
```

**Windows:**
In Terminal, Enter:
```
git config --get credential.helper
```
to determine what credential helper you are using to store cached credentials. If it returns `manager-core` or `manager`, then in Windows search, search for Credential Manager. Go to Credential Manager > Windows Credentials > Generic Credentials, and if you find an entry for `git:https://github.com`, click Remove to remove those stored credentials. 

<img width="822" alt="image" src="https://user-images.githubusercontent.com/7817881/207683791-1505c46c-0edf-4c72-9f3b-46f61492c155.png">


If using SSH with password-protected SSH key, you can clear cached credentials as follows:
Move private and public key to a backup location
```
cd $HOME
mkdir .ssh_bkup
mv .ssh/id_* .ssh_bkup/
```

**Comment by jonvanausdeln** [comment]
Verified on 2023.03.0-daily+284. 
Desktop - Windows 11, Ubuntu22, MacOS
OS Server - Ubuntu22

Tested git commands in terminal using:
* ssh key without passcode
* ssh key with passcode
* https and Personal Access Token

All git commands worked as expected.
