### ISSUE TITLE
Automatic login failed when missing csrf-token item in cookie with www-enable-origin-check=0

### ISSUE THREAD

**Issue by fuzhenxin** [rstudio/rstudio#12405]
### System details

    RStudio Edition : Server
    RStudio Version :  v2022.07.2+576)
    OS Version      :  CentOS 7
    R Version       :  4.2

### Steps to reproduce the problem
In login stage, when posting data to uri ``auth-do-sign-in``, the ``csrf-token`` in cookie is required, even with ``www-enable-origin-check=0`` option.

### Describe the problem in detail

When deploy rstudio server in open-ondemand,  open-ondemand automatic login to rstudio.
The first request sent to rstudio is ``auth-do-sign-in`` without cookie.
But the ``csrf-token`` in cookie is required to login even with  ``www-enable-origin-check=0`` option.

Related source code (validateCSRFForm can not be skipped with ```www-enable-origin-check=0``): https://github.com/rstudio/rstudio/blob/ca13d8830298eebe48d03a8003862e4feed964e2/src/cpp/server/auth/ServerAuthCommon.cpp#L131

### Describe the behavior you expected
 ``csrf-token`` in cookie is not required to login rstudio server with  ``www-enable-origin-check=0`` option.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by fuzhenxin** [comment]
It is hard to integrate the new rstudio with [open-ondemand](https://openondemand.org/)

**Comment by MariaSemple** [comment]
Hi @fuzhenxin, thanks for filing this issue. The `www-enable-origin-check` intentionally does not control whether or not CSRF protections are in place; it controls whether or not we validate the address of the request originator. Because of the importance of protecting against [CSRF attacks](https://owasp.org/www-community/attacks/csrf), adding an option to disable the `csrf-token` is not something we wish to do at this time. 

If you're running in single-user mode, you could potentially add `auth-none=1` to `/etc/rstudio/rserver.conf` and ensure that you start `rserver` as the user you wish to login as and see if that resolves the issue. I'll also do some poking around to see if there's anything I can recommend if you're not running in single-user mode.

**Comment by fuzhenxin** [comment]
Thank you for the response. If ``auth-none=1``, no authentication is required. The rserver service is visible in our cluster, so it is unsafe.

We provide a easy-to-use solution to use rstudio in our supercomputing cluster, so automatic login is necessary. If there is no good way, I will continue to compile a customized rstudio which ignores ``csrf_token``. Compiling the rstudio server is a hard job...

The platform like open ondemand and scow is popular in supercomputing. Many researchers use the platform to use supercomputer. I recommand to consider the compatibility with platform like open ondemand which is very important to high performance computing. Thanks for your hard work again!
