### ISSUE TITLE
Use git distance for the build number

### ISSUE THREAD

**Issue by MariaSemple** [rstudio/rstudio#12434]
Currently the build number is generated as the first step of the os-pipeline and stored in a CSV file in S3. All subsequent builds use the build number stored there. For pro builds, the build number is retrieved from the value stored by the OS-pipeline and the pro-pipeline sets a pro build number in the same way, increasing whenever the OS build number increases. This presents a few challenges:

* because HEAD is pulled for each build, downstream builds with the same build number can have more commits (such as docs, the macOS build, or session components).
* other builds need to wait for the main build to complete before they can begin

I propose the following solution:
* use git distance to set a build number for open source
* have an initial job that sets the commit for all future jobs. All future jobs should trigger at the end of the initial (very quick job)
* potentially use git diff for the pro build number as well, or some other mechanism that can't lead to the same version with different commits.

**Comment by jeffvroom** [comment]
I have a concern that git distance will create some weird build numbers, even if have a way to set the base git commit for each branch/release.  Another idea is to have a data structure, maybe in s3 using directories and files:

* for each release-name the next build number
* for each release-name, for each git-commit, an assigned build number

We already store the release name in git which we can use for looking up the appropriate build number.

Look for an existing build number for this release for this git commit.  If not found, store the current build number for this git commit, and increment it for this release for next build. If there's no build number for a release, we can lazily create that entry starting at 1 so there's no additional work to be done when moving to a new release.

**Comment by MariaSemple** [comment]
What you described is exactly what we already do, and what we're trying to get away from :)

**Comment by zachhannum** [comment]
I think Jeff's proposal would at least solve the problem of pro builds with a technically incorrect open source build number (since we could look up the build number based on the latest hash stored in `upstream/VERSION`, but at least part of impetus for using this method is to get rid of an external dependency for determining build numbers (such as storage in s3).

@jeffvroom What are your particular concerns with deriving the build number from the git distance?

**Comment by zachhannum** [comment]
I have created some experimental Jenkins pipelines to show this method in use:
- [Open Source](https://build.posit.it/blue/organizations/jenkins/IDE%2Fexperiments%2F12424-git-distance-build-number/detail/12424-git-distance-build-number/2/pipeline/31/)
- [Pro](https://build.posit.it/blue/organizations/jenkins/IDE%2Fexperiments%2F12424-git-distance-build-number-pro/detail/12424-git-distance-build-number-pro/6/pipeline/)

**Comment by jeffvroom** [comment]
I think the main goal is to just make sure rebuilding the same commit uses the same build number so we avoid rebuilding completed components. 

As Zach mentioned, that doesn't look true today for pro builds because we always increment the pro suffix, even if we find the "head commit" in pro-suffix.csv. That wouldn't be hard to fix though as we already do that for oss-patch.csv.

The rev-list approach Zach has in the above PR will accomplish the main goal, but I see a few potential minor problems:
1) We will need to be careful to update the base-commit on the first build for each branch or else we'll have an out-of-sequence build number for that branch. Today, the csv files get created automatically for new branches so this is an extra step.
2) Any mistakes made in 1) will be tricky to fix as build numbers are not really in our control
3) If rev-list counts merge commits, or someone merges a small PR with a large # of commits the build numbers won't correspond to real activity so may send a false signal about how much has changed. 
4) There's no way to reset or control build numbers if we need to edit the git history for some reason, and probable that we will get 4 digit build numbers that might cause downstream disruption.

None of those are bad, but is there any downside to just fixing the pro suffix problem? 

I don't really see the s3 storage requirement itself as big problem... it's pretty self managing and we can update those files by hand it if there are problems.

**Comment by zachhannum** [comment]
Will leave this issue open until https://github.com/rstudio/rstudio/tree/epic/4140-jenkinsfile-restructure is merged into main.
