### ISSUE TITLE
Git pane - Add a way to remove untracked git files

### ISSUE THREAD

**Issue by DavisVaughan** [rstudio/rstudio#12453]
I really wish the IDE had a way to remove _untracked_ git files using the git pane. This often comes up with snapshot tests where I will accidentally generate a "new" snapshot file, like `slice.new.md` and I'd like to remove it, so I do:
- Click the file name in the git pane
- Hit the `More` drop down
- Hit `Revert`
- It does nothing

This is presumably because whatever git call is made under the hood doesn't include untracked files.

Currently you have to go into the Files pane, find the file manually, and delete it. This can get pretty annoying if the file is buried deeply (like the snapshot file). I have also trained myself to do `usethis:::git_clean()` to remove these, but figure the IDE could better incorporate something for this.

The other (similar) workflow I have where this comes up is when I have (say) 5-10 files that I want to revert, so I select them all at once in the Git pane and do a mass `Revert`, but if any of them are untracked then it again does nothing for those untracked ones.

@romainfrancois mentioned we maybe could do something like VS Code, which gives you a pop up box saying that the reversion is irreversible:

![image](https://user-images.githubusercontent.com/19150088/208248760-bd284fe6-cfe4-4011-8f34-c2f9769972b5.png)

**Comment by olivroy** [comment]
I know this was closed as stale, but think this is worth it.

The Open file path is a good one, but would be great if the source editor presented a "delete file" option, so the number of steps could be down to 2

It would not be too dangerous, because you would have the chance to look at the file before deleting it.

Adding **Delete file** to
![image](https://github.com/rstudio/rstudio/assets/52606734/c3d6b310-744c-4843-a286-ce82f0314b3b)

would make the process easier?
