### ISSUE TITLE
Colored text causes incorrect indentation

### ISSUE THREAD

**Issue by BartJanvanRossum** [rstudio/rstudio#12489]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2022.12.0+353 "Elsbeth Geranium" 
    OS Version      : Windows 10
    R Version       : 4.2.2

### Steps to reproduce the problem

Create a vector consisting of some colors
```r
c("blue", "red")
```
Move the cursor just after the comma and press enter. This moves "red" to the next line, but with the wrong indentation:
```r
c("blue", 
        "red")
```

### Describe the problem in detail

In the latest version of RStudio the coloring of the text seems to offset the indentation. In the example above replacing "blue" by "bluf" 'fixes' the problem and leads to correct indentation. Changing "red" has no effect on the indentation at all.

### Describe the behavior you expected

Correct indentation as in the previous release version.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@BartJanvanRossum Thank you for raising the issue! I can reproduce it in
- RStudio Desktop 2022.12.0+353 on MacOS 13.2
- RStudio Server 2022.12.0+353 on Ubuntu 20.04.5 via Chrome on MacOS 13.2

It works correctly in version 2022.07.2+576. In addition:
1. The problem occurs even if color preview is turned off in <kbd>Global Options -> Code -> Display -> Enable preview of named and hexadecimal colors</kbd>.
2. The offset doesn't get worse with additional colors:
```
c("blue", 
        "red",
        "green",
        "orange")
```
3. Clicking on <kbd>Enter/Return</kbd> before the closing parens (`)`) uses the new offset instead of matching up with the operner:
```
c("blue", 
        "red"
        ) 
```

**Comment by ronblum** [comment]
Verified in RStudio 2022.03.0-daily+270 on MacOS 13.2:

<img width="105" alt="color_indenttion" src="https://user-images.githubusercontent.com/31009952/214318846-19ba1dab-b8d5-4b39-8461-0a8eb55912bc.png">

Leaving open for creating an automated test for the indentation.
