### ISSUE TITLE
Previewing rendered html_document causes URLs to open in browser

### ISSUE THREAD

**Issue by matt-gunther** [rstudio/rstudio#12494]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.12.0+353 
    OS Version      : MacOS 13.0.1 
    R Version       : 4.2.2

Additional details: 

```
   knitr version: 1.41
   rmarkdown version: 2.19
```

### Steps to reproduce the problem

Knit the following Rmd or Qmd document (sans the `\` escape characters in my R chunk) with **Preview in Viewer Pane** or **Preview in Window**.

````
---
output: html_document
---

```{r}
knitr::include_url("https://www.rstudio.com/")
```

````

### Describe the problem in detail

The referenced URL opens in several (4) tabs in a new browser (Chrome) window. 

*Reversion to RStudio version 2022.07.2 resolves the issue*

*Selecting **(No Preview)** resolves the issue*

### Describe the behavior you expected

Pervious versions of RStudio did not open these links in a new browser window, and I'm not sure why it opens several versions of the same tab.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@matt-gunther Thank you for raising this!
I can reproduce the problem in
- RStudio Desktop 2022.12.0+353 on MacOS 13.2

It works correctly in 
- RStudio Desktop 2022.07.2+576 on MacOS 13.2
- RStudio Server 2022.12.0+353 on Ubuntu 24.04.5 via Chrome on MacOS 13.2

The preview renders correctly, but it is annoying that the four browser windows also open. We'll review this as we continue development of RStudio.

By the way, here's a trick for including backticks in code: wrap the code with an additional backtick. That is, if you have code with three backticks, wrap it with four backticks. I edited the original post to use this:

`````
````
---
output: html_document
---

```{r}
knitr::include_url("https://www.rstudio.com/")
```

````
`````

To display this example with four backticks, I wrapped it with five backticks.

Triage: Regression from Spotted Wakerobin.

**Comment by matt-gunther** [comment]
Brilliant! Thanks for the tick-tip!

**Comment by Robinlovelace** [comment]
Chiming in here from my RStudio installation, it makes previewing blogdown (and I guess other) websites unusable, tons of links opening every time I save a file. I critical issue for some use cases so please prioritise.

I'm on:

RStudio 2022.12.0+353 "Elsbeth Geranium" Release (7d165dcfc1b6d300eb247738db2c7076234f6ef0, 2022-12-03) for Ubuntu Jammy
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) rstudio/2022.12.0+353 Chrome/102.0.5005.167 Electron/19.1.3 Safari/537.36

See the screenshot in this issue for further info: https://github.com/rstudio/blogdown/issues/404

**Comment by ronblum** [comment]
@Robinlovelace Using RStudio Desktop 2022.12.0+353 on MacOS 13.1, I followed comment https://github.com/rstudio/blogdown/issues/404#issuecomment-1368109625:
1. I created a project using https://github.com/rbind/robinlovelace.
2. In the Build Pane: <kbd>Build Website</kbd>
3. In the Console Pane: `blogdown::serve_site()`
    - Index page of site is created in the Viewer Pane
4. In the Viewer Pane: Scroll down to "Setting-up Mastodon" and click on it.
    - The "Setting-up Mastodon" page is shown in the Viewer Pane.
    - The web browser opens with 12 tabs—6 for Mastodon links and 6 for Twitter.

This works fine in version 2022.07.2+576.

Triage: Upping for consideration in Cherry Blossom or sooner.

**Comment by Robinlovelace** [comment]
As a workaround the regression only appears in the desktop version so you can develop websites with RStudio Server in browers on localhost, localhost:8787 by default.

**Comment by mikebessuille** [comment]
Seems to be a duplicate of https://github.com/rstudio/rstudio/issues/12413?

**Comment by Robinlovelace** [comment]
Possibly although I think this issue is broader/different in test. Both will be closed by a single solution I guess.

**Comment by ronblum** [comment]
Additional info: This is also a problem with RStudio Desktop on Windows 11, not just MacOS.

**Comment by ronblum** [comment]
*More from @cderv, copied over from #12620:*

It seems that issue https://github.com/rstudio/rstudio/issues/2756 came back with Electron 

The reprex there is causing the issue 
````r
library(htmltools)
print(browse = TRUE, tags$iframe(src="https://www.rstudio.com/"))
````

On Windows, it opens in the IDE viewer but also 4 tabs in my Google Chrome opened browser

Issue can be encountered with anything showing in the browser like Quarto document 

````markdown
---
format: html
---

## sli.do iframe

```{=html}
<iframe src="https://app.sli.do/event/x37QvAtyvHXNGhFenp3cV1/embed/polls/32cd4326-7c95-4b38-9cef-cdc163ca790e" width="300" height="400"></iframe>
```
## iframe

```{=html}
<iframe src="https://quarto.org/" width="500" height="400"></iframe>
```
## YouTube iframe

```{=html}
<iframe src="https://www.youtube.com/embed/MBCPgQxlrD" width="560" height="315"></iframe>
```
````

Problem also encountered by @mine-cetinkaya-rundel who share the above document in Slack, and working on Mac OS I believe.

### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 2023.3.0.270
    OS Version      : Windows 10 x64 (build 22621)
    R Version       : R version 4.2.0 (2022-04-22 ucrt)

**Comment by ronblum** [comment]
*And even more from @cdrev, also from #12620:*

You get more example above that trigger the behavior. It is not only with Qmd or Rmd, but also from R code. 

Probably somehow linked to what IDE consider to be safe URL or not, as you can observed from the previous example above that Youtube Iframe does not open in external browser

https://github.com/rstudio/rstudio/blob/c6e146b27186c488d4e40c76ed1ec4cc192b5827/src/node/desktop/src/main/url-utils.ts#L79-L90

Hope it helps

**Comment by sharon-wang** [comment]
Just noting that on MacOS Ventura 13.1, I can't reproduce this issue when my default browser is Safari (`Version 16.2 (18614.3.7.1.5)`). However, I can reproduce with Chrome (`Version 109.0.5414.119`), although I only get 2 tabs.

I have a fix brewing though!

**Comment by ronblum** [comment]
@sharon-wang I'm still seeing issues in RStudio Desktop 2023.03.0-daily+312 on MacOS 13.2. This includes the browser opening new windows when the rendering is done the Viewer Pane but it still opens up browser windows. One improvement is that [using the steps from](https://github.com/rstudio/rstudio/issues/12494#issuecomment-1370092901) @Robinlovelace's repository only generates 6 windows instead of 12.

**Comment by ronblum** [comment]
@matt-gunther @cderv and @Robinlovelace, I just want to make sure that I didn't misunderstand something: When rendering or knitting in the Viewer Pane, everything should be in the Viewer Pane and no external web browser windows should be opened. Is this correct?

**Comment by cderv** [comment]
> no external web browser windows should be opened. Is this correct?

I believe no windows should be opened in an external browser in the example I shared. They are including as iframe content and no main page to look at, so it should not suddenly open several browser tab for you unexpectedly; 


I retried both with qmd shared above, and also this R code in console 
````r
library(htmltools)
print(browse = TRUE, tags$iframe(src="https://www.posit.co/"))
````

Fun fact: if the viewer I have a accept cookie box; If I click OK, it will open for me Facebook webpage 😅

**Comment by matt-gunther** [comment]
Exactly right @ronblum. Assuming the setting "Preview in Viewer Pane", my example should only render an HTML document in the viewer pane, and that HTML document should include an iframe (no browser window should open). Reverting to RStudio version 2022.07.2 works this way, but in version 2022.12.0+353  a browser window opens with several duplicate tabs.

**Comment by sharon-wang** [comment]
Thanks for the additional detail everyone!

PR https://github.com/rstudio/rstudio/pull/12660 cuts the duplicate tabs in half for this issue and https://github.com/rstudio/rstudio/issues/12413, but there's some additional issues with iframe (subframe) handling that seems to be the culprit for the urls being opened in an external browser (and multiple times).

Relevant code to this bug was originally added to handle navigation in iframes (for cases like https://github.com/rstudio/rstudio/pull/12660#issuecomment-1426437361) as we await electron's implementation of the `will-frame-navigate` event (https://github.com/electron/electron/pull/34418).

Currently, we're using `onBeforeRequest` to intercept iframe navigation, which seems to be too broadly checking for navigation, resulting in the extra code execution (which causes the external browser tabs). I'm trying to figure out if we can more narrowly detect the particular iframe navigation we're trying to handle (clicking on an url in an iframe, not when iframe `src` urls are requested), but we might need the `will-frame-navigate` event to do so in a reasonable way.

<details>
    <summary>For reference, reproduction cases I've been using</summary>

It's interesting that the following behaves as expected:

#### Case 1 - .Rmd file + Knit (Preview in Viewer Pane)
```RMarkdown
---
title: "Untitled2"
author: "Bug"
date: "`r Sys.Date()`"
output: html_document
---

<https://www.posit.co>
```
- no external browser tabs are opened when previewing
- when `https://www.posit.co` is clicked in the previewed document, the URL is opened in an external browser (no navigation occurs in the IDE) 

However, these cases result in the external browser tab issue.

#### Case 2 - .Rmd file + Knit (Preview in Viewer Pane)
````RMarkdown
---
title: "Untitled"
output: html_document
date: "2023-01-31"
---

```{r}
knitr::include_url("https://posit.co")
```
````

#### Case 3 - R Console

```R
library(htmltools)
print(browse = TRUE, tags$iframe(src="https://www.posit.co/"))
```

#### Case 4 - Quarto  + Render (Preview in Viewer Pane) (from https://github.com/rstudio/rstudio/issues/12413)

##### index.qmd
```Qmd
---
title: "Test"
format: html
---
```

##### _quarto.yml
```yml
project:
  output-dir: docs
  type: website
website:
  comments:
    hypothesis: true
```

</details>

**Comment by ronblum** [comment]
Confirmed that this is still happening in RStudio Desktop 2023.03.0-daily+318 on MacOS 13.2.

```
library(htmltools)
print(browse = TRUE, tags$iframe(src="https://www.posit.co/"))
```

Since we're dependent on a fix in Electron, I'm moving this to Mountain Hydrangea to continue to monitor this, in the hope that the issue be fixed in that timeframe.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2023.03.0-daily+323 on MacOS 13.2 that it's partly working based on the following three tests.

1. @Robinlovelace's repository [#12494#issuecomment-1370092901](https://github.com/rstudio/rstudio/issues/12494#issuecomment-1370092901): Improvement, but still failure. We now only get two browser windows instead of twelve.

2. in the Console Pane: Success.
```
library(htmltools)
print(browse = TRUE, tags$iframe(src="https://www.posit.co/"))
```

3. knitting an R Markdown file with the following: Success.
````
---
output: html_document
---

```{r}
knitr::include_url("https://www.rstudio.com/")
```
````

**Comment by sharon-wang** [comment]
@ronblum ahh so close! Thanks for testing various cases.

For test case 1, how can I get the website to preview in the Viewer Pane instead of in a separate browser? I'm sure it's a setting/config somewhere, but I can't seem to find it 😅 Following https://github.com/rstudio/rstudio/issues/12494#issuecomment-1370092901, at Step 3 (`blogdown::serve_site()`), the website opens in my default browser instead of in the Viewer Pane. I don't experience the extra browser tabs when the site opens in the browser, so this might be a workaround for now.

**Comment by Robinlovelace** [comment]
Amazing work on this! Just to say as a stop-gap for anyone needing one: I don't see the issue on RStudio Server, open or pro.

**Comment by sharon-wang** [comment]
Closing this issue as most of the failing cases have been resolved as part of Cherry Blossom.

The remaining case
> https://github.com/rstudio/rstudio/issues/12494#issuecomment-1370092901: Improvement, but still failure. We now only get two browser windows instead of twelve.

will be tracked in this issue: https://github.com/rstudio/rstudio/issues/12766
