### ISSUE TITLE
RStudio causes read_csv() to fail with "invalid argument to unary operator"

### ISSUE THREAD

**Issue by arencambre** [rstudio/rstudio#12525]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.12.0 Build 353
    OS Version      :  Windows 11 22H2
    R Version       : 4.2.2

I have Tidyverse 1.3.2 loaded. I have no pending package updates.

### Steps to reproduce the problem

Run these two lines of code (CSV file is attached).
[data_test.csv](https://github.com/rstudio/rstudio/files/10346696/data_test.csv)
```
library(tidyverse)
test <-- read_csv("data_test.csv")
```

### Describe the problem in detail
If you run these two lines of code within RStudio, you get standard output for read_csv() followed by this error:
**Error in FUN(left) : invalid argument to unary operator**

The **test** object is not created.

If you run identical code via an R console window--by loading **R 4.2.2** from the Start menu, with RStudio closed--the command works as expected.

### Describe the behavior you expected
These two lines of code work in RStudio.

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [X] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@arencambre Thank you for raising this! I see this behavior as well, though also in R outside of RStudio, and with older versions of `readr` as well (1.4.0 and 2.1.3). But if I change the variable name to something other than `test`, it works:

```
> library(readr)
> test2 <- read_csv("data_test.csv")
Rows: 1 Columns: 5                                                           
── Column specification ───────────────────────────────────────────────────────
Delimiter: ","
chr (3): 2022_general_location, 2022_general_address, profile
dbl (2): 2022_general_site, count

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
```

What happens if you change to something other than `test`?

**Comment by msummersgill** [comment]
@arencambre Not sure whether there could also be a `readr` issue, but your initial error was unrelated to either the IDE or R, but was rather due to an extra `-` in your assignment command.
![image](https://user-images.githubusercontent.com/19575728/210632165-dbc2e3be-5360-4c16-98ad-aff51e9bd5aa.png)

**Comment by ronblum** [comment]
@msummersgill D'oh. When I tried the other filename, I retyped the code instead of just changing the variable name in the original code. Thank you!

**Comment by arencambre** [comment]
I am an idiot! 🫢

Thank you, and sorry for the time waste.

**Comment by ronblum** [comment]
No problem! I bear some of the responsibility. 😅 

FWIW, I didn't notice it because I was using a FiraCode and I didn't realize how good it is at creating arrows.
<img width="340" alt="firacode" src="https://user-images.githubusercontent.com/31009952/210652932-4df0a098-a208-4d29-8f65-443ec6bd11af.png">

 It's obvious in Monaco font:
<img width="326" alt="monaco" src="https://user-images.githubusercontent.com/31009952/210653040-a8af6a7d-606f-4e0b-959b-8e51ba0bea3f.png">

**Comment by arencambre** [comment]
You have no responsibility for me being stupid. :-)
