### ISSUE TITLE
Problems with C++ compiler toolchain for R on Mac in newer Rstudio versions

### ISSUE THREAD

**Issue by paul-buerkner** [rstudio/rstudio#12529]
Cross-posting in from the Rstudio forums (https://community.rstudio.com/t/problems-with-c-compiler-toolchain-for-r-on-mac-in-newer-rstudio-versions/156561) as per request.

I recently came across an issue with the C++ toolchain on Mac that I assume exists since Ventura (Mac 13.x). Up until Rstudio version 2022.02.4-500, this issue never made problems for me in R, but it appeared once I upgraded to more recent versions, specifically 2022.12.0-353. In that later version, I was not able to compile most R packages and also no Stan models anymore when using R through Rstudio.

After playing around for some time, I now unstand it and want to share it with the community in case other's run into the same problem.

The reason turned out to be a change in how the PATH environment variable is handled in Rstudio. Previously (version 2022.02.4-500 or earlier), my PATH as seen via `Sys.getenv("PATH")` was

`/usr/bin:/bin:/usr/sbin:/sbin:/Library/Developer/CommandLineTools/usr/bin:/usr/local/bin:/opt/homebrew/bin/gfortran:/Library/TeX/texbin:/Library/Apple/usr/bin:/opt/local/bin:/Applications/RStudio.app/Contents/MacOS/postback`

In particular, `/usr/bin:/bin:/usr/sbin:/sbin` was at the front.

In the newer version of Rstudio (e.g., version 2022.12.0-353), my PATH was now

`/opt/local/bin:/opt/local/sbin:/opt/homebrew/bin:/opt/homebrew/sbin:/Library/Developer/CommandLineTools/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/homebrew/bin/gfortran:/Library/TeX/texbin:/Library/Apple/usr/bin:/Users/paul.buerkner/Applications/quarto/bin:/usr/texbin:/Applications/RStudio.app/Contents/Resources/app/bin/postback`

so no more `/usr/bin:/bin:/usr/sbin:/sbin` at the front but rather behind `/Library/Developer/CommandLineTools/usr/bin`.

Once /`Library/Developer/CommandLineTools/usr/bin` was removed from the PATH entirely or `/usr/bin:/bin:/usr/sbin:/sbin` was put to the front, things worked correctly. I don't know why `/Library/Developer/CommandLineTools/usr/bin` needs to be in the PATH but it seems Mac itself wants it to be there (it is added in `/private/etc/paths`, a file that does not want to be changed easily).

Perhaps future versions of Rstudio could again add `/usr/bin:/bin:/usr/sbin:/sbin back` at the start of the PATH just to be safe?

**Comment by kevinushey** [comment]
Hm, my `/etc/paths` has:

```
$ cat /private/etc/paths
/opt/local/bin
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
```

but I did edit it myself to add `/opt/local/bin` a while back. I'm curious what the default file contents are in a factory-fresh installation of macOS Ventura; are you sure you didn't modify it? 

All that said, these PATH components:

```
/usr/bin:/bin:/usr/sbin:/sbin
```

normally should be near the end of the PATH, as users might want to place their own utilities in "front" of the default system utilities (e.g. using `git` from `/usr/local/bin/git` instead of `/usr/bin/git`).

For posterity, it might be useful to know what exact error you were seeing during compilation of C++ sources.

**Comment by technocrat** [comment]
This has caused a fair amount of problems for macOS users, the most pressing of which is exemplified by
```
install.packages("ggblanket")
#> Warning in system(paste0("tar zxf \"", path.expand(what), "\" -C \"",
#> path.expand(where), : error in running command
#> Warning: 'tar' returned non-zero exit code 127
#> Error: file '/var/folders/0j/3g7q2zss7fb55q5wqg9t141r0000gn/T//RtmppoOPjA/downloaded_packages/ggblanket_1.6.2.tgz' is not a macOS binary package
Sys.info()
#>                                                                                                sysname 
#>                                                                                               "Darwin" 
#>                                                                                                release 
#>                                                                                               "22.2.0" 
#>                                                                                                version 
#> "Darwin Kernel Version 22.2.0: Fri Nov 11 02:03:51 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T6000" 
#>                                                                                               nodename 
#>                                                                                       "Diomedes.local" 
#>                                                                                                machine 
#>                                                                                                "arm64" 
#>                                                                                                  login 
#>                                                                                                 "root" 
#>                                                                                                   user 
#>                                                                                                   "ro" 
#>                                                                                         effective_user 
#>                                                                                                   "ro"
```
Created on 2023-01-05 with [reprex v2.0.2](https://reprex.tidyverse.org/)

Run in the terminal pane or in a terminal app, the error does not appear.

**Comment by kevinushey** [comment]
> #> Warning: 'tar' returned non-zero exit code 127

That error usually means that `tar` is not on the PATH, which seems surprising. Can you confirm what `Sys.which("tar")` reports, and `Sys.getenv("PATH")` from that R session?

For posterity, I have:

```
> Sys.which("tar")
           tar
"/usr/bin/tar"
> writeLines(strsplit(Sys.getenv("PATH"), ":")[[1]])
/Users/kevin/.rd/bin
/Users/kevin/.pyenv/shims
/Users/kevin/.nvm/versions/node/v16.14.0/bin
/Users/kevin/.yarn/bin
/Users/kevin/.config/yarn/global/node_modules/.bin
/Users/kevin/bin
/Library/TeX/texbin
/opt/local/bin
/opt/homebrew/bin
/usr/bin
/bin
/usr/sbin
/sbin
/opt/X11/bin
/Library/Apple/usr/bin
/Users/kevin/.rd/bin
/Users/kevin/.cargo/bin
/Users/kevin/.nvm/versions/node/v16.14.0/bin
/Users/kevin/projects/depot_tools
/Users/kevin/.fzf/bin
```

**Comment by technocrat** [comment]
From the console
`> Sys.which("tar")
tar 
 "" 
> Sys.getenv("PATH")
[1] "/opt/homebrew/bin:/opt/homebrew/sbin:/bin;/usr/bin;/usr/local/bin;/usr/sbin;/sbin;/Users/ro/local/bin:/Users/ro/Library/Python/3.8/bin:/Users/ro/Applications/quarto/bin:/Library/TeX/texbin:/usr/texbin:/Applications/RStudio.app/Contents/Resources/app/quarto/bin:/Applications/RStudio.app/Contents/Resources/app/bin/postback"
> `

from an R session in terminal pane
`> Sys.which("tar")
           tar 
"/usr/bin/tar" 
> Sys.getenv("PATH")
[1] "/Users/ro/.nvm/versions/node/v18.9.1/bin:/usr/local/mysql-8.0.28-macos11-x86_64/bin:/bin:/usr/bin:/usr/local/bin:/usr/sbin:/sbin:/Users/ro/.local/bin:/Users/ro/Library/Python/3.9/bin:/Applications/CMake.app/Contents/bin:/opt/homebrew/bin:/Users/ro/.cargo/bin:/Applications/Julia-1.8.app/Contents/Resources/julia/bin/julia:/usr/local/go/bin:/Users/ro/.fig/bin"
`

**Comment by kevinushey** [comment]
> [1] "/opt/homebrew/bin:/opt/homebrew/sbin:/bin;/usr/bin;/usr/local/bin;/usr/sbin;/sbin;/Users/ro/local/bin:/Users/ro/Library/Python/3.8/bin:/Users/ro/Applications/quarto/bin:/Library/TeX/texbin:/usr/texbin:/Applications/RStudio.app/Contents/Resources/app/quarto/bin:/Applications/RStudio.app/Contents/Resources/app/bin/postback"

I note that some of the PATH entries are separated with `;` rather than `:` -- I'm not sure where or why that could be happening.

**Comment by paul-buerkner** [comment]
> but I did edit it myself to add /opt/local/bin a while back. I'm curious what the default file contents are in a factory-fresh installation of macOS Ventura; are you sure you didn't modify it?

I am not sure. I may have added it myself, but I cannot remember anymore. The reason, why I brought up this issue here is that previous Rstudio versions had avoided it gracefully. I don't know how the `/private/etc/paths` would look like in a fresh Ventura install. 

Here are some errors that I am seeing when I am using the PATH that is currently default on my system with the new Rstudio version:

```R
Sys.getenv("PATH")
[1] "/opt/local/bin:/opt/local/sbin:/opt/homebrew/bin:/opt/homebrew/sbin:/Library/Developer/CommandLineTools/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/homebrew/Cellar/gcc/12.2.0/bin/gfortran-12:/usr/local/texlive/2021/bin/universal-darwin:/Library/Apple/usr/bin:/Users/paul.buerkner/Applications/quarto/bin:/usr/texbin:/Applications/RStudio.app/Contents/Resources/app/bin/postback"
```


Installing an R package from source that needs C++ compilation:
```R
> install.packages("ape", type = "source")
trying URL 'https://cran.rstudio.com/src/contrib/ape_5.6-2.tar.gz'
Content type 'application/x-gzip' length 1754486 bytes (1.7 MB)
==================================================
downloaded 1.7 MB

* installing *source* package ‘ape’ ...
** package ‘ape’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
clang -arch arm64 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/Rcpp/include' -I/opt/R/arm64/include   -fPIC  -falign-functions=64 -Wall -g -O2  -c BIONJ.c -o BIONJ.o
In file included from BIONJ.c:22:
In file included from ./me.h:8:
/Library/Frameworks/R.framework/Resources/include/R.h:44:11: fatal error: 'stdlib.h' file not found
# include <stdlib.h> /* Not used by R itself, but widely assumed in packages */
          ^~~~~~~~~~
1 error generated.
make: *** [BIONJ.o] Error 1
ERROR: compilation failed for package ‘ape’
* removing ‘/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/ape’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/ape’
Warning in install.packages :
  installation of package ‘ape’ had non-zero exit status
```

Trying to compile a Stan model with cmdstan(r):
```R
> library(brms)
> fit <- brm(count ~ zAge + zBase * Trt + (1|patient),
+            data = epilepsy, family = poisson(), backend = "cmdstanr")
Compiling Stan program...
ld: library not found for -lc++
clang: error: linker command failed with exit code 1 (use -v to see invocation)

make: *** [/var/folders/yx/cyjlcbj51cv_vnkyryldf39c0000gn/T/RtmpSnWtCK/model-161ebe75cb9] Error 1

Error: An error occured during compilation! See the message above for more information.
```

**Comment by kevinushey** [comment]
Is it possible that you have a custom compiler on the PATH that isn't set up to find the standard library headers? What does `Sys.which("clang")` or `Sys.which("clang++")` report?

**Comment by paul-buerkner** [comment]
Yes, this is what I assume happend in some way. Here is the output:

```R
> Sys.which("clang")
                                              clang 
"/Library/Developer/CommandLineTools/usr/bin/clang" 

> Sys.which("clang++")
                                              clang++ 
"/Library/Developer/CommandLineTools/usr/bin/clang++" 
```

**Comment by paul-buerkner** [comment]
Without the `/Library/Developer/CommandLineTools/usr/bin` in PATH I get:

```R
> Sys.which("clang")
           clang 
"/usr/bin/clang" 

> Sys.which("clang++")
           clang++ 
"/usr/bin/clang++" 
```

So it is clear that this is the reason. My question is if Rstudio wants to safeguard users against this kind of problem as it already did in the past.

**Comment by TracyRad** [comment]
Has this problem been worked on or resolved several months later? I cannot get my iMac to work with any package that uses C++ compiler. Sorry for necroposting if that is a thing here, but I can't submit on git per rules, because R won't even let me select crash reports. The crash reports can not be found in /etc as they should be or ~/r.

Despite installing Xcode and command line tools, I get this:

> macrtools::xcode_cli_install() 
Attempting to install Xcode CLI version: Command Line Tools for Xcode-14.3 ...
Please be patient or grab a cup of coffee as Xcode CLI installs.

We expect the installation to take between 10 to 15 minutes.
Running command with sudo ...
You may be prompted for your user password ...
sudo -kS softwareupdate -i 'Command Line Tools for Xcode-14.3' --verbose 
Software Update Tool
Finding available software
Downloading Command Line Tools for Xcode
Downloaded Command Line Tools for Xcode
Installing Command Line Tools for Xcode
Done with Command Line Tools for Xcode
Done.
> macrtools::is_xcode_cli_installed()
[1] FALSE
 macrtools::is_gfortran_installed()
[1] TRUE

I tried to run brms or rstan or rstanarm anyway and I get this: 
Compiling Stan program...
Start sampling

SAMPLING FOR MODEL '9e74e5782f1c71223c7433e864a3913d' NOW (CHAIN 1). 
Then a fatal error in R.   --- BTW, again, for some reason, now I ALSO CANNOT SELECT AUTO CRASH REPORTS IN R STUDIO! 

and after updating Xcode, it now says this on my path:
"/Library/Frameworks/Python.framework/Versions/3.9/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/Library/Frameworks/Python.framework/Versions/3.10/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Apple/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/Trace/Applications/quarto/bin:/Library/TeX/texbin:/usr/texbin:/Applications/RStudio.app/Contents/Resources/app/quarto/bin:/Applications/RStudio.app/Contents/Resources/app/bin/postback"

What is up with all the apple.security in the path? Is there something I did that is the result of this? 
I'm adding some points to my issue brought up in earlier posts to the OP. 
> Sys.which("clang")
           clang 
"/usr/bin/clang" 
> Sys.which("clang++")
           clang++ 
"/usr/bin/clang++"
Sys.which("tar")
           tar 
"/usr/bin/tar" 

I also changed my file path and still cannot use rstan -- fatal report. 

New file path: 
> Sys.getenv("PATH")
[1] "/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/gfortran/bin:/Library/Developer/CommandLineTools/usr/bin:/usr/bin/clang:/usr/bin/clang++:/usr/bin/python3:/Library/Apple/usr/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/local/bin:/private/etc/paths:/Users/Trace/Applications/quarto/bin:/Library/TeX/texbin:/usr/texbin:/Applications/RStudio.app/Contents/Resources/app/quarto/bin:/Applications/RStudio.app/Contents/Resources/app/bin/postback"

This could be wrong and not have helped me at all, I  followed recs here and across the git universe. Please tell me someone is investigating a bug.
