### ISSUE TITLE
Zooming for "Help pane"

### ISSUE THREAD

**Issue by github-wow** [rstudio/rstudio#12540]
Hi,

please add for the "Help" pane:  

1. "web page"-style view with text wrapping (like in MS Word);
2. zooming feature (with mouse wheel scrolling) feature 

Thanks

**Comment by sharon-wang** [comment]
Thanks for opening an enhancement suggestion!

I'd like to better understand what you're looking for, so I have a few follow-up questions for you.

For `1. "web page"-style view with text wrapping (like in MS Word)`, are you experiencing any issues with text wrapping in the Help Pane? When you resize the Help Pane, does text wrap as you'd expect?

Just as a side note, if you'd like a larger or separate window for the Help Pane, you can open the pane as a separate window using the "pop out" button:
<img width="1225" alt="image" src="https://user-images.githubusercontent.com/25834218/231212079-a4d64f92-f8e3-4d02-ac00-6af31c782954.png">

Regarding `2. zooming feature (with mouse wheel scrolling) feature`, are you looking to zoom in on the text because you'd like the font size to be larger? You can zoom by holding `Ctrl` or `Command` and pressing `+` (plus) to zoom in, or pressing `-` (minus) to zoom out. The zoom does apply to the whole IDE and isn't isolated to the Help Pane -- perhaps you're looking for the zoom to apply specifically to the Help Pane?
