### ISSUE TITLE
Quarto missing in Fedora's RStudio RPM - impossible to build

### ISSUE THREAD

**Issue by s-fischbach** [rstudio/rstudio#12609]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2022.12.0-353
    OS Version      : Linux, Fedora 37
    R Version       : 4.2.2

### Steps to reproduce the problem
1. Install the most recent version of RStudio (2022.12.0-353 at the time of writing) via Gnome Software on Fedora 37.
2. Start RStudio
3. Try to create a Quarto file: Menu option "File > New File > Quarto Document" is missing. In "Global options", Quarto options are missing. Opening a Quarto document in the visual editor results in a spinning load indicator and does not show the document.

### Describe the problem in detail
The fedoraproject.org RPM of RStudio has been build without Quarto. This has been mentioned in the [Posit community](https://community.rstudio.com/t/quarto-not-installed-in-rstudio-new-project-menu-choices-in-fedora37/153704). I filed a [bug report](https://bugzilla.redhat.com/show_bug.cgi?id=2162538) in Red Hat Bugzilla which led to the following response by _Iñaki Ucar_:

> Unfortunately, Quarto, in its current state (of dependencies, particularly Deno), cannot be built and distributed in Fedora, and therefore our build disables Quarto. Unless RStudio provides a way to dynamically discover and use a user-installed version of Quarto, there's nothing we can do.

### Describe the behavior you expected
Quarto should be available when installing the most recent version of RStudio on Fedora.

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [X] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@s-fischbach Thank you for raising this!

@Enchufa2 I'm able to install RStudio Desktop binaries on Fedora 37, which include the bundled Quarto binaries.  This is true with the released RStudio Desktop 2022.12.0+353 with Quarto 1.2.269 and the in-development RStudio Desktop 2023.03.0-daily+272 with Quarto 1.2.280. Do you know what might be causing the difference between the RStudio binaries vs. RPMs?

**Comment by Enchufa2** [comment]
Per our [packaging guidelines](https://docs.fedoraproject.org/en-US/packaging-guidelines/what-can-be-packaged/#prebuilt-binaries-or-libraries),

> All program binaries and program libraries included in Fedora packages must be built from the source code that is included in the source package.

Unfortunately, in its current state, Quarto is almost impossible for us to build from source due to its dependencies. There are several issues, but particularly two big show-stoppers:

1. Dart Saas is a nightmare, because it requires the Dart SDK.
2. Deno is an even bigger nightmare. Packaging Deno would be a huge undertaking alone, but also there are dozens of licensing issues in its modules. Also there's the fact that it only builds for x86_64 and aarch64. We currently ship RStudio for ppc64le and s390x too.

Citing a fellow packager that looked into Deno,

> Basically, maintaining a "properly done" package of deno for Fedora would be a full-time job, because of the sheer number of individual components, which also mostly need to be updated in a coordinated fashion.

So I simply cannot manage to get basically two new software stacks to Fedora in order to build Quarto in order to activate it in RStudio, so I disable Quarto in our build.

Solutions? Quarto could use other software stacks, more amenable to packaging, to cover those functionalities. Should I even ask? I'm pessimistic about it. But it would be helpful for everyone involved if RStudio could make this plug-and-play. I.e., use Quarto if found (e.g., because the user installed it), or pandoc otherwise.

**Comment by ronblum** [comment]
@Enchufa2 Thank you for all the info! I'll bring this up with the Quarto team as a starting point.

**Comment by dragonstyle** [comment]
Thank you, this is helpful. We're pretty deeply dependent upon Deno in particular so I think breaking that logjam will be hard. 

I do think it would make sense to pursue the `plug and play` that you suggest, having the `Quarto-less` configuration of RStudio still probe for user installed Quarto and use that, and I don't think this would be too too difficult based upon my understanding of RStudio.

**Comment by Enchufa2** [comment]
Many thanks for your consideration!

**Comment by Enchufa2** [comment]
I would like to add, to help make the case and maybe bring this up in the backlog, that Quarto is evolving quickly, and users may want to update it more often than RStudio. So implementing this mechanism to use an external Quarto installation would be benficial to all users.

**Comment by leonardblaschek** [comment]
Sitting in the same fedora boat, my experience is that quarto, when explicitly installed, doesn't integrate with Rstudio at all. What works of the visual editor (as Tim wrote above) is just Rstudio rendering the quarto document as an rmarkdown file. An revealjs quarto file, for example, will render as a simple markdown html, both in preview and when you click render. The only way to get it rendered as quarto is to do it via the command line and call quarto directly. In other words, writing quarto docs in Rstudio currently doesn't have any advantages over writing quarto docs in any simple texteditor on Fedroa. Here's hoping you can implement the plug-in-play suggested by @dragonstyle above.

**Comment by Enchufa2** [comment]
It's sad that this issue only loses priority over time. :( I think that it has some value to Posit that we independently build RStudio for Fedora, because more bugs are found and we contribute back to the project. But without Quarto support, we are losing users of our packages over time, and you are losing that value. :(

**Comment by jthomasmock** [comment]
Hi @Enchufa2 per @dragonstyle in https://github.com/rstudio/rstudio/issues/12609#issuecomment-1405563577 -- Quarto won't be moving off of Deno in the near future (or likely long-term).

I've opened a new issue to track the "RStudio without Quarto issue" as Quarto being supported on the OS, is a separate issue than making RStudio more usable without Quarto.

**Comment by ronblum** [comment]
@Enchufa2 Thanks!
