### ISSUE TITLE
$PATH not respected by RStudio

### ISSUE THREAD

**Issue by JosiahParry** [rstudio/rstudio#12747]
### System details

    RStudio Edition : "desktop"
    RStudio Version :  ‘2022.12.0+353’
    OS Version      :  macOS Monterey 12.0
    R version:  4.2.2 (2022-10-31)
      Platform: aarch64-apple-darwin20 (64-bit)
      Running under: macOS Monterey 12.0

### Steps to reproduce the problem

Open a terminal. Modify your path. Open RStudio run `Sys.getenv("PATH")` and `system("echo $PATH")`. In your terminal run `echo $PATH`. Note that the path in rstudio in both calls does not contain the modification. 

<img width="786" alt="image" src="https://user-images.githubusercontent.com/13534508/220928719-fc8ba7d1-59f7-433a-9ac4-fd26ba70a50c.png">
<img width="532" alt="image" src="https://user-images.githubusercontent.com/13534508/220928760-2c065116-ed42-4c45-b601-00863f6ca50c.png">

I believe I've reported this issue previously but could not find the issue. 
It also seems related to https://github.com/rstudio/rstudio/issues/12585

### Describe the problem in detail

The `PATH` that is available to my machine is _not_ available to RStudio. 

### Describe the behavior you expected

RStudio should inherit the global path and not create and maintain its own PATH. 

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Hi @JosiahParry! A couple of things:
1) Is this new in 2022.12? We don't expect RStudio Desktop to read .zshrc if it's run by clicking the icon, only the global MacOS paths.
2) What happens if you run RStudio from the command line—is it respecting PATH?
3) Does adding an an entry in `/etc/paths` pick up the

**Comment by MariaSemple** [comment]
Hi @JosiahParry, if I'm reading the report correctly these are the steps you followed (or very similar):

1. open a terminal
2. run `export PATH=$PATH:/some/other/path`
3. start RStudio by clicking on the icon in the MacOS UI
4. check the `PATH` inside RStudio

If that's correct, then that is expected behaviour. When you change the path in a terminal like that, it only affects the terminal that you changed it in. Additionally, as @ronblum has mentioned, we don't expect RStudio to respect an `rc` file (`.bashrc` or `.zshrc`) if started by clicking on the icon. If you were to follow step 2 above by running `/Applications/RStudio/RStudio.app` (or wherever `RStudio.app` is installed on your machine) from the same terminal (#2 in Ron's list) we would expect that to work as desired. The other option Ron also listed, which is to set the entry in a global location, like /etc/paths.

I'm going to close this issue for now, but if I've misunderstood the sequence of events let us know and we can re-open the issue.
