### ISSUE TITLE
Changing font size in any window changes font size in all windows

### ISSUE THREAD

**Issue by PhilSmith26** [rstudio/rstudio#12831]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.03.0+386 (2023.03.0+386)
    OS Version      : macOS Ventura 13.2.1
    R Version       : 4.1.1 (2021-08-10) -- "Kick Things"

### Steps to reproduce the problem
(1) Create a data frame using RStudio (e.g. data(mtcars))
(2) View the data frame (View(mtcars))
(3) Click the "Show in new window" button
(4) Increase the font size in the new window (press command+ in the new window)
(5) Observe that the font size in the RStudio window also increases

### Describe the problem in detail
I have my RStudio font size set up to suit my eye comfort. When I view a data frame using the View(df) command, I want to see the df in an external window so I can look at it while working on my code in RStudio. So I click the "Show in new window" button. This moves the displayed df to an external window and lets me view my code in RStudio at the same time. But the font size in the new window is very small so I press command+ in that window to increase the font size. That works, but it increases the font size in the RStudio window at the same time, which I do not want. Previously this was not the case. 

### Describe the behavior you expected
I expect  to be able to change the font size in the external window without affecting the font size in the RStudio window.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
I was able to reproduce this.

In desktop versions prior to Elsbeth Geranium (2022.12), zooming a satellite window did not change the zoom of the main window. However, this was also buggy, because the last window whose zoom was changed is the one writing the preference. Thus when you quit and restart, all the windows get the text size from the one you changed last.

So in that regard the new behaviour is more consistent (at least when quitting and restarting) since we only have a single zoom preference at the moment.

**Comment by gtritchie** [comment]
I also tried with RStudio Server (I tried both the 2022.07 and 2022.12 releases) and changing font size in any RStudio window changes all others at the same time. So the new desktop behavior is actually the "by design" behavior.

Thus this issue might better be worded as a feature request: "Support different font sizes in each RStudio window".
