### ISSUE TITLE
Inconsistent behaviour in the crossref index in the RStudio visual editor

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#12882]
Needed for Quarto 1.3. See Quarto issue https://github.com/quarto-dev/quarto/issues/120 and commit https://github.com/rstudio/rstudio/commit/3fb564f0cdd35f5327a3ab1afc45b180fdba6a02 for details.

**Comment by ronblum** [comment]
Original conditions now work. However, see https://github.com/quarto-dev/quarto/issues/120#issuecomment-1491712511 for a condition in which the cross references are missing.

**Comment by ronblum** [comment]
Tested with Quarto version 1.3.299 and RStudio Desktop 2023.03.1+422/4 on MacOS 13.2.

The original steps in https://github.com/quarto-dev/quarto/issues/120#issue-1635819906 work. However, I found one condition in which the cross references don't show up:
1. Create a new Quarto document.
2. In source mode, paste the code above.
3. Switch back to visual mode and click somewhere in the body of the document.
4. <kbd>Insert -> Cross Reference</kbd>
    - Neither of the cross references is available.
5. Save the file.
6. <kbd>Insert -> Cross Reference</kbd>
    - Neither of the cross references is available.
7. Add another character.
8. <kbd>Insert -> Cross Reference</kbd>
    - Sometimes the cross references now appear.
    - But sometimes, the cross references never appear. Instead, the message "Working" appears, and never goes away. The Insert -> Cross Reference can be closed, but the IDE becomes unusable—files can be edited but not saved, the Console is unresponsive, you can't switch between panes, etc. The only thing that can be done is to quit RStudio and restart.
<img width="673" alt="working" src="https://user-images.githubusercontent.com/31009952/231257228-cf616f86-3aef-4eda-b7a3-d747c7fb5b6b.png">

**Comment by timtmok** [comment]
I've managed toidentify another cause where no cross references are shown. When saving the file, the first attempt to insert a cross reference will generate the cross reference index. This index is cached for the next time the cross reference index is loaded. If no edits are made, the cross reference cache is used. It is reading this cache that has a problem with the cache format.

So rendering the document isn't necessary. As long as the cache is being used, which happens if the document was saved, not edited, and the insert cross reference shown once before, then it won't show any cross references.

Repro steps:
1. Create a new Quarto document.
2. In source mode, paste the code above and save the file.
3. Switch to visual mode and place the cursor in the body of the document.
4. `Insert -> Cross Reference` (this generates the cache) and close the dialog
5. `Insert -> Cross Reference` (this shows no cross references)

The IDE is still usable in this case.

I haven't quite found why the IDE gets into an unusable state. I've seemed to trigger it a couple of times and events stop appearing. In progress events to the rsession time out.

**Comment by timtmok** [comment]
I tried some things out with Ron and found a reproducible case to generate the unresponsive UI.

Steps:
1. Create a new Quarto document using `File -> Quarto Document` (creates an unsaved, untitled document)
2. Paste the code from the reprex
3. Switch to visual mode and place the cursor in the body of the document
4. `Insert -> Cross Reference`

It seems to hang at the point of running `pandoc` to generate the cross reference index. This makes `rsession` unresponsive to further requests, which is why the UI hangs as it cannot communicate to get data for updating the UI.

**Comment by timtmok** [comment]
The hang while running `pandoc` is from feeding it blank input for the file contents. It seems unable to process the result (successful return code, nothing in stderr). When trying to read the unsaved file, it doesn't build a path to the temp file and incorrectly uses the home directory.

This should be protected from running pandoc with no content (same issue with a saved file without content) as well as properly retrieving the content for the unsaved file.

**Comment by timtmok** [comment]
The next build will have both fixes for the unresponsive UI and no cross references loading.

**Comment by ronblum** [comment]
Verified using RStudio Desktop 2023.03.1+434 on Red Hat 9.1 that cross references now show up, whether or not the source file was saved.

The unresponsiveness isn't occurring on earlier versions of RStudio Desktop on Red Hat, so waiting for a MacOS build to verify fix.

**Comment by ronblum** [comment]
Verified using RStudio Desktop 2023.03.1-daily+304:
- IDE doesn't become unresponsive.
- Cross references show up.

Note that the file first needs to be saved for any cross references to show up, although after a file is first saved, new cross references show up, too.

**Comment by ronblum** [comment]
Reopening: Just saving the file isn't enough. After saving the file, you first have to do something else, like inserting a space or switching to source mode, saving, and then switching back to visual mode.

**Comment by timtmok** [comment]
I've got another PR ready for review. Saving the file causes the rendered cross reference index cache to be created but not actually populated. So it was always preferring the newer rendered cross reference index even though the indexing was never run at all.

I'm adding a check on this cache to determine if the indexing needs to run.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2023.05.0-daily+320 on MacOS 13.4, Windows 11, and Red Hat 9.1.
