### ISSUE TITLE
Broken output of dataframes' last page (Markdown visual editor)

### ISSUE THREAD

**Issue by x1o** [rstudio/rstudio#12929]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.03.0+386
    OS Version      : MacOS Ventura 13.1 (22C65)
    R Version       : 4.2.2 (2022-10-31)

### Steps to reproduce the problem

1. Create a new R Notebook
2. Insert a new chunk, enter `mtcars`
3. Run the chunk
4. Navigate to the last page of the output

### Describe the problem in detail

<img width="1054" alt="image" src="https://user-images.githubusercontent.com/3007504/228444003-1bf91b38-bda0-4a43-bc8c-62704e77d58d.png">

<img width="1058" alt="image" src="https://user-images.githubusercontent.com/3007504/228443756-428206af-6591-4663-8a26-e82e3be8caee.png">

### Describe the behavior you expected

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@x1o Thank you for raising this! I can't reproduce this in the same environment, though. A few things:
1) This shouldn't make a difference, but what happens with a light theme?
2) Does this happen with other data sets? For example, `iris`.
3) What happens if you preview or knit the file—does it show up correctly?
4) Do you know if this worked or was an issue in earlier versions of RStudio?

**Comment by x1o** [comment]
Hi Ron!

1. Visual mode only
2. The problem persists
3. Yes, but! Only if the last page has less than 10 rows
4. Preview works just fine
5. It was an issue in the previous stable release of RStudio, yes

<img width="891" alt="image" src="https://user-images.githubusercontent.com/3007504/228537944-7afdc6b2-f21b-4925-a316-294a12238374.png">
<img width="888" alt="image" src="https://user-images.githubusercontent.com/3007504/228538011-9dc654ec-de7e-4f3f-b324-2eb815444be9.png">
<img width="1023" alt="image" src="https://user-images.githubusercontent.com/3007504/228538307-52df5870-895c-4074-8a44-b1f300ae2205.png">

**Comment by ronblum** [comment]
@x1o Thanks for the info!

@timtmok Do you have any thoughts about what might be happening or how to investigate this further?

**Comment by timtmok** [comment]
@ronblum This is something that I'm not familiar with since it's from quarto-dev/quarto code but it might be something wrong with feeding the output back to the visual editor. There have been about a dozen changes to the visual editor since the 2023.03.0 release. A daily build from Mountain Hydrangea might have fixed it.
