### ISSUE TITLE
Add support for environment variable to publish deploy

### ISSUE THREAD

**Issue by hadley** [rstudio/rstudio#13032]
Now that https://github.com/rstudio/rsconnect/pull/794 has been merged, it would be great if the IDE could add the ability to select from currently available environment variables.

**Comment by kevinushey** [comment]
@hadley: any opinion on the priority of this issue?

**Comment by kmasiello** [comment]
Big agree on the need. It's a hurdle to deploying effortlessly, and it also encourages publishers to do things like include their .Renviron / .Rprofile in their deployment bundle to make it work. They don't know this isn't the right way to solve the problem, and we make it so easy to go down that bad path by providing the file browser.

**Comment by kevinushey** [comment]
We're definitely planning to work on this for the next RStudio release, but I'm trying to iron out the UI design. I've asked around a bit internally but I figure it doesn't hurt to ask here as well!

- Do we want to allow users to specify these environment variables at deploy time? Or, to modify an existing deployment? Or, both?

- Does a user typically want to associate specific environment variables with specific deployments? Or do they re-use the same variables for all their deployments? Or is there any sort of scoping?

- Do you think users will want to set this via UI, or rather do this programmatically in some way? (E.g. set an R variable, or R callback function, which can associate deployments with environment variables)

- Do we have any existing proposals for where this UI should live, or what the UI should look like?

My guess / proposal is that we'd want to add a button / input widget to this deploy dialog:

<img width="603" alt="Screenshot 2024-08-29 at 9 29 38 AM" src="https://github.com/user-attachments/assets/12977508-70bf-45dd-b047-55d497f59ffb">

We could either do a free-form text input where you just copy the names of environment variables, or (probably more user friendly) a multi-select widget that's populated with environment variable names (perhaps with some smart filtering on what environment variables a user might actually care about publishing)

**Comment by ronblum** [comment]
Are we including only environment variables from `.Renviron` and `.Rprofile`? Maybe their site-wide equivalents? Or are there others? Asking because I have a fair number of environment variables, but the only one that shows up is one I have defined in `.Renviron` (`DATABRICKS_TOKEN` if that's useful). And even there, I have two defined, but only the databricks token shows up; I also have `R_MAX_VSIZE`, but that's not in the list.

**Comment by ronblum** [comment]
@kevinushey Does the pattern at https://github.com/rstudio/rstudio/blob/661e130f4cfd91ac355c40169c64d224ae87a0aa/src/cpp/session/modules/SessionRSConnect.R#L30 cover it all, or are there any others that should get picket up?

**Comment by kevinushey** [comment]
@jthomasmock and I made the decision that:

- We would explicitly only check for environment variables in either the project directory, or the user directory -- we don't check the site-wide equivalents;
- We would filter to only environment variables that are likely to contain keys / credentials, to avoid listing irrelevant environment variables.

So I think this is all expected.

**Comment by ronblum** [comment]
Verified* in RStudio Desktop 2024.11.0-daily+269 on Windows 11.

Checked
- In project and no project
- Using Renviron and Rprofile (although the source shouldn't matter, they're handled by R)
- Key words with word boundaries vs. part of a long word
- Upper and lower case
- Number of variables is accurate
- From Editor Pane, Viewer Pane, and external window
    - Though not really on external window due to #15289 
- Variables passed on if and only if they're selected
    - Checked in both deployment log and variables tab at Connect
- Values passed from RStudio to Connect are accurate

Caveats:
1) I'm assuming that we're not picking up `PWD` and `PASSWORD` because they're too dangerous, but I wouldn't be opposed to including them.
2) It's possible to create an environment variable with spaces, e.g. 
`'np_environ PASS RRR'=rrr`
will result in the name-value pair `'np_environ PASS RRR'` and `rrr`. We're not matching this (we also don't if we use underscores instead of spaces). I'm all for not passing these variables on. Though if should, I can reopen this.
