### ISSUE TITLE
Credentials are visable in console output

### ISSUE THREAD

**Issue by dariusgm** [rstudio/rstudio#13046]
### System details

    RStudio Edition : Desktop 
    RStudio Version :  2023.03.0-386-x86_64
    OS Version      :  Red Hat Enterprise Linux 7
    R Version       :  3.6.0

### Steps to reproduce the problem
Using a CRAN Proxy in a company network, that is a mirror for the official repositories.

### Describe the problem in detail
When installing packages via R, the credentials are shown in the console output, what can potencial leak sensitive data, for example in screen sharing sessions.

### Describe the behavior you expected
I expect the credentials to not be visable to the user. At least the password may be dotted out. (user:***@example.com)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

I am not a R developer and have no knowledge about R (only other languages).

I am only passing this bug request here. When this is related to R itself, than please redirect me to the correct repository where to put this bug.

**Comment by ronblum** [comment]
@dariusgm Thank you for raising this! Does this only happen when running in RStudio, or does it happen with R outside of RStudio?

**Comment by dariusgm** [comment]
Thank you @ronblum for the fast response. This also happens when I run R directly from the command line and try to install tidyr.

The credentials are passed via environment variables to `~/.Rprofile` with the following content (removed company sensitive information)


```
local({
  r <- list("cran" = paste("https://",Sys.getenv("USER_NAME"),":",Sys.getenv("TOKEN"),"@example.com", sep=""))
  options(repos = r)
})
```

**Comment by ronblum** [comment]
Thanks for checking @dariusgm! Since this is an issue in base R, and this repo is specifically for RStudio, there are a few things I would suggest:
1. Search for and post an issue in one of the user groups, to see if anyone has tried suppressing this information:
* [RStudio Community](https://community.rstudio.com/)
* [Stack Overflow](https://stackoverflow.com/questions/tagged/r)
2. File a bug report with the R project. You might have to create an account for this: https://www.r-project.org/bugs.html

**Comment by kevinushey** [comment]
Rather than encoding the username + password in the URL itself, I'd recommend including them as part of the headers in your web requests to that CRAN server. You could do this with something like:

```
options(download.file.method = "curl")
```

and then use a `.curlrc` file to include the appropriate headers in any requests made. See e.g. https://everything.curl.dev/cmdline/configfile.
