### ISSUE TITLE
Opening pdf vignette opens empty page in browser 

### ISSUE THREAD

**Issue by therealgenna** [rstudio/rstudio#13041]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.03.0+386 (2023.03.0+386)
    OS Version      : Mac OS 11.7.2 
    R Version       : 4.2.2

### Steps to reproduce the problem
Trying to open pdf vignette for package lme4 just opens an empty page in the browser at the address:
http://127.0.0.1:33297/help/library/lme4/doc/Theory.pdf

The file exists and can be opened in Acrobat and in that same browser (safari) just fine from its location:
/Library/Frameworks/R.framework/Versions/4.2/Resources/library/lme4/doc/Theory.pdf

This seems to be similar to the issue described, but not resolved, at 
https://community.rstudio.com/t/access-to-127-0-0-1-was-denied-when-trying-to-to-open-pdf-vignette/159189/9

### Describe the problem in detail
That's not specific to this pdf - it seems to be the same for all other pdfs, for example I also see empty page for:
http://127.0.0.1:33297/help/library/limma/doc/intro.pdf
(as above, the file exists and can be opened externally)

### Describe the behavior you expected

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@therealgenna Thank you for raising this! We'll review this as we continue development of RStudio.

I can reproduce this in 
- RStudio Desktop 2022.12.0+353 on MacOS 13.4
- RStudio Desktop 2023.05.0-daily+275 on MacOS 13.4
This works in
- RStudio Desktop 2022.07.2+576 on MacOS 13.4
- RStudio Server 2023.05.0-daily+275 on Ubuntu 20.04.5 via Chrome on MacOS 13.4

**Comment by aphalo** [comment]
I still see the problem in 2023.06.2 under Windows 10. Just in case it helps `vignette()` used at the R console opens the PDF vignettes in the PDF viewer set at default in Windows. Setting the same viewer in Firefox as PDF viewer still results in an empty browser tab.

**Comment by clayford** [comment]
I still see this problem in RStudio 2023.09.0+463 on Windows 10.

**Comment by aphalo** [comment]
Yes, I can confirm that I noticed the same. It is a significant problem when using RStudio in teaching to R newbies.

**Comment by LeonBarmuta** [comment]
I have the same problem under Windows 10 with RStudio 2023.09.0+463 "Desert Sunflower" Release (b51c81cc303d4b52b010767e5b30438beb904641, 2023-09-25) for windows.

RStudio Edition : Desktop
OS Version      : Windows 10 Enterprise version 10.0.19045 Build 19045
R Version       : 4.3.1

If it helps, Sys.getenv("R_PDFVIEWER") returns "" if that helps, but (for example) vignette("Theory") for package lme4 does open a pdf in a browser page.

**Comment by ronblum** [comment]
This is now resolved in 2023.12.0 Ocean Storm, currently in development. The fix is available in [the daily builds](https://dailies.rstudio.com/rstudio/ocean-storm/). Please note that this has been only checked in RStudio Desktop on MacOS, and that these builds are meant for testing and development purposes only, not production.

Verified so far in RStudio Desktop 2023.12.0-daily+165 on MacOS 14. TBD: other OSes and RStudio Server.

**Comment by ronblum** [comment]
This is only partially working in RStudio Desktop 2023.12.0-daily+201 on Windows and Linux

Works on both
- Clicking on "Show in new window" and then on the Vignette PDF link will show the PDF in the RStudio viewer.

Windows 11
- Only works if an external viewer like Adodbe Acrobat is installed. Otherwise, nothing happens.

Red Hat 9.2
- Nothing happens except for `sh: line 1: : command not found` in the Console Pane.

**Comment by ronblum** [comment]
Fixed as is.
