### ISSUE TITLE
Add the option to decide if we want the assign operator (<-) to be replaced with an arrow

### ISSUE THREAD

**Issue by cornejocastellano** [rstudio/rstudio#13153]
I find it very annoying that since the last version, the assign operator (<-) is visually replaced by an arrow to the left (←) . It does not add anything of value. How can this be changed? In any case, an option would need to be added to let the user decide such visual aspects.

**Comment by kevinushey** [comment]
What font are you using? Most likely, you've configured RStudio to use a font that includes ligatures -- switching to a different font is one solution.

Unfortunately, as far as I can see, we don't provide a way to disable ligatures when using a font that has ligatures, so that would be worth investigating.

**Comment by cornejocastellano** [comment]
My bad, that was the cause. I changed fonts and it was corrected. Thank you
