### ISSUE TITLE
Missing option in rstudio for .qmd files

### ISSUE THREAD

**Issue by jardel20** [rstudio/rstudio#13197]
### System details

    RStudio Edition : 
    RStudio Version : 2023.03.1 Build 446
    OS Version      :  Fedora release 38 (Thirty Eight)
    R Version       :  4.3.0 (2023-04-21)

### Steps to reproduce the problem
file > new file --> does not show qmd options.

### Describe the problem in detail
There is no option for .qmd files in my Rstudio.

### Describe the behavior you expected
Should appear options to create files to run with Quarto. (https://quarto.org/)

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@jardel20 Thank you for raising this! This is due to an incompatibility between Quarto's dependencies and Fedora's packaging guidelines. You can follow this in issue #12609. However, if you [download Quarto directly from quarto.org](https://quarto.org/docs/download/), and if you install it so that it's in the path, the Quarto options should be there.

**Comment by Enchufa2** [comment]
Sorry, @ronblum, but the point of #12609 is that, if RStudio is built with Quarto disabled, then the options are not there if you install Quarto yourself, right?
