### ISSUE TITLE
Better highlighting of the "find in topic" search results

### ISSUE THREAD

**Issue by stla** [rstudio/rstudio#13204]
Hello,

My favorite RStudio theme is the cobalt theme. But when I do a search in a package help page with "Find in topic", it is really hard to see the highlighted result.

For example here I search "proj", do you see the highlighted result? It would be better in yellow for example.

![Capture du 2023-06-06 14-03-56](https://github.com/rstudio/rstudio/assets/4466543/382d76ed-7aa5-4eb2-9e3e-29568903c0d1)

**Comment by ronblum** [comment]
@stla Thank you for raising this! I agree that it's hard to read in dark themes, while it's reasonable in light themes. We'll review this as we continue development of RStudio.

**Comment by etiennebacher** [comment]
Could you reopen this? The current highlighting is very hard to see

**Comment by asadow** [comment]
Looking forward to this. With the Twilight theme, it may as well be impossible to see the highlighting.

**Comment by etiennebacher** [comment]
Sorry for another +1 on this, but from the outside it seems like a very simple change that would make the search in docs so much easier. Currently I really have to scan the docs carefully to see where the highlighted part is, which defeats the purpose of the highlight function in the first place.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.07.0-daily+303 on Windows 11. Here's an example with the Dracula dark theme.

![Image](https://github.com/rstudio/rstudio/assets/31009952/74c09076-f848-415c-b7fb-ac603bb82c02)

**Comment by etiennebacher** [comment]
Thank you @kevinushey !

**Comment by frankgibbons** [comment]
Was this ever completed? Seems like such a simple ask, and such a high need (if 'find' doesn't help you find what you're looking for, then it's kind of a broken feature, albeit not due to the core functionality. 

Unfortunately, I'm a corporate environment, without control over which version I can install, so only have R 4.3.1. If this were easily updatable by editing a config, I could do that, but all the config files seem locked in mine (I've tried copying and modifying, but it tells me I don't have permission to save in that directory).

If anyone comes here, in a similar situation to mine, it might be useful to know that Merbivore (which I generally use, and where the search text highlighting is basically non-existent) is fairly similar to 'Vibrant Ink' (which seems "new" to me, and actually has search highlighting you can see). I'd love to be able to tweak them somewhat - I don't find the purple-on-black for comments to be all that legible, and the "hulk-green" color for string literals is a bit glaring (and 70's), but overall it's workable (and you can FIND things)

**Comment by ronblum** [comment]
@frankgibbons The work was completed, hence the "verified" post at https://github.com/rstudio/rstudio/issues/13204#issuecomment-2217453384. Are you seeing that there's a regression and this isn't working again?

**Comment by kevinushey** [comment]
To confirm, here's how things look for me with RStudio 2024.12.1, using the Merbivore theme.

<img width="425" alt="Image" src="https://github.com/user-attachments/assets/6659789d-37a6-4457-808c-ec00369d228a" />

**Comment by frankgibbons** [comment]
Thanks Kevin.

I'm in a corporate environment, so no control over what version I have access to, and I'm still living in 2023. Glad to hear that it's fixed (at least I can use it at home 😉). No regression to report.

________________________________
