### ISSUE TITLE
documentation cross-reference links open external browser against 127.0.0.1

### ISSUE THREAD

**Issue by aronatkins** [rstudio/rstudio#13392]
### System details

    RStudio Edition : desktop
    RStudio Version : 2023.09.0-daily+235
    OS Version      : macOS Monterey 12.6.7
    R Version       : 4.3.1

### Steps to reproduce the problem

1. Open the help for some function from the R console:

    ```r
    ?tidyr::separate_rows
    ```

2. Within the Help pane, click on a link to some other referenced function. In my case, the help for `tidyr::separate_rows` links to `separate_longer_delim()`.
3. An external browser window is opened, visiting `http://127.0.0.1:38251/help/library/tidyr/html/separate_longer_delim.html`, which is a blank page (JS console shows HTTP 403 Forbidden).

### Describe the problem in detail

Help links are not kept within the help pane.

### Describe the behavior you expected

Help links are kept within the help pane.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Note: This is a regression, as it works correctly in RStudio Desktop 2023.06.1+524.

**Comment by timtmok** [comment]
This was caused by trying to fix #13329. The code demo should display in the user's browser but this navigation in the help is also causing a redirect. I'm not sure of a safe enough fix at the moment. I don't want any changes to also break this other use case in #12256.

The `will-frame-navigate` event that is now available won't help here. Electron can already listen on enough events to get an idea that an iframe is navigating and check if it's acceptable. The problem is some use cases, such as restarting R, cause navigation events to incorrect URLs. The difficulty is trying to determine which `localhost` url is supposed to be opened in the IDE and which should be sent to the user's browser.

**Comment by kevinushey** [comment]
I tried to take a closer look, and I think the underlying issue here is that we're no longer injecting our Help JS / CSS into the page after navigating to a demo page. Note that navigating Back / Forward with the buttons does not work, but navigating using back + forward mouse buttons in fact does.

My vote would be to:

1. Roll back the PR in https://github.com/rstudio/rstudio/pull/13329,
2. Figure out why we're losing our injected JS / CSS in that specific context.

I'll try to dig in a bit more for (2).

**Comment by kevinushey** [comment]
I added some debugging, and the problem here is that the R help server is returning a redirect to a separate port + location. That is:

```
/help/library/stats/demo (:29)
$payload
[1] "Redirect to <a href=\"http://127.0.0.1:21942/doc/html/Search?package=stats&agrep=0&types.demo=1&pattern=\">help.search()</a>"

$`content-type`
[1] "text/html"

$header
[1] "Location: http://127.0.0.1:21942/doc/html/Search?package=stats&agrep=0&types.demo=1&pattern="

$`status code`
[1] 302
```

However, we try to rig things so that the Help server is navigated from a local HTTP proxy; that is, the iframe has:

<img width="522" alt="Screenshot 2023-08-24 at 2 50 50 PM" src="https://github.com/rstudio/rstudio/assets/1976582/c56cd9d9-10cf-49df-aeef-77ba3375b537">

Even though the "real" R help server is running on this port:

```
> tools:::httpdPort()
[1] 21942
```

To wit, to resolve this, I think we need to tweak how we handle local redirects from R. That would need to happen somewhere around here:

https://github.com/rstudio/rstudio/blob/8bc6388537b67e1eb46bc4d40ca44783d71061f1/src/cpp/session/modules/SessionHelp.cpp#L468-L475

In particular, we would need to rewrite the Location header on redirects, and ensure that any attempts to navigate to the R help server would instead go to our proxy.

**Comment by jonvanausdeln** [comment]
Verified with [2023.09.0-daily+401](https://dailies.rstudio.com/version/2023.09.0-daily+401)
Windows11, MacOS 12.6, Ubuntu22 (OS Server)

No longer open in external browser, also re-checked https://github.com/rstudio/rstudio/issues/13263
