### ISSUE TITLE
New updates no longer support for ubuntu 18 ?

### ISSUE THREAD

**Issue by realzehuali** [rstudio/rstudio#13409]
New update of 2023.6.1-524.deb rstudio desktop could not be found for ubuntu 18.

**Comment by ronblum** [comment]
@realzehuali That's correct, because Ubuntu 18 is no longer supported for RStudio. Ubuntu [dropped maintenance updates under standard support for Ubuntu 18](https://ubuntu.com//blog/18-04-end-of-standard-support) on May 31, 2023. We only support Ubuntu as long as it provides maintenance updates (see [FAQ 1 at the Posit Platform Support page](https://posit.co/about/platform-support/)).
