### ISSUE TITLE
Copilot agent running and no suggestions are provided on server

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#13445]
### System details

    RStudio Edition : Server
    RStudio Version : 2023.09.0-daily+290
    OS Version      : Ubuntu 20.04.5
    R Version       : 4.2.2

### Steps to reproduce the problem

1. Enable Copilot and install the agent.
2. Open an R file and try to get Copilot suggestions.

### Describe the problem in detail

On RStudio Server, the Copilot agent isn't running, and no suggestions are provided, although the message in the source editor states, "Waiting for completions." This is even after disabling and re-enabling Copilot, logging out and back in, and restarting RStudio.

<img width="313" alt="copilot_agent" src="https://github.com/rstudio/rstudio/assets/31009952/3d907228-f7b8-40e5-991e-b7fcccbfbd77">

<img width="283" alt="no_suggestions" src="https://github.com/rstudio/rstudio/assets/31009952/06ad131d-ecd8-450b-9033-6d3c0f15fa7a">

### Describe the behavior you expected

The agent should run and end up with Copilot suggestions.

See also [this Community post](https://community.rstudio.com/t/copilot-say-installed-successfuly-but-does-not-work/170941).

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
It works for me:

<img width="323" alt="Screenshot 2023-08-10 at 9 31 47 AM" src="https://github.com/rstudio/rstudio/assets/1976582/4441b387-96c0-41ec-adc6-916f603ddc2a">

Presumedly you're not seeing completions because you don't have `node` installed? We still need to ensure that is bundled with RStudio Server for Copilot support.

**Comment by ronblum** [comment]
@kevinushey Yes, I'm pretty sure I didn't have node installed. I'll check if #13232 takes care of that.

**Comment by ronblum** [comment]
Verified in RStudio Server 2023.09.0-daily+337 on Ubuntu 20 via Chrome on MacOS 14.0.

**Comment by CorradoLanera** [comment]
Same on rstudio desktop pro  2023.09.0 Build 463.pro11

**Comment by ronblum** [comment]
@CorradoLanera Does <kbd>Global Options -> Copilot</kbd> state that the agent isn't running? Or is it running, but no suggestions are provided? Also, what OS type and version are you using, and which version of R?

**Comment by CorradoLanera** [comment]
hi @ronblum , I have answered in the opening isse https://github.com/rstudio/rstudio/issues/13732#issuecomment-1747441341

Rstudio desktop pro (updated)
win

just tried to switch on bun nothing never happened (I think the issue is that the agent was not installed... was that my duty and supposed knowledge? I have tried to find info on gh but cannot find an agent for rstudio nor "general" for windows...)

**Comment by ronblum** [comment]
@CorradoLanera Nope, you shouldn't need any specialized knowledge. I'll switch over to the other issue #13732.
