### ISSUE TITLE
In Quarto/RMD SQL code chunks, don't format R # comments as comments

### ISSUE THREAD

**Issue by carlganz** [rstudio/rstudio#13453]
<img width="964" alt="Screenshot 2023-08-03 at 12 06 54 PM" src="https://github.com/rstudio/rstudio/assets/11653794/f9b0c0db-a288-46e6-b44e-39d3dadc92be">

It is an easy mistake to make with the current UX, and the error messages are not intuitive for new users, so I think this would be a major improvement to not format R notes in SQL chunks

**Comment by kevinushey** [comment]
The problem here is that different SQL engines support different comment syntaxes. All of them support `--` comments, but some (e.g. MySQL) support `#` comments.

I suppose we could choose to only support `--` comments but then the MySQL users will be upset... so we'd have to put it behind a toggle or option of some kind.
