### ISSUE TITLE
Clipboard integration in Copilot context

### ISSUE THREAD

**Issue by DavidBlairs** [rstudio/rstudio#13483]
Hello there! 

I've been using the Copilot integration in the latest indev build of R Studio quite a lot recently and I had a thought on how to guide the code generation. I believe that right now, open files are considered when providing context to the Copilot API. A quick improvement to this may be adding the clipboard text to the context as well. When I'm building R Shiny apps, I often want to add a widget that looks quite similar to another widget but needs to be personalised to the localised scope of the module I'm working in and with a slightly different name and style. I feel that adding the clipboard to the context will "nudge" Copilot into this and get to what I want quicker.

**Comment by ronblum** [comment]
@DavidBlairs Thank you for the suggestion! We've decided not to implement this due to security and privacy considerations, which was also raised in this brief discussion: https://github.com/orgs/community/discussions/43371#discussioncomment-6276572

Do you know of any software that shares information from the clipboard to Copilot, as a comparison point? Thanks!
