### ISSUE TITLE
quarto revealjs: presentation vs. viewer pane

### ISSUE THREAD

**Issue by tchevri** [rstudio/rstudio#13606]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.06.2 Build 561, specifically: RStudio 2023.06.2+561 "Mountain Hydrangea" Release (de44a3118f7963972e24a78b7a1ad48b4be8a217, 2023-08-25) for windows Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2023.06.2+561 Chrome/110.0.5481.208 Electron/23.3.0 Safari/537.36  
    OS Version      : Edition Windows 11 Home Version 23H2 Installed on ‎5/‎16/‎2022 OS build	22631.2265 Experience	Windows Feature Experience Pack 1000.22674.1000.0
    R Version       : R version 4.3.1 (2023-06-16 ucrt) -- "Beagle Scouts"

### Steps to reproduce the problem

New file -> quarto presentation, just the default presentation works fine.

### Describe the problem in detail

When I render the default `revealjs` presentatoin template, my document is rendered in the presentation pane of the viewer output. That's the desired behavior. If I use a different `revealjs` template, specifically, in the `YAML`, I replace:
`format: revealjs`  
with  
`format: metropolis-revealjs`, then the document is no longer rendered in the presentation pane, but is now rendered in the viewer pain (oops, typo, I meant "pane", sorry). Since this is still a `revealjs` presentation, it seems this behavior is inconsistent with the desired goal, correct? please, note [I also posted this issue here](https://community.rstudio.com/t/viewer-vs-presentation-output-pane-is-it-possible-to-control-where-the-document-is-being-rendered/173090?u=tchevri).

### Describe the behavior you expected

I would expect that my document is rendered in the presentation pane. Talking of which, is there a way to control where the document is rendered, that is in which output pane?

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@tchevri Thank you for the suggestion! We'll review it as we continue development of RStudio and Quarto.

**Comment by BorgeJorge** [comment]
I was having the same problem with the [metropolis theme for revealjs](https://github.com/shafayetShafee/metropolis) (as well as with other themes, like [clean](https://github.com/grantmcdermott/quarto-revealjs-clean)). The workaround I found was to copy the metropolis.scss file from the Quarto project's _extensions subdirectory to the subdirectory where Quarto installs its standard revealjs themes (which is normally C:\users\[USERNAME]\AppData\Local\Programs\Quarto\share\formats\revealjs\themes\).

Then you also have to change the document's YAML, from:
```
format: metropolis-revealjs
```
to:
```
format:
  revealjs:
    theme: metropolis
```
For me this was a crucial find, since I think the only way to create a properly formatted pdf version of a revealjs presentation is to use the Print button in the Presentation pane. (Other methods don't align slides with page breaks.)
