### ISSUE TITLE
publishing attempts to use an empty directory, causing linting and publishing errors

### ISSUE THREAD

**Issue by aronatkins** [rstudio/rstudio#13637]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.09.0-daily+384
    OS Version      : macOS Ventura 13.5.2
    R Version       : 4.3.1

### Steps to reproduce the problem

Create a Quarto project with the following structure:

```
_quarto.yml
index.qmd
project.Rproj
materials/project/05_connectwidgets/project_curation.qmd
```

The contents of the two `*.qmd` does not matter.

The content of `_quarto.yml` must be:

```yaml
project:
  type: website
  render:
    - "index.qmd"
```

In the IDE, open the `project_curation.qmd` file and then click the publishing button. Target some Connect server.

### Describe the problem in detail

When attempting to publish, the pre-flight lint check errs:

<img width="264" alt="image" src="https://github.com/rstudio/rstudio/assets/362187/53a89d52-1ffb-4732-966c-fc633f8c996c">

This error is because the lint workflow is passed an empty target string:

https://github.com/rstudio/rstudio/blob/main/src/cpp/session/modules/SessionRSConnect.R#L246-L273

If you try to "Publish Anyway", you receive an error in the Deploy pane:

```
Error in `check_file()`:
! `x` must be a single string, not the empty string "".
Backtrace:
    ▆
 1. └─rsconnect::deployApp(...)
 2.   └─rsconnect:::check_directory(appDir)
 3.     └─rsconnect:::check_file(x = x)
 4.       └─rsconnect:::check_string(...)
 5.         └─rsconnect:::stop_input_type(...)
 6.           └─rlang::abort(message, ..., call = call, arg = arg)
Execution halted
```

This second error is because `deployApp()` is passed an empty string for `appDir`, which is also the reason that the linting failed.

### Describe the behavior you expected

Linting passed and deployment succeeded.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
QA note: This can be reproduced using the `about.qmd` file in a default Quarto Website project, but the `_quarto.yml` must be edited as described above.

**Comment by kevinushey** [comment]
If I understand correctly, the issue here is that Quarto doesn't think this file is part of the project, and doesn't return any project-related metadata. In particular:

```
$ quarto inspect materials/project/project_curation.qmd
{
  "quarto": {
    "version": "1.4.330"
  },
  <...>
}
```

This returns a bunch of metadata about the document, but not about the project itself. Contrast that with the top-level index file:

```
$ quarto inspect index.qmd
{
  "quarto": {
    "version": "1.4.330"
  },
  < ... >,
  "project": {
    "quarto": {
      "version": "1.4.330"
    },
    "dir": "/Users/kevin/scratch/example",
    "engines": [
      "markdown"
    ],
    "config": {
      "project": {
        "type": "website",
        "render": [
          "index.qmd"
        ],
        "lib-dir": "site_libs",
        "output-dir": "_site"
      },
      "language": {},
      "format": {
        "html": "default"
      },
      "website": {}
    },
    "files": {
      "input": [
        "/Users/kevin/scratch/example/index.qmd"
      ],
      "resources": [],
      "config": [
        "/Users/kevin/scratch/example/_quarto.yml"
      ],
      "configResources": []
    }
  }
```

I'm not exactly sure what the right solution here is, though:

1. Assert that this is user error; they need to declare the file's relationship to the project in `_quarto.yml`?
2. Use some other heuristics to guess the website directory?
3. [Run away from home and live in the woods](https://www.wikihow.com/Run-Away-from-Home-and-Live-in-the-Woods)?

**Comment by kevinushey** [comment]
For reference: https://github.com/rstudio/rstudio/blob/4991540dda167d5d07980351dcf8df6d20ea016b/src/cpp/session/modules/quarto/SessionQuarto.cpp#L540-L574

**Comment by aronatkins** [comment]
I'm all for living in less populated areas.

The example is trying to publish a standalone Quarto that is located within a Quarto project hierarchy. Standalone Quarto documents (not in a project) are fine, but it sounds like the problem comes when you drop that standalone document into a project.

The original error occurred when folks were trying to distribute a single repository containing a top-level Quarto project (website) along with some standalone Quarto documents to demonstrate different concepts.

@kmasiello could probably better describe what they were trying to accomplish. I'm not sure what would be the best hierarchy.

**Comment by kmasiello** [comment]
The case here was this repository was for a workshop. The standalone Quarto documents were activities (examples) for participants to work with and publish. But then we stood up a website front for the repository to publish slides and overall navigation instructions for the repo.  

I think this would come up frequently in the wild as quarto is being used for courses and teaching purposes.

**Comment by jgutman** [comment]
@kevinushey The existing `quartoProjectConfigFile` function already seems to be successful at finding the `_quarto.yml` in these cases -- I think we can just remove the check that looks for the project metadata from the inspect output? If we remove that check, we're still able to successfully locate `_quarto.yml` file, and since this is a permitted workflow, is there any reason to keep it around? We only use the data we get from `_quarto.yml`, not from `quarto inspect`, so everything kind of works as desired if we just remove the `if` clause. PR incoming -- any reason this is a bad idea though?

**Comment by jonvanausdeln** [comment]
Verified with [2023.12.0-daily+234](https://dailies.rstudio.com/version/2023.12.0-daily+234)
Windows 11

Projects publish as expected.
