### ISSUE TITLE
Visual editor omits chunks contents with certain class names (e.g., `note`)

### ISSUE THREAD

**Issue by adisarid** [rstudio/rstudio#13663]
### System details

    RStudio Edition : Desktop (but reproduces in Server as well)
    RStudio Version : 2023.06.1 Build 524
    OS Version      :  Windows 11
    R Version       :  4.2.0

### Steps to reproduce the problem

Create a quarto document:

```
---
title: "bug reprex"
format: html
editor: visual
---

::: note
some random text
:::
```

Save the file and switch between Source and Visual viewer modes.
Text inside the note div does not appear in Visual viewer mode.

### Describe the problem in detail

After saving the file, switch between Source and Visual modes. The source shows:
![image](https://github.com/rstudio/rstudio/assets/19262838/83d8aff4-370a-4e94-acb4-fafc0d996b27)

But Visual mode shows
![image](https://github.com/rstudio/rstudio/assets/19262838/31f32ad5-6277-4c28-a043-ac2bd9362896)

I.e., whatever is within that class does not appear when Visual Viewer is used.

I first encountered this problem using class names such as `note` to create customized chunks. At the time, I wasn't aware of the callouts feature, which is somewhat equivalent to what I was trying to accomplish and provides a reasonable workaround.

However, I believe it is worth while to identify the extent of the problem (which class names create the issue other than "note"), and either fix it or provide some other kind of notification.

### Describe the behavior you expected

The chunk class "note" text should appear in the Visual viewer viewing mode.

**Comment by kevinushey** [comment]
Interestingly, the text does exist in the document, it's just not visible, and this is seemingly intentional.

<img width="670" alt="Screenshot 2023-09-20 at 9 23 56 AM" src="https://github.com/rstudio/rstudio/assets/1976582/cb5b6fbc-26fd-4cce-8181-2358a5f0957b">

<img width="197" alt="Screenshot 2023-09-20 at 9 24 37 AM" src="https://github.com/rstudio/rstudio/assets/1976582/da08866c-bf3f-4f52-be33-2850c8121f1f">
