### ISSUE TITLE
Fatal error occurs when load cmdstanr library!

### ISSUE THREAD

**Issue by williamlorder** [rstudio/rstudio#13769]
### System details

    RStudio Edition : 
    RStudio Version : 2023.12.0-daily+134 (2023.12.0-daily+134)
    Platform: aarch64-apple-darwin20 (64-bit)
    OS Version      :macOS 14.0 
    R Version      : R version 4.2.0 (2022-04-22)

### Steps to reproduce the problem
```r
library(cmdstanr)
```
the Rstudio Crashed when loading cmdstanr, albeit it works fine when in the R terminal(R console).
<img width="1440" alt="截屏2023-10-07 20 29 52" src="https://github.com/rstudio/rstudio/assets/83387569/b9df730e-0ec5-47ba-9068-c3ab7712b75f">

### Describe the problem in detail
the Rstudio Crashed when loading cmdstanr, albeit it works fine when in the R terminal(R console).

<img width="1440" alt="截屏2023-10-07 20 29 52" src="https://github.com/rstudio/rstudio/assets/83387569/b9df730e-0ec5-47ba-9068-c3ab7712b75f">
### Describe the behavior you expected

work properly.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@williamlorder Thank you for raising this—I can't reproduce the issue in the same environment. Did this work correctly previously in
- An earlier version of RStudio (2023.09.0 or earlier)
- An earlier version of MacOS (13 or earlier)

**Comment by eipi10** [comment]
@ronblum I'm having this issue as well on my Macbook Pro M2, Sonoma 14.1.1, RStudio 2023.09.1+494, R 4.3.2, and `cmdstanr` 0.6.x or 0.7.0 (which was just released today). Running `library(cmdstanr)` or`cmdstanr::[any function]` causes an "R Session Aborted" message. `cmdstanr` works as expected when directly using the built-in R console, so it seems to be related to RStudio specifically. 

Everything works fine after rolling back to RStudio 2023.06.2+561, which appears to be the most recent version that doesn't result in R crashing.

This issue was also reported a couple of months ago on the [Stan discourse](https://discourse.mc-stan.org/t/using-cmdstanr-crashing-rstudio/33081/5) and [github](https://github.com/stan-dev/cmdstanr/issues/868) sites.

**Comment by eipi10** [comment]
This is weird: To do some more testing I reinstalled RStudio 2023.09.1+494 and now I'm not getting any crashes with `cmdstanr`. I first started getting these crashes last week so it was reproducible on at least a few occasions. But today is the first time I rolled back to an earlier RStudio version and then rolled forward to the latest version. Let me know if there are any other tests I should run that would help diagnose what's going on.

**Comment by marcdotson** [comment]
I'm not sure what's changed, but I no longer get fatal errors when loading cmdstanr or using it to compile and sample.

- RStudio Version 2023.12.0+369
- CmdStan version: 2.33.1
- cmdstanr version 0.7.1
- MacBook Pro M2 Pro
- macOS Sonoma 14.2.1

**Comment by eipi10** [comment]
`cmdstanr` is also working fine for me with RStudio Version 2023.12.0+369.
