### ISSUE TITLE
YAML chunk option syntax highlighting applies different highlighting to numbers and special words

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [rstudio/rstudio#13836]
In 2023.12.0-daily+221, create a new Quarto document with the following contents:

````markdown
---
format: html
---

```{r}
#| label: fig-plot-no-1
#| fig-cap: A caption
#| fig-subcap:
#|   - Caption for Plot 1
#|   - Caption for Plot 2
#| layout-ncol: 2

plot(cars, main = "Plot 1")
plot(cars, col = "red", main = "Plot 2")
```
````

All text should be the same color but special words like "no" and numbers are highlighted differently:

<img width="712" alt="Screenshot 2023-10-24 at 7 42 12 AM" src="https://github.com/rstudio/rstudio/assets/5965649/c66b6a67-87b1-44a8-85ef-ef8a52e9251e">

**Comment by jgutman** [comment]
For clarification on the desired behavior: no is highlighted because it is interpreted as a possible boolean value (same for true, TRUE, yes etc). However, when it appears as part of a longer string/expression, clearly in that context it is not intended as a boolean. Would you expect that words like no never get highlighted, or that they get highlighted if and only if that is the full value of the chunk option (e.g. `echo: no`) but not when appearing as part of a larger expression? To me I think we want the latter, but checking in what you think here. Same thing for numbers, i.e. layout-ncol: 2 the 2 should be highlighted, but in the fig-subcap example it should not?

**Comment by mine-cetinkaya-rundel** [comment]
Agreed, I think when words are numbers are valid YAML values they should be highlighted. If appearing within a text string they should not be.

**Comment by jgutman** [comment]
This probably needs to be changed here:
https://github.com/rstudio/rstudio/blob/6405c6ecd83217409d7fb153474284c8106eed8b/src/gwt/acesupport/acemode/yaml_highlight_rules.js#L94-L101

Note that in these 3 regexes, Ace doesn't check for the beginning and end of the entire expression (e.g. `^` and `$`). We probably want to add this

**Comment by olivroy** [comment]
I think I found a little problem.

If we use `|>` (hence a trailing `>` on the first line), the parser has difficulty to highlight the code. Note that this is minor, and easy to work around. Just thought I'd let you know what I see on RStudio 2023.12.0+283 (I don't know if #13951 fixed that)


The problem is the first chunk in visual mode:
![image](https://github.com/rstudio/rstudio/assets/52606734/9768664e-918d-4b36-8a5e-9d6c40bde73d)

also, when I press Enter after `mtcars |>` , the cursor doesn't indent correctly, I suspect a parsing issue.

1. Can work around by using another yaml tag after, skipping a line,

**Comment by kevinushey** [comment]
Thanks! The problem here is that the highlighter thinks we're still in YAML mode, even without the comment prefix:

<img width="255" alt="Screenshot 2023-11-27 at 10 53 05 AM" src="https://github.com/rstudio/rstudio/assets/1976582/e53eb050-8ca1-496a-8a05-302b6ddcab30">

This should be an easy fix; I'll take a look.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.04.0-daily+426 on MacOS 14.3 that the special words and numbers are no longer highlighted if they're part of longer expressions, with one exception: If they appear at the start. For example, `Caption TRUE` is the correct color, but `TRUE` has the color of a special word in `TRUE-caption`.


![Image](https://github.com/rstudio/rstudio/assets/31009952/772cc008-1c75-46f6-92db-e64752b31956)

![Image](https://github.com/rstudio/rstudio/assets/31009952/a495818a-798d-4c56-8f80-fc45cfc85394)


(The label and values I added don't match—I was just picking random labels.)

**Comment by kevinushey** [comment]
@ronblum thanks for catching that! I'll see if I can tidy that up.

**Comment by ronblum** [comment]
Almost there! One last bit: The `2` at the start of `2 + 2` is still highlighted.

![Image](https://github.com/rstudio/rstudio/assets/31009952/bc28ae39-03b2-4200-be15-015573cf58d1)

Including the code that I added:

````
---
format: html
---

```{r}
#| label: fig-plot-no-1
#| classes: fig plot no 1
#| cache: no
#| cache-vars: no fig plot 1
#| fig-cap: A caption
#| fig-subcap:
#|   - Caption for Plot 1
#|   - Caption for Plot 2
#|   - Caption TRUE
#|   - TRUE
#|   - TRUE caption
#|   - TRUE-caption
#| layout-ncol: 2
#| layout-nrow: 2 + 2

plot(cars, main = "Plot 1")
plot(cars, col = "red", main = "Plot 2")
```
````

**Comment by kevinushey** [comment]
Should be looking good in the next builds:

<img width="267" alt="Screenshot 2024-02-28 at 2 29 01 PM" src="https://github.com/rstudio/rstudio/assets/1976582/ad635b01-6c1e-437d-88b3-edbce79d60fa">

**Comment by ronblum** [comment]
Verified in 
- RStudio Desktop 2024.4.0.573 on MacOS 14.4
- RStudio Server 2024.4.0.573 on Ubuntu 22.04 via Chrome on MacOS 14.4

Confirmed with [the code above](https://github.com/rstudio/rstudio/issues/13836#issuecomment-1942106383):
![Image](https://github.com/rstudio/rstudio/assets/31009952/8c610447-bb0b-48c0-a4b8-01ab50883bfe)
