### ISSUE TITLE
browser() statement opens read only view on execution unless entire function or file is sourced

### ISSUE THREAD

**Issue by jthomasmock** [rstudio/rstudio#13925]
### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 2023.12.0.278
    OS Version      : macOS 13.6
    R Version       : R version 4.2.0 (2022-04-22)

### Steps to reproduce the problem

Any user-defined functions that aren't Sourced will open up a read-only Source Window.

Use the following code in a .R file named `single-fn.R` and highlight the entire script and Cmd+Enter or click on "Run".

```r
get_index <- function(currIndex){
  print(currIndex)

  browser()
}

get_index(5)
```

![image](https://github.com/rstudio/rstudio/assets/29187501/f8dc8c2e-cbb8-49ca-be40-2c8c78f78b93)

Alternatively, create a second .R file named `debug-index.R` and also try running it with Cmd+Enter or via "Run". Each time you step through the function it will open/return to the read-only view.

```r
get_index <- function(currIndex){
  print(currIndex)

  browser()
}


lapply(
  X = 1:10,
  FUN = get_index
)
```

### Describe the problem in detail

Per the docs:

> If RStudio can’t find a .R file that matches the function, it will show the code in the Source Viewer. This can happen either because no .R file exists or because the function object doesn’t match the definition in the .R file.

Even if the code for the function hasn't changed AND the source is available it is still opening a read-only view. 

Overall I don't think we NEED to open a read-only view unless the function comes from a malformed package or some other location where the source code is not retrievable, unlike the interactive workflow of a local file.

I have seen a few issues that #6740 #9943 and have split off this topic from: #12505 . There's a lot of chatter on a few issues and some emails.

### Describe the behavior you expected

If I `source()` or use the Source button in RStudio, it will keep focus on the sourced open file. I believe that this behavior should be present unless we truly find an externally defined function that the user cannot access. I think this is a regression because the source IS available and at worst, it should return focus to the file where the function exists. As a potential mitigation, perhaps we could allow users to turn off the "read only view".

I think the source for this is: https://github.com/rstudio/rstudio/blob/68a2b9bc237675e62b190891f1008f7e32361941/src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/codebrowser/CodeBrowserEditingTarget.java#L760-L772

And perhaps we want to follow a heuristic that if the user closes the "Warning bar for approximate location" we should also not open the readonly view?

https://github.com/rstudio/rstudio/blob/68a2b9bc237675e62b190891f1008f7e32361941/src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/codebrowser/CodeBrowserEditingTarget.java#L224-L226

### Describe the behavior you expected

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by vertesy** [comment]
I encountered the same issue, but I am not sure what the `unless` refers to.

I have a [fun](https://github.com/vertesy/Seurat.utils/blob/28d2d670a06568c3400fbeca106a85d65f86cb52/R/Seurat.Utils.Visualization.R#L710) that work generally well, but fails on a specific dataset. 

Jumping happens if I redefine the same fun as `qSeuViolin2` in the current window (saved script) then call `qSeuViolin2()`

Based on the current title of this thread, I tried:
2. I redefined `qSeuViolin3` in `test.r` and then `source(test.R)`  then `qSeuViolin3()` **`browser()` is ignored** just fails with error. This was unexpected to me.
3. Same ignore happened if I add `browser()` to library's code, `devtools::load_all(Seurat.Utils)`  then `qSeuViolin()`

I use
RStudio 2023.09.1+494.pro2 "Desert Sunflower" Release (80aa7dd23784dedd170aff0e7e1e1cdd1e99924b, 2023-10-16) for CentOS 7 Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:121.0) Gecko/20100101 Firefox/121.0


**Is there a workaround?** (as I thought from the title)

**Comment by datakid** [comment]
Seen in ticket #99601

**Comment by vertesy** [comment]
Thanks! Do you have a link, or is it internal?

**Comment by datakid** [comment]
@vertesy correct, that's to an internal ticket tracker.

**Comment by wyuill** [comment]
We also have this issue with Posit Workbench 2023.09.1+494.pro2, “Desert Sunflower” (80aa7dd2)

**Comment by kevinushey** [comment]
If I'm understanding the issue correctly, I think this is expected. RStudio relies on R's source references in order to guide the debugger view, and source references giving the file location can only be available if the associated functions are executed via `source()`.

If they're run in the console via Cmd + Enter or the Run button, then those source references aren't set, and we won't be able to present the "original" view. (Conceptually, this is like copy + pasting the code from the file into the Console pane -- at that point, we no longer know that the code came from that source file.)

The issue described in the internal ticket 99601 sounds different -- if I'm understanding correctly, that's specifically about the IDE focus being forced back into the debugged file every time a command is executed. Is that correct? This sounds very similar to https://github.com/rstudio/rstudio/issues/10664 -- @PatrickCoyle, can you confirm if that issue matches the behavior you're seeing?

**Comment by PatrickCoyle** [comment]
> If I'm understanding the issue correctly, I think this is expected. RStudio relies on R's source references in order to guide the debugger view, and source references giving the file location can only be available if the associated functions are executed via `source()`.
> 
> If they're run in the console via Cmd + Enter or the Run button, then those source references aren't set, and we won't be able to present the "original" view. (Conceptually, this is like copy + pasting the code from the file into the Console pane -- at that point, we no longer know that the code came from that source file.)
> 
> The issue described in the internal ticket 99601 sounds different -- if I'm understanding correctly, that's specifically about the IDE focus being forced back into the debugged file every time a command is executed. Is that correct? This sounds very similar to #10664 -- @PatrickCoyle, can you confirm if that issue matches the behavior you're seeing?

@kevinushey yes that is a correct summary of what I'm seeing (internal ticket #99601). The behavior I see is the same as what's described in #9918, not #10664 (although the two may be related. I couldn't say). Thank you.

**Comment by kevinushey** [comment]
Thanks @PatrickCoyle -- I think the issue you describe will be fixed via https://github.com/rstudio/rstudio/pull/14360, and that fix will be in the next daily builds (hopefully available by tomorrow).
