### ISSUE TITLE
failing rsession test

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#13945]
```
── Failed tests ────────────────────────────────────────────────────────────────
Error (test-rsconnect.R:75:4): .rs.rsconnectDeployList() includes _quarto.yml and _metadata.yml files (#10995 )
Error in `if (dirlist$totalSize >= max_size) NULL else .rs.summarizeDir(dirlist$contents,
    5)`: missing value where TRUE/FALSE needed
Backtrace:
    ▆
 1. └─.rs.rsconnectDeployList(main, FALSE, main) at test-rsconnect.R:75:3

[ FAIL 1 | WARN 1 | SKIP 2 | PASS 2956 ]
```

**Comment by kevinushey** [comment]
If I understand correctly... the problem here occurs because, in our test, we run using whatever the current working directory is, but try to introspect a Quarto project living in another directory:

https://github.com/rstudio/rstudio/blob/f43bda13bc27c9d9a3791889cdb7fd8215acb38d/src/cpp/tests/testthat/test-rsconnect.R#L56-L57

When we try to build the list of files for deployment, we only keep the target's filename:

https://github.com/rstudio/rstudio/blob/f43bda13bc27c9d9a3791889cdb7fd8215acb38d/src/cpp/session/modules/SessionRSConnect.R#L355

However, we don't do the same sort of transformation for the `_quarto.yml` file path:

https://github.com/rstudio/rstudio/blob/f43bda13bc27c9d9a3791889cdb7fd8215acb38d/src/cpp/session/modules/SessionRSConnect.R#L372-L378

And so we fail to compute the size here, since we have these incongruent paths:

```
Browse[3]> str(file_list)
 chr [1:2] "main.qmd" "/private/tmp/RtmpEMCzZQ/file163b02b2877f/_quarto.yml"
```

but we compute file sizes assuming everything can be resolved relative to the 'target' here:

https://github.com/rstudio/rstudio/blob/f43bda13bc27c9d9a3791889cdb7fd8215acb38d/src/cpp/session/modules/SessionRSConnect.R#L385-L389

This change was made back in https://github.com/rstudio/rstudio/commit/dace60da12d7c327270e55edd1ff9e0320bc9156.

@jgutman you also helped review in https://github.com/rstudio/rstudio/pull/11201; does this ring any bells?

**Comment by kevinushey** [comment]
This is also failing on CI, but the test failure isn't being properly reported.

<img width="1240" alt="Screenshot 2023-11-22 at 11 39 34 AM" src="https://github.com/rstudio/rstudio/assets/1976582/e3b5bbb8-8d30-4b58-8951-54b149d21f5b">

**Comment by kevinushey** [comment]
This test has been failing for some time, and the code involved looks suspect. Kicking this out of Ocean Storm as it's too late to safely fix this.

**Comment by jgutman** [comment]
So this test passed when it was written, and it passed because at the time, `.rs.quartoFileProject(qmdPath)$project` would return `""`  as the project, when the directory contained a `_quarto.yml` but not `.RProj` file. Now, it returns the path to the directory containing the `_quarto.yml` file. It looks like this change was made by JJ in October 2022 ([here I think](https://github.com/rstudio/rstudio/commit/05d95dd1e61de555053bdf8b981a2c250088fbd6)), a few months after this test was originally written and passing. JJ's change probably made sense, but the change by Romain passed the test because when the project name was `""`, `_quarto.yml` was added, not the absolute path, so the file_list was `main.qmd` and `_quarto.yml`, and all the sizes could be reasonably computed. But if we always add just the `_quarto.yml` then we have trouble computing the sizes with the subdirectory, because those files are no longer in the same relative directory

**Comment by jgutman** [comment]
I spent some time looking at this, but more importantly, I confirmed that the expected behavior this test is supposed to be testing for actually does work correctly. So basically, create a project with the following structure:

- `test.RProj`
- `main.qmd`
-`_quarto.yml`
- `sub/`

Inside the `sub` directory:
- `sub.qmd`
- `_metadata.yml`

Contents of these files don't really matter. If we open `sub/sub.qmd`, Click on Publish > Posit Connect > Publish document with source code, the operation succeeds and we get the list of files we expect: `sub.qmd`, `_metadata.yml`, and `../_quarto.yml`. Doing the same from `main.qmd`, we get `main.qmd` and `_quarto.yml` as expected. So I think that the original issue solved by #11201 still works, however, the test fails because `.rs.docDeployList` actually produces the wrong list. So for example, in the UI, with `sub.qmd`, the list of files to deploy is displayed as 
<img width="318" alt="image" src="https://github.com/rstudio/rstudio/assets/7817881/14e5977f-2901-482d-a541-720e47139350">
but that's not the output we get from the `docDeployList` function
<img width="501" alt="image" src="https://github.com/rstudio/rstudio/assets/7817881/34d8cad5-f90d-4db0-bfe2-45f3bf27521e">

So I'm not sure how this seems to work fine for publishing in the UI if the function is giving the wrong output, causing the test to fail

**Comment by jgutman** [comment]
Okay, I figured out why it works in practice but not in the test -- the function is particular about receiving an absolute, normalized path to the target. It gets messed up in the test with tempfiles because of the symlink (`/var` versus `/private/var`) and got messed up with me calling it with a relative path to the target. If we call `normalizePath` at the beginning of the .rs.docDeployList function, the behavior remains unchanged, but the test now passes. PR imminent

**Comment by jgutman** [comment]
Confirmed that test passes in CI in [2023.12.0-hourly+343](https://build.posit.it/job/IDE/job/OS-Builds/job/Platforms/job/macos-pipeline/job/main/705/)
