### ISSUE TITLE
Proxy authentication configuration

### ISSUE THREAD

**Issue by Waldi73** [rstudio/rstudio#14094]
When I use a proxy (for example corporate), I'm not able to update packages under RStudio.

Work around is to set environment variable `https_proxy`, but this creates safety issues as described in this Stackoverflow question : [How to use Windows user credentials for proxy authentication in R/RStudio](https://stackoverflow.com/questions/77668899/how-to-use-windows-user-credentials-for-proxy-authentication-in-r-rstudio)

Under Windows, when I use a web browser like Firefox, I have the possibility to configure the browser to use System settings for proxy configuration, so that I don't need to input any proxy user / pwd.

Would it be possible to include a similar proxy configuration option in future versions of RStudio?

**Comment by kevinushey** [comment]
It's unfortunately deprecated, but you might have better luck using `options(download.file.method = "wininet")` on Windows. For example: https://community.rstudio.com/t/proxy-support-broken-cannot-install-any-packages-anymore/147160/8

Otherwise, if you're using the default ("libcurl") downloader, then you do indeed need to set `http_proxy` and `https_proxy` appropriately.

**Comment by Waldi73** [comment]
@kevinushey, thanks a lot for your answer, `options(download.file.method = "wininet")` is exactly what I was looking for!
A pity this is deprecated, hopefully it will survive.

**Comment by kevinushey** [comment]
It looks like `curl` uses `:` as a convention for "use default credentials" -- does this work if you try to set that in the proxy URL itself, e.g.

```
Sys.setenv(https_proxy_user = ":")
Sys.setenv(https_proxy = "proxy.<my.domain>:8080")
```

**Comment by Waldi73** [comment]
@kevinushey , thanks so much, that's it!
