### ISSUE TITLE
CLIENT_EXCEPTION Errors when using ctrl + c shortcut in satellite window

### ISSUE THREAD

**Issue by cm421** [rstudio/rstudio#14140]
### System details

    RStudio Edition : Server and Workbench
    RStudio Version :  2023.12.0
    OS Version      : Linux
    R Version       : N/A

### Steps to reproduce the problem
Found in customer ticket 99252. Filing in open source since it occurs in both RStudio Server and Workbench

1. In an RStudio IDE session open a file into a satellite window ("Show in new window" button in top left of a file's pane). 
2. In the satellite window select some text and press ctrl + c
   3.  A Client Exception will appear in `rserver.log`

I was able to produce this locally on both Server and Workbench 2023.12.0 in Firefox, generating the following error 
```
CLIENT EXCEPTION (rsession-parallels): TypeError: $wnd.desktop is undefined;|||http://localhost:8787/s/d5de8cfc78a31ca964c82/?launcher=1&view=source_window_wcd01wp06bz2n line 9 > injectedScript#-1::a/<|||Unknown#-1::anonymous|||Client-ID: 090adfe7-50de-49c7-8a7e-664ad074e069|||User-Agent: Mozilla/5.0 (X11  Ubuntu  Linux x86_64  rv:121.0) Gecko/20100101 Firefox/121.0
```

### Describe the problem in detail

Despite the client exception log, the shortcut still works as ctrl + v still pastes whatever code was copied. The exception does not occur when copying code in the main RStudio IDE window.

### Describe the behavior you expected

Using the ctrl + c should create client exceptions in the logs

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Note: I can reproduce this in RStudio Server (Ubuntu 22 via Chrome on MacOS 14.3), but no equivalent in RStudio Desktop (MacOS 14.3.).

**Comment by gtritchie** [comment]
I'll take a look.

**Comment by gtritchie** [comment]
I reproed back to version 2022.07.0, but I think this problem has always existed (no older builds available for the platform I happen to be testing on).

The problem is a hook that a RStudio Desktop-only hook is being invoked on Server/Workbench. The bit of problematic code is here:

https://github.com/rstudio/rstudio/blob/6c7ff83c7c21a9fd98643c06f6b410f49529f17f/src/gwt/src/org/rstudio/studio/client/application/DesktopHooks.java#L91-L102

`addCopyHook()` gets invoked by the constructor for this class, and it adds copy/cut listeners. These get invoked when you do <kbd>Ctrl</kbd>+<kbd>C</kbd> and try to access a non-existent property, throwing the exception.

The fix is simple, this code needs to do what another instance of this code does, namely check to see if we're actually a Desktop instance before registering these handlers (e.g. `if ($wnd.desktop) {`): 


https://github.com/rstudio/rstudio/blob/6c7ff83c7c21a9fd98643c06f6b410f49529f17f/src/gwt/src/org/rstudio/studio/client/common/shell/ShellWidget.java#L279-L289

**Comment by gtritchie** [comment]
I don't think this is worth backporting to an older release, but we should fix it in next release.

**Comment by ronblum** [comment]
Verified in RStudio Server 2024.04.0-daily+270 on SLES 15 SP5 via Chrome on MacOS 14.3.
