### ISSUE TITLE
No option for users to indicate non-standard R installation path in RStudio-2023.12.0-369.zip

### ISSUE THREAD

**Issue by staehlo** [rstudio/rstudio#14180]
Dear RStudio Team,

I would like to raise an issue that is linked to previously reported issues (which have been closed as resolved):
- [RStudio not able to load selected R version on Windows #12452](https://github.com/rstudio/rstudio/issues/12452)
- [Studio not detecting R](https://community.rstudio.com/t/studio-not-detecting-r/159879)

### System details

    RStudio Edition : Desktop
    RStudio Version : 2023.12.0-369
    OS Version      : Windows 10 Enterprise
    R Version       : 4.3.2

### Steps to reproduce the problem

1. Log on to a Windows 10 computer without admin rights. The issue only appears if the computer has no previous installation of RStudio.
2. Install R under `C:\Users\USERNAME\AppData\Local\R` (might be necessary if you are working on an office computer and your IT department does not allow users to install programs under `C:\Program_Files`). During installation, uncheck "Save version number in registry" and "Associate R with .RData files". This is necessary as you cannot install R without admin rights if these boxes are checked.
3. Download "RStudio-2023.12.0-369.zip" and unzip the folder under `C:\Users\USERNAME\AppData\Local\RStudio`.
4. Enter the folder and launch "rstudio.exe".

### Describe the problem in detail
If you follow the steps described above, RStudio 2023.12.0-369 will show this error message:
![R_Not_Installed_Error_Message](https://github.com/rstudio/rstudio/assets/38019064/1d352626-72b7-4477-ab65-3a19afcb1fda)
Clicking "Yes" or "No" will both terminate "rstudio.exe" without giving you the option to point RStudio to the existing R installation.

The error message will not appear if a previous installation of RStudio exists on the computer as the old installation will have created the folder `C:\Users\USERNAME\AppData\Roaming\RStudio` which contains a "desktop.ini" file. RStudio 2023.12.0-369 seems to detect this file and fetch the path to the R installation from the contained `RBinDir` value. Deleting this file will make the error message reappear.

### Describe the behavior you expected
Previous versions of RStudio (for example 2022.07.0-548) showed the following message in the scenario described above:
![Choose_R_Installation_Message](https://github.com/rstudio/rstudio/assets/38019064/c837bf81-0119-4563-825d-a4f521039cdb)
This made it possible for users to install both R and RStudio under `C:\Users\USERNAME\AppData\...` without the need for admin rights.

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
It feels like we should do away with the "R Not Installed" dialog, and instead show the "Choose R Installation" dialog by default, but add the text blurb from that dialog like "R can be installed from the official R Project website. Please click here to navigate your browser to the R Project website."

Or, alternatively, have a button at the bottom left like "Download R" that would do the same.

**Comment by gtritchie** [comment]
Confirmed that if I install R directly in `Local\R` instead of `Local\Programs\R` I can repro the problem.

Also, I was able to let R installer "Save version number in registry" with no problems (no prompt for admin creds, etc.), and if I do that, then RStudio DID find it in this other location.

**Comment by gtritchie** [comment]
Note that RStudio does specifically look in %localappdata%\Programs\R: https://github.com/rstudio/rstudio/blob/417e7e00ad6ce156396f85fa5b6745428dc797c9/src/node/desktop/src/main/detect-r.ts#L341-L347

This is the standard Windows location for per-user windows programs (`FOLDERID_UserProgramFiles`).

**Comment by gtritchie** [comment]
> Admins can probably fine-tune the privileges of non-admin users. In my case, writing to the registry seems to be completed blocked

For sure, you can apply ACLs to any level of the registry, so probably something they've pushed out via group policy or such. I was testing on a vanilla Windows 11 machine, not on a domain.

> Leaving the default suggestion (C:\Program Files...)

That's interesting, in my case the installer detected I was running as a non-admin user and gave the per-user path I mentioned earlier by default. Probably also related, somehow, to your organization's settings.

> Would it be possible to change line 346 of detect-r.ts from ${getenv('LOCALAPPDATA')}/Programs/R to ${getenv('LOCALAPPDATA')} in future releases of RStudio Desktop? That way, any R installation under AppData should be detected?

I don't think we search recursively (I haven't checked), due to the potential performance problems at startup if someone has a bunch of things installed, so probably don't want to search everything.

But yes, I do want to make the change Kevin suggested; not sure yet if that'll be in the next release or have to wait for the one after that.

**Comment by gtritchie** [comment]
Some other information, in case it is helpful. The RStudio installer can be forced to do a per-user install (without requiring elevation). Not sure if this will work in your environment given what you've described.

Here's one way to do it: https://github.com/rstudio/rstudio/issues/8598#issuecomment-743332502 (the key is setting the environment variable `set __COMPAT_LAYER=RunAsInvoker` before running the installer.

Another way to do the same thing: https://github.com/rstudio/rstudio/issues/8598#issuecomment-1883610096

There are some known issues, though, such as uninstall not working correctly: https://github.com/rstudio/rstudio/issues/14122

I'd like to make the installer ask if you want to do per-user or per-machine (and fix the uninstall bugs) but that's probably not going to happen anytime soon due to other priorites.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.04.0-daily+672 on Windows 11, both when RStudio is from the installer-less zip file and the installation executable.
