### ISSUE TITLE
QA tracking issue for yaml-cpp 0.8.0

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#14206]
https://github.com/rstudio/rstudio/pull/14189 wasn't associated with any particular commit; this issue is used to track testing of the updated yaml-cpp 0.8.0 dependency.

yaml-cpp is used in a few places:

- Parsing Quarto chunk options (test execution of Quarto documents?)
- Parsing roxygen2 tags for autocompletion support (test autocompletion of roxygen2 tags?)
- Parsing YAML in Tutorial files (test enumeration of tutorials in the Tutorial pane?)

**Comment by olivroy** [comment]
Do not know if this is related, but I think that highlighting for a plain .yaml file seems broken. Probably not related to #14227 , because it was the same in 2024.04.0+397 and +426, was not like this in 2023.12.0
![image](https://github.com/rstudio/rstudio/assets/52606734/3ac453e7-57c4-49c9-a970-bb88dc4b05f3)

**Comment by kevinushey** [comment]
@olivroy can you please file a new issue, with the text of the document in which you're seeing the highlight issue included?
