### ISSUE TITLE
Can't step into a `tryCatch()` (or maybe any `{`?) when `keep.source = FALSE`

### ISSUE THREAD

**Issue by DavisVaughan** [rstudio/rstudio#14306]
Should probably be tackled with #14276 because you'll already be in that headspace. As with that issue, this is quite common when debugging packages installed from CRAN, and my reprex below just fakes that experience.

```r
eval(parse(text = "fn <- function() {
  tryCatch({
    1 + 1
    2 + 2
    3 + 3
  })
}
", keep.source = FALSE))

debugonce(fn)

fn()
```

Note how the line number doesn't update once we are in the try catch

This has actually annoyed me quite a bit over the years

https://github.com/rstudio/rstudio/assets/19150088/bffc21f4-ed84-4171-a2e2-a97e7583942c

**Comment by kevinushey** [comment]
Testing note: there's still an issue where the first attempt to step into the body of the `tryCatch()` statement doesn't update, e.g.

<img width="292" alt="Screenshot 2024-02-28 at 1 57 10 PM" src="https://github.com/rstudio/rstudio/assets/1976582/7f03cab4-31e9-422d-a2c4-b1f079141d14">

But somehow we recover on the following attempts to step through. Debugging the issue was hairy, more-so because it seemed to work on occasion when I was debugging, hinting at a possible race condition somewhere? But perhaps that's still "good enough" for this issue?

**Comment by ronblum** [comment]
Verified using the original example in
- RStudio Desktop 2024.04.0-daily+581 on MacOS 14.4
- RStudio Server 2024.04.0-daily+593 on Ubuntu 22.04 via Chrome on MacOS 14.4
