### ISSUE TITLE
Make "remove objects" confirmation optional

### ISSUE THREAD

**Issue by jondo** [rstudio/rstudio#14416]
When clicking the "Clear objects from the workspace" broom icon, I get the dialog:
"Are you sure you want to remove all objects from the environment? This operation cannot be undone."

As I am always sure (and ensure reproducibility by using scripts and restarting R often) I want to get rid of this dialog. Please make it optional.

(Seen in RStudio 2023.12.1+402)

**Comment by ronblum** [comment]
@jondo Thank you for the suggestion! We'll consider it as we continue to develop RStudio.

**Comment by jondo** [comment]
@ronblum Thank you! Do you have a development roadmap published somewhere? The next release [will be](https://github.com/rstudio/rstudio/blob/main/NEWS.md) "Chocolate Cosmos" – Is there any system behind your release [milestone](https://github.com/rstudio/rstudio/milestones) names?

**Comment by jondo** [comment]
Ah, and: The "Are you sure" dialogs of "Remove the current plot" / "Clear all plots" should also be optional.

**Comment by jondo** [comment]
This is still disturbing my workflow.

**Comment by jondo** [comment]
My workaround: Session -> Restart R instead (ctrl+shift+F10).
Fortunately (but inconsistently 😉) this does not show a similar confirmation dialog.

**Comment by kevinushey** [comment]
A destructive action that cannot be undone should require user confirmation -- otherwise, a misclick could lead to unintended data loss.

If you want to remove data without confirmation, you can execute `rm(list = ls())`, and even bind execution of that code to a keyboard shortcut / make an [RStudio Addin](https://rstudio.github.io/rstudioaddins/).
