### ISSUE TITLE
Support Rtools 4.4

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#14453]
R 4.4.0 is due to be released in April, and alongside it a new release of Rtools is being prepared as well. Users who wish to build packages from sources on Windows will need to have Rtools44 installed.

This issue tracks updating RStudio to support installation + discovery of Rtools44.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.04.0-daily+652 on Windows 11 using R 4.4.0 pre relase (R-devel).

Tested by checking out [the `dplyr` package](https://github.com/tidyverse/dplyr) and running "Install" which downloads and installs RTools 4.4.0. Running "Install" again successfully compiles and builds the package (might first need to load package dependencies).

**Comment by MukhalaC** [comment]
I am using R 4.5.2 and RStudio 2026. There are some packages I would like to install but they fail because Rtools for the R version I am using, fails to install. It says version for Windows you are using is not available. I am using Windows 11 and Rtools version I have been trying to install since I installed Windows 11 is Rtools 4.5. Is there any way out of this problem?

**Comment by kevinushey** [comment]
Can you please share the output you're seeing when you try to install packages?
