### ISSUE TITLE
Debugging line offset and misbehaviour when breakpoints within S3 method

### ISSUE THREAD

**Issue by ms609** [rstudio/rstudio#14499]
### System details

    RStudio Edition : Desktop or Server
    RStudio 2023.12.1+402 "Ocean Storm" Release (4da58325ffcff29d157d9264087d4b1ab27f7204, 2024-01-28) for windows
    Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) 
    RStudio/2023.12.1+402 Chrome/116.0.5845.190 Electron/26.2.4 Safari/537.36
    OS Version      : Windows 10
    R Version       : devel

### Steps to reproduce the problem

1. Open an R package project within RStudio
1. Place a breakpoint within an S3 method.  For example, create a file `R/debug.R` containing:
```r
Foo <- function(x) {
  UseMethod("Foo")
}

#' @export
Foo.numeric <- function(x) {
  aa <- 1 # Place breakpoint on this line
  bb <- 2 # Place breakpoint on this line
  x
}
```
3. Load the code, perhaps with <kbd>Shift-Ctrl-L</kbd> or `devtools::load_all()`
4. Call the method from the console – in this example, type `Foo(1)`

### Describe the problem in detail

1. The code breaks at the call to `UseMethod("Foo")`.  If only one breakpoint is set, this is the extent of the problem; when "Next" is pressed (or `n` is typed), debugging continues normally.

![image](https://github.com/rstudio/rstudio/assets/1695515/8eb05403-4027-4b10-ae6d-10975ee6add4)

2. If two breakpoints are set, we are in the same condition when we reach the first breakpoint: the wrong line is indicated, but the correct line is actually being encountered by the debugger:

![image](https://github.com/rstudio/rstudio/assets/1695515/f074f218-b609-459a-92be-dcf177babdf1)

![image](https://github.com/rstudio/rstudio/assets/1695515/b641fcaa-58c0-430b-bfe7-e881e149826f)

3. But when we click "Next", the debug line contains an extra `.doTrace(browser())`:

![image](https://github.com/rstudio/rstudio/assets/1695515/71ac84e1-f325-4879-9028-8b6f192de07c)

![image](https://github.com/rstudio/rstudio/assets/1695515/19f275dc-e016-4d80-978e-09ce4bdf4786)

5. And when we click "next" again, we debug `.doTrace(browser())`, and the cursor points to the third line after `UseMethod("Foo")`.

![image](https://github.com/rstudio/rstudio/assets/1695515/372d296b-bd8a-4b89-8564-20ae74d1277f)

![image](https://github.com/rstudio/rstudio/assets/1695515/89879479-df1d-479d-b6ac-618ce4847b7a)

### Describe the behavior you expected

Cursor should point to line being debugged; only code in script should be debugged.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jthomasmock** [comment]
Thanks for noting the issue. Can you try with manual `browser()` calls as well?

**Comment by ms609** [comment]
I hope I've interpreted @jthomasmock 's comment correctly: when I run this code with no breakpoints:
```r
#' @export
Foo.numeric <- function(x) {
  browser()
  aa <- 1 # Place breakpoint on this line
  browser()
  bb <- 2 # Place breakpoint on this line
  x
}
```

I see:
```
> Foo(1)
Called from: Foo.numeric(1)
Browse[1]> n
debug at C:/Users/pjjg18.MDS/GitHub/Ternary/R/test.R#8: aa <- 1
Browse[2]> n
debug at C:/Users/pjjg18.MDS/GitHub/Ternary/R/test.R#9: browser()
Browse[2]> n
```
Which is as expected so far.

But now, the next press of "Next" does not advance the code; the pointer remains on the `browser()` line. (Note that the previous `n` call did not display any output – presumably this is where an invisible operation has occurred).

```
Browse[2]> n
debug at C:/Users/pjjg18.MDS/GitHub/Ternary/R/test.R#10: bb <- 2
Browse[2]> n
debug at C:/Users/pjjg18.MDS/GitHub/Ternary/R/test.R#11: x
Browse[2]> n
[1] 1
```

**Comment by kevinushey** [comment]
Trying to brain-dump some investigation... if you call `Foo.numeric(1)` directly, you get the right debugger behavior. This is because R is able to provide us with a srcref that gives the location of the current bit of code being executed.

<img width="571" alt="Screenshot 2024-07-08 at 5 14 08 PM" src="https://github.com/rstudio/rstudio/assets/1976582/9e17f9a8-420c-4c4f-931f-3acafda7320f">

However, for some reason, when S3 dispatch is performed to a debugged method, those source references are lost. That is, if I call `Foo(1)` instead:

<img width="563" alt="Screenshot 2024-07-08 at 5 15 14 PM" src="https://github.com/rstudio/rstudio/assets/1976582/fc5c76d7-2966-45d7-b0b5-937010177013">

Note that `srcref` is just an empty pairlist (ie, `NULL`). When this happens, we try using the source reference from the next context instead, since that's also associated with the same closure:

<img width="563" alt="Screenshot 2024-07-08 at 5 16 09 PM" src="https://github.com/rstudio/rstudio/assets/1976582/e2873712-e794-47e0-8afc-9b4ed06df553">

but that source reference is associated with where `Foo.numeric(1)` was invoked; ie, where `UseMethod("Foo")` is.

I need to think a bit more about what the right fix is, but it's probably something like:

- If we have a source reference associated with the currently-browsed frame, use it as-is.
- If we do not, then try to pull source references from a parent context, but only use that for figuring out what file a particular function definition lives in -- use heuristics to resolve the debug location in that scenario.)

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.07.0+316 on Windows 11 with R 4.0.5 and 4.4.1.

Notes
1. Reproduced in RStudio Desktop 2024.04.2+764 on Windows 11 with R 4.0.5 and 4.4.1. More extreme version in  RStudio 2022.12.0+353 with R 4.0.5.
2. Reprex requires both `devtools::document()` and `devtools::load_all()`.
