### ISSUE TITLE
Provide optional method to use RStudio without Quarto

### ISSUE THREAD

**Issue by jthomasmock** [rstudio/rstudio#14505]
There have been some OS (CentOS 7 and Fedora) that are incompatible with Deno, which thus makes bundling Quarto a problem and RStudio behave a bit unexpected.

We could allow for a way to build or distribute RStudio on these OS without Quarto, and allow the IDE to act like it did prior to 2022.07.0 where Quarto integration was optional.

See: https://github.com/rstudio/rstudio/issues/12609

**Comment by Enchufa2** [comment]
Just to be clear: we don't want to use RStudio without Quarto; we want RStudio to detect an externally-provided Quarto installation and use it (just like with e.g. git).

There's already a way to build RStudio without Quarto (admittedly, with some tweaks), and we (Fedora) already do this. But the issue is that, if I install Quarto myself, the options to create a new Quarto document, etc., are not there.

**Comment by ronblum** [comment]
@Enchufa2 Going by https://github.com/rstudio/rstudio/pull/14759#issuecomment-2138267571, I think that we can consider this resolved--is that correct?

**Comment by Enchufa2** [comment]
Errors or omissions excepted, and if the PR does what it claims, then yeap! :) I didn't have the opportunity to test it yet. I'll try to make a nightly build with our configuration for Fedora and report back.

**Comment by ronblum** [comment]
Great! And thank you--I'll leave this open until you have the opportunity to test this.

**Comment by Enchufa2** [comment]
Tested, works great!
