### ISSUE TITLE
Document outline broken for title-less Quarto slides with slide-level attribute

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [rstudio/rstudio#14552]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2024.04.0-daily+689 "Chocolate Cosmos" Daily (9ee2b6131e42e36e31cec48a4eb88d2e700e272c, 2024-04-10) for macOS Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2024.04.0-daily+689 Chrome/120.0.6099.291 Electron/28.2.6 Safari/537.36, Quarto 1.4.553 (/Applications/quarto/bin/quarto)
    OS Version      : Mac OS Ventura 13.5 (22G74)
    R Version       : R version 4.3.3 (2024-02-29) -- "Angel Food Cake"

### Steps to reproduce the problem

Create a Quarto slide deck with `format: revealjs` and include a mix of slides with and without titles:

````markdown
---
format: revealjs
---

# Section with title

## Slide with title

Some content.

##

Slide without title

# Another section with title

## Another slide with title
````

What the document outline shows is not ideal (it completely ignores the title-less slide) but has the right indentation for sections and slides, in both the visual and source editors.

<img width="400" alt="Screenshot 2024-04-16 at 3 14 45 PM" src="https://github.com/rstudio/rstudio/assets/5965649/d2e260a4-1a05-4e4a-9f62-8282c6701a22">

<img width="400" alt="Screenshot 2024-04-16 at 3 14 56 PM" src="https://github.com/rstudio/rstudio/assets/5965649/33376b7d-1bcf-4c92-948d-17d6ef6f7405">

Now add a slide-level attribute to the title-less slide (e.g., `{.smaller}`). The document outline indentation is broken in the source editor, still look ok (even if not ideal) in the visual editor.

<img width="400" alt="Screenshot 2024-04-16 at 3 16 30 PM" src="https://github.com/rstudio/rstudio/assets/5965649/39674566-10fc-4186-a84a-c18436762149">

<img width="400" alt="Screenshot 2024-04-16 at 3 16 43 PM" src="https://github.com/rstudio/rstudio/assets/5965649/123c4c82-f1a4-4101-97fe-53f73b39f6cf">

### Describe the problem in detail

Title-less slides break document outline indentation in the source editor if they have an attribute at the slide level.

### Describe the behavior you expected

I expected

1. Title-less slides to show up in the document outline
2. The behavior of the document outline to match between source and visual editors when title-less slide has a slide-level attribute.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Reproducible in both RStudio Desktop 2023.12.1+402 and 2024.04.0-daily+693 on Windows 11.

**Comment by cathblatter** [comment]
I observe this inconsistently also with html–documents.
Adding (and then removing) another hashtag to the title triggers the section to appear again in the toc.

(R 4.4.0 / R Studio 2024.05 / newest quarto release)

**Comment by gtritchie** [comment]
This issue is essentially the same as #13159, which was partially addressed via https://github.com/rstudio/rstudio/pull/14908.

Beginning with RStudio 2024.07.0+271, if the empty header has any attributes (even `{}` will do) it shows up in the outline as "(Untitled)." However, this is only true in source mode, it still doesn't display in Visual Editor mode.

<img width="557" alt="untitled heading shown in outline in source mode" src="https://github.com/rstudio/rstudio/assets/10569626/036bb568-37ea-4595-831c-cb2aad7e52f5">

<img width="555" alt="untitled heading not displayed in outline in visual mode" src="https://github.com/rstudio/rstudio/assets/10569626/43ddb56b-8559-4389-9d7c-2f9f557bafae">

However, without any attributes then the problem as reported still exists: the section isn't displayed in the outline; leaving this issue open to track that specific problem.

<img width="557" alt="heading not displayed and indentation incorrect in source mode" src="https://github.com/rstudio/rstudio/assets/10569626/75cfec7b-b02e-46cb-8c57-a997e341824c">

**Comment by gtritchie** [comment]
Verified in build 2024.10.0-hourly+196 on macOS.
