### ISSUE TITLE
RStudio on Ubuntu 24.04 does not start, causes fatal error in setuid_sandbox_host.cc (chrome-sandbox)  -> work-around included

### ISSUE THREAD

**Issue by GerryT11** [rstudio/rstudio#14601]
I installed RStudio in a new Ubuntu 24.04 installation. The installation of RStudio worked fine, but it was not able to start. It caused a fatal error in setuid_sandbox_host.cc ("chrome-sandbox is owned by root and has mode 4755", "I'm aborting now").

Please update the rstudio settings for Ubuntu 24.04, so that it runs properly.

Work-around: 
sudo chmod 4755 /usr/lib/rstudio/chrome-sandbox
-> after applying the work-around, RStudio just worked fine.

**Comment by gtritchie** [comment]
Already tracked in #14336. Closing as duplicate.

**Comment by ejneves** [comment]
This solved the problem for me:

sudo chown root:root /usr/lib/rstudio/chrome-sandbox
sudo chmod 4755 /usr/lib/rstudio/chrome-sandbox

**Comment by Rexel1** [comment]
I have the same problem, I have tried it but don´t works:
“[2726:0703/123020.124647:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I’m aborting now. You need to make sure that /usr/lib/rstudio/chrome-sandbox is owned by root and has mode 4755.”

Help!

**Comment by gtritchie** [comment]
This is the wrong issue; please use https://github.com/rstudio/rstudio/issues/14336.
