### ISSUE TITLE
Chinese comments make R Session to Abort

### ISSUE THREAD

**Issue by ziqiuduofu** [rstudio/rstudio#14665]
### System details

    RStudio Edition : 
    RStudio Version : RStudio 2024.04.0+735
    OS Version      : macOS Sonoma 14.3.1
    R Version       : 4.4.0

### Steps to reproduce the problem
p <- forest(dt[,c(1:3, 8:9)],
            est = dt$est, #效应值
            lower = dt$low, #lower value
            upper = dt$hi,  
            sizes = dt$se,  
            ci_column = 4)
### Describe the problem in detail
If there are Chinese comments within a line inside a function, pressing Tab on that line causes R Session to Abort, with a fatal error message: "Unexpected exception: vector."

![image](https://github.com/rstudio/rstudio/assets/80271567/793a3f36-c4dc-4699-8098-11d5d5af4b67)

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@ziqiuduofu Thank you for raising! In addition to MacOS, I can reproduce this in RStudio Server 2024.04.0+735 on Ubuntu 22 via Chrome on Windows 11. There's no problem on Windows 11. Note that occurs with autocomplete, both with <kbd>Tab</kbd> and <kbd>Ctrl+Space</kbd>.

Verified fixed in
- RStudio Desktop 2024.04.1+748 and 2024.07.0-daily+102 on MacOS 14
- RStudio Server 2024.04.1+748 and 2024.07.0-daily+102 on Ubuntu 22 via Edge on Windows 11

@kevinushey Could this have gotten fixed as bonus of the fix to #14625?

**Comment by kevinushey** [comment]
I suspect so!
