### ISSUE TITLE
Feature request: add a dropdown button to select language for a code snippet

### ISSUE THREAD

**Issue by mdehollander** [rstudio/rstudio#14785]
Originally posted at quarto at https://github.com/quarto-dev/quarto/issues/461, but is more a RStudio thing than Quarto specific, so posting here:

With R Markdown notebooks you can select the language when inserting a code chunk. With Quartro notebooks this is not present, where manually changing r to bash after a code chunk has been inserted works. A dropdown would be more user friendly.

| notebook | image| 
|----|----|
|Quartro |![image](https://github.com/quarto-dev/quarto/assets/262872/fa4a3163-380c-4bc6-8432-251a7a5391ab) |
|R Markdown | ![image](https://github.com/quarto-dev/quarto/assets/262872/22a69193-e479-444d-a6cb-df750ff6ffd4)|

**Comment by ronblum** [comment]
@mdehollander Thank you for the suggestion! We'll review it as we continue development of RStudio.

**Comment by gtritchie** [comment]
The existing menu for inserting code cells (Visual Mode, Insert / Executable Cell) has a couple more options (D3 and Julia) and is in a different order than the newly added dropdown (see screenshots).

This may have been intentional, per the PR comment, "Updated the menu items to better match the most commonly used chunk options," but I thought I'd check.

### Existing menu
<img width="351" alt="existing-menu" src="https://github.com/user-attachments/assets/f64e1cde-a232-406d-bb14-2c51baa983bb">

### Newly added dropdown menu
<img width="134" alt="new-dropdown-source" src="https://github.com/user-attachments/assets/de763446-482e-4836-bb3d-aff92899ec26">

**Comment by gtritchie** [comment]
Also noticed there are commands (e.g. via command palette) for inserting all these types except Julia.

<img width="616" alt="insert-commands" src="https://github.com/user-attachments/assets/6fd570af-3809-4d40-abda-ef55c6009acc">

**Comment by gtritchie** [comment]
Verified on build 2024.10.0+182 on macOS.

**Comment by mdehollander** [comment]
:tada: Great to see that this has been picked up. Thanks.
