### ISSUE TITLE
Cannot open RNW

### ISSUE THREAD

**Issue by huzefaKhalil** [rstudio/rstudio#14794]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2024.04.0 build 748
    OS Version      : macOS Sonoma 14.5
    R Version       : 4.3.3

### Steps to reproduce the problem
Try and open an RNW file.

### Describe the problem in detail
File doesn't open and gives an error message
(TypeError) : Cannot read properties of undefined (reading 'count')

### Describe the behavior you expected
The file would be opened

- [ x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@huzefaKhalil Thank you for raising this! This bug is being tracked in issue #14646. It will be addressed in patch 2024.04.2, which will be released very soon. You can view a preview of it at https://dailies.rstudio.com/rstudio/chocolate-cosmos/. Note that these builds are for testing purposes only and not for production use.
