### ISSUE TITLE
Running code adds a newline to the codeblock

### ISSUE THREAD

**Issue by matlzztt** [rstudio/rstudio#14813]
RStudio Edition: "Chocolate Cosmos" for X86_64 GNU/Linux, ([https://aur.archlinux.org/packages/rstudio-desktop](AUR))
    RStudio Version: "Build 748"
    OS Version: "Arch Linux x86_64  (kernel is Linux 6.9.3-arch1-1)"
    R Version: R version 4.4.0 (2024-04-24) -- "Puppy Cup" ([https://archlinux.org/packages/extra/x86_64/r/](official package))

### Steps to reproduce the problem

Try to run code in the text editor pressing Ctrl+Enter or pressing the Run button.

### Describe the problem in detail

Cursor in the text editor acts as if I pressed Enter on it, creating a newline and altering the document.

### Describe the behavior you expected

Running code should not modify the text editor.

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [X] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@fangederos Thank you for raising this! Can you provide sample code for which this occurs, or does it even happen with the default Quarto or R Markdown files? Also, do you know which version of RStudio this last worked?

**Comment by ronblum** [comment]
@fangederos Ah, sorry, I left out that I was asking for code because I couldn't reproduce the issue. 🙂 

But, I can reproduce it, after all: It happens if the cursor is in the last line of the script. Any other line, and the problem doesn't happen. Can you confirm?

Looks like this has been around for a while, if not always, as the problem occurs in RStudio Desktop 2022.12.0+353 on Windows.

**Comment by ronblum** [comment]
@fangederos Also, it's not you being a noob. 😄

**Comment by fangederos** [comment]
@ronblum That's fine! I'm glad to help uncovering this with you lol

'Can you confirm?' I cannot, actually. Here it happens in any line in the document, weirdly enough. 

I've actually grew to like it a little bit... because it behaves as it was 'parsing' through the code, making it easy to run theoretically run various scripts inside an R script. Not that I've done any of that.
