### ISSUE TITLE
Outline has gaps in it in long qmd documents 

### ISSUE THREAD

**Issue by stgries** [rstudio/rstudio#14906]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2024.04.2+764
    OS Version      : POP OS 22.04
    R Version       : 4.4.1

### Steps to reproduce the problem
The bug cannot be reproduced other than by loading the relevant files: I have two books each written in Quarto 1.5.47 (/opt/quarto/bin/quarto):

* book 1: 16000 lines
* book 2: 7600 lines

Both books use a document structure defined by # headings can be knitted without problems. However when I open them, the outline pane has weird gaps in it. This has happened before and I downgraded RStudio to, I think, the last 2023 version, which worked fine. But now I upgraded again to the version mentioned above and the same problem resurfaced; see attached screenshots:

![Untitled1](https://github.com/rstudio/rstudio/assets/174378807/4284c008-8feb-41b3-8283-d0417e1e1d6b)
![Untitled2](https://github.com/rstudio/rstudio/assets/174378807/b2885fe1-2c5a-4e7b-a05b-d0da75981789)

The same happens on an Windows 11 laptop with the same version of R and RStudio installed.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by stgries** [comment]
Update: I regressed to RStudio 2023.12.1 Build 402 and the problem disappeared on both the POP OS and the Win 11 systems: this must be something introduced between that version and the current one(s).

**Comment by kevinushey** [comment]
A reproducible example would be helpful. Can you share the document wherein you're seeing this behavior?

**Comment by stgries** [comment]
Ok, I will send you one of the two book files to your email address. As for your question

"are those just very unnecessary blank spaces, or is part of the outline missing?"

Yes, the part of the outline is missing, that IS the bug, the fact the current versions of RStudio introduce those gaps in the outline.

**Comment by ronblum** [comment]
@stgries Thanks! File received.

And I was trying to differentiate between bad (missing info) and ugly (complete info but with a big blank area in the middle). So we've got bad. We strive for good.

**Comment by stgries** [comment]
Sure thing, I hope the file will help!

**Comment by ronblum** [comment]
I can reproduce it. As described above: works in RStudio Desktop 2022.12, regressions starts in 2024.04 (checked on Windows).

**Comment by ronblum** [comment]
Oof, updated. Thank you! This is why I usually copy and paste the version from `RStudio.Version()$long_version` instead of typing it out...

**Comment by kevinushey** [comment]
I did some investigation... this one seems pretty hairy. RStudio uses what it calls a "scope tree" to keep track of the scopes created by e.g. sections from Markdown headers, as well as R chunk boundaries.

When a new node is added, we have some code that "opens" a node that might've already been closed here:

https://github.com/rstudio/rstudio/blob/8360520006e35cb49cf5165517f56e20dc192a0d/src/gwt/acesupport/acemode/r_scope_tree.js#L124

In this scenario, we end up "opening" a chunk which should actually already be closed. This "open" chunk then ends up "eating" all subsequent chunks.

I think we run into trouble because 'closeScope' only ever tries to close the last node in a scope tree:

https://github.com/rstudio/rstudio/blob/8360520006e35cb49cf5165517f56e20dc192a0d/src/gwt/acesupport/acemode/r_scope_tree.js#L150-L182

but apparently we can run into a scenario where the unclosed chunk isn't actually the last node in that scope tree. For example:

<img width="816" alt="Screenshot 2024-07-05 at 11 11 39 PM" src="https://github.com/rstudio/rstudio/assets/1976582/d71dab03-4052-4134-a238-89a74b96dfad">

Note how, in this case, "Chunk 357" has `end: null`, even though it's not the last chunk in the scope tree. This eventually leads to this bit of confusion:

<img width="198" alt="Screenshot 2024-07-05 at 11 12 40 PM" src="https://github.com/rstudio/rstudio/assets/1976582/c41d1bee-28f4-41ac-bc8e-3e97090af480">

I still don't have a minimal reproducible example, however, but at least this is roughly where we need to look, I think.

Also potentially related: https://github.com/rstudio/rstudio/blob/8360520006e35cb49cf5165517f56e20dc192a0d/src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditor.java#L4691-L4739

**Comment by kevinushey** [comment]
As a side note, commenting out this line:

https://github.com/rstudio/rstudio/blob/8360520006e35cb49cf5165517f56e20dc192a0d/src/gwt/acesupport/acemode/r_scope_tree.js#L124

also resolves the issue, but that alone is almost surely not the right fix. (Perhaps it's okay to allow an already-closed chunk to remain closed?)

**Comment by stgries** [comment]
Ok, that's all definitely stuff above my level of competence ;-) But thanks for the update, much appreciated. I hope fixing this won't be too much hassle ...

**Comment by gtritchie** [comment]
The issue started with this PR: [support exit from nested state in chunk #14558](https://github.com/rstudio/rstudio/pull/14558)

Specifically, if you undo the first change in `src/gwt/acesupport/acemode/utils.js` (line 115 - 120) the problem goes away.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.07.0-daily+303 on Windows 11 using the sample file.
