### ISSUE TITLE
There is no arrow pointing to the current line when debugging

### ISSUE THREAD

**Issue by A-Pai** [rstudio/rstudio#15395]
My Rstudio version is “2024.09.0 Build 375”，R version is “R version 4.4.2 (2024-10-31 ucrt) -- "Pile of Leaves"”
There is no arrow pointing to the current line when debugging：
![image](https://github.com/user-attachments/assets/61645975-1f66-432e-840b-068803ba8f3b)

Arrows are available only if the version of R is back to 4.3.2：
![image](https://github.com/user-attachments/assets/af23c2bb-23a6-4687-a894-da003119b802)

**Comment by kevinushey** [comment]
This seems to work as expected for me in the latest daily builds of RStudio: https://dailies.rstudio.com/

Any chance you'd be able to check and see if the issue persists for you there as well?

**Comment by gtritchie** [comment]
I also cannot repro with latest daily build (2024.12.0-daily+368), but I was able to repro using 2024.09.1+394 on Windows-11 with R 4.4.2:

![r-4 4 2](https://github.com/user-attachments/assets/28184969-0e43-43a2-aea6-e677ddeccafc)

But downgrading to R 3.6.3 (in my case) fixes it:

![r-3 6 3](https://github.com/user-attachments/assets/ea11159a-da66-4d0a-b083-f6534e609834)

So this appears fixed in the upcoming 2024.12 release.

**Comment by gtritchie** [comment]
I'm closing this. If you find that 2024.12 doesn't fix this for you please let us know and we'll reopen this.
