### ISSUE TITLE
Blank lines omitted in executed notebook chunks

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#1556]
First, create this R Markdown Notebook:

      ---
      title: "R Notebook"
      output: html_notebook
      ---
      
      ```{r}
      # Here is a math
      invisible(1 + 2)
    
      # Here is more math
      invisible(1 + 3)
      
      # Math is everywhere
      ```

Don't execute the code, but preview the notebook. Note that blank lines are preserved in the output.

![image](https://user-images.githubusercontent.com/470418/31288862-85fa1934-aa7b-11e7-9aa8-0aaac02b8ba8.png)

Run the chunk. Nothing visible happens, but... preview the notebook again. The blank lines are gone.

![image](https://user-images.githubusercontent.com/470418/31288868-8b6d42a6-aa7b-11e7-8b7a-9cfbca9fdba1.png)

**Comment by jmcphers** [comment]
Reported on the R notebooks docs:

http://rmarkdown.rstudio.com/r_notebooks.html#comment-3212998177

and Stack Overflow:

https://stackoverflow.com/questions/41066190/no-line-breaks-inside-code-chunks

and R Markdown issues page:

https://github.com/rstudio/rmarkdown/issues/1074

**Comment by kevinushey** [comment]
It looks like the root of this issue is likely that the blank lines in the source code aren't entering the notebook cache:

```
kevin@cdrv:~/.rstudio/notebooks/6878EAFD-ouch/1/s/ckqmnc467jup3
$ cat 000002.csv
"0","# Here is a math"
"0","invisible(1 + 2)"
"0","# Here is more math"
"0","invisible(1 + 3)"
"0","# Math is everywhere"
```

**Comment by dfalty** [comment]
Verified fixed 1.2.150

**Comment by gcalmettes** [comment]
The fix seems to work for all but `python` language.

Any idea why?

![img](https://i.imgur.com/0tMUzx2.png)

**Comment by kevinushey** [comment]
The issue you're seeing is an issue in `rmarkdown` (or possibly `knitr`) as it can be reproduced with a plain `rmarkdown::render()`.

**Comment by kevinushey** [comment]
Sorry, this is an issue in the reticulate Python engine (as used by knitr). I'll take a look.

**Comment by gcalmettes** [comment]
Thanks @kevinushey !

**Comment by jbullock35** [comment]
A version of this problem seems to persist in RStudio 1.2.5033 and 1.3.878. Specifically, blank lines that appear in code chunks are skipped in the RStudio Preview output if (a) they follow commands that print something to the screen, (b) one is working with an R Notebook, and (c) `results = FALSE`. 

This isn't an `rmarkdown::render()` problem. It doesn't occur for HTML documents (as opposed to notebooks). And it occurs whether `eval` is `TRUE` or `FALSE`. Here is a minimal example:

    ---
    title: "Example: Omitting Blank Lines in Chunk Output"
    output: html_notebook
    ---

    ```{r, results = FALSE}  
    myString <- "The blank line after this one will appear in the chunk output."

    print("In RStudio Preview, the blank line that follows won't be printed.")        

    print("No blank line appears above this line in the previewed chunk output -- but a blank line should appear.")
    ```

And here is the previewed output:
![image](https://user-images.githubusercontent.com/4016787/75890956-b5b28380-5df4-11ea-94d1-0585d5373519.png)

But when I create the R Notebook directly with `rmarkdown::render()`, there is no problem.

Am I right to think that this is a problem, or is this the intended behavior?

**Comment by kevinushey** [comment]
This sounds like a bug. Would you mind filing a separate issue?

**Comment by jbullock35** [comment]
> This sounds like a bug. Would you mind filing a separate issue?

Thank you. I don't mind at all—I'll file the issue now.

**Comment by jbullock35** [comment]
> This sounds like a bug. Would you mind filing a separate issue?

Thank you. I don't mind at all; I just filed the new issue (#6399).
