### ISSUE TITLE
Spell check does not fully check .Rmd files (bug)

### ISSUE THREAD

**Issue by colinbrislawn** [rstudio/rstudio#1588]
Take this example R markdown file:

```
---
title: "Title"
output: html_document
---

## H2 missssspelling

** Bold text missssspelling **
_ italisized text with two missssspellings _

Normal text with a final missssspelling.

```{r }
library(rmarkdown)
library(knitr)
.
.
.
```

Currently, Check Spelling only identifies spelling errors in the normal text of `.Rmd` files, and would only identify a single error in this document. Styled text in markdown files should be check as well.

---

P.S. This is my first time submitting to this repo and I appreciate your feedback and guidance.

**Comment by jmcphers** [comment]
This happens because of the way R Markdown documents are tokenized. Only tokens with the "text" type are spell-checked. 

https://github.com/rstudio/rstudio/blob/master/src/gwt/src/org/rstudio/studio/client/common/filetypes/TextFileType.java#L481-L482

However, for syntax highlighting, we assign non-text token types to headers, etc. For example the bold text is `constant.numeric`: 

![image](https://user-images.githubusercontent.com/470418/31467687-b1b2295a-ae8f-11e7-923f-2268ab225137.png)

whereas the correctly spellchecked text is just `text`.

**Comment by mattpollock** [comment]
Is any work on this issue planned for the near future? I'm trying to transition my org to use RMD to reveal.js (away from PPT) briefings, but it is embarrassing when the resulting briefings have errors all over the headers, styled text, and 2nd level or deeper bullet points.

**Comment by colinbrislawn** [comment]
I agree. The technical impact of this bug is negligible, but the social impact is HUGE! I'm nervous to share my code with colleagues if it's littered with silly errors. Right now I do a spellchecking pass in Atom, and I'm cringing even as I write that sentence. 

Spellcheck is a crucial tool for social collaboration!

While I would love to see [proper scaling on 4k displays](https://github.com/rstudio/rstudio/issues/2135), I would use proper spelling every day. 📝 ❤️
