### ISSUE TITLE
Unable to open RStudio Desktop v1.2.105 on MacOS

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#1600]
I am unable to open RStudio Desktop v1.2.105 on MacOS. I've tried all the way back to v1.2.73, but no luck. This is on MacOS Sierra (10.12.6) on a 15-inch 2017 MacBook Pro. The error message is "RStudio cannot be opened because of a problem."
![macos_failure](https://user-images.githubusercontent.com/31009952/31517924-765e8268-af6b-11e7-90fc-748d0d1c15f3.png)

Full problem report:
Process:               RStudio [574]
Path:                  /Applications/RStudio.app/Contents/MacOS/RStudio
Identifier:            org.rstudio.RStudio
Version:               1.2.105 (1.2.105)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           RStudio [574]
User ID:               501

Date/Time:             2017-10-12 16:18:42.613 -0400
OS Version:            Mac OS X 10.12.6 (16G29)
Report Version:        12
Anonymous UUID:        F8B5B80E-7EBE-E268-6BAE-4656A98D45BF

Time Awake Since Boot: 44 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries
DYLD_VERSIONED_FRAMEWORK_PATH=/System/Library/StagedFrameworks/Safari

Dyld Error Message:
  Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /Applications/RStudio.app/Contents/MacOS/RStudio
  Reason: image not found

Binary Images:
       0x1096b6000 -        0x109936ffb +org.rstudio.RStudio (1.2.105 - 1.2.105) <1E190A18-BA43-3466-BFA7-090027E1DDC2> /Applications/RStudio.app/Contents/MacOS/RStudio
       0x109bc8000 -        0x109fcbffb  com.apple.WebKit (12604 - 12604.1.38.1.7) <1453D9AA-E604-3625-9181-D869808644D7> /System/Library/StagedFrameworks/Safari/WebKit.framework/Versions/A/WebKit
       0x119b59000 -        0x119b96dc7  dyld (433.5) <322C06B7-8878-311D-888C-C8FD2CA96FF3> /usr/lib/dyld
    0x7fff7fde1000 -     0x7fff80bbaff3  com.apple.AppKit (6.9 - 1504.83.101) <AE51ACB3-D501-3F91-B369-3D3711F24D0A> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff8316c000 -     0x7fff8316cfff  com.apple.CoreServices (775.19 - 775.19) <7255917D-EFBB-3BE2-A8FD-DAD631BC0949> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
    0x7fff872ec000 -     0x7fff872fafff  com.apple.opengl (14.0.16 - 14.0.16) <167C9883-A79E-3B7F-AFED-8CD6683B291D> /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
    0x7fff9650c000 -     0x7fff9650dffb  libSystem.B.dylib (1238.60.2) <F18AC1E7-C6F1-34B1-8069-BE571B3231D4> /usr/lib/libSystem.B.dylib
    0x7fff979ba000 -     0x7fff979cbff3  libz.1.dylib (67) <46E3FFA2-4328-327A-8D34-A03E20BFFB8E> /usr/lib/libz.1.dylib

Model: MacBookPro14,3, BootROM MBP143.0160.B02, 4 processors, Intel Core i7, 2.9 GHz, 16 GB, SMC 2.45f0
Graphics: kHW_IntelHDGraphics630Item, Intel HD Graphics 630, Built-In
Graphics: kHW_AMDRadeonPro560Item, Radeon Pro 560, PCIe, 4096 MB
Memory Module: BANK 0/DIMM0, 8 GB, LPDDR3, 2133 MHz, 0x80CE, 0x4B3445424533303445422D45474347202020
Memory Module: BANK 1/DIMM0, 8 GB, LPDDR3, 2133 MHz, 0x80CE, 0x4B3445424533303445422D45474347202020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x173), Broadcom BCM43xx 1.0 (7.21.171.130.1a1)
Bluetooth: Version 5.0.5f1, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB 3.0 Bus
USB Device: USB Receiver
USB Device: Keyboard Hub
USB Device: Apple Keyboard
USB Device: iBridge
USB Device: USB 2.0 BILLBOARD
Thunderbolt Bus: MacBook Pro, Apple Inc., 22.2
Thunderbolt Bus: MacBook Pro, Apple Inc., 22.2

**Comment by jmcphers** [comment]
I bet this is because the libssl on the Jenkins build slave is accidentally linked against a Homebrew copy, and no one on the dev team has noticed because we all have the libssl from Homebrew.

**Comment by jmcphers** [comment]
Looked into this a little more today, and was not delighted at the result.

RStudio 1.1 is built on an old version of MacOS that still has OpenSSL headers. 

In RStudio 1.2, we build on a much newer version of MacOS. This one doesn't have OpenSSL headers, so we have some compiler flags which cause us to link against the Homebrew version of OpenSSL if it exists.

https://github.com/rstudio/rstudio/blob/a791cdc8ac408b441818a89ddabcede219a87c91/src/cpp/core/CMakeLists.txt#L185-L203

However, linking RStudio against Homebrew OpenSSL makes RStudio unusable on systems which do not have Homebrew OpenSSL.

So, why does RStudio 1.1 work if the system doesn't have OpenSSL any more? The answer is that Apple didn't actually fully remove OpenSSL; they just keep shipping a very old version for compatibility that we appear to be picking up, in `/usr/lib/libssl.0.9.8.dylib`. 

Here are some of our options:

1. Break our OpenSSL dependency on OS X entirely by rewriting anything that uses OpenSSL to use Apple libraries. This is the path Apple wants us to take, obviously.

2. Try to keep building RStudio on a very old OS X release. We can't do this forever but it would buy us some time.

3. Make a copy of the old Apple OpenSSL headers and put them on the newer OS X builder, then tell it to link against the legacy `/usr/lib/libssl.0.9.8.dylib`. 

4. Link OpenSSL from Homebrew statically and/or ship it with RStudio.

**Comment by jmcphers** [comment]
Did a little more investigation here. The good news is that Apple's new bet is on LibreSSL, which is a fork of OpenSSL. Because it's not a totally new implementation, there's a healthy chance that we could use our existing code with little modification.

The bad news however is that LibreSSL is pretty new; it was released in 2015, and [first included in El Capitan](https://eclecticlight.co/2016/03/23/the-tls-mess-in-os-x-el-capitan/). Making RStudio depend on a system LibreSSL library on MacOS means locking out all MacOS releases prior to El Capitan, which is old but not *that* old.

So I think we're going to have to bundle OpenSSL to get out of this mess. This will allow us to use the same crypto code, unmodified, on all platforms. And what's more, we *already* bundle OpenSSL on Windows (starting in 1.1).

**Comment by jmcphers** [comment]
Some work in progress:

https://github.com/rstudio/rstudio/commit/2b041f6120f3dfa839a67cf2e554b2e552821987

This approach works by bundling the Homebrew version of OpenSSL, but it turns out that this is much more complicated than it appears. Bundling the libraries from `/usr/local/opt/openssl/lib/` still doesn't allow RStudio to boot, because those libraries have *further* dependencies on the specific OpenSSL version installed in the Cellar. We can choose to (a) try to bundle those, too, (b) build OpenSSL ourselves, or (b) try linking statically (would need to check the licenses to make sure this is okay).

**Comment by ronblum** [comment]
Verified! With v1.2.197 on MacOS.
