### ISSUE TITLE
Qt build script fails to set RUNPATH on Qt shared objects

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#1610]
Here:

https://github.com/jmcphers/qt-gst10/blob/master/Dockerfile.x86_64#L77-L78

The invocation fails because `chrpath -r` attempts to replace an existing RUNPATH. This fails if no RUNPATH exists on the object, which is true for these shared objects.

Using `patchelf --set-rpath '$ORIGIN'` would likely work here (it creates a RUNPATH entry if none exists beforehand).

On Ubuntu 17.04 at least, this implies that executables which recursively depend on these libraries will fail to be resolved; e.g. `uic` depends on `libQt5Core.so` which depends on `libicui18n.so`. However, without a RUNPATH (even though those objects live in the same directory), `libQt5Core.so` will fail to discover `libicui18n.so`, and so transitively `uic` fails to see it as well. (It seems that shared objects no longer automatically discover dependent libraries that live in the same directory?)

**Comment by jmcphers** [comment]
@kevinushey Do you know whether this has caused any trouble other than building RStudio from source on Ubuntu 17?

The existing `RPATH` code seems to do the right thing, in that it makes everything work at least at run and compile time on Ubuntu 16, and must be doing *something* (because without it it demonstrably doesn't run on 16). I'll try with `patchelf` to see if that makes things better on 17, too.

**Comment by kevinushey** [comment]
Thus far it seems like this may be an Ubuntu 17.04-only issue, but I wonder if it could have been related to some of the issues you saw where launching a new session from RStudio could fail on Ubuntu desktop?

Either way, we have a workaround for that so fixing this may not be very high priority.

**Comment by jmcphers** [comment]
We've had no reports of the built version of 1.1 failing on 17.04 (and several that it works fine) so for now this is a build-time issue. Maybe even specific to `uic`?

Re: new session -- it could indeed be related. It looks like `RPATH` takes precedence over `LD_LIBRARY_PATH`, but `RUNPATH` doesn't, and the problem observed in that case was caused by system Qt 5 libraries in `LD_LIBRARY_PATH` taking precedence over the paths baked into the binaries.

**Comment by jmcphers** [comment]
FWIW, `RPATH` is deprecated in favor of `RUNPATH`, so going forward we should just plan on `LD_LIBRARY_PATH` trumping everything (the fix we made for new sessions on Ubuntu 16+ involves replaying the `LD_LIBRARY_PATH` that successfully launched the initial copy of RStudio).

http://man7.org/linux/man-pages/man8/ld.so.8.html

**Comment by kevinushey** [comment]
The problem I see on Ubuntu 16.04 is that our `uic` executable actually ends up linking to the system Qt libraries:

```
kevin@KBOX:~/Qt5.4.2/5.4/gcc_64/bin
$ ldd uic
	linux-vdso.so.1 =>  (0x00007ffc7bba9000)
	libQt5Core.so.5 => /home/kevin/Qt5.4.2/5.4/gcc_64/bin/./../lib/libQt5Core.so.5 (0x00007fdebd692000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fdebd310000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fdebcf46000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fdebcd29000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fdebcb0f000)
	libicui18n.so.55 => /usr/lib/x86_64-linux-gnu/libicui18n.so.55 (0x00007fdebc6ad000) <--
	libicuuc.so.55 => /usr/lib/x86_64-linux-gnu/libicuuc.so.55 (0x00007fdebc319000) <--
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fdebc115000)
	libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007fdebbe04000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fdebbbfc000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fdebb8f3000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fdebb6dd000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fdebdbdb000)
	libicudata.so.55 => /usr/lib/x86_64-linux-gnu/libicudata.so.55 (0x00007fdeb9c26000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007fdeb99b6000)
```

**Comment by jmcphers** [comment]
We no longer build Qt from source ourselves, so that entire project (and this conversation) is no longer relevant as I'm reading it. Feel free to reopen if you feel this isn't accurate!
