### ISSUE TITLE
Need a way to abort session recovery in RStudio Server

### ISSUE THREAD

**Issue by renkun-ken** [rstudio/rstudio#1633]
Sometimes I'm working on a huge workspace which takes forever to save to disk and recover from disk. If I forget to cleanup, after a night the workspace is saved to disk so that the memory is freed. Whenever I continue the session, it will automatically attempt to recover from disk. When the workspace is huge and I want a new session in a hurry, I can't immediately get to a fresh new session even I run `rstudio-server kill-all`. That is, I don't have a decent way to abandon the previous session unless I disable session timeout (which is not ok because the server needs much memory in the morning for production), or delete files `~/.rstudio/sessions/acitve`. 

I'm wondering if RStudio Server can check the size of the workspace and prompt if it's too big before restoring it so that I can choose to abandon it?

**Comment by shapenaji** [comment]
I have the same issue, I would really like to turn off saving the workspace by default for all of my users. The only time they even notice the workspace is when I have to go in and delete the .RData file.

On a possibly related note, CTRL+SHIFT+F10 not giving me a clean workspace and attempting to reload packages and data is a bit of a pet peeve.

**Comment by raubreywhite** [comment]
Agreed

**Comment by RobinL** [comment]
This causes us lots of problems too - essentially placing an upper limit on the amount of memory we can give to our users, because the more we give them, the longer rstudio hangs for when they return to it.    I end up suggesting they use R in Jupyter where they are using loads of memory.

(Our setup is dockerised R Studio running in Kubernetes. )

**Comment by jmcphers** [comment]
Also tracked in https://github.com/rstudio/rstudio/issues/3013.

**Comment by jmcphers** [comment]
I have an exploratory branch which adds an abort button that bails out of the session recovery and resumes it in "safe mode" (doesn't load .Rdata or .Rprofile).

https://github.com/rstudio/rstudio/tree/feature/safe-mode-reload

It basically works by sending a few extra params during `client_init` that signal that a session started from that init request should not load .Rdata or .Rprofile. We should tie these params to the querystring so that it's possible to force a safe-mode reload in the initial request (or from an external system like rstudio.clooud). 

However, this branch has a couple of bugs that would need to get worked out before we can merge it, and isn't likely to land for 1.2 unless they turn out to be shallow.

**Comment by jmcphers** [comment]
Implemented in https://github.com/rstudio/rstudio/pull/4338 for RStudio 1.3.

**Comment by sciencepeak** [comment]
> Second this issue. RStudio will choke and die on reloading sessions that have more than maybe 5-10GB of memory. The session times out mid-way through reloading an existing RStudio session, and the user is effectively locked out until you delete `~/.rstudio`.
> 
> If you know about this limitation and can work around it, fine - but if there are a lot of users that don't know RStudio can't handle large amounts of memory, the only way to prevent them from constantly locking themselves out of their sessions is to set memory limits, which is not really a great option.
> 
> I think workspaces larger than say 4GB should not be saved to disk, ever. Or the session saving mechanism needs to be reworked so that RStudio can successfully reload large sessions quickly.

I use Rstudio server and encounter the same issue in 2023. The Rstudio server keeps loading the previous session in vain.

The error message from `sudo rstudio-server status` is `ERROR The previous R session terminated abnormally; LOGGED FROM: rstudio::core::Error {anonymous}::rInit(const rstudio::r::session::RInitInfo&)`

I tried many ways including rebooting the operating system, installing new Rstudio server, wating for safe mode, killing rsessions using `sudo rstudio-server kill-all`, adding `?restore_workspace=0` to the hyperlink that are input in the web browser to access the Rstudio server, deleting or renaming the project folder and files therein, trying to find all the folders and files related to the Rstudio server, removing `~/.rstudio` etc., however, all these approaches don't work.

When I access the Rstudio server via a web browser, the Rstudio server keeps creating the project folder and file structure that I have deleted or renamed. So the key of issue is that the Rstudio server can not forget the previous session. In other words, where does Rstudio server record the user session information? ChatGPT suggested several directories that are completely wrong. Then I use Google to search and find the answer [here]([Resetting a user&#39;s state on Posit/RStudio Workbench / Rstudio server &ndash; Posit Support](https://support.posit.co/hc/en-us/articles/218730228-Resetting-a-user-s-state-on-Posit-RStudio-Workbench-RStudio-Server)).

| Location | Information stored |
| --- | --- |
| `~/.config/rstudio/` | All user settings (Global Options) |
| `~/.local/share/rstudio/` | All open files and tabs, as well as active and suspended sessions. |

In the older Rstudio server versions the user session information is stored in `~/.rstudio`, whereas in the later Rstudio server versions, we need to delete or rename the `~/.local/share/rstudio/` to get rid of the previous rsessions.

**Comment by bastianolea** [comment]
Can confirm that deleting `~/.local/share/rstudio/` solves RStudio Server being stuck on relaunch due to a stuck session. Thanks @sciencepeak! Deleting the folder and restarting RStudio Server (`sudo systemctl restart rstudio-server`) allows RStudio to launch into a clean session, unstuck by previous issues. In my case, the issue that made the IDE get stuck, unresponsive and therefore impossible to quit/restart or launch a new session, was simply having a console trying to output great amounts of text (in my case, unknowingly printing a `stm` model). I believe the IDE should not be expected to crash under these circumstances, or at least, the IDE should be able to recover from the innocent fact of a user printing a big object on the console (and in fact the console does cut out printing of large vectors and data frame, but not lists), without forcing the user having to manually remove folders in order to continue working.
