### ISSUE TITLE
Allow RStudio installer to install without admin privilges

### ISSUE THREAD

**Issue by renejuan** [rstudio/rstudio#1634]
I think this will be a nice enhancement especially for users in enterprise environment. It will be nice to be able to install RStudio using user privileges. Currently this is possible by downloading the zip for windows and copying but the installer requires admin privileges. I would like to see this enhancement.

**Comment by renejuan** [comment]
I think will be good to allow multiple versions of RStudio to be installed at the same time. A few things to consider as part of this enhancement:
1. Will `AppData\Local\RStudio-Desktop` interfere between versions?
2. The version number does not seem to be reported to WIndows (Control Panel Add/Remove Programs).

**Comment by jmcphers** [comment]
It would be nice, but there's been no additional interest for a couple of years and it's unlikely we'll have time to work on it in the next year, so closing. The zipfile is the best choice for installing without privileges, and most of the additional work done by the installer would require privileges anyway.

**Comment by lejeczek** [comment]
My vote goes to this. In enterprise of any kind(colleges, universities, etc.) all the users I'm sure would welcome this with a big 'thanks'. All these users have had their 'Rs' installed without admin privileges and must wonder why RStudio can't do the same.
Thanks.

**Comment by CrimsonVex** [comment]
It's insane that you can't install RStudio without admin privileges. I work in a hospital; of course IT won't give us admin rights. I can install R with no issues though...

**Comment by gtritchie** [comment]
For what it's worth, you can download and use RStudio without admin privileges on Windows, with some caveats.

Download and extract the installer-less / zip-file package, and extract it wherever you want. Double-click on rstudio.exe to run it.

You will have to create a shortcut if you want one, and you won't have file associations (e.g. making it so double-clicking a .R file in Explorer opens it in RStudio). It also, of course, won't appear in Add/Remove programs since it's not installed in that sense.

On https://posit.co/download/rstudio-desktop/  scroll down to this section:

<img width="1183" alt="Screenshot 2023-01-28 at 12 43 42" src="https://user-images.githubusercontent.com/10569626/215287710-ef44351a-cc9a-48fd-8823-e0d5ba022a53.png">

**Comment by gtritchie** [comment]
Note to self: an example of a per-user installer script for NSIS: https://github.com/kichik/nsis/blob/master/Examples/install-per-user.nsi

**Comment by swiderskiji** [comment]
> For what it's worth, you can download and use RStudio without admin privileges on Windows, with some caveats.
> 
> Download and extract the installer-less / zip-file package, and extract it wherever you want. Double-click on rstudio.exe to run it.
> 
> You will have to create a shortcut if you want one, and you won't have file associations (e.g. making it so double-clicking a .R file in Explorer opens it in RStudio). It also, of course, won't appear in Add/Remove programs since it's not installed in that sense.
> 
> On https://posit.co/download/rstudio-desktop/ scroll down to this section:
> 
> <img alt="Screenshot 2023-01-28 at 12 43 42" width="1183" src="https://user-images.githubusercontent.com/10569626/215287710-ef44351a-cc9a-48fd-8823-e0d5ba022a53.png">

since there are people and environments where this will continue to be necessary every time RStudio updates--which is not infrequently, though perhaps not quite frequently enough for folks (ok, me) to remember each time how to do it without significant frustration--perhaps some note should be added to the download page that if you don't have admin rights on your machine, you can still use RStudio but you'll have to _do it this way_...

Currently there's a reference to using Posit Cloud if you "don't want to download or install anything", but that's not the situation -- I _do_ want to install something, I just _can't_ do anything that requires admin privileges.  There is, I eventually determine, a way around it, but it'd be nice not having to hunt for it every six to eight months or whenever an update drops.
