### ISSUE TITLE
Allow rserver to listen on a unix domain socket

### ISSUE THREAD

**Issue by nathanweeks** [rstudio/rstudio#1635]
Currently, rserver listens on the TCP port specified by the --www-port option-argument. It would be helpful if rserver also had the ability to listen on a unix domain socket. This could facilitate secure connections via SSH unix domain socket forwarding---probably with a TCP port on the client side---e.g., to a to a containerized rserver instance started by a user on a multi-tenant server.

**Comment by jmcphers** [comment]
This is a feature of RStudio Server Pro; it always listens on a Unix domain socket (the TCP connections are forwarded there by a bundled copy of nginx).

**Comment by nathanweeks** [comment]
Thanks, @jmcphers . Does RStudio Server Pro have the ability to:
1. Listen & accept connections _only_ on a Unix domain socket (without nginx listening on a TCP port), and if so
2. Have a command-line option that allows the pathname of the unix domain socket to be specified?

**Comment by jmcphers** [comment]
1. Not elegantly, but yes. You can disable the built-in nginx binary.
2. No, it's always in the same place: `/tmp/rstudio-rserver/rserver.socket/`

**Comment by yuvipanda** [comment]
Heya! I'd love to have this feature in the open source version - mostly to make it easier to work on mybinder.org & similar setups. Any chance this can be moved to the open source version? Would very much appreciate that :)

**Comment by PromyLOPh** [comment]
I’m also interested in this feature. Currently I’m using a custom patch to achieve this (see https://github.com/leibniz-psychology/guix-zpid/blob/master/rstudio-server-1.2.5033-listen-socket.patch), but it’s a PITA, because there’s so many places that “do some network stuff” and it’ll probably break TCP-based access. Also the websocket-based terminal server needs to be disabled (see https://github.com/leibniz-psychology/guix-zpid/issues/8), because it cannot operate over the same socket.

**Comment by nathanweeks** [comment]
Still interested...

**Comment by mbreese** [comment]
So, it's not as good as a built-in option, but *if* you are working with a dockerized (or Singularity) workflow, you might be able to add a front-end nginx proxy that listens to a unix socket that is bind mounted to outside the container.

This would basically be the reverse of what RStudio Server Pro is apparently doing (nginx tcp port -> rstudio unix).

It is possible that this could keep the TCP port open only within the container and only expose the RStudio instance with the proxied unix socket.

I've only briefly tested this, but it might work (because I'm looking to do something similar).

**Comment by PromyLOPh** [comment]
We’re still using this custom patch: https://github.com/leibniz-psychology/guix-zpid/blob/master/rstudio-server-1.3-rserver-socket.patch

**Comment by yuvipanda** [comment]
If you're running JupyterHub in containerized spaces, you can also use https://github.com/jupyterhub/jupyter-rsession-proxy/

**Comment by nathanweeks** [comment]
> So, it's not as good as a built-in option, but _if_ you are working with a dockerized (or Singularity) workflow, you might be able to add a front-end nginx proxy that listens to a unix socket that is bind mounted to outside the container. Something like:
> 
> nginx unix -> rstudio tcp/8787
> 
> This would basically be the reverse of what RStudio Server Pro is apparently doing (nginx tcp port -> rstudio unix).
> 
> It is possible that this could keep the TCP port open only within the container and only expose the RStudio instance with the proxied unix socket.
> 
> I've only briefly tested this, but it might work (because I'm looking to do something similar).

That's an interesting idea. I'd be particularly interested in seeing a Singularity example using a rocker/rstudio base image with nginx added.

**Comment by jhgoebbert** [comment]
You might want to check this PR https://github.com/rstudio/rstudio/pull/14938

**Comment by jhgoebbert** [comment]
The PR for unix-socket support in RStudio is now merged and will be part of the official "Kousa Dogwood" builds expected in 2024.10 : https://github.com/rstudio/rstudio/pull/14938#issuecomment-2243950205

@nathanweeks I think this issue can be closed now
