### ISSUE TITLE
Don't scroll down in console when switching to RStudio

### ISSUE THREAD

**Issue by wch** [rstudio/rstudio#1638]
If the console is the active pane, then I scroll up in the console, switch to another application, and then switch back to RStudio, it automatically scrolls down to the bottom of the console. This behavior is unhelpful -- in most cases, when someone scrolls up in the console, it's because they want to look at some previous output, and having it scroll away automatically is disruptive for that.

**Comment by jmcphers** [comment]
I think this is just default browser behavior: when an element receives focus, it is automatically scrolled into view. Switching away from RStudio causes the console input line to lose focus; when you switch back, it regains focus and consequently gets scrolled so you can see it.

I'm not sure we can change this--maybe we could remember the position of the console scrollbar when app window is blurred, and restore it when reactivated.

**Comment by dfalty** [comment]
Got another vote from @jspiewak on this. This was reproducible on RSP 1.2.747-3 with Chrome.

**Comment by MariaSemple** [comment]
@wch Confirmed this is still an issue.

**Comment by mikebessuille** [comment]
The result is unfortunate.  The impact of fixing this is outweighed by the effort in this case.

**Comment by ReinoWCC** [comment]
This has been frustrating for my R team on a regular basis for a few years now.  We often take screenshots or take rolling captures of console outputs because we are working quickly collaboratively.  We are also going back and forth with the output and checking numbers in documents or spreadsheets online. If we need to adjust the Rstudio console to scroll back, it will automatically snap to the bottom again if we had clicked away at all.  We are the tip of the iceberg. I have talked to a number of R users who don't like this behavior.  My suggestion would be to have it snap to the bottom when something is entered in console, or if the home key is pressed.

**Comment by ProfFancyPants** [comment]
This has been frustrating for my R team on a regular basis for a few years now. We often take screenshots or take rolling captures of console outputs because we are working quickly collaboratively. We are also going back and forth with the output and checking numbers in documents or spreadsheets online. If we need to adjust the Rstudio console to scroll back, it will automatically snap to the bottom again if we had clicked away at all. We are the tip of the iceberg. I have talked to a number of R users who don't like this behavior. My suggestion would be to have it snap to the bottom when something is entered in console, or if the home key is pressed.

**Comment by kevinushey** [comment]
I don't think this is a browser-specific behavior; it seems like an issue with how we handle focus events in the Console pane.

More specifically, to reproduce:

1. Ensure the console input line is focused,
2. Scroll up in the console history,
3. Click away from RStudio into a separate application,
4. Return focus to RStudio.

Because the console input was the last-focused item, we try to bring it back into view on focus here:

https://github.com/rstudio/rstudio/blob/824afaba8ebf47ea52816b51d5c9688aff88dd87/src/gwt/src/org/rstudio/studio/client/common/shell/ShellWidget.java#L119

You'll note the issue doesn't occur if you change focus in the IDE to a separate pane; e.g. if you scroll the console history, click into the Source pane, and then try switching focus.

**Comment by jonvanausdeln** [comment]
Verified on 2022.12.0-daily+270
Ubuntu 22.04 server (Windows Chrome browser & Chrome on Ubuntu) and Windows 11 desktop

Console windows stayed in position after switching to various windows, minimizing, and locking screen.
