### ISSUE TITLE
Allow customization of log directories

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#1678]
Many RStudio users (open source and pro) have requested a way to change where RStudio Server writes its log files.

This includes:

- session logs
- server logs (i.e. what we send to the system logs today)
- monitor logs (in Pro)

Log output could go to:

- system logging facility
- a file descriptor (stdout/stderr)
- a specific log file

**Comment by OssiLehtinen** [comment]
Dear jmcphers,

just to highlight a reason why the ability to adjust where the logs are written would be excellent:

The thing is, every time something crashes in Rstudio server (which is quite often when doing development with unstable packages or what not), an error message gets written in the /var/log/messages.

Since our server is hosted by a third party, they proceed to report these errors back to us (and charge for their services, don't ask why we can't ask them not to do that...).

Forcing everything to sys messages seems a bit 'intrusive', and avoiding such behavior would go a long way for us!

Thanks for your efforts on the over all nice tool!
Ossi

**Comment by jmcphers** [comment]
Implemented in https://github.com/rstudio/rstudio/commit/467f0704ea7a35d7a1149317de592c9f94b1d202.
