### ISSUE TITLE
Load All shortcut doesn't work when Terminal is open

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#1723]
Repro:

1. Create or open a Package project
2. Put the cursor in the R console
3.  Press `Ctrl + Shift + L`; this is a shortcut for Load All and should emit `devtools::load_all(".")` to the console
4. Open the Terminal and type a command
5. Put the cursor back in the R console
6. Press `Ctrl + Shift + L` again

Nothing happens. 

Originally reported here: https://community.rstudio.com/t/bug-report-ctrl-shift-l-stops-working/1999

**Comment by gtritchie** [comment]
This is because there is a `Ctrl+Shift+L` shortcut for the Clear Terminal Buffer command (left over from before I made Ctrl+L clear the Terminal instead of the Console depending on focus).

So as soon as there's a terminal instance, Ctrl+Shift+L starts being routed to it, even when it isn't visible.

I think I should remove this shortcut altogether, since Ctrl+L already does the trick.

In the meantime, users can modify the keyboard shortcut and remove it themselves. Tools / Modify Keyboard Shortcuts, type `clear terminal` in the filter, double-click on the `Shift + Ctrl + L`, delete it, and Apply.

![2017-11-07_21-37-52](https://user-images.githubusercontent.com/10569626/32533269-99838e48-c404-11e7-869a-cbd163e25e2f.png)

**Comment by jcpayne** [comment]
@gtritchie's fix worked for me, but I had to restart RStudio before the change took effect.

**Comment by ronblum** [comment]
Verified in RStudio server and desktop v1.1.393.
