### ISSUE TITLE
Multilevel dictinory in YAML metadata not allowed

### ISSUE THREAD

**Issue by r-cheologist** [rstudio/rstudio#1752]
As discussed [here](https://stackoverflow.com/q/47284942), the following works with `bookdown`/`rmarkdown`/`knitr` through `RStudio`:

    ---
    params:
      first_level: ~
    ---
    
    ```{r}
    params
    ```

and produces

    ## $first_level
    ## NULL

This, however:

    ---
    params:
      first_level:
        second_level: ~
    ---
    
    ```{r}
    params
    ```

Is expected to give:

    ## $first_level
    ## $first_level$second_level
    ## NULL

but results in `Error: no value field specified for YAML parameter 'first_level'
Execution halted`.

@yihui informs me (at above link) that plain `rmarkdown::render`ing actually produces the expected, so there's likely an `RStudio` bug involved.

**Comment by jmcphers** [comment]
I think this bug is actually in `rmarkdown`. That's where the error is coming from, and `rmarkdown::render` shows the error `Error: no value field specified for YAML parameter 'first_level' Execution halted` for me, even when run at the command line outside RStudio.

@yihui can you confirm that plain `rmarkdown::render` works for you? If so, what versions of knitr/rmarkdown are you using?

**Comment by yihui** [comment]
Sorry, I don't know what happened when I tried this example a few days ago, but I tried it again today, and it seems to be an issue in **rmarkdown** indeed. I'll try to fix it there.

**Comment by yihui** [comment]
After I thought about it more carefully, I'd say this is by design, and will not be changed: https://stackoverflow.com/a/47373541/559676

I think this issue can be closed.

**Comment by jmcphers** [comment]
Okay, great. Thanks, @yihui.
