### ISSUE TITLE
Enhancement: Cursor placement when inserting .Rmd code chunks

### ISSUE THREAD

**Issue by pkq** [rstudio/rstudio#1782]
Currently, when you insert an R, Bash, Python, or Rcpp code chunk, RStudio places the cursor inside the chunk. However, the first thing I usually want to do after inserting a chunk is to name it. What do you think about having RStudio place the cursor inside the chunk definition instead (with a space after the chunk type), similar to the current behavior for SQL and Stan chunks? Admittedly, it's not that difficult to move the cursor, but I think this approach would encourage more folks to adopt what generally seems to be considered [best practice](http://kbroman.org/knitr_knutshell/pages/Rmarkdown.html), and possibly even cut down on the [unnamed-chunk](https://twitter.com/JennyBryan/status/739133331036479488) issue. Thoughts?

**Comment by jmcphers** [comment]
For users just starting out I think it's more important that the cursor lands somewhere that they can begin to type code right away. It'd be unquestionably better if people named all their chunks, but in my view making this the default would be frustrating to the many people for whom naming chunks isn't important.

If you just want this for your own convenience, you might consider using the `r` snippet instead of the Insert chunk command. This snippet is designed for users who want to be more intentional about filling out the chunk details, and lets you tab quickly from the chunk's label to its options and then its body.

![image](https://user-images.githubusercontent.com/470418/33582279-510a9958-d909-11e7-8564-237331d19ac7.png)

Feel free to open a thread on our community forum if you'd like to discuss this further!

https://community.rstudio.com/c/rstudio-ide

**Comment by pkq** [comment]
Makes sense. Thanks for the tip about the `r` snippet! I had somehow missed that the markdown versions existed, and that solves this use case nicely. Much appreciated!
