### ISSUE TITLE
Bug: Overwriting `<-` leads to errors in RStudio

### ISSUE THREAD

**Issue by klmr** [rstudio/rstudio#1816]
## To reproduce:

1. Open a clean RStudio
2. Create a new file
3. Enter the following code:

     ```r
     `<-` = function (...) stop('nope')
     ```
4. Execute that code 
5. Save the file

## Observable result:

Error messages start appearing in the R console. They seem to be triggered by certain user interactions (such as saving, see step 5). The message is:

> Error in fullName <- paste(".rs.", name, sep = "") : nope

Debugging shows that the reason is that the user-defined `<-` is somehow leaked into the scope of RStudio utility functions (in particular, `.rs.getVar`).

This bug occurs in actual usage since I am overriding `<-` (more meaningfully than above). A similar error occurs when overriding other functions used by these utility functions (such as `paste`, …).

RStudio 1.1.383.

<details><summary>Session info</summary>

```
> sessionInfo()
R version 3.4.2 (2017-09-28)
Platform: x86_64-apple-darwin16.7.0 (64-bit)
Running under: macOS Sierra 10.12.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLAPACK.dylib

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] compiler_3.4.2 R6_2.2.2       magrittr_1.5   tools_3.4.2    yaml_2.1.14   
 [6] roxygen2_6.0.1 Rcpp_0.12.13   xml2_1.1.1     stringi_1.1.6  stringr_1.2.0 
[11] commonmark_1.4
```

</details>

**Comment by kevinushey** [comment]
I think at least one instance of this issue is being triggered here:

https://github.com/rstudio/rstudio/blob/560aeb25f6634b3187082280e192d595ebc047be/src/cpp/session/modules/SessionDiagnostics.cpp#L368

The overarching issue, however, is that our `RFunction` class evaluates our utility functions in the global environment by default, e.g.:

https://github.com/rstudio/rstudio/blob/560aeb25f6634b3187082280e192d595ebc047be/src/cpp/r/RExec.cpp#L365-L368

https://github.com/rstudio/rstudio/blob/560aeb25f6634b3187082280e192d595ebc047be/src/cpp/r/RExec.cpp#L353-L356

We should re-evaluate whether we truly want these to evaluate in the global environment, or within the `tools:rstudio` environment. (Note that the `tools:rstudio` is still not truly isolated; since it's on the search path it also has access to any other attached packages following it on the search path. But screening out the global environment seems like the right decision regardless.)

**Comment by jmcphers** [comment]
It'd be nice to make this better, but I think this falls under the category of things we are not likely to improve soon (especially since overriding operators in this way is not common).

**Comment by klmr** [comment]
Shame. Unfortunately this is a blocking issue for me since I commonly *do* redefine this operator.
