### ISSUE TITLE
Rstudio runs system instead the engine function in notebook format

### ISSUE THREAD

**Issue by devereaux** [rstudio/rstudio#1822]
The following minimal reproducible example should unconditionally output 'hello world', regardless of the chunk content, for a newly defined m engine

```{r}
eng_dummy_m= function (options) 
{
  knitr::engine_output(options, options$code, "hello world\n")
}

knitr::knit_engines$set(m=eng_dummy_m)
```

It works differently in Rstudio notebook and a knitted file:
```{m}
looks like it expects some bash:
 it returns '/bin/sh: 1: m: not found' in a rstudio notebook,
 it returns  '## hello world' if knitted
```

This impacts custom engines by creating inconstant behaviors. For example, it is not possible to reproduce the example from https://codedump.io/share/z3JfmwzdQBKw/1/changing-the-prompt-in-a-multilanguage-knitrrmarkdown-document or http://datadrivensecurity.info/blog/posts/2015/Jun/running-other-languages-in-r-markdown-files/ in a notebook.

I would recommend adding a hook to knitr so that "hello world" can be returned in a notebook after defining some code, to address https://support.rstudio.com/hc/en-us/community/posts/115008946228-knitr-language-engines-not-working-in-windows -- I would also add support for asis so that "<b>hello world</b>" can be shown in bold

I would recommend fixing rstudio so that arbitrary strings are not executed with system() when defining a custom engine, to address https://stackoverflow.com/questions/46895260/how-do-i-stop-knitr-from-trying-to-call-system-on-my-engine

**Comment by kevinushey** [comment]
If I understand correctly, this is an MRE for the problem you describe:

````
```{r}
eng_dummy <- function(options) {
    knitr::engine_output(options, options$code, "hello world\n")
}
knitr::knit_engines$set(dummy = eng_dummy)
```

```{dummy echo=FALSE}
# This is ignored!
```
````

Knitting this produces the text `## hello world` for the `dummy` chunk, but attempting to run it within a Notebook context prints

    /bin/sh: dummy: command not found

The code that needs to change lives here:

https://github.com/rstudio/rstudio/blob/a38dbdc6510a8cf007350d4dcd5ccd1afb315147/src/cpp/session/modules/rmarkdown/NotebookAlternateEngines.cpp#L482-L491

Rather than applying that logic to all kinds of engine chunks, we should restrict it to the default engine implementations that are known to be associated with an interpreter.

**Comment by kevinushey** [comment]
https://github.com/rstudio/rstudio/commit/f46d4b7e43fcb66ecac364df0d7629458737719a

This commit adds support for engines that produce output through `knitr::engine_output()`; more work is forthcoming for engines that produce arbitrary `evaluate()`-style output (as `reticulate::eng_python()` does).

**Comment by devereaux** [comment]
Thanks @kevinushey! For the upcoming fixes, may you please also support asis style?

The use case is a custom engine that produces HTML code or an image that could be inlined.

**Comment by jmcphers** [comment]
This works now that we have support for knitr custom engines.

![image](https://user-images.githubusercontent.com/470418/69682060-12b7d400-1065-11ea-9305-42d213fc3263.png)
