### ISSUE TITLE
ODBC connection disappears after updating package, installing unixodbc libraries

### ISSUE THREAD

**Issue by pbhogale** [rstudio/rstudio#1832]
(Rstudio 1.1)
I accessed the new connections connections pane and it showed spark and ODBC. When I clicked on ODBC, it asked me to update the odbc package. To be on the safe side, I re-installed unixodbc (with sudo apt-get on linux and brew on MacOS), updated the odbc package successfully.

However, both on MacOS and Linux Mint, the odbc option in new connections disappeared. 

re-installs and re-booting have not helped.

**Comment by ronblum** [comment]
Hi pbiogale,
This is the expected behavior—you’re on the right track. The next step is to install your ODBC driver. Once you’ve set it up, it should be referenced in the drivers file—on Linux, it’s typically `/etc/odbcinst.ini`, but you can use the command `odbc -j` to check its location. RStudio will recognize the driver in `odbcinst.ini` and make it available in the “Connections” tab.
