### ISSUE TITLE
Stop code completion after pipe is inserted via keyboard shortcut

### ISSUE THREAD

**Issue by etienne-s** [rstudio/rstudio#1834]
Inserting `%>%` with <kbd>Ctrl</kbd><kbd>Shift</kbd><kbd>M</kbd> should stop the code completion tool. Currently when I want to type something like:

```r
iris %>% 
  group_by(Species) %>% 
  summarise(m = mean(Sepal.Length))
```

after inserting the first pipe RStudio displays code completions for `iris`, which:
1. makes no sense
2. is slightly annoying since it is then necessary to press <kbd>Esc</kbd> before being able to insert a new line with <kbd>Enter</kbd>.

![code_completion_rstudio](https://user-images.githubusercontent.com/22758616/33807963-ea65f8c0-ddde-11e7-9519-8879f390a980.png)

**Comment by ronblum** [comment]
Code completion goes away once an object name is chosen. However, if the object begin with the same letters, code completion doesn’t go away until the two are disambiguated. In the case of `iris` and `iris3`, the difference isn’t made until the _3_ is typed, so if we just type `iris`, the pop-up stays up. It’s overstaying its welcome, though, because typing a space after the name—`iris `—doesn’t make it go away, even though this makes the choice clear. Only clicking on one of the options or typing a non-space character, like a letter or _%_, does so. 

Typing <kbd>Ctrl</kbd><kbd>Shift</kbd><kbd>M</kbd> isn’t getting treated as a character getting typed, so the code completion remains. So really, there are two issues:
1. <kbd>Ctrl</kbd><kbd>Shift</kbd><kbd>M</kbd> and <kbd>Cmd</kbd><kbd>Shift</kbd><kbd>M</kbd> should make the code completion go away, just like typing _%_ does.
2. Typing a space should make it go away, too.
