### ISSUE TITLE
Mysterious increase of reference count in R studio

### ISSUE THREAD

**Issue by Ttonyy** [rstudio/rstudio#1842]
I think there is a potential bug for the “Environment” panel (or somewhere else) in R studio.

Basically, it seems that when running in R studio, the GUI itself adds a reference count on the variable created.
 
You can see the following code, when the new matrix created, it should have reference count 1 throughout. This is indeed the case when you run code in a block. Also, as you can see, the function refs itself does not add reference count. 

However, after the block is finished, rerun refs() function will return 2 (see highlighted line in the graph below).

![capture](https://user-images.githubusercontent.com/34490551/33907942-f2d3c4d0-dfda-11e7-8061-a9ce338b0428.JPG)
 
Doing the same process in the native R (without any GUI) consistently return 1 regardless whether run by block or line-by-line.

Note: I notice the problem existence because the RAM usage was showing duplication when an entry of matrix x is changing. function refs() was an after thought and does not cause the problem.

**Comment by jmcphers** [comment]
Here are a couple of things to try:

1. RStudio's environment pane usually uses `str(x)` to generate its display. If you run `str(x)` before the last line outside RStudio, does it bump the ref count?

2. In RStudio 1.2, you can disable the environment pane refresh if you believe it's interfering. Does that make the behavior go away for you?

![image](https://user-images.githubusercontent.com/470418/33908347-f80b4f70-df3c-11e7-860d-dad042a8bf7b.png)

**Comment by Ttonyy** [comment]
Thank you @jmcphers 

I can confirm that str(x) does increase reference count. (a bit unexpected to be honest, not sure whether that is intentional)

At the moment, I have not yet installed Rstudio 1.2, since the compiled version is not yet listed. Will try that later.

**Comment by jmcphers** [comment]
I don't think `str()` increases the reference count intentionally, but it is a well known side effect for many object types. There's no need to try 1.2 now; as RStudio uses `str()` to build the environment pane it's virtually certain that's the source of the ref.

In a future version of RStudio we're hoping to reduce or eliminate our use of `str()` due to this and other issues; one of the other main issues is that `str()` hangs and crashes on some object types. To get around this we'll probably do object introspection from the C side of things (a la https://github.com/hadley/lobstr), but for now there's nothing we can do since we depend on `str()`.

Appreciate the report!
