### ISSUE TITLE
Feature request: customize location of .rstudio directory

### ISSUE THREAD

**Issue by pyltime** [rstudio/rstudio#1846]
Requested by a few customers and written up in our old ticket system as case 5379 - users would like to be able to customize the location of the .rstudio directory currently placed in users' home directories. This is especially important for people with quotas on their home directories.

See support tickets 15520, 15843, 20209

**Comment by jmcphers** [comment]
For anyone arriving at this issue because they're trying to find a way to customize the .rstudio directory in existing versions of RStudio, see this support article for a writeup of some things you can do today to help reduce disk space pressure on RStudio Server user home directories:

https://support.rstudio.com/hc/en-us/articles/218417097-Filling-up-the-home-directory-with-RStudio-Server

We've looked at doing this in the past; see https://github.com/rstudio/rstudio/pull/825 for some discussion of the tradeoffs involved.

**Comment by ncalies** [comment]
We have another customer that would benefit from this change - #32502

**Comment by jmcphers** [comment]
See also https://github.com/rstudio/rstudio/issues/1607 for moving preferences (not storage) out of `~/.rstudio`.

**Comment by jmcphers** [comment]
Another customer request in #46349.

**Comment by jmcphers** [comment]
Fixed in https://github.com/rstudio/rstudio-pro/pull/1602
