### ISSUE TITLE
Open file from terminal within RStudio

### ISSUE THREAD

**Issue by nuest** [rstudio/rstudio#1850]
I like the new terminal integration in RStudio. It would be even better if I could open files from it. Right now I get an error:

```bash
$ rstudio DESCRIPTION
rstudio: symbol lookup error: /usr/lib/x86_64-linux-gnu/libQt5Sql.so.5: undefined symbol: _ZNK19QAbstractTableModel7siblingEiiRK11QModelIndex
```

The command works when called from an external terminal, it also does open it in the same RStudio window. _Am I doing something wrong?_ IMHO it would also be fine if there would be a specific command for this..

**Comment by dfalty** [comment]
This works for me on 1.1.383 on Ubuntu 16.04. What platform and RStudio version are you on?

**Comment by jmcphers** [comment]
You're not technically doing anything wrong, no. The reason you're getting this error is that you have a `LD_LIBRARY_PATH` set in your shell that's causing RStudio to bind to your system Qt libraries  (`/usr/lib/x86_64-linux-gnu/libQt*`) instead of RStudio's own bundled Qt libraries, and they are not compatible.

You might be able to open a file in an RStudio instance by writing a script that clears `LD_LIBRARY_PATH` and then runs RStudio, but either way this isn't something we currently support.

You're welcome to file an enhancement request for this, of course (curious why this is more convenient for you workflow than e.g. Ctrl+. -- are you writing a script?)

**Comment by nuest** [comment]
Problem 1: I didn't know about `Ctrl+.` but will use it a lot from now on.
Problem 2: I wanted to open a file outside of my working directory, e.g. from another package to look something up, or a configuration file of a system library/service. For that I would just be way faster going `rstudio /etc/..` in the terminal.

I'll think about filing a request - thanks for the help!

**Comment by jmcphers** [comment]
If you just want to type a path and have it open in RStudio, you can do that, too -- in the R console:

    > file.edit("/etc/...")

**Comment by jannes-m** [comment]
@nuest I just stumbled across this issue. And maybe my two cents are still of use. I have also installed vifm (a command line based file explorer a bit similar to nnn), then I run `vifm .` in the RStudio terminal and can open R files, etc. since I have configured in the vifm config file (`vifmrc`):

```
 " open R related stuff with rstudio
filetype *.Rproj,*.R,*.Rmd, rstudio &  
```

However, I haven't got this to work with RStudio Server (using [rocker-docker](https://github.com/rocker-org/rocker)), since I cannot call `/usr/bin/rstudio` from the terminal. @jmcphers do you know how to do that with RStudio Server?

**Comment by mmahmoudian** [comment]
Some 3.5 year after the last post I landed here for similar question.

I am working remotely on data and using Rstudio server, and there are files that are not in the working directory and the fastest way is to use terminal and navigate there. For instance one can use `fzf` which nicely works inside Rstudio terminal to fuzzy-find the file they want. It would be ideal if it was possible to open a file from terminal in the rstudio server. The current workflow:
1. navigate to the path in terminal
2. use `fzf`, `find`, `fd`, `ls` to find the file
3. use the mouse to copy the path
4. go to Rstudio console
5. type `file.edit("`
6. paste the address and press enter

Ideal workflow number 1:
1. navigate to the path in terminal
2. use `fzf`, `find`, `fd`, `ls` to find the file and pipe it to some shell function to open it in Rstudio

Ideal workflow number 2:
1. navigate to the path in terminal
2. use `ls` to find the file and click on it to open it in rstudio

**Comment by kevinushey** [comment]
Thanks @mmahmoudian -- I've opened a separate issue to track that request.
