### ISSUE TITLE
Feature request: Run code chunks in terminal via play button

### ISSUE THREAD

**Issue by mdehollander** [rstudio/rstudio#1880]
I would like to execute code chunks in a R notebook in a Terminal. Running code in a terminal has been introduced in RStudio 1.1 and currently works with selecting lines and pressing `Cntrl + Alt + Enter`. However to be able to use this in a R Notebook with non R-code, you need to be able to run the code chunk in a terminal. Especially when you use bash chunks on Windows. Would it be possible to introduce a 'Run current chunk in Terminal` via the play button?

**Comment by wwgordon** [comment]
I was about to make a new feature request but this seems to be largely the same idea as my own. I was hoping to see bash chunks "routed" to the terminal, so that they behave the same as code in a .sh file (e.g. ctrl+enter sends to terminal). This could enable notebooks to contain a mix of R and shell code (as well as output), which would be hugely helpful for workflows that bounce between the two.
