### ISSUE TITLE
Diagnostics - Warn if variable used has not definition in scope

### ISSUE THREAD

**Issue by FelixErnst** [rstudio/rstudio#1951]
Following situation
- a package with two R files
- a S4 object system
- calling a S4 method from the other file like this

`x <- functionS4(S4Class,arg1,arg)`

If this is code is used in a file, in which the definition does not reside in a warning will be displayed. Is this normal behaviour?

**Comment by kevinushey** [comment]
Got it! Thanks for taking the time to provide an example. Here's the most minimal reprex:

```R
setGeneric(name = "hello", function(x) standardGeneric("hello"))
hello("world")
```

Note that the issue is that RStudio doesn't understand calls to `setGeneric()` where the first parameter (`name`) is explicitly specified. Compare with the following:

![screen shot 2018-01-12 at 11 14 41 am](https://user-images.githubusercontent.com/1976582/34891289-df59594e-f789-11e7-877e-83b2cbe11d95.png)

If you remove the `name =` part of the generic, that would work around this issue in the diagnostics system.

**Comment by FelixErnst** [comment]
Can this be fixed? Even if it is quite clear in this instance, explicit calls should surpass implicit calls, shouldn't they?

**Comment by FelixErnst** [comment]
@kevinushey

**Comment by FelixErnst** [comment]
@jmcphers Is still something you consider fixing? Was it already fixed?
