### ISSUE TITLE
scrollbar indicator always visible on mac os x

### ISSUE THREAD

**Issue by jjallaire** [rstudio/rstudio#1953]
The scrolling indicator seems to be always visible on OS X with the QtWebEngine build:

<img width="1272" alt="screen shot 2018-01-12 at 7 26 59 am" src="https://user-images.githubusercontent.com/104391/34875168-1ed1739c-f76a-11e7-957e-9fc734441c02.png">

Note that this is in spite of the OS preference being set to "automatically":

<img width="650" alt="screen shot 2018-01-12 at 7 29 04 am" src="https://user-images.githubusercontent.com/104391/34875210-4c33eb44-f76a-11e7-98dd-00e30e406e5b.png">

Also note that these are scroll indicators rather than scroll bars (i.e. you can't actually interact with them using the mouse, you have to start scrolling with the trackpad first and then they become scrollbars). As I recall, Mac OS X will often "flash" these scrollbars when a window first appears to indicate that scrolling is possible, however I've never seen them be persistent like this.

**Comment by kevinushey** [comment]
I can reproduce this -- doing a bit of testing locally, I only see this when performing `ant build` but not with `ant desktop` (which is basically GWT SuperDevMode for desktop).

I'll see if I can figure anything else out.

**Comment by kevinushey** [comment]
FWIW I don't see this issue if I launch RStudio while I have a mouse plugged in + external monitors.

**Comment by jjallaire** [comment]
Yes, OS X behaves differently w/r/t to scroll bar display when a mouse is
plugged in

**Comment by kevinushey** [comment]
Looks like this may be a known Qt issue: https://bugreports.qt.io/browse/QTBUG-63381

**Comment by jjallaire** [comment]
Yes, that does look related. This is interesting: "If a stylesheet is used
for QScrollBar"  -- maybe there is a way to remove the stylesheet for
QScrollBar or change it in a way that eliminates the problem?

I think this will drive people batty so hopefully there is a fix that
doesn't require us to beg for a fix from Qt.

**Comment by gtritchie** [comment]
Sure sounds like it, so I gave it an upvote. No doubt it will be fixed
immediately as a result.

**Comment by gtritchie** [comment]
I can repro on Qt 5.9.2, 5.9.3, and 5.9.10, using Qt-supplied example programs. So far we've not found a way to change this behavior. Opened a bug to Qt. https://bugreports.qt.io/browse/QTBUG-65745

**Comment by gtritchie** [comment]
Essentially the same bug opened in Qt in April 2017; guessing mine will get marked as a duplicate of this: https://bugreports.qt.io/browse/QTBUG-59943

**Comment by jjallaire** [comment]
Given that this bug has been set to P3 priority that doesn't bode well for the more recently reported bug. I'm wondering if we're going to need to investigate fixing the bug ourselves (i.e. build Qt from source on the Mac and bundle our fix).

**Comment by gtritchie** [comment]
Yes, I think we're going to have to dig into the guts of QtWebEngine to see
if (1) we have to fix this ourselves or (2) there's a way to coerce the
behavior we want without rebuilding Qt.--or (3) somebody has figured out
(2) and shares it with us.

**Comment by gtritchie** [comment]
Posted a question on Qt forum: https://forum.qt.io/topic/86821/how-to-fix-qtwebengine-to-obey-mac-osx-auto-show-scrollbar-setting

**Comment by gtritchie** [comment]
And here: https://stackoverflow.com/questions/48253738/how-to-make-qtwebengine-obey-macos-auto-scrollbar-setting

**Comment by kevinushey** [comment]
You should link to the Qt issue in Stack Overflow and perhaps also use the images you generated in the StackOverflow post as well (since that'll increase the likelihood that someone who cares will take the time to respond)

**Comment by kevinushey** [comment]
@jmcphers @jjallaire I've spent a lot of time on this but for the life of me cannot find good fix (even in attempting to patch Qt WebEngine sources). This has actually been an issue since Qt 5.7 so the issue has been present for a while, but thus far Qt seems relatively uninterested in getting to the bottom of it.

In Qt 5.10, it's possible to disable scrollbars entirely, but that seems like overkill for this kind of problem (and I don't think it's possible to toggle the scrollbars on / off at runtime in a simple way; it's an all-or-nothing switch).

As far as I can see it, there's a few potential ways out of this hole:

1. Move back to the (new) version of QtWebKit (https://github.com/annulen/webkit). Currently it's maintained as a third-party package, but it appears to be surprisingly heavily used. From what I understand, there are plans to bring it back into the official Qt releases but this hasn't happened just yet. (https://github.com/annulen/webkit)

2. Start building the macOS front-end as a Cocoa application again, but pursue a separate workaround for the lagginess users were encountering with RStudio + high DPI displays. It's possible that this could be solved by porting our old Cocoa code from the old, synchronous interface to the new, asynchronous interface (but this would be a lot more work, and would again sign us up to duplication of code we'd rather not duplicate).

3. Keep on digging in the Qt / QtWebEngine code base. Maybe their team would be more interested in helping us out if we were paying customers?

4. Investigate an alternative to Qt altogether, using e.g. Electron or something similar. @gtritchie did some work on a very simple prototype that had promising results, and we know its widespread usage would also imply widespread testing.

Maybe something to discuss at work week next week...

**Comment by gtritchie** [comment]
I’m happy to dig in and see if I can figure out a patch. I don’t have any magical abilities here and this is very complex code but a second set of eyeballs can’t hurt.

I’m going to defer starting that until we have a chat at work week, however.

**Comment by jjallaire** [comment]
So nasty! Yes, let's discuss our available options over work week.

**Comment by gtritchie** [comment]
Scrollbars have been disabled  completely on the Mac build while we investigate fixes for the QtWebEngine issue.

**Comment by gtritchie** [comment]
This was marked as fixed by Qt in 5.15.0, but when I tried removing our previous workaround, all our scrollbars came back. Same result with sample Qt programs, so have updated their issue to suggest it hasn't been fixed.
