### ISSUE TITLE
Cannot interrupt R session

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#1970]
I've reproduced this all the way back to **1.2.7**, oldest 1.2.x I've found (Mac desktop), but also happens on Linux, haven't tried Windows. It repro's today on **rstudio.cloud**. Works as expected on my machine with 1.1.412.

In console: Sys.sleep(20)

While it is busy, try to interrupt with "Stop Sign" or Session->Interrupt R. Should return to R prompt. 

Nothing happens. If I try multiple times I get the following (as expected when cannot interrupt after multiple tries):

![2018-01-14_12-44-40](https://user-images.githubusercontent.com/10569626/34920508-b5609d32-f928-11e7-8e4f-284a52ceb376.png)

Actually more general problem than interrupt; looks like anything that requires a call from the UI to the backend doesn't work while R is busy. Try to show About dialog, or Global Options, for example.

**Comment by gtritchie** [comment]
I can repro long before the QtWebEngine merge so removing that tag.

I saw this in a sampling of Mac builds back to 1.2.214 from December 15, 2017, (and probably before that, that's just how far back I've gone so far).

**Comment by kfeinauer** [comment]
Caused by https://github.com/rstudio/rstudio-pro/pull/155. Recommend reverting the code changed by that PR as it only fixed some very minor MacOS timeout issues.

**Comment by ronblum** [comment]
This works for Sys.sleep(20), but is still an issue when issuing a system command like `system("sleep 1234")` or `system2("sleep", args = "2350")`. Click on the stop sign multiple times and picking "Yes" on the pop up (above) restarts the session. The processes are still running, though: 

```
Rons-MacBook-Pro:~ ronblum$ ps -ef | grep sleep
  501 38300     1   0  1:05PM ??         0:00.00 sleep 2350
  501 38432     1   0  1:06PM ??         0:00.00 sleep 1234
  501 39168 39139   0  1:10PM ttys001    0:00.00 grep sleep
Rons-MacBook-Pro:~ ronblum$
```

**Comment by kevinushey** [comment]
I think this is chiefly because RStudio handles interrupts by setting a flag on the R session to handle interrupts on the next chance it gets (e.g. in `R_CheckUserInterrupt()` or `R_ProcessEvents()`) rather than actually sending an interrupt signal to the process. Some motivation for this decision is outlined here:

https://github.com/rstudio/rstudio/blob/ec3247337fbcda6d4109eec540269bb408370fd4/src/cpp/r/session/REmbeddedPosix.cpp#L57-L74

It seems like we could attempt to detect if R is within a subprocess, and if so send a `SIGINT` when attempting to interrupt. We could also replicate R's own interrupt behavior by following what R does here:

https://github.com/wch/r-source/blob/536099e8deb41d899b1d454e07e8e58a7158691c/src/main/main.c#L642-L668

https://github.com/wch/r-source/blob/536099e8deb41d899b1d454e07e8e58a7158691c/src/main/main.c#L425-L429

**Comment by kevinushey** [comment]
The bigger issue here is that the thread handling RPC requests is completely blocked when a system call is made, so attempts to interrupt the process are not actually handled until the associated `system()` call has returned.

In theory, we could have the thread handling the HTTP requests signal the interrupt, but this seems like it would take time to get right.

**Comment by gtritchie** [comment]
@ronblum Is this a regression from prior versions? The inability to interrupt Sys.sleep was a regression and is fixed, but how about `system("sleep 1234")`? Did that used to work?

**Comment by ronblum** [comment]
system("sleep 1234") is not a regression—that's how it was in the past. Should I file a separate issue for that, something to look at in the future? Because meanwhile, I've verified interrupting Sys.sleep() works.

**Comment by gtritchie** [comment]
Yes, please open a new issue on that. Thanks.

**Comment by gtritchie** [comment]
Closing this; per @ronblum the regression was fixed, the fact you can't interrupt `system` commands isn't a new problem and should be tracked separately.

**Comment by ronblum** [comment]
Confirmed. And @ronblum finally filed the separate issue, #2565, to be tracked separately.
