### ISSUE TITLE
See All Shortcuts link in Keyboard references doesn't work

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#1992]
Help -> Keyboard Shortcuts Help
Click on "See All Shortcuts..."

Expect: launches a page in the web browser
Actual: nothing happens

**Comment by jmcphers** [comment]
Best guess so far is that it's related to the issue described here:

https://stackoverflow.com/questions/37898660/qdesktopservicesopenurl-does-not-work-neither-for-urls-nor-for-local-files-o

In short, we need an instance of `QApplication` in order for `openUrl` to work, but we never actually instantiate this since we're using this 3rd party `QtSingleApplication` thing.

https://github.com/rstudio/rstudio/blob/7bbb81720692a19eef58599dc42ceea0a415c9e5/src/cpp/desktop/DesktopUtils.cpp#L334-L337

https://github.com/rstudio/rstudio/blob/master/src/cpp/desktop/DesktopPosixApplication.hpp#L31-L32

**Comment by jmcphers** [comment]
Hmm, maybe not. It looks like some URLs do work. It looks like the reason this URL doesn't work is either that it's local, or that the `keyboard.htm` file it's trying to open does not exist.

**Comment by jmcphers** [comment]
@gtritchie In my testing this actually does work in released builds with QtWebEngine; it fails in dev mode because the resource path is different. Can you confirm?

**Comment by gtritchie** [comment]
Confirmed, it does work on released builds. FYI, I am looking into other cases involving loading external links (#1942 ): `QDesktopServices::openUrl` works, but in cases where it's done directly via an anchor in the HTML RStudio then crashes (but successfully launches the page into browser).

**Comment by gtritchie** [comment]
Closing; this works in actual builds of the product, just not in development environment.
