### ISSUE TITLE
RStudio keep hanging when "Quit Session" or saving file 

### ISSUE THREAD

**Issue by abbatidanilo** [rstudio/rstudio#2007]
RStudio (RStudio-1.1.414) keeps on hanging on most principal actions, for example simply quitting or opening existing files. In particular I am dealing with RMarkdown projects. I tried with different R version shifting from the latest version 3.4.3 down to 3.3.3 but with no appreciable improvement.

**Comment by jmcphers** [comment]
Sorry you're having trouble! We have not been able to reproduce this, unfortunately; could you include some additional details about your system? See our contribution guide for what to include:

https://github.com/rstudio/rstudio/blob/master/CONTRIBUTING.md

**Comment by abbatidanilo** [comment]
No problem Jonathan!
My fault instead: I just realized what a poor subject I put for to describe the issue...
In any case, I was in a hurry so I preferred to rollback to a previous  edition of RStudio (Version 1.0.153) because I realized than the issue persists even with older version of the R compiler.
Pity I removed the current edition with all the relevant diagnostic. I promise: I won't do it again b4 saving the sessionInfo()!
Now I am using RStudio ver 1.0.153 with R3.3.3 and it works much better  (the ones I used some weeks ago).
I do not know if others are facing the same problem (I discovered the same kind of issues described in the past <https://stackoverflow.com/questions/34532328/couldnt-quit-r-session-or-couldnt-quit-rstudio> - but I thought it was too old...)

cheers

**Comment by jmcphers** [comment]
Okay, I don't think we have enough to go on here -- but if you do start seeing it again and have time to collect more diagnostics, feel free to reopen.

**Comment by ronblum** [comment]
[Combing with #2036]

> Hello,
RStudio keeps on hanging when you try to quit or to save a file. In particular I am writing a RMarkdown note with nothing especial on it.
The issue happens some time using RStudio-1.0.153 but much often when using the most recent RStudio-1.1.414. I tried with the most recent R compiler 3.4.2 but I also downgrade to 3.4.0 and 3.3.3 (which is the one I currently using). I cannot say if this depends on the R compiler or the RStudio version itself, but it seems the older, the better...
I opened the same issue last week but in that case I did not send any detail. Here at least I managed to have the diagnostics-report.
I cannot provide the sessioninfo() because when it hangs, the only way is to kill the process.
OS: Windows 10 pro on an Intel i5 2540M CPU
[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/1661561/diagnostics-report.txt)

**Comment by ConorIA** [comment]
A number of us on Arch(-based distros) have encountered this as well when building from source (see this [PKGBUILD](https://aur.archlinux.org/packages/rstudio-desktop-git/)).

Basically, as I encounter it, any pop-up dialogue is will not perform the selected response, meaning that one cannot perform the action that prompted the dialogue ("Yes" or "No" have the same effect as "Cancel").

| Situation | Related Prompt | Workaround |
|-------------|-----------|------------------|
| When trying to close an unsaved file | Do you want to save these changes? | `xkill` the window |
| When trying to quit the R session | Save workspace image to ~/.Rdata | `> quit(save = "no")` |
| When trying to upgrade a package that is already attached | Do you want to restart R prior to installing? | Manually restart R from the `Session` menu |

The first two are the most frustrating

**Comment by kevinushey** [comment]
What's the output of executing

    lsof -p `pidof rstudio`

in the terminal while RStudio is running?

Unfortunately, I don't see anything that stand out in the diagnostics report.

**Comment by abbatidanilo** [comment]
Hello Kevin,
I-ll do it as soon as I face the issue again.
The problem is that when it's hanging some of the functionalities are
completely frozen (#@? frustrating!) and sometimes the terminal as well...
cheers
Danilo

**Comment by ConorIA** [comment]
@kevinushey, here is the output from my setup. https://cloud.conr.ca/s/jEsfSSTS9Dr5Q4k

**Comment by kevinushey** [comment]
@ConorIA the problem appears to be that RStudio is using the system Qt libraries on your machine, rather than the bundled Qt libraries. Do you have `LD_LIBRARY_PATH` or something similar set up to point to these libraries? Or does Arch Linux do something specific here to prefer the system libraries?

**Comment by ConorIA** [comment]
@kevinushey, I don't have anything set in particular. However, I notice that the package doesn't actually contain any bundled libraries (See (here)[https://cloud.conr.ca/s/H6ziGajbBSeZpKH]). I think the [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=rstudio-desktop-git) must be missing a step. Perhaps we need to use `install-qt-sdk`.

**Comment by kevinushey** [comment]
That's likely the case. Also, take a look at how `cmake` is invoked here:

https://github.com/rstudio/rstudio/blob/4ede38f9786df61ee7bbf5ede5df662b131fe5c6/package/linux/make-package#L56-L61

Setting `RSTUDIO_PACKAGE_BUILD` also implies defining `RSTUDIO_BUNDLE_QT`. You don't want a package build, but you will have to define `RSTUDIO_BUNDLE_QT` when invoking `cmake`.

**Comment by ConorIA** [comment]
Thanks very much @kevinushey. Looks like I've got myself a weekend project.

**Comment by ConorIA** [comment]
@kevinushey, completely solved with a few [changes to the PKGBUILD](https://cloud.conr.ca/s/dkrK4SN7d6qTgBF). 

That said, it seems I wrongfully usurped @abbatidanilo's issue.  Based on the first few comments, I thought that we were experiencing the same issue, but I haven't experienced the freezing the described in @abbatidanilo's last comment. Sorry folks! Thanks for all the help.

**Comment by artemklevtsov** [comment]
Is it possible to build package with system Qt libs?

**Comment by abbatidanilo** [comment]
Hello Artem,
when Rstudio is hanging, there's no possibility to perform any kind of
action (even the most simple, included to produce any snapshot of the
system)
I don't know if I answered your question
cheers
Danilo

**Comment by abbatidanilo** [comment]
Hello Kevin,
I am currently working with RStudio 1.1.447 with R 3.5.0 since a while with
no problem.
I do not know wheter this is still pending but I would close it by now.
Thank you
Bye

**Comment by twnawrocki** [comment]
I also see this error. It seems to have originated when knitting an R markdown file. RStudio hangs when loading a file, saving, or quitting now even after a fresh installation of both R 3.5.0 and RStudio 1.1.453. I'm using a windows 10 system. Others seem to have succeeded in fixing this problem by deleting the QtProject.conf.lock file but I have been unsuccessful in finding such a file on my system so far.

**Comment by fvalenduc** [comment]
> @kevinushey, completely solved with a few [changes to the PKGBUILD](https://cloud.conr.ca/s/dkrK4SN7d6qTgBF).
> 
> That said, it seems I wrongfully usurped @abbatidanilo's issue. Based on the first few comments, I thought that we were experiencing the same issue, but I haven't experienced the freezing described in @abbatidanilo's last comment. Sorry folks! Thanks for all the help.

The link to the PKGBUILD file is not working anymore. Can you post it again or explain what has changed ?

**Comment by ConorIA** [comment]
@fvalenduc, sorry, I didn't see this message as my email server was down. If I recall correctly, the relevant changes are in this commit: https://aur.archlinux.org/cgit/aur.git/commit/?h=rstudio-desktop-git&id=2c4413a5714dae9753d2e62ba326286871ca94ef. Some more changes since then, but the package is largely working fine. There are still a couple of frustrations, e.g. the "shell" button in the git tab does not actually launch Konsole.

**Comment by fvalenduc** [comment]
Thanks, I am trying to apply the same changes on gentoo and I adapted the ebuild more ore less in the same way. Unfortunately, it ends with this error:

CMake Error at src/cpp/desktop/CMakeLists.txt:83 (find_package):
  Found package configuration file:

    /usr/lib64/cmake/Qt5WebKit/Qt5WebKitConfig.cmake

  but it set Qt5WebKit_FOUND to FALSE so package "Qt5WebKit" is considered to
  be NOT FOUND.  Reason given by package:

  Qt5WebKit could not be found because dependency is required to have exact
  version 5.11.x.

**Comment by jmcphers** [comment]
This bug has turned into a discussion of how to build RStudio from source, which we are happy to give some pointers for but isn't what this issue should be tracking (we still don't really have evidence of a good repro for the original hang, and can't formally support third-party source builds on Linux distributions).

For help building RStudio from source, use our community forum:

https://community.rstudio.com/c/rstudio-ide
