### ISSUE TITLE
Feature Request: keyboard shortcut for Code Folding **Toggle**

### ISSUE THREAD

**Issue by plantarum** [rstudio/rstudio#2033]
Just a small enhancement: would it be possible to get a keyboard shortcut for toggling code folding? The current behaviour requires one combo for folding, and another for unfolding. I prefer the way Emacs handles this: the same key combo opens and closes the section. That is, if the section is folded, hitting the shortcut opens it, and if it's open, the same key folds it. 

This makes sense, in that you never want to fold a section that's already folded, or open a section that's already open. You actually want to switch from the current state to the other state, regardless of which state you're in.

Not a big deal, but it would be nice to have :)

**Comment by ronblum** [comment]
Thank you for the suggestion, @plantarum !

**Comment by DesiQuintans** [comment]
Important suggestion.

**Comment by DesiQuintans** [comment]
Turns out that this is already in RStudio, it's just not bound by default. Go to _Keyboard Shortcuts_, search for 'fold'. You'll see _Toggle Fold Widget_ and _Toggle Parent Fold Widget_.

I disabled nearly all of the folding shortcuts and I just have this:

- Fold All, Alt + O
- Unfold All, Shift + Alt + O
- Toggle Parent Fold Widget, Alt + L
- Fold Other, Shift + Alt + L
