### ISSUE TITLE
Busy Session Causes Browser to Become Unresponsive

### ISSUE THREAD

**Issue by kfeinauer** [rstudio/rstudio#2038]
### Overview

Currently, the RPC message handling in the session process is done on the same thread that processes the R event loop. This causes issues when running a long-running statement that blocks execution, causing incoming RPC events to queue up until completion of the command.

The problem with this is that not only does it cause the current session to be completely unresponsive, but when using many modern browsers like Chrome, the maximum number of simultaneous open connections (usually 6) is reached, causing the browser to be unable to interact with *any* RStudio pages (since the connection limit is per domain).

### Repro

Open two sessions. In one, execute a very long running statement, such as a database call that does not return for a long time. While it is executing, switch tabs continuously. Each time the busy session is activated, a `get_active_sessions` RPC request is sent. After some time, the maximum number of allowable simultaneous open connections will be reached. At this point, you will be unable to interact with any RStudio page, including the second (idle) session.

**Comment by kfeinauer** [comment]
@jmcphers and I have briefly discussed tackling this in the past. The argument was made that it's not too big of a deal because this only affects the session doing the busy work, but now it has been discovered that this causes a backup of requests that affect connectivity to other pages.

**Comment by jmcphers** [comment]
There are a number of bugs that would be addressed if we were able to better manage concurrency between the RPC events and the R event loop. For instance, if the R session is busy doing work there are a number of things you can't do in the UI (as the RPCs don't return), which is a frequent source of frustration. However, separating these concerns such that the RPCs that service the UI and those that talk to R are separated and threadsafe is a nontrivial architectural undertaking, especially since many of the RPCs which service the UI *do* talk to R at some point. 

Until we have time to get at the root issue (and we won't in 1.2), I think we can solve this particular issue practically for most users by treating the symptoms. The `get_active_sessions` RPC should have a re-entrancy guard; that is, the code which invokes the RPC should first check to make sure it isn't currently waiting for an RPC it invoked earlier. This will keep the connections from stacking up in the manner observed.

There are probably two or three other frequently invoked RPCs that could use reentrancy guards to keep them from stacking while R is busy. We might also spend a little time once `get_active_sessions` is guarded to see if there are any others that tend to stack while waiting for R (otherwise we may just wind up with the same problem on another RPC!). More ambitiously we could create a reentrancy guard wrapper which could be applied generically to any RPC we suspect will stack, although this would be hard to do elegantly (might have to use a decorator and a rebind generator).

**Comment by mikebessuille** [comment]
There are *so many* customer complaints about their UI freezing during long-running R execution.  This is one of the most critical features we need to address.  Just one example:
https://community.rstudio.com/t/rstudio-goes-blank-when-ram-is-low/97704

**Comment by colearendt** [comment]
Worth noting that the problem @mikebessuille mentions is the much more user-facing problem (which would be AMAZING to fix). The issue reported by @kfeinauer seems to be more technical in nature and harder to hit practically, but much more debilitating if hit. (i.e. the issue Mike reports can be resolved by switching to a different session. However, that is often not what is desired as a user - I might want to explore files in my working directory, send launcher jobs, or work on editing something while my R session is busy)

**Comment by kevinushey** [comment]
I think this issue tracks the more narrow issue of ensuring certain eagerly-handled RPCs (e.g. abort) can still be serviced even if the R session is busy. The larger work of separating `rsession` into two components would likely be handled in a separate issue / epic.

(brain-dumping) FWIW, I think the ultimate goal eventually will be to separate the `rsession` process into two pieces:

- The `rstudio-session` process, which would be the "core" session state without any R-specific bits;
- The `rsession` process, which specifically handles RPCs which require interfacing with R.

The `rstudio-session` process would be a sort of middleware: it is responsible for communicating with the front-end (RStudio Desktop or `rserver`), and "proxying" RPC requests to the `rsession` process if required. Similarly, the `rsession` process would communicate with the `rstudio-session` process rather than `rserver`, and rely on `rstudio-session` to forward those responses to the server.

At first, the `rstudio-session` process would do nothing more than act as proxy between the `rserver` and `rsession` processes; slowly, we would port functionality from `rsession` into `rstudio-session` as appropriate. This would hopefully minimize disruption and risk as we separate pieces out.

**Comment by jcheng5** [comment]
A few other random thoughts I have had about this issue in the last few weeks, while working with RSP customers.

1. This is the underlying cause of 504 errors. Amazon ALB defaults to 60 second request timeout. I expect as customers deploy into AWS more and more we'll see more and more 504 errors--we'll need to tell/convince people to crank that timeout to the maximum until RStudio is free of this limitation.
2. Not all long running calls block HTTP handlers from executing. `Sys.sleep(10)` doesn't, `system("sleep 10")` does. C/C++ code calling `R_CheckUserInterrupt()` seems to be enough to temporarily yield control to RStudio.
3. The `get_events` RPC call is not subject to this problem; in almost all circumstances, it returns within 50 seconds (although I suppose it could be queued on the _cilent_ side behind 6 stalled HTTP requests).
4. Slack appears to use WebSockets. Maybe the world is ready for RStudio to move off of long polling HTTP? It wouldn't solve the actual user slowness, but it would solve the 504 and the concurrent HTTP request count limit--so, like, 20% of the problem I guess.
5. If not WebSockets, there's an in-between approach that still uses long polling but has every non-`get_events` RPC request immediately return a request ID and nothing else; and make `get_events` responsible for returning the result of every RPC request. That would solve the same 20% of the problem as WebSockets would, just with considerably more network overhead but possibly greater compatibility with legacy firewalls/proxies and less code changes required.

(BTW, for both 4 and 5, I imagine the changes on the client being all within the existing facade of `RemoteServer.java`; and all the changes on the server... well, I'm not sure, but maybe all within `SessionHttpConnection*.[hc]pp`. My point is, only the network transport needs to change, not any of the code that uses the transport.)

**Comment by jcheng5** [comment]
> It'd be great if websockets just worked, but our experience is still that they often get caught in firewalls and proxies that don't upgrade the connection properly.

2022 will be the year of ~the Linux desktop~ WebSocket acceptance, I'm sure of it!

**Comment by colearendt** [comment]
For what it's worth, though websockets do get caught, most customers need websockets to work for Shiny to function properly (without websockets, the Shiny app just disconnects immediately). Do we know of customers that have a functional environment with not-functional websockets? 

Also, I think Jupyter Notebooks do not work properly without websockets. So we may be fine to move forward with websockets

**Comment by jeffvroom** [comment]
There is a fix for this issue on the new "main" branch but it's not enabled by default. I'll leave this open until we've done more testing on it and it's ready for everyone.  For now you can turn it on with:

---- /etc/rstudio/rsession.conf:
# settings to keep connectivity alive
session-async-rpc-enabled=1
session-async-rpc-timeout-ms=250

# settings to process requests offline
session-handle-offline-enabled=1
session-handle-offline-timeout-ms=250

**Comment by jeffvroom** [comment]
Both async-rpc and handle-offline are now enabled by default with these default values 
session-async-rpc-timeout-ms=200
session-handle-offline-timeout-ms=200

**Comment by jeffvroom** [comment]
Here's the main PR for this fix with the QA notes:

https://github.com/rstudio/rstudio/pull/9261

**Comment by ronblum** [comment]
One of the components isn't merged yet, so I'm pausing QA for now and putting this back in back in "in progress" state for the moment.

**Comment by ronblum** [comment]
This has been working as expected. Similarly to #8494, I've been running this occasionally and semi-randomly. As the final verification, I've followed the suggestions in the QA Notes in
- RStudio Desktop 2021-07.0.270 on MacOS 12 beta
- RStudio Server 2021.7.0.271.1 on Red Hat 8.4 via Chrome on MacOS 12 beta
- RStudio Server 2021.7.0.271.1 on SLES 15 SP3 via Safari on MacOS 12 beta

However, this is so fundamental, that I'd like it if we get another person to try this out for a final formal verification, so I'm unassigning it from me and leaving this in a "verifying" state, for someone else to follow up.

**Comment by astayleraz** [comment]
I followed the steps as well in version 2021-08.0 Build 317-2 on Ubuntu20 server and was working for me as expected. Closing issue.
