### ISSUE TITLE
connect R to Presto ---->Error in curl::curl_fetch_memory(url, handle = handle) : Empty reply from server

### ISSUE THREAD

**Issue by ArRstudio** [rstudio/rstudio#2046]
### System details

    OS Version      : ubuntu 14.4
    RStudio Version : 1.0.136
    R Version       :3.3.3

### Steps to reproduce the problem
> library(dbConnect)
Loading required package: RMySQL
Loading required package: DBI
Loading required package: gWidgets
> library(RPresto)
> library(dplyr)

Attaching package: ‘dplyr’

The following object is masked from ‘package:gWidgets’:

    id

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

> db <- src_presto(
+     host='abcd.com',
+     port=443,
+     user=Sys.getenv('abcd'),
+     schema='default',
+     catalog='ares',
+ )
> iris <- tbl(db, 'xyz_abc')
Error in curl::curl_fetch_memory(url, handle = handle) : Empty reply from server

### Describe the problem in detail

I am trying to connect R to Presto from R-Studio application,I am receving below error,please help me support on this issue

Error in curl::curl_fetch_memory(url, handle = handle) : Empty reply from server

**Comment by ronblum** [comment]
Hi @ArRstudio Two notes:
1) I wasn't able to reproduce this error. Running the same code (also Ubuntu 14, but with R 3.4.0). I got a connection refused.
> Error in curl::curl_fetch_memory(url, handle = handle) : 
  Failed to connect to abcd.com port 443: Connection refused

2) Have you tried this out in R, instead of RStudio? This appears to be a base R issue, not RStudio. I would suggest a site such as [Stack Overflow](https://stackoverflow.com/questions/tagged/r), in which R users could help. Good luck!
