### ISSUE TITLE
auto.snapshot option is not carried over from first "Use packrat with this project"

### ISSUE THREAD

**Issue by ras44** [rstudio/rstudio#2067]
### System details

    OS Version      : CentOS 7
    RStudio Version : 1.1.414
    R Version       : 3.4.3

### Steps to reproduce the problem
The first time a user enables packrat with via Tools->Project Options->Packrat by clicking on "Use packrat with this project", the auto.snapshot option selected below is not passed through to the newly initialized project. By default auto.snapshot is not selected, ie. it should be false.

After enabling packrat, R installs packrat and runs

packrat::init()

The new project has auto.snapshot=TRUE instead of false as it should be.

**Comment by ronblum** [comment]
Thanks for the report! Confirmed on CentOS 7 with RStudio Server 1.1.383 and MacOS Desktop 1.1.419.

It looks like this is because the default value of auto.snapshot on init is TRUE. In order for it to be set to false, the value must be set with the init, i.e.
   `packrat::init(options = list(auto.snapshot = FALSE)`

Compare this to checking the boxes for automatic snapshotting and global caching, where the options are correctly included:
   `packrat::init(options = list(auto.snapshot = TRUE, use.cache = TRUE))`

**Comment by jmcphers** [comment]
Unfortunately, the Packrat integration has been deprecated, and this option no longer exists in the daily builds.
