### ISSUE TITLE
Reformat code is incorrect whese using chinese characters.

### ISSUE THREAD

**Issue by taoruicn** [rstudio/rstudio#2080]
### System details

    RStudio Edition : 
    RStudio Version :  1.1.419  
    OS Version      :  Ubuntu 16.04
    R Version       :  3.4.3

### Steps to reproduce the problem
 ggplot(Population.plot,
       aes(
         x = 年份,
         y = value,
         group = variable,
         color = variable
       )) + geom_line() + geom_smooth() 

### Describe the problem in detail
  Command "Reformat code" always adds a space before chinese characters. For example, a space will always adds before 年份 when press Command "Reformat code".

**Comment by kevinushey** [comment]
Thanks for the bug report! The problem here is that our tokenizer doesn't recognize non-ASCII identifiers:

![screen shot 2018-01-29 at 11 30 07 am](https://user-images.githubusercontent.com/1976582/35530074-d4aaec68-04e7-11e8-900f-923c8dff7cdf.png)

We'll have to make our tokenizer unicode-aware to handle this properly.
