### ISSUE TITLE
Improve RStudio startup diagnostics / preflight checks

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#2097]
Users often bump into issues when launching RStudio. Unfortunately, there usually isn't a single one reason as to why these failures to launch occur, but the most common catch-all reasons:

- The R session crashes on initialization; often due to an attempt to restore a corrupt workspace, or to load a package that is either corrupt or does not work with the current version on R.

- Permissions on files used by RStudio during launch (e.g. the source database) are set in such a way that RStudio cannot access them.

- Firewall restrictions are preventing RStudio and the R session from communicating.

- A corrupt R / RStudio installation leads to a mixing of different (incompatible) versions of components.

It'd be helpful if we could learn a bit more about what exactly is going on during the RStudio / rsession launches, e.g.

- An INFO system log (with a simple way to toggle the log level) indicating what stage of initialization the process is in.

- Top-level exception handlers (e.g. POSIX signal handling of `SIGSEGV` / uncaught Windows exceptions) that capture and write a backtrace (or other information) to the system log, or some other location.

Notes:

https://msdn.microsoft.com/en-us/library/windows/desktop/ms680634(v=vs.85).aspx
https://msdn.microsoft.com/en-us/library/windows/desktop/bb204633(v=vs.85).aspx

Chromium does something similar for capturing of backtraces:

https://cs.chromium.org/chromium/src/base/debug/stack_trace_posix.cc?sq=package:chromium&dr=C
https://cs.chromium.org/chromium/src/base/debug/stack_trace_win.cc?sq=package:chromium&dr=C

**Comment by kfeinauer** [comment]
@kevinushey I did some work on this already for RStudio Server Pro - see http://docs.rstudio.com/ide/server-pro/latest/r-sessions.html#diagnosing-session-launch-failures.

We may be able to utilize some of this, or it may be that whatever work is done for this feature obviates the need for what I had done in 1.2.

**Comment by kevinushey** [comment]
Placing in v1.3-preview -- I think we should at least improve the error reporting when startup fails (e.g. replacing the "404 Page not Found" page with something more meaningful; even a plain "The R session failed to initialize" would be better)

**Comment by jmcphers** [comment]
This is absolutely worth doing but would not be worth holding up the preview to fix.

**Comment by jmcphers** [comment]
Poked at this a little today. Some notes:

QtWebEngine can accept raw HTML in addition to a URL. I think our general approach should be to create an error page (and possibly a loading page) as text templates that exist outside the R session HTML. In the event that the R session doesn't load, we can load raw HTML into the web view with error details.

Here's where we do the initial URL load:

https://github.com/rstudio/rstudio/blob/d26b0b6d0f6ed5ec458f307016c6170345483d94/src/cpp/desktop/DesktopSessionLauncher.cpp#L192-L200

We could do something like this in addition:

1. Instead of loading this URL, load a "starting R" loading page.
2. Start a thread which checks to see (a) if the R process is alive, and/or (b) if it is responsive to HTTP requests.
3. When we detect that the R process is alive and healthy, we load the URL.
4. If it isn't healthy or the process dies, show a diagnostic error page that includes the stdout of the process, the last entries in the R session log file, etc.
