### ISSUE TITLE
notebook -> non-notebook conversion is confusing

### ISSUE THREAD

**Issue by aronatkins** [rstudio/rstudio#2105]
Start with an Rmd notebook. Notice that there is a "Preview" button instead of a "Knit" button. Choose the drop-down and choose to "Knit to HTML".

This operation updates the YAML so the Rmd is no longer seen as a notebook. It is not obvious if there is a way to get the Rmd back into its notebook form.

Observed during the Intro to R and RStudio course at rstudio::conf 2018.

CC @ronblum 
CC @AmeliaMN

**Comment by kevinushey** [comment]
IMHO the whole way we handle this (updating the YAML metadata just before attempting a new render) is somewhat janky; it feels like there should be some way to accomplish this without needing to mutate the original document itself.

That said, it might be too late to change this behavior, or there might be other considerations as to why we do this.

**Comment by jmcphers** [comment]
The root of the problem is that we have a single UI gesture which has two possible intents:

1. Render the current document to the given output format *just this one time* (i.e. render the document to a different type)
2. Change the current document so that it *always* renders to the given output format (i.e. change the type of the document)

Aron expected (1) and got (2), but if we swap it then we'll likely have users who want to do (2) frustrated that now (1) is the behavior.  I think what we need is two different UI gestures, one for one-off rendering (which will not alter the YAML) and one for initiating a permanent type change (which will).

**Comment by aronatkins** [comment]
Quite a few folks in the intro course were surprised by the fact that the Rmd was no longer a notebook. It felt surprising because the "Preview" (and even "Knit") do not modify the source document. It's unclear which operations in the knit menu are only artifact-producing versus source-document changing.
