### ISSUE TITLE
RStudio crash on close on macOS

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#2110]
Some users have reported seeing RStudio crash on close on macOS. In particular, this seems to happen when attempting to close the IDE while in fullscreen mode. It's somewhat difficult to tell what causes the crash, but it is not completely reproducible (most users see it happen anywhere from 10% to 50% of the time when trying to close)

Associated code path:

https://github.com/rstudio/rstudio/blob/e06b759e7c444ba07cea81c311538c205c56c8fc/src/cpp/desktop-mac/MainFrameController.mm#L138-L150

This commit is where we added this observer:

https://github.com/rstudio/rstudio/commit/c1d28583f870515234230a6fe7143b8ed1dbc2df

but in the current v1.1-patch branch, I can't actually see the code where we register the observer -- it seems we only ever attempt to de-register it!

See also:

https://community.rstudio.com/t/rstudio-1-1-crashing-with-unclear-pattern/2132
https://support.rstudio.com/hc/en-us/community/posts/115007991213-RStudio-Preview-keeps-crashing-on-Quit
https://support.rstudio.com/hc/en-us/community/posts/115008292147-R-keep-quitting-showing-internal-error

**Comment by kagray** [comment]
Process:               RStudio [26836]
Path:                  /Applications/RStudio.app/Contents/MacOS/RStudio
Identifier:            org.rstudio.RStudio
Version:               1.1.421 (1.1.421)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           RStudio [26836]
User ID:               501

Date/Time:             2018-02-01 15:54:09.598 -0800
OS Version:            Mac OS X 10.13.3 (17D47)
Report Version:        12
Anonymous UUID:        A80CA4CC-CC76-3251-94DA-09C738AE2AFE

Sleep/Wake UUID:       FE53E843-2278-4C1C-8AC8-6AFA6879CE74

Time Awake Since Boot: 81000 seconds
Time Since Wake:       2600 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
*** Terminating app due to uncaught exception 'NSRangeException', reason: 'Cannot remove an observer <MainFrameController 0x604000162280> for the key path "runningApplications" from <NSWorkspace 0x6040000006e0> because it is not registered as an observer.'
terminating with uncaught exception of type NSException
abort() called

Application Specific Backtrace 1:
0   CoreFoundation                      0x00007fff3dc29fcb __exceptionPreprocess + 171
1   libobjc.A.dylib                     0x00007fff648c7c76 objc_exception_throw + 48
2   CoreFoundation                      0x00007fff3dcbb9ed +[NSException raise:format:] + 205
3   Foundation                          0x00007fff3fca7bd7 -[NSObject(NSKeyValueObserverRegistration) _removeObserver:forProperty:] + 497
4   Foundation                          0x00007fff3fca798d -[NSObject(NSKeyValueObserverRegistration) removeObserver:forKeyPath:] + 84
5   AppKit                              0x00007fff3ba777be -[NSWorkspace removeObserver:forKeyPath:] + 54
6   Foundation                          0x00007fff3fd11784 -[NSObject(NSKeyValueObserverRegistration) removeObserver:forKeyPath:context:] + 177
7   RStudio                             0x0000000100018104 -[MainFrameController dealloc] + 68
8   libobjc.A.dylib                     0x00007fff648c1db4 _ZN11objc_object17sidetable_releaseEb + 266
9   AppKit                              0x00007fff3b1956d8 -[NSWindowController release] + 154
10  AppKit                              0x00007fff3b80957e -[_NSWindowExitFullScreenTransitionController doAfterExitFullScreen] + 129
11  AppKit                              0x00007fff3baef5e2 -[_NSExitFullScreenTransitionController _doAfterExitFullScreen] + 185
12  AppKit                              0x00007fff3baefb24 -[_NSExitFullScreenTransitionController _doSucceededToExitFullScreen] + 458
13  AppKit                              0x00007fff3b557ab1 __NSFullScreenDockConnectionSendExitForSpace_block_invoke + 88
14  libxpc.dylib                        0x00007fff6577db95 _xpc_connection_reply_callout + 36
15  libxpc.dylib                        0x00007fff6577db00 _xpc_connection_call_reply_async + 82
16  libdispatch.dylib                   0x00007fff6548a8c8 _dispatch_client_callout3 + 8
17  libdispatch.dylib                   0x00007fff65499afe _dispatch_mach_msg_async_reply_invoke + 360
18  libdispatch.dylib                   0x00007fff654891b9 _dispatch_main_queue_callback_4CF + 776
19  CoreFoundation                      0x00007fff3dbe2929 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
20  CoreFoundation                      0x00007fff3dba4bea __CFRunLoopRun + 2586
21  CoreFoundation                      0x00007fff3dba3f43 CFRunLoopRunSpecific + 483
22  HIToolbox                           0x00007fff3cebbe26 RunCurrentEventLoopInMode + 286
23  HIToolbox                           0x00007fff3cebbb96 ReceiveNextEventCommon + 613
24  HIToolbox                           0x00007fff3cebb914 _BlockUntilNextEventMatchingListInModeWithFilter + 64
25  AppKit                              0x00007fff3b186f5f _DPSNextEvent + 2085
26  AppKit                              0x00007fff3b91cb4c -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 3044
27  AppKit                              0x00007fff3b17bd6d -[NSApplication run] + 764
28  RStudio                             0x0000000100017b9a main + 330
29  RStudio                             0x0000000100003dc4 start + 52
30  ???                                 0x0000000000000002 0x0 + 2

**Comment by jmcphers** [comment]
@kevinushey made a fix for this: https://github.com/rstudio/rstudio/commit/b80e0e095b6d796e33c45f2e82e4ac401c42cf83

@kagray we've just published a patch which contains this fix (1.1.423): https://www.rstudio.com/products/rstudio/download/preview/

**Comment by kagray** [comment]
Sweet works great thanks
