### ISSUE TITLE
RStudio daily builds fail to launch on OpenSUSE 42.3 Leap

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#2139]
I see:

```
kevin@linux-awyh:~> rstudio
rstudio: error while loading shared libraries: libssl.so.10: cannot open shared object file: No such file or directory
```

I see OpenSSL libraries installed here:

```
kevin@linux-awyh:/> find . -name "*libssl*" 2> /dev/null
/usr/lib64/pkgconfig/libssl.pc
/usr/lib64/libssl3.so
/usr/lib64/libssl.so
/lib/libssl.so.1.0.0
/lib64/libssl.so.1.0.0
```

**Comment by kevinushey** [comment]
Making these symlinks in `/usr/lib64` resolves the issue:

- `libssl.so` -> `libssl.so.10`
- `libcrypto.sl` -> `libcrypto.so.10`

**Comment by jmcphers** [comment]
We typically get around this issue by 

1. creating softlinks to the libraries in question alongside our binaries, and
2. updating the RPATH of our binaries so that they look in their own folder.

https://github.com/rstudio/rstudio/blob/782ebb6cd26ab9c58550a1b6e947e8d8a737e42f/package/linux/rpm-script/postinst.sh.in#L39-L58

Probably this isn't firing for some reason.

If the symlink approach is becoming too fragile, another thing we could do is try building directly on an openSUSE container. I tried this at one point a few months ago; you can find the Dockerfile here:

https://github.com/rstudio/rstudio/blob/master/docker/jenkins/Dockerfile.opensuse-x86_64

**Comment by gsgxnet** [comment]
Similar issues here.
The symlink had worked before but is failing now on OpenSuse Tumbleweed latest update version. (Re)Tried with newest -1.2.370 fedora rpm daily built.

Without the link, i get the usual error:
rstudio: error while loading shared libraries: libcrypto.so.10: cannot open shared object file: No such file or directory  

When the libcrypto.so link is set, this is the new error:
/usr/lib/rstudio/bin/rsession: /usr/lib64/libcrypto.so.10: version `libcrypto.so.10' not found (required by /usr/lib/rstudio/bin/rsession)

I have no clue how to use the docker image to build from source.

**Comment by gsgxnet** [comment]
found an other issue in the setup.
There is since 13.x no more an /etc/SuSE-release file to determine the OS version.

see e.g.: https://forums.opensuse.org/showthread.php/492084-openSUSE-13-1-etc-SuSE-release-is-deprecated and links within. 

This problem will make the `rstudio/package/linux/rpm-script/postinst.sh.in` script not workimg as expected on newer version of OpenSuse distributions. 
Since 13.x is deprecated since some years - we had Leap 42.1, 42.2 and 42.3 and now 15.x is in development and there is also the rolling release Tumbleweed, i would suggest an update to the standard conformant `/etc/os-release`

`cat /etc/os-release`
```
NAME="openSUSE Tumbleweed"
# VERSION="20180225"
ID=opensuse
ID_LIKE="suse"
VERSION_ID="20180225"
PRETTY_NAME="openSUSE Tumbleweed"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:tumbleweed:20180225"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
```

**Comment by diloreto** [comment]
Hi - I'm trying to install RStudio Server by following the instructions [on this page](https://www.rstudio.com/products/rstudio/download-server/), and running into the same issue. I don't want to create symbolic links and believe the application should be updated for the latest libssl libraries. 

When can we expect an updated binary?

`./rserver: /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0: version 'OPENSSL_1.0.0' not found (required by ./rserver)`

**Comment by diloreto** [comment]
Actually running Linux Debian 4.9. Thanks for the URL, will install from that.

**Comment by kevinushey** [comment]
But this issue was opened for launch failures with OpenSUSE -- if you're having issues launching RStudio on a separate platform, please file that as a separate issue and include your system information in the report.

**Comment by gsgxnet** [comment]
I can confirm the newest dailies RStudio desktops can be installed and used without issues on openSUSE Leap 42.3 and Tumbleweed.  I will try out the newest openSUSE 15 some time soon and will report if there are (no) problems.

Thanks a lot for all that support!
