### ISSUE TITLE
Code completion error

### ISSUE THREAD

**Issue by etienne-s** [rstudio/rstudio#2144]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.419
    OS Version      : Windows 7 x64
    R Version       : 3.4.3

### Steps to reproduce the problem

1. Create this dataframe: `df <- data.frame(id = 1, source_id = 1)`
2. Start typing the following command: `df %>% left_join(source %>% select(aaaaa))`

### Describe the problem in detail

- A tooltip is displayed: "R code execution error"
- The following error message is repeatedly printed:
```
Error in leftData[completions] : 
  object of type 'closure' is not subsettable
```

![bug autocomplete rstudio](https://user-images.githubusercontent.com/22758616/35866204-d2ec0c5c-0b56-11e8-8f21-d993eaac86a1.PNG)

**Comment by ronblum** [comment]
@etienne-s Thank you for the report. There are two issues here:

1. I can reproduce the problem. However, the code itself contains errors; for example, I believe `source` is meant to be `source_id`. I'm not sure exactly what the code is meant to do, so I can't correct it. Here is an example of code using `left_join()` that could be helpful:

```
library(dplyr)
df <- data.frame(id = c(1, 2, 3, 4), field = c("a", "b","c","d"))
df %>%
  left_join(df, by = "id")
```
2. That said, the error message is written to the console every time the letter _a_ is typed (after the first few). It's unclear whether or not it should be written to the console as the code is being written, and it ideally wouldn't be written with every keystroke. So, I will mark this as a bug for now.

Thank you!

**Comment by etienne-s** [comment]
@ronblum Thanks for the answer.

I actually meant `source` and not `source_id`.
This is a minimal example built from a more complex case, but the idea is as follows:
- A dataframe named `source` already exists.
- I join `df` with some columns of `source`
So the entire command is more like:
```r
df %>%
  left_join(source %>% select(source_id, fieldA, fieldB), by = "source_id)
```

**Comment by colearendt** [comment]
`source` in base R is a function (type `closure`) that calls another file with R code in it.  It looks like that is what you are referring to here.  It is best not to name data.frames after existing base R functions (like `t()`, `source()`, `summary()`, and others), but if you do, then you need to include the definition of the data.frame in your [reprex](http://reprex.tidyverse.org/).

```r
source
#> function (file, local = FALSE, echo = verbose, print.eval = echo, 
#>     exprs, spaced = use_file, verbose = getOption("verbose"), 
#>     prompt.echo = getOption("prompt"), max.deparse.length = 150, 
#>     width.cutoff = 60L, deparseCtrl = "showAttributes", chdir = FALSE, 
#>     encoding = getOption("encoding"), continue.echo = getOption("continue"), 
#>     skip.echo = 0, keep.source = getOption("keep.source")) 
#> {
...
```

That is the reason for the error (you cannot left join a function to a data.frame).

**Comment by etienne-s** [comment]
@colearendt Thanks, I'm aware that `source` is a base function, but here the problem seems to rather come from `df`, which is also a function (from the base package `stats`). I agree that naming objects after existing base R objects is not a best practice, but it happens quite often.

I can reformulate for the sake of clarity. The following code:

```r
library(dplyr)
df <- data.frame(id = 1, animal_id = 1)
ref <- data.frame(animal_id = 1, fieldA = "a", fieldB = "b")
df %>%
  left_join(ref %>% select(animal_id, fieldA), by = "animal_id")
```
is valid and is run by without any problem if you paste it into RStudio. However, if you _type_ it one character at a time, you get an "R code execution error" tooltip and a bunch of error messages.

**Comment by colearendt** [comment]
Yes, great call-out :) Also true for `df`, too.  Thanks for the extra clarification - that reprex is great to really highlight the bug!

**Comment by statsandthings** [comment]
RStudio Edition : Desktop
    RStudio Version : 1.1.383
    OS Version      : Windows 10
    R Version       :  3.4.3

For me this issue is reproducible without having to execute any code. Simply editing in the source pane triggers the error. Let me explain.

First off - I do not save my workspace to .RData and I do not restore .RData into my worspace upon startup. I can fire up a totally fresh console, paste the code shown below, and I get the same error above repeated in my console after each key press on my keyboard. `Error in rightData[completions] : object of type 'closure' is not subsettable`

The trigger for this error is slightly different though. Just copy/paste syntax below into a blank source pane. Place your cursor on line 15, just after the letter D. For me this is position `15:23`. Start typing random characters on your keyboard. After entering ~50 characters this `'closure' is not subsettable` error will start firing off with each subsequent keypress. Sometime you don't even need to bang out ~50 characters, it'll start happening sooner. I also get the hovering `R code execution error` in my source pane.

NOTE: I tried this same procedure on my Linux box with the same versions of R and R Studio. I was unable to reproduce this issue under Linux. Only happens on my Windows machine. @etienne-s are you able to reproduce this error as well utilizing my technique?

```
data_frame %>% 
  left_join(
    read_tsv("data.txt") %>% 
      select(
        `Column A`, 
        ColumnB, 
        `Column C`, 
        `Column D`, 
        `Column E`
      ) %>% 
      rename(
        CA = `Column A`,
        CB = ColumnB,
        CC = `Column C`,
        CD = `Column D`
      ), 
    by = "VariableX"
  ) %>% 
  left_join(
    read_tsv("new_data.txt"), 
    by = "date"
  )
```

**Comment by etienne-s** [comment]
@statsandthings I've just tried an no I can't reproduce it. Maybe it's because you use an older version of RStudio.

**Comment by statsandthings** [comment]
@etienne-s I just installed R Studio version 1.1.423 and my error is still occurring. Strange it's not reproducible on your machine. I'll paste an animated GIF screen capture below showing what's happening. Is this similar to your situation?

https://s10.postimg.org/5c93je6cp/Issue_2144.gif

Note at the beginning of the gif the console is empty, completely black, and then starts populating with all the errors as I type.

![](https://s10.postimg.org/5c93je6cp/Issue_2144.gif)
