### ISSUE TITLE
Printer and zooming icons don't work in History pane

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#2191]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.342
    OS Version      : MacOS 10.12.6 (Sierra)
    R Version       : 3.4.3

### Steps to reproduce the problem

1. Go to the "Help" pane
2. Click on printer ("Print topic") or box-and-arrow ("Show in new window") icons at the top of the pane

### Describe the problem in detail

The "Print topic" and "Show in new window" buttons in the Help pane don't result in printing or a new window. They do depress nicely, but nothing happens.

By comparison, these do work:
- The arrows and the home button in the History pane
- "Show in new window" in the Viewer and Source panes

### Describe the behavior you expected

A print dialog or a new window with the current help page.

This is a regression in 1.2—it works in 1.1.423.

**Comment by kevinushey** [comment]
The print issue is a Qt bug: https://bugreports.qt.io/browse/QTBUG-53745

**Comment by jmcphers** [comment]
Show in New Window works now.

I've just removed the Print button instead of trying to make it work. I don't think many people are printing hard copies of the documentation, and for those that are there are other ways to do it (you can for example just look it up online and print it from your browser, presuming you have internet access). We'll see how much pushback we get from this but I think other work we're doing in 1.2 is more important.

**Comment by ronblum** [comment]
Verified on Desktop and Server 1.2.893.
