### ISSUE TITLE
4 Rstudio IDE's open at once

### ISSUE THREAD

**Issue by tcratius** [rstudio/rstudio#2225]
### System
    RStudio Edition : 
    RStudio Version : 3.4.3 (Guessing at the moment as sessionInfo() is not working)
 
    OS Version      : "Linux Mint 18.3 Sylvia" 
    R Version       :  3.4.3 (2017-11-30)

### One Rstudio IDE opens with project.

 No worries

**Comment by ronblum** [comment]
@tcratius To make sure I understand correctly:
1) Are you going into the file system and double-clicking on the Project.Rproj file? Or are you first running one instance of RStudio and opening the project from within it?
2) Do you mean that four instances start up, and one of them works while the rest hang? Or do they all hang?
3) To see what version of RStudio you're running, open RStudio and click on Help -> About RStudio. The version will likely be something like 1.1.383 or 1.1.423.

**Comment by tcratius** [comment]
Hi Ronblum,

1. I am going to the file system and double-clicking on the Project.Rproj file.  It doesn't do it when open it from an instance of Rstudio.  Probably shouldn't do the former.
2. All of the instances hang.
3 Version 1.1.419
4. Sorry for being a pain and didn't see the message till now

**Comment by jmcphers** [comment]
Unfortunately we can't offer support for Linux Mint, and this problem is specific to Mint (it seems that somehow its version of file associations has multiple RStudio entries). We also haven't had any other reports in almost two years. If you're still seeing the issue, we suggest looking at file associations in Mint (https://forums.linuxmint.com/viewtopic.php?t=170973) or opening a thread on our community forum: https://community.rstudio.com/c/rstudio-ide
