### ISSUE TITLE
Cmd-M isn't minimizing the current window

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#2234]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.353
    OS Version      : MacOS 10.12.6 (Sierra)
    R Version       : 3.4.3

### Steps to reproduce the problem

Click cmd-M

### Describe the problem in detail

Clicking cmd-M typically minimizes the window of Mac applications. However, in RStudio 1.2, it does nothing. It did work in previous versions, such as 1.1.423.

### Describe the behavior you expected

The window would be minimized and be shown in the taskbar instead of the screen.

**Comment by kevinushey** [comment]
What keybinding is shown in the `Window -> Minimize` menu for you? For what it's worth, I have:

![screen shot 2018-02-20 at 10 10 31 am](https://user-images.githubusercontent.com/1976582/36441060-4d4325ce-1626-11e8-8441-9f99121040d8.png)

and that keybinding works as expected. Note that I rebound my Minimize shortcut as I have only ever accidentally minimized a window on macOS, since I can never figure out how to re-display a minimized window.

**Comment by ronblum** [comment]
It's bound to ctrl-M in 1.2.353 and to cmd-M in 1.1.423. Was it intentionally changed to ctrl instead of cmd?

**Comment by kevinushey** [comment]
It was not! That sounds like the cause of the underlying issue.
