### ISSUE TITLE
FreeBSD port: TypeError: undefined is not an object (evaluating 'window.desktopHooks.notifyRCrashed')

### ISSUE THREAD

**Issue by yurivict** [rstudio/rstudio#2242]
Version 1.1.409 on FreeBSD 11.1 amd64 fails during run:

```
"TypeError: undefined is not an object (evaluating 'window.desktopHooks.notifyRCrashed')"
```
This has been going on for a while with more than one user.
I am a maintainer of the port, but I have no idea why does this happen.

Please advise how to resolve this.

The port is here: https://svnweb.freebsd.org/ports/head/devel/RStudio/

**Comment by yurivict** [comment]
@jmcphers @kfeinauer 
Hi guys,

You are the latest committers. Maybe you could help with this problem?
It is completely broken on FreeBSD now, and users complain.

Yuri

**Comment by jmcphers** [comment]
It sounds like this error isn't from the official RStudio builds but from a build compiled externally from pre-release sources for an unsupported platform (FreeBSD). We can't generally offer support for these builds since we don't have insight into how they are produced.

That said, the error suggests that your user's R sessions are crashing. This might be related to RStudio but could also be a variety of other things. Could you have one of the users who is experiencing crashes describe the problem in detail on our community forum?

https://community.rstudio.com/c/rstudio-ide

Hope this helps in resolving the issue!

**Comment by yurivict** [comment]
https://community.rstudio.com/t/rstudio-breaks-on-freebsd-typeerror-undefined-is-not-an-object-evaluating-window-desktophooks-notifyrcrashed/5481
