### ISSUE TITLE
RStudio responds very slowly under Ubuntu 16-04 LTS

### ISSUE THREAD

**Issue by codingbutstillalive** [rstudio/rstudio#2244]
Hi there,

I recently updated RStudio to its latest version. I am running it under Ubuntu 16.04 LTS as a Guest OS in VirtualBox. Since the update, the IDE is very slow - in almost every aspect, i.e. scrolling, opening files and so on. 

Can anyone help? This is like the worst thing that could happen!!!

**Comment by jmcphers** [comment]
Sorry, we would need a lot more information to diagnose this! If you need to revert to an older version, you can do so here:

https://support.rstudio.com/hc/en-us/articles/206569407-Older-Versions-of-RStudio

**Comment by codingbutstillalive** [comment]
I am sorry. But you could have asked for the information that you need. I don't think it's wise to just ignore this bug.

**Comment by kevinushey** [comment]
You can re-open and provide the information necessary for us to diagnose this issue:

- What is your host operating system?
- What version of VirtualBox are you using?
- Do you have 3D acceleration enabled in VirtualBox? The rendering engine in the newest daily builds of RStudio benefit greatly from the presence of 3D acceleration.
- What other details can you share about your environment?

In order for us to resolve this, we need to be able to reproduce the issue locally, and so that implies us being able to replicate your environment as closely as possible.

For what it's worth, I've seen similar lagginess with VirtualBox and my experience has been that it doesn't handle 3D acceleration as well as other virtualization solutions (e.g. VMware, Parallels) and so have avoided using it.
