### ISSUE TITLE
Notebook viewer sends clip() to wrong device

### ISSUE THREAD

**Issue by jeroen** [rstudio/rstudio#2290]
The notebook viewer seems to override any devices opened by the user in order to display all graphics inline, but it seems to fail to capture calls to open a new page in the device.

Below is the literal example for `?clip`. It works as a chunk it works, but if we run it line-by-line it fails:
````r
```{r}
x <- rnorm(1000)
hist(x, xlim = c(-4,4))
usr <- par("usr")
clip(usr[1], -2, usr[3], usr[4])
hist(x, col = 'red', add = TRUE)
clip(2, usr[2], usr[3], usr[4])
hist(x, col = 'blue', add = TRUE)
do.call("clip", as.list(usr))
```
````

This is what I get (rstudio  1.1.419):

<img width="1792" alt="screen shot 2018-02-28 at 2 27 00 pm" src="https://user-images.githubusercontent.com/216319/36789928-7ddc519c-1c93-11e8-8e6b-de70cd5b365d.png">

**Comment by jmcphers** [comment]
This is an unfortunate limitation of the way graphics work in notebook chunks. When you execute a set of lines from a notebook chunk -- whether one, some, or all -- a capturing graphics context is created. When the line(s) are done executing, it's removed. This means that you can't always run things line-by-line if they rely on building up state in the context.

The solution is a little messy; we basically need to open the graphics context when you run a line from a chunk and *leave it open in case you decide to run more lines from that chunk*. This is messy because it involves back-tracking to close things off once you've executed other code. It probably also means that we need to draw and show intermediate states in the graphics device, because when running line-by-line we have no guarantee that any additional lines will be run.

**Comment by jeroen** [comment]
@jmcphers ok but that may not be the full story. Note that in https://github.com/ropensci/magick/issues/114 we get this issue even when running a single line.
