### ISSUE TITLE
Unable to copy viewer pane cell values when using IE11

### ISSUE THREAD

**Issue by hdykiel** [rstudio/rstudio#2351]
### System details

    RStudio Edition : Server
    RStudio Version : unknown
    OS Version      : unknown
    R Version       : unknown
    Browser: Internet Explorer 11 

### Steps to reproduce the problem
`View(iris)`

### Describe the problem in detail
In view pane, you are unable to select or highlight a cell value to copy & paste elsewhere.

### Describe the behavior you expected
Cursor should highlight cell value when it is double clicked, as it does with RSP on chrome and the desktop IDE. The open source edition was also reported to work correctly on IE11, but not the pro.

Feature request: be able to select cells or a range of cells with the cursor and move around the table with the keyboard arrow keys (as you would in excel or SAS).

**Comment by dfalty** [comment]
I'm able to reproduce this with RSP 1.1.442 on Win 10 with IE 11.

**Comment by ronblum** [comment]
[Created #2359 for the enhancement request.]

**Comment by d-matsubara** [comment]
I inform you our system details

RStudio Version  : RStudio version 1.1.383

OSVersion : Red Hat Enterprise Linux Server release 6.4 (Santiago)

R Version : R version 3.4.1 (2017-06-30) -- "Single Candle"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-redhat-linux-gnu (64-bit)

**Comment by jmcphers** [comment]
A fun one. It turns out that IE11 applies the CSS rules for the `<body>` tag to the `<iframe>` tags inside the `<body>`. I cannot imagine why it does this but I'm sure someone's legacy app depends on it. The `user-select` properties we set on RStudio's `<body>` were being inherited by the `<iframe>` that hosts the data viewer -- and by all the other frames in RStudio, too (you also couldn't select text in the Viewer pane for example). 

@hdykiel should be fixed in the dailies shortly; thanks for reporting!
