### ISSUE TITLE
Help sometimes opens in the browser

### ISSUE THREAD

**Issue by hadley** [rstudio/rstudio#2391]
1. Start a fresh session of RStudio
2. Create R script containing this code

    ```R
    library(MASS)
    rlm
    ```

3. Put cursor in `rlm` and press F1
4. Click "MASS" in help window
5. Help page opens in browser

**Comment by ronblum** [comment]
This is what the Help pane looks like in this case:
<img width="681" alt="source_f1_failure" src="https://user-images.githubusercontent.com/31009952/37369680-3409db46-26e0-11e8-9a0e-030a182a68c0.png">

By comparison, using `??rlm` at least bring up search results with links that stay within the Help pane:
<img width="681" alt="console_question_marks" src="https://user-images.githubusercontent.com/31009952/37369705-4284ba42-26e0-11e8-816b-93347ca97afa.png">

Finally, using the source code above, typing `rlm` and so that it autompletes and then clicking on `F1`, will show the MASS::rlm help page:
<img width="677" alt="source_autocomplete_success" src="https://user-images.githubusercontent.com/31009952/37369934-0807b012-26e1-11e8-94d4-2e52605c9bf1.png">

**Comment by hadley** [comment]
Oh good point - this is a simpler reprex:

```R
help("rlm", try.all.packages = TRUE)
```

**Comment by jmcphers** [comment]
This is the same underlying issue as https://github.com/rstudio/rstudio/issues/2260; namely, the problem is that the package links on that first help page are not being fixed up correctly (they have `target="_blank"` which is what causes them to open in a new window)
