### ISSUE TITLE
Suggestions for the code chunk options dialog

### ISSUE THREAD

**Issue by nwstephens** [rstudio/rstudio#2420]
I find the current code chunk options dialog confusing (despite frequently using it for years). 

It currently looks like this:

![image](https://user-images.githubusercontent.com/7519295/37541909-a7dc3628-2932-11e8-88da-9a9fd330b6d5.png)

I think it should look more like this:

![image](https://user-images.githubusercontent.com/7519295/37541873-90e147f6-2932-11e8-8733-ba7f3de8385f.png)

**Comment by kevinushey** [comment]
Some comments:

- Each checkbox really has three states: 'yes', 'no', and 'use default'. How would 'use default' be expressed in your markup?

- The chunk options (for the non-setup chunk) will _always_ apply to only this chunk, so that item is redundant.

We decided to use the generic 'Output: ' select box as we figured there was only a couple permutations of options that made sense, but I agree this is ultimately confusing.

**Comment by nwstephens** [comment]
There are several conventions for three state checkboxes. Here is one that I personally like (there are more to chose from):

![image](https://user-images.githubusercontent.com/7519295/42117821-10f5b002-7bcd-11e8-8193-c9ed7d9f7e71.png)

The `setup` code chunk has a special interaction with this box, different from all other code chunks. The settings in `setup` are called within the R code chunk which applies them to all subsequent code chunks. The settings in all other code chunks are applied within the the code chunk options are are applied only to that code chunk. We should do something to explain to users that the `setup` code chunk is special.

**Comment by jmcphers** [comment]
The tri-state toggle was implemented in https://github.com/rstudio/rstudio/pull/3209, and I think the rest is out of scope for 1.2.
