### ISSUE TITLE
Changed zoom levels

### ISSUE THREAD

**Issue by martj42** [rstudio/rstudio#2487]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.468
    OS Version      : Windows 10
    R Version       : 3.4.4

I'm mostly using rstudio on a Windows 10 laptop with the screen scaled at 150%(as are a lot of people I imagine?). In rstudio 1.1.442(and earlier) I had the zoom under Global Options > Appearance at 100% and I paid no mind to it, it was perfect. However it seems that for 1.2.468 the levels have been changed and 100% is way too big and there isn't an option to recreate the older preferred size. 75% is also too big and 50% is too small. Maybe 100/150 = 67% could be added?

**Comment by ronblum** [comment]
I wasn't able to reproduce this—the levels appear identical for 1.1 and 1.2 under the same screen resolutions. Can you provide some screen shots—and any other information—that might help?

**Comment by martj42** [comment]
I can't think of anything out of the ordinary that could cause it - everything on the laptop is set up very default. I tried deleting the C:\Users\username\AppData\Local\RStudio-Desktop folder, which didn't change it.

I created this gif to illustrate:
https://i.imgur.com/fHxDPUN.gifv

It switches from 1.1 with 100% zoom to 1.2 with 100%, then 90%, 80%, 75% and 50%.

Another thing I noticed is that in 1.2 if I change the zoom with the keyboard shortcut, the options menu will not show the new zoom level. So in the above example where I zoomed to 50%, when I go to the options, it will say the zoom is at 100%.

**Comment by ronblum** [comment]
@martj42 Is this still an issue in [the latest version of RStudio](https://rstudio.com/products/rstudio/download/#download]? We just released an update, 1.2.5033. If so, does changing the rendering make a difference? You can do so in Tools -> Global Options -> Advanced -> Rendering Engine.

**Comment by martj42** [comment]
It's not an issue since I'm not on that laptop anymore. So if no one else was complaining about this, you can consider it resolved. 😉

**Comment by lhansa** [comment]
I'm having this same issue since I got my current laptop around a couple of years ago (a 13-inch HP --don't know how to see the model name). The effect is the same as the one shown on the [previous gif](https://imgur.com/fHxDPUN). I've tried what is explained [here](https://github.com/rstudio/rstudio/issues/3228) but got no improvements. 

As it is explained in the opening question, I also thought that a 67% zooming option was missing, but reading the provided answers I understand that I may be using an unsuitable configuration.

R version: 4.1.0
RStudio version: 1.4.1717
