### ISSUE TITLE
embedded videos spawn in external browser window

### ISSUE THREAD

**Issue by jjallaire** [rstudio/rstudio#2490]
qtwebengine issue

When running this learnr tutorial (https://github.com/rstudio/learnr/blob/master/examples/00-setup/00-setup.Rmd) the embedded videos spawn new external browser windows rather than playing inline.

You can run the tutorial by just opening it in the IDE and clicking "Run Document"

**Comment by kevinushey** [comment]
Seems to be caused by this QtWebEngine bug: https://bugreports.qt.io/browse/QTBUG-56805

The `NavigationType` item is unreliable in QtWebEngine. Since it believes every navigation attempt is a 'link clicked' attempt, we go through `desktop::openUrl()` rather than just letting the URL open as normal.
