### ISSUE TITLE
Arrow keys on iPad physical keyboard don't work in console

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#2514]
### System details

    RStudio Edition : Server
    RStudio Version : 1.2.x
    OS Version      : iOS 11.x
    R Version       : 

### Steps to reproduce the problem
Load RStudio server in Safari on iPad with a physical keyboard. In console, try to use arrow keys to move around current line, or to scroll through command history.

### Describe the problem in detail
Arrow keys don't do anything.

### Describe the behavior you expected
Arrow keys act like they do on other platforms.

See #2186 for same issue in the text editor.

**Comment by esaru** [comment]
Issue: Can't scroll history in console when using up/down arrow keys, when accessing RStudio Server via iPad w/ external keyboard.

Is there a doc with a list of what works and what remains buggy using iPad and RStudio? Currently using the Source pane + option-return to run a line (but Source pane on iPad w/external keyboard has it's own quirks.)

The set up is as follows:

Server: Digitalocean instance of Ubuntu 18.10x64 with all current software

Client: new iPad Pro with Apple external bluetooth keyboard.

Problem exists whether using Safari, Firefox or Chrome. Should be noted that on above iPad setup, up-down arrow keys work fine for in-field entry, such as in the RStudio Source window, Pastebin, or in vim running inside Blink (Esc works too!).  Up/down arrow keys do not, however, work in Terminal Pane either.	

Some posts note that this is putatively fixed in RStudio Server v1.2.1268-3 Preview, and I've updated to this version. When using the iPad, now the up/down arrow keys seem to scroll the screen output, rather than the history.
 
However, all works fine on a laptop, up-down keys in console scroll command history.

System details below.

Many thanks,
Eric


>  Tools>About RStudio gives:
      RStudio Version 1.2.1268
      Build 1257 (87 a96932) 

Works on this (laptop): Mozilla/5.0 (Macinstosh; Intel Mac OS X 10_12_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.3 Safari/605.1.15

Not on this (ipad): Mozilla/5.0 (iPad; CPU OS 12_1_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) FxiOS/15.0b13894 Mobile/16D57 Safari/605.1.15

> sessionInfo()
R version 3.4.4 (2018-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.2 LTS

**Comment by gtritchie** [comment]
This issue is still open, and specifically tracks the fact you can't navigate in the console with arrow keys on iOS, so it is expected it does not yet work.

You can see the list of issues we are aware of on iOS here: https://github.com/rstudio/rstudio/labels/ios.

## Background
Safari on iOS (which also includes any other web browser on iOS as they are all essentially Safari with a different wrapper) does not report arrow keys correctly (i.e. like any other web browser on any other platform in the known universe).

I applied a workaround to the editor component of RStudio 1.2 to make the arrows work (see #2186), but this has not been applied to the remainder of the RStudio interface, including the console and the terminal. We hope to make improvements here in a future release of RStudio.

**Comment by maurizio-manuguerra-mq** [comment]
Tried with the last daily build of RStudio Server (v. 1.3.78) but it still does not work.
It would be great if this could be fixed, or if a workaround could be implemented.

**Comment by gtritchie** [comment]
This has been fixed by Safari improvements in iPadOS 13.1. I tried against both RStudio Server 1.2.1335 and a recent 1.3 build and the arrow keys now work in the console.

**Comment by ronblum** [comment]
Verified on iPadOS 13.3.1 connected to RStudio Server 1.3.929 on Red Hat 7.8.
