### ISSUE TITLE
Git history shows date with UTC instead of local date time

### ISSUE THREAD

**Issue by psychelzh** [rstudio/rstudio#2544]
### System details

```
R version 3.4.4 (2018-03-15)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)
```

### Describe the problem in detail

The history date shows in RStudio Git:

![image](https://user-images.githubusercontent.com/13306020/38130476-d62ec848-3435-11e8-8c11-2abdec6d379d.png)

The real date should be (I am in a +8:00 time zone):

![image](https://user-images.githubusercontent.com/13306020/38130576-3c71a918-3436-11e8-9933-c7d119b71170.png)

**Comment by ronblum** [comment]
@psychelzh The timestamp is correct, but it's displaying the value in UTC, not local time. So what you're looking for is a switch to local time. For example, in `git`, the equivalent would be one of these:
```
git log  --date=iso-local
git log  --date=local
```
Thanks for the suggestion—we'll take it into consideration as we work on development of future version of RStudio.

**Comment by jflycn** [comment]
I am very new to git.
I used the following code in console:
`git config --global log.date local`
It doesn't have any effect on RStudio.

**Comment by mirh** [comment]
Of course it doesn't work, when rstudio is explicitly forcing itself the reading of UTC date
https://github.com/rstudio/rstudio/blob/34c39a3321e1273ede3fe40f7c5683269e03f3a5/src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/dialog/CommitDetail.java#L199
https://github.com/rstudio/rstudio/blob/8af730409bb6d651cc8f6816d136bea91441e7a4/src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/dialog/CommitInfo.java#L52-L57
https://github.com/rstudio/rstudio/blob/e9adaf7cf4b2fb9fb7090669b004b9cae8fcf5df/src/cpp/session/modules/SessionGit.cpp#L1366

**Comment by rgayler** [comment]
I am new to git and just ran into this issue in Rstudio 1.3.104. It took me a while to work out that the commit dates in Rstudio were displayed in UTC, whereas the GitHub equivalents are displayed in the local timezone.

Given that I am not collaborating with someone in a different timezone and not moving between timezones it would be more convenient for Rstudio to display the commit dates in my local timezone. So +1 for the enhancement.

Failing that, how about in the header labels of the history table having "Date (UTC)" and in the header for the selected commit having the date formatted with the timezone included?

**Comment by rgayler** [comment]
Issue still present in 1.4.1103-4

![image](https://user-images.githubusercontent.com/5409051/106998396-8e202400-67d8-11eb-9723-c158612b599a.png)

I suspect the least effort enhancement would be to change the Date column label in the table of commits to "Date (UTC)" and the Date label for the selected commit to "Date (UTC)". That should alert the user to think about time zones.

**Comment by colearendt** [comment]
Agree!

**Comment by m-macaskill** [comment]
The situation is now perhaps worse (for much of the world): the date column has reverted from the ISO standard of `YYYY-MM-DD` shown in the screenshot above to now be the ambiguous US convention of `MM-DD-YY`.

This issue is current as at RStudio 2022.02.0+443 "Prairie Trillium" Release for Mac. 

Is it possible to revert to the ISO standard, or at least provide a setting for users to control the date format used?

<img width="335" alt="Screen Shot 2022-03-21 at 12 32 37" src="https://user-images.githubusercontent.com/931027/159190847-adc168de-8004-4b3a-b2ba-448eeda074a2.png">

**Comment by ronblum** [comment]
@m-macaskill Thank you for raising this regression! I filed a separate issue for it, #10810, so that we keep this issue for the enhancement request.

**Comment by gtritchie** [comment]
I have implemented the smallest fix, adding (UTC) to the labels as was suggested.

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2022.06.0-daily-282 on MacOS 12.3 by going to
- Git Pane -> Diff -> History

**Comment by professorbeautiful** [comment]
I'm grateful for the UTC label addition.
So why does it matter?
Showing UTC instead of local time is a problem because I am trying to report on daily activities and progress.
Can't easily ascribe to the correct date when Greenwich is in the wee hours and the rest of us haven't gone to bed yet. 
OTOH, subtracting 4 hours... or is it 5?... is good mental gymnastics. Over and over.
