### ISSUE TITLE
modify behavior of 'asString()'?

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#2589]
See `r::sexp::asString()` here:

https://github.com/rstudio/rstudio/blob/93e800ce333e5c929f36b195b3e3a6d54e4d1b8d/src/cpp/r/RSexp.cpp#L123-L126

If one passes an R `NULL` to this function, one gets the unexpected result `"NA"`. This can be avoided by calling `safeAsString()` instead, but I wonder if we should just make `asString()` convert `NULL` to the empty string by default (since I don't think converting to `"NA"` is ever what we want).

**Comment by mikebessuille** [comment]
Ooops setting this back to Developer.  This is clearly an internal code refactoring thing.

**Comment by kevinushey** [comment]
Marking as 1.5 since this is a small + safe refactor that could prevent unintended bugs down the line.

**Comment by kevinushey** [comment]
Marking as "good first issue"; it's a good excuse to go spelunking through our R interface.

**Comment by cm421** [comment]
Looks like this has already been fixed by @kevinushey in #7263

https://github.com/rstudio/rstudio/blob/a363a0ba8639506135299f597e0d5116a5fd16df/src/cpp/r/RSexp.cpp#L174-L177

Particularly on line 155 of `asStringImpl()`:
https://github.com/rstudio/rstudio/blob/a363a0ba8639506135299f597e0d5116a5fd16df/src/cpp/r/RSexp.cpp#L144-L156

Checking for a `NULL` `SEXP` pointer by checking length is unexpected, but I'm assuming it's because it's a JSON object, an empty size equates to a `NULL` pointer?

**Comment by kevinushey** [comment]
Looks like you're right! Although to clarify some of the language:

- In this case, the object isn't a null pointer; rather, it's R's "null" object. This is normally called `NULL` from R code, and `R_NilValue` from C / C++ code.

- The R objects here aren't JSON objects, they're real R `SEXP`s (which are pointers to `SEXPREC`s, which are basically the core R data structure for any R object).

- Behind the scenes, `R_Nilvalue` implemented as a zero-length R pairlist, which is why this length check actually catches this -- R's `NULL` has 0 length.

Ultimately though, you're right -- it looks like I unintentionally fixed this before. 😬
