### ISSUE TITLE
Rmd 'chunk output in console' and 'chunk output inline' have different working dirs

### ISSUE THREAD

**Issue by DesiQuintans** [rstudio/rstudio#2595]
### System details

    RStudio Edition :  Desktop
    RStudio Version :  1.1.383
    OS Version      :  Win 7 64-bit
    R Version       :  3.4.2

### Steps to reproduce the problem

1. Make an R project in some folder.
2. Make an Rmd file in a subfolder inside the project folder.
3. Run `getwd()` inside the Rmd with "Chunk Output Inline" and "Chunk Output in Console" and compare the results.
4. With Chunk Output Inline, the location of the Rmarkdown document is the root. With Chunk Output in Console, the R project is the root.

### Describe the problem in detail

Displaying the output in either the document or the console should be a matter of personal preference, but it turns out to have an actual effect on how you access other files within the project.

### Describe the behavior you expected

I expected that the project directory would always be the root, regardless of where the Rmarkdown output was viewed.

**Comment by DesiQuintans** [comment]
| Knit Directory →        | Document  | Project   | CWD       |
|-------------------------|-----------|-----------|-----------|
| Chunk Output Inline     | Rmd dir   | Proj root | Proj root |
| Chunk Output In Console | Proj root | Proj root | Proj root |

**Comment by jmcphers** [comment]
This is kind of by design. "Chunk output in console" causes the code to be executed just like an R script would be--each line is literally emitted to the console. This is exactly how how code execution in R Markdown documents used to work in RStudio 0.99, before notebooks and knit directories and the like arrived. 

The setting's name is thus somewhat misleading; it not only changes the output mode but also the execution context. It might be better named *make it work exactly like it used to*.

It wouldn't be impossible to change the working directory just like we do for code executed inline, but it'd undoubtedly break some workflows as there would then be no obvious way to revert to the previous behavior. Some possible mitigations:

1. Rename these options to something like "Execute chunks in notebook" and "Execute chunks at R console" to improve clarity (it might be less surprising that chunks executed "at the R console" don't get the working directory "in the notebook" applied), or

2. Begin respecting the Knit Directory for code executed in the R console, but default the Knit Directory to Current Working Directory (maintaining the legacy defaults) when chunk output is set to Console.

**Comment by DesiQuintans** [comment]
I think #2 is the best option, I'd like it if the user was also warned about the unseen working directory change. I stumbled upon this issue when my script was no longer able to load a .csv because it was looking in a different place, and it took me a while to troubleshoot.

**Comment by jdblischak** [comment]
Would it be possible to configure the default setting of the Knit Directory in the RStudio project settings? I disable the inline preview, so this isn't a problem for me. But when collaborators try to run my R Markdown files that are saved in subdirectories of the project, the code fails because the working directory is wrong (because Document Directory and inline preview are both the default settings).

**Comment by CamiloEr** [comment]
I noticed that if I use the traditional `setwd("C:/New/Directory")` in only one chunk, the first one or where I need it, with the **console mode**, it remains so for all the document (all chunks), als a .R script. This is obviosly not recomended when *knit* (if you don't put opts_knit$set(root.dir:.) in setup), but is a nice (but contradictory?) workaround.

The good thing is that this workaround doesn't have any problem when knit. I suspect that `setwd()` only rewrites the same (changed) directory in that chunk and the others are simply modified by `opts_knit$set(root.dir:.)`.

See my similar question:  https://community.rstudio.com/t/knitr-opts-knit-set-root-dir-ignored-when-chunk-output-type-console/27665/2

or

https://stackoverflow.com/questions/55481128/knitr-opts-knitsetroot-dir-ignored-when-chunk-output-type-console
