### ISSUE TITLE
Add support for openSUSE 15, Tumbleweed, and OpenSSL 1.1

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#2606]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.516
    OS Version      : openSUSE 15.0 beta & Tumbleweed
    R Version       : 3.4.4

### Steps to reproduce the problem

Install RStudio Desktop on openSUSE 15.

### Describe the problem in detail

The symlinks to the libssl and libcrypto libraries don't get created.

### Describe the behavior you expected

openSUSE 15 is currently in beta and will be live in May or June, 2018. It comes with libssl.so.1.1 and libcrypto.so.1.1. The installer should recognize this version and the symlinks should point to these libraries.
<img width="409" alt="osrelease" src="https://user-images.githubusercontent.com/31009952/38391926-c6cad988-38f3-11e8-9569-4284c3cc9b0e.png">

**Comment by ronblum** [comment]
I think openSUSE Tumbleweed has the same, or a similar, issue. RStudio Desktop 1.1.442 starts fine, but 1.2.510 similarly can't find the libssl and libcrypto files. The contents of /etc/os-release are different: Tumbleweed is a rolling release, so the `VERSION_ID` field changes is often; it's in the format YYYYMMDD. 

```cat /etc/os-release```
````
NAME="openSUSE Tumbleweed"
# VERSION="20180313"
ID=opensuse
ID_LIKE="suse"
VERSION_ID="20180313"
PRETTY_NAME="openSUSE Tumbleweed"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:tumbleweed:20180313"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
````

_[Note: 1.2.510 needed updates to several packages, including ```libgstreamer```, before getting to this point.]_

**Comment by jmcphers** [comment]
Unfortunately I don't think it's as simple as updating our OS check and adding symlinks. We build against OpenSSL 1.0 which is [not ABI compatible with OpenSSL 1.1](https://abi-laboratory.pro/tracker/timeline/openssl/). So we will need to do one of the following:

1. Bundle OpenSSL with RStudio and use RPATH to load it in favor of the system OpenSSL. We already do this on Mac and Windows, though it's much easier there because we don't have nearly as many platform differences to concern ourselves with.
2. Create a separate RStudio version which is built against the newer OpenSSL. We already do this for Debian 9 which has an OpenSSL that is not ABI compatible with previous versions of Debian.

If we're doing all this we may also want to revisit the attempt to build our SuSE builds on SuSE itself; I tried this last year but got stuck on some dependencies (another hangup is that the relationship between SLES and OpenSuSE is much more distant than the one between CentOS and RHEL).

**Comment by jmcphers** [comment]
The reason 1.1 works fine is that in 1.1 RStudio Desktop doesn't require or use OpenSSL at all. In 1.2 however, it's used both by Chromium and by RStudio Desktop itself for crypto.

**Comment by jmcphers** [comment]
Note that we only produce OpenSUSE 15 builds for the desktop; on the server, the `websocketpp` library we use does not build with OpenSSL 1.1.

https://github.com/zaphoyd/websocketpp/issues/725
