### ISSUE TITLE
On-demand reticulate upgrade to run Python code results in error

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#2630]
### System details

    RStudio Version : 1.2.536
    OS Version      : MacOS High Sierra
    R Version       : 3.4

### Steps to reproduce the problem

1. Install reticulate 1.5 or earlier.
2. Create a new Python file, and add a line of code to it (such as `print(42)`)
3. Press Cmd+Enter to execute the line of code.
4. A prompt appears asking to install a new version of reticulate to execute Python code; accept it
5. reticulate 1.6 is installed, but the following error appears:

    > reticulate::repl_python()
    Error: 'repl_python' is not an exported object from 'namespace:reticulate'
    
    > print(42)
    [1] 42

### Describe the problem in detail

There are two problems here:

1. The new version of reticulate is not available at the time we attempt to invoke the REPL (we may need to restart R to pick up the new version of reticulate)
2. The Python code shouldn't be sent to the R console if `repl_python()` failed.

**Comment by jjallaire** [comment]
In these cases I think it's better if the prompted update just result in a no-op (then the user can try again after the installation has occurred)

**Comment by kevinushey** [comment]
One saving grace is that this issue will only occur if the `reticulate` namespace is already loaded before the first attempt to run some Python code. If it's not loaded, installation + load goes fine and the new methods are picked up.

It seems to me the dependency manager should detect whether a package is already loaded / attached, and if so, prompt the user to restart R before package installation. (This is especially important for Windows, since installation of `reticulate` could fail if the package is loaded and the `reticulate` DLL is locked). I think we display this prompt for 'normal' package installation, e.g. `install.packages()`, but we neglect to do so through dependency manager installs.

**Comment by kevinushey** [comment]
Given that reticulate 1.8 is now on CRAN and users are relatively proactive about upgrading reticulate I think it's okay to punt on this one.

**Comment by jmcphers** [comment]
Seems fair to me!
