### ISSUE TITLE
arrow keys sometimes stop working in Rstudio on Ubuntu

### ISSUE THREAD

**Issue by kendonB** [rstudio/rstudio#2666]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.447
    OS Version      : Ubuntu 16.04
    R Version       : 3.4.3

The problem is intermittent

I am editing a .py file and using the terminal within RStudio and the arrow keys intermittently stop working. When it happens, the main keyboard works fine but the arrow keys and pgup, pgdn stop working.

**Comment by gtritchie** [comment]
What text editor are you using in the terminal?

**Comment by ronblum** [comment]
@kendonB Does it make a difference which shell you're using? I also see an issue on Ubuntu 16.04.4 and 17.10 using Ubuntu Desktop 1.2.573 in which ANSI escape characters are displayed instead of arrow key movement. This only occurs using `sh`; `bash` and `csh` don't have this issue.

When typing the following in the command line:
```
pwd
date
[Up arrow][Down arrow]
pwd[Left arrow][Down arrow]
```

I end up with:
```
$ pwd
/home/ronblum
$ date
Mon Apr 23 04:52:09 PDT 2018
$ ^[[A^[[B
/bin/sh: 21: : not found
$ pwd^[[D^[[C
/bin/sh: 22: pwd: not found
$
```

**Comment by kendonB** [comment]
Sorry, to be clear, I am seeing the issue while the cursor/focus is in the RStudio editor, not in the shell.

**Comment by jmcphers** [comment]
This isn't a regression and we don't have a reproducible case so moving out of 1.2 (feel free to move it back if either of those change!).

**Comment by philmikejones** [comment]
I also experience this problem (arrow keys stop working; pgdn/pgup stoip working). In addition the backspace key stops working, and the behaviour of the delete key changes so that it behaves like the backspace key.

A restart of the R session doesn't affect this. Sometimes the problem can be fixed by focusing/alt+tabbing to a new window and back, but sometimes I have to close down and re-open RStudio.

As for a repro if I manage to isolate the problem I'll of course add one but I haven't yet spotted a clear pattern to the behaviour.

```
> sessionInfo()
R version 3.4.4 (2018-03-15) Platform: x86_64-pc-linux-gnu (64-bit) Running under: Ubuntu 16.04.5 LTS  Matrix products: default BLAS: /usr/lib/openblas-base/libblas.so.3 LAPACK: /usr/lib/libopenblasp-r0.2.18.so  locale:  [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C               LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8      [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8    LC_PAPER=en_GB.UTF-8       LC_NAME=C                   [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C         attached base packages: [1] stats     graphics  grDevices utils     datasets  methods   base       other attached packages: [1] bindrcpp_0.2.2 stringr_1.3.1  dplyr_0.7.8    sf_0.7-1       testthat_2.0.1  loaded via a namespace (and not attached):  [1] Rcpp_1.0.0       rstudioapi_0.8   bindr_0.1.1      magrittr_1.5     units_0.6-2      tidyselect_0.2.5 R6_2.3.0          [8] rlang_0.3.0.1    fansi_0.4.0      tools_3.4.4      grid_3.4.4       packrat_0.5.0    utf8_1.1.4       cli_1.0.1        [15] e1071_1.7-0      DBI_1.0.0        class_7.3-14     rprojroot_1.3-2  assertthat_0.2.0 tibble_1.4.2     crayon_1.3.4     [22] spData_0.2.9.6   purrr_0.2.5      glue_1.3.0       stringi_1.2.4    compiler_3.4.4   pillar_1.3.0     backports_1.1.2  [29] classInt_0.2-3   pkgconfig_2.0.2
```

```
uname -a
Linux ggp13pmj 4.4.0-140-generic #166-Ubuntu SMP Wed Nov 14 20:09:47 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by kevinushey** [comment]
Sorry, but we're still unable to reproduce and so have little idea what might be causing this particular issue.

**Comment by aroman12** [comment]
Same problem here. As BastiHz discovered (Thanks!), after selecting a word (on the editor panel) using the **sequence** press shift, press ctrl, press alt, press M, release all: causes the arrow keys to malfunction (not responding); using press ctrl, press alt, press shift, press M, release all: works fine. 
Using RStudio v. 1.1.463 on Ubuntu 18.04. This does not happen in Windows, same version.

**Comment by sihanwusean** [comment]
It happens to me in Win10 multiple times. To recreate this, simply push Win+Space key (by default, it switches IME) and then the arrow keys will stop working.

**Comment by sihanwusean** [comment]
> 
> 
> It happens to me in Win10 multiple times. To recreate this, simply push Win+Space key (by default, it switches IME) and then the arrow keys will stop working.

The ctrl+shift+alt+M fix the problem! Thanks, aroman12!

**Comment by AghiadHaloul** [comment]
I run into the same issue quite frequently with RStudio 1.2.1335 / Windows 10 Education 64-bit.

Initially, the cursor seemed to randomly stop responding, but after reading the replies here I noticed the issue is mainly triggered by pressing the combination of **Windows key + Space**, which shows a small pop-up to switch the input language in Windows.

**Comment by rysterzhu** [comment]
I run rstudio in web browser by rstudio-server into the same issue. it always happens when I switch IME.

**Comment by sihanwusean** [comment]
> 
> 
> > It happens to me in Win10 multiple times. To recreate this, simply push Win+Space key (by default, it switches IME) and then the arrow keys will stop working.
> 
> The ctrl+shift+alt+M fix the problem! Thanks, aroman12!

I find sometimes this trick doesn't work. One workaround, is every time when you type anything in Rstudio with a wrong IME, DO NOT hit the win+space to switch. Now, minimize the Rstudio window, hit win+space to switch to English/or anything you would like to type, then go back to Rstudio, and you shall be fine.

**Comment by srvanderplas** [comment]
I also get this on Ubuntu 18.04, RStudio version 1.2.1518. Ctrl-Shift-Alt-M (e.g. the default "edit all instances of a variable" shortcut) sporadically causes arrow keys not to function. Pressing the sequence again restores function. 

I've uploaded a diagnostics report that may provide more information - 
[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/3261470/diagnostics-report.txt)

I managed to reproduce the situation a couple of times using the key combination mentioned above, and new errors didn't seem to get added to the log, so I suspect whatever is happening here isn't causing enough of an error to be recorded in the diagnostic log.

**Comment by kevinushey** [comment]
Thanks @srvanderplas! This was the hint I needed in order to be able to reproduce this. I can reliably reproduce the 'stuck' cursor if I quickly press and release the Ctrl + Alt + Shift keys, in that sequence. Does that seem to be the case for you as well?

I also see that, if my cursor is stuck, pressing the Alt key twice will get the cursor un-stuck. Does that seem true for you as well?

Thanks for taking the time to investigate and report what you're seeing!

**Comment by kevinushey** [comment]
Interestingly enough, I cannot reproduce this in the [daily builds](https://dailies.rstudio.com) of RStudio, so this is an issue that may have been fixed when we updated our bundled copy of Ace.

**Comment by SimonCouv** [comment]
I can report the same problem in RStudio Version 1.2.1303 on Ubuntu 18.04.2 LTS. Behaviour is exactly as described by @philmikejones. The combination ctrl+alt+shift is sufficient to reproduce the problem consistently. Repeating the combination, or pressing alt twice, restores the normal behaviour.

**Comment by rysterzhu** [comment]
It seems that happend with Win+space, I recommend you change the shortcut key of switch IME to other combination like "Ctrl + Shift"

**Comment by msberends** [comment]
I can report the same problem on Ubuntu 18.04, R 3.6.0, RStudio 1.2.1541 (latest preview).

Switching to other window and back solves it (temporarily).

**Comment by hazybluedot** [comment]
This has been happening to me as well using Rstudio 1.2.1335 on PureOS. Thanks to @kevinushey, I found that for me pressing Shift + Alt + Ctrl reproduces the problem (not Ctrl + Alt + Shift), and pressing Alt twice, or pressing Ctrl + Alt + Shift fixes it.

**Comment by jannikbuhr** [comment]
I can confirm a similar issue on fedora 30 with gnome 3.32.2 and RStudio version 1.2.1578.
When using a shortcut that requires Shift + Alt, Holding Alt and then Shift works but when Holding Shift and then Alt, the shortcut does not work and instead diables the functionality of the arrow keys unitl the window is left and entered again or Alt is pressed twice.

Additionally, the shortcut to copy a line up (Shift + Alt + Up) does not work (sometimes it does nothing, sometimes it copies the line down instead of up).

**Comment by davfre** [comment]
Confirm an identical issue on Windows 10, RStudio 1.2.1335 (but I've had this issue for the last year or so on several versions on Win 10). Glad to have found the "fix" of pressing Alt twice (or ctrl-shift-alt m) but preventing it from happening in the first place would be nice.

**Comment by kevinushey** [comment]
I believe this issue is solved in the latest release of RStudio (1.2.5001; https://www.rstudio.com/products/rstudio/download/#download)

**Comment by kendonB** [comment]
Still a problem for me. Shift-Alt-Ctrl to reproduce.

**Comment by duccioa** [comment]
Same problem for me on Ubuntu18.04 LTS usign RStudio 1.2.5001, when I use Shift+Alt+Up or Down in this order to copy a line. The line is not copied and the arrows do not work anymore. If I press Alt twice the arrows go back to working normally. If I reverse the order to Alt+Shift+Arrow, it works fine.

**Comment by furiousbean** [comment]
Confirm this bug on both Windows 10 and macOS versions of RStudio. I use Win + Space on both computers to switch keyboard layout. Setting your OS to keep layout for each window may help you to avoid the bug.

**Comment by SimonDedman** [comment]
Sounds like I've got the same issue. With a data frame open as a tab in datasheet view, I can scroll with page up/down for a while, until it displays the 'loading' overlay whereby it refreshes the memory with a new bunch of screens (5 to 10 I'd guess). At which point it seems the focus is lost - I can get it back by clicking on the datasheet with my mouse, so I wonder if it's something to do with the loading popover taking focus and not returning it to the previous sheet, but just orphaning it? Xubuntu 19.10 v1.2.5013.

**Comment by jmcphers** [comment]
Can anyone reproduce this issue with the latest daily builds?

https://dailies.rstudio.com/

There's a new version of Ace in RStudio 1.3, which (as per @kevinushey's comment above) may address this issue.

**Comment by kendonB** [comment]
Looks good. Closing. Thanks!
