### ISSUE TITLE
Run unix program "less" on any file in the terminal tab freezes the terminal.

### ISSUE THREAD

**Issue by professorbeautiful** [rstudio/rstudio#2669]
### System details

    RStudio Edition : Desktop 
    RStudio Version : 1.1.383
    OS Version      :  OSX 10.13.4
    R Version       :  3.4.2

### Steps to reproduce the problem

Open the terminal tab.
Run unix program "less" on any file.
(Shell is bash.)
(This happens every time.)

### Describe the problem in detail
The terminal window is unresponsive.
The menu pick "Interrupt Current Terminal" has no effect.

### Describe the behavior you expected

The customary behavior of "less".

**Comment by gtritchie** [comment]
This is same as #1875. Fixed in the 1.2 dailies if you want to confirm that for your situation (https://dailies.rstudio.com/). Be aware that 1.2 is still under active development and stability can vary from build-to-build.

You can try working around it in 1.1 by making the terminal pane taller than 25 rows (won't fix a terminal that's already stuck, but new ones shouldn't get stuck).
