### ISSUE TITLE
Viewer Zoom results in external browser window

### ISSUE THREAD

**Issue by jjallaire** [rstudio/rstudio#2747]
If you display content in the Viewer, e.g.

```r
library(dygraphs)
dygraph(ldeaths)
```

Then press the Zoom button (on OSX), the Zoom window opens but it's blank, then the content actually opens in an external browser window (that's also blank).

This is a new behavior as I tested this 2 or 3 weeks ago and it behavior as expected. Perhaps related to the sandboxing work? A related clue: If I include an iframe on an external domain in an R Markdown document it also open a new browser window for that iframe's content (this behavior also showed up around the time of the sandboxing work).

@dfalty and @jmcphers I didn't see a way to target bugs for "Preview" but I think this one is worthy of being fixed before we preview.

**Comment by jmcphers** [comment]
The behavior predates sandboxing. I think this winds up happening because we cannot distinguish among navigation types (i.e. we think you're clicking a link, not loading a URL in an IFrame, because both look the same). 

https://bugreports.qt.io/browse/QTBUG-56805

I'll take a look!

**Comment by jmcphers** [comment]
I've fixed this by having the Viewer Zoom window ask the page that opened it if the URL to be loaded is from the Viewer (which allows us to load URLs that would otherwise be forbidden). 

Note however that we still have a bug wherein external URLs that are loaded in IFrames will be opened in separate windows, which is due to the aforementioned QT bug. I'll open a separate issue for that.

**Comment by jmcphers** [comment]
Aforementioned issue opened here: https://github.com/rstudio/rstudio/issues/2756

**Comment by dfalty** [comment]
Verified fixed 1.2.616.
