### ISSUE TITLE
Indenting on soft wrap

### ISSUE THREAD

**Issue by franknarf1** [rstudio/rstudio#2764]
I am used to understanding my code's structure at a glance based on how deeply code is indented.** Unfortunately, for long lines RStudio wraps starting at the first column:

![badwrap](https://user-images.githubusercontent.com/4649190/39873537-37c58538-5439-11e8-8901-62effcc613d9.png)

So that kind of messes with my workflow. To clarify what I mean, compare display of line 245 above, to...

![goodwrap](https://user-images.githubusercontent.com/4649190/39873569-4ca81c54-5439-11e8-8740-a1ef0f6147b1.png)

line 405 here (from notepad++). I also like the little arrow on the right side in this latter picture, but its absence or inclusion isn't a big deal.

**Some more context: I'm looking to use this in an rmd. The table of contents along the sidebar is great for navigating between sections and chunks, but won't help me within a single chunk when I'm informally breaking up code with indentation... I mean like

```
## Do some stuff
##############
# comment on purpose
# and some more

code

# do A

    code
    ecod
    deco
    odec

    # follow side track
    # comment on why
    
        code
        ecod

    deco
    odec

# do B

    code
    ecod
    deco
    odec

## Do some other stuff
##############
```

I guess I would also use it with *.r files, but am sticking with notepad++ for those for now. (Integration with knitr is the killer feature drawing me to use RStudio.)

I brought this up [on the forum](https://community.rstudio.com/t/indenting-on-soft-wrap/8208) in case the feature already existed, and Curtis confirmed that it doesn't and directed me here. I have a couple more links/references there.

**Comment by kevinushey** [comment]
For (developer) future reference, Ace supports this natively with the `indentedSoftWrap` option: https://stackoverflow.com/questions/38208984/how-to-disable-indentation-of-subsequent-lines-in-ace-editor-when-line-wrapping

**Comment by andrewmarx** [comment]
Just came here to make this same request for r scripts and found this. Would be a great feature to have. I'm tired of splitting my function calls across lines, but the lack of an indent for the soft wrap makes it harder to read than it needs to be. It would also be nice if it was intelligent about where the wrap takes place so that a statement like:
```
some_function(foo1 = some_value, foo2 = some_other_value)
```
Doesn't get split up like this:
```
some_function(foo1 = some_value, foo2  
  = some_other_value)
```
But instead does this:
```
some_function(foo1 = some_value,  
  foo2 = some_other_value)
```

Even better if it can automatically match the indent with the other parameters like this:
```
some_function(foo1 = some_value, 
              foo2 = some_other_value)
```
Which is basically what I do manually, but if a variable name changes or I add or remove a parameter, etc, then I have to spend a bunch of time realigning things and it can cause a large number of line changes when I use diff

**Comment by JochenFruend** [comment]
I'd also highly appreciate such a feature in Rstudio! Would make the code much more readable in cases where long lines cannot be avoided.
