### ISSUE TITLE
double-clicking R file gives '127.0.0.1 refused to connect' error on Windows

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#2801]
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.2.639
    OS Version      : Windows 10 64-bit (Version 1803; OS build 17134.48)
    R Version       : R 3.5.0

### Steps to reproduce the problem

Attempt to double-click a file e.g. `test.R` on the desktop.

### Describe the problem in detail

RStudio opens, but a "refused to connect" message is displayed:

![screen shot 2018-05-17 at 9 49 35 am](https://user-images.githubusercontent.com/1976582/40191905-a1da09de-59b7-11e8-9027-cbf2b78373fc.png)

### Describe the behavior you expected

RStudio should open without issue.

**Comment by kevinushey** [comment]
Possibly related: https://github.com/rstudio/rstudio/issues/2365

**Comment by jmcphers** [comment]
Not able to repro in 1.2.657, suspect that it was fixed recently (possibly with @gtritchie's recent fix https://github.com/rstudio/rstudio/commit/82d8ed85fc33ac2b89a130ec27159a20f1e4640c). Let me know if you're still seeing it!

**Comment by mirh** [comment]
Just for the properest records: I could very easily trigger again this issue... after I *accidentally* uninstalled R while I had Rstudio opened. 
Which made R.dll and a couple of others libs remain on their folder (since they were in use). 

In turn this had every next launch fail so badly, because the crude [autodetect](https://github.com/rstudio/rstudio/blob/master/src/cpp/desktop/DesktopRVersion.cpp) mechanism could still find the "installation" anyway, while not detecting that anything but the kitchen sink wasn't anymore.
