### ISSUE TITLE
Feature request: turn of chunk background (make same as non-chunk)

### ISSUE THREAD

**Issue by kmace** [rstudio/rstudio#2837]
Please include a way to turn off chunk background coloring!

![a7ae4b3f4efc332c015fae19045b0707226bc3e4](https://user-images.githubusercontent.com/18296227/40444808-340ccce4-5e7f-11e8-878e-94dcc9403071.png)

**Comment by jmcphers** [comment]
Can you tell us a little more about why you want to do this?

**Comment by kmace** [comment]
Simply visual preference. I find it hard to stare at a matted background
color for hours at a time.

On May 23, 2018 11:59 AM, "Jonathan" <notifications@github.com> wrote:

Can you tell us a little more about why you want to do this?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/rstudio/rstudio/issues/2837#issuecomment-391460088>,
or mute
the thread

**Comment by vikram-rawat** [comment]
I on the contrary why to differentiate more drastically is there a way I can change the background color to light blue or light green or something more distinguishable than just a little darker shade of same color.

Please let me know if you could allow us to change the chunk background color.

**Comment by mine-cetinkaya-rundel** [comment]
Another reason why it would be great to be able to customize the chunk background color is teaching: most projectors do not show the subtle difference between the background colors of chunk and non-chunk areas in a document. It would be good to be able to crank up the contrast for teaching purposes.

**Comment by rdalbanus** [comment]
Agreed. I find staring at this grayish background very tiresome to the eyes.

**Comment by colinjstief** [comment]
I also find that the lack of contrast between text and background in the chunks to be incredibly tiring to the eyes.

**Comment by kmprioliPROF** [comment]
I agree that this would be a really useful feature to implement.

**Comment by dfalty** [comment]
Verified on version 1.2.1090.

**Comment by colinjstief** [comment]
@dfalty Maybe I'm missing something, but isn't the latest RStudio version 1.1.463?

**Comment by dfalty** [comment]
@colinjstief The 1.2 release is available on the daily builds page. 
https://dailies.rstudio.com/

**Comment by brianstamper** [comment]
> I on the contrary want to differentiate more drastically between chunk and written code. is there a way I can change the background color to light blue or light green or something more distinguishable than just a little darker shade of same color.
> 
> Please let me know if you could allow us to change the chunk background color.

Figured out the hack for this. I'm used to doing this on RStudio server because the IDE is in your web browser, so I just use a general CSS browser plug-in to fix things, but here we have to dig a little deeper.

Right-click on the RStudio IDE and select Inspect. Click around and look for the name of the css file for your currently selected editor theme, should be a long hex string ending with .cache.css

![screenshot_20190112_152838](https://user-images.githubusercontent.com/636124/51078196-b97ac800-167f-11e9-83ec-5e121320fb8a.png)

In my case this was for the theme "Tomorrow Night Bright". Then you need to find where this file lives. On Kubuntu Linux I found it in /usr/lib/rstudio/www/rstudio. Now with much experimentation you can figure out which elements you need to change (they are not so easy to find with the Inspect tool).

I wanted the code chunks to be black and the non-code chunks to be just slightly shaded, so I changed two things. To change the overall background, you want to find this:

    .ace_editor, .rstudio-themes-flat.ace_editor_theme .profvis-flamegraph, .rstudio-themes- 
    flat.ace_editor_theme, .rstudio-themes-flat .ace_editor_theme {
       background-color: #000000;
       color: #DEDEDE
     }

And to change the color of code chunks, you are looking for this:

    .ace_marker-layer .ace_foreign_line {
      position: absolute;
      z-index: -1;
      background-color: #212121;
    }

And just change those background colors however you like. Restart RStudio to see the change.

Good luck!

**Comment by brianstamper** [comment]
In the current builds of RStudio these have less cryptic names as .rstheme files, on my system in `/usr/lib/rstudio/resources/themes`. Edit the same CSS block I mentioned above with `.ace_foreign_line` to change the background color of Rmd code chunks.
