### ISSUE TITLE
rstudio 1.2.637 crashes when attempting to view any vignette from the drake package

### ISSUE THREAD

**Issue by lepennec** [rstudio/rstudio#2868]
### System details
    RStudio Edition : Desktop
    RStudio Version : 1.2.637
    OS Version      :  Fedora 27
    R Version       :  3.5.0

### Steps to reproduce the problem
1) install drake if it is not installed
2) browse any vignette from drake
3) rstudio crashes

### Describe the problem in detail
Rstudio crashes when attempting to view any vignette from this package. The vignettes work for any other packages I've tried. Note that the corresponding html files are displayed correctly by Firefoxor Chrome.

### Describe the behavior you expected
Rstudio should not crash...

**Comment by kevinushey** [comment]
Thanks for the bug report! This should be fixed in the latest daily builds of RStudio, although I note that because the vignette attempts to load content from an external website (in an `iframe`) those `iframe`s end up being opened in an external browser, which is not ideal.

Would it be worth recommending to the `drake` package authors that the vignettes should be self-contained, so that they might work in an environment where e.g. one does not have internet access?

**Comment by ronblum** [comment]
@lepennec Is the issue resolved in the latest builds?

**Comment by lepennec** [comment]
Yes, the issue is solved.
