### ISSUE TITLE
1.2.637 build fails: error: use of undeclared identifier 'initialize'

### ISSUE THREAD

**Issue by yurivict** [rstudio/rstudio#2888]
```
/usr/ports/devel/RStudio/work/rstudio-1.2.637/src/cpp/desktop/DesktopInfo.cpp:150:4: error: use of undeclared identifier 'initialize'
   initialize();
   ^
1 error generated.
*** [src/cpp/desktop/CMakeFiles/rstudio.dir/DesktopInfo.cpp.o] Error code 1
```

FreeBSD 11.1
RStudio is built from the port.
qt5-core-5.10.1

**Comment by kevinushey** [comment]
This is because `DesktopInfo.cpp` contains code that only handles Linux, macOS and Windows. FWIW this could be patched with something like:

```
#ifdef Q_OS_FREEBSD
void initialize() {}
#endif
```

But in reality it should be written to discover the OS name + version. (On modern Linux, this is done by reading `/etc/os-release` -- I'm not sure if there's a similar analogue for FreeBSD)

**Comment by yurivict** [comment]
On BSDs it is ```uname -a```.

But you should really remove the empty functions.

**Comment by kevinushey** [comment]
I agree -- should be fixed up in https://github.com/rstudio/rstudio/commit/8967d0e4979b81b4792093e869ae9a6bf6d96397.

**Comment by yurivict** [comment]
This fixed the problem, thanks!
