### ISSUE TITLE
 Non-ASCII character parameters cannot be correctly read from front matter on Windows when executing R Markdown code block in RStudio session

### ISSUE THREAD

**Issue by psychelzh** [rstudio/rstudio#2998]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.453
    OS Version      :  Windows >= 8 x64 (build 9200)
    R Version       : R version 3.5.0 (2018-04-23)

### Steps to reproduce the problem

Here is a minimal example of `R Markdown`, and I saved it with `UTF-8` encoding:

````r
---
title: "Untitled"
output: html_document
params:
  test: "测试"
---

```{r setup}
test <- params$test
```
````

### Describe the problem in detail

When you run the code block in `RStudio` session, the variable `test` will be messy as follows:

```r
test
[1] "娴嬭瘯"
```

### Describe the behavior you expected

It should output the correct characters.

```r
test
[1] "测试"
```

**Comment by ronblum** [comment]
Reproducible on Windows 10. Not an issue on MacOS 10.12.6 (Sierra) and SUSE 12.3.

**Comment by kevinushey** [comment]
Thanks for the bug report! This will be fixed with https://github.com/rstudio/rstudio/commit/15c36db4b87b3dc0e8292e18e0dafeb831cb68e3, although for now the encoding of any strings in the YAML header need to be representable in the current locale. This should hopefully be fixed up in the next version of `knitr`.

**Comment by jmcphers** [comment]
Fixed with https://github.com/rstudio/rstudio/commit/15c36db4b87b3dc0e8292e18e0dafeb831cb68e3.
