### ISSUE TITLE
Discard pending console input on error

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#3014]
Execute the following code, all at once, with <kbd>Cmd</kbd>+<kbd>Enter</kbd>:

    print("1")
    stop("2")
    print("3")

All three lines are executed, even though an error occurred while executing the second one.

It'd be nice if we could avoid submitting additional lines to the interpreter in this case; it's unlikely that any lines after the one that failed will succeed, but there's no way to keep them from being executed, even if they're expensive (aside perhaps from interrupting R itself).

R scripts stop on error, and so does interactive code execution in the notebook, so this would also make multi-statement execution more consistent across execution methods.

(suggested by @hadley)

**Comment by MarcoPortmann** [comment]
What is the status of this feature request?

I used to work with Tinn-R (https://github.com/MarcoPortmann/Tinn-R) where execution stops on errors. As @jmcphers said, it is unlikely that any lines after an unhandled error make sense. Moreover, if execution doesn't stop it just increases the risk of overlooking an error and makes debugging more tedious (find the error in the code; and you probably have to re-run the script up to where the error occurred).
I know that R-Studio offers additional debugging options. But usually all I want is just a stop when an error occurs.

**Comment by hadley** [comment]
I think this is worth keeping alive 💓

**Comment by jmcphers** [comment]
Another vote here: https://github.com/rstudio/rstudio/issues/9076

**Comment by jmcphers** [comment]
Very similar issue in https://github.com/rstudio/rstudio/issues/9405, suggesting we should also discard input on browser().

**Comment by lfmcmillan** [comment]
I totally agree with this issue, I would really like Rstudio to stop on first error.

What I find particularly confusing is that I don't think this used to happen in RStudio i.e. I have happily debugged in Rstudio in the past by selecting parts of the code and running them and then going through the browser() debugger to find bugs. (and prior to that I used Matlab's excellent debugging and breakpoint options for 4 years). So this issue seems like a new feature of RStudio that suddenly makes it hard to do something that was easy before...

The file lets me debug from the browser() statement if I source the whole file, but I really don't want to redo all the bits of code every time I debug one little bit, especially if the rest of it is slow data processing of a large file. And I also don't want to have to spend time commenting out or locking out bits that I don't want to rerun and then unlocking them when I do want to rerun them. So just being able to select some of the code and get the same effects as if I'd sourced that bit of code was much more useful.

Once the code is working I'll end up making functions out of it etc. so I can run it selectively, but in the initial hacky stages of setting up complex statistical simulations it's easier to just start with scripted commands.

**Comment by kevinushey** [comment]
I think this is worth considering for a future release.

**Comment by timtmok** [comment]
From what I can understand of the R Api and how we use it, the R session is fed the selected lines through stdIn and the result is captured through a callback so it can be sent to the IDE. The `R_WriteConsoleEx` callback has `otype` to determine the type of console output. There doesn't appear to be any other indicator whether the result is an error. Unfortunately, the `otype` uses the same value for errors and warnings. It even returns an error/warning value when calling `install.packages`. So it cannot be used as an error flag to clear pending console input.

Unless there's another way of detecting an error from executing a line, I think a more complicated solution is required.

I can think of writing the console input to a temp file and executing `source(<temp file>)` would work. Running it this way stops execution upon encountering an error.

Or, the pending input could be sent to R together instead of line by line. I think this might run into buffer size problems though.

**Comment by jmcphers** [comment]
By default, we install our own top level error handler with `options(error = ... )` (see https://github.com/rstudio/rstudio/blob/main/src/cpp/session/modules/SessionErrors.R). So we could add code to our custom handlers to call back into the IDE and clear any pending input. Users can of course install their own error handlers on top of ours but that's somewhat rare. 

We definitely don't want to use temp files, that will result in all kinds of side effects since it changes the evaluation environment, source refs, R's internal history, call stack, etc. in ways that are hard to disguise.

**Comment by hadley** [comment]
(As of 4.0 (I think) you can also use `globalCallingHandlers()` which allow you to register an error handler which will be called in addition to whatever the user has set; probably not important here, but good to know about in general).

**Comment by kevinushey** [comment]
> By default, we install our own top level error handler with options(error = ... ) (see https://github.com/rstudio/rstudio/blob/main/src/cpp/session/modules/SessionErrors.R). So we could add code to our custom handlers to call back into the IDE and clear any pending input. Users can of course install their own error handlers on top of ours but that's somewhat rare.

Unfortunately it's fairly common for packages to do this, e.g.

```
options(error = rlang::trace_back)
```

would be commonly set for anyone who wants `rlang`-style errors.

> Unless there's another way of detecting an error from executing a line, I think a more complicated solution is required.

R does have a callback for resetting the console that we haven't implemented:

https://github.com/wch/r-source/blob/777b35108d3aaf87ad9afece6b9652acb2d3c5fb/src/unix/system.txt#L41-L61

https://github.com/rstudio/rstudio/blob/88f2af61390ebcdee960a93b4098f02a8fae817a/src/cpp/r/session/REmbeddedPosix.cpp#L151-L155

I wonder if we could actually provide a `ptr_R_ResetConsole` that would discard pending console input?

**Comment by timtmok** [comment]
Providing a callback to `ptr_R_ResetConsole` works! As per the docs, it is only called after an error and implementing a callback to clear the pending input functions as expected.

I don't think it can work for Windows though. The docs have nothing on a console reset callback.

**Comment by cjyetman** [comment]
I made a package/RStudio add-in that achieves something like this by wrapping the selected lines in `{` and `}` before being sent to the console so that they're run as a code block, which will stop at the first error... https://github.com/cjyetman/safe.run

I'd be very happy to see this feature rolled directly into RStudio instead.

**Comment by timtmok** [comment]
Enclosing the lines in `{ }` would achieve the desired behaviour on Windows. I'm not sure how others feel about modifying the input like that though. I'm not sure I know enough about R to foresee issues with modifying input like this. The only thing I can think of is a multi-line command where the user accidentally misses selecting the rest of the command.

```
1  print(
2    "33")
```

Selecting only line 1 and executing would have different behaviour if the IDE enclosed the code in `{ }`. It could return an error that might not make sense to the user because the input was modified.

**Comment by hadley** [comment]
I don't think enclosing in `{}` is the right approach for RStudio, but it's reasonable hack.  The problem is you still want to interleave input and output for non errors, i.e. you want:

```
> print("1")
[1] 1
> print("2")
[1] 2
```

Not

```
> print("1")
> print("2")
[1] 1
[1] 2
```

**Comment by kevinushey** [comment]
For Windows, I think we can use [detours](https://github.com/microsoft/Detours) to hot-patch the `R_ResetConsole` implementation.

**Comment by timtmok** [comment]
Tested with the latest R (4.2.0 RC) that has implemented the reset console callback. Kevin's change https://github.com/rstudio/rstudio/pull/10835 to adopt the callback now stops script execution on Windows when an error is encountered.

**Comment by mjsulik** [comment]
Is there a way to disable this change? It has disrupted my workflow when working interactively with Rmd files because non-code text now halts execution of subsequent commands. This makes it difficult to run a selection of more than one code chunk interactively because even the control sequences ```{r} or ``` will return an error, halting execution of any subsequent code chunks. 

Here's an example:

> Here are some notes. 
> 
> ```{r}
> print("hello, world!") 
> ```

**Comment by gtritchie** [comment]
> Is there a way to disable this change?

Not yet; recommend you upvote: https://github.com/rstudio/rstudio/issues/10391
