### ISSUE TITLE
Japanese input (Anthy) on Ubuntu 18.04 doesn't work inside Rstudio

### ISSUE THREAD

**Issue by pascaloettli** [rstudio/rstudio#3015]
The issue described here is not really a unsolved bug, as the Rstudio Preview (`1.2.679`) doesn't have this problem. But it exists in the stable release `1.1.453` and perhaps Rstudio developers would be interested in knowing this particular issue.

### System details
    RStudio Edition : Desktop
    RStudio Version : 1.1.453
    OS Version      : Ubuntu 18.04
    R Version       : 3.5.0

### Steps to reproduce the problem
1. Open Rstudio,
2. Switch from English (US) to Japanese (Anthy), keyboard input managed by IBus,
3. Trying to type 「あ」 either in the Source or in the Console Pane (on a US keyboard, this kana is mapped to the "a" key),
4. Result is invariably "a".

### Describe the problem in detail
Japanese input works on any window (i.e. web browser, text editor, terminal...), but not inside Rstudio.

### Current solution
Actually, using the Rstudio Preview `1.2.679` solves this issue.

**Comment by jmcphers** [comment]
Very glad to hear the preview solves your issue! The preview release has some major underlying technology changes that we can't backport to the 1.1 release; these are probably the reason that the bug is fixed but are also unfortunately the reason we can't also fix this in 1.1. Appreciate the report!
