### ISSUE TITLE
After moving project, terminal opens in old location

### ISSUE THREAD

**Issue by hadley** [rstudio/rstudio#3019]
1. Create new project and open the terminal.
1. Close RStudio, and copy the project to a new location
1. Reopen project
1. Reopen terminal

Working directory of the terminal is still the old project directory. This just caused me 5 mins of head scratching as to why changes I was making with command line git weren't reflected in the git pane.

**Comment by gtritchie** [comment]
This is currently "by design". Each terminal instance (per session) tries to remember its last state, including current working directory. That current working directory is not related to the project directory. When you copy the entire project, you are also copying the session data, and it remembers the last location for each terminal.

**Comment by kevinushey** [comment]
Would it make sense for these paths to be relative to the project root (when the working directory lives within the project), rather than absolute?

**Comment by gtritchie** [comment]
Yes, it could be changed to work that way.

**Comment by scubastevew** [comment]
A customer has reported this as well: https://rstudioide.zendesk.com/agent/tickets/38317

**Comment by ronblum** [comment]
Do we need to take into account the rest of the state for the terminal, in addition to the project’s working directory? Consider the following scenarios:

---

**A: Current directory**
1. Open a project
2. Open a terminal in the Terminal pane
3. `cd /tmp`
4. Switch to a different project
5. Go back to the first project from step (1)
6. `rm -rf *`

Did we just delete the contents of /tmp or everything in the project directory?

---

**B: Field values**
1. Open a project
2. Open a terminal in the Terminal pane
3. `export A_DIRECTORY="."`
4. `cd $A_DIRECTORY`
5. Switch to a different project
6. `export A_DIRECTORY="/tmp"`
7. `cd $A_DIRECTORY `
8. Go back to the first project from step (1)
9. `rm -rf $A_DIRECTORY `

Did we just delete the contents of /tmp or everything in the project directory?

---

Also, how would the directory change due to project switching interact with 
&nbsp;&nbsp;&nbsp;Tools -> Global Options -> General -> Advanced -> Re-use idle sessions for project links
disabled or enabled?

**Comment by gtritchie** [comment]
The thought is that the terminal's persistence of current-working-directory would be relative to the project root, but if the current working directory was not under the project root, it would be saved as an absolute path. So "/tmp" would always come back as "/tmp".

Good question on the re-use of sessions with project switching, I need to look into that more as part of thinking about this.
