### ISSUE TITLE
RStudio desktop >=1.2.737 crashes immediately on Windows

### ISSUE THREAD

**Issue by wch** [rstudio/rstudio#3055]
This is a follow-up to #2958. In the course of tracking down that bug, I found that newer builds of RStudio would crash immediately on start.

### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.737
    OS Version      : Windows 10.0.16299
    R Version       : 3.5.0

### Steps to reproduce the problem

Open RStudio. It crashes immediately.

![](https://user-images.githubusercontent.com/86978/41792542-ce929198-761e-11e8-99b4-183650f0efb7.png)

I bisected the daily builds and found that 1.2.737 was the first one that did this. (Probably not coincidentally, it is 40 MB larger than 1.2.736.) Here are the results from my testing:

1.2.770: bad
1.2.761: bad
1.2.758: bad
1.2.738: bad
1.2.737: bad
1.2.736: good
1.2.734: good
1.2.730: good
1.2.724: missing
1.2.723: good
1.2.710: good

I'm using a Dell XPS 13 9370, which is only about a month old.

**Comment by gtritchie** [comment]
Are you running 32-bit or 64-bit Windows 10?

**Comment by wch** [comment]
It is indeed 64 bit.

If you're asking about the 1.1.x series, 1.1.455 works fine.

**Comment by kevinushey** [comment]
Would you be able to create a crash minidump for us? The process is a bit convoluted (you need to edit a bunch of registry entries to request it) but it could be helpful.

https://msdn.microsoft.com/en-us/library/windows/desktop/bb787181(v=vs.85).aspx

For what it's worth, one bug that came up on the forums with a crash-on-load was due to old video card drivers: https://community.rstudio.com/t/preview-release-1-2-747-3-doesnt-open-on-windows-10/10050/7

**Comment by kevinushey** [comment]
@wch saw that this is a Qt bug: https://bugreports.qt.io/browse/QTBUG-64697

**Comment by gtritchie** [comment]
Sweet! Well, not sweet given we're probably going to hit this a lot out in the wild, but at least a clear cause and fix. Thanks @kevinushey.

**Comment by wch** [comment]
Updating the display driver made it stop crashing. I updated with Device Manager -> Display Adapters -> Intel(R) UHD Graphics 620 -> Update Driver.

**Comment by gtritchie** [comment]
Closing since this is a known driver/Qt issue.
