### ISSUE TITLE
RStudio installer claims package is not signed on openSUSE 15

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#3069]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.774
    OS Version      : openSUSE 15.0
    R Version       : 3.5.0

### Steps to reproduce the problem

1) Import and validate the key following the instructions at https://www.rstudio.com/code-signing/. 
2) Install RStudio using the command line or the GUI software installer.

### Describe the problem in detail

Installing the application should proceed without warning that the package is not signed, especially after the key has been imported and validated. However, installing with the command line results in the following:
> Retrieving package rstudio-1.2.774-1.x86_64                                    (1/1),  94.6 MiB (554.2 MiB unpacked)
rstudio-1.2.774-x86_64.rpm:
    Package is not signed!

> rstudio-1.2.774-1.x86_64 (Plain RPM files cache): Signature verification failed [6-File is unsigned]
Abort, retry, ignore? [a/r/i] (a): 

Similarly, the GUI installer pops up with the following warning:
<img width="701" alt="opensuse_15_0" src="https://user-images.githubusercontent.com/31009952/41866819-4baa1496-787f-11e8-8b3b-264fc9295382.png">

Choosing "Ignore" in both cases results in a successful installation.

### Describe the behavior you expected

The installation should proceed without a warning, at least after validating the key using https://www.rstudio.com/code-signing/. 

Cf. #2436—this works on openSUSE 42.3.

**Comment by jmcphers** [comment]
The reason this doesn't work is that OpenSUSE 15 does not provide GnuPG 1. In GnuPG 2 all of the key management was moved to `gpg-agent`, which while more convenient for interactive use is much less amenable to scripting. 

We have the same problem on Debian 9, but we get around it by installing a GnuPG 1.4 package that Debian provides. 

https://github.com/rstudio/rstudio/blob/8af730409bb6d651cc8f6816d136bea91441e7a4/docker/jenkins/Dockerfile.debian9-x86_64#L24

As far as I can tell no such package exists for SuSE, so our options are either to:

1. rewrite our code signing script so that it works with gpg-agent, or
2. install gpg 1 on the opensuse15 image from source.
