### ISSUE TITLE
View() in R Markdown file keeps open an XQuartz app on MacOS

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#3073]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.453 and 1.2.776
    OS Version      : MacOS 10.12.6 (Sierra)
    R Version       : 3.5.0

### Steps to reproduce the problem

On MacOS, knit an R Markdown file that calls the data viewer.

1. `File` -> `New File` -> `R Markdown` -> `OK`
2. Add the following code to the file
````
```{r}
View(cars)
```
````
3. `Knit` -> Choose a file name, e.g. `dv.Rmd`

### Describe the problem in detail

On MacOS, knitting an R Markdown file that calls the data viewer with `View()` opens up an extra "XQuartz" app that seems to do nothing except for a brief flash of a table. The app doesn't close when RStudio is closed—it needs to be closed separately

### Describe the behavior you expected

No extra app opens up, or at least sticks around when knitting is done.

It's also a problem in 1.1.453, so it's not a regression. It's not an issue in Windows. Also, opening the stray app is benign, and calling the data viewer from a knitted R Markdown file probably isn't useful, so this is low priority.

**Comment by jmcphers** [comment]
This happens because the View() command in the child R Markdown process is not hooked up to the RStudio view, but to R's viewer, which invokes X. I don't think this is worth fixing since it's very benign and it doesn't make sense to View() (which is interactive) when knitting (which isn't). 

One solution might be to patch View() so that it no-ops while knitting; see https://github.com/rstudio/rstudio/issues/5771.
