### ISSUE TITLE
"Remove package" icons are mostly obscured by scrollbar

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#3085]
### System details

    RStudio Edition : Desktop & Server
    RStudio Version : 1.2.780
    OS Version      : Desktop: MacOS 10.12.6 (Sierra), Windows 10, Linux (Ubuntu 18.04); Server: MacOS/Chrome to Red Hat 7.5
    R Version       : 3.4.4 & 3.5.0

### Steps to reproduce the problem

Choose Packages pane.

### Describe the problem in detail

The "remove package" icons on the right are mostly obscured by the scrollbar. They can only be clicked by moving the cursor to a tiny area on the left.

### Describe the behavior you expected

The "remove package" icons should be completely visible.

This was not an issue in 1.1.453 in which only "remove package" icons were present. In 1.2, though, there is also a "browse package" icon and a nefarious scrollbar.

**Comment by kevinushey** [comment]
Note that on macOS, unless you have a mouse plugged in, you might need to explicitly ask for scrollbars to always be drawn (otherwise the overlay scrollbars fade in and out as desired). See System Preferences -> General -> Show Scroll Bar setting:

<img width="674" alt="screen shot 2018-06-27 at 9 28 22 am" src="https://user-images.githubusercontent.com/1976582/41986898-7686fe2c-79ec-11e8-9453-785170fc1ded.png">

Here's what I see with persistent scrollbars:

<img width="562" alt="screen shot 2018-06-27 at 9 29 20 am" src="https://user-images.githubusercontent.com/1976582/41986945-9b1f34f2-79ec-11e8-9b98-bd964185d202.png">

Note that other places in the IDE where scrollbars are drawn, the content area is properly resized (so that things aren't shown under the scrollbar)

<img width="342" alt="screen shot 2018-06-27 at 9 30 40 am" src="https://user-images.githubusercontent.com/1976582/41986994-c77c7848-79ec-11e8-94be-96049e6d350a.png">

**Comment by kevinushey** [comment]
It looks like this is a DataGrid feature: the scrollbar is drawn as part of a separate, absolutely-positioned div and so doesn't interact with layout the same way as other scrollbars. This could probably be fixed with some DOM surgery...
