### ISSUE TITLE
Edit -> Replace and Find fails to open when there is an existing multiline text selection

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#3094]
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.2.753
    OS Version      : Ubuntu 16.04
    R Version       : 3.4.4

### Steps to reproduce the problem

Given a document with contents:

```r
abc
def
```

Try highlighting everything with <kbd>Ctrl + A</kbd>, and then attempt to open the Find and Replace dialog with <kbd>Ctrl + Shift + J</kbd>.

### Describe the problem in detail

The Find and Replace dialog fails to open.

### Describe the behavior you expected

We should do something, at least. I don't think our Find and Replace helper supports replacements across multiple lines, but we should probably still just open the dialog with an empty selection?

**Comment by kevinushey** [comment]
As an aside, the name `Replace and Find` feels a bit strange, given the order of operations is that first you find, then you replace. I wonder if we should flip that around?

**Comment by ronblum** [comment]
Reproduced on MacOS 10.12.6. Looks like it happens if more than one line is selected—it doesn't have to be the whole document.

**Comment by ronblum** [comment]
@KBGrammer Interesting. Can you provide a reproducible example of it working? I've it on Ubuntu 18.04 Desktop and Ubuntu 16.04.4 Server, but no luck.

**Comment by KBGrammer** [comment]
I'm using Version 1.2.747 (using it because the current release version has broken middle click paste, but the preview works) on Ubuntu 16.04. All of this holds true for a previous version of 1.1.442. I believe it also holds true for 1.1.453, but I only had that installed for 10 minutes before switching to the preview version.

Steps that fail outright:
1. Load a generic script:
```
print("this")
print("that")
print("the other thing")
```
2. Highlight the last 2 lines.
3. Press `Ctrl+Shift+J`. (nothing happens)

Steps that bring up the menu:
1.  Load a generic script:
```
print("this")
print("that")
print("the other thing")
```
2. Press `Ctrl+Shift+J`. (a search text box, buttons saying Next, Prev, All, etc. shows up at the top of the screen)

Here's where things diverge. The following steps allow me to search and replace within the selection (Sequence A)
3. Highlight the last two lines.
4. Check "In selection"
5. Begin typing 't' in the "Find" box, and it highlights the 't' in print on line 2 (in blue). From here, I could replace 't's individually or all at once. The selection remains highlighted (in gray).

The following steps are not in the proper sequence. (Sequence B) 
3. Check "In selection".
1. Load a generic script:
```
print("this")
print("that")
print("the other thing")
```
2. Highlight the last 2 lines.
3. Press `Ctrl+Shift+J`. (nothing happens)
4. Highlight the last two lines. (as soon as you click to begin highlighting, 'in selection' is no longer selected).
5. Check "In selection".
6. Begin typing 't' in the "Find" box, and it highlights the 't' in print on line 2 (in blue). From here, I could replace 't's individually or all at once, as I choose. The selection remains highlighted (in gray).

Another out of sequence version. (Sequence C)
3. Highlight the last two lines.
4. Begin typing 't' in the "Find" box, and it highlights the 't' in print on line 2 (in blue). (at this point, my selection is no longer highlighted and the only highlighted piece is the t on line 2. This means that I could click replace until I've reached the end of what my selection was, but I can't replace all or it would be for the whole script).
5. Highlight the last two lines.
6. Check "In selection".
7. Press "Replace" and it highlights the t on the second line and a second press of "Replace" will replace it and move on. The selection remains highlighted (in gray).

Imagine I have a very long script and my three lines are in the middle of it and I've navigated to that point (call it lines 500-502). The following lines show undesirable results if I don't do things in the proper sequence. (Sequence D)
3. Begin typing 't' in the "Find" box. (RStudio searches for the first instance in the whole script of the letter 't' and continues searching if I type more, so I'm very far from lines 500-502).
4. Navigate back to lines 500-502.
5. Perform Sequence A.

I think it's a normal flow of a "find and replace" operation to open the requisite dialog, type what I want to replace, type what I want to replace it with, and go from there. The live-search feature, which is useful as a search feature, doesn't seem beneficial to the find and replace feature because I think it's acceptable to assume that I don't want to start searching until I've manually clicked something to do so. It seems as though there is only a single sequence that works (Sequence A) and that extra steps get added in order to re-select or re-do different pieces of that sequence if it's done out of order (Sequences B-D). I think a find and replace feature without the live search functionality would be useful, and the choreography where you must do things according to sequence A or else you have to re-do pieces of it in the right sequence later is not desirable.

Additional odd functionality:
1. Load a generic script:
```
print("this")
print("that")
print("the other thing")
```
2. Highlight line 3
3. Press `Ctrl+Shift+J`. (dialog shows up with `print("the other thing")` in the Find text box).

I hope that provides enough information about what happens when I'm trying to replace some characters within a block of a script, swapping similar filenames for instance.

**Comment by ronblum** [comment]
@KBGrammer We really appreciate not only for reporting the issue but also for providing such a detailed reproduction of the issue and your observations. Since you did all your work on RStudio Desktop Ubuntu 16.04 with R 3.4.4, I tested this using the Desktop on MacOS 10.12.6 with and the Server on Red Hat 7.5, both with R 3.5.0. I can reproduce the behavior you found on versions 1.2.789 as well as 1.1.453, so this is not a regression. We'll review both the problem and your thoughts on how the feature should behave as work on future development. Thank you very much for putting so much time and effort to help improve the products!
