### ISSUE TITLE
Terminal is unresponsive on R Studio Server

### ISSUE THREAD

**Issue by mathan4stat** [rstudio/rstudio#3123]
### System details

    RStudio Edition : Server
    RStudio Version : 1.1.423
    OS Version      : Red Hat Enterprise Linux Server 7.4 (Maipo) 
    R Version       : 3.4.1 (2017-06-30)

### Steps to reproduce the problem
1. Trying to use the existing terminal
2. Creating a new terminal

### Describe the problem in detail
Terminal shows blank screen and it does not allow to type anything on the terminal. 

![2018-07-06_14h14_20](https://user-images.githubusercontent.com/23045567/42372186-32ca9e2e-812f-11e8-9a48-0ccabed2335a.png)

### Describe the behavior you expected
The terminal should allow us to type

### Additional info:
```
> devtools::session_info() 
Session info ------------------------------------------------------------------------------------------------------------------------
setting  value                       
 version  R version 3.4.1 (2017-06-30)
system   x86_64, linux-gnu           
 ui       RStudio (1.1.447)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       <NA>                        
 date     2018-07-05  
```

**Comment by jmcphers** [comment]
Can you include your terminal diagnostics? (Tools -> Terminal -> Terminal Diagnostics)

**Comment by gtritchie** [comment]
You may be hitting a bug where the terminal is unable to use WebSockets, but failing to switch to the slower but less finicky "RPC" mechanism.

Try unchecking `Tools -> Global Options -> Terminal -> Connect with WebSockets`.

Then close the terminal tab completely (via the [X]), then Tools -> Terminal -> New Terminal.

**Comment by mathan4stat** [comment]
@gtritchie It did not help.

**Comment by gtritchie** [comment]
Next experiment, try **unchecking** `Tools -> Global Options -> Terminal -> Close terminal when shell exits`.

Then try to create a new terminal. Does anything show in the terminal pane (error messages, etc.)?

**Comment by mathan4stat** [comment]
@gtritchie I got the following error in Terminal window

```
/usr/bin/env: bash: no such file or directory
[Process Completed]
[Exit code: 127]
```

and unable to type anything in the terminal window

**Comment by gtritchie** [comment]
This means the command used to launch the terminal shell isn't finding bash for this user. By default the terminal does:
```
/usr/bin/env bash -l
```
So the error suggests the $PATH doesn't include the location of bash for this user. You can either fix that, or specify a fully-qualified path to `bash` via Tools / Global Options / Terminal / New Terminals Open With: Custom.

For example (this path is what `which bash` returns on my Mac, would have to be changed to whatever the correct value is on your system):

![2018-07-12_10-30-01](https://user-images.githubusercontent.com/10569626/42649720-45b0f60c-85bf-11e8-8be2-1f27feed2da8.png)

Note, it is possible to use other shells instead of bash, but that can lead to other quirks which often requiring unchecking "Local terminal echo" and/or "Save and restore environment variables".

**Comment by mathan4stat** [comment]
We have set the 'Custom shell binary (fully qualified path)' as '/usr/bin/bash'. Now the terminal is alive but basic commands like “top” or “ls” do not work.

```
/usr/libexec/grepconf.sh: line 5: grep: command not found
bash: id: command not found
[user@si-2891 model_office]$ top
bash: top: command not found
[user@si-2891 model_office]$ 1s -1
bash: ls: command not found
[user@si-2891 mode1_office]$ |
```

**Comment by gtritchie** [comment]
This matches the fact that the default shell settings aren't work. Something is wrong with that user's path. You will need to examine their shell configuration files; this isn't specific to RStudio.
