### ISSUE TITLE
Cannot View data frame with integer64 columns

### ISSUE THREAD

**Issue by renkun-ken** [rstudio/rstudio#3145]
### System details

    RStudio Edition : both Desktop and Server
    RStudio Version : 1.2.812
    OS Version      : Ubuntu 16.04, macOS 10.13.6
    R Version       : 3.4.4, 3.5.1

### Steps to reproduce the problem

```r
data <- data.frame(x = bit64::as.integer64(c(1,2,3)))
View(data)
```

```
Error in hist.default(hist_vals, plot = FALSE) : 
  some 'x' not counted; maybe 'breaks' do not span range of 'x'
In addition: Warning message:
In pretty.default(range(x), n = breaks, min.n = 1) :
  Internal(pretty()): very small range.. corrected
```

**Comment by ronblum** [comment]
Thanks @renkun-ken for letting us know about this issue.

Reproduced on Windows 10 and MacOS 10.12.6 (Sierra). This is a regression (worked in RStudio 1.1.453).

**Comment by jmcphers** [comment]
The error's actually changed somewhat; it now references the new code:

   Error in hist.default(as.numeric(hist_vals), plot = FALSE) : 

The problem is that `as.numeric` doesn't work on `integer64` values until the `bit64` package is loaded. That's why it doesn't work on startup, but it does during the session in which you've called `bit64::as.integer64` (as doing so loads the package).

We try pretty hard not to have RStudio load spurious packages at startup, and I'm also not sure all of the codepaths that support the histogram are going to handle 64 bit integers gracefully, so I think we should prevent this kind of thing by refusing to histogram-ize any numeric columns which have a special class applied.

**Comment by ronblum** [comment]
The error is gone. However, we're still displaying values in both cases. First we get (1, 2, 3):
![123](https://user-images.githubusercontent.com/31009952/44405947-7ed58f00-a528-11e8-8848-0621369e2fa0.png)
but when the project is reopened, we get this:
![int64](https://user-images.githubusercontent.com/31009952/44405905-62395700-a528-11e8-9dd3-e7f3a1062ec4.png)

**Comment by jmcphers** [comment]
The bit64 package must be loaded in order for us to get sensible values. We do not load packages on startup, so the raw values are displayed. This behavior is weird, but it isn't a regression, and should be filed separately.

**Comment by ronblum** [comment]
Done! Verified that error is gone.

**Comment by nielsenrechia** [comment]
Hi, I'm getting the same error `Error in hist(hist_vals, plot = FALSE) : could not find function "hist"`, but insted of `integer64` it is occuring for for `double` columns.

data <- data.frame(x = as.double(c(1,2,3)))
View(data)

Someone could help me?

thanks
