### ISSUE TITLE
improve alignment of checkboxes + labels in options menu

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#3190]
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.2.821
    OS Version      : Windows 10 x64
    R Version       : 3.5.1

### Steps to reproduce the problem

Using a high DPI monitor, open the Global Options pane.

### Describe the problem in detail

Checkboxes and labels are slightly misaligned -- the checkbox is drawn slightly above the associated label text.

<img width="314" alt="screen shot 2018-07-19 at 11 46 59 am" src="https://user-images.githubusercontent.com/1976582/42963622-97fd6960-8b49-11e8-8437-c0b8d398037c.png">

### Describe the behavior you expected

The checkbox should be drawn slightly lower (or text higher), to improve alignment.

As an aside: we currently draw our own custom checkboxes on all platforms; I feel like the first reason why we pursued this was due to bugs in rendering of checkboxes on macOS. I wonder if it's worth reverting back to the native checkboxes?

**Comment by jmcphers** [comment]
> I feel like the first reason why we pursued this was due to bugs in rendering of checkboxes on macOS

Yes, we started doing this back when Yosemite came out; it had the baffling behavior of drawing additional checkboxes in random locations when checkboxes were toggled. 

One reason we haven't switched back is that drawing our own checkboxes allows us to control the size and alignment much more precisely. We've had quite a lot of trouble over the years with native checkbox controls being drawn cartoonishly large (e.g. on some versions of Windows with high DPI settings) or otherwise misaligned. This has resulted in us using our own checkbox render all the time. 

It's possible all these issues have gone away with QtWebEngine, and I'd be delighted to use checkboxes with a more native appearance, but we'd probably want to get eyes on lots of areas of the product under multiple OS and DPI settings if we made a more sweeping change.
