### ISSUE TITLE
GUI Package Management setting doesn't change repos if previously set with options()

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#3218]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.846
    OS Version      : MacOS 10.12.6 (Sierra)
    R Version       : 3.5.1

### Steps to reproduce the problem

1. Make sure the primary CRAN repository is set to the global CRAN repository. Change it if needed: 
   - Tools -> Global Options -> Packages
   - *If needed: Change -> Global (CDN) RStudio -> OK*
   - OK
2. `options("repos")`
   - Output should be:
```
> options("repos")
$repos
                       CRAN 
"https://cran.rstudio.com/" 
attr(,"RStudio")
[1] TRUE
```
3. `options(repos = "https://cran.case.edu/")`
4. `options("repos")`
   - Output is:
```
> options("repos")
$repos
[1] "https://cran.case.edu/"
```
5. Tools -> Global Options -> Packages
   - Note that the primary repository is still the global repository
6. Bulgaria [https] - Sofia University -> OK -> OK
7. `options("repos")`
   - Output is still:
```
> options("repos")
$repos
[1] "https://cran.case.edu/"
```
8. Session -> Restart R
9. `options("repos")`
   - Output is now:
```
> options("repos")
$repos
                            CRAN 
"https://ftp.uni-sofia.bg/CRAN/" 
attr(,"RStudio")
[1] TRUE
```
10. Tools -> Global Options -> Packages-> Change -> Global (CDN) RStudio -> OK -> OK
11. `options("repos")`
   - Output is now:
```
> options("repos")
$repos
                       CRAN 
"https://cran.rstudio.com/" 
attr(,"RStudio")
[1] TRUE
```
12. (Optional) Switch back to your favorite mirror, if it's elsewhere
  - Tools -> Global Options -> Packages-> Change -> [Your favorite mirror] -> OK -> OK

### Describe the problem in detail

- Steps 3–7: After setting the current repository using `options(repos = "[mirror]")`, the current repository reflected by `options("repos")` is correctly changed. However, then changing the primary repository using the Package Management in the GUI doesn't affect the current repository in the current session, shown by `options("repos")`.
- Steps 7–9: R has to be restarted for the new value to take effect.

### Describe the behavior you expected

If the repository is set manually using `options(repos = "[mirror]")` and then changed using the GUI (Package Management in Global Options), the new primary repository in the current session should change. This is the behavior that occurs if only the GUI is used and no manual setting is done (steps 9–11).

**Comment by jrowen** [comment]
Related to this issue, I'm finding that RStudio is not respecting the repo settings made via `Rprofile.site`.  In particular, I'm adding a second, private repo and not seeing it in the Packages->Install->Install select box.  

If I go to the terminal and run `Rscript -e 'getOption("repos")'`, I can see the second repo working, but if I run the same command from the Console in Rstudio, I see
```
> getOption("repos")
                       CRAN 
"https://cran.rstudio.com/" 
attr(,"RStudio")
```

I've also tried running the following from the RStudio console
```
> options(repos = c("https://cran.rstudio.com/","<private repo url>"))
> getOption("repos")
[1] "https://cran.rstudio.com/"                                 "<private repo url>"
```
but I also don't see these changes reflected in the Install from select box.

It seems that the only fix is going to Tools->Global Options->Packages and then adding the private repo as a secondary repo.  After restarting R, the private repo shows up in the Install tab.  Is this expected behavior, and if so, what's the new process for defining additional repos in RStudio.
