### ISSUE TITLE
Add "copy to clipboard" command to History tab

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#3219]
Request from an RStudio Server user (paraphrased):

> I often want to copy R commands from one R session to another. I use the History tab, click To Console or To Source, then copy and paste the emitted command. It'd be a lot easier if I could just copy the command directly via Ctrl+C or a toolbar button.

**Comment by aronatkins** [comment]
Similar workflow: Browse history and copy a command to paste elsewhere (Github comment, email, some other editor).

**Comment by DDorch** [comment]
I also search for this functionality for the same reason. It's annoying to double-click on an item of the history tab to get it in the console and then select it for copying it. 

The weird thing is that if you right-click on a row of the history tab a menu with "Cut, Copy, paste and Select All" items appears. But the "copy" item is disable and I don't understand what can do the "Paste" command in this context.

**Comment by aronatkins** [comment]
Please keep this alive.

**Comment by HenrikBengtsson** [comment]
Adding my upvote for this one:

I just observed a beginner testing out a few commands in the console, which they then wanted to copy-and-paste into their Rmarkdown document. The obvious attempt to copy from the 'History' panel ended with confusion by trying to figure out why 'Copy' was disabled while 'Paste' wasn't (see screenshot).  What does 'Paste' mean here?
![flameshot_2021-06-22T140818](https://user-images.githubusercontent.com/1616850/123000427-6e8f2f80-d364-11eb-8d48-ace5638c16db.png).

The advantage of being able to copy from the 'History' panel is that you'll only copy the command called, and none of it's output, which you otherwise have to deal with if you copy from the console.  Also, re-running commands in the 'History' panel just to be able to copy from there is also inferior; you might trigger a long running task or produce lots of output that you have to scroll back over, plus you might now want to run that command again, e.g. `file.remove()`, `install.package()`, etc.

**Comment by colearendt** [comment]
Stale bot, stale bot,
Why must you
Threaten to close
All issues

**Comment by pymrkc** [comment]
👍

**Comment by jpmonteagudo28** [comment]
I was redirected here from Posit Community thinking the issue had been solved, but I see it's still a work in progress.

**Comment by FlorinAndrei** [comment]
This would be very useful to have. It's surprising this feature does not exist yet.

**Comment by kevinushey** [comment]
We should at least let Ctrl + C or Cmd + C function to copy text here. This currently doesn't work because the elements are marked as `user-select: none;`. Instead of this, we should use something like `user-select: all` and disable CSS highlight (since we manage that visibility ourselves)

**Comment by jonvanausdeln** [comment]
Verified with [2023.12.0-daily+278](https://dailies.rstudio.com/version/2023.12.0-daily+278)
Windows 11, MacOS12

Copy is now allowed from the history pane

**Comment by FlorinAndrei** [comment]
@jonvanausdeln Awesome!

Quick question: will the fix be available in the next released version? The version I have now is 2023.09.1 Build 494.

**Comment by jonvanausdeln** [comment]
@FlorinAndrei , yes it will be in our next release. 

If you'd like to try it now, it is in the [Daily builds](https://dailies.rstudio.com/). Note, these are intended for testing purposes only and not for production work.

**Comment by DDorch** [comment]
I have tested it on the daily [2023.12.0-daily+283](https://dailies.rstudio.com/version/2023.12.0-daily+283) under Windows 10. Both the contextual menu and the shortcut Ctrl+C are functional. Thanks a lot for this feature :)
