### ISSUE TITLE
Garbled file path

### ISSUE THREAD

**Issue by etienne-s** [rstudio/rstudio#3256]
### System details

    RStudio Edition : Desktop or Server
    RStudio Version : 1.1.456
    OS Version      : Windows 7 x64
    R Version       : 3.5.1

### Steps to reproduce the problem

- Create a file named `foo%.txt`.
- Copy it from the file explorer with <kbd>Ctrl</kbd>+<kbd>C</kbd>.
- Paste into RStudio.

### Describe the problem in detail

The path reads: `file:///C:/Users/xxx/foo%25.txt`.

### Describe the behavior you expected

It should be `file:///C:/Users/xxx/foo%.txt`.

**Comment by ronblum** [comment]
The file path is using the encoding for special characters with a percent symbol followed by their hex symbol, and for % symbol the conversion is %25. Using the same URI in a web browser will open up the same file, although this copy-and-paste approach doesn't seem to work in Windows 7 in most applications I've tried, and not at all on Windows 10. By comparison, MacOS just uses the file name ("foo%.txt" without the path), and on Linux, either the URI is used with the special-character encoding ("file:///home/xxx/foo%25.txt") or the file path instead of the URI ("/home/xxx/foo%.txt"). In short, if copy-and-paste works, the pasting in operating systems is inconsistent, but when URI is used, the hex encoding is always performed.
