### ISSUE TITLE
 error while loading shared libraries libQt5WebKitWidgets.so.5

### ISSUE THREAD

**Issue by sephib** [rstudio/rstudio#3343]
I'm working on an offline environment.
While loading RStudio I'm getting the error 

>  ./anaconda3/bin/rstudio: error while loading shared libraries: libQt5WebKitWidgets.so.5: cannot open shared object file: No such file or directory

### System details

    RStudio Edition : Desktop
    RStudio Version :  1.1.456
    OS Version      :  SLES 12 SP3
    R Version       :  3.5.0

### Steps to reproduce the problem
1. Installing Anaconda3-5.2.0-Linux-x86-64.sh
2.  conda install r-* --offline -f -y --use-local (after downloading relevant packages) 
3.  conda install rstudio1.1.456-h6bb024c_1.tar.bz2 --offline -f -y --use-local
 (same happned when installing rstudio-1.1.423-hcfd39f1_0.tar.bz2)

### Describe the problem in detail
RStudio does not open (nor by command line or anaconda navigator)
I can verify that `libQt5WebKit.so.5` is located under `/usr/lib64/libQt5WebKit.so.5` 
When opening the `anaconda-navigator`  I can see that the has a mark that

### Describe the behavior you expected
RStudio IDE will open

**Comment by sephib** [comment]
### Update
Apparently I don't have a full installation of `Qt5`  
I installed `libQt5WebKitWidgets5` and now I'm getting an error 

> 
> /lib/libQt5Quick.so.5: version `Qt_5.6.2_PRIVATE_API` not found  (required by /usr/lib64/libQT5WebKit.so.5)
> /lib/libQt5Gui.so.5: version `Qt_5.6.2_PRIVATE_API` not found  (required by /usr/lib64/libQT5WebKit.so.5)
> 

This issue may be similar to [issue 4445](https://github.com/ContinuumIO/anaconda-issues/issues/4445). 

`env | grep LD_` does not produce any results so I don't have `LD_LIBRARY_PATH` set - should I do so?

@ccordoba12 any guidance / assistance would be gratefully appreciated.

**Comment by jmcphers** [comment]
This is an issue with your conda environment rather than RStudio. RStudio installs its own copy of `libQt5WebKit`. The most likely source of the issue is that conda is running RStudio in an environment that causes it to attempt to load the system or conda Qt libs instead of its own (RStudio requires a very specific Qt version which is why you're getting errors when running against the system libs). 

We can't offer support for this configuration in our bug tracker. I'd suggest asking on either the conda or RStudio community forums:

https://community.rstudio.com/c/rstudio-ide
