### ISSUE TITLE
Margin doesn't show on dark themes

### ISSUE THREAD

**Issue by EdwinTh** [rstudio/rstudio#3420]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.453
    OS Version      :  macOS 10.13.6
    R Version       : 3.5.0

### Steps to reproduce the problem

Switch back and forth between a light and a dark theme as described below.

### Describe the problem in detail

The margin line that can be enabled with Tools > Global Options > Code > Display tab > show margin (Margine column 80) does only show when a light theme is set. When switching to a dark theme, for instance "Material" the line is invisible. When switching back to a light theme, such as "Eclipse", it shows again. 

Most likely the line is applied in dark within the dark theme. The resolve would then be to give the line a lighter colour when a dark theme is applied.

### Describe the behavior you expected

The margin line is visible in a dark theme.

**Comment by ronblum** [comment]
@EdwinTh I can reproduce this on RStudio Desktop (MacOS) and Server (SUSE), both 1.1.456 and 1.2.957. However, it appears to be theme-specific, only an issue with the Material theme. Other dark themes, such as Dracula and Twilight, work fine. Let me know if you see something different.

**Comment by EdwinTh** [comment]
Confirming that the other dark themes do have the margin line visible. I incorrectly assumed it was a dart theme thing, it is Material specific.

**Comment by DavisVaughan** [comment]
Confirming that the `.ace_print-margin` color is not showing up for Material.

This color specification seems to look good (slightly noticeable, not outlandish), but I'm sure you guys have a material palette to pick from

```
.ace_print-margin {
  width: 1px;
  background: rgb(47, 57, 65)
}
```

**Comment by mjsteinbaugh** [comment]
I'm noticing a visual issue with the [Dracula](https://draculatheme.com/) color theme that may be related to dark mode. On my RStudio install (v.1.1.423), the margin guide for the Dracula is jarringly bright. In don't have such an issue with the other dark themes (e.g. Tomorrow Night).

When looking at the [dracula.rstheme](https://github.com/rstudio/rstudio/blob/master/src/cpp/session/resources/themes/dracula.rstheme) file, here's the current config:

```
.ace_print-margin {
  width: 1px;
  background: #e8e8e8;
}
```

`#e8e8e8` seems to be the culprit here, and should be darkened to a different color in the [recommended palette](https://github.com/dracula/dracula-theme#color-palette).

**Comment by rovyko** [comment]
I think the pull requests #4737 and #4863 have fully addressed this issue. None of the other themes seem to have glaring issues with the margin colors.

**Comment by ronblum** [comment]
Verified in with RStudio Desktop 1.3.205 on MacOS 10.14.6.

**Comment by kmishra9** [comment]
Hey there,

With RStudio's recent tmTheme support, I've been looking for documentation on how to modify the color of the margin line. It's pretty obnoxious for [this otherwise beautiful dark theme](https://github.com/UnderlineWords/Agola-Color-Schemes/blob/master/AgolaNimbus.tmTheme). I'm not sure how I can add the ace editor info to a tmTheme 🤷‍♂

**Comment by kevinushey** [comment]
The margin will have a class of `ace_print-margin`, so you can style it by targeting that class.

**Comment by kmishra9** [comment]
So from [Creating Custom Themes for RStudio](https://rstudio.github.io/rstudio-extensions/rstudio-theme-creation.html)
> While an rstheme can be written from scratch, they contain a fair amount of generated values. The most straightforward method to create one would be to write a tmTheme and import to RStudio and then modify the generated rstheme.

And the `ace_print-margin` target is helpful as well. Unfortunately, it's not clear _where_ I can find and modify the resulting rstheme file. Any hints?
