### ISSUE TITLE
Can't navigate between multiple R Markdown documents published to Connect

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#3427]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.456 and 1.2.955
    OS Version      : macOS 10.13.6
    R Version       : 3.4.3

### Steps to reproduce the problem
- Create a project containing multiple R Markdown source files with HTML links between them; for example, https://github.com/gtritchie/MultiRmd
- Links are authored as such: `[Page Two)[Page2.html)`
- Open each .rmd and knit it to html
- Confirm in Viewer pane or Preview Window that the links will navigate between the files
- **Scenario One**: using viewer/preview publish button, publish all documents in the directory / Publish with source code (this is to Connect): it does correctly show all the .Rmd source files in the picker

![2018-09-05_10-26-31](https://user-images.githubusercontent.com/10569626/45110205-79ff0680-b0f6-11e8-9c55-a07c525c7243.png)

- **Scenario Two**: new deployment, this time publish all final files; can't tell which files are being uploaded; it only shows a single page in the publish dialog, which suggests it isn't going to work:

![2018-09-05_10-28-37](https://user-images.githubusercontent.com/10569626/45110217-81261480-b0f6-11e8-807b-b15b633d3a5b.png)
 
### Describe the problem in detail
- **Scenario One**: the page is shown on Connect, but the links to other pages 404; looking in the bundle on Connect, all the Rmd files are there, but either they are not being rendered, or linking between them with relative links doesn't work for some reason
- **Scenario Two**: again, page shows, but broken links; looking in the package, this time only the last knit page html was included

### Describe the behavior you expected

Uploading multiple static files is only really useful if you can navigate between the files. So we should either block this altogether, or make it work on Connect.

### Other Findings
Links do work if using shiny markdown files, and authoring links to the Rmd files, e.g. `[Foo](Foo.Rmd)`.

**Comment by aronatkins** [comment]
Your findings are correct. Connect only renders the primary Rmd. Links to Rmd deployed with that primary document will 404 (since secondary Rmd are not available in the directory containing rendered output).

We do care about multiple Rmd deployed together when one of them is annotated with `runtime: shiny`. I cannot say how often this happens intentionally, but ...

This is complicated by how Rmd are treated when deployed to shinyapps.io. There is no concept of "rendered" content there. We detect the presence of a single Rmd and use the "Shiny R Markdown" runtime. This is true even if no Rmd is not annotated with `runtime: shiny`. As a result, we get cross-document links in all shinyapps.io Rmd deployments.

`rsconnect` also writes an `index.htm` file that is used by shinyapps.io to enumerate the Rmd. This is served only with shinyapps.io deployments when there are multiple Rmd and none is named `index.Rmd`.

Both parts of the shinyapps.io Rmd serving (inferring of Shiny runtime and index.htm) are used by customers.

We could prohibit bundling multiple Rmd when targeting Connect (not shinyapps.io) if the primary Rmd is not `runtime: shiny`. It doesn't feel like we can be more restrictive given the number of deployments already in play.

**Comment by gtritchie** [comment]
Taking out of 1.2; doesn't seem like this is worth messing with right now. Leaving open as it might inform future publishing work in the IDE.
