### ISSUE TITLE
No submenu is shown and None menu is functioning....

### ISSUE THREAD

**Issue by jiapei100** [rstudio/rstudio#3510]
RStudio build from source, git of September 20, 2018.
Everything goes on well. However, after installation, when I tried to run **rstudio**, I always obtain the following **ERROR** message:

```
$ [0920/002409.390277:WARNING:stack_trace_posix.cc(699)] Failed to open file: /tmp/.gl2pTxbR (deleted)
  Error: No such file or directory
```

And, **ONLY the 1st level** of **rstudio menu** is able to show, **none of the 2nd level menu** is able to show. I mean, under **File**, there is **NOTHING** shown.

Suggestions please?

Cheers
Pei

**Comment by kevinushey** [comment]
If you're building from source, I suspect the issue arises because you're attempting to build against incompatible versions of RStudio's dependencies (e.g. Boost or Qt). Unfortunately we don't have the time to diagnose issues that occur when users attempt to install RStudio from source (we only support the binary copies of RStudio we distribute explicitly). You can see how we build and install RStudio in the `package/` sub-directory; e.g. on linux we use:

https://github.com/rstudio/rstudio/blob/master/package/linux/make-package
