### ISSUE TITLE
RStudio debugging keybindings

### ISSUE THREAD

**Issue by marinsokol5** [rstudio/rstudio#3539]
Hi,
It would be great if we could change the default keybindings for RStudio debugger, the ones for executing the next line, stepping into the function or moving onto the next debugging point.

Thanks in advance.

**Comment by marinsokol5** [comment]
@kevinushey

**Comment by ronblum** [comment]
@marinsokol5 Thanks for the suggestion/request. Just to make sure we understand the request correctly, what are the names of the functions for which you're requesting updates in `Tools -> Modify Keyboard Shortcuts`?

**Comment by marinsokol5** [comment]
@ronblum 
Functions commonly used during debugging. 
```
Execute the next line of code.
Step into the current function call.
Continue execution until the next breakpoint is encountered.
```

All of them currently have hardcoded keyboard shorcuts and we are unable to modify them.

**Comment by xuancong84** [comment]
Being able to customizing debugging hotkeys is a very important feature for any IDE. The reason why this feature is missing in the existing RStudio is because the high-level architectural design is not elegant enough. An elegant design should include:

1) every menu item in the recursive menu tree;
2) basic editor commands like going to line beginning, deleting current line, etc. which may or may not be present in the program menu.

In this way, no matter what future modification you make in the program menu hierarchy, you will not miss out the corresponding hotkey entry.
