### ISSUE TITLE
Make keybindings work in console

### ISSUE THREAD

**Issue by hammer** [rstudio/rstudio#3556]
As requested at https://stackoverflow.com/questions/40457084/how-to-set-the-consoles-key-binding-in-rstudio. I would also like to be able to use emacs keybindings in the R console--particularly useful for those of us who worked primarily in ESS in the pre-RStudio era.

**Comment by ronblum** [comment]
@hammer Thank you for the suggested feature!

**Comment by cunningjames** [comment]
For what it's worth, persnickety folks like me _still_ find themselves going back to ESS because the keyboard shortcuts in RStudio are ... eh ... let's not say half-baked, let's say still somewhat doughy. Switching to the console and expecting my fingers' favorite shortcuts to work is painful every time.

**Comment by ctm22396** [comment]
Please let me know if this is poor github etiquette, but this is a feature that I would like to see as well. It is frustrating to have to use different keys when switching to the console. For example I use ctrl+a and ctrl+e to navigate in the script, but these do not work in the console.

**Comment by gtritchie** [comment]
> Please let me know if this is poor github etiquette

Not bad etiquette at all. Even better is to click the Thumbs Up on the original comment; we do look at those counts to find popular requests when planning future work.

**Comment by ukpro** [comment]
I would very much like to see this...
