### ISSUE TITLE
greyed window of rstudio addins after turn on proxy

### ISSUE THREAD

**Issue by shizidushu** [rstudio/rstudio#3562]
### System details

    RStudio Edition : Server 
    RStudio Version : 1.2.1013
    OS Version      :  Debian 9
    R Version       :  3.5.1

### Steps to reproduce the problem

- turn on proxy
- access `Addins ==> Render reprex`
- greyed window pops up

### Describe the problem in detail

I open a [issue about greyed window of rstudio addins](https://github.com/rstudio/shiny/issues/2053) months ago

Now I find proxy might be the problem. When I turn on Lantern (manage system proxy) on my computer (Fedora 28), the Rstudio Server (run on a remote sever) addins doesn't work (window greyed out). However, the rstudio server (version 1.1.456 run on my local computer) addins keep working.

### Describe the behavior you expected
no greyed window

**Comment by jmcphers** [comment]
This is probably because your proxy is not handling websockets correctly. RStudio add-ins use Shiny windows, and Shiny uses websockets; if it can't establish a connection you'll see the greyed out behavior.

This forum is for reporting bugs in RStudio. For help configuring your system to work with RStudio Server, please visit our community forum:

https://community.rstudio.com/c/rstudio-ide

Hope this helps!

**Comment by kalaschnik** [comment]
We are using Apache and we were missing the `proxy_wstunnel` module. After installing it, shiny apps were not grayed-out anymore. Project sharing also works!
Install the apache module with `sudo a2enmod proxy_wstunnel`
