### ISSUE TITLE
Open tabs including new files disappear after restarting R

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#3568]
### System details

    RStudio Edition : Server
    RStudio Version : 1.2.1013
    OS Version      : Ubuntu 16.04.5, SUSE 12.3, Red Hat 7.5
    R Version       : 3.4.4 and 3.5.1

### Steps to reproduce the problem

1) Open some existing files and a new file (don’t save it). 
2) “Session -> Restart R” or “Run -> Restart R and …” in an Rmd file.

### Describe the problem in detail

R will restart in the console, then the message below will pop up. Clicking on the button will cause the browser to refresh, and all the tabs will be gone, including any unsaved files.

<img width="276" alt="restart_r" src="https://user-images.githubusercontent.com/31009952/46297791-8f3b4980-c56b-11e8-9bc9-2ddd3a197a7b.png">

### Describe the behavior you expected

The tabs, including new/unsaved files, should remain. This works correctly in RStudio Server Pro and Desktop, and worked in 1.1.456.

**Comment by jmcphers** [comment]
Discussed this real-time with @ronblum since I wasn't able to reproduce locally.

Some notes from the call:

- Neither of us could repro on a clean VM with 1.2 installed
- All affected machines are on EC2 (this may or may not be relevant)
- All affected machines have had both an installation of 1.1 and 1.2 (this may or may not be relevant)
- If a machine had the problem with 1.2, it *also* had the problem with 1.1 
- Switching file locking types did not help
- Blowing away the `.rstudio` folder fixed the problem

There are too many variables to know exactly what's causing this without heavier debugging, but we can at least conclude it is not a regression in 1.2. 

Since blowing away the state in `.rstudio` fixes the issue, the problem is probably associated with some session state being written there. It is still possible that this is a 1.2 bug (i.e. that 1.2, given state from 1.1, corrupts it in some way that makes restarting the session not work in both 1.1 and 1.2), but we can't tell for sure at this point.

**Comment by kevinushey** [comment]
Do we see any `lock_file` instances being left behind in the `~/.rstudio` folder? What is the output of

    find ~/.rstudio -name "lock_file"

If a lock file exists, does that lock file go away if the session is closed?

**Comment by kevinushey** [comment]
I'm able to reliably reproduce this now. The simplest way to do this with RSO installed is to try duplicating the active session folder; e.g. with a session running in RSO, try running the following:

```sh
cp -R ~/.rstudio/sessions/active/* ~/.rstudio/sessions/active/session-abcd1234
```

Now, whenever you attempt to restart your R session, you'll see the 'R Session Disconnected' message.

I suspect it's possible to get into this state through the following sequence of actions:

1. Install RSP,
2. Launch multiple sessions (so the `sessions/active` directory is filled up),
3. Forcefully kill these R sessions and the server (so they don't get a chance to clean up session state directories),
3. Uninstall RSP and install RSO.

If RSO is installed without giving RSP a chance to clean up the old session state folders, it's possible the user could get stuck in this state.

Because getting stuck in this state requires a fairly specific set of actions and won't affect most users, I think we can bump this out of v1.2.

**Comment by ronblum** [comment]
Confirmed! Multiple sessions followed by `server-multiple-sessions=0` reproduced the issue.

**Comment by ronblum** [comment]
Closing this it out as an RStudio Server Pro issue.
