### ISSUE TITLE
R Studio does not quit

### ISSUE THREAD

**Issue by snag18** [rstudio/rstudio#3671]
Hi, 

I think i do have a bug in my R studio as it refuses to quit. The last command I had given was the debug(ls) and that same command appears again and again and doesn't stop after I have clicked on the Stop button. I get a window asking me if I want to save my file or not and then the program begins to quit. It has been quitting for an hour now but to no avail. I cannot restart or shut down my laptop because of this. Please help. 

### System details

    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       :

**Comment by jmcphers** [comment]
Try `undebug(ls)`. :-)

If that does not work, you will probably have to force-quit RStudio. RStudio itself calls `ls` a lot, so if you set the debug flag on it, it's difficult to get out of. 

We generally recommend using `debugonce` instead of `debug` for this reason. See this article for more help:

https://support.rstudio.com/hc/en-us/articles/205612627-Debugging-with-RStudio
