### ISSUE TITLE
packages fail to update when using a VPN

### ISSUE THREAD

**Issue by sycoforbidden** [rstudio/rstudio#3673]
### System details

    RStudio Edition : Desktop
    RStudio Version : Version 1.1.456
    OS Version      :  Windows 10 Home
    R Version       : 3.5.0

### Steps to reproduce the problem

- Use a VPN
- Try to install or update packages

### Describe the problem in detail

When using a VPN, the CRAN links become unaccessible to R Studio only, even if in a browser these are still accessible.
After turning the VPN off, they become accessible again.
I tried using options(repos = "New link...") but failed, regardless of the link i put in.

### Describe the behavior you expected

I expected R Studio to get the packages regardless of network configuration.
Not using a VPN may prove insecure for certain cenarios, so this bug should be addressed.

**Comment by kevinushey** [comment]
We haven't seen this before (even with a VPN active) so we suspect it must be something specific to how your VPN is configured.

**Comment by jmcphers** [comment]
Our community forum is a great place to ask questions about configuration. 

https://community.rstudio.com/c/rstudio-ide

See `?download.file` for more info on how R accesses CRAN links.

**Comment by timeddilation** [comment]
FYI, for anyone who encounters this issue in the future, I have found a workaround. I've been having the same issue for weeks while using my company's VPN. The problem is that the default method in `download.file` is to use wininet in Windows 10, and there is a bug here on certain types of VPNs. I can reproduce the issue while connected to a l2TP/ipsec VPN. You can fix this if you change the method to libcurl.

Ensure you have libcurl enabled:
`capabilities("libcurl")` 
should return `TRUE`

Then you can use that method in `download.file` and it should work.
`install.packages("data.table", method = "libcurl")`

**Comment by 2jzfx** [comment]
An issue is alive and well to this day on our end of things . Using SSL VPN end user is unable to install packages . Disabling it seemingly resolves it. Will test the workaround.
