### ISSUE TITLE
Keyboard shortcuts Ctrl + PgDn and Ctrl + PgUp don't navigate between chunks

### ISSUE THREAD

**Issue by robinryder** [rstudio/rstudio#3727]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.1.456
    OS Version      : Kubuntu 18.04
    R Version       : 3.5.1

### Steps to reproduce the problem

1. _File -> New R Markdown Notebook_
2. Place cursor in the first chunk.
3. Ctrl + PgDn

### Describe the problem in detail

The keyboard shortcuts Ctrl + PgDn and Ctrl + PgUp are supposed to make the cursor go to next/previous section/chunk, per the Keyboard Shortcuts Help. This does not happen.

Note that if there are several tabs open in the editor, these shortcuts allow to navigate between tabs: Ctrl + PgUp is a synonym of Ctrl + Tab and Ctrl + PgDn is a synonym of Ctrl+ Shift + Tab.

### Describe the behavior you expected

The shortcuts should lead to the next/previous chunk. Alternatively, the Keyboard Shortcuts Help should be corrected.

**Comment by kevinushey** [comment]
Looks like it's been this way for a while. The issue here is that we have two competing bindings for Ctrl + PageUp and Ctrl + PageDown, e.g.

https://github.com/rstudio/rstudio/blob/2ce99b49616fc7bf8104caee2a8ed84d06111ae9/src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml#L632

https://github.com/rstudio/rstudio/blob/2ce99b49616fc7bf8104caee2a8ed84d06111ae9/src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml#L675

Not sure if we should try to adjust the keybindings or just update the documentation.

**Comment by robinryder** [comment]
I would argue that it would be useful to have a shortcut for jumping to the next chunk. There is already another shortcut for switching tabs.

**Comment by sn248** [comment]
I am still seeing this keyboard binding not working, i.e. `Ctrl+PgUp/PgDn` do not take me to the next section. I have also tried changing the keyboard binding to another set of keys and this still does not work, .e.g. `Ctrl+PgUp` in the code below jumps from `Section 1` to `Section 3`

```
## Section 1 --------------
print("Section 1")

## Section 2 --------------
print("Section 2")



## Section 3 --------------
print("Section 3")

```
On the other hand `Ctrl+Alt+T` runs each section separately.

System details

```
RStudio Edition : Desktop
RStudio Version : 1.1.383
OS Version      : Windows 10
R Version       : 3.5.1

```
