### ISSUE TITLE
RStudio Versions 1.2.x do not show data in RStudio Data Viewer 

### ISSUE THREAD

**Issue by gregkvas** [rstudio/rstudio#3734]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1070
    OS Version      :  Windows 7 Prof. SP1 64bit; Windows 10 Home 64bit
    R Version       : R-3.5.1

### Steps to reproduce the problem
1. Copy a .csv Textfile into the data directory of a R Project
2. Reading the .csv Textfile via read_delim() into the workspace:
Textfile <- read_delim("data/Textfile.csv", delim = ";", locale = locale(decimal_mark = ".", grouping_mark = ","))
3. View(Textfile) or selecting in Global Environment

### Describe the problem in detail
When trying to view a read in .csv Textfile in the RStudio Data Viewer, only a blank tab occurs, i.e. NO grid, NO attributes, NO data, eventhough there is data in the Textfile. However, using the command utils::View(Textfile) shows the data frame with the data of the Textfile in the "utils-Data-Viewer" without any problem.

### Describe the behavior you expected
I would have expected, that the read in Textfile is beeing shown with its values in the grid of the RStudio Data Viewer, for this works for the "utils-Data-Viewer" just fine.

Thanks for any help!
Best, Gregor

**Comment by ronblum** [comment]
@gregkvas I am unable to reproduce this on either Windows 10 or MacOS 10.14. Can you please provide a sample .csv file so that we can try to reproduce?

**Comment by gregkvas** [comment]
Hi Ron!
I uploaded the Textfile and screenshots of the described behaviour.

Thanks for any help!
Gregor

[Textfile_Screenshots.zip](https://github.com/rstudio/rstudio/files/2512561/Textfile_Screenshots.zip)

**Comment by kevinushey** [comment]
If you open developer tools, we can see there's a JSON parsing error. The JSON blob is:

```
"[{"col_label":"","col_max":0.000000000000000,"col_min":0.000000000000000,"col_name":"","col_search_type":"none","col_type":"rownames","col_type_r":"","col_vals":[""]},{"col_breaks":[-500000000000000.0,0.000000000000000,500000000000000.0,1000000000000000.,1500000000000000.,2000000000000000.,2500000000000000.,3000000000000000.],"col_counts":[1,2,2,3,0,0,2],"col_label":"","col_name":"X","col_search_type":"numeric","col_type":"numeric","col_type_r":"double","col_vals":[""]}]"
```

Note that some numbers there have a trailing `.`, e.g.

```
1000000000000000.
```

which is not valid for a JSON number.

**Comment by gregkvas** [comment]
@pascaloettli and @kevinushey  thanks a lot for your explorations!

What actions could be taken then, to make the very large numbers in attribute "Pseudonym" work with the RStudio Data Viewer without altering or ommitting them, for they are needed for further joins within other tables?

Does the exploration from @kevinushey mean, that RStudio can not show very large numbers in RStudio Data Viewer because they are getting corrupted by a trailing "." in the viewing process which makes them no valid JSON numbers anymore?

**Comment by kevinushey** [comment]
Right; this is just exploration of what the underlying issue is (and we'll try to fix this in v1.2 since this works correctly in v1.1)

**Comment by kevinushey** [comment]
I think this is a bug in our JSON serialization library. Here:

https://github.com/rstudio/rstudio/blob/367639dbd2016c86ff1574418a9f370dcb7908ad/src/cpp/core/json/spirit/json_spirit_writer_template.h#L135-L136

The use of `showpoint` and `setprecision` together can effectively cause this sort of invalid JSON to be generated. (I'm not sure why this is done, since IIUC JSON explicitly allows for exponential notation in representing numbers)

At least here: https://github.com/png85/json_spirit/blob/master/json_spirit/json_spirit_writer_template.h#L196

we can see that this particular change was evidently rolled back (or never existed? Not sure if that was some kind of local patch)

@jmcphers: what do you think about patching JSON Spirit to remove the extra formatting bits for real numbers? Feels pretty ugly to be touching something like this so close to release, though.

**Comment by jmcphers** [comment]
> what do you think about patching JSON Spirit to remove the extra formatting bits for real numbers?

I definitely wouldn't churn that code this close to release as it's used just about everywhere. In 1.3 we're going to remove JSON Spirit entirely in favor of [RapidJson](https://github.com/Tencent/rapidjson), which I suspect does not suffer from this issue.

It looks like this is a problem only in 1.2 (and not 1.1) because of the new `col_breaks` data. What I'd suggest instead is to patch this problem specifically by marshaling these particular numbers into strings _prior_ to JSON conversion, then `parseFloat` on the way back out on the JavaScript side.

**Comment by kevinushey** [comment]
That sounds good to me. I'll explore that.
