### ISSUE TITLE
Changing the font size of Latex output rendered as preview in RMarkdown documents

### ISSUE THREAD

**Issue by expersso** [rstudio/rstudio#3774]
When writing RMarkdown documents, it would be very useful if one were able to adjust the font size of the preview of the Latex output. Equations are often rendered in giant fonts (e.g. see below), which makes it cumbersome to write longer documents with preview activated. From what I can tell, there is currently no support for in RStudio for making such adjustments.

![image](https://user-images.githubusercontent.com/7280464/47640516-10cec900-db64-11e8-80af-e33afe635681.png)

**Comment by kevinushey** [comment]
The issue placeholder asks you information about your system (OS, version of RStudio, version of R) for a reason. Without it, we cannot help you.

**Comment by expersso** [comment]
That's fair. My apologies. For the example above I was using Windows 7, RStudio 1.2.720, and R 3.4.1.

```
> sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: i386-w64-mingw32/i386 (32-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1
```

**Comment by ronblum** [comment]
@expersso I'm able to reproduce this on 1.2.720. However, it's working on the latest build, 1.2.1807. Can you please try a recent build and see if the issue is resolved for you?

<img width="766" alt="issue_3774" src="https://user-images.githubusercontent.com/31009952/47919628-2e62a200-de86-11e8-9a6c-102d1eb4262a.png">

````
---
title: "Issue 3774"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

$$
GNI = GDP + Y_f \\
GNDI = GNI + TR_f = C + I +\underbrace{(Ex - Im + Y_f +TR_f)}_{\text{Current account(CA)}} \\
GNDI - \underbrace{C- I}_{\text{Absorption (A)}} = CA \\
GNDI - A = CA
$$
````

**Comment by jmcphers** [comment]
Closing since we haven't heard back in a year.
