### ISSUE TITLE
Copying tabulated text produces missaligned text.

### ISSUE THREAD

**Issue by skanskan** [rstudio/rstudio#3779]
Hello.

This is a small cosmetic bug I see on Rstudio since a long time ago. It happens on all my computers with Windows 10 no matter the version of R and Rstudio you are using.
When you copy a text (code) containing tabulations and paste it on a different tab page the output appears completely missaligned, the space created by the tabulations are much wider and you need to delete it manually.

**Comment by jmcphers** [comment]
This is caused by the "reindent on paste" setting. You can disable it in *Options -> Code -> Editing -> Auto-indent code after paste*

In RStudio 1.3 (not due out for a while) we're adding separate "paste with indent" and "paste without indent" commands so that it isn't necessary to toggle the option to change behavior. See here for more: https://github.com/rstudio/rstudio/pull/3596
