### ISSUE TITLE
Feature request: Open filetype in Rstudio Addins

### ISSUE THREAD

**Issue by vnijs** [rstudio/rstudio#3812]
I have a shiny app that runs (best) as an Rstudio Addin. The app can save the state of the application making it easy to start back up where you left off with your analysis. The file extension I use for these "state" files is `.state.rda`

If would be great if there was an option to double click on a file of that type and have Rstudio open the .state.rda file in Addin. I have a relevant command as part of the radiant package that would already do something like this once Rstudio has been opened:

```
radiant::radiant("https://github.com/radiant-rstats/docs/raw/gh-pages/examples/demo-dvd-rnd.state.rda")
```

It would be great if something like this could be added to an `addins.dcf` file, i.e., double click a file in the OS file browser (e.g., Finder), open Rstudio, and run a command on that file. I had hoped that this might work with .Rprofile but these commands would need to run *after* Rstudio has been opened.

Rstudio addin: https://github.com/radiant-rstats/radiant

**Comment by jmcphers** [comment]
This is a neat idea but hasn't had any love in over a year, and we're not likely to implement it in the next year. One reason is that creating file associations requires admin privileges, and since add-ins are discovered rather than installed there's no reasonable place to hang the escalation. :-/ Closing for now.
