### ISSUE TITLE
Cannot type into Source window after toggling "Allow drag and drop of text"

### ISSUE THREAD

**Issue by psalveson** [rstudio/rstudio#3992]
### System details

    RStudio Edition : Desktop
    RStudio Version :  1.2.1163
    OS Version      :  Windows 10 x64
    R Version       :  3.5.1

### Steps to reproduce the problem
Tools > Global Options > Code > Display
Remove the check mark from "Allow drag and drop of text".
Click "OK".

### Describe the problem in detail
After turning "Allow drag and drop of text" off, I am no longer able to type in the "Source" window. I am able to type in the console and terminal per usual. To the remedy this issue, turn "Allow drag and drop of text" back on. I've noticed this behavior in the last few previews.

### Describe the behavior you expected

I expected to turn "Allow drag and drop of text" off and still be able to type in the source window.

1. The output of sessionInfo() 

Happens regardless of packages loaded.

2. The R code in question

None

-Peter

**Comment by kevinushey** [comment]
Thanks for the bug report! I can reproduce this; we'll try to get this fixed up for the v1.2 release.

**Comment by kevinushey** [comment]
Likely caused by this API call here:

https://github.com/rstudio/rstudio/blob/fa6ce5ca84b8d3fc6f024a46808cd0590cd7321d/src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditorWidget.java#L1149-L1157

And we update / set this property here:

https://github.com/rstudio/rstudio/blob/fa6ce5ca84b8d3fc6f024a46808cd0590cd7321d/src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java#L6771-L6775

But we're really setting the _wrong_ preference: there's two behaviors that have unfortunately been conflated:

1. Are we currently dragging a document tab?
2. Have we enabled / disabled text drag into an Ace instance?

It looks like changing this preference is erroneously toggling (1) instead of (2).

**Comment by kevinushey** [comment]
@jmcphers can you take a look? Looks like you were most recently in this code (although it was a while ago): https://github.com/rstudio/rstudio/commit/ac87fcdea7ebba5646d6605c874f3962ae513a42
