### ISSUE TITLE
Files pane hangs application on a directory with a lot of files

### ISSUE THREAD

**Issue by sentieonycdev** [rstudio/rstudio#4023]
Using RStudio Server ... the Files pane hangs the server and the UI on a directory with 10,000 files.
Can the Files pane not paginate the directory?

### System details

    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       :

**Comment by ronblum** [comment]
@sentieonycdev Thank you for filing this issue. We will review it as we work on development of future versions of RStudio.

Reproduced with RStudio Desktop 1.2.1184-1 on MacOS 10.14.2 and RStudio Server 1.2.1186-1 on Ubuntu 16.04.5. In addition, when I tried refreshing the Files pane or switching directories after removing the files from the terminal, I got the following error instead:
<img width="521" alt="many_files" src="https://user-images.githubusercontent.com/31009952/49762957-50c3b880-fc99-11e8-8606-0fb0e38e3b78.png">

**Comment by kevinushey** [comment]
That error is due to the large recursion in `findNodes()` here:

https://github.com/rstudio/rstudio/blob/5783d0e0df42ed1b16f530aadfc3bdd1f59b32db/src/gwt/src/org/rstudio/core/client/widget/RStudioDataGrid.java#L65-L78

In particular, the recursion for each sibling becomes quite expensive:

https://github.com/rstudio/rstudio/blob/5783d0e0df42ed1b16f530aadfc3bdd1f59b32db/src/gwt/src/org/rstudio/core/client/dom/DomUtils.java#L645-L681

**Comment by jmcphers** [comment]
That code is new in 1.2 (we added it to deal with some scrollbar drawing issues in Chromium), so this is probably a regression we need to fix.

**Comment by jmcphers** [comment]
@ronblum:

> Reproduced with RStudio Desktop 1.2.1184-1 on MacOS 10.14.2 and RStudio Server 1.2.1186-1 on Ubuntu 16.04.5.

@kevinushey 

> That error is due to the large recursion in findNodes() here:

We only enter that code on MacOS, but Ron observed it on Ubuntu, so something else is going on (too).

**Comment by jmcphers** [comment]
See #2808 and #3707 for some of the issues the original change was meant to address.
