### ISSUE TITLE
.rs.api.getThemeInfo() no longer returns foreground and background colors

### ISSUE THREAD

**Issue by javierluraschi** [rstudio/rstudio#4055]
I believe there was a good reason to remove from `.rs.api.getThemeInfo()` the `foreground` and `background` fields by adding support for custom themes, but `r2d3` and other packages could still make use of getting the foreground and background programmatically.

Related to https://github.com/rstudio/r2d3/issues/50

**Comment by jmcphers** [comment]
If memory serves, we removed this because it was implemented by hand-extracting foreground and background colors from the hard-coded theme list. Now that you can load any old CSS file as a theme, attempting to scrape out the fore and back colors is somewhat difficult without doing some level of finicky parsing and interpretation of the CSS. 

I wonder, though, if there's another way to do it -- we could have the browser send the server its current theme values (just by reading the computed style off the screen) after application and whenever the theme changes.
