### ISSUE TITLE
Single tick mark double autocompletes

### ISSUE THREAD

**Issue by jgoodwyn** [rstudio/rstudio#4062]
Currently, in RStudio when autocomplete is turned on and using a tick mark ` to denote a variable with spaces in it, it autocompletes again. Entering a tick mark correctly generates the closing tick mark, but once the partial variable name is entered and autocomplete choices for variables in the environment appear and one is selected, another closing tick mark is incorrectly generated.

Example of code I was trying to write: sum(`` ` ``Allocated Total`` ` ``)

**Comment by kevinushey** [comment]
We appreciate your taking the time to fill out a bug report, but can you also please fill out the issue template so we know what version of RStudio, R, and OS you're working with?

```
### System details

    RStudio Edition : <!-- Desktop or Server -->
    RStudio Version : 
    OS Version      : 
    R Version       : 
```

**Comment by jgoodwyn** [comment]
### System details

    RStudio Edition : Desktop
    RStudio Version : Version 1.1.442
    OS Version      : macOS  Mojave 10.14.1
    R Version       : 3.4.4 (2018-03-15)

**Comment by ronblum** [comment]
Confirmed. Also, the behavior is slightly different between in 1.2 and in the R terminal:
- 1.1: ```sum(`Allocated Total``)```
- 1.2: ```sum(` `Allocated Total``)```
- R (with space): ```sum(` Allocated Total`)```
 -R (no space): ```sum(`Allocated Total`)```

R doesn't not require the initial space, and it shouldn't be used because R won't recognize the variable). So I think there are two issues here:
1) Do not require a space for autocompletion within tick marks
2) When autocompletion is used, rely on any existing tick marks.
