### ISSUE TITLE
[Windows] Knitr not detected in R presentations

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#4169]
**Steps to reproduce:**
* Install `knitr`, e.g. `install.packages(“knitr”)`
* Create a new R presentation through the button at the top-left that has a white paper with a green plus sign on top.

**Expected behavior:**
Tab `Presentation` in the top-right pane should render the demo file that is automatically generated as new presentation.

**Actual behavior:**
In windows 10 (but not in linux), shows the title and a background, but has this error message on top and does not display further slides:
```
Error in library(knitr) : there is no package called 'knitr'
Execution halted
```

**Setup:** RStudio 1.2.1237, R 3.5.1, running on windows 10

Doesn’t make a difference whether the library is loaded (`library(knitr)`), the R session is restarted, or RStudio is relaunched. Other types of documents such as Rmarkdown detect `knitr` successfully and don’t throw such error.
![no_knitr](https://user-images.githubusercontent.com/11860098/51244380-a1f85380-198d-11e9-8a6c-46dbf4c0f053.png)

**Comment by kevinushey** [comment]
I wasn't able to reproduce.

Do you have a startup file (or similar) that affects your R library paths? What is the output of `.libPaths()` and `find.package("knitr")` in your R session where `knitr` is available?

**Comment by david-cortes** [comment]
> I wasn't able to reproduce.
> 
> Do you have a startup file (or similar) that affects your R library paths? What is the output of `.libPaths()` and `find.package("knitr")` in your R session where `knitr` is available?

I do have a startup script that modifies the library paths, but `find.package("knitr")` returns the first path (+ `/knitr`) from `.libPaths()`.

**Comment by kevinushey** [comment]
I'm guessing that the presentations are viewed with an externally-run R command that perhaps doesn't receive the same library paths as your current session.

**Comment by jmcphers** [comment]
That's correct. 

https://github.com/rstudio/rstudio/blob/e816f7e51aa74695f1d548b104674e2d602aa99f/src/cpp/session/modules/presentation/SlideRequestHandler.cpp#L313-L349

When we start an external R process we typically forward `R_LIBS` so that we get access to the library paths, as here:

https://github.com/rstudio/rstudio/blob/8af730409bb6d651cc8f6816d136bea91441e7a4/src/cpp/session/SessionAsyncRProcess.cpp#L146-L154

It looks like we might just need to do this when executing R presentation slides.
