### ISSUE TITLE
Bug - Alt rep string objects materialization in rstudio IDE

### ISSUE THREAD

**Issue by traversc** [rstudio/rstudio#4171]
I posted this on r-devel, but got no response.  Since it's an issue that mostly affects rstudio, I thought I'd post it here.  

I have a toy alt-rep string package that generates randomly seeded strings.

In R command line it works fine:
```
example:
library(altstringisode)
x <- altrandomStrings(1e8)
head(x)
[1] "2PN0bdwPY7CA8M06zVKEkhHgZVgtV1" "5PN2qmWqBlQ9wQj99nsQzldVI5ZuGX" ... etc
```

In Rstudio, I think Rstudio calls object_size or Object.size?  At any rate, on instantiation, the `set_altstring_Elt_method` is called for all elements 1 through 1e8 which forces materializing (slowly) of every element of the vector.  

This is a problem since the purpose of alt-rep is to defer evaluation until necessary.  

### System details

    RStudio Edition : Any
    RStudio Version : Any
    OS Version      : Any
    R Version       :  3.5+

### Steps to reproduce the problem
    Make an alt rep string object

### Describe the problem in detail
    See above

### Describe the behavior you expected
    Rstudio shouldn't force evaluation of alt rep string objects and possibly other alt-rep types

**Comment by kevinushey** [comment]
You are correct; RStudio calls `str()` and `object.size()` when updating the Environment pane with information about R objects in the global environment.

**Comment by traversc** [comment]
Thanks for confirming.  Will this behavior be changed in an update?

**Comment by jmcphers** [comment]
No, this is generally how the environment pane works for objects that it doesn't have specific knowledge of. 

If you need to work with these and don't want RStudio evaluating them, you can turn off the environment pane's auto refresh here:

![image](https://user-images.githubusercontent.com/470418/51357022-95a1f280-1a82-11e9-8035-3687c8fd5dd8.png)

Does that do what you want?

How are these objects implemented? There are some kinds of special objects (such as active bindings) which RStudio knows to avoid.

**Comment by kevinushey** [comment]
ALTREP objects are a new kind of object introduced in base R. They were described in DSC here:

https://www.r-project.org/dsc/2017/slides/dsc2017.pdf

Such objects typically defer the 'materialization' of their underlying R memory; e.g. one example is using a memory-mapped file behind an R vector here:

https://github.com/ALTREP-examples/Rpkg-simplemmap

Since users construct these objects and typically want to avoid forcing the materialization of the whole vector when possible, I think we'll have to screen these appropriately.

**Comment by traversc** [comment]
@kevinushey Yes I would like if Rstudio screened alt-rep objects in general.  

@jmcphers That's a workaround, but I disagree that it's what should happen.  

For example, if I implemented an alt-rep type in a package (which is what I want to do), users would have no idea what the issue would be if they instantiated such an object as in the original post, and Rstudio just hanged up.

**Comment by jmcphers** [comment]
> ALTREP objects are a new kind of object introduced in base R. They were described in DSC here:

Thanks, I wasn't aware of these! If they're a part of base R, I agree that we need to deal with them in the environment pane.

> I have a toy alt-rep string package that generates randomly seeded strings.

Do you have a copy of that package available for us to test against?

**Comment by traversc** [comment]
Here's the toy package: https://github.com/traversc/altstringisode

I also have a more serious package that uses  alt-rep strings you can test against: 

https://github.com/traversc/qs

**Comment by jmcphers** [comment]
Thanks! We'll take a look.

**Comment by jmcphers** [comment]
This is going to be a little trickier than I thought at first. `ALTREP` objects are well-nigh indistinguishable from the objects they wrap -- clearly intentional since they are intended to serve as alternative representations of those objects. Unfortunately that makes it difficult for us to figure out if a given object is an ALTREP from the external interface exposed by R. The above makes what looks more or less like a regular `STRSXP`. 

    > x <- altrandomStrings(1e8)
    > .Internal(inspect(x))
    @7ffd888ecd98 16 STRSXP g0c0 [NAM(1)] random_string_data (len=100000000, ptr=0x7ffd82ff89b0)

The good news is that there's a simple flag in the SEXPREC structure which indicates whether a SEXP points to an ALTREP, and even a macro which checks this flag.

https://github.com/wch/r-source/blob/8f3bd87455b38c416c1a72f7366f6f1f6ce032fc/src/include/Rinternals.h#L323

The bad news is that the `sxpinfo` structure is different for different versions of R, which means that if we want to use it, we have to import a copy for every version of R we work with and then dynamically resolve to the correct one at runtime based on the R version. We already do this unpleasant dance for the RCNTXT struct, for extremely similar reasons.

https://github.com/rstudio/rstudio/blob/8af730409bb6d651cc8f6816d136bea91441e7a4/src/cpp/r/RCntxt.cpp#L36-L51

It'd be nice if there were a way to identify ALTREP objects without taking this dependency on R internals, but the above should work if we can't find something more elegant.

**Comment by traversc** [comment]
Hi @jmcphers, I haven't dug into R source code too deeply, but I think you may be overcomplicating the issue.  Alt-rep objects were only implemented after 3.5 (Maybe 3.4?).  I know there has been a flag, but as far as I know, it is only a placeholder for earlier versions of R.  

R objects from earlier version can't be alt-rep objects (I think).  

So you could check for R version > 3.5+, and only then check for alt-rep using 3.5+ methods.

**Comment by jmcphers** [comment]
> only then check for alt-rep using 3.5+ methods.

This is the complicated bit (especially since we can't take a build time dependency on 3.5). Which check were you thinking of?

**Comment by traversc** [comment]
Could you do something like this?

```
// [[Rcpp::export]]
bool isAltRep(SEXP x) {
  // Check R version goes here
  // if R < 3.5, return false
  unsigned char* sexp_bytes = reinterpret_cast<unsigned char*>(x);
  return sexp_bytes[0] & 0x80;
}
```

**Comment by jmcphers** [comment]
Yes, we certainly could. The downside of that approach is that it depends on the bit fields in `sxpinfo` not moving around, and there's no guarantee they won't in the future. As noted earlier however we already have this issue for other internal R data structures we're forced to peek into, so not the end of the world.

**Comment by traversc** [comment]
@kevinushey @jmcphers I just tested out rstudio 1.2, and I don't believe the issue to be fixed.  Here's an example:

```
library(altstringisode)

z <- altrandomStrings(1e5) # works as expected and is not materialized

z2 <- data.frame(x = altrandomStrings(1e5), stringsAsFactors=F) # is unexpectedly materialized
```

I think the issue is more complicated than originally thought to be, since alt-reps could be hidden within other containers.  This issue would affect e.g. Jim Hester's vrooom package, which reads in CSV data using the alt-rep system, as well as my own package (mentioned above).  

Early materialization of a data.frame containing alt-rep data would defeat the purpose of particularly Jim Hester's package.

**Comment by jmcphers** [comment]
We have a similar problem for null external pointers (in which we have to recursively scan containers to see if there's a null pointer inside them somewhere, so we know to give those containers special treatment). We might have to do the same thing here.

Does overriding `str()` for the object in question help?

**Comment by traversc** [comment]
I'm not sure how overriding `str` would help.  But I think if you have a method that recursively scans an object for alt-rep data, that would be great!
