### ISSUE TITLE
NCBI Eutils Crashes 

### ISSUE THREAD

**Issue by npcooley** [rstudio/rstudio#4180]
I have an issue while running NCBI's Eutils in RStudio, that doesn't replicate in the regular R console.

A simple example I have is that calling the terminal command "esearch" through system, in the regular R Console, i'll return an expected output.

```R
system(command = "esearch -db assembly -query Archaea")
```
```
<ENTREZ_DIRECT>
  <Db>assembly</Db>
  <WebEnv>NCID_1_215148627_130.14.22.32_9001_1547825805_1831572895_0MetA0_S_MegaStore</WebEnv>
  <QueryKey>1</QueryKey>
  <Count>3263</Count>
  <Step>1</Step>
</ENTREZ_DIRECT>
```
The same command hangs in RStudio, and the session has to be terminated. This happens without anything fancy loaded, but i've included my session info below. What's puzzling is that I can call esearch's help flag in RStudio, and it returns the help as it would in the console, or in the terminal.

RStudio Version: 1.1.463

R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS  10.14.2

Matrix products: default
BLAS: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.5.1

**Comment by jmcphers** [comment]
We can't help with this since we don't have NCBI's Eutils or your environment, but what we'd generally recommend is checking that your relevant environment variables (esp. PATH and library loader vars like DYLD_LIBRARY_PATH) are set exactly the same in RStudio and the regular R console. Many behavior differences between R and RStudio are ultimately a result of different libraries/paths getting loaded.

If that doesn't help, you might try our community forum:

https://community.rstudio.com/c/rstudio-ide
