### ISSUE TITLE
Autocomplete function arguments does not engage after a newline

### ISSUE THREAD

**Issue by colearendt** [rstudio/rstudio#4219]
When typing a function with arguments on newlines, autocomplete is not accessible. It works great, so long as my cursor is still on the comma:

![image](https://user-images.githubusercontent.com/23075542/51702659-5c1d3a00-1fe2-11e9-80f9-4366ec979630.png)

But if I `<ENTER>` to a newline, `<TAB>` no longer means anything:

![image](https://user-images.githubusercontent.com/23075542/51702686-6b03ec80-1fe2-11e9-93a4-50bc3259b4e9.png)

If I put the comma _on_ the newline, then RStudio knows what to do... however, I know many style guides (and even RStudio's own comma behavior in some cases) do not recommend this:

![image](https://user-images.githubusercontent.com/23075542/51702751-97b80400-1fe2-11e9-87d3-6cf646ed7249.png)

It is a bit problematic that the user in this case _may_ actually want a `<TAB>` character, which probably makes this difficult to discern... I don't know what the right solution is :smile:

**Comment by colearendt** [comment]
FWIW, the same is true for the first argument as well:

![image](https://user-images.githubusercontent.com/23075542/51702967-24fb5880-1fe3-11e9-9f50-ad005b88458e.png)

Followed by `<ENTER>` and no autocomplete:
![image](https://user-images.githubusercontent.com/23075542/51702985-30e71a80-1fe3-11e9-824d-79be207cc3c6.png)

**Comment by kevinushey** [comment]
You can use <kbd>Ctrl + Space</kbd>. See also the `[ ] Use tab for multiline autocomplete` preference:

<img width="601" alt="screen shot 2019-01-24 at 12 22 35 pm" src="https://user-images.githubusercontent.com/1976582/51706270-c5954c80-1fd2-11e9-87f4-5c497e679df9.png">

The behavior here is intentional; it's more likely the user is pressing Tab to adjust indentation on blank lines rather than request autocompletion results.

**Comment by ronblum** [comment]
Closing this out since it's the intended and configurable behavior.

**Comment by colearendt** [comment]
Awesome! Thanks so much @kevinushey !!
