### ISSUE TITLE
Feature request: Word count for .Rmds (scripts pane)

### ISSUE THREAD

**Issue by garrettgman** [rstudio/rstudio#4237]
It would be very useful to have a word count appear at the bottom of the scripts pane when you write .Rmd files. The count should show the total number of words in the file. When you highlight a section of the file, the count should show the total number of words in the highlighted section. The count would be useful no matter how you decide to handle code chunks and YAML (I would not count them).

Two typical use cases:

1. Composing an abstract for a conference proposal (these are usually limited by number of words)
2. Tracking productivity with a #wordsperday slack channel

Word count seems more like a feature of a text editor than an IDE, but the IDE has become the de facto text editor for R Markdown documents.

**Comment by jmcphers** [comment]
Thanks for the suggestion! If you want to do this today, there's an add-in that helps:

https://github.com/benmarwick/wordcountaddin

**Comment by benmarwick** [comment]
I was chatting with @kevinushey recently about how wonderful it is to have live spellchecking in RStudio now (#2825), and was hoping that the talent responsible for that breakthrough (thanks @adamconroy !) might now be able to turn their brilliance to implementing live word count. 

Kevin suggested opening an issue, but since this one is here already, I'll just add to this one. I'm the author of the [wordcountaddin](https://github.com/benmarwick/wordcountaddin), and would love to see a way to get live word counts in the status bar at the bottom of the editor pane, or something like that.

**Comment by adamconroy** [comment]
@benmarwick how did you know my weakness was flattery? 😊
