### ISSUE TITLE
View throws error if importing utils in dev package

### ISSUE THREAD

**Issue by renozao** [rstudio/rstudio#4280]
This issue basically prevents from using View as soon as I load a dev package, since in most cases it imports `utils`, which is AFAIK necessary since the package check complains if utils is not listed there. 

### System details

    RStudio Edition : Server
    RStudio Version : 1.1.447
    OS Version      :  Linux
    R Version       :  3.5.0

### Steps to reproduce the problem
Create a package `ABC` (with `devtools::create`) with the following DESCRIPTON and NAMESPACE

DESCRIPTION:
```
Package: ABC
Title: What the Package Does (one line, title case)
Version: 0.0.0.9000
Authors@R: person("First", "Last", email = "first.last@example.com", role = c("aut", "cre"))
Description: What the package does (one paragraph).
License: What license is it under?
Encoding: UTF-8
LazyData: true
Depends: 
  R (>= 3.5.0)
Imports:
  utils
```

NAMESPACE:
```
# Generated by roxygen2: fake comment so roxygen2 overwrites silently.
exportPattern("^[^\\.]")
import(utils)
``` 

### Describe the problem in detail
`View` throws an error when trying to display a `data.frame`:

```R
> View(data.frame(a = 1:2))
> devtools::load_all("ABC")
Loading ABC
> View(data.frame(a = 1:2))
Error in .External2(C_dataviewer, x, title) : unable to start data viewer
In addition: Warning message:
In View(data.frame(a = 1:2)) : unable to open display
```

### Describe the behavior you expected
The data.frame should show up as a tab.

**Comment by jmcphers** [comment]
The problem is that you're importing all of `utils` in your `NAMESPACE`, including `utils::View` which shadows our own `View()` function. We won't change this behavior because some people need to be able to load the viewer from Utils.

You should be able to fix this by only importing the functions from `utils` that you need to use in your . dev package instead of importing the whole package. Here's an example from devtools:

https://github.com/r-lib/devtools/blob/e4e57aa6a775ef6f48eebc933ed7c4ad0a6e9c07/NAMESPACE#L157-L164

Hope this helps! Our community forum is a good place to continue the conversation if you're still stuck: https://community.rstudio.com/c/rstudio-ide

**Comment by renozao** [comment]
Thanks @jmcphers for your reply.
I imagine it is common to just import such a base package as `utils` entirely though, and aren't functions imported from other packages supposed to be accessible only from within the importing package, unless the package providing the function is attached? That is they should not be exported and shadow others in the Global environment.

Maybe:

  * RStudio can identify this situation and call its own `View` when clicking on the object's entry in the environment tab. It has a handle at that level and this may cover a large part of the use cases.
  * Provide an alias to the viewer function with a name that does not conflict with `utils::View` so that it can be called directly
  * it is a problem from `devtools::load_all`, which should not export the imported functions?

In any case, is there already a way to directly call Rstudio `View` function?
