### ISSUE TITLE
RMarkdown notebook defaults to inline output regardless of Global Options settings

### ISSUE THREAD

**Issue by isteves** [rstudio/rstudio#4334]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1237
    OS Version      : Windows 10
    R Version       : 

### Steps to reproduce the problem

1. Uncheck inline option in Global Options --> RMarkdown
2. Create new notebook file
3. Delete `editor_options: chunk_output_type: inline`
4. Try `plot(cars)`

### Describe the problem in detail/Describe the behavior you expected

I'm not sure if this behavior is limited by how notebooks are configured, but I expected that if no output options are configured automatically, the behavior would default to whatever is set in the Global Options.  As far as I can tell, Global Options have no effect on R notebooks.

**Comment by jmcphers** [comment]
This is intentional; a "notebook" implies inline output. All of the notebook features (such as the preview in the Viewer pane) don't make sense without it, so it always defaults to inline output mode. 

If you want a traditional R Markdown file without inline output, use an HTML document, which *should* respect the global option.

Maybe we could label the options better? Would also be curious to hear why you want to use a notebook but *don't* want inline output.
