### ISSUE TITLE
flashing scrollbars with Qt 5.12

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#4431]
### System details

    RStudio Edition : Desktop
    RStudio Version : v1.2.1322
    OS Version      : macOS 10.14.3
    R Version       : 3.5.1

### Steps to reproduce the problem

Open RStudio, and try navigating within the Files pane.

### Describe the problem in detail

![](https://user-images.githubusercontent.com/1976582/54099587-4471f900-4377-11e9-88ac-45ac31972d30.gif)

### Describe the behavior you expected

No flashing scrollbars.

### Notes

- Does not reproduce with Qt 5.11.3, but does reproduce with Qt 5.12.1.
- Does not reproduce if we disable this preference (https://github.com/rstudio/rstudio/blob/0868e5c7a78cb85fdb3d4b036ea66244177a1c2e/src/cpp/desktop/DesktopMain.cpp#L473-L478), but then sticky scrollbars return.
- Does not reproduce if mouse is plugged in (only reproduces with trackpad)
- Still reproduces when using software rendering (so evidently, something beyond the GPU is going on?)

### See Also

Flashing scrollbars. See https://github.com/rstudio/rstudio/pull/3078, https://github.com/rstudio/rstudio/issues/2808, https://github.com/rstudio/rstudio/pull/4047 for previous run-ins with this render bug.

**Comment by ronblum** [comment]
@kevinushey It looks like the scrollbar in the Environment pane sticks around when it shouldn't:
![more_scrolling](https://user-images.githubusercontent.com/31009952/54157880-9ec69480-441f-11e9-858d-9edb47cba0e0.gif)

**Comment by kevinushey** [comment]
I don't see a scrollbar in the environment pane. Can you provide more details on your configuration? Do you have a mouse plugged in?

**Comment by gtritchie** [comment]
Here's an example of what I'm seeing. This is on late 2015 iMac 5K, AMD Radeon R9 M390 2048 MB, macOS 10.14.3. RStudio 1.2.1322-3.

![2019-03-11_15-27-54 (1)](https://user-images.githubusercontent.com/10569626/54163061-fad7eb80-4414-11e9-9f85-5292db566e0b.gif)

**Comment by ronblum** [comment]
No external mouse. It happens when you mouse over the area at the bottom of the pane, when System Preferences -> General -> Show Scroll Bars is set to "Automatically" or "When scrolling," but not "Always." 

1. Close RStudio (so that we start fresh)
2. System Preferences -> General -> Show Scroll Bars -> Automatically (or When Scrolling etc.)
3. Open RStudio
4. Switch to Environment pane
5. Hover mouse over bottom of quadrant, right above the border
    - Horizontal scroll bar should appear
6. Click on another pane in the same quadrant
7. Click on Environment pane
    - Horizontal scroll bar is still gone

Follow that up with:

8. Hover over the bottom of the pane, so that the scrollbar returns
9. System Preferences -> General -> Show Scroll Bars -> Always
     - Horizontal scroll is still there
10. Mouse over the Environment pane
     - Horizontal scroll bar may or may not go away
11. Switch to another pane in the same quadrant
12. Switch to Environment pane
     - Horizontal scroll bar may go away or be replaced by a lighter-gray scrollbar

Next:

13. Close RStudio
14. Reopen RStudio
15. Hover over bottom of Environment pane
     - No horizontal scroll bar

**Comment by ronblum** [comment]
This is an issue in 1.2.1332.

**Comment by ronblum** [comment]
Closing and opening #4529 which covers the persistent floating scrollbar, which is a separate issue.
