### ISSUE TITLE
Data viewer status bar progressively becomes out of sync with visible data

### ISSUE THREAD

**Issue by calpan** [rstudio/rstudio#4517]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1327
    OS Version      : Windows 10 x64 1803 build 17134.648
    R Version       : 3.5.1

### Steps to reproduce the problem
View a data frame with more rows than can fit on one screen.
`View(airquality)`

### Describe the problem in detail
![](https://i.imgur.com/0Q0aTuI.png)
The data viewer appears to calculate the visible portion of the data set incorrectly. Here, rows 1-22 are visible, but the status bar indicates that rows 1-24 are being shown (perhaps it is including the height of the header row when calculating what should be visible). This discrepancy compounds as you scroll further down the dataset; by the time one scrolls to the end of the data set, the status bar says that rows 144-153 are being shown, when it is in fact rows 133-153.

For longer data sets (~200+ rows), this can result in situations where there is no overlap between what is shown and what the status bar says is shown.

Minor observation: rows with NA cells are taller than those without any NA values.  

### Describe the behavior you expected
The status bar should show the actual rows visible above it.

**Comment by ronblum** [comment]
@calpan Thank you for reporting this issue.

This might be related to #3465. I'm seeing different behavior on different OS, browser, and product. I need to investigate further to figure out the pattern.

**Comment by R-Hannibal** [comment]
Verified Fixed on: RStudio Version - 1.4.703, R Version - 4.0.2, Windows 10 x64 - Desktop

This issue is looking fixed in the [current daily build](https://dailies.rstudio.com/). There is some remaining odd behavior in this area with the status bar (narrowing the source view and scrolling to the end of the dataframe), but that is being tracked in a separate ticket [3465](https://github.com/rstudio/rstudio/issues/3465).
