### ISSUE TITLE
Impending requirement for non-MAS apps to be notarized

### ISSUE THREAD

**Issue by hrbrmstr** [rstudio/rstudio#4597]
Mojave 10.14.5 betas are beginning the slippery slope of requiring all non-MAS apps to be notarized: https://developer.apple.com/documentation/security/notarizing_your_app_before_distribution?language=objc

Right now, I believe RStudio falls into the grandfathered category since the current requirement is that "all _new_ software distributed with a _new_ Developer ID must be notarized in order to run".

Only noting this b/c RStudio appears to be RC but isn't notarized and Apple could just flip the switch completely in 10.14.6.

**Comment by jmcphers** [comment]
Yes, we just became aware of this earlier this week! Thankfully it's possible to get apps signed with a Developer ID notarized after release so we can do that very soon (but ideally we'd have the ticket stapled to the app itself for offline validation).

**Comment by jmcphers** [comment]
The good news is that I was able to generate a build of RStudio which was approved by the notarization service.

The bad news is that in order to be notarized, you have to enable the new Hardened Runtime, which of course we do not do yet. I signed our app bundle with `--options runtime` and RStudio doesn't boot.

```
[53764:1229933:20190409,152104.633860:WARNING process_memory_mac.cc:93] mach_vm_read(0x7ffeed0cd000, 0x2000): (os/kern) invalid address (1)
[53764:1229933:20190409,152104.635959:WARNING system_snapshot_mac.cc:42] sysctlbyname kern.nx: No such file or directory (2)
[53764:1229933:20190409,152104.968550:WARNING process_memory_mac.cc:93] mach_vm_read(0x7ffee9f9d000, 0x2000): (os/kern) invalid address (1)
[53764:1229933:20190409,152105.053444:WARNING system_snapshot_mac.cc:42] sysctlbyname kern.nx: No such file or directory (2)
```

Hopefully there's just some work to be done here:

1. Figure out which runtime entitlements we need; https://developer.apple.com/documentation/security/hardened_runtime_entitlements
2. Begin signing code with the secure timestamp (`--timestamp`) and hardened runtime (`--options runtime`) flags;
3. Send our builds to Apple's notarization service after completion in the lab; and
4. (later) Poll for completion of the notarization and amend the build with the stapled notarization ticket.

**Comment by jmcphers** [comment]
We have begun to see "unidentified developer" warnings on Catalina for builds we've recently signed, and think this may be related.

**Comment by jmcphers** [comment]
Some preliminary work is on this branch:

https://github.com/rstudio/rstudio/compare/feature/apple-notarization

**Comment by jmcphers** [comment]
Update with some recent research:

The minimal set of entitlements that allow RStudio to boot properly are `cs.disable-library-validation` and `cs.disable-executable-page-protection`. The latter is required by the JIT in Qt WebEngine as [reported here](https://forum.qt.io/topic/102212/qtwebengine-signing-issues/3).

RStudio boots and works if the `get-task-allow` entitlement is present, but crashes on launch if it isn't. Unfortunately that entitlement (which is required to attach a debugger) is not allowed in notarized apps for obvious reasons. 

It looks like the reason it's crashing (and the major impediment to notarization at this point) is that we sort out a lot of library locations at runtime, and you can't do this in a hardened application.

```
dyld: Library not loaded: @executable_path/libR.dylib
  Referenced from: /Volumes/RStudio-1.3.906/RStudio.app/Contents/MacOS/rsession
  Reason: no suitable image found.  Did find:
        file system relative paths not allowed in hardened programs
```

We use the `@executable_path` trick all over the place. For example:

- To load R at runtime,
- To load OpenSSL libs that are bundled with RStudio instead of system libs,
- To load the Qt framework bundled with RStudio, etc.

It's not clear yet whether we can continue to do this using some other mechanism or whether we need to rethink the way we load bundled libraries entirely.

**Comment by kevinushey** [comment]
A Firefox commit attempting to handle this here:

https://hg.mozilla.org/releases/mozilla-release/rev/4e7be2db653e644365fcf1c569552f1feaf3ee33

suggests that there's a flag we can request to make this possible.

```
+    <!-- Allow dyld environment variables. Needed because Firefox uses
+         dyld variables (such as @executable_path) to load libaries from
+         within the .app bundle. -->
+    <key>com.apple.security.cs.allow-dyld-environment-variables</key><true/>
```

Can we make use of `cs.allow-dyld-environment-variables`?
