### ISSUE TITLE
Use git bash's OpenSSH on windows

### ISSUE THREAD

**Issue by kendonB** [rstudio/rstudio#4623]
RStudio seems to set some environment variable that causes the "Terminal" when using git bash to use Window's native ssh instead of the one that ships with git bash.

I see this in RStudio when using git bash terminals:

```
$ ssh -Version
OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
```
and this in gitbash.exe
```
$ ssh -Version
OpenSSH_7.9p1, OpenSSL 1.1.1a  20 Nov 2018
```
Windows is slower at updating its own ssh, which leaves ssh security updates on the table for potentially long periods.

**Comment by kevinushey** [comment]
This is because the PATH is different between Git Bash and an RStudio terminal -- in particular, Git Bash adds entries like `/usr/local/bin` and `/usr/bin` that don't get added by RStudio. I'm not exactly sure why this occurs but it may be sensible to ensure that we retain the same PATH elements that one gets in a regular Git Bash session.

**Comment by kevinushey** [comment]
This is because the PATH is different between Git Bash and an RStudio terminal -- in particular, Git Bash adds entries like `/usr/local/bin` and `/usr/bin` that don't get added by RStudio. I'm not exactly sure why this occurs but it may be sensible to ensure that we retain the same PATH elements that one gets in a regular Git Bash session.

**Comment by kendonB** [comment]
I see @kevinushey. I have patched this for my purposes by explicitly referring to /usr/bin/ssh` every time I run ssh from RStudio.

**Comment by kendonB** [comment]
I had a colleague with a new PC report this issue as well.
