### ISSUE TITLE
re-evaluate QtWebEngine print support

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#4651]
Qt 5.12.4 should again support `window.print()`; we may want this for v1.3.

https://bugreports.qt.io/browse/QTBUG-53745

**Comment by jmcphers** [comment]
Here's the gross 1.2 code I'd love to remove:

https://github.com/rstudio/rstudio/blob/4512c098a0ece4df11608edda082aa0c2521db59/src/cpp/desktop/DesktopGwtCallback.cpp#L156-L207

**Comment by kfeinauer** [comment]
Having looked into this, I don't think it's possible to print so simply by effectively reverting https://github.com/rstudio/rstudio/commit/222f11216454b42f617f478916a94e6978681282. 

The issue here is that `window.print()` is indeed called, and we get the notification in the `QWebEgninePage` object, but this is simply a notification that something in the page has requested printing. In this case, it is the special iframe we construct within the page to contain the code contents.

However, we have no ability within QT WebEngine to grab the iframe itself - this is Javascript only, as noted here (https://doc.qt.io/qt-5/qwebenginepage.html):

```
An HTML document is loaded in a main frame within the web page. If it references child frames (as defined by the <frame> or <iframe> elements), they are considered part of the content. Child frames are individually accessible only through JavaScript.
```

So as far as I know, there is no effective way within the QT code to simply print the iframe. The best we can do is to print the entire page, which is clearly not what we want.

Let me know if I have any gaps in my understanding of how QT works and I can have another go at this.

**Comment by jmcphers** [comment]
I think we could make this work by reworking print so that it opens a new top-level window (instead of an iframe), and printing that. But that's more work than I think is warranted for 1.3 given that printing is rare these days.
