### ISSUE TITLE
list.dirs() connection issue

### ISSUE THREAD

**Issue by JeremiahLee1** [rstudio/rstudio#4661]
### System details

Version 1.2.1335
© 2009-2019 RStudio, Inc.
Build 1351 (f1ac3452)
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.1 Chrome/69.0.3497.128 Safari/537.36

### Steps to reproduce the problem
Installed and ran Swirl

Enter list.dirs() in Console
Get error - Error: C stack usage  7970900 is too close to the limit
Attempt to enter other command and get error - Error: Unable to establish connection with R session

Must then restart RStudio 

### Describe the behavior you expected

It is expected that list.dirs() works as intended and does not cause RStudio connection issues

**Comment by rich-rstudio** [comment]
Not able to reproduce on Version 1.2.1335
© 2009-2019 RStudio, Inc.
Build 1351 (f1ac3452)
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.1 Chrome/69.0.3497.128 Safari/537.36

**Comment by JeremiahLee1** [comment]
[rsession-jeremiahlee.log](https://github.com/rstudio/rstudio/files/3096454/rsession-jeremiahlee.log)

Attaching my log to see if you can get some useful info from it.
Or if there is a way to get a better log while/after issue happens, let me know.

**Comment by kevinushey** [comment]
Your log contains an error message I've never seen before :-)

I can only guess there's something unique about the directory you're working in that's causing `list.dirs()` to fail, and I expect that would fail in a plain R session outside of RStudio as well -- that is, the issue is likely not unique to RStudio.

I'd recommend following up at https://community.rstudio.com/.
