### ISSUE TITLE
RStudio crashes in MX Linux while installing packages

### ISSUE THREAD

**Issue by ambijat** [rstudio/rstudio#4680]
RStudio Edition : Desktop
    RStudio Version : 1.2.1335
    OS Version      : MX Linux 64 bit
    R Version       : 3.3

install.packages(igraph)

Above line leads to crash of Rstudio and it closes. After reopen and re-run the command leads to the lines of error reproduced below.

`ERROR: failed to lock directory ‘/home/ambijat/R/x86_64-pc-linux-gnu-library/3.3’ for modifying
Try removing ‘/home/ambijat/R/x86_64-pc-linux-gnu-library/3.3/00LOCK-igraph’
Warning in install.packages :
  installation of package ‘igraph’ had non-zero exit status`

After removing lock folder again running the script leads to crash again. It crashes while compiling.

**Comment by ronblum** [comment]
@ambijat Thank you for reporting this. RStudio isn't currently supported for MX Linux; the [list of support platforms](https://www.rstudio.com/about/platform-support/) is available at https://www.rstudio.com/about/platform-support/. I tried it on Ubuntu 18.04.2, but it works fine in it.

It's useful to have this ticket in case anyone else runs into the same issue. It might be useful to try out the following
1. Report any errors in the log files
2. See what happens if the lock file is removed
3. See what happens with a more recent version of R

**Comment by Spencerx** [comment]
Can't you run RStudio in a container, docker or jail or any form of virtualisation in MX? Unless you need direct access to hardware this shoud not be a major issue for most users who don't use things such as hardware accelerators, GPGUs and the likes.
