### ISSUE TITLE
Updated to RStudio 1.2.1335; now doesn't run on Linux Mint 18 64-bit

### ISSUE THREAD

**Issue by bateyt** [rstudio/rstudio#4710]
### System details

    RStudio Edition : Desktop
    RStudio Version : 
    OS Version      : Linux Mint 18 (64-bit)
    R Version       : 3.4.4

### Describe the problem in detail

Hello.

I'm running Linux Mint 18 (64-bit).  I just updated to the newest version of RStudio (rstudio-1.2.1335-amd64.deb).  Now, when I click on the RStudio icon, nothing happens.  I tried to run from the terminal's command line by typing `rstudio`, and I get the following message:

`rstudio: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory`

Should I re-install an older version of RStudio?  Any suggestions are much appreciated.  Thanks!

--Trey

**Comment by bateyt** [comment]
I just wanted to give an update.  I re-installed RStudio 1.1.463, and it still works.  So, if nothing else, I'll keep using that version.  I would still like to update eventually.  I hope someone has insight to this issue.  Thanks again.  --Trey

**Comment by jmcphers** [comment]
Mint is based on Ubuntu. Did you try the download for Ubuntu 18?

https://download1.rstudio.org/desktop/bionic/amd64/rstudio-1.2.1335-amd64.deb

**Comment by bateyt** [comment]
Yes.  The one that didn't work was the download for Ubuntu 18.  Thanks.

**Comment by jmcphers** [comment]
Did you try the other Ubuntu installers? You need to use one that matches your Linux Mint distribution, but I'm not familiar with Mint so can't tell you exactly which will match.

**Comment by rdewald** [comment]
@jmcphers I ran into a similar situation installing 1.2.1.1335 on (a fresh install of) plain vanilla Ubuntu 18.4.  OSS IDE version would crash on start, crash on (application) restart, and then stay running long enough after the third restart (of the application, not the OS) to make the loss of unsaved data really costly :-).  My entire console would lock up and become unresponsive, the only thing that would move me forward was a hard power-cycle (holding down the button til it all goes dark), so I didn't turn in a ticket right away because I wasn't sure I had eliminated hardware as the issue,

This happened a series of times, the "third restart is the charm, sort of" pattern was persistent.  I rebooted several times, did a sudo apt update, closed everything else that might be calling the same libraries, everything I could think of.   

The only thing non-standard about the hardware I have is the on-board video is disabled (because I am using a better video card).  Otherwise it's a fairly ordinary 8-core 3.5 Ghz Ryzen7 with 16GB of RAM.  Everything is on a LUKS partition with LVM on an SSD.  Also using apt's version of R 3.5.3.

Since I was up against a wall with something I needed to finish and couldn't locate a roll-back rpm (my bad) I installed the OSS server version of 1.2 1335.  

The server version runs like a charm, no problems or issues whatsoever.  As an RAdmin at work, I like this better anyway since everything is where I expect it to be, I should have done this from the beginning.

But, for your other customers, that might not be a desireable workaround, so I thought I would give you a heads up.

**Comment by jmcphers** [comment]
@rdewald Thank you for the additional detail, and glad the server version worked for you.

@bateyt Sorry we weren't able to help you here; we don't offer support for Linux Mint (we only formally support Debian, Ubuntu, RedHat, CentOS, and SuSE). You will probably be successful with one of the .deb packages since we build against a wide variety of OpenSSL versions (four at last count); if not, you might ask on the community forum: https://community.rstudio.com/c/rstudio-ide
