### ISSUE TITLE
environment pane declares S4 object as "Object with null pointer"

### ISSUE THREAD

**Issue by reikoch** [rstudio/rstudio#4741]
With the following code from the man page of SummarizedExperiment I create a simple object of this type:

```
library(SummarizedExperiment) 
nrows <- 200; ncols <- 6 
counts <- matrix(runif(nrows * ncols, 1, 1e4), nrows) 
rowRanges <- GRanges(rep(c("chr1", "chr2"), c(50, 150)), 
IRanges(floor(runif(200, 1e5, 1e6)), width=100), 
strand=sample(c("+", "-"), 200, TRUE), 
feature_id=sprintf("ID%03d", 1:200)) 
colData <- DataFrame(Treatment=rep(c("ChIP", "Input"), 3), 
row.names=LETTERS[1:6]) 
rse <- SummarizedExperiment(assays=SimpleList(counts=counts), 
rowRanges=rowRanges, colData=colData)

```
All works fine but in the environment pane it lists rse as 
"<Object with null pointer>".

Observed with RStudio server 1.2.1335 on RHEL 7.6 and with RStudio IDE 1.2.1335 on Windows 10.

**Comment by dfalty** [comment]
@reikoch Thank you for reporting this issue. I also see `<Object with null pointer>` on Mac 1.2.1335.

**Comment by kevinushey** [comment]
This is because the object does contain a null pointer:

```
> library(SummarizedExperiment) 
> rse <- SummarizedExperiment()
> rse@assays@.xData$.refClassDef@versionKey
<pointer: 0x0>
```

We've seen issues in the past where attempting to call `str()` on objects containing null external pointers could cause crashes, hence why the environment pane reports objects as such in these cases.

**Comment by mtmorgan** [comment]
This is from the methods package, where one typically creates a class definition and serializes it when the package is installed, and then uses the unserialized class definition after the package is loaded. This serialization / deserialization introduces the null pointer
```
> setClass("E")
> e = getClassDef("E")
> e@versionKey
<pointer: 0x10edf4a60>
> unserialize(serialize(e, NULL))@versionKey
<pointer: 0x0>
```
The above shows a standard S4 class; since reference classes are implemented as S4 classes, the same effect shows up there... The effect can be seen in, e.g., the methods package where the definition of the class used to represent S4 classes (or any of the other class definitions in the package) has a null pointer
```
> getClassDef("classRepresentation")@versionKey
<pointer: 0x0>
```
As far as I know (it must be the case, since it's a null pointer...) `versionKey` is unused. 

Apparently the display in RStudio causes some users confusion, e.g., at https://support.bioconductor.org/p/122184/

**Comment by kevinushey** [comment]
Thanks for the extra context, @mtmorgan.

FWIW, it may be that this check is no longer required. I think the primary culprit in this crash was igraph (https://support.rstudio.com/hc/en-us/community/posts/115007615008-Rstudio-crashes-on-running-monocole) and igraph has long since been upgraded to avoid this crash.

**Comment by bbolker** [comment]
There are a stack (as it were) of StackOverflow questions, and a Github issue, commenting on a similar symptom that occurs for `lme4` objects. I don't have easy access to RStudio right now (long story) and/or haven't been able to reproduce consistently. It's not a big deal but would be nice to resolve ...

- https://github.com/lme4/lme4/issues/619
- https://stackoverflow.com/questions/62770580/r-version-4-0-2-lm4-package-lmer-bug
- https://stackoverflow.com/questions/59365389/warnings-when-running-an-lmer-in-r
- https://stackoverflow.com/questions/64211186/glmer-models-in-rstudio-run-but-show-object-with-null-pointer-in-the-global-en
- https://stackoverflow.com/questions/65718024/setting-classx-to-environment-sets-attribute-to-null-result-will-no-longer
- https://stackoverflow.com/questions/68837177/object-with-null-pointer-appears-on-r-studio-environment

**Comment by srfall** [comment]
I am able to reproduce the issue @bbolker mentioned.

Steps to reproduce:
first run this
````
library(terra)
x1 <- vect("POLYGON ((0 0, 8 0, 8 9, 0 9, 0 0))")
x2 <- vect("POLYGON ((10 4, 12 4, 12 7, 11 7, 11 6, 10 6, 10 4))")

x <- rbind(x1, x2)

values(x) <- data.frame(xid=1:2)
crs(x) <- "+proj=utm +zone=1"
plot(x)
````
Result: no errors up to this point

then click on the "x"  object in the Rstudio Environment pane to open a new window to inspect the object.
now run:
````
plot(x)
````
again.

Result:

> Warning message:
In class(object) <- "environment" :
  Setting class(x) to "environment" sets attribute to NULL; result will no longer be an S4 object


````
> sessionInfo()
R version 4.2.2 (2022-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 22621)

Matrix products: default

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] terra_1.7-0

loaded via a namespace (and not attached):
[1] compiler_4.2.2   tools_4.2.2      Rcpp_1.0.9.5     codetools_0.2-18
###########################################
> rstudioapi::versionInfo()

$mode
[1] "desktop"

$version
[1] ‘2022.12.0.353’

$long_version
[1] "2022.12.0+353"

$release_name
[1] "Elsbeth Geranium"
````
