### ISSUE TITLE
Catalina: Warning: Features disabled: R source file indexing, Diagnostics

### ISSUE THREAD

**Issue by renkun-ken** [rstudio/rstudio#4755]
### System details

    RStudio Edition : Server
    RStudio Version : 1.3.154
    OS Version      : Ubuntu 16.04.6
    R Version       : 3.6.0

### Steps to reproduce the problem

If an active RStudio Server session is left idle for a while, then the following warnings may appear when I re-enter the session.

```
Warning message:
File monitoring failed for project at "~/Workspaces/rproj1"
Error 2 (No such file or directory)
Features disabled: R source file indexing, Diagnostics
sh: 0: getcwd() failed: No such file or directory
```

**Comment by kevinushey** [comment]
The warning messages imply that the directory hosting your project (`~/Workspaces/rproj1`) likely was no longer available when the RStudio session was resumed. Could that be the case? Is that directory (or a parent directory; e.g. the home directory) mounted or something similar?

**Comment by renkun-ken** [comment]
I guess it is caused by the auto-umount of user home folder by ecryptfs in Ubuntu 16.04.

**Comment by hrbrmstr** [comment]
I can echo being hit with this starting today.

- macOS 10.15 Beta (19A471t) — i.e. WWDC Catalina release
- RStudio Daily Build 207 (b5223eda, 2019-06-11)

This literally just happened 2 minutes ago:

```
Warning message:
File monitoring failed for project at "~/projects/2019-exim-uptime"
Error 2 (No such file or directory)
Features disabled: R source file indexing, Diagnostics
```

But, I've been getting it all day on both projects (when re-knitting things) and on packages (when building packages).

I was abt to file a new issue since I figured it was stupid macOS tricks but it might not be.

lemme know if I can run anything to triage for y'all.

**Comment by kevinushey** [comment]
@hrbrmstr do you see anything that appears relevant in the RStudio diagnostic logs? (~/.rstudio-desktop/log/rsession-<user>.log)

Most often, this implies that RStudio suddenly lost access to the project folder (e.g. if it were deleted).

**Comment by hrbrmstr** [comment]
Managed to reproduce this morning. Opened up `{ethercalc}` pkg project. Re-knitted README.Rmd.  Bot the "File monitoring…" blah blah msg.

I had shut down RStudio and cleaned out the session log file so it was fresh and when that "File monitoring…" error showed up I got this in the log:

>13 Jun 2019 13:05:25 [rsession-hrbrmstr] ERROR system error 2 (No such file or directory) [path=/Users/hrbrmstr/packages/ethercalc]; OCCURRED AT: void rstudio::core::system::file_monitor::(anonymous namespace)::fileEventCallback(ConstFSEventStreamRef, void *, size_t, void *, const FSEventStreamEventFlags *, const FSEventStreamEventId *) /Users/admin/workspace/IDE/macos-v1.3/src/cpp/core/system/file_monitor/MacFileMonitor.cpp:82; LOGGED FROM: void rstudio::session::projects::ProjectContext::fileMonitorTermination(const rstudio::core::Error &) /Users/admin/workspace/IDE/macos-v1.3/src/cpp/session/projects/SessionProjectContext.cpp:507
13 Jun 2019 13:05:29 [rsession-hrbrmstr] CLIENT EXCEPTION (rsession-hrbrmstr): (SecurityError) : Blocked a frame with origin "http://127.0.0.1:13919" from accessing a cross-origin frame.;|||org/rstudio/core/client/ScrollUtil.java#31::execute|||com/google/gwt/core/client/impl/SchedulerImpl.java#140::execute|||com/google/gwt/core/client/impl/Impl.java#306::apply|||com/google/gwt/core/client/impl/Impl.java#345::entry0|||rstudio-0.js#-1::eval|||com/google/gwt/cell/client/AbstractEditableCell.java#41::viewDataMap|||Client-ID: 33e600bb-c1b1-46bf-b562-ab5cba070b0e|||User-Agent: Mozilla/5.0 (Macintosh  Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.1 Chrome/69.0.3497.128 Safari/537.36

(Also attached the log since ^^ is likely going to be unreadable here)

[rsession-hrbrmstr.log](https://github.com/rstudio/rstudio/files/3286160/rsession-hrbrmstr.log)

**Comment by hrbrmstr** [comment]
It was not as unreadable as I thought it'd be!

**Comment by kevinushey** [comment]
```
ERROR system error 2 (No such file or directory) [path=/Users/hrbrmstr/packages/ethercalc]
```

Is there anything (beyond something odd in macOS Catalina) that could explain why the directory was momentarily unaccessible?

**Comment by hrbrmstr** [comment]
nope. nothing at all on the system and this doesn't happen on my non-Catalina systems. 

Apple has re-jiggered the whole concept of "main volume" for the drive now and I wonder if there's something happening in user space as a result. I'll be loading the second beta in a bit.

(now i need to see if two other bugs I'm experiencing in Dailies on Catalina are already created)

**Comment by kevinushey** [comment]
I'm seeing this on the Catalina beta as well, now.

**Comment by kevinushey** [comment]
Seeing a similar "your project vanished" error in the diagnostic logs:

> 26 Jun 2019 18:28:32 [rsession-kevin] ERROR system error 2 (No such file or directory) [path=/Users/kevin/r/pkg/packrat]; OCCURRED AT: void rstudio::core::system::file_monitor::(anonymous namespace)::fileEventCallback(ConstFSEventStreamRef, void *, size_t, void *, const FSEventStreamEventFlags *, const FSEventStreamEventId *) /Users/admin/workspace/IDE/macos-v1.3/src/cpp/core/system/file_monitor/MacFileMonitor.cpp:82; LOGGED FROM: void rstudio::session::projects::ProjectContext::fileMonitorTermination(const rstudio::core::Error &) /Users/admin/workspace/IDE/macos-v1.3/src/cpp/session/projects/SessionProjectContext.cpp:482

**Comment by jmcphers** [comment]
I debugged this a little a few days ago when I noticed file monitoring seemed busted on Catalina. It looks like we get this event right away almost all the time:

https://github.com/rstudio/rstudio/blob/eb12ec98bb75fe72d2099823fa8202d01be8680c/src/cpp/core/system/file_monitor/MacFileMonitor.cpp#L75-L83

**Comment by jmcphers** [comment]
This is a patch release candidate.

**Comment by ronblum** [comment]
@hrbrmstr and @kevinushey If you're on the most recent Catalina beta, are you still seeing the issue? I can't reproduce it, but it's quite possible that I'm not following the steps correctly.

**Comment by hrbrmstr** [comment]
Thx for the ping. I was going to note that yesterday but I got distracted by the completely white screen on the new dailies. 

Works great now and I've been doing quite a bit of building and knitting. 

#ty!

**Comment by ronblum** [comment]
Shoot. I just updated to 1.2.1565 and I'm getting the error. It's fine with 1.2.1558.

```
Warning message:
File monitoring failed for project at "/System/Volumes/Data/Users/ronblum/RStudio/Projects/Testing/ethercalc"
Error 2 (No such file or directory)
Features disabled: R source file indexing, Diagnostics
```

**Comment by hrbrmstr** [comment]
1.3.323 here.

**Comment by hrbrmstr** [comment]
ARGH. 1.3.333, latest macOS Vista beta. Just got this again when opening a new project from an existing project in the same RStudio window. It does not do that when opening in another (new) window.

**Comment by ronblum** [comment]
This problem is still occurring. For 1.2, it worked in MacOS Desktop 1.2.1558, but it's a problem in 1.2.1564

**Comment by ronblum** [comment]
Confirmed the in RStudio Desktop 1.2.1577 on MacOS 10.15 (Catalina).

Note that in previous builds I was able to reproduce the issue by just switching between projects. The problem no longer appears when doing so—and I tried multiple times—so this is good.
