### ISSUE TITLE
execute the SQL code line by line on Rstudio IDE

### ISSUE THREAD

**Issue by TonyFly3000** [rstudio/rstudio#4761]
Current Rstudio IDE can only execute one command at a time .

I think its will be great if we can execute the SQL code line by line on Rstudio IDE

reference to : https://github.com/rstudio/rstudio/issues/3860

**Comment by ronblum** [comment]
@TonyFly3000 Thank you for filing the new enhancement, triggered by the other issue!

**Comment by genghiskhanofnz** [comment]
Any update on this since I want to test and use it.

**Comment by ronblum** [comment]
@genghiskhanofnz We don't currently have an update on this enhancement request. We regularly review all issues—especially bugs and enhancements—as we continue to develop new versions of RStudio. This enhancement isn't currently slated for an upcoming release, but we're keeping it open so that we can continue to review and consider it.

One thing that is useful is to give the issue a 👍on the initial description. This gives us an indication of how popular the request is, which helps us in prioritizing enhancements and fixes.

**Comment by sanjaysahu1729** [comment]
@TonyFly3000  Thank you for filing the new enhancement. 
@ronblum  Thank you for providing an update regarding the enhancement. I'm really looking forward to seeing this enhancement in the upcoming R-studio version. 
One of the reasons why this request is not so popular is because of the use of R-studio for SQL development.
I'm a Master's Student of Data Science and I understand the usage of this feature. 

I'm really not sure whether this project is open-source or not, but if there is an opportunity to implement this enhancement, I would like to contribute some of my time.

**Comment by genghiskhanofnz** [comment]
@sanjaysahu1729 Thanks for your offer to make it happen.
