### ISSUE TITLE
R Markdown and Shiny apps fail with UNC-formatted paths

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#4807]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1335
    OS Version      : Windows 10
    R Version       : 3.6.0

### Steps to reproduce the problem

1. Set the working directory to a path in UNC format.
2. Create a Shiny app or R Markdown file—the defaults work well.
3. Save the file in a directory using UNC format.
4. Knit the R Markdown file or run the Shiny app.

### Describe the problem in detail

The process will fail.

Shiny:
```
> runApp('')
Error in shinyAppDir(x) : No Shiny application exists at the path ""
```

R Markdown:
```
<snip>
pandoc.exe: unc.utf8.md: openBinaryFile: does not exist (No such file or directory)
Error: pandoc document conversion failed with error 1
Execution halted
```

This may be a problem with other file/process types, but these were the ones I tried.

### Describe the behavior you expected

Shiny apps should run and R Markdown files should be knittable. Workaround: map a drive to the network drive and use it instead.

There are several known issues with UNC paths, such as #3105 and #4137. However, those were preexisting issues. This one is a regression—it works in 1.1.463.

**Comment by rubayat38** [comment]
Anyone tried to resolve this issue?

**Comment by adam-sampson** [comment]
This problem is related to: [https://github.com/rstudio/rmarkdown/issues/701](https://github.com/rstudio/rmarkdown/issues/701)

A dirty workaround is to render to your hard drive and then copy the output from your hard drive to your network drive. You can do this with code by running the following in your console or creating another file RenderMarkdown.R to source.

You MUST create the folder on your hard drive BEFORE you run this code snippet. It doesn't create the folder for you. Feel free to add that to your code if you want. Also note that many organizations that use UNC or NSF also put your Documents and Downloads folder on the network drive...so don't use those as your Intermediates folder.

`# Syntax:
# rmarkdown::render(
#   "//path/to/file/my_markdown.Rmd",
#   intermediates_dir = "C:\\temp\\rmd_knit"
# )`
