### ISSUE TITLE
Keyboard shortcuts to cycle terminals

### ISSUE THREAD

**Issue by kendonB** [rstudio/rstudio#4892]
Next terminal and previous terminal would be welcome shortcut options. Thanks!

**Comment by ronblum** [comment]
@kendonB These should work out of the box: <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>F11</kbd> for "previous terminal" and <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>F12</kbd> for "next terminal." Do these do what you're looking for?

**Comment by kendonB** [comment]
These seem to be mapped to system functions. Doing Ctrl+Alt+F11 I see a bit of a flicker of the screen and Ctrl+Alt+F12 brings up the Intel HD graphics control panel.

**Comment by kendonB** [comment]
Remapping seems to Alt-Shift-F11/12 works though. Mine is quite a common computer (Dell XPS 15 9550) so you might want to consider changing the defaults to Alt-Shift-F11/12.

**Comment by ronblum** [comment]
@kendonB Can you confirm that you're using Windows—and 7 or 10? And I see that at least Ctrl+Alt+F12 has the system mapping you're seeing (https://www.howto-connect.com/enable-disable-create-custom-hot-keys-intel-graphics/). So I'm going to reopen to suggest that we change the mappings.

**Comment by ronblum** [comment]
Summary of the above: "Previous terminal" and "next terminal" use <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>F11</kbd> and <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>F12</kbd>. The shortcut with F12 is used on Windows to open the Intel graphics control panel. I can't find anything on Windows for the shortcut with F11, but it doesn't appear to work.

Recommendation: change the mapping to something else. @kendonB found that remapping to <kbd>Shift</kbd>+<kbd>Alt</kbd>+<kbd>F11</kbd> and <kbd>Shift</kbd>+<kbd>Alt</kbd>+<kbd>F12</kbd>, so those are good candidates.

**Comment by kendonB** [comment]
I also chose those as the Shift Alt part is mapped (in the brain) to the Rstudio terminal.

**Comment by gtritchie** [comment]
It is quite tricky to find usable (and available) keyboard shortcuts that will work for everybody.

On my PC with RStudio Desktop 1.3, the current <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>F11</kbd> and <kdb>Ctrl</kdb>+<kbd>Alt</kbd>+<kbd>F12</kbd> work fine for the terminal, so aren't taken by Windows itself.

On Mac, I'm seeing a new issue (not sure if it's new to 1.3, or shipped with 1.2); when I use current shortcuts to switch terminals, it does switch, but also inserts text into the terminal. <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>F11</kbd> inserts `3;7~` and <kdb>Ctrl</kdb>+<kbd>Alt</kbd>+<kbd>F12</kbd> inserts `4;7~`.

The proposed change to use <kbd>Shift</kbd> instead of <kbd>Ctrl</kbd> is not currently used by any RStudio mappings, so reasonable to change to those given there are known third-party conflicts. That said, almost guaranteed this will cause issues for people who don't currently have a problem (i.e. with some other installed software).

**Comment by ronblum** [comment]
@gtritchie I'm seeing the `3;7~`/`4;7~` issue in RStudio Desktop 1.2.1539 on MacOS 10.14.6. On RStudio Server using Chrome from MacOS, I'm getting `;7~`. I'll open a separate issue for this.
