### ISSUE TITLE
Allow different themes in different instances

### ISSUE THREAD

**Issue by nathancday** [rstudio/rstudio#4905]
First, thanks to all who work building RStudio, is it a *fantastic* data IDE.

Often I will have two instances of RStudio open to dance between projects/tasks. When this happens with terminals, I switch the color theme to help me visually differentiate them. When I try to do the same thing with RStudio's the new theme is propagated to all open instances. 

![rstudio_themes](https://user-images.githubusercontent.com/808225/59031562-024f3b00-8832-11e9-8033-c80127d8ed77.gif)

Right now theme is in `Global Options` so it make sense it would behave like this. But I think it would be nice to have theme-selection as a project/instance option.

Again thanks for building a great tool and I am happy to help out.

**Comment by ronblum** [comment]
@nathancday Thank you for the suggestion—we'll review it as we continue developing RStudio. And thank you for the compliments, and for helping us improve the product!

**Comment by jmcphers** [comment]
This was a popular request (and is now a popular feature) in VSCode.

See this addin:

https://marketplace.visualstudio.com/items?itemName=stuart.unique-window-colors

Also:

> When opening different versions of a directory in two different VSCode instances it is easy to lose track of where you are since VSCode appearances are identical.

https://github.com/Microsoft/vscode/issues/12579

**Comment by iago-pssjd** [comment]
I even would go farther (maybe should I open another issue?) 

It would be great if different tabs (for example console and terminal) in a unique instance could have different appearances applied. 
Even this could be weird, depending on the multiple appearances chosen to look simultaneously, it also can help to improve global appearance, since themes apply different depending on the coding.

For example, currently with the default theme, my source and console tabs appear nice as follows:
![scpanels](https://user-images.githubusercontent.com/40892925/71165304-ed2b7e00-2250-11ea-8bcc-ad95c1584eea.png)

Meanwhile, the same code opened with vim in the terminal has a not so good style:
![vtpanel](https://user-images.githubusercontent.com/40892925/71166173-6ecfdb80-2252-11ea-9617-ccb8bc59065a.png)

Beyond changing the theme, I don't know if there are other solutions, like changing the vim style for R in RStudio or other?

Thank you!

**Comment by markbneal** [comment]
Who hasn't had multiple R instances open on their computer and started typing in the wrong one?
If they opened with a different colour border (from a predetermined palette, or custom palette, or user specified?) wouldn't that be useful?

**Comment by nathancday** [comment]
I still think this is cool and would bring RStudio in-line with other IDE like VS-Code

**Comment by turalsadigov** [comment]
Is there an update on this issue? I would like to know if there is a project-level control on RStudio theme? Thank you.

**Comment by talegari** [comment]
The request is tracked here: https://github.com/rstudio/rstudio/issues/2350
