### ISSUE TITLE
Window Defender's ransomeware protection blocking r to write to csv files.

### ISSUE THREAD

**Issue by pravincesingh** [rstudio/rstudio#5030]
### System details

    RStudio Edition : 
    RStudio Version : 1.2.1335
    OS Version      : windows 10 pro 1903
    R Version       : 3.6.0

### Steps to reproduce the problem
Write to file using write.csv()
### Describe the problem in detail
Whenever i use write.csv() is shows error
`Error in file(file, ifelse(append, "a", "w")) : 
  cannot open the connection
In addition: Warning message:
In file(file, ifelse(append, "a", "w")) :
  cannot open file 'SampleData.csv': No such file or directory`
Once I disabled the ransomeware .It is working file.
### Describe the behavior you expected
I was expecting a csv file in the respective folders . But I go error

**Comment by ronblum** [comment]
@pravincesingh Thank you for raising this issue. What happens when you try to write to a file in standalone R?

The issue is likely with Windows Defender, requiring adding R and/or RStudio to its exclusions list. Here are some discussions in [the RStudio Community](https://community.rstudio.com/) about the impact of antivirus software, including Window Defender, that affect R and RStudio:
- https://community.rstudio.com/t/access-denied-for-all-r-and-rstudio-activities-but-not-other-apps-in-previously-used-folders/11661/5
- https://community.rstudio.com/t/performance-issue-rstudio-windows-10/7608/2
- https://community.rstudio.com/t/rstudio-suddenly-slow-processing/4959/15

**Comment by jmcphers** [comment]
@pravincesingh Closing since we haven't heard back from you. Feel free to reopen if you still have trouble after following @ronblum's advice.

**Comment by sahidyk** [comment]
Why can it happen that R and Rstudio are blocked by Windows Defender?
