### ISSUE TITLE
Rmd Child documents don't change current environment when run from "Run all Chunks Above".  PROBLEM STILL EXISTS

### ISSUE THREAD

**Issue by mepseudo** [rstudio/rstudio#5043]
### System details

    RStudio Edition :  Desktop
    RStudio Version : 1.2.1335
    OS Version      :  Windows 10
    R Version       :  3.5.3

### Steps to reproduce the problem
Unzip two attached demo RMD files into same directory

KNIT "ChildTest_Master.Rmd" to HTML, it will work correctly so you will know that Rmd code works properly.  

Open "ChildTest_Master.Rmd" in RStudio, Position the cursor anywhere inside the 3rd Chunk (named "3rdChunk_Just_A_Place_holder").

From the top menu, "Run All Chunks Above"

You should see this error: 
Error: object 'I_was_defined_in_Child' not found

And this error only occurs when you run the child chunk interacctively from RStudio and not when you Knit to HTML everything at once.

### Describe the problem in detail
I have a master Rmd and a child Rmd.
The master Rmd calls the child Rmd.
The child Rmd defines one variable to have some value
After the master calls the child the variable defined in the child Rmd SHOULD be available in the master Rmd and that works CORRECTLY when you Knit the whole master RMD at once BUT it works incorrectly when you interactively run parts of the master using the ""Run Chunk above this one" button.

### Describe the behavior you expected
A variable that is defined in a child chunk Rmd SHOULD be defined in scope of calling Rmd and it is in scope when the master Rmd is run direction from "Knit to HTML" but it is not in scope when the master Rmd is run chunk-at-a-time using the menu items... and that seems definition-ally wrong?

Here is the output from sessioninfo()
> sessionInfo()
R version 3.5.3 (2019-03-11)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] compiler_3.5.3  htmltools_0.3.6 tools_3.5.3     yaml_2.2.0      Rcpp_1.0.1      rmarkdown_1.13  knitr_1.22      xfun_0.5        digest_0.6.18   evaluate_0.13  
> 

[Child_Test_Rstudio.zip](https://github.com/rstudio/rstudio/files/3347135/Child_Test_Rstudio.zip)

**Comment by mepseudo** [comment]
To be more clear, it is this line:

# Include a Child

```{r 1stChunk_test_child, child = 'ChildTest_Child.Rmd'}===
```
THAT loads the child Rmd from the master Rmd and it is in that Child Rmd where the one line:

I_was_defined_in_Child<-"Value of a Variable defined in a Child"
exists and that variable is not visible in the master after interactive execution of the child using the "run all above chunks" menu item.

**Comment by mpaolo** [comment]
Hi,

was going to file same issue - I think it's the same: I put a number of stuff in a preamble.Rmd as a child chunk but it's simply ignored. Knitting though works as expected. 

But the problem is not just with 'run-all-above/below', same for the 'run' button of the chunk: muted, as if the chunk were void (well, it is, except for the 'child=...' option).

Perhaps connected, I'm seeing same problem with chunks reused via 'ref.label=...' option: do nothing in interactive mode, either by run-code-region or with chunk's run-button. In all cases, according to the descriptions of the options, I'd expect the code referred to to run as if it's typed into the calling chunk. Knitting usually works anyway (except for some ref.label cases that I set aside for later digging and reporting in case, as soon as I have time).

Using:
`RStudio Version 1.2.1335 Build 4 (f1ac3452)`
`Mozilla/5.0 (Windows NT 10.0; rv:70.0) Gecko/20100101 Firefox/70.0`

thx
