### ISSUE TITLE
Breakpoints auto-disabled when file is sourced

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#5112]
Have this problem when I source an `.R` file from a package project.
![cannot_set_brakpoint](https://user-images.githubusercontent.com/11860098/61329920-1ae64400-a827-11e9-9d2c-e593b0c2ed99.gif)

The console says this:
```
Warning message:
In body(fun) : argument is not a function
```

Breakpoints are set right inside the body of the function. Can attach file if it helps.

**Setup:** RStudio 1.2.1555, R 3.6.1, running on debian buster.

**Comment by ronblum** [comment]
@david-cortes Thank you as always for reporting the issue! I'm mark this as a bug as is, since the screenshot shows the behavior you're describing, for us to review as we continue RStudio development.

**Comment by jmcphers** [comment]
Can you attach the file? There are some R constructs that make it hard for the debugger to figure out where to set the breakpoint.

**Comment by david-cortes** [comment]
I don't have the file anymore unfortunately.

**Comment by kevinushey** [comment]
Feel free to re-open when you can provide a reproducible example.

**Comment by aornugent** [comment]
I solved this problem with bisection and brute force. After repeatedly deleting sections of code, setting breakpoints and reloading the package, I discovered that the issue was caused by a single function.

Deleting this function fixed the problem. Replacing the function broke things again. Renaming this function fixed the problem. Changing it back broke things again. 

Eventually I renamed the function, generated new documentation, changed it back and re-generated the old docs and that seems to have stuck. I can now set breakpoints and no longer receive the `Warning message: In body(fun) : argument is not a function` message when I reload my package.

I'm not in a position to share my code so I understand that above isn't especially helpful.

**Comment by aornugent** [comment]
I stand corrected:

> changed it back and re-generated the old docs and that seems to have stuck.

Turns out I had a typo when I tried to change it back to the old function name. So it appears that I cannot use my old function names for whatever reason. Unsatisfying as that is, I'm going to give them new names and carry on.
