### ISSUE TITLE
Allowing sessions on multiple servers through one proxy gateway

### ISSUE THREAD

**Issue by drlemmus** [rstudio/rstudio#5123]
In our setup (a research institute) we have several hosts (blabla1.domain.tld, blabla2.domain.tld, ...) running Rstudio server which are only reachable by reverse proxy through one gateway (intranet.domain.tld). One of our users reported the following problem:
If I log in to a session on blabla1 through the gateway and then log in to a session on blabla2 through the same gateway, my session on blabla1 logs out.

This seems a consequence of the way session cookies are made. They do not seem to be aware of the actual host on which the session is running, only the URL from which it is reached. So if we use a different (temporary) gateway to connect each session, both sessions stay logged in. 

Is this a solvable issue, or should I tell our user to just use two different browsers as a workaround?

**Comment by jmcphers** [comment]
There isn't an easy way to do this with the open source version of RStudio; the professional version supports multiple sessions natively and works behind a load balancer (or can load balance itself).

I'm not 100% clear on what you want to do, but I think you might be able to make it work by using your reverse proxy to rewrite the cookie headers on their way in and out of RStudio Server so that the servers see cookies "scoped" to their own host. If you want help doing this, the R Admins forum on our community site is best:

https://community.rstudio.com/c/r-admin
