### ISSUE TITLE
Hierarchy of heading in the outline

### ISSUE THREAD

**Issue by atusy** [rstudio/rstudio#5128]
# System details

    RStudio Edition : Server
    RStudio Version : 1.2.1335
    OS Version      : Manjaro Linux (not versioned due to rolling release)
    R Version       : 3.6.1

#### Show sections and all chunks for Rmd by global options

``` yaml
Tools:
  Global options:
    R Markdown:
      Show in document outline: Sections and All Chunks
```

#### Write functions in chunks in Rmd

````
```{r chunk}
f1 <- function() {}
f2 <- function() {}
f3 <- function() {}
f4 <- function() {}
f5 <- function() {}
```

```{r chunk2}
g1 <- function() {}
g2 <- function() {}
```

## H2
````

### Describe the problem in detail

Outline shows as if

- function within a chunk belong to the former ones in the chunk.
- A chunk belong to the last function in the previous chunk
- Headings belong to the the last function in the preivous chunk

![image](https://user-images.githubusercontent.com/30277794/61572312-79851980-aad6-11e9-8abf-378cb68a52e6.png)

### Describe the behavior you expected

In the above example, outline should be like

- *chunk*
  - f1
  - f2
  - f3
  - f4
  - f5
- *chunk2*
  - g1
  - g2
- H2

**Comment by ronblum** [comment]
@atusy Thank you for raising this. I tried reproducing this with both RStudio Server on Ubuntu 18.04 and RStudio Desktop 1.2.1335 and 1.2.1558 on MacOS 10.15 (Catalina), but I get the results you expected.

Can you please provide
1) The full code of a .Rmd file, so that I can reproduce exactly what you're doing; and
2) A screenshot of the Rmarkdown options at Tools -> Global Options -> R Markdown? Here's mine.
<img width="606" alt="rmarkdown_options" src="https://user-images.githubusercontent.com/31009952/61649365-56e23480-ac7f-11e9-8512-1b439a2a7784.png">
I want to make sure we're doing the same thing. Thanks!

**Comment by atusy** [comment]
Thanks for trying to reproduce this issue.
Here's what you request.

Note: I'm running my RStudio Server on Docker (`rocker/verse`).

## The full code of a .Rmd file

````
---
output: html_document
---

```{r chunk}
f1 <- function() {}
f2 <- function() {}
f3 <- function() {}
f4 <- function() {}
f5 <- function() {}
```

```{r chunk2}
g1 <- function() {}
g2 <- function() {}
```

## H2
````

## A screenshot of the Rmarkdown options

![image](https://user-images.githubusercontent.com/30277794/61677275-f3690d00-ad39-11e9-98e5-9c7ef0046950.png)

**Comment by kevinushey** [comment]
What browser are you using?

**Comment by atusy** [comment]
Chromium 75.0.3770.100-1

**Comment by jmcphers** [comment]
I can't reproduce this in RStudio Desktop with Chromium 69 or RStudio Server with Chrome 78. I suspect it's a transient issue with Chrome 75? @atusy please feel free to reopen or let us know if you're seeing this with a more recent RStudio (1.2.5019 or newer) and Chrome (78 or newer).

![image](https://user-images.githubusercontent.com/470418/69199214-31a9e980-0aec-11ea-8998-a290c11f534d.png)
