### ISSUE TITLE
Copy + Paste not working over X11 forwarding

### ISSUE THREAD

**Issue by kstrickler** [rstudio/rstudio#5267]
### System details

    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       :

**Comment by ronblum** [comment]
@kstrickler Thank you for raising this. Can you please provide more information so that we can try to reproduce this?

1) The environment you're working in:
```
RStudio Edition : <!-- Desktop or Server -->
RStudio Version : 
OS Version      : 
R Version       : 
```

2) What method are you using to cut and paste? Mouse and right click, CTRL-Shift-C and CTRL-Shift-V, or something else?
3) Does this happen when copying within RStudio, or from another application into RStudio or vice versa?
4) What happens when you try to copy and paste?

Thanks!

**Comment by kstrickler** [comment]
The issue was with outdated software we were using, thanks so much for the quick reply.

**Comment by ronblum** [comment]
My pleasure! I'm glad it's all worked out.
