### ISSUE TITLE
"Extract function" generates redundant warning popup and consolue error

### ISSUE THREAD

**Issue by BartJanvanRossum** [rstudio/rstudio#5285]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1568
    OS Version      : Windows 10
    R Version       : 3.6.1

### Steps to reproduce the problem

In an Rscript type `mtcars[, 1]`.
Select this code and call "Extract function".

### Describe the problem in detail

A popup appears:
![image](https://user-images.githubusercontent.com/28725410/63578138-23513d80-c590-11e9-9fcb-56a045e58415.png)

Clicking yes, a function is still created correctly but an error appears in the console window:
```r
Error in codetools:::walkCode(ee, w) : 
  argument "ee" is missing, with no default
```
The function created is incorrect as well, in the sense that it misses mtcars as an input argument:
```r
test <- function() {
        mtcars[, 1]
      }
```

The warning/error appears whenever there is an empty field within the brackets. So, `mtcars[1, ]` produces the warning, whereas `mtcars[1, 1]` is fine.

### Describe the behavior you expected

No warning and error message.

**Comment by ronblum** [comment]
@BartJanvanRossum Thank you for raising the issue. To summarize, there are three things:

1) The extraction results in both the popup and the console error. Only the popup should appear.
2) The resulting function is missing the input.
3) The error and popup appear in response to a legitimate empty field.

- Tagging this as a bug at least due to (1).
- Regarding (2) and (3): @kevinushey is this an issue with RStudio or `codetools`?

**Comment by jaccoheres** [comment]
This seems to be a quite old bug:
https://support.rstudio.com/hc/en-us/community/posts/200633038-Extract-function-fails

**Comment by JensHumrich** [comment]
This error is still existing in 2020. To reproduce, try to parse this as a function:

df <- df[df$field >= 0, ]

@BartJanvanRossum @ronblum
