### ISSUE TITLE
Preview 1.2.1572 breaks on MacOS if R installed via Homebrew

### ISSUE THREAD

**Issue by rundel** [rstudio/rstudio#5286]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio v1.2.1572-1 Preview
    OS Version      : macOS 10.14.6
    R Version       : 3.6.1

### Steps to reproduce the problem

Upgraded from an earlier preview version to v1.2.1572-1 via the usual download link. R is installed via Homebrew rather than MacOS binaries from CRAN.

### Describe the problem in detail

When loading RStudio the application opens but fails to load completely and all I get is the following error message:

```
This site can’t be reached

127.0.0.1 refused to connect.

Try:
Checking the connection
Checking the proxy and the firewall

ERR_CONNECTION_REFUSED
```

If I run a diagnostic I get the following:
```
[~]$ ~/Downloads/RStudio-Preview.app/Contents/MacOS/RStudio --run-diagnostics

Using R script: /usr/local/Cellar/r/3.6.1/bin/R

Attempting to launch R session...
  R_HOME=/usr/local/Cellar/r/3.6.1/lib/R
  R_DOC_DIR=/usr/local/Cellar/r/3.6.1/lib/R/doc
  R_INCLUDE_DIR=/usr/local/Cellar/r/3.6.1/lib/R/include
  R_SHARE_DIR=/usr/local/Cellar/r/3.6.1/lib/R/share
  PATH=/Users/rundel/.cargo/bin:/usr/local/bin:/usr/local/sbin:/Users/rundel/local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin:/Library/TeX/texbin
  HOME=/Users/rundel

R session launched, attempting to connect on port 32886...
dyld: Library not loaded: /Library/Frameworks/R.framework/Versions/Current/Resources/lib/libR.dylib
  Referenced from: /Users/rundel/Downloads/RStudio-Preview.app/Contents/MacOS/rsession
  Reason: image not found

Connected to R session, attempting to initialize...
```

If I check the linked libraries from the stable release (which works on this system):
```
[~]$ otool -L /Applications/RStudio.app/Contents/MacOS/rsession
/Applications/RStudio.app/Contents/MacOS/rsession:
...
	@executable_path/libR.dylib (compatibility version 3.0.0, current version 3.0.3)
...
```

versus the preview 

```
[~]$ otool -L ~/Downloads/RStudio-Preview.app/Contents/MacOS/rsession
/Users/rundel/Downloads/RStudio-Preview.app/Contents/MacOS/rsession:
...
	/Library/Frameworks/R.framework/Versions/Current/Resources/lib/libR.dylib (compatibility version 3.0.0, current version 3.0.3)
...
```

### Describe the behavior you expected

It seems like it should be possible to switch back to linking `rsession`, etc to `@executable_path/libR.dylib` instead of `/Library/Frameworks/R.framework/Versions/Current/Resources/lib/libR.dylib` to correct this issue for those of us who are using Homebrew.

**Comment by ronblum** [comment]
@rundel Thank you for raising this. If I understand correctly, an earlier preview version was working correctly? If so, do you recall which build it was?

**Comment by kevinushey** [comment]
> It seems like it should be possible to switch back to linking rsession, etc to @executable_path/libR.dylib instead of /Library/Frameworks/R.framework/Versions/Current/Resources/lib/libR.dylib to correct this issue for those of us who are using Homebrew.

Unfortunately this is no longer possible due to Apple's requirements for application notarization (the [hardened runtime](https://developer.apple.com/documentation/security/hardened_runtime_entitlements) seems to prohibit us from lazy-loading `libR.dylib` as we have done in the past)

We did discover one potential solution using, IIRC, `DYLD_INSERT_LIBRARIES` but that will take some time + testing to implement.

@jmcphers do you think we need to find a solution to this for v1.2-patch?

**Comment by jmcphers** [comment]
Unfortunately, yes. The 1.2-patch release needs to be notarized in order to work correctly on Catalina, and we have backported all of the notarization code to it (so it is currently notarized). This is why the preview release is suddenly not working with Homebrew.

@rundel Does softlinking your libR.dylib to the `Current/Resources` path patch things up for you?

I am closing this since we're already tracking this in https://github.com/rstudio/rstudio/issues/5238, and have promoted that issue to 1.2-patch for consideration.
