### ISSUE TITLE
Build single document gitbook doesn't display correct HTML file in Viewer pane

### ISSUE THREAD

**Issue by vinhtantran** [rstudio/rstudio#5371]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.335, 1.2.1578, 1.3.424
    OS Version      : Windows 10 x64 (build 18362)
    R Version       : 3.6.1 (2019-07-05)

### Steps to reproduce the problem
1. Install bookdown package from CRAN
2. Create a new "Book Project using bookdown", give the project a name (say, projectname)
3. Edit _output.yml to add two more rows in bookdown::gitbook (split_by: none, self_contained: true)
4. Use the Build Book dropdown in the Build pane to compile the book as bookdown::gitbook

### Describe the problem in detail
In the pop-up (and also embedded) Viewer pane, although the window header shows a correct link to the output HTML file (projectname.html) and the name before Open in Browser shows correct HTML file, the content of the view shows "pathname/_book/index.html not found" with pathname is the actual local path to my project folder. Clicking Open in Browser shows the correct HTML file in my browser though.

### Describe the behavior you expected
The content of my "single document" HTML (pathname/_book/projectname.html) should be shown in the Viewer pane (both embedded and pop-up versions).

**Comment by kevinushey** [comment]
Internal note: I suspect the change needs to be made around here:

https://github.com/rstudio/rstudio/blob/767b78dcd5cf87ecd56c5dfbbec54a6fe8e1dda5/src/cpp/session/modules/rmarkdown/SessionRMarkdown.cpp#L272-L290

We could do something like the following:

1. If `index.html` exists, use that file;
2. Otherwise, if there is only one `.html` file within the folder, use that instead.

**Comment by rich-rstudio** [comment]
verified in Version 1.3.921
