### ISSUE TITLE
Slow keyboard

### ISSUE THREAD

**Issue by paull71** [rstudio/rstudio#5380]
Hi,

I am experiencing a very slow on-screen keyboard on RStudio 1.2.1577. The same issue does **not** present itself when a real keyboard in plugged in via USB just when the on-screen one is used. 

Tried some alternatives/fixes - 
1. the preview did not improve the speed;
2. The dailies improved the speed a little but still a bit slow
3. reinstalling 1.2.1577
None of which proved to be the long term solution.

The machine is operating WIN10 on a Thinkpad 10.

P

**Comment by ronblum** [comment]
@paull71 Thank you for raising the issue. I am unable to reproduce the issue, also using Windows 10 on a Thinkpad. A few questions:
1) What language are you using? I don't want to automatically assume English.
2) There have been some issues reported due to the rendering engine. Can you try changing it using the suggestions at https://support.rstudio.com/hc/en-us/articles/360017886674-Troubleshooting-RStudio-Rendering-Errors?
3) I apologize my ignorance, but how do I identify the versions of Thinkpad as above (Thinkpad 10)?

**Comment by paull71** [comment]
Thanks Ron for your prompt response.

In response to your questions:
1. English
2. Tried all of the suggestions. Results:
a. they slowed down the system even more ( in some cases slightly)
b. also tried a clean boot - but that did not help; also reduced screen resolution to 1440x 900- but the slowness persisted
c. visual studio improved the speed (to normality) but is not preferred IDE :-) 
3. https://pcsupport.lenovo.com/au/en/products/tablets/thinkpad-tablet-series/thinkpad-10/20c3 is the version that I am using.

Sorry for the slow response.

**Comment by jmcphers** [comment]
We do not have a tablet like that in-house so it is not likely we can make progress on this without some way to reproduce the issue on our end. Are you still seeing it with 1.2.5019? Can you tell us more about the on-screen keyboard software? Is it Lenovo specific or is this the Windows default OSK?

**Comment by paull71** [comment]
Just tried 1.2.5019 and yes the lag is still present with the normal
windows OSK (C:\WINDOWS\system32\OSK.exe)

I have turned off pretty much everything that may consume resources:
* no auto correct
* no text suggestions
so pretty vanilla.

Thanks for trying. Looks like I'll need use with a physical keyboard.
