### ISSUE TITLE
Issues with nouveau driver on Centos7

### ISSUE THREAD

**Issue by CdeMills** [rstudio/rstudio#5511]
### System details

    RStudio Edition :  Desktop
    RStudio Version : rstudio-1.2.5001-x86_64.rpm
    OS Version      :  CentOS Linux release 7.6.1810 (Core)
    R Version       :  R version 3.6.0 (2019-04-26) -- "Planting of a Tree"
    platform Version :  x86_64-redhat-linux-gnu (64-bit) with nouveau

### Steps to reproduce the problem
launch rstudio
### Describe the problem in detail
from the strace capture:
ioctl(12, DRM_IOCTL_NOUVEAU_GEM_PUSHBUF, 0x7ffd8c41e0a0) = -1 ENOENT (No such file or directory)
nouveau: kernel rejected pushbuf: Aucun fichier ou dossier de ce type
nouveau: ch3: krec 0 pushes 1 bufs 4 relocs 0
nouveau: ch3: buf 00000000 00000002 00000004 00000004 00000000
nouveau: ch3: buf 00000001 00000006 00000004 00000000 00000004
nouveau: kernel rejected pushbuf: Aucun fichier ou dossier de ce type
[ Aucun fichier ... = no such file or directory]
[...]
*** Error in `rstudio': double free or corruption (fasttop): 0x00005644cdc42850 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x81609)[0x7fe9320a1609]
/usr/lib64/libdrm_nouveau.so.2(nouveau_bo_ref+0xd5)[0x7fe917b95065]
/usr/lib64/libdrm_nouveau.so.2(+0x40c4)[0x7fe917b960c4]
/usr/lib64/libdrm_nouveau.so.2(nouveau_pushbuf_kick+0x10)[0x7fe917b96bb0]
/usr/lib64/dri/nouveau_dri.so(+0x627b76)[0x7fe9183c1b76]
/usr/lib64/dri/nouveau_dri.so(+0x253754)[0x7fe917fed754]

### Describe the behavior you expected
being able to launch rstudio

**Comment by pascaloettli** [comment]
See #3781

**Comment by pascaloettli** [comment]
Please have a look at #3781

**Comment by ronblum** [comment]
@CdeMills Thank you for raising the issue, and @pascaloettli for directing to the known issue. I'm going to mark this as a duplicate, as the issue is with the driver. There's a suggested workaround at https://github.com/rstudio/rstudio/issues/3781#issuecomment-510945125 , as well as a link to a known issue.

**Comment by CdeMills** [comment]
Le lun. 7 oct. 2019 à 16:38, Ron Blum <notifications@github.com> a écrit :

> @CdeMills <https://github.com/CdeMills> Thank you for raising the issue,
> and @pascaloettli <https://github.com/pascaloettli> for directing to the
> known issue. I'm going to mark this as a duplicate, as the issue is with
> the driver. There's a suggested workaround at #3781 (comment)
> <https://github.com/rstudio/rstudio/issues/3781#issuecomment-510945125> ,
> as well as a link to a known issue.
>
>
> Hello Ron,

I confirm the workaround avoids the crash. Now, on bug report #3781,
everything seems closed ?

OTOH ... there are a lot of  graphical software which don't crash on CentOS
7. Shouldn't we talk of an interaction between Rstudio and the Nouveau
driver ?

Regards

Pascal

**Comment by ronblum** [comment]
Pascal—#3781 is closed because the problem isn't in RStudio—it's a known issue with the nouveau/Qt WebEngine: https://bugreports.qt.io/browse/QTBUG-41242 But we keep the issue available so that if others run into the same problem, the information/workarounds/solutions/etc. can be found.

Also, it's possible that switching to software rendering will take care of this, too. See https://support.rstudio.com/hc/en-us/articles/360017886674-Troubleshooting-RStudio-Rendering-Errors
