### ISSUE TITLE
File path helper support for `file.path()` and friends

### ISSUE THREAD

**Issue by malcolmbarrett** [rstudio/rstudio#5586]
The RStudio IDE has a few convenient helpers for file paths. Tab completion of paths and opening files with Cmd/ctrl+ clicking are two examples. But it's often a good idea to use functions like `file.path()` and `here::here()` to write paths safely. These helpers are less convenient in this setting because the paths are often broken up into elements of a character vector.

Is it feasible to have RStudio extend its path helpers to work in the right context for these types of functions? For instance, an auto-complete for `file.path()` would be aware that the directory might be broken into parts (`file.path("path", "to", "dir")`). I'm not sure exactly what that would look like (whether it automatically expands to the vector format after autocompleting or if it just figures out that "path", "to", and "dir" belong together). 

Opening a file seems like a simpler task because it just needs to evaluate the `file.path()`-type function to get the path to open.

**Comment by noamross** [comment]
It seems to me that perhaps this could be done using an alternate completion key. There are a large number of functions in different packages that might take a path as separate arguments. Thus it's a tall order to detect whether one is in the right context to complete paths this way.  So maybe one could just complete paths this way by finishing with Cmd+Tab or something similar.

**Comment by malcolmbarrett** [comment]
Yeah, I agree it's the detecting the context that's tricky. It could specifically look for these small set of functions, but an alternate key stroke would probably work well, too. That would also extend well to opening a file

**Comment by malcolmbarrett** [comment]
I linked @hrbrmstr's path split add-in in https://github.com/hrbrmstr/hrbraddins to `opt+tab`, and that has been a good solution so far. It would be nice for official support for this practice, though, so I'm going to leave this open.

**Comment by kaijagahm** [comment]
I wanted to second the request for support around file paths for here::here(). @kevinushey told a user [here](https://community.rstudio.com/t/rstudio-tab-completion-within-here-here-function/25010) to post this as a feature request, and as far as I can tell, they haven't done so. I'm in the process of switching my file paths over to using here(), and since I have lots of subdirectories and long file names, autocomplete would be a huge help.

**Comment by shearerp** [comment]
I also would like some enhancements in this area. I often use RStudio's tab autocomplete to specify file paths, so I have a lot of stuff like this in my code:
```
# Case 1: string literal paths, good autocomplete support
source('src/model_v4/fit_model.R')
```
Sometimes I want to do this instead:
```
# Case 2: constructed paths, no autocomplete support
modeling_dir <- 'src/model_v4'
source(file.path(modeling_dir, 'fit_model.R'))
```
The problem is, I get great autocomplete support from RStudio in Case 1 and no support in Case 2.

I don't think a separate or special autocomplete key should be required here, as RStudio is already committed to autocomplete in Case 1, and Case 2 is even less ambiguous than Case 1. In Case 1, RStudio has to guess I'm typing a path based on forward slashes, but in Case 2, it knows for certain that I'm typing a path as soon as I finish typing `file.path(`.
