### ISSUE TITLE
RStudio Freezes after Windows 10 Hibernation

### ISSUE THREAD

**Issue by gainous** [rstudio/rstudio#5752]
I have seen other posts about this on the discussion board but none of the solutions have solved my problem.

Problem: Rstudio is open on my desktop (Windows 10) and I'm connected to a docking station. I close my laptop, remove it from the usb docking station, and the computer goes into hibernation. The next time I open my laptop, RStudio is frozen. The screen is still visible (workspace, script, etc), I can move the cursor around but can't click on anything, or run anything. I close the program, reopen it, and it works fine.

I have updated R, updated RStudio, and updated my packages. This does not solve the problem.

Please help.
### System details
    RStudio Version :  1.2.5019
    OS Version      :  Windows 10
    R Version       :  3.61

**Comment by jmcphers** [comment]
We will probably need some more details to resolve this, since most RStudio users are on Windows 10 and don't have this problem.

1. What version of Windows are you using?
2. Does switching to software rendering solve the problem? See: https://support.rstudio.com/hc/en-us/articles/360017886674-Troubleshooting-RStudio-Rendering-Errors
3. Can you include a diagnostic report? See: https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
4. When RStudio is frozen, is it using a lot of CPU time, or is it idle?
5. How is your external display, if any, connected to the laptop?
6. Does this problem ever happen in the absence of the docking station? For example, if you're using your laptop without the station and it hibernates, is RStudio still frozen when it comes up?

**Comment by gainous** [comment]
I'm trying software rendering now. I'll get back with all the information if that doesn't work. Thanks.

**Comment by gainous** [comment]
Thanks for the tips Jonathan. Software rendering seems to have solved the problem.

**Comment by ceciliabruno** [comment]
Hello,
I have the same problem, my RSturio frozen after windows 10 hibernate. I have the rendering suggested. 
I work with an additional monitor.
Thank you for your help

System information

R version 4.1.0 (2021-05-18)
RStudio version 1.4.1717
Windows Edition Windows 10 Home
