### ISSUE TITLE
instaltion package

### ISSUE THREAD

**Issue by ali296-ali** [rstudio/rstudio#5780]
The issue tracker is not for questions. If you have a question, please feel free to ask it on our community site, at https://community.rstudio.com/c/rstudio-ide.
je peut pas installer pachages

**Comment by ronblum** [comment]
@ali296-ali Thank you for filing the issue. However, there isn't enough information to understand and reproduce the problem, which is why we closed the issue. When you can provide more details, can you please open a new ticket? Thanks! Also, it looks like the template used was for asking questions. For bugs, the "Bug Report" option will provide a more useful template; or you can go directly here: https://github.com/rstudio/rstudio/issues/new?template=bug_report.md
