### ISSUE TITLE
Cannot use text box for a new project path

### ISSUE THREAD

**Issue by jangorecki** [rstudio/rstudio#5811]
Reproduce:

1. click "new project"
2. click "existing directory"
3. you should be in the window called "create project from existing directory"
4. there is a text box having label "project working directory"
5. trying to type text into this text box doesn't work, one has to use "browse" button and pick directory using graphical interface

If the text box is meant to be not writable it should be have grey background, otherwise it is confusing.
Using RStudio Build 93 (7b3fe265, 2019-09-18) on Xubuntu 18.04.

**Comment by BastiHz** [comment]
I can reproduce this on Windows 10 with RStudio1.2.5019.

**Comment by kevinushey** [comment]
This is, at least, partially intentional.

This mechanism helps ensure that we have a "valid" path before proceeding to whatever associated action would be taken with the selected directory; making the fields user-editable would necessitate moving that validation a step down. So it's not as simple as just making these text boxes editable.

@gtritchie, this might fall into the realm of accessibility (at least in terms of UI for displaying a non-editable textbox). Do you think our treatment here is sufficient, or is it worth tweaking?

**Comment by jangorecki** [comment]
Understandable but then it make sense to have it with grey background.
Writable text box could be useful in case when having a directory path in clipboard to paste it into that box. That would be even more useful when having a long path of multiple nested directories. Now I have to click "Browse", then hit "CTRL+L", and then I can paste the path.

**Comment by gtritchie** [comment]
I agree with @jangorecki that the current visual implementation is unexpected (I recently had the same reaction to it), and at a bare minimum should be changed to have a different background color to suggest the read-only behavior, otherwise it is a bit of a mystery why you can't type in it even though you can give it focus.

Making it be editable so you can paste a path into it or edit directly would be preferable, but as you say require a fair amount of work to change validation logic in quite a few places.

Offhand I can't map this to a specific WCAG accessibility violation; if a screen reader user tabs to the read-only text, the read-only state is announced along with the current content so they are actually in better shape here than a visual user. The fact you can get focus on it means you can easily read it with a screen reader, and select/copy it (not sure if that's ever useful).

FWIW, we have cases of this type of control (editbox with a browse button) where we do allow editing of the text (e.g. in the Import Dataset dialogs).

**Comment by gtritchie** [comment]
Another example of a read-only text field is "Search in" here: 

<img width="404" alt="2019-12-02_15-42-17" src="https://user-images.githubusercontent.com/10569626/70004578-a719af00-151b-11ea-909a-d8f2ee3a69c0.png">

**Comment by gtritchie** [comment]
Here's how it looks now (the text field is now the same color as the background to suggest it is read-only):

<img width="535" alt="2019-12-04_12-17-52" src="https://user-images.githubusercontent.com/10569626/70193492-3954bb00-16b4-11ea-8ce4-9cecbecfe715.png">
