### ISSUE TITLE
rStudio freeze when laptop hibernates

### ISSUE THREAD

**Issue by justin107d** [rstudio/rstudio#5927]
RStudio Edition : 
    RStudio Version :   1.2.5019
    OS Version      :    Windows 10 64 bit
    R Version       :     3.6.1

### Steps to reproduce the problem
1)  Load rStudio and start coding on Lenovo ThinkPad T440s.  I happened to be working with Shiny and Markdown, but I don't think it was specific to them.
2)  Let the screen turn black like it wants to hibernate or let it hibernate.

### Describe the problem in detail
When switching between computer and non-computer activities, rStudio will temporarily freeze up for extended periods o time.  The typing cursor will not blink or move.  Mouse is useable.  I can use the file through help menu items at the top of the window but nothing else responds.  If I try closing the window it tends to unfreeze faster.

### Describe the behavior you expected
Expected rStudio to be responsive if left alone for a little while.  Attatched the sessioInfo() report if you find it helpful.  Sounds similar to this thread:  https://community.rstudio.com/t/rstudio-freezes-after-hibernation-on-pc-laptop/44910/3

> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] RSelenium_1.7.5 rvest_0.3.5     xml2_1.2.2      httr_1.4.1      shiny_1.4.0     dplyr_0.8.3     tidyr_1.0.0    

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.3       pillar_1.4.2     compiler_3.6.1   later_1.0.0      bitops_1.0-6     tools_3.6.1      zeallot_0.1.0    digest_0.6.23   
 [9] lifecycle_0.1.0  tibble_2.1.3     gtable_0.3.0     pkgconfig_2.0.3  rlang_0.4.2      rstudioapi_0.10  curl_4.2         binman_0.1.1    
[17] xfun_0.11        fastmap_1.0.1    stringr_1.4.0    knitr_1.26       askpass_1.1      caTools_1.17.1.3 vctrs_0.2.0      grid_3.6.1      
[25] tidyselect_0.2.5 glue_1.3.1       R6_2.4.1         XML_3.98-1.20    selectr_0.4-2    semver_0.2.0     ggplot2_3.2.1    purrr_0.3.3     
[33] magrittr_1.5     backports_1.1.5  scales_1.1.0     promises_1.1.0   htmltools_0.4.0  rsconnect_0.8.15 assertthat_0.2.1 mime_0.7        
[41] colorspace_1.4-1 xtable_1.8-4     httpuv_1.5.2     stringi_1.4.3    openssl_1.4.1    lazyeval_0.2.2   munsell_0.5.0    wdman_0.2.4     
[49] crayon_1.3.4

**Comment by ronblum** [comment]
@justin107d I'm sorry this is happening, and thank you for bringing it to our attention. I'll mark it as a bug to review. Also, does this happen when the computer goes into sleep mode, not hibernate?

**Comment by justin107d** [comment]
Thanks, I notice it most when it comes out of sleep mode and my laptop is
unplugged.  Sometimes the R session fails to reconnect completely and I
have to close and reopen r studio.

**Comment by jmcphers** [comment]
We've had no other reports of this and don't have much else to go on (we don't have a Thinkpad to try a repro on) so closing it. @justin107d If this is still happening for you it would be very helpful to know whether one of RStudio's processes was pegging the CPU, and if so which one.

**Comment by kairikeymaster** [comment]
Hey, this is happening to me too: Windows 10, HP Spectre x360 ("gem cut" version). Doesn't seem to happen when computer sleeps, only when it hibernates. However, my computer doesn't have traditional sleep modes, it has "modern standby." I keep losing my environment and a lot of my variables take a long time to recompute.

**Comment by ericvaughn11** [comment]
Also adding that this issue persists for me on an Asus ROG Strix with both Windows 10 and Windows 11. Does indeed seem to be related to hibernation as keeping my laptop plugged in (where it won't hibernate, but does sleep) prevents RStudio from hanging. It's a bit frustrating because using software rendering doesn't seem to allow me to use Plotly, which I need for 3D plots I produce.

I'll report back if the problem comes up again, but I may have a cure (which I don't fully understand) that seems to work. I figured the computer graphics and Rstudio aren't playing nice at some point when Windows switches to low power hibernate, so I went into the nvidia control panel and switched Rstudio's preferred graphics processor from the default (Integrated) GPU, to my RTX3070 GPU (High Performance Nvidia GPU). I forced Windows to hibernate on battery and on power and don't seem to be getting any freezing anymore. Fingers crossed! Figured I'd post this now before I forget and maybe it'll help some of the others dealing with this pesky issue!

**Comment by justin107d** [comment]
If I recall I too was using plotly at this time.

**Comment by GabryS3** [comment]
Hey this is happening to me too...when I leave the computer for a while and I have RStudio open (I had been working with it but at that moment I leave the computer it was not running any process), then computer goes into sleep/hibernation mode and when I return to it RStudio is frozen and there is no way to reactivate it...i just have to restart it / force quitting and re-open it...

Has a fix been found for this issue? it is quite annoying...

Laptop: HP Zbook
Processor: Intel(R) Core(TM) i7-10810U CPU @ 1.10GHz   1.61 GHz
RAM: 16.0 GB (15.8 GB usable)
System type: 64-bit operating system, x64-based processor
OS: Windows 10 Enterprise - version 21H2 (OS build: 19044.1766)
R version: 4.2.1 
RStudio version: 2022.07.0 Build 548

I would appreciate any help!
Thanks
Gabriella

**Comment by kairikeymaster** [comment]
Sorry, not that I know.

**Comment by ronblum** [comment]
This is covered in issue #10831. This appears to be fixed by our current development builds, in which we switch to a new framework.  [This comment contains information about what can be tried out](https://github.com/rstudio/rstudio/issues/10831#issuecomment-1184491305). Please note that it's currently in development and intended for testing purposes only.
