### ISSUE TITLE
Support proper Python formatting in RMarkdown Python chunks

### ISSUE THREAD

**Issue by blairj09** [rstudio/rstudio#5945]
When creating Python chunks in RMarkdown documents, it would be nice if Python code was automatically formatted correctly. In the following example, the cursor doesn't automatically indent after the function definition line:
![image](https://user-images.githubusercontent.com/10444878/71632146-2efde200-2bca-11ea-8f65-7d050dec3df9.png)

When editing a standalone Python file, Python code is automatically formatted:
![image](https://user-images.githubusercontent.com/10444878/71632183-5c4a9000-2bca-11ea-8c67-942faf3cfd56.png)

**Comment by R-Hannibal** [comment]
@blairj09, thanks so much for reporting this issue!

We have a fix in place in our latest Daily build for the upcoming 1.4 release (available [HERE](https://dailies.rstudio.com/)). If you get the chance will you let us know if the issue is resolved for you in that build (no worries if not, reporting the issue alone is a tremendous help and we appreciate it 👍)?

**Comment by dfalty** [comment]
Verified functionality on v1.4.874 and now we have the python formatting in the RMD chunks. @blairj09 let us know if you see scenarios where this doesn't work now.
