### ISSUE TITLE
Qt 5.14 Data and Translations paths are missing /usr

### ISSUE THREAD

**Issue by JanMarvin** [rstudio/rstudio#5961]
### System details

    RStudio Edition : Desktop
    RStudio Version :  1.2.5033 (32f8964d9d65d5000eb64df89bdbfc4d1093c3e4)
    OS Version      :  Arch Linux with Qt 5.14
    R Version       :  3.6.2

### Steps to reproduce the problem

Build RStudio with `-DQT_QMAKE_EXECUTABLE=/usr/lib/qmake` and launch it. RStudio can no longer find Qt folders Data (resources) and Translations (translations). QtWebEngineProcess looks for both folders in `/share/qt` instead of `/usr/share/qt`

### Describe the problem in detail

After building RStudio on Arch Linux with Qt 5.14 when launching RStudio QtWebEngine complains that the paths for Data and Translations are missing. When looking for the folders it is missing `/usr`. This can be fixed placing a `qt.conf` in `/usr/lib/qt/libexec` [1]. The Arch Linux maintainer of `qt5-webengine` suggest that the messed up path is caused by RStudio [1].

[1] https://bugs.archlinux.org/task/64973?project=1&string=qt5-webengine

### Describe the behavior you expected

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
FWIW, we only generate `qt.conf` when generating package builds of RStudio (ie: bundling our own copy of Qt), and the structure is simply:

```
[Paths]
Prefix = ../
```

placed in the `/usr/lib/rstudio/bin` folder.

See also: https://github.com/rstudio/rstudio/blob/903359257eff3709ba3eb976746473f4f8c795ce/src/cpp/desktop/install/LinuxInstallQt.sh.in

**Comment by flying-sheep** [comment]
Hmm, in my native packaging script I want to use system Qt, but since the last rstudio release, I get errors like @JanMarvin.

What am I doing wrong? https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=rstudio-desktop

**Comment by stephensrmmartin** [comment]
I'd like to add this this is an ongoing problem. I have scoured the codebase for why /usr/ is removed. My only guess is there is some code, somewhere, that assumes we are using a bundled Qt, and then paths out to ../../../share or something when querying for the data location. In the latest AUR release of rstudio-desktop-git, I just include a qt.conf and drop it into /usr/lib/qt/libexec; not an ideal situation, since that affects all qt apps [it does not fully work when placing it in /usr/lib/rstudio/bin, because the qtwebengine executable is elsewhere].

I really have scoured the codebase though; I have no idea why or where the qt settings are being changed from default. I am about 60% sure that it is due to use of relative pathing somewhere, and that pathing is going 'past root', like ../../../share, which will resolve to /share. If anyone has any idea where this could be (perhaps in DesktopOptions.{cpp,hpp} somewhere), please let me know. Help me help you.

**Comment by gtritchie** [comment]
Going to make this as "fixed", although that's a bit misleading. We aren't fixing this, so much as eliminating it by the replacement of Qt with Electron, which is in-progress.

**Comment by gtritchie** [comment]
Closing this. We aren't going to make any changes to the Qt side, and this issue isn't relevant for Electron.
