### ISSUE TITLE
`previewRd()` should run in same session

### ISSUE THREAD

**Issue by hadley** [rstudio/rstudio#5994]
This would make previewing dynamic Rd files easier. The issue comes up in (e.g.) https://github.com/tidyverse/dplyr/pull/4689, where we're dynamically generating a list of methods for the generic. This works almost everywhere because the dynamic code is usually executed in the users session. The only exception is when you're viewing the development documentation with devtools, because we call `rstudioapi::callFun("previewRd", x$path)`, which performs the conversion in [a separate session](https://github.com/rstudio/rstudio/blob/39503aeab68f6da717ceadc25a7b9b9478e0fae8/src/cpp/session/modules/SessionHelp.cpp#L731-L766).

(Thanks to @kevinushey for the investigation of where this happens)

**Comment by hadley** [comment]
This is low priority, but would be a small quality of life improvement for package devs.

**Comment by hadley** [comment]
Bump

**Comment by romainfrancois** [comment]
At the end of the day, `R CMD Rdconv` calls `tools::Rd2HTML()` so we might as well call that directly. https://github.com/r-devel/r-svn/blob/e90a8c9ccf70236ec5ca74d0d0a055c2952ab9e2/src/library/tools/R/Rd2pdf.R#L530

```
> capture.output(tools::Rd2HTML("man/summarise.Rd"))[178:180]
[1] "<p>The following methods are currently available in loaded packages:"              
[2] "dplyr (<code>data.frame</code>, <code>grouped_df</code>, <code>rowwise_df</code>)."
[3] "</p>" 
```

**Comment by romainfrancois** [comment]
QA note: 

- open a package project, e.g. `dplyr` 
- `load_all()` it
- open a help page, e.g. `?summarise` 

This will open a preview help page: 

<img width="1139" alt="image" src="https://user-images.githubusercontent.com/2625526/176400076-fb305c75-4dc3-4e5b-86fe-9f84f0e4021b.png">

but it "knows" about the methods because has been run on the same session: 

<img width="1128" alt="image" src="https://user-images.githubusercontent.com/2625526/176400214-ba71a3bc-b1be-4405-bb81-43dd021437d9.png">

Clicking on links will stay in the preview iff they land on the same package: 

<img width="1129" alt="image" src="https://user-images.githubusercontent.com/2625526/176400496-e0d5986c-de1a-4a57-9abd-d30e363f3e68.png">

but not if going to another, e.g. clicking on `mean()` opens the regular `base::mean()` documentation: 

<img width="1132" alt="image" src="https://user-images.githubusercontent.com/2625526/176400653-aaa3115d-6ccc-4f14-8a07-8b8ee4ff0967.png">

**Comment by romainfrancois** [comment]
This is part of an evil plan to learn some more about how the help system work, so that we can tackle https://github.com/rstudio/rstudio/issues/2083

**Comment by jonvanausdeln** [comment]
Verified on 2022.11.0-82
Windows 11, MacOS 12.4, Ubuntu 22.04

Tested several different packages and help files, including the links within.
