### ISSUE TITLE
Set working directory to source file location that includes quotes in the path

### ISSUE THREAD

**Issue by GreatEmerald** [rstudio/rstudio#6004]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.5033
    OS Version      : Ubuntu 18.04
    R Version       : 3.6.1

### Steps to reproduce the problem
1. Create a directory that includes a " (quote) character
2. Put an R script into it
3. Open it in RStudio and try to set working directory to source file location

### Describe the problem in detail
Pressing the "Set source file location" -> "To source file location" button fails with error: "Unexpected symbol in "setwd(..."

### Describe the behavior you expected
The quote in the path should be escaped and the command should succeed.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@GreatEmerald Thank you for raising this issue. I can reproduce it in RStudio Desktop 1.2.5033 on MacOS 10.15.3 and RStudio Server 1.3.730 on Red Hat 7.7. We'll review it as we continue development of RStudio.

Note: Using directory names with single double quotes (`quo"ty`) and single quotes (`sing'ly`), the following work:
- setting to a directory with single quotes, since the single quote is enclosed within double quotes: `setwd("~/sing'ly")`
- sourcing a file in the double-quoted directory, as `source` uses single quotes around the file name:  `source('~/quo"ty/bobo.R')`
- sourcing a file in a single-quoted directory, because the file name's single-quotes are escaped:  `source('~/sing\'ly/momo.R')`
- setting to a directory with double quotes using the dropdown menu in the MacOS R application

**Comment by GreatEmerald** [comment]
Still happens at least in 1.3.1073. Trying to set the directory to `~/temp/"`:
```R
> setwd("~/temp/"")
+
```
It waits for input forever.

**Comment by kevinushey** [comment]
You need to escape the quotes in the string; e.g.

```
setwd("~/temp/\"")
```

(or, even use single quotes so you can embed double quotes without escaping)

**Comment by kevinushey** [comment]
Associated code that's incorrectly escaping strings here:

https://github.com/rstudio/rstudio/blob/e92d8790f8d135fc2e390b69ffcdbb917106729e/src/gwt/src/org/rstudio/studio/client/common/ConsoleDispatcher.java#L52-L62

**Comment by valerie-rstudio** [comment]
### Verified Fixed

    RStudio Edition : Desktop
    RStudio Version : 1.4.1591
    OS Version      : mac OS 11.2.1
    R Version       : 4.0.3

Verified that you can now successfully set the working directory to a directory that has a name containing double or single quotes.
