### ISSUE TITLE
View doesn't try to convert the input to data.frame

### ISSUE THREAD

**Issue by moodymudskipper** [rstudio/rstudio#6007]
This is not consistent with `utils::View()` and its doc : 

> Object x is coerced (if possible) to a data frame, then columns are converted to character using format.data.frame. The object is then viewed in a spreadsheet-like data viewer, a read-only version of data.entry.

Reproduce with : 

```
View(as.list(iris))
utils::View(as.list(iris))
```

**Comment by ronblum** [comment]
@moodymudskipper Thank you for filing the issue. This is the actually the expected behavior, as `View` within RStudio opens the Object Explorer for list-like objects. The same would occur when clicking on the search icon for a list environment variable in the Environment pane. For example:

`iris_list <- as.list(iris)`

<img width="966" alt="iris_list" src="https://user-images.githubusercontent.com/31009952/72285811-ea366a00-3611-11ea-8bbb-ddc7b4531b0b.png">

Some information about the Object Explorer is available [in this blog post](https://blog.rstudio.com/2017/08/22/rstudio-v1-1-preview-object-explorer/) from when it was first introduced.

**Comment by moodymudskipper** [comment]
Thanks Ron, could Rstudio show an help file that corresponds to the observed behavior?

**Comment by ronblum** [comment]
@moodymudskipper Do you mean the equivalent of something like ```?View()``` that reflects the different behavior in RStudio? That or something similar sounds reasonable. Would you mind opening a new request for that? This way we can keep this one for the issue you raised, in case someone else runs into it, and separately an enhancement request to consider. Thanks!
