### ISSUE TITLE
Allow keyboard shortcuts for splitter adjustment

### ISSUE THREAD

**Issue by noamross** [rstudio/rstudio#6060]
#6029 Added the excellent feature of adjusting pane sizes via keyboard.  However, the menu commands to adjust left/right/middle splitters do not appear as commands that can be assigned under "Modify Keyboard Shortcuts..."

I am using 1.3.761, R 3.6.0, macOS 10.14.6

**Comment by gtritchie** [comment]
They can be assigned keyboard shortcuts, but the command names are not obvious. Search for "separator" and you will see them (they use "focus separator" internally instead of "adjust separator" you see in the menu).

<img width="724" alt="modify keyboard shortcuts dialog showing focus separator commands" src="https://user-images.githubusercontent.com/10569626/72697676-8f12e480-3af5-11ea-97ae-086032a74d64.png">
