### ISSUE TITLE
Exception in Find in Files dialog

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#6085]
### System details

    RStudio Edition : Server
    RStudio Version : 1.3.773

### Repro

Not 100% sure, but suspect that it occurs when we close the Find in Files dialog while we are waiting for preview results to come back.

### Describe the problem in detail

```
23 Jan 2020 00:08:21 [rserver] ERROR CLIENT EXCEPTION (rsession-jmcphers): (TypeError) : null is not an object (evaluating '(nIw[b]='128',a).resultsCount=0');
org/rstudio/studio/client/workbench/views/output/find/FindInFilesDialog.java#128::clearResultsCount
org/rstudio/studio/client/workbench/views/output/find/FindOutputPresenter.java#466::initialize
org/rstudio/studio/client/workbench/views/output/find/FindOutputTab_Shim__Impl.java#79::onSuccess2
org/rstudio/studio/client/workbench/views/output/find/FindOutputTab_Shim__Impl.java#65::execute
org/rstudio/core/client/AsyncShim.java#92::preInstantiationHook
org/rstudio/studio/client/workbench/views/output/find/FindOutputTab_Shim__Impl.java#63::onSuccess
```

### Describe the behavior you expected

No exception. We probably need a null guard here (unless this is suggestive of a deeper issue):

https://github.com/rstudio/rstudio/blob/46f6e09c13285b121062782e122f555b854a5a1f/src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/FindOutputPresenter.java#L249-L251

**Comment by jmcphers** [comment]
Another stack with the same issue:

```
23 Jan 2020 00:08:21 [rserver] ERROR CLIENT EXCEPTION (rsession-jmcphers): (TypeError) : null is not an object (evaluating '(nIw[b]='128',a).resultsCount=0');
org/rstudio/studio/client/workbench/views/output/find/FindInFilesDialog.java#128::clearResultsCount
org/rstudio/studio/client/workbench/views/output/find/FindOutputPresenter.java#466::initialize
org/rstudio/studio/client/workbench/views/output/find/FindOutputTab_Shim__Impl.java#79::onSuccess2
org/rstudio/studio/client/workbench/views/output/find/FindOutputTab_Shim__Impl.java#65::execute
org/rstudio/core/client/AsyncShim.java#92::preInstantiationHook
org/rstudio/studio/client/workbench/views/output/find/FindOutputTab_Shim__Impl.java#63::onSuccess
23 Jan 2020 20:35:05 [rserver] ERROR CLIENT EXCEPTION (rsession-jmcphers): (TypeError) : Cannot read property 'resultsCount' of null;
rstudio-0.js@27#408837::getResultsCount
rstudio-0.js@19#411238::FindOutputPresenter$8.onClick
rstudio-0.js@16#31392::ClickEvent.dispatch
rstudio-0.js@8#31387::ClickEvent.dispatch
rstudio-0.js@8#30997::GwtEvent.dispatch
rstudio-0.js@14#33724::dispatchEvent
rstudio-0.js@9#33834::SimpleEventBus.doFire
rstudio-0.js@8#33913::SimpleEventBus.fireEvent
rstudio-0.js@24#33666::HandlerManager.fireEvent
rstudio-0.js@28#31079::fireNativeEvent
rstudio-0.js@3#31059::fireNativeEvent
rstudio-0.js@7#113688::ToolbarButton.lambda$3
rstudio-0.js@25#165951::ToolbarButton$lambda$3$Type.onMouseUp
rstudio-0.js@16#32581::MouseUpEvent.dispatch
rstudio-0.js@8#32576::MouseUpEvent.dispatch
rstudio-0.js@8#30997::GwtEvent.dispatch
rstudio-0.js@14#33724::dispatchEvent
rstudio-0.js@9#33834::SimpleEventBus.doFire
rstudio-0.js@8#33913::SimpleEventBus.fireEvent
rstudio-0.js@24#33666::HandlerManager.fireEvent
rstudio-0.js@30#12783::Widget.fireEvent
rstudio-0.js@28#31079::fireNativeEvent
rstudio-0.js@3#12848::Widget.onBrowserEvent
rstudio-0.js@17#57613::dispatchEventImpl
rstudio-0.js@3#57601::dispatchEvent
rstudio-0.js@3#59730::DOMImplStandard.dispatchEvent
rstudio-0.js@28#16334::apply
rstudio-0.js@16#16393::entry0
rstudio-0.js@14#16372::<anonymous>
```

**Comment by melissa-barca** [comment]
Hey @jmcphers I'm having trouble reproducing these errors - when you mention the Find in Files dialog are you referring to the results pane or where you select the find options?

**Comment by melissa-barca** [comment]
Hi @jmcphers looking into this more, the first stack trace is caused by this line: https://github.com/rstudio/rstudio/blob/46f6e09c13285b121062782e122f555b854a5a1f/src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/FindOutputPresenter.java#L466

`resultsCount` is a new member of the state so this exception happens every time someone first initiates the new `Find In Files` state. The call to `clearResultsCount` needs to be removed from the initialize function also because this field should retain its value. This likely caused a bug @gtritchie brought up during development that we couldn't reproduce where the replace warning inaccurately stated it would replace `0 occurrences`.

Your second stack trace has me more confused because this.resultsCount should always exist after the first initialization. Do you have any more clues on how you got there? A null guard will do the trick, but like you said we need to make sure there's not a deeper issue. Thanks!
