### ISSUE TITLE
Option to choose repos other than CRAN (eg. Bioconductor) in the "Install Packages" popup

### ISSUE THREAD

**Issue by gabrielodom** [rstudio/rstudio#6130]
## Feature Request:
After speaking with @topepo and @RaymondBalise at the Tidy Dev Day, we discussed options to install from CRAN-like repositories (such as Bioconductor) in the "Install from:" drop-down menu in the "Install Packages" popup. **Please add Bioconductor to the drop-down menu in the "Install Packages" popup window.**

## Motivation
The [Bioconductor](https://www.bioconductor.org/about/) package repository is a massive R package repository specifically for packages related to bioinformatics, biostatistics, genetics, and other fields connected to computational biology. These packages collectively represent hundreds of millions of dollars in NIH and NSF grant funding, as well as hundreds of thousands of human development hours.

## Benefit
If Bioconductor packages are easier to install from the RStudio IDE, then more new Bioconductor R users will be willing to use RStudio.

## Current Workaround
Currently, Bioconductor users call the following code in the command line to install packages (`pathwayPCA` for example):
```
install.packages("BiocManager")
BiocManager::install("pathwayPCA")
```

**Comment by eddelbuettel** [comment]
The issue is actually more complicated.  There are several aspects. As you wrote so diligently with nice formating I will attempt to do the same.

### Existing Support in R 

In a narrow sense, you would like to extend the dropdown for repos in RStudio. The functionality in R is however a little different: it just because "one pool" and that _already works_.   

Background:  Repositories have worked in R since the 1990s.  In fact, at some point R had stanza for CRAN (always empty, leading to the prompt for "which one" at first use unless set which became common in the last few thanks to the CDN behind https://cloud.r-project.org, also set up by RSudio, which ensures you are always network-close) as well as BioConductor and OmegaHat (an initiative from the early 2000s "for a possible successor to R" now largely forgotten).  The help pages eg `help(Startup)` showed how to use it and you can for example do this in `~/.Rprofile`:

```r
    r <- getOption("repos")
    r["CRAN"] <- "https://cran.rstudio.com"
    r["ghrr"] <- "https://ghrr.github.io/drat"
    #r["BioC"] <- "https://bioconductor.og"
    options(repos = r)
```

Try it. If you do this, then on the next start of RStudio the 'button' which show 'CRAN. ghrr' combing CRAN and a [drat](https://github.com/eddelbuettel/drat)-repo (of mine) at GitHub.  

In short, no change needed, multi-repo support is already there.

### BioConductor always was different

The scheme from the previous section works because _all standard repos_ have a `src/contrib/` layout. Which is what add-ons like [drat](https://github.com/eddelbuettel/drat) can rely on, and which scripted installers (I have two in the [littler](https://github.com/eddelbuettel/littler) package I use essentially daily to install or upgrade) use.  BioConductor always used a different scheme to control the interaction between R and its (now annual) releases and the BioConductor releases. Hence the need for `BiocManager::install`.  It simply does not fit the existing schedule, and hence does not fit the GUI scheme you want to add it to.  Try uncommenting the BioC line in my code snippet above and restart--you will get an error.  BioC really is different.  

### Conclusion

I think there is nothing much that the IDE can do here.  Maybe one day someone wants to do an Addin for BioC.

**Comment by mtmorgan** [comment]
`BiocManager::repositories()` returns the correct repositories (including CRAN) for the current R / Bioconductor installation, and actually `BiocManager::install()` uses `install.packages()` with repositories arranged correctly (for us).  A comparable hack would be
```
r <- getOption("repos")
r["ghrr"] <- "https://ghrr.github.io/drat"
r <- append(BiocManager::repositories(), r)
options(repos = r)
```
For an .Rprofile solution, this requires that the BIocManager package is already installed...

**Comment by eddelbuettel** [comment]
> The scheme under https://bioconductor.org/packages/<bioc-version>/bioc is the same as a standard CRAN src/contrib repository structure, contradicting Dirk's [s]tatement.

Right. I looked into that a few times in the last two decades as I am _e.g._ quite fond of the `install.r` and `install2.r` wrappers in littler---and I forgot about / omitted here the point about the _additional_ directory layer you inject for the versioning. Once that is taken care of one _can_ script away.  It "just" needs meta-information to match releases, or automagically switch to dev, or ...:

```r
R> BiocManager::repositories()           # naive use on my R 3.6.2 box
Error: Bioconductor version '3.8' requires R version '3.5'; see https://bioconductor.org/install
R> 
```

I'll make a mental note to play with what you provided to build maybe a `biocinstall.r` for littler using the YAML data etc.  I have the need often enough for reverse-depends checks for Rcpp and friends.

But I think the _tl;dr_ remains the same: this is not something that can be added all _that_ easily to the package installer in RStudio.   Thanks for all the added colour!
