### ISSUE TITLE
Autocompleting with quotes `` atributes starting with '__'  (python)

### ISSUE THREAD

**Issue by Iuiu1234** [rstudio/rstudio#6203]
In python,
When autocompleting atributes of a variable starting with '__',
RStudio adds an inconvenient quotation \`\`

Example:
If you do autocompletion of  __str__ with
 `string = 'this is a string'`
output from RStudio is
`string.\`_str__\`
instead of the desired
`string.__str__`

**Comment by kevinushey** [comment]
It looks like this has already been fixed in the latest [daily builds](https://dailies.rstudio.com). If you're able, would you mind downloading and testing the latest available daily build and confirm whether this appears to be fixed?

Please feel free to re-open if you find the issue has not been resolved.

**Comment by dfalty** [comment]
This works for me on version 1.4.874. Please reopen if it doesn't work for you.
