### ISSUE TITLE
RStudio freezes after creating a new code chunk

### ISSUE THREAD

**Issue by jeancjw** [rstudio/rstudio#6210]
### System details

    RStudio Edition : 
    RStudio Version : 1.3.776
    OS Version      : 10.15.2
    R Version       : 3.6.2

### Describe the problem in detail
Rstudio freezes after I create a new code chunk. I can't click anywhere within RStudio or close the window. I ended up having to force quit each time this happens (pretty much every time I open RStudio).
### Describe the behavior you expected

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@jeancjw Thank you for raising the issue. A few questions:
- Does the problem occur when creating the chunk, even an empty chunk?
- Is there any particular code that causes the problem, or any code?
- Are you creating it by hand or by using the "Insert" button in the Rmd menu?
- What happens when opening a new default Rmd file with File -> New File -> R Markdown, which has predefined chunks in it—does that cause a problem?
- Was this an issue in version 1.2, if you've used it before?
Thanks!

**Comment by jeancjw** [comment]
Hello, 

It usually occurs when I create an empty chunk, but it happens at random.

I create the chunk using the keyboard shortcut.

Opening a new file has no issues.

This only happened after I did a recent update to my R and Rstudio.


Thanks,
Jeanette

**Comment by kevinushey** [comment]
Should be fixed in the latest daily builds via https://github.com/rstudio/rstudio/pull/6259. Thanks for reporting!
