### ISSUE TITLE
RStudio ver. v1.3.820-1 without diacritic marks

### ISSUE THREAD

**Issue by KapRob** [rstudio/rstudio#6236]
In the newest RStudio ver. v1.3.820-1 (Win 10 x64 ver.) I've lost diacritic marks. When I type ALT+S my files are saved which is wrong. I should have got a diacritic mark in my language. The same with ALT+L.

**Comment by ronblum** [comment]
@KapRob Thank you for raising the issue. Before reproducing, what do you expect ALT+S to do—provide a list of diacritics, or a specific one? And what do you expect ALT+L to do? Also, in doing a bit of research, it looks like ALT+S and ALT+L behave differently in different applications. Thanks!

**Comment by KapRob** [comment]
Just one i.e.
ALT+S gives ś
ALT+L gives ł

Every application behaves in the same way - just gives letters. Codes of these letters in UTF-8 are: 347 and 322. Please look below:

library(stringi)
stri_enc_toutf32(c("ś", "ł"))

**Comment by KapRob** [comment]
Still the same problem although RStudio v1.3.895-2 was released.

**Comment by ronblum** [comment]
@KapRob Thanks! I can reproduce this in RStudio 1.3.895:
- With AltGr and a Polish keyboard layout
- Save all documents, for example, should require Ctrl+Alt+S, not Alt+S
- Remapping the keyboard shortcuts, such as Ctrl+Alt+, for the above, doesn't help—instead, nothing is printed
We'll review this as we continue development of RStudio.

**Comment by KapRob** [comment]
Save a document should require Ctrl+S  and all documents Ctrl+Alt+S.

**Comment by mbojan** [comment]
I subscribe to the reported problem too. I upgraded to a preview version of RStudio (because of #6801, now at `1.3.956`) and it just turned out it's not possible for me to write in Polish. It seems to be a re-occuring problem, see my [comment on RStudio Support](https://support.rstudio.com/hc/en-us/articles/206382178/comments/204752297) from 2015 for a list of "special" letters and some references. I disabled all possibly conflicting shortcuts in "Modify Keyboard Shortcuts...". Unfortunately I still can't use `ć` (AltGr+c), `ł` (AltGr+l), `Ł` (AltGr+L) nor `ę` (AltGr+e).

This is really a fundamental problem for Polish users.

**Comment by kevinushey** [comment]
Do you still see this issue in the latest [daily builds](https://dailies.rstudio.com) of RStudio?

**Comment by KapRob** [comment]
I’ve just checked and the problem gone. Thank you.

**Comment by mbojan** [comment]
Yep, works!
