### ISSUE TITLE
Non - English notes report errors

### ISSUE THREAD

**Issue by JnuLi** [rstudio/rstudio#6254]
Use reticulate to run Python with normal comments or strings when compiling Python in R Markdown

```python
print('hello word")
```
output
```
hello world
```
When using Japanese or Chinese

```python
print("石原さとみ")
```
Error
```
Warning in strsplit(code, "\n", fixed = TRUE) :
  input string 1 is invalid UTF-8
Error in py_run_string_impl(code, local, convert) : 
  NameError: name 'NA' is not defined

Detailed traceback: 
  File "<string>", line 1, in <module>
```

**Comment by R-Hannibal** [comment]
@joaomacalos, thanks again for helping to narrow down the reproduction of this issue (and @JnuLi for raising it originally). 

We have a fix in place in our latest daily build for the 1.4 release of RStudio (available [HERE](https://dailies.rstudio.com/)). If you get the chance will you let us know if the issue is resolved for you in that build?

**Comment by joaomacalos** [comment]
Hi @R-Hannibal , thanks for taking a look at this.
I tried now on my machine and it worked perfectly, both in the toy problem reproduction I posted here and in my actual work where I faced the problem.
Cheers!
