### ISSUE TITLE
Auto save on idle makes code completions difficult/impossible to use

### ISSUE THREAD

**Issue by WilDoane** [rstudio/rstudio#6363]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.879
    OS Version      : Windows 10 x64 (build 17763)
    R Version       : 3.6.2 (2019-12-12)

### Steps to reproduce the problem

Set Tools > Global options > Code > Saving > When editor is idle... to "save and write changes"
Set Tools > Global options > Code > Saving > Idle period... to a moderate number for convenience of observing this effect (1000 ms, e.g.)

Create a named source file. In that file, type code for any function that takes arguments. Within the parentheses, manually trigger completion or type enough characters for auto complete to trigger. 

### Describe the problem in detail

The completion menu pops up, then disappears. The auto save takes focus away from the source editor, so the completion popup menu is deactivated.

### Describe the behavior you expected

The completion menu should remain in focus, despite the background document being saved OR the document save should be deferred until no popup menu is active.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
The problem here is that, on save, we refresh a lot of things related to the editor state (including the appropriate editor mode for the file extension). See:

https://github.com/rstudio/rstudio/blob/aaea02860259a7c37107a33e947fdefc6997cb08/src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetWidget.java#L226-L237

https://github.com/rstudio/rstudio/blob/aaea02860259a7c37107a33e947fdefc6997cb08/src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditor.java#L762-L860

We should consider whether we can skip some of these steps when we know the editor language has not changed.

**Comment by jmcphers** [comment]
This is also a problem with vim bindings since we currently leave insert mode when saving.

https://github.com/rstudio/rstudio/issues/6302

**Comment by rich-rstudio** [comment]
verified in version 1.4.77
