### ISSUE TITLE
Make vertically unaligned auto-indent code in the source pane more tidyverse style compliant

### ISSUE THREAD

**Issue by lorenzwalthert** [rstudio/rstudio#6472]
I uncheck the following box in RStudio settings:

Tools -> Global Options -> Code -> Editing -> Vertically align arguments in auto-indent

When the box is *not* checked, the closing parenthesis is moved to the next line when there are no arguments in the call.
```r
call( )
~~~~~^ if I am here and I hit enter
```

I get
```r
call(
  
~^ cursor
)
```

Which is fine. But when I already typed the first argument and hit enter, this does not happen, I will end up like this
```r
call(x = 3,
    )
   ~^ cursor
```
But I think I should end up like this (i.e. just as in the very first code sniped in this comment, but with `x = 3` on the first line):
```r
call(x = 3
  
~^ cursor
)
```

Maybe it's easier to convey this with a GIF:

![rstudio-cursor](https://user-images.githubusercontent.com/10477073/76692666-dcc14e80-6659-11ea-845a-95217e8c6b97.gif)

This would make the behaviour more tidyverse style compliant, as discussed in #6411.

**Comment by ronblum** [comment]
@lorenzwalthert Thank you for filing this issue for separating the bug from the enhancement!

**Comment by aidanhorn** [comment]
When I assign an object (with the `<-` operator), RStudio forces me to put the tailing bracket on the same column as the object name. For example:
```
foo <- c(
  "foo"
)
```
instead of
```
foo <- c(
    "foo"
  )
```
Personally, I would prefer to do it the second way, as then it is more obvious when an object is created. However, I've found that I'm constantly spending seconds editing RStudio's default indentation behaviour, which adds up to minutes and hours over time. I suppose I just need to resign to the default, and fit in with it, because I can't find a way to prevent RStudio from editing the whitespace while I'm busy typing.

**Comment by lorenzwalthert** [comment]
I think the behavior you described @aidanhorn is expected and consistent with the tidyverse style guide and many others. Closing braces are always unindented, this is also the case for curly braces. 
```r
if (x) {
  'indented'
}
```
