### ISSUE TITLE
Project-Menu disappears and no longer reappears when pressing Ctrl+W

### ISSUE THREAD

**Issue by strengejacke** [rstudio/rstudio#6474]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.878
    OS Version      :  Windows 10
    R Version       : 3.6.3

### Steps to reproduce the problem

1) Open RStudio
2) Have some opened files, so you have multiple tabs
3) Click top right corner on project menu:

![image](https://user-images.githubusercontent.com/26301769/76704457-711ec600-66d9-11ea-8411-511f1c10bef7.png)

4) Press Ctrl+W: this will close the menu with the projects list as well as the current active file tab.
5) Now, the project menu (see screenshot above) can no longer be opened again. When pressing on the button that opens the projects menu, an empty square appears:

![image](https://user-images.githubusercontent.com/26301769/76704552-16399e80-66da-11ea-920c-4445171c8155.png)

**Comment by kevinushey** [comment]
I can reproduce on macOS as well. Appears to be a regression as this does not occur on v1.2.

**Comment by adamconroy** [comment]
Spent an hour researching this today. So far I have determined that it's not caused by anything after the call to `closeSourceDoc` so it happens further up the chain (or adjacent). This is very weird indeed.

**Comment by adamconroy** [comment]
This happens when any command is invoked, including save.

**Comment by mikebessuille** [comment]
Kevin says may have already been fixed

**Comment by adamconroy** [comment]
Can confirm that this appears fixed.

**Comment by R-Hannibal** [comment]
@strengejacke, thank you for finding and reporting this issue. 

This issue appears to be fixed in the latest Daily builds for our upcoming 1.4 release of RStudio (available [HERE](https://dailies.rstudio.com/)). Please let us know if the issue re-occurs for you in that build or if you have any other issues you'd like us to look at addressing. And thanks so much for helping us to improve RStudio 😊!
