### ISSUE TITLE
Handle possible NULL char * crashes

### ISSUE THREAD

**Issue by MariaSemple** [rstudio/rstudio#6486]
In some places we attempt to construct `FilePath` objects with `char*`s we receive from other function calls. Because `FilePath` doesn't have a `char*` constructor, the `char*`s are being implicitly converted to `std::string`, which might be causing some seg faults if the `char*` in question is `NULL`. 

To handle this, we should add a `FilePath(const char*)` constructor which throws a proper exception if the `char*` is `NULL` so that it will be more clear what went wrong. We should also address the places in our code that invoke said constructor to avoid the throwing of any exception.

Null char* vulnerable locations that I was able to identify:
* https://github.com/rstudio/rstudio/blob/master/src/cpp/desktop/DesktopUtils.cpp#L451-L463
* https://github.com/rstudio/rstudio/blob/master/src/cpp/shared_core/system/User.cpp#L86

**Comment by jmcphers** [comment]
We're not very exception safe in most parts of the code and this carries a lot of risk as we create `FilePath` objects constantly in every area of the product. Moving to 1.5 due to risk.

**Comment by R-Hannibal** [comment]
Closing as Fixed.

Based off @jmcphers's qa notes:

"This change is too low-level to test directly, and we don't have repro steps for any crashes suspected to be caused by it, so manual verification probably isn't warranted here."

There does not appear to be a great way to verify this and there are no user reports to follow up on. Closing.
