### ISSUE TITLE
Changing rendering engine resets panes positions

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#6560]
**Steps to reproduce**:
* Change the default placement of the panes (console, editor, help, etc.) (Tools -> Global Options -> Pane Layout).
* With that change already in effect, change the rendering engine (Tools -> Global Options -> Advanced -> OS Integration), and restart RStudio afterwards.

**Expected behavior:** should remember the custom placement of the panes.

**Actual behavior:** panes placements are reset.

**Setup:** RStudio 1.3.929, running on debian linux.

**Comment by ronblum** [comment]
@david-cortes Thank you for raising this! I can't reproduce this, though, using RStudio Desktop 1.3.929 on Debian 10 with R 3.6.3. 
1. Does it happen with any change to the rendering engine, or only when switching to a specific one?
2. Can you send me a screenshot of the pane layout so that I can reproduce the exact scenario?

**Comment by david-cortes** [comment]
Not reproducible anymore. Guess it was just a bad session.
