### ISSUE TITLE
Consistently detect missing package dependencies when knitting an R Markdown document and display an install popup.

### ISSUE THREAD

**Issue by R-Hannibal** [rstudio/rstudio#6563]
### System details

    RStudio Edition : Desktop & Server
    RStudio Version : Version 1.3.926
    OS Version      : Windows 10 Pro
    R Version       : 3.6.3

### Steps to reproduce the problem

1. Open RStudio and select File > New File > 'R Markdown...'.
2. Paste the following into the new R Markdown document:

```
---
title: "Issue"
author: 'Yes'
date: "3/26/2020"
output: revealjs::revealjs_presentation
---
```

3. Select 'Knit'. 
### Describe the problem in detail
For certain package dependencies (listed in 'Describe the behavior you expected'), knitting an R Markdown document detects the missing package and opens a pop up informing the user that running the document requires a package they are missing and asking if they want to install it. For the dependencies listed below, no pop-up is displayed, although an error is displayed in the R Markdown log.
**Known Dependencies missing pop-up**:
`output: revealjs::revealjs_presentation`

```
params:
   year: 2018
```

```
output:
  flexdashboard::flex_dashboard
```

![R Markdown_Lack of popup](https://user-images.githubusercontent.com/62304541/78060424-1b8d1f00-7351-11ea-9a2c-925a7fd575a7.PNG)

### Describe the behavior you expected
Behavior is consistent when knitting a document across different types of missing package dependencies. Currently the desired behavior is exhibited by the following dependencies:
`runtime: shiny`

`runtime: shiny_prerendered`

![Shiny_dependency_popup](https://user-images.githubusercontent.com/62304541/78059453-7de52000-734f-11ea-8f66-875d43b5b4c4.PNG)

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
There's a bit of a disconnect here...

The toolbar shown at the top shows packages used or referenced in the user's document, which are not currently installed. This is based on static analysis of the R code in the document (ie: looks for `library()` calls and similar usages) and is ultimately a "best-guess". For that reason, we don't want to block user actions if they've decided to ignore this toolbar for some reason.

The "Running shiny documents" dialog is a harder requirement set by the IDE. Those are the R packages that the IDE needs in order to run Shiny documents at all, separate from other packages which might be referenced or used in the document itself.

Given those constraints I _think_ this UI is okay, but the way we communicate this could be improved.
