### ISSUE TITLE
RStudio crashes without any user friendly error

### ISSUE THREAD

**Issue by vinaychuri** [rstudio/rstudio#6580]
Posting this here to check if anyone else has the same issue.

```
library(dplyr)
attach(mtcars)
mtcars%>%
  count(cyl) # this prints correct information
    cyl     n
  <dbl> <int>
1     4    11
2     6     7
3     8    14

```

But the following should have ideally given me some error saying invalid column etc.
```
mtcars%>%
  count(Cyl) # note that caps "C"

```
But , RStudio crashes with "R Session Aborted" + bomb icon + R encountered a fatal error. The session was terminated.

My versions of the packages are as follows:
R version 3.6.2 (2019-12-12) -- "Dark and Stormy Night"
RStudio Version 1.2.5033
dplyr version ‘0.8.5’

Any thoughts or insights ??

Vinay

**Comment by vinaychuri** [comment]
More debugging:

When I try the invalid command in R.App I get some error information as follows.

> mtcars%>%count(Cyl)

 *** caught segfault ***
address 0x0, cause 'unknown'

Traceback:
 1: grouped_df_impl(data, unname(vars), drop)
 2: grouped_df(groups$data, groups$group_names, .drop)
 3: group_by.data.frame(...)
 4: group_by(...)
 5: .group_by_static_drop(x, ..., add = TRUE, .drop = .drop)
 6: count(., Cyl)
 7: function_list[[k]](value)
 8: withVisible(function_list[[k]](value))
 9: freduce(value, `_function_list`)
10: `_fseq`(`_lhs`)
11: eval(quote(`_fseq`(`_lhs`)), env, env)
12: eval(quote(`_fseq`(`_lhs`)), env, env)
13: withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
14: mtcars %>% count(Cyl)

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
Selection:

**Comment by ronblum** [comment]
@vinaychuri Thank you for raising the issue. Are you using RStudio Desktop or Server, and what operating system are you working with?

That said, since standalone R is crashing, this appears to be external to RStudio. This issue repository is meant for raising bugs and enhancement requests for RStudio. For R questions, I suggest visiting 
[the RStudio Community](https://community.rstudio.com/) and [Stack Overflow](https://stackoverflow.com/questions/tagged/r). Both are good places to search for issues similar to what you're running into, or for posting your questions.
