### ISSUE TITLE
Tutorials installed into the system library don't run

### ISSUE THREAD

**Issue by trestletech** [rstudio/rstudio#6583]
### System details

    RStudio Edition : Server
    RStudio Version : 1.3.928
    OS Version      : Ubuntu 18.04
    R Version       : 3.6.3

### Steps to reproduce the problem

 - Install the learnr R package as root into the global library
 - As an unprivileged user, log in to the IDE
 - Attempt to run a tutorial from a package that's installed in the global library

Observe the following error:

<img width="1792" alt="Screen Shot 2020-04-03 at 10 01 53 AM" src="https://user-images.githubusercontent.com/1593639/78369583-ef71d800-75b4-11ea-8c66-dd62042c63b6.png">

### Describe the problem in detail

It appears that the prerendered HTML file can't be written into the global library, so we get an error and the tutorial never opens.

### Describe the behavior you expected

I expected the tutorial to open and run. 

Perhaps we should be copying out these tutorial RMDs into a temp dir or somehow specifying that the resultant HTML should be written somewhere where we're guaranteed to have write access?

**Comment by kevinushey** [comment]
This seems like a bug in `learnr` itself. @schloerke -- does `learnr` always attempt to render the `learnr` document directly in the installed package's folder? If so, I think that needs to check for write permissions and instead copy + run within the R temporary directory (since `learnr` + `learnr`-using packages might be installed into an R library that the running user doesn't have write access to)

**Comment by schloerke** [comment]
😞 `learnr` tries to write where ever the Rmd file is, which is the installed package folder.

**Comment by schloerke** [comment]
Feel free to close here. Have linked an issue in `learnr`

**Comment by kevinushey** [comment]
Thanks!
