### ISSUE TITLE
AGG graphics device backend doesn't reflect par(bg = ...)

### ISSUE THREAD

**Issue by cpsievert** [rstudio/rstudio#6678]
### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 1.4.206
    OS Version      : macOS Mojave 10.14.6
    R Version       : R version 3.6.3 (2020-02-29)

### Steps to reproduce the problem

Set the graphics backend to AGG, then run this code. 

```r
par(bg = "red")
plot(1)
```

### Describe the behavior you expected

The background appears white, but it should be red

**Comment by kevinushey** [comment]
This appears to be true outside of RStudio as well:

```
library(ragg)
ragg::agg_png("plot.png")
par(bg = "red")
plot(1)
dev.off()
system("open plot.png")
```

cc: @thomasp85; is this intentional or am I using `ragg` incorrectly? (Do I need to explicitly pass along `par("bg")` when calling `ragg::agg_png()`?)

**Comment by thomasp85** [comment]
hmm... I can see that the other devices behaves like that so I'll begrudgingly try to fix this in ragg... `par()` is a base graphics function so it shouldn't really be something the devices should care about IMO, i.e. setting `par(bg = "red")` should make base graphic draw a red rectangle first rather than assume something by the graphic device... @pmur002 any comments as to why this approach have been taken?

**Comment by thomasp85** [comment]
OK, I can see that `par()` communicates with the device in a non-documented way. @pmur002 it should probably be added to the newPage documentation in `GraphicDevices.h` how it is expected to behave

**Comment by thomasp85** [comment]
this is fixed in ragg now. I expected to release a new version next week so this can be closed

**Comment by cpsievert** [comment]
Great, thanks, can confirm this is fixed

**Comment by pmur002** [comment]
Thanks Thomas.  I have added a comment in GraphicsDevices.h (in a branch I am making other changes on).
