### ISSUE TITLE
Package installer pop-up doesn't install package

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#6762]
**Steps to reproduce:**
* Write some script that would require an R package that is not installed.
* When the pop-up saying it's required but not installed shows up, take the option to install it.

**Expected behavior:** should install the package by issuing the appropriate command in the console or through some internal RStudio pop-up.

**Actual behavior:** does nothing.

**Setup:** RStudio 1.3.947, running on debian linux.

![doesnt_install](https://user-images.githubusercontent.com/11860098/80524956-2b704100-8999-11ea-8e93-47735fc40e6d.gif)

**Comment by jmcphers** [comment]
I could not reproduce this. Does it work for you in RStudio 1.2? Can you include a diagnostics report? (mostly interested in any errors in your session logs)

**Comment by david-cortes** [comment]
Attached is the session log.
[rsession-david.log](https://github.com/rstudio/rstudio/files/4547928/rsession-david.log)

**Comment by jmcphers** [comment]
Yes, that definitely has the problem!

```
28 Apr 2020 18:55:26 [rsession-david] ERROR CLIENT EXCEPTION (rsession-david): (TypeError) : Cannot read property 'lastIndexOf' of null;
org/rstudio/studio/client/common/FilePathUtils.java#22::friendlyFileName
org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetWidget.java#910::lambda$13
org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetWidget.java#910::execute
org/rstudio/core/client/widget/InfoBar.java#139::execute
org/rstudio/core/client/widget/InfoBar.java#185::onClick
com/google/gwt/event/dom/client/ClickEvent.java#55::dispatch
com/google/web/bindery/event/shared/SimpleEventBus.java#173::doFire
com/google/gwt/event/shared/HandlerManager.java#117::fireEvent
com/google/gwt/user/client/ui/Widget.java#127::fireEvent
com/google/gwt/user/client/ui/Widget.java#127::fireEvent
com/google/gwt/event/dom/client/DomEvent.java#110::fireNativeEvent
com/google/gwt/user/client/ui/Widget.java#163::onBrowserEvent
com/google/gwt/user/client/ui/Widget.java#163::onBrowserEvent
com/google/gwt/user/client/DOM.java#1432::dispatchEvent
com/google/gwt/user/client/impl/DOMImplStandard.java#312::dispatchEvent
com/google/gwt/core/client/impl/Impl.java#306::apply
com/google/gwt/core/client/impl/Impl.java#345::entry0
rstudio-0.js#-1::eval
Client-ID: 33e600bb-c1b1-46bf-b562-ab5cba070b0e
User-Agent: Mozilla/5.0 (X11  Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.6 Chrome/69.0.3497.128 Safari/537.36
```

**Comment by jmcphers** [comment]
Looking at your GIF and the error, it looks like the problem is that the buffer is not saved. We will fix this for unsaved buffers, but in the meantime if you save the file everything should do what you expect. Thanks for filing this!

**Comment by R-Hannibal** [comment]
Hey @david-cortes, thanks again for finding and reporting this issue. We have a fix in place in our latest preview build (available [HERE](https://rstudio.com/products/rstudio/download/preview/)).

If you get the chance will you let us know if the issue is resolved for you in that build?

**Comment by david-cortes** [comment]
> Hey @david-cortes, thanks again for finding and reporting this issue. We have a fix in place in our latest preview build (available [HERE](https://rstudio.com/products/rstudio/download/preview/)).
> 
> If you get the chance will you let us know if the issue is resolved for you in that build?

I don't get those pop-ups anymore in the latest version.

**Comment by dfalty** [comment]
Hey, @david-cortes does the popup show up for you when you exit and reopen RStudio? I think this is the only way it shows up for me and how it worked in previous versions as well. 

I was able to verify I can actually use the install button in unsaved files with the following steps.

1. Create a new R script but don't save
2. Put in library(<uninstalled package>)
3. Close RStudio
4. Reopen RStudio
5. Observe popup "Package <uninstalled package> required but is not installed"
6. Select Install
7. Package installs! ![image](https://user-images.githubusercontent.com/15237845/84972328-3d8e7600-b0e4-11ea-9e3a-00ab91872478.png)

@jmcphers I'm assuming this shouldn't appear on the fly because that's how it works with saved files as well right?

**Comment by jmcphers** [comment]
That's correct, this check happens when you open a file -- we don't run it constantly while you're editing.

**Comment by david-cortes** [comment]
I don't get it on a fresh RStudio restart either.

**Comment by kevinushey** [comment]
What repositories do you currently have configured? The popup will only appear if:

1. The package appears to be used in that source file,
2. The package is not currently installed,
2. That package is available on your active CRAN repositories (specified in `getOption("repos")`).

**Comment by david-cortes** [comment]
Oh just realized the package I was testing with got recently archived - now I tried with some random packages from CRAN and the pop-up indeed shows up and installs them.

Is this behavior about only showing the pop-up from configured repositories something new? I recall it also used to show non-CRAN packages without having configured more sources.

**Comment by R-Hannibal** [comment]
Hey @david-cortes, I consulted with the development team and the consensus seems to be that the IDE (at least currently) is supposed to only prompt a package installation from configured repositories (ie: if `available.packages()` tells us it exists).

If you can provide a reproducible example of this working for non-configured sources in an older version of RStudio we can definitely re-open this issue and take another look. Otherwise it could be an enhancement request that we look to address in a future build.

Thank you again for raising this issue and helping us to improve the IDE.
