### ISSUE TITLE
checking for required function arguments with grave symbol (`)

### ISSUE THREAD

**Issue by d-morrison** [rstudio/rstudio#6886]
The following code runs as expected in the console, but is marked as an error by the RStudio editor:

```
phi = function(`arg 1`) t^2
phi(`arg 1` = 1)
```

When hovering over the red error annotation, the pop-up is:
> argument '\`arg 1\`' is missing, with no default
> unmatched arguments: `arg 1`

It appears that the editor does not detect that \`arg 1\` in the function call is a match for the argument in the function definition.

Obviously not a critical issue; just wanted to add it to the list. Thanks!

**Comment by kevinushey** [comment]
Thanks for the bug report! I think the issue here is that the backticks are not being stripped from the argument name when performing the argument check diagnostic.

Note that the issue goes away if you remove the `phi` function definition, after executing it so the definition does exist in the session.

**Comment by kfeinauer** [comment]
Verified fixed 1.4.990 - no error shows up for this code in the source editor.
