### ISSUE TITLE
feature to delete, rename, saveRDS objects from Environment pane

### ISSUE THREAD

**Issue by james-ferguson** [rstudio/rstudio#6896]
**Use case** 
Hi - I often find myself rm() ' ing stuff from my global environment in the IDE just to keep what I am working on in view and I guess reduce memory. Occasionally a rename action or saveRDS would be handy too.

**Possible Solution**
1. Add check boxes to Environment pane (similar to Files Packages & Plots Panes)
2. Add actions for selected objects - ;

- delete, 
- rename, 
- saveRDS to wd with default file name from object name,
- other ??

BTW Thanks - **it is indeed a great product!**

**Comment by jmcphers** [comment]
If you switch the view from List to Grid you can indeed delete individual objects:

![image](https://user-images.githubusercontent.com/470418/82232097-f9d8fe80-98e2-11ea-9580-06865912bbe1.png)

**Comment by james-ferguson** [comment]
@jmcphers - Now that is a thing of beauty - I guess I should read the .. manual ;)

**Comment by james-ferguson** [comment]
I guess the additional action srename / saveRDS (with default filename) could be useful.
Happy if you wish to close or not @jmcphers

**Comment by jmcphers** [comment]
I think the real bug here is that there are two views for the Environment pane. We did this because each view has some distinct advantages that were difficult to reconcile into a single view, but in retrospect a compromise would have been better than making two different views. 

I'll go ahead and close this, but I bet https://github.com/rstudio/rstudio/issues/6507 would appreciate an upvote and your thoughts.
