### ISSUE TITLE
Feature request: option to assign a shortcut to toggle panes maximization (NOT zoom)

### ISSUE THREAD

**Issue by almeidaxan** [rstudio/rstudio#7022]
I usually keep my console on the top-right pane and plots on the bottom-right pane. Quite often while coding I'm also plotting and, thus, the console pane gets resized by the plot pane. Whenever I need to type some more code into the console I feel more comfortable if its not resized; hence, I maximize the console pane by clicking on the top-right "Maximize pane" button (see screenshot below).

![Screenshot (19)_LI](https://user-images.githubusercontent.com/4544059/83534815-add3af80-a4c7-11ea-9b68-26eb9a8087ea.jpg)

However, switching my hand from the keyboard to the mouse usually tends to slow down the coding workflow. Thus, what I would like to request is an option to assign the "Maximize pane" button to a keyboard shortcut.

Please note that the "Maximize pane" button behavior is _different_ than the (already available) "Zoom pane", which can be executed through the shortcuts Ctrl/Cmd+Shift+(0,1,2,3...). I'm interested in vertically maximizing the pane, _not_ zooming into it.

**Comment by ronblum** [comment]
@almeidaxan Good idea—and there's a shortcut option already for it! It's not assigned, though, so you need to pick one yourself. Go to
* Tools -> Modify Keyboard Shortcuts -> Maximize Console

and enter a shortcut of your choice. Just make sure that it doesn't conflict with an existing one. I just tried it out with <kbd>ctrl-R</kbd> and it worked with it.

**Comment by almeidaxan** [comment]
@ronblum Thanks for the heads up!

I know that my use case was specific to the console, but It would also be nice to have the same shortcut option to other panes, such as Source.

Also, a **toggle** would be handier than a maximize-only option. (I've edited the issue title to reflect this).

Could you please reopen this issue?

**Comment by gtritchie** [comment]
This is closely related to #6225, let's track it via that issue. Once the IDE has a firm concept of "current pane" then we can create commands such as this without needing separate ones for each pane. Thanks!

**Comment by gtritchie** [comment]
Still an issue, and still getting requests, e.g.:

https://community.rstudio.com/t/maximize-or-minimize-a-pane-vertically/180930

To recap, we have a "Maximize console" command which can be assigned a keyboard shortcut, but no "minimize console" or "restore console". The same is true for the other regions ("Tabset1", "Tabset2").

Keyboard users would like a way to trigger these operations without reaching for the mouse, so making them commands would provide that option.

I had talked earlier about having a command that operated on the currently focused pane instead of being region-specific, but that would not be possible for a minimize pane (can't have focus on a minimized pane) so having region-specific commands would still be necessary.

**Comment by gtritchie** [comment]
This would be an inexpensive change that would be a nice productivity gain for keyboard users. Also marking it as accessibility since these operations are currently extremely difficult to operate for a keyboard-only user (getting focus on the existing min/max/restore widgets is possible but extremely painful).

**Comment by kevinushey** [comment]
Verified in 2024.04.0 Build 624 on Windows.

**Comment by Dusk1087** [comment]
I've seen similar threads about pane resizing in RStudio, but haven't found a clear solution:

Is there a keyboard shortcut that replicates the functionality of the two vertical maximize/minimize buttons at the top-right of each pane? I'm not looking for the shortcut that fully maximizes the pane (Ctrl + Shift + 1 or Cmd + Shift + 1), but rather the shortcut that vertically expands or collapses the pane, exactly like clicking those buttons.

Thanks for the help!
