### ISSUE TITLE
Tab-trap in visual editor mode

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#7089]
### System details

    RStudio Edition : Server
    RStudio Version : 1.4.453
    OS Version      : any
    R Version       : any

### Steps to reproduce the problem
- enable RMD visual editor and open an RMD file
- ensure keyboard focus in editor via <kbd>Ctrl+1</kbd>
- hit Tab key, nothing happens (maybe that's by-design, not sure)
- toggle the "Tab Key Always Moves Focus" accessibility option <kbd>Alt+Shift+[</kbd> on Windows/Linux, <kbd>Ctrl+Opt+[</kbd> on Mac
- try to Tab or Shift+Tab out of the editor

### Describe the problem in detail
- nothing happens

### Describe the behavior you expected
- keyboard focus should to go next/previous focusable item in DOM
- example use might be to get to the editor toolbar quickly via Shift+Tab to use it via keyboard
- note you can see the state of this setting via Help / Accessibility / Focus menu (checkbox)

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jjallaire** [comment]
Yes, tab is currently ignored by default (https://github.com/rstudio/rstudio/blob/master/src/gwt/panmirror/src/editor/src/api/basekeys.ts#L70-L72). We did this because when hosting codemirror instances in the editor the tab key would advance to the codemirror instance, which was quite surprising.

Perhaps though we should do this:

1) Remote any tabindex set by default for codemirror (as they are plenty of other ways to navigate to it w/ the keyboard and tab seems "wrong" to jump around to different regions in the editor).

2) Consider what tab should do by default and/or when the  "Tab Key Always Moves Focus" option is toggled. 

There are some other uses of tab in the editor (indenting list items, moving between table cells) and it does seem surprising when tab switches focus out of the editor. Would it be sufficient to only make it move move focus when that option is toggled?
