### ISSUE TITLE
Ace license in NOTICE is wrong

### ISSUE THREAD

**Issue by dcermak** [rstudio/rstudio#7102]
The following line in NOTICE is wrong:
https://github.com/rstudio/rstudio/blob/16f646a33180117ba1b0582ac3cb8e3563c917f2/NOTICE#L7

Ace is actually licensed under the BSD-3-Clause license: https://github.com/ajaxorg/ace/blob/master/LICENSE

**Comment by kevinushey** [comment]
Thank you for spotting this!

For context, Ace was initially licensed as LGPL when it was first released, and RStudio took a dependency on Ace quite early on:

https://github.com/ajaxorg/ace/commit/6f8f346e408d0f9afb879e085452cc11d49ba314#diff-9879d6db96fd29134fc802214163b95a

But we do of course need to update this as Ace has since updated their license.

**Comment by R-Hannibal** [comment]
@dcermak, thanks again for finding and reporting this issue. 

We have a fix in place in our latest preview build (available [HERE](https://rstudio.com/products/rstudio/download/preview/)). If you get the chance will you let us know if the issue is resolved for you in that build?

**Comment by dcermak** [comment]
@R-Hannibal Thanks for fixing this, however this was more of an FYI issue for the RStudio team. I already fixed the license in the build recipe for openSUSE.

**Comment by dfalty** [comment]
Verified fixed 1.3.1033
