### ISSUE TITLE
RMarkdown documents do not display `iframe`s

### ISSUE THREAD

**Issue by schloerke** [rstudio/rstudio#7104]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.959
    OS Version      : macOS 10.15.5
    R Version       : 4.0.0

### Steps to reproduce the problem

Originally reported on community: https://community.rstudio.com/t/using-existing-shiny-apps-inside-a-learnr-tutorial/69398/3?u=barret

File:
````r
---
title: "iframe is not displaying in IDE"
output: html_document
---

... but does display in Chrome.

```{r}
knitr::include_app("https://gallery.shinyapps.io/001-hello/", height = "500px")
```
````

* Click button "Run Document"

### Describe the problem in detail

The iframe is blank / is not loading.  (There are no JS console errors.)

<img width="1292" alt="Screen Shot 2020-06-11 at 12 13 16 PM" src="https://user-images.githubusercontent.com/93231/84412298-09472100-abdd-11ea-9574-ec6637ab12af.png">

### Describe the behavior you expected

The iframe should display its contents.

Chrome Screenshot:
<img width="1043" alt="Screen Shot 2020-06-11 at 12 13 30 PM" src="https://user-images.githubusercontent.com/93231/84412339-1bc15a80-abdd-11ea-928f-6d86b639c87f.png">

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Note that this is also true in previous releases of RStudio, and so at least isn't a regression.

My recollection is that we explicitly restrict which external URLs we allow one to view within IDE windows, primarily as a security measure. We could consider whether we could relax this for appropriately-sandboxed `iframe`s, though.

**Comment by jmcphers** [comment]
Yes, this behavior is intentional, and it would be difficult to change without security risks. 

We cannot completely sandbox the Viewer pane when an R Markdown document is loaded (as we would for an external URL), since the IDE needs to interact with the document.

Nor is it possible for us to introspect the `iframe` in the R Markdown document to see if it has the correct sandbox attributes. We could do something very complicated like scan the document for iframes and with appropriate sandboxes prior to loading it in the viewer pane to build a whitelist, and/or filtering the HTML for the document to rewrite it with sandboxes, but all probably more work than is warranted. 

See also https://github.com/rstudio/rstudio/issues/2252.

**Comment by chrisaberson** [comment]
I submitted the original issue. If I'm reading this correctly, the response is "you can't do that" - this seems to limit the capabilities of learnr, a package that 1000s of faculty are turning to for teaching online. Additionally, it suggests that a lot of the documentation (e.g., the bookdown documentation) suggests functionality that isn't actually available to users. 

If this issue goes unresolved, I would hope that the various documentation updates to reflect that commands such as knitr::include_app don't actually work under many conditions so that users don't spend countless hours trying to use these approaches.

**Comment by schloerke** [comment]
To add a partial solution for future readers... Even if the tutorial is being run by the IDE, the document can still be viewed with "Open in Browser" and the iframes will appear.

**Comment by yasineahmed** [comment]
### Iframe does not work in Rstudio 1.4.1.093. 
Tried in Chrome and intranet. 
```
RStudio Edition : Desktop
RStudio Version : 1.4.1.093
Running under: Windows 10 x64 
R Version       : 3.6.2 
kniter: 1.3
Rmarkdown: 2.5
```

`knitr::include_url("https://www.youtube.com/embed/wvfI7yGZAHc",height="500px")`

Also tried

`<iframe width="560" height="315" src="https://www.youtube.com/embed/wvfI7yGZAHc" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>`

![image](https://user-images.githubusercontent.com/34150701/103669100-c5c35400-4f2c-11eb-90be-0ba8db02fcbc.png)
