### ISSUE TITLE
improve handling around editing of `$$` boundaries

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#7107]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.458
    OS Version      : macOS 10.15.5
    R Version       : 4.0.1

### Steps to reproduce the problem

Within visual mode, create a Latex chunk with e.g.

`````
$$
\sum_{i=1}^nX_i
$$
`````

Then, try to modify the `$` chunk boundaries (e.g. by deleting a character). Then re-apply the `$`.

### Describe the problem in detail

The chunk boundaries are no longer highlighted as a single token. See e.g.

<img width="145" alt="Screen Shot 2020-06-11 at 1 34 52 PM" src="https://user-images.githubusercontent.com/1976582/84436486-62688200-abe8-11ea-97dc-f055757b4793.png">

You can also get in an awkward state where inner `$`s are tokenized as part of the Latex expression, instead of the bounds.

<img width="158" alt="Screen Shot 2020-06-11 at 1 36 24 PM" src="https://user-images.githubusercontent.com/1976582/84436610-99d72e80-abe8-11ea-99d3-c612aa09a3f0.png">

### Describe the behavior you expected

The chunk boundaries should be highlighted as a single token, and we should be robust to these edits of the chunk boundaries.

(Or perhaps these should get a similar "chunk" treatment as code chunks already do get?)

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jjallaire** [comment]
This gets into one of the toughest issues for the editor: we want to allow certain special character sequences to automatically create "richer" objects. For example, `$...$` should create inline math, `[@cite]` should create a citation, `\@ref(fig:foo)` should create a cross-reference. 

While we have menu items / commands for inserting these objects, we also want plain typing to work (as they are arguably much easier to just type in as opposed to using a command). At the same time, we don't want to force the concept of "escaping" special characters onto visual editor users (it's hard enough for source users to get this right!). i.e. we don't want to require `\$` or even `\\` to escape an escape character). I tried this out at the beginning and it created untold complexities/problems at the implementation level (not even to speak of the user level).

The answer to this is the use of input rules, which are automatic transformations that are *reversible* by the user via backspace or undo. For example:

![Jun-12-2020 07-08-31](https://user-images.githubusercontent.com/104391/84496810-9d67c580-ac7b-11ea-9539-0372d1c0f8be.gif)

Note that if the user actually wants literal "$y=5$" in their document they can just enter it and then press backspace to reverse the input rule. This is considered superior to introducing escaping and requiring e.g. "\\$y=5\\$". 

The other thing we do with these sorts of marks is constantly scan for changes that "break" them (meaning they no longer conform to the required pandoc syntax) and in that case remove the mark. That is what you are seeing in the editor when you play with the mark boundary. This behavior is in fact "correct" in that pandoc will no longer consider that block to be display math so the highlighting reflects that. 

It looks like in this case though we aren't repairing the mark when you re-insert a $ after breaking it. This is likely due to to our input rules not catching that "gesture". It *might* be tricky to get this right though, as the input rules around math are somewhat complex (thus whack-a-mole w/ failure modes). We generally do better with repairing inline math (in fact we might not even have any logic for repairing display math?)

The longer term plan for math is to actually render it fully inline and have a popup Ace editor for editing that actual LaTeX (at which point this issue will disappear, b/c display math at that point will be a richer object that can't have it's delimiters directly edited. 

cc @jcheng5

**Comment by jjallaire** [comment]
PR for a potential resolution here: https://github.com/rstudio/rstudio/pull/7111

**Comment by jjallaire** [comment]
Fixed in https://github.com/rstudio/rstudio/pull/7111
