### ISSUE TITLE
UTF-8 encoding for Vietnames language

### ISSUE THREAD

**Issue by ntluong95** [rstudio/rstudio#7210]
Hello everyone,

One more issues I found quite nuisance is that Rstudio did not display Vietnamese well. Some are well-displayed but some are not. Could you fix this bug?
![image](https://user-images.githubusercontent.com/63569637/85587595-1dbefb00-b66c-11ea-91cd-c13c569694f7.png)

Thank you

**Comment by ronblum** [comment]
@ntluong95 Thank you for raising the issue! We'll review it as we continue development of RStudio.

Also, could you please provide the following information so that we can try to reproduce it?

1. The text that should appear? It'll hopefully save and show up correctly here, in GitHub.
2. The system details for the stack you're working with:

    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       :

**Comment by ntluong95** [comment]
Dear @ronblum,
Thank you for answering me. As far as I know, Rstudio can display Vietnamese well for those special letters: ă, â, ê, ư, ơ but when those letter combine with the accent mark such as ắ, ặ, ằ, ẳ, ế, ờ, etc. they will display as above. For more detail about Vietnamese letter, you can take a look here: http://vietunicode.sourceforge.net/charset/
You can search, for example: "U+1EBF" and the right letter should be in the first column
![image](https://user-images.githubusercontent.com/63569637/85646129-9aca8e80-b6c5-11ea-8c5c-6b8125a48eeb.png)

My system detail
R version: 4.0
OS version: Window 10
Rstudio version: 1.4.506

**Comment by ronblum** [comment]
@ntluong95 Thank you! We've run into encoding issues in the past, and unfortunately, as we fix some, we learn about more. Do you see the issue in 1.3, either [the current release (1.3.959 Middlemist Red)](https://rstudio.com/products/rstudio/download/#download) or [the latest preview](https://rstudio.com/products/rstudio/download/preview/)?

**Comment by ntluong95** [comment]
@ronblum I faced this issues at any version of Rstudio and hopefully Rstudio can fix it to bring better experience for Vietnamese users. Thank you

**Comment by ntluong95** [comment]
Hi @ronblum I hope that the Rstudio team can fix it soon

**Comment by mikebessuille** [comment]
@ntluong95, can you please check if you see the same behaviour in R gui?   And post a screenshot?  Thank you!

**Comment by ntluong95** [comment]
Hello, I did try with RGui and Rstudio, it's the same error (please see the picture attached)
![1](https://user-images.githubusercontent.com/63569637/98590103-94ccf700-22ce-11eb-84e8-b3702c67c933.png)
![2](https://user-images.githubusercontent.com/63569637/98590105-95fe2400-22ce-11eb-9e8b-87902b502098.png)

What is your system language set to in Windows? --> I dont know. How to check that? I think is Vietnamese
![3](https://user-images.githubusercontent.com/63569637/98590212-c47bff00-22ce-11eb-9438-1069e3cd6dd8.png)

**Comment by kevinushey** [comment]
This is unfortunately a more general issue with R on Windows: many functions will attempt to convert strings to the native encoding (especially for formatting), and those attempts will often fail if they cannot be represented in the native encoding.

For general issues of this form (in terms of how output is formatted / displayed), there isn't much we can do. There is hope that this will change in a future build of R:

https://developer.r-project.org/Blog/public/2020/07/30/windows/utf-8-build-of-r-and-cran-packages/index.html

but for now this issue is out of our control.
