### ISSUE TITLE
Rainbow colors could use some tweaks

### ISSUE THREAD

**Issue by adamconroy** [rstudio/rstudio#7213]
It'll be worth the time to get nice colors across all of our default themes. Light and Dark is ok for now but just breaks on some themes (like solarized warm, cobalt). Also pick ascending colors that alternate to keep contrast high and don't just iterate through the rainbow.

Consider using something like `scales::show_col(colorspace::rainbow_hcl(7))` to generate color pallets.

**Comment by EllaKaye** [comment]
Hello. This is a super feature. Thanks for implementing. I agree about the suggested tweaks. I use solarized light theme and the current rainbow choice is pretty jarring on that, especially the bright green. Using `colorspace` hcl palettes would be great to ensure all colours have the same weight. FWIW, my vote would be for `colorspace::swatchplot(colorspace::qualitative_hcl(n = 7, palette = "set2"))` - just a smidge brighter than the set from `rainbow_hcl`, but there's not much in it!

**Comment by EllaKaye** [comment]
Hello again. I've been thinking about @adamconroy comment about alternating colours to keep contrast high. FWIW, it might be good to keep them sequential. Since brackets are nested, having the coloured parentheses in an easily recognised order might help give a quick sense of how deep into the nest you are.

Also, I'm not sure if this is the right place to be making these comments. Is this a space for RStudio developers or is it acceptable for members of the community to make comments here? Apologies if I'm in the wrong place.

**Comment by jmcphers** [comment]
Yes, we welcome community feedback here!

There's a tension between optimizing contrast and making the ordering obvious (it is probably not possible to do both well). One thing you might try is experimenting with the CSS classes that define the colors to see what works best for you; since these are CSS themeable you can just include the `.ace_paren_color_0`, `.ace_paren_color_1`, etc. classes in a custom `.rstheme` file (look for our article on creating custom themes) to set up the colors as you prefer.

**Comment by EllaKaye** [comment]
Thanks for the welcome! 

I appreciate the tension and that that would be a tough balance to strike. Thanks for the tip about altering them in a custom theme. I'll have a play with that. I'm also looking forward to seeing what you ultimately settle on!

**Comment by ronblum** [comment]
I think this belongs here: in dark themes, the sequence contains <kbd>orange - yellow - green</kbd>. But in light themes, the sequence is <kbd>orange - light green - somewhat darker green</kbd>. If yellow can't be used because it blends with the white background, we should include a different color, since the two greens can be confusing.

**Comment by adamconroy** [comment]
I like the higher contrast colors you recommended @EllaKaye and they work great in both dark and light themes! Check out the linked PR above if you're interested in a preview. After that is merged it will show up in the dailies if you want to use it before 1.4 is released.

**Comment by kevinushey** [comment]
Verified in 1.4.1043.
