### ISSUE TITLE
Auto-complete in Rmd chunk header should space around '='

### ISSUE THREAD

**Issue by francisbarton** [rstudio/rstudio#7261]
In most R/Rmd contexts, using tab to auto-complete a function parameter name will fill in the parameter name followed by ` = ` (equals sign surrounded by spaces). This is in line with the [tidyverse style guide](https://style.tidyverse.org/syntax.html#spacing) and is my own preferred style.

However in an Rmarkdown document, in chunk headers, you can use auto-complete to fill in a parameter such as `include = FALSE`, but the default completion inserts `=` *without spaces*. I think this should match the tidyverse style by default, or at least obey the "insert spaces" RStudio global setting (see below).

"Insert spaces around equals for argument completions" is turned on.
![image](https://user-images.githubusercontent.com/1819920/86353294-eef1e780-bc5e-11ea-8773-2d32f284d246.png)

**Comment by kevinushey** [comment]
This is intentional -- this style is chosen to match the example code used in e.g. https://yihui.org/knitr/options/.

In particular, because all chunk options need to be contained on a single line (which can become long), saving space by omitting whitespace around `=` is a reasonable compromise here.
