### ISSUE TITLE
FR: allow option to delete workspace before rebuilding package

### ISSUE THREAD

**Issue by floswald** [rstudio/rstudio#7287]
I have a request that is similar to what was implemented for rserver some time ago [here](https://github.com/rstudio/rstudio/issues/1633). 

my problem is the following:
* i develop a package containing a function that produces large objects as output.
* If i ever forget to `rm(list=ls())` before clicking on *install and reload*, i have to stare for several minutes at my screen while rstudio goes through the cycle of *backing up R session*, and resuming R session etc. 
* I would love a checkbox on the build tools dialogue *delete workspace before rebuilding package* that would call `rm(list=ls())` for me so I don't have to think about it.

**Comment by vh-d** [comment]
+1 vote for this feature
I constantly keep forgetting cleaning environment. I would suggest if that option make the RStudio to skip doing any backup of the session at all.

**Comment by LuisLauM** [comment]
Please, this feature it's totally necessary. It's unbearable to make testing and debugging with a RStudio that takes more than 30 seconds for backing up (some times I have large data sets loaded) and restarting my session.

**Comment by ggordn3r** [comment]
I noticed this issue had been marked stale. Commenting to ensure it remains open. I work with large spatial datasets, so I would also appreciate this feature. Forgetting to remove objects leaves me idle for 30-60 seconds every time I restart R.

**Comment by majazaloznik** [comment]
This issue has still not been addressed, so just commenting to bump it up: it would greatly improve my workflow and seems like a solution should not be too arduous.

**Comment by vh-d** [comment]
I would even go so far and call it is against the principles of reproducibility to reload the environment on rebuild+restart by default.

**Comment by LuisLauM** [comment]
Please, solve this issue, it is not a minor issue at all.

**Comment by cdriveraus** [comment]
yes, please, just an option to disable session backup (in both server and desktop forms), working with large datasets in rstudio is quite a headache...

**Comment by eriqande** [comment]
I agree, this option would be nice.  I found this issue while waiting the 8 minutes it takes to write my environment and then restore it when rebuilding a package.  (I forgot to clear my environment beforehand---i have some large input objects for testing).

It seems to me that RStudio should check the total size of the global environment and then warn the user when it is over some size (like 100 Mb or 1 Gb, or, better yet, some size that is configurable as an option by the user) that will take a long time to write and restore, and ask them if they would rather just empty the environment, or if they would like to cancel the build altogether so the user can selectively remove any large objects.

Otherwise it locks up RStudio, and, in my experience, if you force quit the session, it sometimes leads to inconsistencies/issues that can make RStudio fail upon restarting.  

Thank you all at RStudio for all you do!

**Comment by DesiQuintans** [comment]
I wonder if this should be elevated to something like a bug, or at least unintended behaviour. I have all of the seemingly-relevant options for R backups disabled in my options:

![image](https://github.com/rstudio/rstudio/assets/3200601/2f007d8f-e1fd-45cf-bf8f-283509c1e6e8)

And yet every time I restart the R session with Ctrl + Shift + F10, RStudio still tells me that it is backing up my R session. What is it backing up?

**Comment by kevinushey** [comment]
Internally, RStudio has the notion of a "minimal" save and "full" saves, to be used for different kinds of restarts. We could allow the user to control the type of restart performed after Building and Reloading a package, perhaps via a preference?

https://github.com/rstudio/rstudio/blob/d6b31afcfa51738651a5d0b38ce8457de144ca0a/src/gwt/src/org/rstudio/studio/client/workbench/views/buildtools/BuildPresenter.java#L200-L204

> And yet every time I restart the R session with Ctrl + Shift + F10, RStudio still tells me that it is backing up my R session. What is it backing up?

This is the stuff we do during a restart:

https://github.com/rstudio/rstudio/blob/d6b31afcfa51738651a5d0b38ce8457de144ca0a/src/cpp/r/session/RSessionState.cpp#L481-L521

Note that we only save the global environment if "Save workspace to .RData on exit" is _not_ set to Never, so that shouldn't be running in your case.

https://github.com/rstudio/rstudio/blob/d6b31afcfa51738651a5d0b38ce8457de144ca0a/src/gwt/src/org/rstudio/studio/client/application/ApplicationQuit.java#L490

**Comment by eriqande** [comment]
Thanks for elevating this issue, y'all.

That is interesting to hear you say that they the global environment is not saved on package rebuilding/loading (i.e., in RStudio when you hit the "Install" button in the Build pane of a package project.)  That does not seem to be my experience. (I am using Version 2023.06.0+421 (2023.06.0+421) on an Apple M1 Max laptop running MacOS 12.6.7).

My "Save workspace to .RData on exit" is always set to Never.  However if I open an Rstudio project that is a package and I hit the "Install" button with an empty global environment, it does so quickly, and without any fuss.  If, however, I do something like:

BIG <- runif(1e9)

and then do the "Install" button again, it spends a considerable amount of time backing up and restoring the R session:

![image](https://github.com/rstudio/rstudio/assets/2035238/2f54f5e6-8912-428b-8f66-624e2d481586)

If I delete `BIG` from the global environment, then it no longer takes all that time to backup and restore the R session.  It seems to me like it must be saving and reloading the global environment.

To be sure, I typically really like having my global environment preserved when rebuilding and loading a package I am working on---often I have a lot of variables defined that are useful for debugging or developing sections of code in whatever function I am working on,  but, it is inconvenient when my global env includes so much stuff that it takes a long time to save and reload it. 

As such, an option to globally control the type of restart performed when rebuilding a package might not be as useful (to me, at least) as a feature that warns me when saving and restoring the workspace will take a long time.  I will always want it to restore the global env, _except in cases when the global env is huge and saving and restoring it is going to tie up RStudio for 5 minutes_ (because it might take only 30 seconds to regenerate the variables' values from code).

As always, thank you all at Posit for making RStudio such a fantastic, indispensable product.

**Comment by kevinushey** [comment]
> That is interesting to hear you say that they the global environment is not saved on package rebuilding/loading (i.e., in RStudio when you hit the "Install" button in the Build pane of a package project.) That does not seem to be my experience. (I am using Version 2023.06.0+421 (2023.06.0+421) on an Apple M1 Max laptop running MacOS 12.6.7).

Sorry; I wasn't very clear -- a regular R restart (e.g. Session -> Restart R) doesn't restore the R workspace, but a package build and reload does. I think we should either:

1. Make the behavior consistent, so that disabling the "Save workspace on exit" preference also affects the behavior of Install; or
2. Add a separate preference so users can control if the global environment is saved and reloaded after Install.

> To be sure, I typically really like having my global environment preserved when rebuilding and loading a package I am working on---often I have a lot of variables defined that are useful for debugging or developing sections of code in whatever function I am working on, but, it is inconvenient when my global env includes so much stuff that it takes a long time to save and reload it.

And this is the reason why we're thinking carefully about the behavior :-) But your proposal sounds reasonable; e.g. prompt the user if the workspace size is going to be very large.

**Comment by floswald** [comment]
Great, that's exactly in line with what I had in mind from the start. Thanks everyone for keeping the issue alive! :-)

**Comment by vh-d** [comment]
> 2. Add a separate preference so users can control if the global environment is saved and reloaded after Install.

+1 vote for this

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2023.09.0-daily+349 on MacOS 14 that if 
<kbd>Tools -> Global Options -> Packages -> Development -> Save and reload R workspace on build</kbd>
is unchecked, workspaces are no longer saved and loaded. Checked both that
- The message "Backing up R sessions" is gone
- The environment is clear—objects that were created are gone (checked the Environment Pane)

**Comment by isezen** [comment]
Hello,

I just want to report an issue which is very similar this closed one. If this place is not appropriate and you can reproduce the issue, file a new issue or let me do it. First of all:

1. I unchecked `Options -> General -> Restore .RData into workspace at startup`.
2. I set `Options -> General -> Save workspace to .RData on exit: Never`.
3. I unchecked `Tools -> Global Options -> Packages -> Development -> Save and reload R workspace on build`.
4. `^data-raw$` directory is also excluded in `.Rbuildignore`.

# Issue:
* If I have a big csv file (~5GiB) in the `data-raw` directory, Environment pane experience a relatively long-run refresh even if it is empty.
* It does not matter even if the big file is in a sub-directory of data-raw folder.
* **Workaround:** It only makes difference if I put the big files in another directory and add a symlink in data-raw to the directory.

```
R version 4.3.2 (2023-10-31)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Sonoma 14.2.1

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.11.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: Europe/Istanbul
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] lubridate_1.9.3  rpbl_0.1.0       lattice_0.22-5   xts_0.13.1       zoo_1.8-12       colorout_1.3-0.1 lintr_3.1.1     
[8] rshorts_0.1.0   

loaded via a namespace (and not attached):
 [1] utf8_1.2.4         generics_0.1.3     rwind_0.0.0.9000   xml2_1.3.6         KernSmooth_2.23-22 stringi_1.8.3     
 [7] inum_1.0-5         magrittr_2.0.3     RColorBrewer_1.1-3 grid_4.3.2         timechange_0.2.0   pkgload_1.3.3     
[13] mvtnorm_1.2-4      plyr_1.8.9         Matrix_1.6-4       processx_3.8.3     backports_1.4.1    reshape_0.8.9     
[19] Formula_1.2-5      survival_3.5-7     ps_1.7.5           fansi_1.0.6        lazyeval_0.2.2     cli_3.6.2         
[25] rlang_1.1.2        crayon_1.5.2       splines_4.3.2      remotes_2.4.2.1    withr_2.5.2        tools_4.3.2       
[31] parallel_4.3.2     reshape2_1.4.4     dplyr_1.1.4        prettycode_1.1.0   rpart_4.1.23       vctrs_0.6.5       
[37] cyclocomp_1.1.1    R6_2.5.1           lifecycle_1.0.4    stringr_1.5.1      libcoin_1.0-10     pkgconfig_2.0.3   
[43] partykit_1.2-20    desc_1.4.3         callr_3.7.3        rex_1.2.1          RcppParallel_5.1.7 pillar_1.9.0      
[49] rsconnect_1.2.0    data.table_1.14.10 glue_1.6.2         Rcpp_1.0.11        tidyselect_1.2.0   tibble_3.2.1      
[55] rstudioapi_0.15.0  compiler_4.3.2     gridBase_0.4-7 
```

**Comment by ronblum** [comment]
@isezen Thank you for raising this! Can you open a new issue for it, and reference this one? Thanks!
