### ISSUE TITLE
rstudioapi::setCursorPosition() no longer scrolls the line into view

### ISSUE THREAD

**Issue by yihui** [rstudio/rstudio#7317]
Today I noticed a change in the behavior of  `rstudioapi::setCursorPosition()` from RStudio 1.2 to 1.3. Previously it would scroll the line in the source editor into view, and now it won't. Reprex:

```r
f = tempfile(fileext = '.R')
writeLines(rep('pi', 500), f)
rstudioapi::navigateToFile(f)
Sys.sleep(1)

rstudioapi::setCursorPosition(
  rstudioapi::document_position(100, 1),
  rstudioapi::getSourceEditorContext()$id
)

# file.remove(f)
```

With RStudio 1.2.5042, the editor would be scrolled to the line 100. With 1.3.x, it won't.

**Comment by R-Hannibal** [comment]
@yihui, thanks again for finding and reporting this issue as well as the detailed reprex. 

We have a fix in place in our latest preview build (available [HERE](https://rstudio.com/products/rstudio/download/preview/)). If you get the chance will you let us know if the issue is resolved for you in that build?

**Comment by yihui** [comment]
I can confirm that it has been fixed. Thanks!
