### ISSUE TITLE
No warning is presented to the user when closing the terminal with an active job running, and both the terminal and running job are terminated.

### ISSUE THREAD

**Issue by R-Hannibal** [rstudio/rstudio#7321]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.1056-1
    OS Version      : Windows 10 x64
    R Version       : 4.0.2

### Prerequisite

- Set the terminal in the IDE to Git Bash (Tool > Global Options > Terminal).

### Steps to reproduce the problem

1. Login to the IDE and open a Git Bash terminal.
2. Enter the command `notepad` into the terminal to open a notepad job.
3. Close the terminal.

### Describe the problem in detail
The terminal and the running notepad job are closed without a warning/confirmation dialogue being presented to the user.

### Describe the behavior you expected
A dialogue is presented to the user warning them that the terminal and all currently running jobs will be close is presented to the user as seen in the screenshot below from 1.3.959:

![Close Terminal Dialogue](https://user-images.githubusercontent.com/62304541/87206669-e6895480-c2cf-11ea-9793-71655d8c6110.PNG)

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
This is by design on Windows. We cannot do busy-detection for Windows Terminals due to architectural limitations. We used to support it for Command Prompt and PowerShell, but never for Git-Bash, WSL, or custom.

There was a bug in 1.3.959 which was causing these to be shown as busy, this was fixed in 1.3-water-lily.

Issue: https://github.com/rstudio/rstudio/issues/7112
Fix: https://github.com/rstudio/rstudio/pull/7123

Note the Terminal support article (https://support.rstudio.com/hc/en-us/articles/115010737148-Using-the-RStudio-Terminal#appendixa) says:

> A terminal with child processes is considered busy by RStudio, and will have (busy) next to its name, and the close [x] changes to a stop button. This feature is only available on Mac, Linux, and RStudio Server.

**Comment by gtritchie** [comment]
For accuracy, that issue (#7112) was actually introduced post 1.3.959 as a side effect of fixing the terminal for RTOOLS4.

**Comment by R-Hannibal** [comment]
Closing this issue as Out of Scope.

The documentation linked by @gtritchie seems definitive: busy detection for terminal processes is not intended to be available on Windows, so not seeing that warning appear here is _by design_ or at the very least a known limitation of Windows.

Does seem odd that we're thinking the issue was introduced post-1.3.959 when the incorrect behavior (warning dialogue IS appearing) is reproducible on 1.3.959, but most importantly" current functionality in 1.3.1056-1 is correct behavior.

**Comment by gtritchie** [comment]
> Does seem odd that we're thinking the issue was introduced post-1.3.959 when the incorrect behavior (warning dialogue IS appearing) is reproducible on 1.3.959, but most importantly: current functionality in 1.3.1056-1 is correct behavior.

It is odd (but expected). There were two interrelated issues. Here's the longer story.

The issue introduced after 1.3.959 caused the Git-Bash terminal to *always* show as busy. The cause was me changing the way we launch Git-Bash by using the git-bash launcher which then starts the actual shell as a child process. This was needed to get things working with RTools4 (and was how we should always have done it). The subprocess detection was (technically) correct in showing terminal as always busy since "busy" simply means the executable started as the terminal shell has a running subprocess.

Prior to that, Git-Bash would show busy if you started a Windows desktop application (such as notepad.exe), as you have observed. However, it would not show busy if you started a Posix command, such as `vim` or `sleep 100`. The same is true with WSL.

The intent was always to err on the side of not doing busy-indication on Windows, since it wasn't consistent, so in this latest change I closed the loopholes (e.g. detecting notepad.exe) instead of continuing with the "sometimes it notices it's busy, sometimes it doesn't" behavior.

Still not ideal, would love to make it correctly detect things like `vim`, of course, but haven't ever pulled that off.

**Comment by gtritchie** [comment]
If you think it would be better to have the behavior we had in 1.3.959 and earlier (e.g. notepad.exe from git-bash causes it to be busy) then open an issue to track. I could definitely do that by special-casing git-bash to ignore that launcher process.

In hindsight would have been the more narrowly scoped fix, for sure.
