### ISSUE TITLE
EPIC: Electron

### ISSUE THREAD

**Issue by mikebessuille** [rstudio/rstudio#7389]

**Comment by rstudio-codetree** [comment]
###### do-not-edit-start-codetree-epic-issues

#### Issues in this epic:

Title | Milestone | Assignees | Stage | State
----- | --------- | --------- | ----- | -----
![](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/issue-opened.svg) [Shiny numeric inputs increment twice on arrow click #6953](https://github.com/rstudio/rstudio/issues/6953)  [![](https://codetree.com/small_codetree_logo.png)](https://codetree.com/projects/AK4D/issues/11794509) | v1.5 | N/A | backlog | Open


###### do-not-edit-end-codetree-epic-issues

**Comment by mirh** [comment]
But why? It will only make the program n-times more bloated.

**Comment by gtritchie** [comment]
The desktop RStudio UI has always been implemented in HTML and JavaScript using an embedded Chromium browser to render it (with QtWebEngine). Electron is a much more current, performant, and better maintained form of the same thing. So this isn't a radical change.

**Comment by nowshed-imran** [comment]
I was concerned about the same thing. However, if Qt-Webengine is the core of UI, I suppose it won't matter. It would get better wayland support though ozone layer in Chromium.

**Comment by mirh** [comment]
I'm not pretending to be some experienced developer or anything, but it was my understanding that while QtWebEngine is one of the slimmest rendering engines out there (not last, at least part of the UI is native I guess), electron is one of the most infamously heavy. 
https://medium.com/commitlog/why-i-still-use-vim-67afd76b4db6
https://pkoretic.medium.com/quick-look-electron-vs-qt-qml-app-memory-usage-e8769008534f
I think you are looking forward to at least twice the memory usage, and I cannot imagine cpu time.

**Comment by jmcphers** [comment]
> le QtWebEngine is one of the slimmest rendering engines out there (not last, at least part of the UI is native I guess), electron is one of the most infamously heavy.

You're confusing QtWebEngine with native Qt widgets and QML. QtWebEngine, which we use today, is similar in size, performance, and functionality to Electron, because they are fundamentally the same thing: an embedded version of the Chromium browser. Electron may even be a little faster since this is its entire purpose for existence, whereas QtWebEngine is but one Qt widget among many, for which our "build a whole app" usage is somewhat off-label.

**Comment by mirh** [comment]
Right, sorry. Anyhow, I have yet to see an electron app below 300MB. 
The Rstudio UI takes half of that at the moment. 
I just hope you know what you are doing.

**Comment by nowshed-imran** [comment]
> Part of the Rstudio UI seems actually native AFAICT.
> Anyhow, bloopers of mine aside, my point is that I have yet to see an electron app below 300MB of ram (and I'm being generous).
> The Rstudio UI takes half of that at the moment.
> I just hope you know what you are doing.

I thought so too. Then I wanted to see the whole impact on RAM. Here is my IDE with no extra library loaded with just a simple Rproject loaded. I trust the Devs on this project. They have made an awesome product and definitely knows the  best.
![image](https://user-images.githubusercontent.com/22009014/102695836-1449d080-4254-11eb-97b2-03cc0b2df454.png)

**Comment by mirh** [comment]
Rsession is, well, R.. I omitted it since it's not really the UI and shouldn't change. 
Rstudio on start is only 90MB for me and QtWebEngineProcess is only a single process of 75MB (or 120 and 90, go figure out the right metrics). I guess there's slight differences between linux and windows. 

I hope the speed comparison wasn't being done between the 2 years old chromium version the old Qt 5.12 [ships](https://wiki.qt.io/QtWebEngine/ChromiumVersions), and the latest one that electron is using.

**Comment by stephensrmmartin** [comment]
I am curious - Is the change from qtwebengine to electron certainly going to happen? My main concern is in two domains.

1) In my experience (and others, it seems), electron is a resource hog. With say, slack and signal running; the cumulative memory usage of the two are about 2.5gb of ram. 2.5 gb. Slack alone varies between 480mb to 1gb. Electron has also had some gnarly memory and cpu usage bugs on linux (that were fixed, after a long time of ignoring the issue, if I recall correctly): When using global menus, it would saturate all cores on a CPU, then all the ram (literally, 16gb/16gb of ram, over time). Again, this particular bug was fixed, but it took them several months (iirc) to acknowledge it as their problem. Regardless, even now it is using an enormous amount of memory across the electron processes just to show a webpage. It uses less ram to just visit, e.g., slack in chrom(ium) or firefox via their webpage, than it does to use the electron-powered app.

2) Packaging electron apps is awful. I'm one of a few people who package rstudio-desktop and rstudio-server for arch linux in the AUR. I also once packaged other tools that used electron, or transitioned to using electron. I have since dropped those electron packages, largely because the build process was so poorly documented and difficult, that I couldn't justify the time spent maintaining it. This is *particularly true* when you want to use the *system* electron package, rather than include electron with every single electron app. But this was *still true* even when shipping each package with its own electron libs.

*IF* the rstudio team is indeed set on using electron, rather than qtwebengine or something else, I just humbly request two things. First: Please monitor the resource usage in a fair way - Electron has built quite a reputation for soaking resources, and this is a valid criticism. Especially when you're dealing with in-memory analytics languages, minimal wasted memory usage is extremely important. Second: Please, please make the build system *very* simple and *very* well documented, especially with respect to electron. Please make it dead-simple (and *without* requiring root access and imposing side-effects, as the previous /opt/rstudio-tools approach did), or make it easy to incorporate a system-installation version into it (so that distro maintainers can just list electron as a dependency, and the package maintainer can just include links where appropriate).

I greatly appreciate all that you do; I am just concerned about the use of Electron from a resource perspective, and especially from a packaging perspective.

**Comment by gtritchie** [comment]
@stephensrmmartin Thanks for the detailed explanation of concerns.

Yes, we are proceeding with the move. Possibly in the RStudio 1.5 timeline, possibly a release close after that (depends on other internal factors). Here's some background (my rambling opinions, and certainly appreciate further feedback).
 
## Concern 1
I've done considerable memory benchmarking with a relatively fully functional prototype I created. I did not have to make any changes to any of the "interesting" RStudio code to stand this up.

Note the entire UI (everything inside the main window and satellite windows) is identical; same source code, same runtime, same appearance; ditto for the native rsession code that hosts the R session. Zero code changes necessary.

To be transparent, ran memory tests almost entirely on Windows and Mac, so it's possible there's some other factor on Linux that I'm not aware of, and I will re-run my testing there, soon. Also I haven't done any long-running testing. Not quite ready for that.

Findings: For a standard single-window RStudio IDE instance, the initial memory usage was almost identical between Qt and Electron. Sometimes a bit lower, sometimes a bit higher, but essentially the same. This makes sense, the stacks are almost identical. Qt adds some its own overhead on top of Chromium, Electron adds some similar but different layers.

Startup performance felt (we're talking "one-one-thousand, two-one-thousand level of benchmarking) the same to slightly better with the Electron version, without any optimization or minifying being done. Once I have a more complete (optimized) build I'll run better tests on all of this.

Where Electron does impose additional overhead is when opening multiple "satellite" windows in a single RStudio instance (i.e. popping out editor windows, utility windows like Git, etc.). This is due to Electron using separate Chromium process for each window vs. Qt's model of a single process for all top-level windows within a single application instance (just a lot more threads). The delta wasn't enough to concern us.

I suspect that the only reason QtWebEngine-based applications don't share the reputation for memory hogging is there really aren't any in widespread mainstream use that I'm aware of. Dropbox was using it at one point, but looks like they may have ditched it (or renamed things so I don't recognize it).

## Concern 2
Packaging concerns are reasonable, but Qt has been a nightmare for us in this regard, too. Though I imagine it's a better known nightmare, at least.

It is definitely a goal to simplify how to produce an RStudio desktop build on all platforms. Both for our own internal sanity, and for concerns like you are expressing for repackaging efforts.

It's good to be reminded of scenario where you want the IDE to use system electron vs. bundled. I had not considered that and will add a task for it so we make sure we wire that in and document it.

That said, it may not solve all your existing concerns; most of our energy goes into either native RStudio development environments on Mac/Win/Linux (which assume root access in some cases, as you've seen), or container-based builds (which is what we use for our official builds and will increasingly use even for local development).

## Next steps
For a period of time we will have both (Qt and Electron) desktop builds happening, until we make the final call to switch over and cease the Qt flavor. This allows us flexibility in a variety of ways (including any late-breaking "Oh No!" discoveries).

Until we feel we're functionally complete enough for the many people who download our daily builds and do work with them (despite warnings not to do that), our public daily builds page will only list the Qt flavor, but the Electron build will also be there if you know how to concoct the download link. The master repo will contain both, no private branches. Expect this to start appearing in "master" once the current 1.4 patch release (juliet-rose) is done and released.

Once we switch to linking to the Electron build, instead, we'll continue keeping them both healthy for a period of time until we've gathered some real-world feedback. Then, and only then, will be terminate the Qt builds and (ultimately) delete the unused sources.

Happy to chat more. gary@rstudio.com

**Comment by stephensrmmartin** [comment]
Thanks, Gary.

Just one note about packaging, containers, and root: Arch linux build scripts *cannot* touch root. The build process is, effectively, just a bash script that defines meta-data, build instructions, and packaging instructions. That script is then run with the UID of the user (and in some cases, using fakeroot just for the uid). For this reason, any method that, say, installs to /opt/rstudio-tools is completely dead in the water. This is part of the reason why either that location must be variable at build-time (so that we can specify that directory to be one within the scope of the build directories defined by the PKGBUILD file), or to tweak the scripts (terrible to do, since we have to patch downstream), or to use system-libs (preferable, because it's considerably cheaper, and easy to just link where things need to be). I believe the Rstudio team in the past has accommodated these needs by allowing for system-libs to be used, rather than bundling [for Qt, and for Soci]; and we intervene in the dependency installation by instead soft-linking to system libs (e.g., for pandoc) or downloading them ourselves (e.g., gwt) [/opt/rstudio-tools cannot be used; so we've had to manually intervene to fix that]. 

All this to say - Preferably, the build system can be /self-contained/, and not stomp on anything outside the build directories because it's against policy and best-practices to do so. Building a package /shouldnt/ require modifying root in untrackable ways; we would greatly appreciate any effort to avoid that, especially with regard to electron.

Thanks again for the quick response.

**Comment by gtritchie** [comment]
Broke out into two tracking issues (one for builds w/o root access, one for using system Electron).

**Comment by stragu** [comment]
I just wanted to mention something that hasn't been mentioned in this thread, and that I think should definitely be considered when discussing the the pros and cons of moving to Electron: it has been explained by the RStudio team that the current sub-par support for screen readers is due to the limitations of QtWebEngine, and that moving to Electron will allow making the interface read by this kind of software without producing incomprehensible audio.
So, if we are taking accessibility seriously, and want to make sure everyone can use RStudio regardless of their disability, the move to Electron is very welcome. (And in my opinion, the memory cost is by far eclipsed by the possibility of resolving this limitation.)

**Comment by nowshed-imran** [comment]
> I just wanted to mention something that hasn't been mentioned in this thread, and that I think should definitely be considered when discussing the the pros and cons of moving to Electron: it has been explained by the RStudio team that the current sub-par support for screen readers is due to the limitations of QtWebEngine, and that moving to Electron will allow making the interface read by this kind of software without producing incomprehensible audio.
> So, if we are taking accessibility seriously, and want to make sure everyone can use RStudio regardless of their disability, the move to Electron is very welcome. (And in my opinion, the memory cost is by far eclipsed by the possibility of resolving this limitation.)

I use Linux operating system. The time before electron is bleak to say the least. I don't like electron apps that much but most popular apps support linux just because of electron. I also support this.

**Comment by mikebessuille** [comment]
The accessibility aspect is a primary reason for moving to Electron.  Gary, a senior developer who is leading the electron effort, is also our accessibility expert.   Another key reason for moving to Electron is that we expect it will fix a very large number of bugs that we can't fix using QTWebEngine.

**Comment by stragu** [comment]
Is it already possible to install an experimental Electron build to help with testing?

**Comment by gtritchie** [comment]
Not yet, it's not wired into our builds yet. Hopefully in the next few weeks.

**Comment by gtritchie** [comment]
@netique I'm actively working on it (just returned from a vacation). The first builds will not be feature complete, though many things are already working. Answer is still "next few weeks"; I'll have something else distracting me next week, but we are also looking at getting more resources on this as it's an important change and has been dragging on longer than expected. A software project taking longer than expected, who would have thought such a thing could happen?
