### ISSUE TITLE
Last active tab is not restored when quitting + reloading RStudio

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#7406]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.618
    OS Version      : macOS 10.15.5
    R Version       : 4.0.2

### Steps to reproduce the problem

1. Create a bunch of untitled documents.
2. Select the first (left-most) document tab.
3. Quit RStudio.
4. Open RStudio again.

### Describe the problem in detail

Normally, RStudio should open and show the last-open tab on restart.

### Describe the behavior you expected

RStudio always selects the last tab in the list.

---

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by melissa-barca** [comment]
Just tested this out and it has since been fixed.

**Comment by R-Hannibal** [comment]
Verified Fixed on: RStudio Version - 1.4.747, R Version - 4.0.2, Windows 10 - Desktop 

Unable to reproduce the original issue (issue was already fixed/not reproducible in the oldest available [Daily build](https://dailies.rstudio.com/rstudio/oss/windows/)). However, the issue does appear fixed in the latest Daily (IDE consistently opens to the last Source tab/document that had focus).
