### ISSUE TITLE
Update Resize Splitter commands to account for multiple columns

### ISSUE THREAD

**Issue by melissa-barca** [rstudio/rstudio#7436]
Navigating to View >> Panes gives you the following options to adjust pane splitters: Adjust Left Splitter, Adjust Right Splitter, Adjust Center Splitter. If a user adds additional source columns to their layout, there is no way to adjust the splitter to the left of these columns via the keyboard. Selecting Adjust Center Splitter always adjusts the right most vertical splitter. 

Today selecting the Tab Key after one of these options removes focus from the splitter. I propose changing the name of Adjust Center Splitter to Adjust Vertical Splitters and configuring a keyboard shortcut (possibly `Shift + Tab`?) to switch between the vertical panes, regardless of how many there are.

**Comment by melissa-barca** [comment]
@gtritchie do you have any further thoughts on this?

**Comment by gtritchie** [comment]
## Idea One
Your idea, have a shortcut that moves between vertical splitters (or all splitters?). At first I didn't think this was a good idea because making that shortcut discoverable would be tough. With the current behavior we shouldn't use Tab or Shift+Tab because those are expected to move between focusable elements on the page in DOM order.

There is a draft ARIA model for this, but it brings up more questions than answers especially for our multi-pane layout, here: https://www.w3.org/TR/wai-aria-practices/#windowsplitter

## Idea Two
Extend the current model and dynamically add new menu commands for resizing each existing source column. "Resize source column one", etc.

## Idea Three
Only have a single command for "resize current source column". This command would only be enabled when a source column is selected, and put focus on the vertical splitter on its right. In theory you could have this command show up as a button in each source column's toolbar, though I think that would be overkill. 

Personally, I think "three" is the simplest extension of what we already have. It's all a bit clunky, but at least we provide a way to do this via keyboard which is more than most comparable UIs do.

**Comment by rich-rstudio** [comment]
verified on Version 1.4.752
