### ISSUE TITLE
"No such file or directory" even if I don't want to save the file upon Shiny application launch

### ISSUE THREAD

**Issue by SarenT** [rstudio/rstudio#7521]
### System details

    RStudio Edition : Desktop
    RStudio Version : Version 1.3.1056
    OS Version      : Ubuntu 18.04 LTS
    R Version       : 4.0.2

### Steps to reproduce the problem
1) Open a file from external drive.
2) Do some editing.
3) Remove external drive.
4) Run another local file, which needs to be a **Shiny** application.
5) RStudio will ask to save unsaved files.
6) Uncheck files and/or click Don't Save
### Describe the problem in detail
RStudio is giving the error message box "No such file or directory" even if the files aren't meant to be saved. I work on several scripts at different times and some of them are on external drives. RStudio shouldn't try to access those folders in case of "Don't Save" option.
### Describe the behavior you expected
RStudio should simply close the save dialog without error messages.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@SarenT Thank you for filing the issue! We'll review it as we continue development of RStudio.

Also, I can reproduce the issue on MacOS 10.15.6 with RStudio Desktop 1.4.673 by:
- deleting the file instead of removing the drive; that is, in (1) save the file locally and skip (3) above 
- quitting RStudio, choosing to not save the file, and then not remove it. It causes the R session to abort, forcing a restart, and RStudio doesn't close.

**Comment by kevinushey** [comment]
Just to confirm the repro steps:

1. Create a new project,
2. Create a new Shiny application,
3. Create and open a separate file (e.g. `repro.R`),
4. Edit `repro.R` so that it is "dirty",
5. Return to the new Shiny application, and try to run it via Run App,
6. Click "Don't Save" on the ensuing Save prompt.

**Comment by kevinushey** [comment]
Some investigation. We're getting a server error back here:

![Screen Shot 2020-08-04 at 9 46 36 AM](https://user-images.githubusercontent.com/1976582/89321203-756f5f80-d637-11ea-9201-6a195f938c82.png)

This is ultimately being caused by a failed `revertDocument` RPC:

<img width="1552" alt="Screen Shot 2020-08-04 at 9 48 12 AM" src="https://user-images.githubusercontent.com/1976582/89321289-9f288680-d637-11ea-9071-6531658c08d7.png">

One solution would be to skip the revert attempt in this case, and just leave the RStudio document state as-is.
