### ISSUE TITLE
IDE creates a blank R script when starting / refreshing the session

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#7532]
### System details

    RStudio Edition : Desktop or Server
    RStudio Version : 1.4.680
    OS Version      : any
    R Version       : any

### Steps to reproduce the problem
- (optional) start with a clean state by running rstudio/scripts/clean-rstudio
- start a session

### Describe the problem in detail
- get a blank untitled R script

### Describe the behavior you expected
- in 1.3 and earlier, do not get a blank script when starting the IDE

### Another variation
- in RStudio Server, close the Untitled1 script, then refresh the browser
- creates Untitled1 again

### FYI
- note that the View / Panes / Console on Left | Right commands create an Untitled1 if nothing is open in source panel; this is also true with 1.3 and earlier so we should try to preserve this behavior to stay consistent

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
FWIW, I think we normally _do_ want the IDE to open with a blank document for brand new RStudio installations. The intention is that for a brand new user, if this is the first time they've ever installed and started the IDE, they should have a blank document to work in, in addition to the console. Otherwise, this could lead to user confusion -- e.g.  a brand new user asking "how do I save my work?" without realizing they've been working in the console the whole time, because they didn't have a Source pane.

For subsequent launches, if the user had indeed closed all tabs in their previous session then we should respect that and ensure the next IDE session launches with no tabs (assuming they're opening the same project, attaching to same source database, etc.)

**Comment by jmcphers** [comment]
> I think we normally do want the IDE to open with a blank document for brand new RStudio installations.

See also https://github.com/rstudio/rstudio/issues/4362.

**Comment by melissa-barca** [comment]
What about the case where a user has multiple columns in their prefs file but for whatever reason we can't restore the documents from the previous column for that session? Should we open the column with a blank document, not open the additional column(s) and update the preferences to not include them, or open an empty column (which is otherwise an impossible state to get to)? Here, I think we'd want to open a column with a blank document. 

Any other thoughts?

**Comment by R-Hannibal** [comment]
@melissa-barca - Testing around this issue revealed one very minor regression (or at least change) from 1.3.1073 functionality:

![File preserved on re_launch](https://user-images.githubusercontent.com/62304541/91181122-2b195580-e6ae-11ea-841d-cf3bddf0a7ab.PNG)

The screenshot shows the 1.3.1073 build after re-launching the IDE with an edited unsaved file open and the Source pane 'minimized' (Console pane fully expanded). The Source pane is still present on re-launch, still in a minimized state.

On the latest Daily, performing the same steps, when the IDE is re-launched the Source pane is completely hidden. The file state IS preserved, and as soon as the Source pane is opened (either by reducing Console view or opening a new file) the file can be viewed. But it feels a little confusing that the file is in an open but hidden state after re-launch.

**Comment by kfeinauer** [comment]
Verified fixed 1.4.1069
