### ISSUE TITLE
key press sequence shortcuts of length > 2 key presses do not function

### ISSUE THREAD

**Issue by MilesMcBain** [rstudio/rstudio#7536]
### System details

    RStudio Edition : Desktop
    RStudio Version :  Version 1.4.672
    OS Version      :  Windows 10 1909
    R Version       :  4.0.2

### Steps to reproduce the problem

0. Starting with Keybindings set to 'vim' under Options -> Code -> Editing -> Keybindings.

1. Set a keybinding for 'Move Focus to Console' involving 3 key presses, e.g. `CTRL + M W 2`

![image](https://user-images.githubusercontent.com/9996346/89516173-73fe8c80-d81b-11ea-91e0-84c87435cb66.png)

2. From the source editor attempt to use the keybinding and observe focus does not change to the console.

3. Change the `Move Focus to Console` keybinding to a sequence of length 2, e.g. `CTRL + M 2`

![image](https://user-images.githubusercontent.com/9996346/89516630-0acb4900-d81c-11ea-85a0-77b32ee5a539.png)

4. From the source editor attempt to use the keybinding and observe focus changes to the console.

### Describe the problem in detail

The problem is not limited to vim keybindings mode, it occurs in emacs mode, and default mode as well. 

I also tried for key sequences of length 4 and found they did not work.

### Describe the behavior you expected

I would expect that if RStudio lets me configure a keypress sequence of length 3 as a shortcut, then that shortcut should work. 

It would be really great if sequences of 3 or 4 keypresses could be supported, beyond that is perhaps a bit unlikely to be used.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by MilesMcBain** [comment]
@ronblum I think this is a bug no? You can configure shortcuts that don't work?

**Comment by ronblum** [comment]
@MilesMcBain Good point. I was considering this an enhancement request because I focused too much on the last sentence, that "[i]t would be really great if sequences of 3 or 4 keypresses could be supported." I see, though—you're raising that it's a bug  to allow configuring a keyboard shortcut that won't work. I'll relabel the ticket.

That said, if you would like the IDE to support shortcuts using three or four key presses, can you file a separate enhancement request? Thanks!

-----

Side note: we use the labels "bug" and "enhancement" to triage the issues and help prioritize them., so the distinction is important. So, I'm glad to be corrected. :)
