### ISSUE TITLE
Up-arrow doesn't work when cursor is inside a misspelling

### ISSUE THREAD

**Issue by jcheng5** [rstudio/rstudio#7587]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.710
    OS Version      : macOS 10.14.5
    R Version       : 3.6.1

### Steps to reproduce the problem

1. Open up an Rmd in visual mode with a misspelling further down in the doc
2. Put the cursor in a misspelling (marked with red squiggles)
3. Press Up arrow key

### Describe the problem in detail

The cursor moves to the end of the misspelling instead of up

### Describe the behavior you expected

Cursor moves to previous line

And actually, there is also something wrong with the down arrow (from a cursor position within a misspelling). Sometimes it jumps down by two lines, sometimes it only goes to the end of the misspelled word.

---

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jjallaire** [comment]
This appears to be a contentEditable interaction w/ the fact that the spelling decoration has `display: inline-block`:

https://github.com/rstudio/rstudio/blob/master/src/gwt/panmirror/src/editor/src/editor/styles/styles.css#L237-L239

This in turn we do so that we can provide some extra air underneath the spelling outline. If there isn't another way to provide the air it may be worth tolerating this behavior.

**Comment by jjallaire** [comment]
Fixed via https://github.com/rstudio/rstudio/commit/2697e3963e5940efcb43f132184016833cea6f22 (should be in tomorrow's daily build)
