### ISSUE TITLE
Loading sign-in page over https causes mixed-content / request blocked errors

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#7691]
### System details

    RStudio Edition : Server (using open-source)
    RStudio Version : started with 1.4.514 (998ae9d8)
    OS Version      : Linux (I'm using Centos7, probably doesn't matter)
    R Version       : any

### Steps to reproduce the problem
- Install RStudio Server so it can be reached via https, otherwise a vanilla install
- Load the login page
- Open browser tools / Console

### Describe the problem in detail
- The follow error is logged in devtools console about every 3/4 of a second

`Mixed Content: The page at 'https://***.com/rstudio/auth-sign-in' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://***.com/rstudio/auth-sign-in?appUri=%2F'. This request has been blocked; the content must be served over HTTPS.`

### Describe the behavior you expected
- no such error being logged, presumably by this request also using https

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ricardofandrade** [comment]
It seems to be a proxy misconfiguration that wasn't triggered before because there wasn't a redirect rewrite hitting the configured conditions.

This was nginx configuration before:
```
        proxy_redirect http://localhost:8787/ $scheme://$host/rstudio/;
        proxy_redirect https://localhost:8787/ $scheme://$host/rstudio/;
```

However, `$scheme` would always be `http` instead of `https`.
Possibly, there's another proxy in front of this one, forcing `X-Forwarded-Proto`.
This was confirmed with the `tcpdump` command:
```
$ sudo stdbuf -oL -eL tcpdump -i lo  -A -s 10240 "tcp port 8787 and (((ip[2:2] - ((ip[0]&0xf)<<2)) - ((tcp[12]&0xf0)>>2)) != 0)" | egrep -a --line-buffered ".+(GET |HTTP\/|POST )|^[A-Za-z0-9-]+: " | perl -nle 'BEGIN{$|=1} { s/.*?(GET |HTTP\/[0-9.]* |POST )/\n$1/g; print }'
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on lo, link-type EN10MB (Ethernet), capture size 10240 bytes

HTTP/1.1 200 OK
Content-Encoding: gzip
Expires: Fri, 01 Jan 1990 00:00:00 GMT
Pragma: 

HTTP/1.1 200 OK
Content-Encoding: gzip
Expires: Fri, 01 Jan 1990 00:00:00 GMT
Pragma: 
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Content-Type: application/json
Content-Length: 113
Connection: 
Date: Mon, 31 Aug 2020 21:43:05 GMT
X-Content-Type-Options: nosniff
Server: RStudio

POST /events/get_events HTTP/1.1
X-Forwarded-Proto: http
Connection: close
X-Real-IP: 172.31.20.250
X-Forwarded-For: 172.31.20.250
Host: localhost:8787
Content-Length: 149
X-Forwarded-Port: 443
X-Amzn-Trace-Id: Root=1-5f4d6eea-76173746d9fb7238695d20a0
pragma: no-cache
cache-control: no-cache
accept: application/json
x-rstudio-refresh-auth-creds: 0
x-csrf-token: 6a3cf382-716a-4bf3-a7f0-59bc492630b3
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36
x-rs-rid: -57810341
content-type: application/json
origin: https://access2.soleng.rstudioservices.com
sec-fetch-site: same-origin
sec-fetch-mode: cors
sec-fetch-dest: empty
referer: https://access2.soleng.rstudioservices.com/rstudio/
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9
cookie: port-token=a4c6d1e48a28; csrf-token=6a3cf382-716a-4bf3-a7f0-59bc492630b3; persist-auth=0; user-id=ricardo|Mon%2C%2031%20Aug%202020%2022%3A43%3A01%20GMT|MT%2FNgpCI%2BmCe%2BGhWEvYF27EPNwd6xbIDvucRMtFVDYQ%3D; user-list-id=9c16856330a7400cbbbba228392a5d83|Mon%2C%2031%20Aug%202020%2022%3A43%3A01%20GMT|uKUm%2BBXQvjiuSHJhcxK3oozMFNe7nj%2Fs43%2Fu%2FhBZ3Mo%3D
Content-Encoding: gzip
Expires: Fri, 01 Jan 1990 00:00:00 GMT
Pragma: 
Content-Encoding: gzip
Expires: Fri, 01 Jan 1990 00:00:00 GMT
Pragma: 
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Content-Type: application/json
Content-Length: 113
Connection: 
Date: Mon, 31 Aug 2020 21:43:05 GMT
X-Content-Type-Options: nosniff
Server: RStudio
```

Forcing NGINX to have it's own `X-Forwarded-Proto` set to `https` and rewriting only `https` redirects (also forced to `https`) did the trick:
```
        #proxy_redirect http://localhost:8787/ https://$host/rstudio/;
        proxy_redirect https://localhost:8787/ https://$host/rstudio/;
        proxy_set_header X-Forwarded-Proto https;
```

**Comment by R-Hannibal** [comment]
@ricardofandrade - Is there a linked PR or check-in where this issue was fixed? Or is it 'out of scope'/'by design'?

**Comment by ricardofandrade** [comment]
@R-Hannibal The proxy settings worked before because certain class of redirects would be rare during normal operation.
A new redirect is now triggered by just loading the sign-in page, that was added as part of rstudio/rstudio-pro#1731.
Without the proper proxy configuration the URL returned in the redirect won't match the protocol (http vs. https) causing the browsers to show an error.

In this particular case, there's apparently two proxies involved. The first one does TLS termination (it seems to be a AWS proxy) and the second one (running in the same box as RStudio) does the port translation (80 <> 8787). Because the connection between the proxies is done via http, that's the perceived protocol at RStudio. Therefore, all redirects generated by RStudio will use this protocol. By using `X-Forwarded-Proto https` we indicate that's the actual protocol used to RStudio which in turn will use the proper protocol in redirects. Additionally, the redirects from RStudio will have the host/port of the server itself, instead of the proxy. So the proxy needs to rewrite the redirects looking for the correct protocol (now https), host and port to translate that to the external hostname and port.

Recent changes in rstudio/rstudio-pro#1410 and rstudio/rstudio-pro#1579 also made it easier to diagnose proxy issues and have more options for configure proxies.

**Comment by gtritchie** [comment]
> Is there a linked PR or check-in where this issue was fixed? Or is it 'out of scope'/'by design'?

I think "by design" is most accurate. There were no code changes just a config change.

**Comment by R-Hannibal** [comment]
Adding the 'verified' label.

No code change here, issue marked as by design. Please see the comment trail for more detail.
