### ISSUE TITLE
Align and Justify Buttons

### ISSUE THREAD

**Issue by euriconoleto** [rstudio/rstudio#7700]
It would be awesome to have align and justify buttons similar to MS Word... There are some css ways to do it with html and others... but still no good option for word format...

**Comment by jmcphers** [comment]
This isn't possible right now since R Markdown doesn't provide a way to express these ideas (this is richer formatting than is possible with Markdown itself). This issue belongs in the rmarkdown repo itself since that's where the Word conversion happens (see https://github.com/rstudio/rmarkdown/issues/1801 for an example of how we dealt with a Word specific feature, in this case a page break).
