### ISSUE TITLE
5-6 tab key hits to get focus on filename input box in save file dialog (macOS Big Sur) — possibly a Qt issue

### ISSUE THREAD

**Issue by hrbrmstr** [rstudio/rstudio#7748]
Hey folks,

you know the drill: latest RStudio Daily, latest Big Sur Beta.

This has been happening for quite a a while but I figured the Qt folks might have fixed it by now but it seems not.

90% of the time (yep, it's intermittent, but more deterministically intermittent than some bugs) it takes 5-to-6 tab hits in the save file dialog box to get focus on the filename input box:

![there-are-5-(sometimes 6)-tabs!](https://user-images.githubusercontent.com/509878/92498481-ad366d80-f1c8-11ea-88ba-12ddea314323.gif)

in the above case I just made a new source doc, hit cmd-s, and then hit tab 5 times to get to the input box. it sometimes takes 6. sometimes the focus is on the input box by default.

It's more of a minor annoyance than anything else but figured it should be logged. 

---------

You may want the following in a separate issue, but Qt windows are doing something else odd re: interfacing with the OS Window UI. Note the position of the close/resize buttons in RStudio here:

<img width="129" alt="Screen Shot 2020-09-08 at 11 45 08" src="https://user-images.githubusercontent.com/509878/92498785-09998d00-f1c9-11ea-9b9b-5689065ce089.png">

vs Chromium (or any other "native" app):

![image](https://user-images.githubusercontent.com/509878/92498928-3c438580-f1c9-11ea-9705-e0620b269dd4.png)

It's (again) more of a nit than anything else, but Big Sur is imminent and this rly looks out of place when compared to other apps (though Visual Studio Code and Sublime Text 3 both exhibit the same non-uniform placement, so perhaps this is in the choice of title bar type, but I use the compact version in RSwitch and do not have the way-too-close-to-the-window-edge placement of the buttons).

I'll add that Slack had major UX issues until recently on Big Sur after Slack updated Electron (it, too, had the too-close-buttons thing before that).

I added this nit to the aforepicked-nit since I suspect this is more Qt UI<->Big Sur than it is something you can fix.

**Comment by ronblum** [comment]
@hrbrmstr Thank you as always! I've now installed Big Sur (prodded by this issue), and I can reproduce this on MacOS 11.0 Beta (20A5364e).

**Comment by kevinushey** [comment]
Depending on how this shakes out, we'll probably have to test and see if this is fixed in the latest Qt releases, and if not, consider a patch release soon after Big Sur and Qt are updated.

For what it's worth, I don't see anything filed on the Qt side yet: https://bugreports.qt.io/browse/QTBUG-85546?jql=text%20~%20%22%5C%22big%20sur%5C%22%22

**Comment by gtritchie** [comment]
With Electron RStudio, the focus always starts in the filename input box.  This is on 12.0.1 Monterey, so it's possible behaviour could be different on Big Sur but I don't have that handy.

For the title-bar layout, the visual behaviour (again, on Monterey) seems consistent with other native apps such as TextEdit, so whether that was fixed by Electron or Monterey I can't say.

Marking this as ready for test (via Electron, when official builds become available).

**Comment by ronblum** [comment]
Confirmed on Big Sur, as well. Note that the first time, the down arrow on the "Where" row needs to be clicked so that the full dialog, including the directories. Then test on subsequent "Save" actions.

That is, we want this:
<img width="791" alt="full" src="https://user-images.githubusercontent.com/31009952/161341832-c27c52f2-9a92-45f8-91f2-680b20611d4d.png">

Not just this:
<img width="318" alt="minimal" src="https://user-images.githubusercontent.com/31009952/161341850-7c0a3c1a-ac77-4435-a6af-dadc8bc2886a.png">
