### ISSUE TITLE
RStudio Shiny Package Installation Issue

### ISSUE THREAD

**Issue by staci12** [rstudio/rstudio#7763]
###  System details
    RStudio Edition : Desktop
    RStudio Version : 4.0.2
    OS Version      : Windows

Installation Error occurs when trying to install Shiny package. 

> install.packages("shiny", repos="http://R-Forge.R-project.org")
Installing package into ‘C:/Users/Staci Board/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘shiny’ is not available (for R version 4.0.2)
Warning in install.packages :
  unable to access index for repository http://R-Forge.R-project.org/bin/windows/contrib/4.0:
  cannot open URL 'http://R-Forge.R-project.org/bin/windows/contrib/4.0/PACKAGES'

**Comment by kevinushey** [comment]
Is there a reason why you're attempting to install Shiny from R-Forge? You should prefer using the regular / default CRAN mirror; e.g.

```
install.packages("shiny", repos="http://cran.rstudio.com")
```

Or, more simply,

```
options(repos = c(CRAN = "https://cran.rstudio.com"))
install.packages("shiny")
```

That said, this is ultimately an R rather than an RStudio question so this isn't the appropriate forum for further follow-up -- I'd suggest starting a conversation at https://community.rstudio.com. Thanks!
