### ISSUE TITLE
When attempting to Open a Project on Mac, double-clicking the Documents folder creates a new R Project 'Documents.Rproj'.

### ISSUE THREAD

**Issue by R-Hannibal** [rstudio/rstudio#7764]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.1091
    OS Version      : macOS Catalina 10.15.6
    R Version       : 3.6.3

### Steps to reproduce the problem

1. Launch the IDE and select File > Open Project...
2. Double-click the Documents folder.

### Describe the problem in detail

A new Project is created and opened titled 'Documents.Rproj'. This is a minor issue as once the user realizes what happened they can easily close/delete the spurious project and go open the project they intended to open. But the user experience is a little clunky and confusing for more entry level users.

### Describe the behavior you expected
Only existing .Rproj files can be opened through the 'Open Project...' dialogue window, similarly to the way this works on Windows (on Windows only .Rproj files can be selected for opening, other files/folders do not display as options for opening).

### Notes

- This 'issue' may very well be a 'this is the way this works on Mac' thing and outside of our control.
- Issue is present in current stable (1.3.1073) and current daily (1.4.798) builds.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
This may be intentional. The Open Project dialog explicitly allows you to open a directory as a project, if that project does not contain a `.Rproj` file.

Given that macOS normally uses this a view that doesn't require double-clicking a folder for navigation; e.g.:

<img width="807" alt="Screen Shot 2020-09-10 at 12 23 40 PM" src="https://user-images.githubusercontent.com/1976582/92790245-772bf180-f360-11ea-9059-069b34a9d3bb.png">

I think it is reasonable to treat a double-click on an item as a request to select + use that particular item.

**Comment by R-Hannibal** [comment]
Thanks for the info @kevinushey, that sounds reasonable to me.

Closing this issue as by design.
