### ISSUE TITLE
Using `bookdown::serve_book()` turns off visual editor (v1.4)

### ISSUE THREAD

**Issue by adisarid** [rstudio/rstudio#7958]
### System details

    RStudio Edition : Server
    RStudio Version : 1.4.869
    OS Version      :  Debian 9.13
    R Version       : 3.6.3

### Steps to reproduce the problem

   1. Open a bookdown (either new from template or an existing book).
   2. Open a specific chapter (Rmd file).
   3. Use visual editor to display/edit the chapter.
   4. Run `bookdown::serve_book()` in the console.

The book will render ok, but the visual editor will revert to the regular (classic) editor.

### Describe the problem in detail

This is a really weird issue, every time I use `serve_book` the visual editor reverts back to the classic editor. The bug is not severe as it does not occur on re-rendering of files (i.e., "refreshing" an already served book). I also tried to reproduce the problem with `blogdown` which has a similar approach to serving (blogs) but the bug does not occur in blogdown.

I'm using the current CRAN version of bookdown (0.20)

### Describe the behavior you expected

I expect the book to be served and the Rmd file to remain opened with the visual editor.

**Comment by jjallaire** [comment]
The issue is that in `bookdown::serve_book()` a call for the active document context is made: https://github.com/rstudio/bookdown/blob/cd9a8a55671ddd3183433e4d1fe58f74a1aa4ded/R/utils.R#L350

This is just to get the path to the active file though. @yihui  There is a new `rstudioapi::documentPath()` function which you can use to get the path (which won't have the side effect of switching out of the visual editor). Full docs on this in a new vignette on using rstudioapi in a visual mode friendly way: https://github.com/rstudio/rstudioapi/blob/master/vignettes/visual-mode.Rmd

**Comment by kevinushey** [comment]
This should also "just work" in the latest daily builds where `getSourceEditorContext()` is still able to provide a limited context in visual mode.

**Comment by ronblum** [comment]
Should this be moved over to the bookdown repo?

**Comment by cderv** [comment]
As @kevinushey said, I believe this is now working in last daily build. I tested with 1.4.959 and it works for me. 
@adisarid can you also try on your side ?

**Comment by adisarid** [comment]
Thanks @cderv 
I just installed the daily build 1.4.965 and the issue seems to be resolved.
