### ISSUE TITLE
Data viewer on list-column fails to load dataframe within the tibble

### ISSUE THREAD

**Issue by ahcyip** [rstudio/rstudio#7985]
### System details

$mode
[1] "desktop"

$version
[1] ‘1.3.1093’

OS Version      : Windows 10 enterprise
R Version       : 3.6.2

### Steps to reproduce the problem

1:10 %>% map(~seq(1:.x) %>% as_tibble()) %>% enframe()

Then I try to click on any data frame in the list column and I get:
  > View(.[[2]][[1]])
Error in View : object '.' not found

### Describe the problem in detail

Error in View : object '.' not found

It looks like the Viewer cannot handle temporary objects that were passed into View()?

### Describe the behavior you expected

I expected to see the data frame that is described when I hover over the data frame emoji/symbol.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).

**Comment by ahcyip** [comment]
Looks like this was previously filed #7498

**Comment by ahcyip** [comment]
Not fixed yet in my version, but may be fixed in a newer version in the works?

**Comment by ronblum** [comment]
@ahcyip I think you meant to put this in #7986? In any case, there were several issues that boiled down to the same problem, which got consolidated in #9960. The problem was just fixed in the release that we're working on, Kousa Dogwood. You can see it in the latest daily builds at https://dailies.rstudio.com/rstudio/kousa-dogwood/ . Please note that the dailies are for testing purposes only, not production.
