### ISSUE TITLE
Refresh the current opened page in the viewer pane

### ISSUE THREAD

**Issue by cderv** [rstudio/rstudio#8096]
While working on live reload of document in the viewer with @yihui to try fixing an annoying issue in **blogdown** between RStudio Server and Hugo livereload feature not working together, we [wondered](https://github.com/rstudio/blogdown/issues/486#issuecomment-706225200) if this would be possible to refresh the viewer while staying on the last and current page opened.

Currently, the refresh button will reload the whole website so for **blogdown** for example, it will go back to homepage and not stay on the current blog post one is editing. That means `rstudioapi::executeCommand("viewerRefresh")` will do the same. 

I guess this is because the refresh button will kind of re-run the initial browse command that lead to the homepage.

Having an API to refresh the current served page could help - something like `rstudioapi::viewer(currentUrl = TRUE)` or `rstudioapi::viewer(refresh = TRUE)`. 

Or any other mechanism that would help with reloading a page currently in the viewer.

Is there already a command for that ? Would it be something that could be considered ?

**Comment by kevinushey** [comment]
Closed by https://github.com/rstudio/rstudio/pull/8084.

**Comment by kfeinauer** [comment]
@yihui Could you confirm if this is fixed in the latest version of RStudio?

**Comment by yihui** [comment]
If I understand it correctly, the fix is for RStudio Server only, but I don't have RStudio Server installed on my computer. I wonder if @cderv could verify it.

@cderv You could also verify if the Knit button could refresh the Viewer in RStudio Server if you have the daily build installed. I added this commit to **blogdown** a few days ago: https://github.com/rstudio/blogdown/commit/62b953e4de531ddbe6a59856b04358ce0acd1d62 Thanks!

**Comment by cderv** [comment]
I can confirm this is working on rstudio server with `rstudioapi::executeCommand('viewerRefresh')`

The current opened page is now refreshed. 

**blogdown** now uses that when a document is knitted by the user to refresh the page.
