### ISSUE TITLE
Pandoc dependency usage is not version aware

### ISSUE THREAD

**Issue by adamconroy** [rstudio/rstudio#8111]
### System details

    RStudio Edition : Desktop or Server
    RStudio Version : 1.4.5002
    OS Version      : All
    R Version       : 4.0

### Steps to reproduce the problem

Replace the installed Pandoc with an older version (such as 2.9), open an Rmd file, click on Visual Mode.

### Describe the problem in detail

Your session will hang forever and is only recoverable by resetting the entire state by clearing out `~/.local/share/rstudio`

### Describe the behavior you expected

There are two things going on here.
1. The dependency script is currently version agnostic so wont upgrade you if an older version is already present.
2. There is no indication to the user that they do not have the correct version of Pandoc loaded, either through logs or through the UI. At the least it should be in the logs but, as @kevinushey has pointed out, it may possible for there to be an invalid `pandocPath()` option, in which case a stronger call to action may be warranted.

Relevant code paths:
https://github.com/rstudio/rstudio/blob/efc873ed38a738be9dc0612d70f21f59bfd58410/dependencies/common/install-pandoc#L27-L31

https://github.com/rstudio/rstudio/blob/ca9faebabba016ac2dc7fd994798eff5cb9d6f5a/src/cpp/session/SessionPandoc.cpp#L34-L43

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jjallaire** [comment]
This is an issue which will impact devs not end users (as for end users we will always have the correct version). Worse for this case, Pandoc 2.11's AST is incompatible w/ Pandoc 2.9. This rarely occurs, which is likely why we haven't seen this issue before. Since it's a dev issue, perhaps all we need to do is have CMake barf if you haven't updated pandoc? (i.e. this just needs to be made version aware: https://github.com/rstudio/rstudio/blob/master/src/cpp/session/CMakeLists.txt#L28-L30, note that below the install directive is version aware: https://github.com/rstudio/rstudio/blob/master/src/cpp/session/CMakeLists.txt#L553-L559)

**Comment by jjallaire** [comment]
This should resolve the issue for devs: https://github.com/rstudio/rstudio/commit/e3f15a9a96dba0dda9506a825a581b678bb5b09b

For end users, the `external-pandoc-path` option (and in fact all of the `external-*` options aren't documented (they are there for managing dev vs. release configs) so that varying from our known embedded version is not a concern.

**Comment by kfeinauer** [comment]
Verified when doing dev builds - if Pandoc is out-of-date, you are forced to rerun dependencies script to perform a build.
