### ISSUE TITLE
Can't save new R Notebook files until changes are made

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#8228]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.984

### Steps to reproduce the problem

1. Create a new R Notebook file, *File -> New -> R Notebook*
2. Invoke the **Save** command by clicking the disk icon in the toolbar or using the keyboard shortcut.

### Describe the problem in detail

Nothing happens. However, if you make a change to the file's content in the editor, it can be saved.

### Describe the behavior you expected

It ought to be possible to save a file (give it a name) before working on it. This is a regression from 1.3, in which the Save command works immediately, and isn't consistent with other file types; e.g., new R Scripts can be saved without modifying them first.

**Comment by kevinushey** [comment]
Note: this only reproduces for me if there aren't already any open documents. If there's already an open document of some type, then the newly-opened document can be saved.

I see this assertion being fired in a dev build:

<img width="1920" alt="Screen Shot 2020-10-29 at 2 13 46 PM" src="https://user-images.githubusercontent.com/1976582/97633236-0369a500-19f1-11eb-8264-820cb5f16135.png">

So it appears that the issue here is that the Save command itself is not being enabled on load in this context.

**Comment by kfeinauer** [comment]
Verified fixed 1.4.991
