### ISSUE TITLE
Adding the support for "ED25519" cryptography in SSH

### ISSUE THREAD

**Issue by now-im** [rstudio/rstudio#8255]
[Gitlab](https://docs.gitlab.com/ee/ssh/) and [Github](https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent#generating-a-new-ssh-key) suggests using either ED25519 or RSA keys size of at least 2048 bits.
I have personally found ED25519 very fast in git commit verifying and ease to use. 

**Problem:**
Rstudio supports adding only RSA key in SSH which is most widely used.
![image](https://user-images.githubusercontent.com/22009014/98379394-71f1d700-2071-11eb-8d9d-0cda85751a06.png)

**Solution**
Adding optional ED25519 as it has proven viability to be a major counterpart of RSA in SSH.
Rstudio should automatically detect ED25519 key or have the option to create it.

P.S. Thanks for this great piece of software. Huge fan here!

**Comment by ronblum** [comment]
@nowshed-imran Thank you for the suggestion! I'll mark this as an enhancement request to review as we continue development of RStudio. And thank you for the kind words—I and the rest of the team appreciate it! 😄

**Comment by jennybc** [comment]
I think this should be addressed and it's getting more urgent. To be clear, people can use keys created with the Ed25519 algorithm, but RStudio gives the impression you don't have keys, which is really confusing.

Other issues where this has been discussed this before: #1969, #1645

I just set up keys following GitHub's current advice, as part of freshening up Happy Git with R:

https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent#generating-a-new-ssh-key

This has people creating keys with the Ed25519 algorithm if their system supports it, which I suspect most do.

At this point, RStudio's *Tools > Global Options ... > Git/SNV* suggests that I don't have SSH keys, but I definitely do.

Given GitHub's recent changes re: disallowing password auth (for https) and changing the PAT format, it feels like once they decide to do something, they move rather rapidly. I guess it's not likely that RSA keys will be dropped any time soon, but it feels like RStudio should get ready for more people to be using Ed25519 keys.

A relevant post re: SSH changes at GitHub:

https://github.blog/2021-09-01-improving-git-protocol-security-github/

**Comment by gtritchie** [comment]
Would it be worth splitting into two issues?

One tracking having RStudio recognize existing ED25519 key (instead of saying "(None)". That's what I'm proposing we try to get into PT.

A separate issue for fully supporting these keys, i.e. letting you generate them via the RStudio UI. That will be more work so definitely needs to wait for a future release.

**Comment by ronblum** [comment]
[From #10807 by @jeroen]

The IDE lets uses generate an RSA keypair (under global options -> git/svn), however as of recently [github restricts use of newly generated rsa keys](https://github.blog/2021-09-01-improving-git-protocol-security-github/). This is particularly a problem because R packages gert and libgit2 (and perhaps others) don't support the newly required RSA SHA-2 signatures yet, as described in the [post](https://github.blog/2021-09-01-improving-git-protocol-security-github/):

> __libgit2 and other Git clients__
> If you’re using libgit2 or another piece of code using libssh2, we recommend you use libssh2 1.9.0 or newer and an ECDSA key, since it does not yet support RSA with SHA-2. 

Here is an actual bug reported by a user that used the rstudio generated rsa key: https://github.com/r-lib/gert/issues/172

So the recommendation from the blog post is to switch to ecdsa instead of rsa for newly generated keys. I think that makes sense, ecdsa has been supported in openssl and openssh for a very long time now, it's available in every os.

[From me]
Triage note: Based on this information, I'm suggesting considering this in Spotted Wakerobin, or Elsbeth Geranium at the latest.

**Comment by jgutman** [comment]
> [From #10807 by @jeroen]
> 
> The IDE lets uses generate an RSA keypair (under global options -> git/svn), however as of recently [github restricts use of newly generated rsa keys](https://github.blog/2021-09-01-improving-git-protocol-security-github/). This is particularly a problem because R packages gert and libgit2 (and perhaps others) don't support the newly required RSA SHA-2 signatures yet, as described in the [post](https://github.blog/2021-09-01-improving-git-protocol-security-github/):
> 
> > **libgit2 and other Git clients**
> > If you’re using libgit2 or another piece of code using libssh2, we recommend you use libssh2 1.9.0 or newer and an ECDSA key, since it does not yet support RSA with SHA-2.
> 
> Here is an actual bug reported by a user that used the rstudio generated rsa key: [r-lib/gert#172](https://github.com/r-lib/gert/issues/172)
> 
> So the recommendation from the blog post is to switch to ecdsa instead of rsa for newly generated keys. I think that makes sense, ecdsa has been supported in openssl and openssh for a very long time now, it's available in every os.
> 
> [From me] Triage note: Based on this information, I'm suggesting considering this in Spotted Wakerobin, or Elsbeth Geranium at the latest.

It seems like the issue with newly created RSA keys, is that newly created RSA needs to be at least 2048 bytes, and the Github instructions seem to actually recommend 4096. Updating this issue so that newly created RSA keys are created with a larger size, making them usable. Also making ED25519 the default for newly created keys. As for ECDSA, that is not included in this PR, and the latest Github instructions do recommend ED25519, but we can easily add ECDSA as both a detectable and creatable type in a follow-on PR

**Comment by romainfrancois** [comment]
Verified with build: 

```
RStudio 2022.06.0-daily+351 "Spotted Wakerobin" Daily (ab19e471486aa89e6d350db4e93027845e0847f2, 2022-05-03) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 12_3_1) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.10 Chrome/69.0.3497.128 Safari/537.36
```

Can create ED25519 and RSA keys: 

![image](https://user-images.githubusercontent.com/2625526/166661260-0e95c1c6-c8e1-4a4b-9a69-4fa987425e08.png)

ED25519 is selected by default if both exist: 

<img width="568" alt="image" src="https://user-images.githubusercontent.com/2625526/166661319-b9fdd828-6f5e-4248-8c6f-f37f12699cec.png">

- Removed ED25519, Does indeed have to restart Rstudio for detection, but then it finds the RSA key: 

<img width="564" alt="image" src="https://user-images.githubusercontent.com/2625526/166661512-001edaab-dbc7-4a89-afc7-73b9bd76f4b4.png">

- creating a new ED25519, then removing(manually) the RSA key. 

The ED25519 is created, however when closing and back at the dialog, it still finds RSA: 

<img width="564" alt="image" src="https://user-images.githubusercontent.com/2625526/166662266-bad284dc-432d-496f-b388-63e8d1f66c32.png">

although we just created a ED25519 key. 

- This gets resolved when the ide is restarted. 

<img width="481" alt="image" src="https://user-images.githubusercontent.com/2625526/166662402-c7c17b9f-3750-4d9d-ad54-5392ad9a3763.png">

Could we make it so creating a key makes it the selected one ?

**Comment by romainfrancois** [comment]
Or should that force a restart ?

**Comment by jgutman** [comment]
And yes, we intentionally prefer ed25519 if both exist (based on github's recommendation)

**Comment by romainfrancois** [comment]
Starting with no key at all, creating a RSA key, clicking Apply or ok, then reloading the Options give: 

<img width="1170" alt="image" src="https://user-images.githubusercontent.com/2625526/168010058-037308fc-2fa5-474f-be99-3788bc9d2332.png">

I only see it when restarting the ide. 

<img width="658" alt="image" src="https://user-images.githubusercontent.com/2625526/168010240-15dd20ab-f7e8-4bca-bdc8-f780c68199b5.png">

However, if I then create a key, it becomes the default: 

<img width="652" alt="image" src="https://user-images.githubusercontent.com/2625526/168010377-39cd6c2c-4bd2-4035-b2e3-47b0daeea87d.png">

**Comment by jgutman** [comment]
Can you confirm if you're using daily 391?

**Comment by romainfrancois** [comment]
Yeah this was 391. I think we can close this issue now.
