### ISSUE TITLE
Pooled PostgreSQL connections forever unusable if database connections are lost

### ISSUE THREAD

**Issue by kfeinauer** [rstudio/rstudio#8266]
### System details

    RStudio Edition : Server
    RStudio Version : 1.4.969-1

### Steps to reproduce the problem

1. Configure RStudio to use the PostgreSQL database backend
2. Start the service
3. Stop the PostgreSQL database service
4. Attempt to sign in / sign out. Note that you cannot - this is expected since the database is down.
5. Restart PostgreSQL service
6. Notice you still cannot sign in / out, even though the DB is back up.

### Describe the problem in detail

Connection failures are a final state - the database connections are forever lost once connectivity is initially lost.

### Describe the behavior you expected

Database connections should reconnect.

**Comment by kfeinauer** [comment]
Connections can also be killed via the following query:

SELECT
	pg_terminate_backend(pg_stat_activity.pid)
FROM
	pg_stat_activity
WHERE
	pg_stat_activity.datname = 'rstudio'
	AND pid <> pg_backend_pid();

**Comment by kfeinauer** [comment]
@R-Hannibal Assigned to you since you are testing the database feature epic.

**Comment by R-Hannibal** [comment]
Verified Fixed on: RStudio Version - 1.4.1096-1, R Version - 3.6.3, RHEL8 - Server 

Verified postgres db connection can be re-established after an interruption: logged into RSP instance > stopped postgresql service > attempt to login to the RSP instance > error due to licensing system being down > restart postgresql service > login functionality to the RSP instance is restored.
