### ISSUE TITLE
Can not use "Save As"

### ISSUE THREAD

**Issue by tungmilan** [rstudio/rstudio#8277]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.999
    OS Version      : Windows 10 Enterprise 64-bit
    R Version       : 4.0.3 64-bit

### Steps to reproduce the problem

Open any R script then try saving it as a different file

### Describe the problem in detail

The option is not available

![rstudio_201103094930](https://user-images.githubusercontent.com/6590141/98022713-cddf0600-1dba-11eb-8a09-73560fce574d.png)

### Describe the behavior you expected

Save file as should work

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by melissa-barca** [comment]
Verified this reproduces on Windows and MacOS.

**Comment by melissa-barca** [comment]
@kevinushey It looks like this is being caused by adding `saveSourceDocAs` to the manageSaveCommand logic since it's making it disabled when the document is not dirty. Do you think we could remove this or would that bring back the issues we saw before with switching between source data viewers and editors?

https://github.com/rstudio/rstudio/blob/master/src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceColumn.java#L824

**Comment by kevinushey** [comment]
@melissa-barca I think you're right. If that's the case then I think we can just remove that. (I was worried because the `Save As` command remained un-enabled but `Save` was enabled in the prior issue but I think we can just live with that for 1.4)

**Comment by tungmilan** [comment]
Thank you both!

**Comment by kfeinauer** [comment]
Verified fixed 1.4.1003
