### ISSUE TITLE
Incorrect coloring in roxygen-commented docs.

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#8352]
**Steps to reproduce:**
* Write some roxygen2 docs having an `\eqn` statement.
* On the 2nd argument of `\eqn`, write some equation having two multiplications.

**Expected behavior:** should be colored like regular text, since what's inside `\eqn` doesn't follow markdown.

**Actual behavior:** after seeing a second `*`, things get colored as if they were markdown-formatted, even though they don't render like that when building the docs.

**Setup:** RStudio 1.4.953.

Example:
```r
#' @description multiplication:
#' \eqn{\mathbf{A} = \mathbf{B} \mathbf{C} \mathbf{D}}
#' {A = B*C*D} more text here
```

**Comment by kevinushey** [comment]
Does this screenshot match what you're seeing?

<img width="443" alt="Screen Shot 2020-11-12 at 9 21 12 AM" src="https://user-images.githubusercontent.com/1976582/98973316-716d9c00-24c8-11eb-8745-4884e61a732d.png">

I think we highlight things this way because, at least in a regular R Markdown document, something like:

```
Regular*Italics*Regular
```

would be interpreted with the `*Italics*` bit as styled with italics.

Regardless... it's a real bug but just wanted to explain the likely source of the issue.

**Comment by david-cortes** [comment]
Yes, that's what I see when I type that, and although it doesn't seem like much of a problem, gets annoying when the lines are long and the asterisks are near the beginning or the end.
