### ISSUE TITLE
Running previous chunks in visual mode doesn't work if cursor is outside of a chunk

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#8500]
### System details

    RStudio Edition : Desktop and Server
    RStudio Version : 1.4.1063
    OS Version      : MacOS 11.1 and Ubuntu 20.04
    R Version       : 4.0.3

### Steps to reproduce the problem

1. Open a markdown document.
2. Enter visual mode.
3. Place the cursor outside of a code chunk.
4. <kbd>Run -> Run All Chunks Above</kbd>
    - Previous chunks aren't executed.
5. Place the cursor inside a code chunk.
6. <kbd>Run -> Run All Chunks Above</kbd>
    - Previous chunks get executed.

Repeating the same in source mode will result in chunks always running (step 4 ends with chunks getting executed).

### Describe the problem in detail

In visual mode, running previous chunks only works if the cursor is in a code chunk. In source mode, it works from both in and out of a code chunk. 

### Describe the behavior you expected

Execute previous chunks regardless of where the cursor is.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment]
This happens because these commands effectively work by synchronizing the selection state from visual mode:

https://github.com/rstudio/rstudio/blob/fd8b30c42efbd329ce8171cf7dec7fea662b192f/src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java#L5641-L5657

However, that sync only works if selection is inside a code chunk (since there is currently no 1:1 way map the cursor location outside code chunks).

We will probably need to fix this by having the visual editor map the cursor location onto the _nearest_ chunk.

**Comment by jmcphers** [comment]
Fixed by https://github.com/rstudio/rstudio/pull/8602 in Juliet Rose.

**Comment by astayleraz** [comment]
Verified on mac desktop Version 1.4.1527 this is now running the chunks below and above as expected in visual mode. Closing as fixed.
