### ISSUE TITLE
Jumping console with wide tibble

### ISSUE THREAD

**Issue by avsmith** [rstudio/rstudio#8504]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1056
    OS Version      :  MacOS 10.15.7
    R Version       :  4.0.3

### Steps to reproduce the problem

- Load tibble with lots of columns. (I have an 5002 row/85 column example, and 2398 row/75 column example)
- Then try to look at snippet of tibble (by entering the tibble name)

### Describe the problem in detail

The console screen then jumps, with a blue "Latest" button appearing in lower right. Rather than 10 rows being displayed, there is a cycle of tibbles being displayed with varying numbers of rows (<= 10). The console then jumps around.

I can stop the console jumping by displaying a narrower tibble. I have to get the wider tibble to scroll off the top of the screen to stop the jumping.

### Describe the behavior you expected

A non-jumping tibble shown in the console.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ ] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
Try turning off the "Limit console display to a subset..." option. We are working on several fixes in this area but did recently turn this option on by default.

![screenshot of global options highlighting mentioned option](https://user-images.githubusercontent.com/10569626/100808220-975fcf80-33e8-11eb-8db3-e6b775598ceb.png)

**Comment by gtritchie** [comment]
Adding to 1.4 so it gets on the radar.

**Comment by adamconroy** [comment]
Hi @avsmith, thanks for the report. Can I get a minimal reprex as well the size of your screen (if you're on a 13" MacBook or a 40" iMac)?  I couldn't repro it on my machine so there might be a specific thing I'm missing about the configuration.

**Comment by avsmith** [comment]
My examples are with sensitive data, so I wasn’t able to even make a screencast of the behavior. I’ll try to make an example in a bit.

FWIW, the suggestion to turn off "Limit console display to a subset…” did make the jumping stop.

-a

**Comment by david-cortes** [comment]
Not sure if #8535 is the same issue, but it's still happening in 1.4.1078.

Here's a reproducible example:
```r
while (TRUE) {
    print("polluting the console")
    Sys.sleep(0.05)
}
```

**Comment by adamconroy** [comment]
@david-cortes feel free to @ me with this, I'm looking into it. Does this repro for you with a cleared console? What is the size of your console panel? When does it start for you? I let it run for a minute and never saw any strange behavior. I also tried using `message` instead of `print` which will trigger the paging algorithm and it functioned properly.

**Comment by david-cortes** [comment]
@adamconroy does it make a difference if you put the console pane on the top-left? (by default, the editor pane is placed there)

**Comment by adamconroy** [comment]
It doesn't. I've had it running for a few minutes now with no issues yet. I'll try interlacing in different methods as well to keep trying to get into the bad state. I did see the jumping behavior early on in the feature development so I do have a good idea of what's happening but it's hard to narrow down exactly the cause without an exact repro.

https://i.imgur.com/xmlDVtv.gif

**Comment by adamconroy** [comment]
For reference this is the expected behavior: https://i.imgur.com/txWH7kZ.gif

It will be a little different with ONLY prints in a for-loop because all of those will count as a single message instead of each one counting towards the paging. However, it should still not exhibit any degenerate behavior.

**Comment by david-cortes** [comment]
@adamconroy : what if you try it within a package project while having the build pane visible at the top right?

**Comment by adamconroy** [comment]
No difference, good idea though. I'll try on my Mac laptop. I have been testing on my Windows machine but that shouldn't make a difference as the similarly filed issues were for Windows.

**Comment by adamconroy** [comment]
Worked flawlessly on my 13" Macbook, interpolated messages and prints as well and couldn't reproduce any strange behavior.

@david-cortes would you be able to record a gif or video of the behavior (or at least a screenshot of your pane configuration)? My feeling is that the cause might be triggered by the pane/application resolution.

**Comment by david-cortes** [comment]
Attached is a gif:
![jumping_console](https://user-images.githubusercontent.com/11860098/101211110-50d7d280-367f-11eb-911f-fd44004b49ae.gif)

**Comment by adamconroy** [comment]
@david-cortes ...oh. That's expected behavior, to me anyway. In fact it's how many consoles work by default. It will always jump to the bottom as you get more input. I thought there was some extreme jumping up and down outside of peoples' control when output wasn't being added. We could add a pin output functionality or I could turn the jumping off by default but I wrote this with my default preference which is to always jump to the bottom when there is new input, I see now that it doesn't work that way with this feature turned off.

I actually think this is different than what `avsmith` reported initially. Thanks for the help though! I will reach out to the team and see what they would prefer.

**Comment by david-cortes** [comment]
@adamconroy : that's not how e.g. konsole or windows CMD works - they will only do that if the last line is visible with the current scroll. Also it doesn't happen when I tick off the setting for limiting the console display.

**Comment by adamconroy** [comment]
Not every console, but many! This is VSCode, for example: https://i.imgur.com/pztLIOr.png

The limit console display is the feature that I wrote, with it turned off the functionality will be the same as RStudio 1.3. Considering this is the default that is expected by RStudio users I will evaluate if it is trivial to turn off the jumping, it should be.

**Comment by kevinushey** [comment]
FWIW, it looks like this is indeed a change in behavior: when Limit Console Output is disabled, we maintain the scroll position as new output is streamed to the console; however, this is not the case with Limit Console Output enabled.

Here's where we try to re-scroll to the bottom when new output is appended to the history:

https://github.com/rstudio/rstudio/blob/5ace4730ef6f412e38c65e4c09aba99249dad7fc/src/gwt/src/org/rstudio/studio/client/common/shell/ShellWidget.java#L241-L250

**Comment by kevinushey** [comment]
I can see this being annoying for users with long-running scripts. For example, imagine you're running that runs for a while and emits output intermittently; e.g.

```
> Running job 5 of 100...
> Status: etc.
```

and you're trying to peruse that output while the script continues running. If the view is being inadvertently scrolled to bottom while doing that it could be pretty disruptive. (I think this sort of usage would be relatively common, so if this is safe to fix for 1.4 I'd advocate doing so)

**Comment by avsmith** [comment]
We may be talking about two different issues (though perhaps related). I've made a reproducible examples of what I see. As noted, "Limit console display to a subset..." needs to be on. I included a screen grab to show what I see. I don't think I see the jumping on the first display of the tibble, which is why I repeat the call to display.

`library(dplyr)

tib_wNA <- as_tibble(data.frame(replicate(100,sample(c(NA,NA,0:1),10000,rep=TRUE))))

tib_wNA
tib_wNA
tib_wNA`

![jumping](https://user-images.githubusercontent.com/130802/101223771-c9786800-365a-11eb-9c89-569c15210250.gif)

**Comment by kevinushey** [comment]
Thanks! I think you're right that these are separate issues and I can reproduce via the code you've provided.

For me, the issue reproduces if I run the mentioned code, and then attempt to scroll quickly (via trackpad) to the top or bottom. It seems sort of like the virtual scroller is updating too slowly to keep pace with the user as they try to scroll? Or that perhaps the buckets are too small?

**Comment by adamconroy** [comment]
Thanks for the reprex! These are two different issues. I almost have a PR ready to fix the autoscrolling. I will look into the actual issue filed here this weekend.

**Comment by valerie-rstudio** [comment]
### Verify Failed

    RStudio Edition : Desktop
    RStudio Version : 1.4.1532
    OS Version      : mac OS 11.1
    R Version       : 4.0.2

### Failure Points
When the "Limit Console Output" option is selected, scroll position does not follow output by default.
1. Go to Tools -> Global Options -> Console and check "Limit visible console output". Restart RStudio.
2. Open a new R Script and run this code: `while (TRUE) {
    print("polluting the console")
    Sys.sleep(0.05)
}`
3. **Expected Behavior:** The console scrolls down along with the output. If the user changes the scroll position on the console, then the console maintains the users scroll position.
4. **Actual Behavior:** The console maintains scroll position at the start of the while loop and does not follow the output. If the user changes the scroll position on the console, then the console maintains the users scroll position.

### Notes
- You can view the Expected Behavior by running the same R code in step 2 with the "Limit Console Output" option unchecked.

**Comment by adamconroy** [comment]
Confirmed that this seems to stop scrolling after a few commands, particularly on smaller screens and on Desktop. I think we're being a little too strict with the threshold for scrolling to the bottom. Should be a quick fix.

**Comment by valerie-rstudio** [comment]
### Verified Fixed

    RStudio Edition : Desktop
    RStudio Version : 1.4.1597
    OS Version      : mac OS 11.2.1
    R Version       : 4.0.3

Verified that with limit console output checked or unchecked, the console follows output by default, and maintains scroll position if a user scrolls up.
