### ISSUE TITLE
Long character variables get truncated in console

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#8567]
**Steps to reproduce:**
* Create a very large character variable in R that would span hundreds of lines.
* Print said variable through `cat(long_char)`.

**Expected behavior:** should print all the lines if possible, tell whether truncation occurred if not, or make it deducible from what's showing at the beginning of the console.

**Actual behavior:** prints only the tail of the variable. Before the print starts, the `cat` statement and whatever was there before show correctly and are still visible in the console, despite the output from `cat` having been truncated.

**Setup:** RStudio 1.4.1078.

Attached is an example serialized variable to reproduce.
[long_char.zip](https://github.com/rstudio/rstudio/files/5661426/long_char.zip)

(The file needs to be renamed to `.rds` and loaded with `readRDS`)

**Comment by kevinushey** [comment]
Simpler reproducible example:

```
long <- as.character(1:1E4)
writeLines(long)
```

Note that this will be fixed in the latest daily builds (>= 1.4.1087) as we've disabled virtualized console output by default for now. For posterity, I see:

<img width="233" alt="Screen Shot 2020-12-08 at 1 55 08 PM" src="https://user-images.githubusercontent.com/1976582/101546023-ff6c6380-395c-11eb-9ed2-6f5614fe0792.png">

And also "holes" in the output:

<img width="145" alt="Screen Shot 2020-12-08 at 1 55 37 PM" src="https://user-images.githubusercontent.com/1976582/101546054-0f844300-395d-11eb-89b6-7162d9770475.png">

**Comment by adamconroy** [comment]
This is the same issue as https://github.com/rstudio/rstudio/issues/7712 which supposedly was fixed in https://github.com/rstudio/rstudio/pull/7909/files

The code is untouched so I don't know why it's resurfacing.

It is a Desktop only bug which explains my issues reproducing it, forgot about that. Will have to see if that communication can be equalized between versions too, not sure why there is any difference.

**Comment by valerie-rstudio** [comment]
### Verified Fixed

    RStudio Edition : Desktop
    RStudio Version : 1.4.1540
    OS Version      : mac OS 11.1
    R Version       : 4.0.3

Verified that the console output of a variable that is 10,000 lines no longer has "holes" in the output, and also clearly appears truncated (see image).
![Screen Shot 2021-02-02 at 4 41 32 PM](https://user-images.githubusercontent.com/75644399/106672681-0cc95700-6576-11eb-9d2b-801b1c0c5d94.png)

**Comment by david-cortes** [comment]
@valerie-rstudio : But the issue originally was that it gets truncated without any hint. From that image, it's not possible to discern whether one is seeing the full output or not.

**Comment by adamconroy** [comment]
@david-cortes I agree that it's not ideal. The original interpretation here is that this was a regression (which it was), what is currently there now matches the functionality that has always been in RStudio. I'll look into options and file an issue.

**Comment by david-cortes** [comment]
@adamconroy : If I'm not mistaken, in previous versions it would have shown the command that printed the lines first, and as lines appear and reach the display limit, it would remove the command as it was in an earlier line and it removed them on a FIFO basis.
