### ISSUE TITLE
Switching from/back to RStudio scrolls console to the end

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#8568]
**Steps to reproduce:**
* Print many statements in the console so as to make it scrollable.
* Scroll up in the console.
* Switch from RStudio to a different application.
* Switch back to RStudio.

**Expected behavior:** the console focus should remain where it was.

**Actual behavior:** the console focus always moves to the end. If switching with `Ctrl + Tab`, the console focus will move to the end right when switching *from* RStudio, whereas if clicking a different window it will wait until switching back to move to the end.

**Setup:** RStudio 1.4.1078, running on debian testing (bullseye), KDE 5.19.5, QT 5.15.1.

**Comment by adamconroy** [comment]
This is happening because of this:
https://github.com/rstudio/rstudio/blob/697a761479c3bc06eb14d93be55935cee3f5eab8/src/gwt/src/org/rstudio/studio/client/common/shell/ShellWidget.java#L713

For some reason `scrollPane.getElement().getScrollTop()` is ALWAYS returning the max value...even when I'm getting the correct value from the devtools console. I may be able to fix this by directly routing into virtualscroller.js but this feels like something going wrong in GWT itself.

**Comment by kevinushey** [comment]
@adamconroy: Do you see the correct result if you bypass some of the GWT APIs here; e.g. if you define your own JSNI method like `ElementProperty.scrollTop()`? We did something similar for `NativeEvent`s here:

https://github.com/rstudio/rstudio/blob/cb6d0a1e6fdb05c6498284bcad3f8716e946e794/src/gwt/src/org/rstudio/core/client/dom/EventProperty.java#L21

**Comment by adamconroy** [comment]
Looks like I was barking up the wrong tree. Something else is setting the scrollTop before it even gets to that line in ShellWidget. The search continues...

**Comment by adamconroy** [comment]
Closed in #8682

**Comment by astayleraz** [comment]
I verified the fix for this in Version 1.4.1524-1 R 4.0.2. I was not seeing the scrolling issue and was also able to do a git commit.
