### ISSUE TITLE
locator returns incorrect coordinates when graphics device AGG is selected

### ISSUE THREAD

**Issue by sjmgarnier** [rstudio/rstudio#8571]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1056
    OS Version      :  macOS 11.0.1
    R Version       :  4.0.3

### Steps to reproduce the problem

```r
plot(c(-1, 1, 1, -1), c(-1, -1, 1, 1))
locator(4)
```
Click on all four points. The returned coordinates are incorrect, i.e. they do no correspond to the input coordinates of the points.

### Describe the problem in detail

See above. 

### Describe the behavior you expected

`locator` should return the coordinates that correspond to that of the points in graph. 

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@sjmgarnier What are you getting if you run this in R outside of RStudio? I tried it out, and I got the following 

```
$x
[1] -0.9955863  1.0019897  1.0017511 -1.0034754

$y
[1]  0.9867773  1.0001683 -0.9982052 -1.0023723
```

It's not returning the location of the points themselves, but where the clicks occur. So if I click in the center of the graph four times, I get

```
> locator(4)
$x
[1] -0.03237114 -0.03237114 -0.03237114 -0.03237114

$y
[1] 0.02967022 0.02967022 0.02967022 0.02967022
```
Almost (0,0) but not quite. This is the behavior of the `locator` function in R.

**Comment by sjmgarnier** [comment]
@ronblum Did you try that with the AGG device activated in RStudio Preview? The results are widely different from those you get when using the default graphics device. I guess I should have made this more clear in my explanation. The locator function returns what one expects when selecting the default graphics device but not when selecting the AGG device.

**Comment by kevinushey** [comment]
I can reproduce as well. Perhaps a more dramatic example:

```
> plot(1)
> locator(1)
$x
[1] 0.6624613

$y
[1] 1.376489
```

**Comment by ronakv10** [comment]
If you're having issue with locator function then it might be because of the zoom level of the Rstudio or Scale of the windows (Display settings). Change both the zoom levels to 100% as shown:

**Changing the zoom level of RStudio**

Go to **Tools -> Global Options -> Appearance -> Zoom (change that to 100%)**

![photo_2](https://user-images.githubusercontent.com/48622666/228611802-4ec34e66-b1c2-4f6a-bb0e-7a38a402730a.jpg)

**Changing the zoom level of Windows**

This happens often in the laptops where the Scale is 150% by default. You have to change that 100%.

Right click on windows' desktop, **Display Setting -> Scale (change that to 100%)**

![photo_](https://user-images.githubusercontent.com/48622666/228610968-8bcd2da8-69c8-4b3f-9f1b-8dfa06b529f2.jpg)
