### ISSUE TITLE
Safari number/bullet for new list lines don't show up until typing content

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#8581]
### System details

    RStudio Edition : Server using Safari
    RStudio Version : 1.4.1081
    OS Version      : From MacOS 11.1 beta to Red Hat 8.3
    R Version       : 4.0.3

### Steps to reproduce the problem

In Safari, pointing at RStudio Server:
1. Open a markdown document in visual mode.
2. Type “1.” to create a list
    - The “1.” disappears
3. Type anything else.
    The “1.” reapers.
4. Click “Return”
    - What looks like a blank line is created.
5. Type anything
    - The “2.” appears

### Describe the problem in detail

In Safari, when creating a new list, the list is created, but the number/bullet/etc. don’t show up until something else is typed.

This is not an issue with Chrome and Firefox or in RStudio Desktop.

### Describe the behavior you expected

Numbers/bullets/etc. should not disappear.

I'm marking this as 1.4 so that it gets considered for it, but I'm not certain that this meets the bar as 
1) The list gets created.
2) The numbers, etc. appear as soon as something is typed, and presumably list items will contain content.
3) It's limited to one browser.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
This issue is very odd. Reproducing this consistently has been hard, but in testing I've seen:

1. The bullet remains visible when the cursor is in a Markdown region, but disappears if I click into a code chunk,
2. The bullet remains visible, but then goes invisible if I click to focus a different window and then later return focus,
3. Visibility of the cursor + bullet can depend on what _other_ tabs in the IDE are focused. E.g. if I enable the Tutorial pane, _sometimes_ the cursor + bullet number become visible again!

Ultimately, this seems like some sort of bug in Safari itself. I think we should wait and see for now if the next release of Safari fixes this; assuming a bugfix release will be published in the next couple of months.

**Comment by jjallaire** [comment]
Given that this is likely a Safari bug I am going to close this (I haven't been able to repro on the version of Safari I am using)
