### ISSUE TITLE
Switching between projects is very slow (after upgrade from 1.2 to 1.3)

### ISSUE THREAD

**Issue by Avi-Kenny** [rstudio/rstudio#8585]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.1093
    OS Version      :  Windows 10 Home
    R Version       :  3.6.3

### Steps to reproduce the problem

Click on the project dropdown on the top-right and choose a new project.

### Describe the problem in detail

The problem is simple. After I upgraded from RStudio 1.2 to 1.3, the issue appeared. When I have a project open and I click on the project dropdown on the top-right and choose a new project, nothing happens for 10-20 seconds (it varies), and then the project finally switches. This does not happen every time I switch projects, but maybe half the time.

### Describe the behavior you expected

Before I upgraded from 1.2 to 1.3, the switch between projects would be almost immediate.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@Avi-Kenny Thank you for raising the issue! We'll review it as part of the development of RStudio.

**Comment by R-Hannibal** [comment]
@Avi-Kenny - I am not able to reproduce the issue currently (Testing on Windows 10/3.6.3/1.3.1093).

Have you upgraded to our latest stable release of RStudio, 1.4.1103 (available [HERE](https://rstudio.com/products/rstudio/download/))? Curious if the issue is still occurring for you there. If it is still occurring in 1.4 builds, any more specifics you can provide around the behavior you're seeing will aid our attempts to reproduce in-house -

- Does it occur with all your projects/project types, or only specific ones?
- Does rolling back to 1.2 fix the issue, or does it continue occurring after a rollback?
- Any other slow behavior within the IDE after upgrading to 1.3, or is opening projects the only thing?

Thank you again for reporting this issue and helping us to improve RStudio.

**Comment by Avi-Kenny** [comment]
I just upgraded from 1.3 to 1.4 and it seems like this behavior is no longer happening. I'll close this issue. Thanks!
