### ISSUE TITLE
Inserting a code block with a code chunk in it directly under a list item munges up the code

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#8617]
### System details

    RStudio Edition : Desktop and Server
    RStudio Version : 1.4.1088
    OS Version      : MacOS 11.1 beta, Red Hat 8.3, SLES 15.2, etc.
    R Version       : 4.0.3

### Steps to reproduce the problem

The simplest way to do this is:
1. Open an R Markdown document in RStudio Server.
2. Switch to source mode.
3. Paste the following. Make sure to include the leading four spaces in the R code chunk.
````
-   List item
    ```{r}
    plot(pressure)
    ```
````

4. Switch to visual mode.
    - The above is replaced with 

- List item `f3175f2a-e8a0-4436-be12-b33925b6d220     31b8e172-b470-440e-83d8-e6b185028602:dAB5AHAAZQA6AFoAZwBBAHoAQQBEAEUAQQBOAHcAQQAxAEEARwBZAEEATQBnAEIAaABBAEMAMABBAFoAUQBBADQAQQBHAEUAQQBNAEEAQQB0AEEARABRAEEATgBBAEEAegBBAEQAWQBBAEwAUQBCAGkAQQBHAFUAQQBNAFEAQQB5AEEAQwAwAEEAWQBnAEEAegBBAEQATQBBAE8AUQBBAHkAQQBEAFUAQQBZAGcAQQAyAEEARwBRAEEATQBnAEEAeQBBAEQAQQBBAAoAcABvAHMAaQB0AGkAbwBuADoATQBRAEEAdwBBAEQARQBBAAoAcAByAGUAZgBpAHgAOgBJAEEAQQBnAEEAQwBBAEEASQBBAEEAPQAKAHMAbwB1AHIAYwBlADoAWQBBAEIAZwBBAEcAQQBBAGUAdwBCAHkAQQBIADAAQQBDAGcAQQBnAEEAQwBBAEEASQBBAEEAZwBBAEgAQQBBAGIAQQBCAHYAQQBIAFEAQQBLAEEAQgB3AEEASABJAEEAWgBRAEIAegBBAEgATQBBAGQAUQBCAHkAQQBHAFUAQQBDAGcAQQBnAEEAQwBBAEEASQBBAEEAZwBBAEcAQQBBAFkAQQBCAGcAQQBBAD0APQAKAHMAdQBmAGYAaQB4ADoA:31b8e172-b470-440e-83d8-e6b185028602`
5. Switch to source mode.
    - The code in step 4 has replaced the original code.

### Describe the problem in detail

The initial code is replaced by something unreadable.

### Describe the behavior you expected

The code should stay the same.

As far as I can tell, the conditions are to insert a code block with a code chunk in it directly under a list item. (In most circumstances, four or more leading spaces indicates a code block.)

1) Create a list item
2) On the next line, indent by four spaces or more, which indicates a code block.
3) Insert a code chunk, keeping the indentation.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
Note: trying to do something similar starting in visual mode is harder to do, if outright impossible, because the visual editor will correctly insert a blank line that separates the code from the list.

However, starting with the above source and switching to visual mode means losing the code. This can be undone by switching back to source mode and undoing with <kbd>Cmd-Z</kbd> or <kbd>Ctrl-Z</kbd>. However, if the file is saved before undoing, the code will be lost.

**Comment by jmcphers** [comment]
The GUID comes from here:

https://github.com/rstudio/rstudio/blob/6ac74e366279aef2b076d4d7f27d8414d028f0a1/src/gwt/panmirror/src/editor/src/nodes/rmd_chunk/rmd_chunk-capsule.ts#L24

It _looks_ like what's going on is that the chunk capsule is getting treated as an indented literal code block instead of a chunk capsule.

**Comment by jmcphers** [comment]
Moving this to the patch release after conversation with @jjallaire. Highlights:

- This syntax is invalid; you can't nest an R chunk directly inside a list item like this. If you knit it, the R code chunk will not be executed and will instead turn into an inline code string. 
- The code responsible for this bug is mission-critical; breaking it could result in problems worse than this one for other documents. It also does not currently have automated tests, so the only real way to validate changes is field testing (thousands of user docs). 

We will plan to take #8626 for the patch release, which does not fix the problem (in the sense that it takes the invalid syntax and makes it valid) but will prevent the document from becoming corrupt by blocking the switch to visual mode.

**Comment by ronblum** [comment]
Verified in:
- RStudio Server 1.4.1103 on Ubuntu 20.04 from Chrome on MacOS
- RStudio Desktop 1.4.1103 on MacOS 11.1
- RStudio Desktop 1.4.1507 on MacOS 11.1
The fix was merged into Wax Begonia, hence testing in 1.4.1103.
