### ISSUE TITLE
Refreshing Shiny App creates multiple background jobs

### ISSUE THREAD

**Issue by JosiahParry** [rstudio/rstudio#8746]
### System details

    RStudio Edition : Desktop OS
    RStudio Version :  ‘1.4.1103’
    OS Version      :  macOS Catalina 10.15.3 
    R Version       : 3.6.3 (2020-02-29)

### Steps to reproduce the problem

1. Run a shiny application in the background. 
2. Make change to application.
3. Press green `Refresh App` button above source editor.

### Describe the problem in detail

When refreshing a shiny app that is running in a background job from the Refresh App button above source editor a new background job is created.

### Describe the behavior you expected

My anticipation was that running a shiny app in a background job would behave similar to what is illustrated at https://github.com/sol-eng/background-jobs/tree/master/shiny-job. In that it would auto-reload on save.

Specifically I would anticipate `options(shiny.autoreload = TRUE)` behavior and a single background session.

May be related to https://github.com/rstudio/rstudio/issues/6904.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by nwstephens** [comment]
This issue is particularly confusing when running multiple background jobs in the viewer pane. When running in a window, reloading the app pulls up a new window with a new port. However, when running in the viewer pane, you do not get a new viewer and you do not see the port. Like @JosiahParry , I would expect the current viewer pane to reload (or alternatively see a new tab in the viewer pane).

![image](https://user-images.githubusercontent.com/7519295/120848915-41e8b480-c52a-11eb-815d-136fd7aded3c.png)

![image](https://user-images.githubusercontent.com/7519295/120849235-a60b7880-c52a-11eb-863b-5ff04b273043.png)

![image](https://user-images.githubusercontent.com/7519295/120849281-bae80c00-c52a-11eb-9294-d7bf70f7f38f.png)

**Comment by astayleraz** [comment]
I verified in Version 1.5.139-1 I am no longer seeing multiple background jobs being created and added a test for this case. I did run into an issue with the new replay button in the jobs tab. I filed that here:  https://github.com/rstudio/rstudio/issues/9548 Closing this issue.
