### ISSUE TITLE
Gracefully handle architecture mismatch on macOS

### ISSUE THREAD

**Issue by jmcphers** [rstudio/rstudio#8771]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1103
    OS Version      : macOS

### Steps to reproduce the problem

1. Install an ARM (M1) build of R on macOS. This can be done by building R from source using Homebrew, or by installing r-devel from https://mac.r-project.org/. 
2. Start RStudio.

### Describe the problem in detail

An extremely unhelpful error appears.

```
dyld: could not load inserted library '/opt/homebrew/Cellar/r/4.0.3\_2/lib/R/lib/libR.dylib' because no suitable image found. Did find: /opt/homebrew/Cellar/r/4.0.3\_2/lib/R/lib/libR.dylib: mach-o, but wrong architecture /opt/homebrew/Cellar/r/4.0.3\_2/lib/R/lib/libR.dylib: stat() failed with errno=1
```

### Describe the behavior you expected

An error message indicating what's actually wrong (architecture mismatch, trying to load ARM R into x64 RStudio session) and what to do about it (install the x64 version of R instead). 

This problem is about to become much more common once R 4.1 is released with a formal ARM64 build. People who download the newest versions of R and RStudio on M1 Macs are likely to hit it. 

We are still a ways off from a formal M1 build of RStudio (see https://github.com/rstudio/rstudio/issues/8652), but we don't have to implement M1 support to improve the user experience here.

**Comment by bayeslearner** [comment]
May I confirm rstudio right now is intel only? But R does have an ARM version with (Homebrew or source installation).  Correct?

**Comment by gtritchie** [comment]
Correct, RStudio is currently Intel-only on macOS.

**Comment by jmcphers** [comment]
@kevinushey or @gtritchie Could you look at this? I think real M1 hardware will be required to validate the change.

**Comment by kevinushey** [comment]
I can take a look.

**Comment by gtritchie** [comment]
Thanks, my M1 hardware is back ordered so not much I can do.

**Comment by kevinushey** [comment]
Sketching out an approach for getting universal `rsession` binaries built. Basically, we need to build RStudio once for each architecture; the hard part is we also need to build all of RStudio's dependencies separately for each architecture.

This is somewhat complicated by the fact that we install some dependencies via Homebrew:

https://github.com/rstudio/rstudio/blob/9d3de7858d87b68a349747adcee0073fa6fb755f/dependencies/osx/install-dependencies-osx#L43-L48

We install some dependencies with our own build scripts:

https://github.com/rstudio/rstudio/blob/master/dependencies/common/install-boost
https://github.com/rstudio/rstudio/blob/master/dependencies/common/install-yaml-cpp

And for Crashpad, we either try using pre-built binaries or we try building ourselves:

https://github.com/rstudio/rstudio/blob/master/dependencies/common/install-crashpad

So we either need to:

1. Tweak our build scripts so that we can produce universal libraries, or
2. Find a way to produce parallel builds (arm64-only and x86_64-only builds), and then combine the resulting `rsession` binary.

I suspect (1) will be the most straightforward solution, but it will take some time to figure out. (in theory passing `-arch x86_64 -arch arm64` will suffice in producing universal binaries / libraries, but will have to play around)

Will need to watch https://developer.apple.com/videos/play/wwdc2020/10214/ for more details.

**Comment by jmcphers** [comment]
Thanks to @kevinushey we don't need to handle architecture mismatch at all -- we have a separate Apple Silicon build of the R session that will work out of the box w/ an aarch64 build of R.

**Comment by astayleraz** [comment]
I verified in version 1.4.1662 I was able to install and run on an M1 mac 11.2.3. Closing this issue.
