### ISSUE TITLE
RStudio's diagnostic engine incorrectly flags whitespace as unnecessary

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#8822]
https://community.rstudio.com/t/the-tidyverse-style-guide-inconsistent-with-rstudio-style-diagnostics/94060

---

### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 1.4.1522
    OS Version      : macOS Big Sur 10.16
    R Version       : R version 4.0.3 (2020-10-10)

The following R code is incorrectly diagnosed with unnecessary whitespace:

```
foo <- { 1 + 1 }
```

<img width="222" alt="Screen Shot 2021-01-27 at 9 41 58 AM" src="https://user-images.githubusercontent.com/1976582/106031617-54d31000-6084-11eb-8c78-abae0adede8c.png">

**Comment by valerie-rstudio** [comment]
### Verified Fixed

    RStudio Edition : Desktop
    RStudio Version : 1.4.1548
    OS Version      : mac OS 11.1
    R Version       : 4.0.3

Verified that any whitespace character(s) after a `{`, `(`, or before a `}`, `)` do not cause an "unnecessary whitespace" warning.

### Notes
- In order to repro the original issue, you will need to ensure that the option - Tools > Global Options > Code > Diagnostics > Provide R style diagnostics (e.g. whitespace) - is checked.
