### ISSUE TITLE
Environmental pane in R display abnormal 

### ISSUE THREAD

**Issue by ntluong95** [rstudio/rstudio#8834]
### System details

    RStudio Edition : 
    RStudio Version : 1.4.1524
    OS Version      : Window 10
    R Version       :  R devel 4.1

### Describe the problem in detail
After I initialize Python from Rmarkdown, the R environment display object envir and handlers as in the picture below. I tried to install newest version of Rstudio and R but nothing changed. I even reinstall my Window to clean install R and Rstudio but I can not fix it
![image](https://user-images.githubusercontent.com/63569637/106137206-ae156f00-616a-11eb-950a-5c94d7415b40.png)

**Update** This happens even when I call function from R, for example: `library(tidyverse)`
### Describe the behavior you expected
I hope can find solution that after run Python, R environment will be the same and not add 2 objects like this

`[x]` I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
`[x]` I have installed the latest version of RStudio, and confirmed that the issue still persists.
`[x]` If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
`[x]` I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@ntluong95 Thank you for raising the issue! Is your concern that the `environ` and `handlers` show up in the Environment pane, or that are there objects missing from it?

**Comment by ntluong95** [comment]
I mean it showed up in environment pane instead of not showing

**Comment by kevinushey** [comment]
Thanks; I can reproduce as well (happens whenever a chunk is run in an R Markdown document)

**Comment by R-Hannibal** [comment]
Verified Fixed on: RStudio Version - 1.4.1591, R Version - 4.0.3, Windows 10 - Desktop 

Tested running empty r chunks in RMarkdown, no additional environment variables are being created. I again missed the daily build window where this issue could be reproduced, so did a comparison test between 1.4 Tiger Daylily and current 1.4 Juliet Rose to confirm consistent functionality.

@ntluong95 - thanks again for bringing this issue to our attention. The fix is now available in our latest [Daily builds](https://dailies.rstudio.com/) of the upcoming 1.4 Juliet Rose release.
