### ISSUE TITLE
Tooltip in the console stop icon should say "Interrupt Python" instead of "Interrupt R"

### ISSUE THREAD

**Issue by astayleraz** [rstudio/rstudio#8838]
### System details

    RStudio Edition : Desktop
    RStudio Version : Version 1.4.1527
    OS Version      : 10.15.17
    R Version       : 4.0.3

### Steps to reproduce the problem

Run the following code in Python:
```
import time
time.sleep(60)
```
When the Stop button is displayed, mouse over it to observe the tooltip

**Note**: requires the development version of reticulate for interrupt support. Install it with:
remotes::install_github("rstudio/reticulate")

### Describe the problem in detail
<img width="809" alt="Screen Shot 2021-01-28 at 11 16 57 AM" src="https://user-images.githubusercontent.com/1482677/106182285-d8abfb80-615b-11eb-9158-2b1c0bc32de9.png">

The tooltip is misleading and makes me think R is running.

### Describe the behavior you expected
If I am running Python I would expect the stop button to say Interrupt Python.

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by romainfrancois** [comment]
Seems fixed. Tested in server: 

<img width="135" alt="image" src="https://user-images.githubusercontent.com/2625526/193868812-8ad33987-e3a0-4652-b0aa-575a3c1271a9.png">

and daily build RStudio 2022.11.0-daily+240 "Elsbeth Geranium" (but has probably been fixed for a while, since #9337)

<img width="138" alt="image" src="https://user-images.githubusercontent.com/2625526/193870047-9eb7aaec-8aa0-4f80-ad50-12e3f6819cd5.png">
