### ISSUE TITLE
Missing '#include <sys/socket.h>' and '#include <netinet/in.h>' in src/cpp/shared_core/system/PosixSystem.cpp

### ISSUE THREAD

**Issue by yurivict** [rstudio/rstudio#8890]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1103
    OS Version      : FreeBSD 12.2
    R Version       : 4.0.3

### Describe the problem in detail
This line https://github.com/rstudio/rstudio/blob/master/src/cpp/shared_core/system/PosixSystem.cpp#L115 breaks:
```
usr/ports/devel/RStudio/work/rstudio-1.4.1103/src/cpp/shared_core/system/PosixSystem.cpp:115:45: error: member access into incomplete type 'struct sockaddr'
        sa_family_t family = pAddr->ifa_addr->sa_family;
                                            ^
```

```#include <sys/socket.h>``` is missing.

Subsequent lines also require ```#include <netinet/in.h>```.

**Comment by yurivict** [comment]
ping.

**Comment by yurivict** [comment]
ping

**Comment by atheriel** [comment]
It looks like this is due to the fact that Linux and macOS both import `netinet/in.h` via `netdb.h`, while FreeBSD does not:

* FreeBSD: https://codeberg.org/FreeBSD/freebsd-src/src/branch/main/include/netdb.h
* Glibc [does so via](https://elixir.bootlin.com/glibc/latest/source/include/netdb.h#L214) `netgroup.h` -> `nsswitch.h` -> `netinet/in.h`
* macOS: https://opensource.apple.com/source/Libinfo/Libinfo-391/lookup.subproj/netdb.h.auto.html
* OpenBSD has it too: https://cvsweb.openbsd.org/src/include/netdb.h?rev=HEAD
* And Musl: https://elixir.bootlin.com/musl/latest/source/include/netdb.h

FreeBSD isn't a supported platform so we don't usually special-case it, but the POSIX specification [seems to suggest](https://pubs.opengroup.org/onlinepubs/009695399/basedefs/netinet/in.h.html) that the canonical definitions are in `netinet/in.h`, so maybe we should indeed include it explicitly.

**Comment by atheriel** [comment]
I don't have a FreeBSD test environment, but maybe someone who does can submit a patch and verify that it fixes the build.

**Comment by yurivict** [comment]
not stale
