### ISSUE TITLE
Daemonized server process still prints to its standard error

### ISSUE THREAD

**Issue by yurivict** [rstudio/rstudio#8916]
### System details

    RStudio Edition : Server
    RStudio Version : 1.3.1093
    OS Version      : FreeBSD 12.2
    R Version       : irrelevant

### Describe the problem in detail
The server prints messages like this:
```
07 Feb 2021 03:14:59 [rsession-yuri] WARNING Unable to determine LANG (proceeding with no LANG set; LOGGED FROM: void rstudio::core::r_util::ensureLang() src/cpp/core/r_util/REnvironmentPosix.cpp:942
```

All messages should be printed to the log file or to ```syslog(3)``` interface.

Nobody is reading what daemons print to their standard output and standard error.

Also, ```rserver --help``` doesn't contain "-o {logfile.log}" where messages could be logged.
This is a common practice for daemons.

**Comment by yurivict** [comment]
ping.

**Comment by mikebessuille** [comment]
I think this has now been addressed as of Ghost Orchid.  See the release notes for Ghost Orchid here: https://www.rstudio.com/products/rstudio/release-notes/

In particular,
## Logging
In an effort to help make the RStudio Team products more cohesive, logging has been changed significantly.
By default, server logs will now be written to file instead of syslog. Warnings and errors will still log to syslog. This can be controlled by the warn-syslog parameter in logging.conf.
By default, server logs will now be written under /var/log/rstudio/rstudio-server.
Logs can now be written in JSON lines format.
Reloading the logging.conf configuration by sending a SIGHUP to the rserver process will now cause all RStudio managed subprocesses to also refresh their logging configuration.
Logging can now be partially configured using environment variables (RS_LOGGER_TYPE, RS_LOG_LEVEL, RS_LOG_MESSAGE_FORMAT, and RS_LOG_DIR).
Log files will now rotate by time in addition to the existing rotation by file size. This can be controlled by the rotate-days parameter in logging.conf.
For more information, see section 2 of the Admin Guide.

**Comment by mikebessuille** [comment]
@yurivict, If this addresses your issue, we should close this.
