### ISSUE TITLE
Visual editor duplicates and moves anchor tags when in proximity to references

### ISSUE THREAD

**Issue by conig** [rstudio/rstudio#8980]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.1575
    OS Version      : Windows 10 19042.804
    R Version       : 4.0.4

### Steps to reproduce the problem
1. Create an rmarkdown with the following text:
```
---
output: pdf_document
---
Text [@ref]. [Anchor text [@ref2] around ref]{#anchortag}.

```
2. Switch to visual editor
3. Switch to source editor
4. Switch to visual editor
5. Switch to source editor

### Describe the problem in detail
markdown anchors are moved and duplicated by the visual editor breaking their functionality. 
The steps above produce the following source text:
```
Text [@ref]. [Anchor text [@ref2]{#anchortag}][ around ref]{#anchortag}.
```
This seems dependent on configuration of references as above or similar.

### Describe the behavior you expected
The source code should not be modified by the visual editor.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by ronblum** [comment]
@conig Thank you for raising this! Using the visual editor can change the source code according to standard Pandoc rules: https://rstudio.github.io/visual-markdown-editing/#/markdown However, I'll mark this as a bug to review.

**Comment by jjallaire** [comment]
Should be fixed with this: https://github.com/rstudio/rstudio/commit/0a070e3c51ca32b6470092b5907bc3803f2eb2ff

@dragonstyle, you can actually repro this even more simply with:

```markdown
Text [@ref]. Text [@ref2].
```

Basically, two cites in the same line. The problem was that in our appendMarkTransaction handler for cites we were recognizing all of the text from the first bracket in the paragraph to the last bracket in the paragraph as a single cite mark.

I discovered that there were two regexes in there that each could trigger this independently. Here are the changes I made to them:

<img width="973" alt="Screen Shot 2021-07-25 at 8 02 41 PM" src="https://user-images.githubusercontent.com/104391/126917779-fd438d5d-0e71-4e25-81e5-507b11a40b09.png">

For the first one, I just made the match after the first bracket non-greedy (so that it terminate as soon as a `]` appears). For the second, I required that whitespace (rather than any characters) appear between the cite_id and the suffix.

Asking you to further review this b/c those regexes are also used elsewhere and I want to make sure that these modifications don't somehow trip up those other uses.

**Comment by dragonstyle** [comment]
This seems like a great fix - I don't think it will cause other problems (and it sure may fix other problems...)
