### ISSUE TITLE
Quick accesss to "Show Folders in New Window"

### ISSUE THREAD

**Issue by Sibojang9** [rstudio/rstudio#9044]
For the recent Rstudio 1.4.1103 , there is no quick access to  "Show Folders in New Window" since it is way down located under the the More menu and no keyboard shortcut is allowed to be assigned to this function either.  It will be much more handy if "Show Folders in New Window"  can be lifted up to the top menu or be allowed to assign a keyboard shortcut.
![snap1142](https://user-images.githubusercontent.com/11802171/109440172-1c598580-79e6-11eb-8653-9eb3720c51af.jpg)
![snap1143](https://user-images.githubusercontent.com/11802171/109440206-33987300-79e6-11eb-83db-333ab34cb6ea.jpg)

**Comment by ronblum** [comment]
@Sibojang9 Thank you for the suggestion! We'll review it as we continue development of RStudio, at least for adding a keyboard shortcut.

In the meantime, this may not be any faster, but if you'd like to work just with the keyboard, you may do so with the Command Palette: <kbd>Shift-Cmd-P</kbd> then start typing the name of the command; `Show Folder` should be sufficient. Also, in the release currently being worked on (1.4 Juliet Rose at https://dailies.rstudio.com/), the command palette will remember your command history, so that next time "Show Folders in New Window" will be the first available, default command.
