### ISSUE TITLE
Clicking on a citation doesn't allow the key to be deleted and clicking on another one overwrites it

### ISSUE THREAD

**Issue by ronblum** [rstudio/rstudio#9124]
### System details

    RStudio Edition : Desktop and Server
    RStudio Version : 1.4.1106 and 1.4.1627
    OS Version      : MacOS 11.3 and Red Hat 8.3 via Chrome on MacOS 11.3
    R Version       : 4.0.4

### Steps to reproduce the problem

1. Open an R Markdown document.
2. Switch to visual mode if not already in it.
3. <kbd>Insert -> Citation</kbd>
4. Choose a source. (I tried it with a local reference and PubMed.)
5. Search for records.
    - Wait for results to appear.
6. Click on one of the results (not the plus sign).
    - The key will appear in the "Selected Citation Keys" bar.
7. Click on the X in the key to remove it.
    - Nothing happens.
8. Click on the plus sign next to a citation—the same as before or a different one.
    - The previous entry is removed.
    - The new key shows up.
 9. Click on the X in the key to remove it.
     - The key is properly removed.

### Describe the problem in detail

1. If a citation entry is clicked in search results, the key appears in the bar, but it can't be deleted. (Step 7)
2. If a citation is clicked on—but not the plus—its key appears, but if another one is selected by clicking on it or the plus sign, the new key replaces the old one. (Step 8)

### Describe the behavior you expected

1. Any key that appears in the "Selected Citation Keys" bar should be removed if its X is clicked.
2. Keys that previously showed up because of a non-plus click should not be deleted when a new key is chosen; or, keys should only be included if the plus sign is clicked.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by mikebessuille** [comment]
Melissa - add automation, Ron manually verify

**Comment by melissa-barca** [comment]
@ronblum @dragonstyle I'm still seeing this issue when choosing "From DOI" as my source. I no longer see it with any of the other sources.

**Comment by dragonstyle** [comment]
This should be fixed in #10201

**Comment by dragonstyle** [comment]
(I applied test tag, thinking that was correct next step, but please adjust as necessary)

**Comment by melissa-barca** [comment]
All automated tests are now passing with the daily builds, @ronblum if this passes your verification, please close it.

**Comment by ronblum** [comment]
Tested DOI using the following values:
- 10.1093/ajae/aaq063
- 10.1371/journal.pgen.1001111
- https://doi.org/10.1080/15588742.2015.1017687
[Ref https://guides.lib.montana.edu/doi#s-lg-box-3940185 and https://www.iirp.edu/images/pdf/What-is-a-DOI-060617.pdf]

Verified that delete now works for it. However, when
1. Clicking on the record, not the plus sign: adds citation key
2. Clicking on another record or the plus sign: the previous citation key is removed and the new key is added.

Should I file this as a separate issue?

**Comment by ronblum** [comment]
Tested DOI using the following values:
- 10.1093/ajae/aaq063
- 10.1371/journal.pgen.1001111
- https://doi.org/10.1080/15588742.2015.1017687
[Ref https://guides.lib.montana.edu/doi#s-lg-box-3940185 and https://www.iirp.edu/images/pdf/What-is-a-DOI-060617.pdf]

Verified that delete now works for it. However, when
1. Clicking on the record, not the plus sign: adds citation key
2. Clicking on another record or the plus sign: the previous citation key is removed and the new key is added.

@dragonstyle Should I file this as a separate issue?

**Comment by dragonstyle** [comment]
That is definitely another issue, but I think it may be by design. The dialog is trying to enable two significant use cases:

1) Enable easy selection of a single entry to insert.
2) Enable the selection of multiple entries to insert.

It is tough to make both of these first class (e.g. we could always require the user to tap the '+' icon to add an entry, but that makes adding a single entry now take 2 clicks). What we ultimately decided to do was to make the dialog do the following:

- If an entry is selected (showing the selection treatment), it will appear in the list of citations. As you move selection around (e.g. arrow up or down), the entry in the citation list should change to reflect the currently selected item. Deleting the entry from the list of citations effectively unselects it, those removing it from the list.

- If you'd like to add an entry to the list that doesn't depend upon selection, tap the plus icon. That item will stay in the list until it is removed, no matter how selection changes.

This was our best compromise to enable very simple single item add (uses selection) and the idea of accumulating multiple items to add (hitting the plus).

If this is what you're seeing (I think it is?), this is by design. If you're seeing something different, seems like it should be a bug and a distinct one from this bug.

**Comment by ronblum** [comment]
@dragonstyle This is what I'm seeing, and it applies to all entries. I'll close this. Thanks!
