### ISSUE TITLE
read_dta attributes issue

### ISSUE THREAD

**Issue by rudjer** [rstudio/rstudio#9209]
I have a reprex in which the data frame produced by read_dta generates an error, while if I convert it to matrix and back to data frame (thereby stripping the stata attributes), it runs without any problem.  Admittedly, this may be attributable to some blunder in the coding in my quantreg package, if so, I would be happy to learn about that.

require(haven) # for reading dta file
#Ddta <- read_dta("regional_ITN_indicators_access.dta")
#D <- with(Ddta, data.frame(y = access_merg, x = meannets_allhh, z = meanhh))
#save(D, file = "D.Rda")
#load("D.Rda")
con <- url("http://www.econ.uiuc.edu/~roger/research/data/D.Rda")
load(con)

# If I purge the Stata attributes:
A <- as.matrix(D)
B <- as.data.frame(A)

# This works:
with(D,plot(x, y, cex = .5, col = "grey"))
taus <- 1:4/5
require(quantreg)
for(i in 1:length(taus)){
    f <- rqss(y ~ qss(x, constraint = "I", lambda = 1), tau = taus[i], data = B)
    plot(f, add = TRUE, col = i)
}
# However, the same code with data = D, does not.  Why?

**Comment by ronblum** [comment]
@rudjer Thank you for raising this! This repository is meant for bugs and enhancements, rather than addressing R coding. However, I'm not sure whether or not this is a bug or an R coding issue. A few things:

1) Can you include the exact code that fails? I'm not sure where to insert `data = D`.
2) The lines with `read_dta` and below are commented out. Should these be run? And if so, can you provide a sample file?
3) Can you provide the following so that we're looking at the same environments?

###
    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       : 

Thanks!

**Comment by rudjer** [comment]
The comments were only to indicate how the file D.Rda was created...  The rest can be run as is, and (obviously, or at least I thought it was obvious) the rest of the uncommented code can be run as is.  I don't use Rstudio so  my experience is from a terminal on a mac mini.  Again, obviously, you were intended to replace data = B by data = D.  The point is that without the attributes created by read_dta the example runs without error, with them it fails.

R Under development (unstable) (2021-02-19 r80028) -- "Unsuffered Consequences"
Copyright (C) 2021 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin17.0 (64-bit)

**Comment by ronblum** [comment]
Ah! This is occurring outside of RStudio (which I've just confirmed, as well). Is this the error you're getting?
```
Error: object of type 'closure' is not subsettable
```

In that case, since it's outside of RStudio, a few places that could be helpful are [the RStudio Community](https://community.rstudio.com/) and [Stack Overflow](https://stackoverflow.com/questions/tagged/r). They're both good places to ask questions, and it's also possible that someone has run into a similar issue.
