### ISSUE TITLE
Add 'delete' to the git pane

### ISSUE THREAD

**Issue by OfekShilon** [rstudio/rstudio#9310]
Two suggestions that would make my life noticeably easier:
(1) Add 'sync location' from editor to the files pane: when invoked, the files pane will navigate to the currently active file in the editor.  If you do - please make it bindable to a keyboard shortcut.
(2) Add 'delete' to the git pane, either in the context menu or (better) on 'delete' keypress.  If somehow this is hard, add 'sync location' from the git pane to the files pane too.

**Comment by jmcphers** [comment]
The first is already effectively done in our Ghost Orchid release (1.5, will be in dailies next week). To use it 

1. In the Files pane, click "More...", then check Synchronize Working Directory
2. Bind a keyboard shortcut to the command *Set Working Directory to Current Document's Directory*

Now whenever you execute your shortcut, the working directory in R will change and the Files pane will pick it up. More details in this PR: https://github.com/rstudio/rstudio/pull/9277

**Comment by colearendt** [comment]
👍

**Comment by ScientificProgrammer** [comment]
Hello Team

> 1. In the Files pane, click "More...", then check Synchronize Working Directory

I'm running the following version of RStudio.

```
RStudio 2021.09.0+351 "Ghost Orchid" Release (077589bcad3467ae79f318afe8641a1899a51606, 2021-09-20) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36

```
I just noticed the `Synchronize Working Directory` command toggle switch in the `Files` pane, but I couldn't figure out what it does. I checked the RStudio documentation, and when I didn't find any information there, I performed a Google search, and this discussion thread here on Github was the only link I could find discussing this feature.

After reading through this discussion thread, I think I understand what the command does, but I want to confirm my tentative understanding with you. Here is my understanding.

1. Open a *project* in RStudio.

1. In the `Source` pane, open a file that is not located in the directory that R is currently using as its working directory, *i.e.*, the result that is output by `getwd()`.

1. Right click on the *file* mentioned in the previous step and select the `Set Working Directory` option. Then, RStudio will instruct R to use that *file's directory path* as its active working directory. 

1. If `Synchronize Working Directory` is set to `TRUE`, RStudio will automatically update the `Files` pane to show the contents of the newly set working directory. Otherwise, if `Synchronize Working Directory` == `FALSE`, the `Files` pane will not update automatically, and for it to display the files in R's current working directory, a user would have to manually refresh the pane.

Is my understanding correct?

Thank you for the great work you do!
