### ISSUE TITLE
Tab key does not work properly

### ISSUE THREAD

**Issue by xec-cm** [rstudio/rstudio#9380]
### System details

    RStudio Edition : Desktop
    RStudio Version :  1.4.1106
    OS Version      :  macOS Big Sur
    R Version       :  4.0.3 (2020-10-10) -- "Bunny-Wunnies Freak Out"

### Steps to reproduce the problem

Install a new keyboard 

### Describe the problem in detail

After the installation of a new peripheral keyboard, the tab key no longer inserts tabs. Now when I press the tab key, the cursor is selecting the different selectable elements of the RStudio graphical interface. Now this problem occurs with my 3 keyboards, but only in RStudio since in vscode the tab key works as expected. I have tried reinstalling RStudio and deleting the ~/.local /shared /rstudio folder but it doesn't solve the problem.

### Describe the behavior you expected

I expect that when I press the tab key my cursor stays in the source pane and insert tabs. 

- [ x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x ] If I am reporting an RStudio crash, I have included a [diagnostics report]([diagnostics-report.txt](https://github.com/rstudio/rstudio/files/6517577/diagnostics-report.txt)).
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by gtritchie** [comment]
It sounds like the "Tab key always moves focus" setting is enabled? If so, try turning it off and see if that helps.

![screen shot of settings showing Tab Key Always Moves Focus checkbox](https://user-images.githubusercontent.com/10569626/119022060-07d9b900-b955-11eb-8b1e-6cd03209e9fc.png)

**Comment by xec-cm** [comment]
Solved! Thanks!

**Comment by Lulliter** [comment]
I think RStudio updates (2023.03.2+454 and up) automatically check that!

**Comment by gtritchie** [comment]
> I think RStudio updates (2023.03.2+454 and up) automatically check that!

@Lulliter I expect we'd have had a lot of complaints if this was happening to everyone who updates. Still, I don't want to assume there isn't a problem. What platform are you using (Windows, Mac, Linux)?

Any chance you might have accidentally triggered the keyboard shortcut that toggles this setting? It's <kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>[</kbd> on Windows and Linux, and <kbd>Ctrl</kbd>+<kbd>Opt</kbd>+<kbd>[</kbd> on Mac.

Be aware that in the most recent RStudio Release (2023.09.0) there is a bug where this command always shows as disabled (unchecked) in the menu (Help / Accessibility / Focus / Tab Key Always Moves Focus) even when it is enabled. That will be fixed in the first patch for 2023.09. Tracked here: #13710

If this shortcut conflicts with something on your system, you can remove it in Tools / Modify Keyboard Shortcuts; search for "Toggle Tab Key" and then delete the existing shortcut.
