### ISSUE TITLE
RStudio Download is damaged/cannot be opened/suggestion to move to trash 

### ISSUE THREAD

**Issue by AutumnInfandino** [rstudio/rstudio#9484]
Hello,
I have seen 4 emails since 6/4/21 that all mention when trying to download RStudio they get an error along the lines of “RStudio is damaged and can’t be opened” and to move it to the Trash, 3/4 specifically reference that they are using a Mac. Wanted to mention it in case there was an issue with the downloads. Relevant details from their emails below, TIA!

> I have been trying to download RStudio version RStudio-1.4.1717.dmg for MacOS High Sierra multiple times but it says that “RStudio is damaged and can’t be opened”. 

> When I try to install the latest open source desktop version I get a message saying the file is “damaged” and to move it to the Trash. Prior to attempting to install it I installed R-4.1.0 and XQuartz-2.8.1 and both installations went okay. I've done several downloads from the blue box with “DOWNLOAD RSTUDIO FOR MAC” written in it and from the “All Installers” list below without getting an undamaged file. I re-installed version 1.4.1106 which I had been using previously and it works fine with the new versions of R and XQuartz.  Some computer details: iMac with High Sierra version 10.13.6.

> I have attempted multiple times to download R Studio IDE for desktop over the past couple weeks and it keeps saying it is corrupted.

> I am running MacOS 10.13.6. I have used the main download portal on your site for the download. I have installed many different versions of R, including the most up to date one as well as 3.0.1. Every time I try to open RStudio, I get the message “RStudio is damaged and cannot be opened”.

**Comment by AutumnInfandino** [comment]
I think this community post also ties in and provides a possible solution https://community.rstudio.com/t/r-studio-is-damage-and-cant-be-opened-after-dragging-to-application-folder/106695/3.

**Comment by gtritchie** [comment]
Copying the workaround from the community post as a reference:

> The problem seems to be related to MacOS's app verification not playing nicely with this version of RStudio. As a result, the app retains its "quarantine" attribute and cannot bypass the verification. You can remove that attribute (proceed at your own risk) by using
>
>xattr -d com.apple.quarantine /Applications/RStudio.app/

**Comment by jmcphers** [comment]
I think this is also the source of this community forum issue: 

https://community.rstudio.com/t/rstudio-1-4-1717-is-failing-on-os-x-10-13-6-verification/107121

**Comment by jmcphers** [comment]
@AutumnInfandino After some research we've discovered that macOS 10.13 is no longer a supported OS (not even by Apple themselves), which is why it is not receiving the patches that would be required for it to verify apps built on newer versions of macOS. 

https://en.wikipedia.org/wiki/MacOS_High_Sierra

(Realize that Wikipedia isn't a primary source; their claim is based on the fact that Apple, while they don't publish EOL dates has stopped releasing security updates to High Sierra as of 12/2020.) 

We will be updating our platform support and download pages to make it clear that we don't support macOS 10.13 due to lack of vendor support. For customers who can't update macOS, they can use the workaround @gtritchie references.
