### ISSUE TITLE
Intermittent failure to extract soci on Windows builder

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#9497]
This is an issue with the Docker-based builder for Windows.

Every so often the attempt to install the dependencies inside the running container fails as follows:

```
 --> Unzipping SOCI sources
[2021-06-09T20:15:06.437Z] > 7z.exe e soci.tar.gz
[2021-06-09T20:15:06.437Z] FATAL: Command exited with status 7.
[2021-06-09T20:15:06.437Z] Logs written to c:\Users\jenkins\workspace\ide\open-source-pipeline\v1.4-trampled-dandelion\dependencies\windows\install-soci\logs\7z.exe-output-13b0584321d5.txt:
[2021-06-09T20:15:06.437Z] 
[2021-06-09T20:15:06.437Z] 7-Zip [32] 16.04 : Copyright (c) 1999-2016 Igor Pavlov : 2016-10-04
[2021-06-09T20:15:06.437Z] 
[2021-06-09T20:15:06.437Z] 
[2021-06-09T20:15:06.437Z] 
[2021-06-09T20:15:06.437Z] Command Line Error:
[2021-06-09T20:15:06.437Z] Unsupported command:
[2021-06-09T20:15:06.437Z] .exe
```

The build then proceeds, and ultimately fails with:

```
[2021-06-10T18:04:55.910Z] C:\Users\jenkins\workspace\ide\open-source-pipeline\v1.4-trampled-dandelion\src\cpp\core\include\core/Database.hpp(27): fatal error C1083: Cannot open include file: 'soci/soci.h': No such file or directory
```

The SOCI unzip happens here:

https://github.com/rstudio/rstudio/blob/dd2b5b4d74da77b797c4ae96b05df90751f18a3f/dependencies/windows/install-soci/install-soci.R#L68-L69

Only workaround we've found is to connect to the running container and manually decompress the archive.

**Comment by stevenolen** [comment]
what a funny error. I've got a couple ideas on how to break through. Be warned, they have varying levels of dumbness:

Have you tried passing the full path to that executable to see if this error is less frequent?
Additionally, what happens if you restart the build pipeline, does it work on the second try? 
The jenkins step that install dependencies could also have a retry in it, and after this step you could do a file lookup to ensure soci exists and "exit 1" if it doesn't (therefore triggering the jenkins retry logic to re-rerun the install dependencies step)

**Comment by gtritchie** [comment]
In the past the error manifested differently, making it appear additional (incorrect) arguments had been passed.

Rerunning hasn't helped.

Will be adding a check like you describe to bail early if the expected file isn't extracted.

Using full path can't hurt and might provide something interesting so will look at that, too.

**Comment by jmcphers** [comment]
Finally got to the bottom of this one (almost). The problem turns out to be a combination of seemingly unrelated factors.

We have a copy of 7zip in the repo, here: https://github.com/rstudio/rstudio/blob/main/dependencies/windows/tools/7z.exe . It was added to permit unzipping Boost sources w/o external dependencies in https://github.com/rstudio/rstudio/commit/46484a7b1d200bbf888cc2982224d93def602144. 

This copy takes precedence over the much newer 64 bit 7zip which we install inside the Windows container: https://github.com/rstudio/rstudio/blob/0c2d46e04b8d1ef9c738737df4e03c3c1ae30892/docker/jenkins/Dockerfile.windows#L24

As a result, the `7z.exe` executed by this script is inside the tools directory, which can be verified with `Sys.which()`:

```r
> Sys.which("7z.exe")
                                                                                                               7z.exe
"C:\\Users\\jenkins\\workspace\\ide\\open-source-pipeline\\v1.4-trampled-dandelion\\DEPEND~1\\windows\\tools\\7z.exe"
```

It appears that R has a bug when dealing with very long executable paths on Windows; the string math isn't done correctly and as a result the command receives part of its own path as an argument. You'll note this one is so long (in part due to the long branch name) that it has to get shortened.

To verify this I did some tests:

- If the given path to the executable changes, the error message changes as well. For example, changing the command to `7z` instead of `7z.exe` (reducing by four bytes) adds another four bytes to the error message as well, so that it reads `Unsupported command: s\7z.exe`. 
- If the `7z.exe` file in `tools` is renamed so that it is no longer on the `PATH`, and `Sys.which("7z.exe")` returns the copy in `C:\ProgramData\chocolatey\bin`, then everything works fine.
- If the `7z.exe` file from Chocolatey is copied into the `tools` folder, then we get the same error message. This implies that the problem is the location of 7zip, not 7zip itself. 

Not sure where R's making a mistake, but this looks like a possible culprit:

https://github.com/wch/r-source/blob/79298c499218846d14500255efd622b5021c10ec/src/gnuwin32/run.c#L45-L48

I think the right fix here is to either remove 7zip from our repo entirely, or to ensure that we prefer a system 7zip (if available) to the one in the repo.

**Comment by kevinushey** [comment]
Another fix, I think, would be to just use the name of the executable and rely on the system to resolve the "right" version on the PATH.

**Comment by kevinushey** [comment]
Ah, sorry, I misunderstood -- I thought we had hard-coded the path to the `7z.exe` executable in the tools folder.

Given that we only need 7zip to build our dependencies and not to download / install them, I'd be okay with removing it from the repository as well.

**Comment by AndrewMcClain** [comment]
Already completed by https://github.com/rstudio/rstudio/commit/02dc65df728483aa89408d11101c26e25ae65d00
