### ISSUE TITLE
Removing values containing a space in their name

### ISSUE THREAD

**Issue by giribet00** [rstudio/rstudio#9525]
Suppose I have created a variable that contains a space in its name:

```
`Variable A` <- 5
```

Deleting it with ```rm(`Variable A`)``` will effectively delete it. However, the environment window - by default in the top right section - will still show it until you refresh. I haven't noticed this behaviour with any other type of object.

Thanks.

**Comment by ronblum** [comment]
@giribet00 Thank you for raising the issue! I can't reproduce it in RStudio Desktop or Server. Can you please provide the system details, so that we can try to reproduce the issue in a similar environment?

### System details

    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       : 

By the way, if you need to include the tick marks in the code, you can surround it with multiple ticks, e.g.

````
```
`Variable A` <- 5
```
````
