### ISSUE TITLE
Recognize comments beginning with a hash in .sql files

### ISSUE THREAD

**Issue by Mosk915** [rstudio/rstudio#9578]
Some databases such as MySQL and MariaDB recognize single-line comments that begin with a hash (#).  It would be useful if RStudio could recognize these types of comments  in .sql files and color code them as such.

![image](https://user-images.githubusercontent.com/59397359/124955131-cffe0200-dfe4-11eb-90a6-be2b674264e6.png)

**Comment by ronblum** [comment]
@Mosk915 Thank you for the suggestion! I'll mark this for review as part of our ongoing development of RStudio.

**Comment by kevinushey** [comment]
The rule could be added here:

https://github.com/rstudio/rstudio/blob/abafb3817a6c566b7b80d02a1f852170a6b6aa4b/src/gwt/acesupport/acemode/sql_highlight_rules.js#L56-L59

Good first issue for someone who wants to get familiar with Ace's highlight rules.

**Comment by ronblum** [comment]
Verified in
- RStudio Desktop 2022.02.0+364 on MacOS 12.1
- RStudio Server 2022.02.0+364 on Ubuntu 20.04 via Chrome on MacOS 12.1

using the following:
```
# This is a comment
/* This is also a comment */
-- This is another comment

SELECT 1
```

However: This doesn't distinguish between DBMS vendors. This means that:
1) The IDE will do so both when `#` is a valid way to identify a comment (like MySQL) and when it's not (most vendors, e.g. PostgreSQL). When the latter is run, any line beginning won't be treated as a comment—it'll result in an error.
2) `#` is used in SQL Server to identify temporary tables. So now, those are showing up as comments: 
![hashtag.png](https://codetreeusercontent.s3.amazonaws.com/uploads/94f998fd-93e2-4637-a7bc-8cbe7ca3d293/hashtag.png)

I think we should reconsider making this change, unless we can control for this based on the destination DBMS, since in most cases identifying this as a comment will be incorrect.

**Comment by timtmok** [comment]
@kevinushey I don't see anything to set a flavour of SQL. This looks like it would require a bigger change to support # comments for MySQL. I don't know how customizable Ace is with the highlighting but I think the proper change is allowing users to have SQL options in the preferences for setting the comment marker.

**Comment by kevinushey** [comment]
Perhaps a simple change for now would be to only allow `#` for comments at the beginning of a line?

**Comment by ronblum** [comment]
@kevinushey I like this solution of `#` at the beginning of a line equals a comment.

**Comment by timtmok** [comment]
Good idea. The start of line is a fair compromise for now. I'll put up a PR!

**Comment by ronblum** [comment]
Verified in
- RStudio Desktop 2022.02.0+366 on MacOS 12.1
- RStudio Server 2022.02.0+366 on Ubuntu 20.04.3 via Chrome on MacOS 12.1

Also checked that there was no impact to the use of `#` in R files (comments) and R Markdown files (comments in chunks, heading or text in the body).
