### ISSUE TITLE
visual editor quote and en-dash symbol conversion creates unintended source markdown

### ISSUE THREAD

**Issue by jjallaire** [rstudio/rstudio#9680]
Discussion here:

https://community.rstudio.com/t/how-to-disable-symbol-conversion-in-rstudio-visual-markdown-mode-to-prevent-damage-of-content/110725

**Comment by GegznaV** [comment]
I copy the original message here:

***

I use R Markdown editor in RStudio (1.4.1717). I created `.Rmd` file with contents like this:

```markdown
The closing quote must not be changed „here“.

Interval -2–-1: the combination of – (en dash) and hyphen must not be changed into ---
```

[![enter image description here][1]][1]


After switching to Visual Markdown and back to regular markdown editor, the contents were changed into:

```markdown
The closing quote must not be changed „here".

Interval -2---1: the combination of -- (en dash) and hyphen must not be changed into ---
```

[![enter image description here][2]][2]

The same happens when I save the Rmd file in the Visual Markdown editor.

- Here `„` was changed into `"`. In English, it would be OK, but in my language, these are two different symbols. The text got distorted in an unwanted way.
- Next, interval "from minus two to minus one" was converted into "from minus two to (plus) one".  This changed the meaning of the content.

Sometimes I copy-paste pieces of text into R Markdown file, sometimes I want to use Visual mode on old Rmd files in which non-Englis language is used. If these conversions happen and the user does not notice them on time, the damage can irreversible.

**Question:** How can these unwanted symbol conversions be reliably disabled in RStudio? 

  [1]: https://i.stack.imgur.com/YXoJq.png
  [2]: https://i.stack.imgur.com/j7Q72.png

**Comment by jjallaire** [comment]
With this commit (https://github.com/rstudio/rstudio/commit/9ee27901ec563c6d71a3ad6c570fc9ab0f2565c1), this can now be prevented by disabling the `smart` extension for the editor:

```yaml
---
title: "My Document"
editor_options:
  markdown:
    extensions: -smart
---
```

**Comment by valerie-rstudio** [comment]
### Verified Fixed

    RStudio Edition : Server
    RStudio Version : 2021.12.0-daily+80
    OS Version      : ubuntu20
    R Version       : 4.0.3

Verified that the unwanted symbol conversions are now prevented by disabling the smart extension for the editor.

**Comment by GegznaV** [comment]
1. Can this behavior be set as the default in RStudio?
2. Is it documented? If yes, please, add the link to this thread?

**Comment by GegznaV** [comment]
And how this be controlled in, e.g., `bookdown` projects, where `.Rmd` files of chapters do not contain YAML header. Is it sufficient to set this option in any of the setup files. E.g., in `index.Rmd`?
