### ISSUE TITLE
Object size not shown when containing environment attributes

### ISSUE THREAD

**Issue by david-cortes** [rstudio/rstudio#9686]
**Steps to reproduce:**
* Create a list object with another list object inside having objects which together would sum to a large enough memory footprint so as to have it indicated in the environment pane. Example:
```r
my_list <- list(
    obj = list(v = numeric(1e7))
)
```
* Look at the environment pane, hover the mouse over the position where `my_list` is shown, and confirm that it shows the size.
* Convert the inside list object to an environment:
```r
my_list$obj <- as.environment(my_list$obj)
```
* Look again at the environment pane, perhaps refresh it if needed.

**Expected behavior:** should show the size of the object like before.

**Actual behavior:** does not show the size of the object anymore.

**Comment by david-cortes** [comment]
@ronblum Sorry, edited the example - now it runs correctly and showcases the issue.

**Comment by kevinushey** [comment]
This is because of how R computes the size of environments:

```
> long <- numeric(1E7)
> object.size(long)
80000048 bytes
> object.size(globalenv())
56 bytes
```

And we don't show the size of "small" objects in the environment pane. IIRC there are a variety of discussions e.g. on R-devel as to why asking for the size of an R object is a bit of a misfeature (primarily because data can potentially be "shared" or referenced in multiple environments, and so the sum of the amount of memory used by each object in the global environment isn't necessarily the total amount of memory used)
