### ISSUE TITLE
View blame on Github opens master branch even when there is not master (instead of local branch or main branch)

### ISSUE THREAD

**Issue by cderv** [rstudio/rstudio#9798]
### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 2021.11.0.23 (daily)
    OS Version      : Windows 10 x64 (build 19043)
    R Version       : R version 4.1.0 (2021-05-18)

### Steps to reproduce the problem

1. Open RStudio version (daily) 
2. Create a new project from Git using : https://github.com/rstudio/rmarkdown/ (place it in a folder without name conflict)
3. Create a new branch locally that won't be pushed / tracked on remote 
   `git checkout -b dummy` 
3. Open README.md (`file.edit("README.md")`)
4. Click on the button to view blame for the file (or CTRL + MAJ + P and search "blame" for "View Git Blame on Github"
5. This will go to https://github.com/rstudio/rmarkdown//blame/master/README.md which does not exist instead of https://github.com/rstudio/rmarkdown//blame/main/README.md 
   (not the double slash also but that is not part of the problem)
6. Click "View file on Github" will open https://github.com/rstudio/rmarkdown/blob/master/README.md which is also wrong, but will work because Github redirect to https://github.com/rstudio/rmarkdown/blob/main/README.md
7. When doing the same on a synced branch, the correct branch name is used and correct url is opened.

Cleaning: Remove the created project from your computer.

### Describe the problem in detail

In a project using Git, with a remote available, using `main` and not `master` as main branch (like rstudio/rmarkdown), when a file is opened, one can click on "Blame on Github" button. 
When the file is from a branch that is not yet think, looking at the blame will send to a url using `master` by default, which no more exist. It does not link to the `main` branch in this case. 

I think `master` is used as default when no remote branch is tracked with the current local branch. 

### Describe the behavior you expected

The blame view should not be opened on `master` because it could not exist (renamed `main`). It should be opened on the default branch called `main` (or else ?)
Same for "View File". 

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jennybc** [comment]
I just bumped into this, but purely using "View file on GitHub", i.e. not doing anything re: git blame.

In general, the repos I work in used to use `master` but now use `main`, i.e. we moved the default branch in 2021 (https://www.tidyverse.org/blog/2021/10/renaming-default-branch/).

Today was actually the first time I used "View file on GitHub" in RStudio! I then got very puzzled because my local version of the file had many more lines than what I saw on GitHub 🤔 Then I inspected the URL and realized I was seeing the file circa 2 years ago, the last time a commit was made on `master`.

> Click "View file on Github" will open https://github.com/rstudio/rmarkdown/blob/master/README.md which is also wrong, but will work because Github redirect to https://github.com/rstudio/rmarkdown/blob/main/README.md

I would claim that this does not really work, although it sort of feels like it's working, because it's actually showing you an old version of the file. I'm not getting a redirect to the `HEAD` of `main`, which would be correct.

While trying to reproduce this, I've noticed that repeated or subsequent attempts to view a file on GitHub *do* start to correctly show me `main` instead of `master`.

I have no idea if this is because RStudio has started constructing the URL with the right branch (`main` instead of `master`) or if GitHub's redirect kicks in after the first attempt?

**Comment by jennybc** [comment]
Now I can reproduce this. I'm encountering this when I've created a local branch but haven't pushed. So there's no upstream branch yet, which then sends "View file on GitHub" down this fallback path which is hard-wired to prefer `master` and `origin/master`.

```
~/rrr/testthat % git rev-parse --abbrev-ref @{upstream}                              
fatal: no upstream configured for branch 'snapshot-local-interactive'
```

https://github.com/rstudio/rstudio/blob/a5b19b2c35c30da2c130b6094ba32dcb49252264/src/cpp/session/modules/SessionGit.cpp#L2163-L2172

**Comment by kevinushey** [comment]
What do you think the right behavior here is? Should we just produce a warning / error stating that the current branch hasn't been configured with an upstream remote?

**Comment by jennybc** [comment]
I would be happy to see my default branch in the "no upstream" case (so: `main` instead of `master`, usually). Maybe the fallback should be updated to reflect new conventions around `master` vs. `main`?

Or an error is probably better than showing something wrong/out-of-date. VS Code seems to make you pick the branch from a dropdown in the "no upstream" case.

FWIW for a git remote, a reasonable definition of the default branch is "whatever `HEAD` points to". So there is a pure git way to determine what `origin` thinks the default branch is. usethis does this when we want to know a GitHub remote's default branch and we're not sure we can use the GitHub API (which *does* report the default branch explicitly):

https://github.com/r-lib/usethis/blob/467ff57f92afb34878dc411c46e3f0de029ceea4/R/git-default-branch.R#L219-L221

**Comment by jennybc** [comment]
Actually if all you need is a URL to visit in the browser, the fallback can just be `https://github.com/{owner}/{repo}/blob/HEAD/{path}` and there's no need to figure out what the default branch is. `HEAD` will put you there. Then the fall back logic reduces to assuming `origin` is the right remote to consult to learn about `owner` and `repo`.

**Comment by timtmok** [comment]
I think the fallback should be the commit hash if there's no default branch. This would show the annotated file for the version that is checked out.

**Comment by jonvanausdeln** [comment]
Verified with [2023.12.0-daily+262](https://dailies.rstudio.com/version/2023.12.0-daily+262)
Windows 11, MacOS 12.6

Blame opens up to a github URL with commit ID. Still gives a 404 because the commit doesn't exist on remote (GitHub), but no longer tries to open the `master` branch
