### ISSUE TITLE
Error: pandoc document conversion failed with error 4

### ISSUE THREAD

**Issue by jpmaroco** [rstudio/rstudio#9807]
### System details

    RStudio Edition : desktop
    RStudio Version : 2021.09.0 Build 338
    OS Version      :  Win 10
    R Version       : "R version 4.1.1 (2021-08-10)"

### Steps to reproduce the problem

 I am trying to produce a pdf from a Rmd file using this code `rmarkdown::render(input = "Intro.Rmd",output_file ="Intro.pdf")`. It worked before, but now is given the error:
`"C:/Program Files/RStudio/bin/pandoc/pandoc" +RTS -K512m -RTS Intro.knit.md --to html4 --from markdown+autolink_bare_uris+tex_math_single_backslash --output Intro.pdf --lua-filter "D:\ONEDRI~3\RStudio\RMARKD~1\RMARKD~1\lua\PAGEBR~1.LUA" --lua-filter "D:\ONEDRI~3\RStudio\RMARKD~1\RMARKD~1\lua\LATEX-~1.LUA" --self-contained --variable bs3=TRUE --standalone --section-divs --template "D:\ONEDRI~3\RStudio\RMARKD~1\rmd\h\DEFAUL~1.HTM" --no-highlight --variable highlightjs=1 --variable theme=bootstrap --include-in-header "C:\Users\jpmar\AppData\Local\Temp\Rtmp0WIdtF\rmarkdown-str4d1436c9f8e.html" --mathjax --variable "mathjax-url:https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML" 
cannot produce pdf output from html4
Error: pandoc document conversion failed with error 4`

I have updated R for version 4.1.1 (from 4.0), and do regular update of packages. My rmarkdown version is  2.10.

Any idea on how to correct this error?
Thanks!

- [ ☓ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [☓ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by cderv** [comment]
Hi, 

I don't think there is an issue with RStudio IDE. 
This code 
```r
rmarkdown::render(input = "Intro.Rmd",output_file ="Intro.pdf")
```
only involves **rmarkdown** package. 

From what I can see of the command line output you pasted 

* `rmarkdown::render(input = "Intro.Rmd",output_file ="Intro.pdf")` => this means that you expect to convert to a PDF file. is that right ? 
* `C:/Program Files/RStudio/bin/pandoc/pandoc" +RTS -K512m -RTS Intro.knit.md --to html4` => this shows that you are converting the Rmd file to an HTML output format. At least Pandoc is seeing this. Hence the error, because you can't name a HTML output with a `.pdf` extension (here `--output Intro.pdf`) 

There must be something with your YAML header. 

* What is your YAML header ? 
* What output format are you using in it ? 
* For PDF, it should be `pdf_document` usually (or something derived from it like `bookdown::pdf_book`) 

Please, check your YAML header. The first will be used by default when you are using `rmarkdown::render()`. 
You can select the one you want by using something like 
```r
rmarkdown::render(input = "Intro.Rmd", output_format="pdf_document", output_file ="Intro.pdf")
```

to use the output format matching in your YAML header
````yaml
output:
  html_document: default
  pdf_document: default
```

Thanks.

**Comment by jpmaroco** [comment]
Hi Cristhoper,

Thanks for your prompt reply. The header of my Intro.Rmd file is:

---

header-includes:

- \usepackage{booktabs}

- \usepackage{longtable}

- \usepackage{array}

- \usepackage{multirow}

- \usepackage{wrapfig}

- \usepackage{float}

- \usepackage{colortbl}

- \usepackage{pdflscape}

- \usepackage{tabu}

- \usepackage{threeparttable}

- \usepackage{threeparttablex}

- \usepackage[normalem]{ulem}

- \usepackage{makecell}

- \usepackage{xcolor}

output:

  pdf_document:

    toc: no

    template: default.latex

    latex_engine: xelatex

    includes:

      in_header: header.tex

  always_allow_html: yes

  html_document:

    toc: no

    df_print: paged

editor_options:

  chunk_output_type: console

fontsize: 11pt

classoption: a4paper

mainfont: Arial #Adobe Garamond Pro #"Helvetica"

geometry:

- margin=1in

- right=.75in

---

 

The strange thing is that if I make my wd just “D:/Exam1” instead of "D:/OneDrive - ISPA/AEI/2020-2021/Exam1" it does work. I wonder if it has something to do with OneDrive syncing?

 

Warm regards, and thanks again

João

**Comment by cderv** [comment]
> The strange thing is that if I make my wd just “D:/Exam1” instead of "D:/OneDrive - ISPA/AEI/2020-2021/Exam1" it does work. I wonder if it has something to do with OneDrive syncing?

Yes it is possibly something related to onedrive thinking. I think we have some issues reported with that in the past. 

I can't clearly see why you would get this error though... but the fact that the document rendering works locally seems to indicate a remote issue. 🤔

**Comment by jpmaroco** [comment]
Yes, agree. I will stop onedrive sync and see if it helps…

Best regards
