### ISSUE TITLE
Cannot Connect to R in a Windows 10 Multi Host machine 

### ISSUE THREAD

**Issue by MaheshChellamuthu** [rstudio/rstudio#9844]
The issue tracker is not for questions. If you have a question, please feel free to ask it on our community site, at https://community.rstudio.com/c/rstudio-ide.

**Comment by ronblum** [comment]
@MaheshChellamuthu I'm not sure I understand the issue.
1) Are you able to use R outside of RStudio?
2) If so, what exactly happens within RStudio?
3) Can you please provide the full environment info?
### System details

    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       :

**Comment by MaheshChellamuthu** [comment]
Hi Ronblum,

Thanks for picking up the request. Below are the detailed explanation,

We use Palo Alto TS Agent ( Firewall) agent for firewall rules . It uses the ports from 20000 to 39999 , which interferes with the R ports on the local host. How do we define the set of ports for R to run on a local host. Please let me know if you need more infromation.
 Cheers,
Mahesh

**Comment by ronblum** [comment]
@MaheshChellamuthu Ah! Good question. This repository is actually meant for bugs and enhancements specific to the RStudio IDE. However, I can highly recommend the following:
- [the RStudio Community](https://community.rstudio.com/)
- [the R channel in Stack Overflow](https://stackoverflow.com/questions/tagged/r)

Both of these are good places to see if there are other users who are doing the same thing you, or for posting what you're running into so that others can provide guidance and suggestions.
