### ISSUE TITLE
Increase the number of "recent" projects

### ISSUE THREAD

**Issue by RaymondBalise** [rstudio/rstudio#9849]
Can you please give us the ability to increase the number of "recent" projects that show up under the upper right project menu?  I know I can edit this: ~/.local/share/rstudio/monitored/lists/project_mru file but I teach and each student has their own project.  So, my student's projects fill my recent projects list (and I loose my own work off the bottom).  Adding a global option to control the number of files in the recent list would be ideal but even a parameter that would let me increase the items (to 20) in the configuration files would also work for me.

**Comment by ronblum** [comment]
@RaymondBalise Thank you for the suggestion! We'll consider it as part of our ongoing development of RStudio.

**Comment by colearendt** [comment]
Agree! It is always sad when an oft-used project falls off the "Recent Projects" list!

**Comment by jmcphers** [comment]
This isn't a constant we can tweak since every MRU entry has its own "command":

https://github.com/rstudio/rstudio/blob/e1e10d8665a1472e7ba6419dd5dbe0f036f2169a/src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml#L111-L128

Obviously not _too_ hard to give it a larger, fixed size, but making it possible for users to adjust it on the fly would involve some work to build menus at runtime that are currently baked in at compile time.

**Comment by RaymondBalise** [comment]
Any increase in the number would be a great help.  I know you don't want the pick list to scroll off the bottom of the screen for folks that have a small display but the more you can add the better.

**Comment by aushev** [comment]
I second, please allow user to increase number of MRU items - both for Recent Files and Recent Projects!
