### ISSUE TITLE
Collapsed code chunk in visual editor does not show correct class in shown summary 

### ISSUE THREAD

**Issue by cderv** [rstudio/rstudio#9929]
### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 2021.12.0.91
    OS Version      : Windows 10 x64 (build 19043)
    R Version       : R version 4.1.1 (2021-08-10)

### Steps to reproduce the problem

* Create a new `test.md` document with this content
````markdown
``` yaml
output: 
  html_document: 
    self_contained: false
```
````
* Activate visual mode
* Collapse the chunk using the new feature

### Describe the problem in detail

`R` is shown in the summary instead of YAML which is the class of the code chunk. 

![image](https://user-images.githubusercontent.com/6791940/136360084-92343611-e3dd-452a-a088-b972bed9fcf8.png)
![image](https://user-images.githubusercontent.com/6791940/136360145-2b5f87ad-0273-48f5-8b85-b89f97b7f44f.png)

### Describe the behavior you expected

I would expect to see 

```
> YAML, 3 lines
```

and not R which is puzzling as this chunk as nothing to do with R. It works ok if I add a python code chunk executable in the document, in a RMD for example

````markdown
```{python}
import os
```
````
 
![image](https://user-images.githubusercontent.com/6791940/136360054-49dd3081-8b7c-4b1a-93c4-cac84943252a.png)

![image](https://user-images.githubusercontent.com/6791940/136360024-668d4dcd-f011-4bd3-9c4b-ce036efd0d77.png)

Is this an issue or just that non executable code chunk shouldn't be collapsible ?

**Comment by ronblum** [comment]
1) I can reproduce the original issue with an earlier build (spec. 2022.01.0-daily+272), with non-executable blocks like ```` ``` python ``` ````, as described in the QA notes.
2) This is mostly fixed in
- RStudio Desktop 2022.01.0-daily+295 on MacOS 12.1
- RStudio Server 2022.01.0-daily+295 on Ubuntu 20.04.3 via Safari on MacOS 12.1
3) However, this is still an issue if the code block is empty, e.g.
````
``` python
```
````
returns ![empty_python.png](https://codetreeusercontent.s3.amazonaws.com/uploads/69dbd61a-cdd8-416e-88b6-0842033ab943/empty_python.png)


Tested using an code both as Markdown and R Markdown files:
````
---
title: "Document"
author: "someone"
date: "12/8/2021"
output: html_document
---

```{r}
x <- 1
```

``` r
y <- 23
```

```{r}
```

``` r
```

```{python}
x = 1
```

``` python
y = 23
```

```{python}
```

``` python
```

```{html}
<HR>
```

``` html
<HR>
```

```{html}
```

``` html
```

```{sql}
SELECT 1;
```

``` sql
SELECT 1;
```

```{sql}
```

``` sql
```

```{actionscript}
var x:int = 5;
```

``` actionscript
var x:int = 5;
```

```{actionscript}
```

``` actionscript
```

```{yaml}
output: html_document
```

``` yaml
output: html_document
```

```{yaml}
```

``` yaml
```
````

**Comment by ronblum** [comment]
Verified using the code above in:
- RStudio Desktop 2022.01.0-daily-308 on MacOS 12.1
- RStudio Server 2022.01.0-daily-309 on CentOS 8 via Safari on MacOS 12.1

Note: Discovered #10227 along the way.
