### ISSUE TITLE
avoid over-aggressive setting of RETICULATE_PYTHON

### ISSUE THREAD

**Issue by kevinushey** [rstudio/rstudio#9990]
https://github.com/rstudio/rstudio/issues/9952

This issue tracks RStudio setting `RETICULATE_PYTHON` over-aggressively within RStudio projects where a specific version of Python hasn't been explicitly requested by the user.

---

The underlying issue is that we attempt to pick a "good" default version of Python for the user here:

https://github.com/rstudio/rstudio/blob/1def6347c41fae467f12adebbc2ea68b8287ca11/src/cpp/session/modules/SessionPythonEnvironments.R#L147-L198

And if we find such a version of Python, we try to "activate" it in a way that ensures this will be the version of Python used in all contexts (ie, both the R interpreter and in Terminal sessions).

https://github.com/rstudio/rstudio/blob/1def6347c41fae467f12adebbc2ea68b8287ca11/src/cpp/session/modules/SessionPythonEnvironments.R#L233-L290

The problem here is that we're too aggressive: the selected version of Python here shouldn't override any explicit user requests made via `reticulate` APIs, which is what using `RETICULATE_PYTHON` will do.

One possibility would be to set the `RETICULATE_PYTHON_FALLBACK` environment variable, as used by `reticulate` here:

https://github.com/rstudio/reticulate/blob/3eda565d9d790f3381c170b5739a93e35228a9f7/R/config.R#L219-L228

That way, user-requested copies of Python will have higher precedence than our fallback default. However, with that change, we'd likely need tweak in RStudio to look at both `RETICULATE_PYTHON` and `RETICULATE_PYTHON_FALLBACK`; e.g.

https://github.com/rstudio/rstudio/blob/1def6347c41fae467f12adebbc2ea68b8287ca11/src/cpp/session/modules/SessionReticulate.R#L2056-L2088

A short-term fix is tracked in #9999.

**Comment by t-kalinowski** [comment]
FWIW, I still sometimes have trouble sometimes predicting which python will be found by reticulate. I wonder if this is maybe also an opportunity to refactor `reticulate::use_python(,required=TRUE)` to be mostly a wrapper around `Sys.setenv(RETICULATE_PYTHON=)`.

**Comment by gtritchie** [comment]
Chatted with @kevinushey and he'd like to see the smaller fix he mentions (removing lines 147 to 198) get into a patch release, then a more ambitious fix involving RETICULATE_PYTHON_FALLBACK, presumably in PT or beyond.

**Comment by jgutman** [comment]
QA notes: see [PR description]( https://github.com/rstudio/rstudio/pull/10518#issue-1126382555) for example code and expected outputs.

**Comment by romainfrancois** [comment]
Verified on SW build 160, following description in pull request: 

<img width="439" alt="image" src="https://user-images.githubusercontent.com/2625526/156153151-84c38c50-5f00-422d-8e80-53694189574b.png">

then on another project: 

<img width="438" alt="image" src="https://user-images.githubusercontent.com/2625526/156153453-699becb8-b760-47b8-a08a-9d6b07f897dc.png">

further tests: 

<img width="1103" alt="image" src="https://user-images.githubusercontent.com/2625526/156154086-467c195f-41c1-4ced-83b7-bbb8d6d93061.png">

**Comment by salim-b** [comment]
I did not follow all the issues/PRs related to all the recent Python discovery changes. But I think I've just stumbled upon a **serious regression**:

#### Setup details

- I use `rstudio-2022.06.0-daily-394-amd64` on Ubuntu 22.04
- I have set the environment variable `WORKON_HOME=/home/salim/.by_pkg_mngr/virtualenvwrapper`, then created the virtualenv `r-reticulate` (default name) using `reticulate::virtualenv_create()` and finally installed the Python package `plotly` in it using `reticulate::virtualenv_install(packages = "plotly")`.

#### Problem description

If I open *any* RStudio **project**, trying to discover the proper python location fails:

```
> reticulate::py_discover_config(required_module = "plotly")
python:         /usr/bin/python3
libpython:      /usr/lib/python3.10/config-3.10-x86_64-linux-gnu/libpython3.10.so
pythonhome:     //usr://usr
version:        3.10.4 (main, Apr  2 2022, 09:04:19) [GCC 11.2.0]
numpy:          /usr/lib/python3/dist-packages/numpy
numpy_version:  1.21.5
plotly:         [NOT FOUND]

NOTE: Python version was forced by RETICULATE_PYTHON_FALLBACK
```

But when I open an RStudio session that is not associated with a project, my virtualenv `r-reticulate` is properly detected:

```
> reticulate::py_discover_config(required_module = "plotly")
python:         /home/salim/.by_pkg_mngr/virtualenvwrapper/r-reticulate/bin/python
libpython:      /usr/lib/python3.10/config-3.10-x86_64-linux-gnu/libpython3.10.so
pythonhome:     /home/salim/.by_pkg_mngr/virtualenvwrapper/r-reticulate:/home/salim/.by_pkg_mngr/virtualenvwrapper/r-reticulate
version:        3.10.4 (main, Apr  2 2022, 09:04:19) [GCC 11.2.0]
numpy:          /home/salim/.by_pkg_mngr/virtualenvwrapper/r-reticulate/lib/python3.10/site-packages/numpy
numpy_version:  1.22.3
plotly:         /home/salim/.by_pkg_mngr/virtualenvwrapper/r-reticulate/lib/python3.10/site-packages/plotly

python versions found: 
 /home/salim/.by_pkg_mngr/virtualenvwrapper/r-reticulate/bin/python
 /usr/bin/python3
```

This looks like a clear regression to me since the same reticulate setup on stable RStudio 2022.02.2+485 on Ubuntu 20.04 detects the virtualenv in both cases. My guess would be that this regression was introduced with https://github.com/rstudio/rstudio/pull/10518, thus pinging @kevinushey @jgutman

**Comment by jgutman** [comment]
Thanks @salim-b ! I will look into this shortly, and I've reported it as a new issue so we can track it.

**Comment by jgutman** [comment]
Hi @salim-b, I am not entirely sure this is not intended behavior. In this case, because you have not provided reticulate with any information about which Python version or virtual environment you want to use, it tries to guess. Since you are using a virtual environment, we are not able to guess automatically that that is the intended version of Python you would like to use. 

There are two clear workarounds:
1. In Global Options > Python, uncheck the box for "Automatically activate project-local Python environments". This is what controls whether or not RStudio will attempt to infer what version of Python you are using when you activate a project. When you uncheck this box, your project session will behave in the same way as your non-project session
2. Instead of, or in addition to suggestion 1, you can explicitly tell reticulate you want to use your virtual environment by using `reticulate::use_virtualenv("r-reticulate")` and then when you run `reticulate::py_discover_config("plotly")` you will get the desired result
<img width="845" alt="image" src="https://user-images.githubusercontent.com/7817881/168615788-99fe6a39-5762-4e77-8350-19c9af142b75.png">

Therefore, while this is a change in behavior introduced with the PR you pointed to, it is not entirely unintended or considered a regression. When you use "Automatically activate project-local Python environments" and you do not explicitly set your project Python version, RStudio does its best to guess which Python you want, and sets that Python to `RETICULATE_PYTHON_FALLBACK`; however there is no way to consistently infer correctly which Python/virtual environment the user might want at any given time -- the way to guarantee that is to follow the suggestions above.

**Comment by kevinushey** [comment]
> Therefore, while this is a change in behavior introduced with the PR you pointed to, it is not entirely unintended or considered a regression. When you use "Automatically activate project-local Python environments" and you do not explicitly set your project Python version, RStudio does its best to guess which Python you want

If this preference is set, but the project doesn't have any project-local virtual environment set up, then I think the behavior should be the same as if the user weren't in a project at all. (That is, it should match the default `reticulate` behavior).

Do you know how hard this would be to handle? I think there's a large number of RStudio + reticulate users who rely on reticulate's default behavior of looking for a virtual environment called `r-reticulate` in `WORKON_HOME`, and using that rather than a "system" Python.

(The solution here might be to just check if `reticulate` is installed, and then ask `reticulate::py_discover_config()` what version of Python RStudio should try to use.)

**Comment by jgutman** [comment]
> large number of RStudio + reticulate users who rely on reticulate's default behavior of looking for a virtual environment called r-reticulate in WORKON_HOME

Okay. if that's a common thing, then I think we probably can change the position of that in the hierarchy so that gets inferred earlier when trying to infer what Python to use. I don't think we have special handling for that now, but that probably shouldn't be hard, would that be a good solution?

**Comment by kevinushey** [comment]
I think so; at least, for this particular case (since the `r-reticulate` environment is "special").

**Comment by salim-b** [comment]
Thanks for the detailed answer @jgutman. I agree with @kevinushey that 

> If this preference is set, but the project doesn't have any project-local virtual environment set up, then I think the behavior should be the same as if the user weren't in a project at all. (That is, it should match the default reticulate behavior).

It would simply be more intuitive for "non-insiders", I guess :)

**Comment by jonvanausdeln** [comment]
This looks to be working on MacOS and Linux.. but not on Windows.

**Comment by jonvanausdeln** [comment]
Verified on 2022.11.0-78, Windows11, MacOS, Ubuntu 22.04

The windows issue above is due to installing Python via Microsoft Store instead of directly form python.org.  That will be opened as a separate issue.

Tested as described in PR and with various virtual envs.
